### ISSUE TITLE
How to set initial value and how to get Html text?

### ISSUE THREAD

**Issue by LaTrita97** [singerdmx/flutter-quill#1]
Hi, I've installed this plugin and I want to know two things:

- How I set an initial value to QuillController?
- How to get Html code from QuillController?

Best regards, thank you.

**Comment by singerdmx** [comment]
`How I set an initial value to QuillController?`

Check out https://github.com/singerdmx/flutter-quill/blob/master/app/lib/pages/home_page.dart#L33

**Comment by singerdmx** [comment]
`How to get Html code from QuillController?`

Why do you need that?
HTML is only used by web. For web development, ReactQuill https://github.com/zenoamaro/react-quill  is recommended to use for compatibility.
If you use our app https://bulletjournal.us/home/index.html, the way we solve it is to only use **delta** for data between mobile and web. HTML is actually not needed for mobile side. At web side, we use ReactQuill https://github.com/zenoamaro/react-quill to generate html. 
Bullet Journal app is open sourced at https://bulletjournal.us/home/index.html https://github.com/singerdmx/BulletJournal

**Comment by LaTrita97** [comment]
Thanks for your help

**Comment by nikolabrdaroski** [comment]
> Hi, I've installed this plugin and I want to know two things:
> 
>     * How I set an initial value to QuillController?
> 
>     * How to get Html code from QuillController?
> 
> 
> Best regards, thank you.

@LaTrita97 have you found some solution about this?

**Comment by singerdmx** [comment]
@nikolabrdaroski  This issue is resolved already. What is missing that you still need help with?
What questions do you have?

**Comment by singerdmx** [comment]
@nikolabrdaroski @LaTrita97  I recommend you just use pub https://pub.dev/packages/flutter_quill for this.

**Comment by nikolabrdaroski** [comment]
@singerdmx 

Yes, I already tried that.

But I have html as input to be shown in the editor, and then I need to get html as output to send further.

That is why I asked if there is possibility for html input/output.

**Comment by singerdmx** [comment]
Oh, now I understand your question.
No, our contact for this library is delta. HTML is not considered here by any mean.
You may want to check out if there is any library does the conversion between HTML and delta.

**Comment by singerdmx** [comment]
Check out https://github.com/ArjanAswal/quill_markdown @nikolabrdaroski @LaTrita97

**Comment by dsyrstad** [comment]
@LaTrita97 To get HTML, https://pub.dev/packages/vsc_quill_delta_to_html provides a robust delta to HTML conversion.

**Comment by mariam992001** [comment]
> `How I set an initial value to QuillController?`
> 
> Check out https://github.com/singerdmx/flutter-quill/blob/master/app/lib/pages/home_page.dart#L33

Hi, what is the solve of this problem ? 
I try to show the Html code in the QuillEditor as initial value , as Html Runner
