### ISSUE TITLE
[web] Cursor error when click bold

### ISSUE THREAD

**Issue by artemsivcev** [singerdmx/flutter-quill#10]
Hello! I'm using your plugin on web and I found some bug. 
v.0.2.2 (last for now).
1. Type some text. Cursor must be at end of text
2. Select bold, italic, etc...
Expected result:
3. Cursor still at the end and next text become bold, italic, etc
Actual result:
3. Cursor move at start of text but next typed text become bold, italic, etc and its position right on the end
4. And after that there is some strange behaviour about delete some letters, some times delete button delete 2 or more letters...

<img width="416" alt="Screenshot 2021-01-29 at 09 35 49" src="https://user-images.githubusercontent.com/5911567/106251537-24c37280-6226-11eb-8c58-4c389f04f921.png">

**Comment by singerdmx** [comment]
For web development, ReactQuill https://github.com/zenoamaro/react-quill is recommended to use for compatibility.
If you use our app https://bulletjournal.us/home/index.html, the way we solve it is to only use delta for data between mobile and web. HTML is actually not needed for mobile side. At web side, we use ReactQuill https://github.com/zenoamaro/react-quill to generate html.
Bullet Journal app https://bulletjournal.us/home/index.html is open sourced at https://github.com/singerdmx/BulletJournal

**Comment by singerdmx** [comment]
@artemsivcev As mentioned in the README, this library has no intention of supporting web. ReactQuill https://github.com/zenoamaro/react-quill is recommended for web development.
Note that our underlying data format is 100% compatible with quill delta.

**Comment by singerdmx** [comment]
Closing
