### ISSUE TITLE
[Desktop] Opening local image on Linux truncates image file on disk to zero.

### ISSUE THREAD

**Issue by true2thepen** [singerdmx/flutter-quill#1000]
My issue is about [Desktop]

I have tried running `example` directory unsuccessfully before creating an issue here. 

Opening any image in example app on Linux instantly truncates file on disk destroying image file.

**Comment by freshtechtips** [comment]
Thank you for the report. I know I'm a little bit late but we will look into that!!

**Comment by CatHood0** [comment]
@true2thepen does this issue still persists?

**Comment by EchoEllet** [comment]
This seems to be no longer an issue.
