### ISSUE TITLE
[Mobile]  undo  exception 

### ISSUE THREAD

**Issue by demoYang** [singerdmx/flutter-quill#1005]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here. 

Please note that we are using <b>latest</b> flutter version in stable channel on branch master. If you are using beta or master channel, or you are not using <b>latest</b> flutter version in stable channel, you may experience error.

Flutter version 3.3.7
flutter_quil : 6.1.4

undo  wiil make exception, Chinese input not support well ,and the cursor location not right  when undo

https://user-images.githubusercontent.com/7134823/201251110-83132ed9-b857-4887-ac07-2dff885a668b.mp4

**Comment by demoYang** [comment]
any update

**Comment by singerdmx** [comment]
Will take a look

**Comment by demoYang** [comment]
```
 HistoryChanged _change(Document doc, List<Delta> source, List<Delta> dest) {
    if (source.isEmpty) {
      return const HistoryChanged(false, 0);
    }
    final delta = source.removeLast();
    // look for insert or delete
    int len = 0;
    var offset = 0;
    final ops = delta.toList();
    for (var i = 0; i < ops.length; i++) {
      if (ops[i].key == Operation.insertKey) {
        len = len + (ops[i].length ?? 0);
        if (offset != 0) {
          offset = offset + (ops[i].length ?? 0);
        }
      } else if (ops[i].key == Operation.deleteKey) {
        len = len - (ops[i].length ?? 0);
      } else if (ops[i].key == Operation.retainKey) {
        offset = ops[i].length ?? 0;
      }
    }
    final base = Delta.from(doc.toDelta());
    final inverseDelta = delta.invert(base);
    dest.add(inverseDelta);
    lastRecorded = 0;
    ignoreChange = true;
    doc.compose(delta, ChangeSource.LOCAL);
    ignoreChange = false;
    return HistoryChanged(true, len);
  }
```

may be work

**Comment by demoYang** [comment]
https://github.com/singerdmx/flutter-quill/assets/7134823/a6c74eff-73a7-4864-b7e0-5957759213e7

**Comment by demoYang** [comment]
<img width="733" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/7134823/f824d277-6bc3-48c1-845e-639ef9de882a">

maybe work

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
