### ISSUE TITLE
[Mobile] InlineStyle background is not being applied

### ISSUE THREAD

**Issue by JCKodel** [singerdmx/flutter-quill#1014]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/379339/204353578-b0cc84d7-70f9-422e-a455-2d870dbdc226.png">

This image shows a Code block followed by an inline code. Both has the same styles, but the background color of inline code is not applied (even if I set it to `Color.red`).

**Comment by adil192** [comment]
I'm experiencing this too. I'll be setting the text color to black for the time being in [adil192/saber](https://github.com/adil192/saber)

**Comment by adil192** [comment]
I'm still experiencing this issue on 8.3.0. Did you mean to close this issue?

**Comment by freshtechtips** [comment]
> I'm still experiencing this issue on 8.3.0. Did you mean to close this issue?

Hi, I didn't check it since there were more than 170  issues

So I closed the old issues since it's not applicable anymore 

There are no interactions with it

**Comment by freshtechtips** [comment]
> `InlineCodeStyle.backgroundColor` does nothing, but `InlineCodeStyle.style.backgroundColor` works. We might need to remove `InlineCodeStyle.backgroundColor` or fix it.
> 
> ```dart
> inlineCode: InlineCodeStyle(
>   backgroundColor: Colors.red, // does nothing
>   style: GoogleFonts
> ```

Reopened.

**Comment by freshtechtips** [comment]
> I'm still experiencing this issue on 8.3.0. Did you mean to close this issue?

Reopened.
