### ISSUE TITLE
Formatting removed on pasting formatted copied text

### ISSUE THREAD

**Issue by pramod51** [singerdmx/flutter-quill#1018]
I have implemented for web.
When i paste any formatted text it remove all formatting and hyper links. Please help me.
you can try from [this](https://en.wikipedia.org/wiki/Main_Page)page content

**Comment by NExPlain** [comment]
Same problem here, is there any quick fix to support pasting at least bullet points/list?

**Comment by Ibtesam-Mahmood** [comment]
Same here, just copies the plain text

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
