### ISSUE TITLE
device_info_plus  version 

### ISSUE THREAD

**Issue by cgzcgb** [singerdmx/flutter-quill#1019]
Running "flutter pub get" in nnbq...                            
Because upgrader >=5.0.0-alpha.1 depends on device_info_plus ^8.0.0 and flutter_quill 6.1.6 depends on device_info_plus ^7.0.0, upgrader >=5.0.0-alpha.1 is incompatible with flutter_quill 6.1.6.
And because no versions of flutter_quill match >6.1.6 <7.0.0, upgrader >=5.0.0-alpha.1 is incompatible with flutter_quill ^6.1.6.
So, because nnbq depends on both flutter_quill ^6.1.6 and upgrader ^5.0.0, version solving failed.
pub get failed (1; So, because nnbq depends on both flutter_quill ^6.1.6 and upgrader ^5.0.0, version solving failed.)
Process finished with exit code 1

**Comment by SmirnovM91** [comment]
+1

**Comment by singerdmx** [comment]
Done
