### ISSUE TITLE
[Mobile] Error when clicking on "Open" in the BottomSheet of a link.

### ISSUE THREAD

**Issue by tschiekdev** [singerdmx/flutter-quill#1021]
If you open the BottomSheet with a long press on a link and the keyboard may have been open before, you get the following error when you tap "Open".

`The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      StatefulElement.state (package:flutter/src/widgets/framework.dart:4999:44)
#1      Navigator.of (package:flutter/src/widgets/navigator.dart:2543:47)
#2      _showMaterialMenu.<anonymous closure>.<anonymous closure> (package:flutter_quill/src/widgets/link.dart:171:40)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#16     _invoke1 (dart:ui/hooks.dart:167:13)
#17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#054e2
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(133.8, 642.2)
  finalLocalPosition: Offset(133.8, 18.9)
  button: 1
  sent tap down`

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
