### ISSUE TITLE
how to make connect between toolbar button and embed 

### ISSUE THREAD

**Issue by troy0632** [singerdmx/flutter-quill#1025]
My issue is custom button only ontap, can not like the toolbar button edit content;
My issue is about [Mobile]

**Comment by freshtechtips** [comment]
It can, please use the quill controller

Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
