### ISSUE TITLE
[Mobile] When I add image in quill editor using base64 then release app show grey screen

### ISSUE THREAD

**Issue by YoonKyeongho** [singerdmx/flutter-quill#1027]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here. 

If you check by building in release mode, the screen is grayed out.
This issue occurs on both android and iOS.

If you search for this issue, you will find the following answers.
https://stackoverflow.com/questions/68558184/when-i-add-image-in-quill-editor-using-base64-then-release-app-show-grey-screen

In fact, if you do it in the following way, it will output normally.
Please check why this issue is occurring.

**Comment by kingmaster772** [comment]
I have the same issue. It looks like because this error on `flutter_quill-4.2.3\lib\src\widgets\text_line.dart`

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'RenderErrorBox' is not a subtype of type 'RenderContentProxyBox?' in type cast. Error thrown Instance of 'ErrorDescription'.
       at _TextLineElement._updateRenderObject(text_line.dart:1243)
       at _TextLineElement.insertRenderObjectChild(text_line.dart:1208)
       at RenderObjectElement.attachRenderObject(framework.dart:5958)
       at RenderObjectElement.mount(framework.dart:5635)
```

**Comment by RamiHI** [comment]
I had the same error and didn't get a solution

**Comment by freshtechtips** [comment]
This issue should be fixed in the newer versions.

Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
