### ISSUE TITLE
Repeat 2 ol list

### ISSUE THREAD

**Issue by mny459** [singerdmx/flutter-quill#1031]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here. 

As screenshot below, there are repeat 2 when I insert a indent between 1 an 2

![image](https://user-images.githubusercontent.com/24559456/209419179-e2abc922-ab76-4f20-b5c2-b36bcd022664.png)

**Comment by spChief** [comment]
![simulator_screenshot_FC266EA9-7832-40CF-B9D1-AAD852998F26](https://user-images.githubusercontent.com/5066552/227834514-02e5ad1e-4a1c-41b1-8466-21f525a4c85a.png)
Same here, I created PR #1142 with fix
