### ISSUE TITLE
Show scrollbar for editor [Mobile] 

### ISSUE THREAD

**Issue by thanhdatvo** [singerdmx/flutter-quill#1037]
My issue is about [Mobile]
Hi, 
Scrollbar is one of signifiers to tell user that they can scroll in this area and about current scroll position.
How could I add scroll bar to quill editor?

 Thank you,

**Comment by freshtechtips** [comment]
You can show it using

```dart

Scrollbar(
child: QuillEditor()
)

```

Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
