### ISSUE TITLE
Cursor is still showing in read only mode [Mobile]

### ISSUE THREAD

**Issue by Itz-Shubham** [singerdmx/flutter-quill#1043]
![1669123680468](https://user-images.githubusercontent.com/67543467/210171696-ff4df62d-b48b-4713-be1c-63289cdb9311.jpg)

How to get rid of it? 🙂

**Comment by codemaster-mo** [comment]
You have to create the quill editor yourself and pass the properties, see example below. 

```
QuillEditor(
                          controller: controller.quillController,
                          scrollController: ScrollController(),
                          scrollable: true,
                          focusNode: FocusNode(),
                          autoFocus: true,
                          enableInteractiveSelection: controller.isEditEnabled,
                          enableSelectionToolbar: controller.isEditEnabled,
                          readOnly: !controller.isEditEnabled,
                          expands: false,
                          **showCursor: controller.isEditEnabled,**
                          padding: EdgeInsets.zero,
                          keyboardAppearance: Brightness.light
)
```

**Comment by Itz-Shubham** [comment]
> You have to create the quill editor yourself and pass the properties, see example below.
> 
> ```
> QuillEditor(
>                           controller: controller.quillController,
>                           scrollController: ScrollController(),
>                           scrollable: true,
>                           focusNode: FocusNode(),
>                           autoFocus: true,
>                           enableInteractiveSelection: controller.isEditEnabled,
>                           enableSelectionToolbar: controller.isEditEnabled,
>                           readOnly: !controller.isEditEnabled,
>                           expands: false,
>                           **showCursor: controller.isEditEnabled,**
>                           padding: EdgeInsets.zero,
>                           keyboardAppearance: Brightness.light
> )
> ```

Nope! It still showing the cursor... here is the code 

```
  QuillEditor(
    controller: QuillController(
      document: Document.fromJson(
        jsonDecode(snapashot.data!.description),
      ),
      selection: const TextSelection.collapsed(offset: 0),    // That was necessary that's why
    ),
    scrollable: false,
    scrollController: ScrollController(),
    focusNode: FocusNode(),
    autoFocus: true,
    enableInteractiveSelection: false,
    enableSelectionToolbar: false,
    readOnly: true,
    expands: false,
    // **showCursor: controller.isEditEnabled,**
    padding: EdgeInsets.zero,
  ),
```


My previous code was like this...

```
  Padding(
    padding: const EdgeInsets.all(8),
    child: QuillEditor.basic(
      controller: QuillController(
        document: Document.fromJson(
          jsonDecode(snapashot.data!.description),
        ),
        selection: const TextSelection.collapsed(offset: -1),
      ),
      readOnly: true,
    ),
  ),
```

**Comment by Itz-Shubham** [comment]
By doing this I am able to hide the cursor until user not click on the text, **but it showing errors** 

`selection: const TextSelection.collapsed(offset: -1),`

**Comment by liu1009xf** [comment]
I think you have accidentally commented out the line where it says `showCursor = controller.isEditEnabled`, which is literally the argument that controls if you want to show cursor and it is default to true if showCursor is not given, that's why you still seeing the cursor. 

> > You have to create the quill editor yourself and pass the properties, see example below.
> > ```
> > QuillEditor(
> >                           controller: controller.quillController,
> >                           scrollController: ScrollController(),
> >                           scrollable: true,
> >                           focusNode: FocusNode(),
> >                           autoFocus: true,
> >                           enableInteractiveSelection: controller.isEditEnabled,
> >                           enableSelectionToolbar: controller.isEditEnabled,
> >                           readOnly: !controller.isEditEnabled,
> >                           expands: false,
> >                           **showCursor: controller.isEditEnabled,**
> >                           padding: EdgeInsets.zero,
> >                           keyboardAppearance: Brightness.light
> > )
> > ```
> 
> Nope! It still showing the cursor... here is the code
> 
> ```
>   QuillEditor(
>     controller: QuillController(
>       document: Document.fromJson(
>         jsonDecode(snapashot.data!.description),
>       ),
>       selection: const TextSelection.collapsed(offset: 0),    // That was necessary that's why
>     ),
>     scrollable: false,
>     scrollController: ScrollController(),
>     focusNode: FocusNode(),
>     autoFocus: true,
>     enableInteractiveSelection: false,
>     enableSelectionToolbar: false,
>     readOnly: true,
>     expands: false,
>     // **showCursor: controller.isEditEnabled,**
>     padding: EdgeInsets.zero,
>   ),
> ```
> 
> My previous code was like this...
> 
> ```
>   Padding(
>     padding: const EdgeInsets.all(8),
>     child: QuillEditor.basic(
>       controller: QuillController(
>         document: Document.fromJson(
>           jsonDecode(snapashot.data!.description),
>         ),
>         selection: const TextSelection.collapsed(offset: -1),
>       ),
>       readOnly: true,
>     ),
>   ),
> ```
