### ISSUE TITLE
[Web], [Mobile], [Desktop] - Unable to insert link mailto and tel

### ISSUE THREAD

**Issue by tomotoshi3** [singerdmx/flutter-quill#1048]
My issue is about all platforms.

I have tried running `example` directory successfully before creating an issue here. 

When you want to add link - dialog with text and link input fields is opened. But, validation on the link field allows only http urls. It would be nice to have mailto and tel links also. In fact, in earlier versions of this lib this was possible.

**Comment by freshtechtips** [comment]
> My issue is about all platforms.
> 
> I have tried running `example` directory successfully before creating an issue here.
> 
> When you want to add link - dialog with text and link input fields is opened. But, validation on the link field allows only http urls. It would be nice to have mailto and tel links also. In fact, in earlier versions of this lib this was possible.

Thank you for bringing that to our attention!!
we will work on that

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
