### ISSUE TITLE
[Desktop] How to resize images ?

### ISSUE THREAD

**Issue by tolotrasamuel** [singerdmx/flutter-quill#1051]
I do not find the feature to resize images on Flutter Mac desktop. Is this supported yet? If so, how to enable it ? 
The image seems huge 

<img width="1680" alt="Screen Shot 2023-01-06 at 7 45 41 PM" src="https://user-images.githubusercontent.com/29230303/211122958-aca25752-be0c-46e1-b822-97b04abe07d7.png">

**Comment by singerdmx** [comment]
no
Mobile only

**Comment by Mooyeee** [comment]
Will it come to desktop aswell?

**Comment by vd3d** [comment]
I also need this, an image with the possibility to resize it is just useless :-(
Resizing and moving an image is really a must-have feature... please don't forget desktop developers ;-)

Is there any plan to implement this?

**Comment by vd3d** [comment]
I've just noticed that @singerdmx is currently working on the image resize feature, if my understanding is correct (I hope so).
See here: https://github.com/singerdmx/flutter-quill/issues/644

**Comment by freshtechtips** [comment]
> Will it come to desktop aswell?

We have added an image resizing feature to the desktop as well!! but web is currently not supported

This issue has been fixed, if you still facing this issue or any others, feel free to contact us on GitHub
