### ISSUE TITLE
[Mobile] [Web] [Desktop] Align numerical list and bullet points with text content

### ISSUE THREAD

**Issue by Dnathan33** [singerdmx/flutter-quill#1053]
My issue is about [Web] [Mobile] [Desktop]

When aligning a text today with numerical or bullet points applied, the text is aligned however, the numerical or bullet contents are not.

See screenshot below

![Simulator Screen Shot - iPhone 13 - 2023-01-10 at 09 54 40](https://user-images.githubusercontent.com/39175434/211584273-129c8614-765f-477f-8f1a-a0c64e9f71a8.png)

**Comment by Dnathan33** [comment]
#1054 solves this issue

**Comment by AndreVicenteW** [comment]
For me this error still happens in version 7.4.9

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.

**Comment by freshtechtips** [comment]
> For me this error still happens in version 7.4.9. Is there anything else I should do?

Hi, if you still facing this issue please create a new issue
