### ISSUE TITLE
[Mobile] 6.2.0 cursor is misaligned by one character on iOS and Android

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1057]
Cursor caret is behind the last inputted character by one character space on the latest 6.2.0 version on iOS and Android

6.1.12 is OK

**Comment by singerdmx** [comment]
I will revert https://github.com/singerdmx/flutter-quill/commit/1c5177953ff8687c1283578c258c75de023c6aff
This causes regression

**Comment by singerdmx** [comment]
Reverted at https://github.com/singerdmx/flutter-quill/commit/7e14392cc6ca28344168dab01d0e1304e2c600d2
