### ISSUE TITLE
 [Mobile] Insert HTML code or convert HTML to Delta

### ISSUE THREAD

**Issue by vzdorrr** [singerdmx/flutter-quill#1058]
How to insert HTML string from server to flutter_quill editor or convert HTML to Delta? Maybe is it unable thing... Thanks for any answers!

**Comment by hoangsang17th** [comment]
Currently, The best solution is to use another package that supported set the HTML and getting the delta 1 pure way. You can try using Quill HTML Editor to set HTML and then get Delta from it, but it is a temporary solution because the performance by it

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
