### ISSUE TITLE
Migration from zefyr, notus, quill_delta

### ISSUE THREAD

**Issue by VladimirMitso** [singerdmx/flutter-quill#106]
Previously I was using these three packages in my app: `zefyr`, `notus`, `quill_delta`. Users were able to make notes and save them in database. Then I upgraded project to Flutter 2.0 and realised that `zefyr 0.12.0` is not working any more, there is no new versions and nobody accepts PRs from other developers. In `zefyr` issues I found this package. And as I understand document, delta and other tools are in one package now. But my code is not working because attributes are different. For example in `notus` bold was `b` and here it is `bold`. And I already have database filled with this kind of data:
```
[
  {"insert":"BOLD","attributes":{"b":true}},
  {"insert":"ITALIC","attributes":{"i":true}},
  {"insert":"H3,"attributes":{"heading":3}},
  {"insert":"H2","attributes":{"heading":2}},
  {"insert":"H1","attributes":{"heading":1}},
]
```
So now I need converter to migrate from old attributes to new attributes. @singerdmx I saw at least few your messages in `zefyr` issues that developers can use your package. Do you have this converter? Or do you know some easy way to implement it?

![Screenshot 2021-03-24 at 10 22 13](https://user-images.githubusercontent.com/31623922/112278650-bb8f3700-8c8b-11eb-91bc-6ff0c4e151c5.png)

**Comment by singerdmx** [comment]
Check our slack channel

**Comment by singerdmx** [comment]
There is a google doc in pinned topic

**Comment by VladimirMitso** [comment]
Table with differences? Okay, and what is next? I still need to implement converter?

**Comment by VladimirMitso** [comment]
Or you are talking about different document?

**Comment by singerdmx** [comment]
Ask who wrote the doc

**Comment by singerdmx** [comment]
https://bulletjournal1024.slack.com/archives/CTDTAAMEX/p1614786061002200

**Comment by VladimirMitso** [comment]
As I understand there is no working solution. Maybe you can include one when it will be ready. But as for now migration will not be so fast. Thank you.

**Comment by ArjanAswal** [comment]
@VladimirMitso Try this
![Screenshot_2021-03-25-00-13-19-723_com.github.android~2.jpg](https://user-images.githubusercontent.com/64231789/112366709-2594f400-8cff-11eb-85fe-68b2cc1148d2.jpg)
