### ISSUE TITLE
[Mobile] Dependency conflict issues with `i18n_extension: ^6.0.0`

### ISSUE THREAD

**Issue by Dnathan33** [singerdmx/flutter-quill#1064]
My issue is about [Mobile]

We are having dependency conflict issues with `i18n_extension: ^6.0.0`. This is causing a conflict with `sprintf: ^6.0.0` on our end, which in turn causes us to downgrade `analyzer` to version `5.3.0`, which then does not allow us to run `flutter packages pub run build_runner build --delete-conflicting-outputs`.

Downgrading `i18n_extension` to  `^5.0.1` resolves all this issue.

Flutter Version: 3.3.10

**Comment by veselv2010** [comment]
Try bumping `sprintf`

**Comment by Dnathan33** [comment]
Yes, so we did that and that was what was causing an issue with analyzer.
