### ISSUE TITLE
[Mobile] Override Image ErrorBuilder

### ISSUE THREAD

**Issue by WesselvanDam** [singerdmx/flutter-quill#1065]
Noticed this on Mobile, but probably applies in a similar fashion to Web and Desktop as well. 

When using a `QuillEditor` with a document that contains a NetworkImage,  the current ErrorBuilder that is shown on an error (in my case, not having an internet connection) is rather basic, featuring a red box and cross:

![image](https://user-images.githubusercontent.com/43265483/213810872-bea0dbe9-0e4c-458c-8fef-d744e4f0d1a9.png)

Is there a way to override this ErrorBuilder? If not, I think it would be a nice feature to have. I can imagine the `embedBuilders` play a role here, but I don't see how to override the errorBuilder specifically. 

My pubspec contains:
``` 
flutter_quill: ^6.2.2
flutter_quill_extensions: ^0.1.0
```

**Comment by freshtechtips** [comment]
Thank you for the report, This is already done in the latest version
