### ISSUE TITLE
Arrow and backspace keys not working

### ISSUE THREAD

**Issue by matthiasn** [singerdmx/flutter-quill#1069]
My issue is about [Desktop]

After upgrading to Flutter 3.7 and `flutter_quill: ^6.3.0`, I cannot move the cursor with the arrow keys any longer, nor delete text with the backspace key. Typing works.

**Comment by bynicodevelop** [comment]
Same probleme

**Comment by mcdanyl** [comment]
I have the same problem

**Comment by matthiasn** [comment]
@singerdmx do you have any ideas for workarounds, or a fix? Totally blocked right now. Thanks a lot 🙏

**Comment by singerdmx** [comment]
Sorry I don't have time to look

**Comment by singerdmx** [comment]
Sorry I am totally occupied by things in my work and life.
Really busy these days and don’t have time to look.

**Comment by singerdmx** [comment]
I

**Comment by singerdmx** [comment]
I will take a look when things are less busy for me.

**Comment by matthiasn** [comment]
Thanks 🙏

**Comment by htoopyaelinn56** [comment]
works fine on window but same issue on mac

**Comment by ericmartineau** [comment]
I put a PR up for this:

https://github.com/singerdmx/flutter-quill/pull/1089

**Comment by matthiasn** [comment]
@ericmartineau thanks a bunch, I can confirm that this issue is resolved for me.

**Comment by singerdmx** [comment]
@ericmartineau  Thanks!
