### ISSUE TITLE
 [Mobile] ios  The cursor cannot focus until the last character

### ISSUE THREAD

**Issue by dt-wonder** [singerdmx/flutter-quill#1074]
[Mobile]
flutter 3.7
flutter_quill 6.3.1

The cursor cannot focus until the last character 

Ios has this problem, android doesn't have it, it's in Chinese, and it doesn't have it in English

**Comment by nrikiji** [comment]
me too...

**Comment by im-x** [comment]
me too...

**Comment by dt-wonder** [comment]
@singerdmx

**Comment by CatHood0** [comment]
Does this issue still persists? I think this was fixed since was mentioned into a PR. I will close it by the moment. Please reopen if the issues can be reproduced into the current version of the package.
