### ISSUE TITLE
[Desktop] Set font family, when using dynamic fonts loading

### ISSUE THREAD

**Issue by vd3d** [singerdmx/flutter-quill#1080]
My issue is about [Desktop]

I'm trying to use a set of Google Fonts and apply them to the current selection.

I have installed the package : https://pub.dev/packages/google_fonts
This package loads the fonts dynamically and save them locally.

All these fonts are there and I do not want to add them to the assets folder.

It seems that the Quill component is not able to use such fonts, do you think if there is a way ?

If you have any idea to help me, you're highly welcome :-)

Thanks

**Comment by vd3d** [comment]
Just for information, I'm searching and doing some test, so

1 - In my application I have added the toolbar for testing, it does not change the font family.
2 - I have try your sample, and there it works fine.

So, there is something different... but what, I have no idea. I'm currently searching for a difference but honestly, it is not that easy.

**Comment by WillianSalceda** [comment]
Any updates on this?

Currently having the same problem on mobile.

**Comment by frk0708** [comment]
Same here,I want to use google_fonts for the selected text in editor instead of storing the fonts in asset.is there any way to achieve this?

**Comment by ellet0** [comment]
Please take a look at the [https://github.com/singerdmx/flutter-quill/blob/master/example%2Flib%2Fscreens%2Fquill%2Fmy_quill_toolbar.dart](example)

We already covered that

**Comment by frk0708** [comment]
it working as expected.Thank you.
