### ISSUE TITLE
Project build error after adding the package: Android

### ISSUE THREAD

**Issue by singhayush20** [singerdmx/flutter-quill#1083]
I am building a mobile application and want to use this package.
Project SDK versions-
**minSdkVersion 30
targetSdkVersion 33
compileSdkVersion 33**
I am running the app on a **Android 12 device**
Pre-existing packages in my project-
`cupertino_icons: ^1.0.2  
  shared_preferences: ^2.0.17  
  provider: ^6.0.5  
  google_fonts: ^4.0.1  
  get: ^4.6.5    
  sizer: ^2.0.15  
  cached_network_image: ^3.2.3  
  dio: ^4.0.6  
  loading_indicator: ^3.1.0  
  image_picker: ^0.8.6+1  
  loader_overlay: ^2.1.0  
  font_awesome_flutter: ^10.3.0  
  email_validator: ^2.1.17  
  settings_ui: ^2.0.2`  

I ran the following command to add the package-
`flutter pub add flutter_quill`

After the dependency was added I tried to build my project and got the following errors-

`Launching lib\main.dart on SM M215F in debug mode...
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/toolbar/quill_font_size_button.dart:113:41: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
- 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/D:/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try accessing using ?. instead.
    final overlay = Overlay.of(context).context.findRenderObject() as RenderBox;
                                        ^^^^^^^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/toolbar/quill_font_family_button.dart:112:41: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
- 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/D:/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try accessing using ?. instead.
    final overlay = Overlay.of(context).context.findRenderObject() as RenderBox;
                                        ^^^^^^^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:87:61: Error: The argument type 'OverlayState?' can't be assigned to the parameter type 'TickerProvider' because 'OverlayState?' is nullable and 'TickerProvider' isn't.
- 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/D:/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/overlay.dart').
- 'TickerProvider' is from 'package:flutter/src/scheduler/ticker.dart' ('/D:/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/scheduler/ticker.dart').
        duration: const Duration(milliseconds: 150), vsync: overlay);
                                                            ^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:225:10: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
- 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/D:/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try calling using ?. instead.
        .insert(toolbar!);
         ^^^^^^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:316:10: Error: 'TextSelectionPoint' isn't a type.
    List<TextSelectionPoint> endpoints;
         ^^^^^^^^^^^^^^^^^^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:410:10: Error: Method 'insertAll' cannot be called on 'OverlayState?' because it is potentially null.
- 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/D:/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try calling using ?. instead.
        .insertAll(_handles!);
         ^^^^^^^^^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:7: Error: Type 'TextInputControl' not found.
      TextInputControl? oldControl, TextInputControl? newControl) {
      ^^^^^^^^^^^^^^^^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:37: Error: Type 'TextInputControl' not found.
      TextInputControl? oldControl, TextInputControl? newControl) {
                                    ^^^^^^^^^^^^^^^^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:7: Error: 'TextInputControl' isn't a type.
      TextInputControl? oldControl, TextInputControl? newControl) {
      ^^^^^^^^^^^^^^^^
/D:/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:37: Error: 'TextInputControl' isn't a type.
      TextInputControl? oldControl, TextInputControl? newControl) {
                                    ^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.
* Where:
Script 'D:\flutter_windows_2.10.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter_windows_2.10.5-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 30s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

Please help!

**Comment by redvelvet-fan** [comment]
same issue

**Comment by redvelvet-fan** [comment]
#1084 Fix Problem by Upgrade Flutter version

**Comment by singhayush20** [comment]
Ok, I'll check again after upgrade.
