### ISSUE TITLE
[Mobile] Build Error in iOS

### ISSUE THREAD

**Issue by redvelvet-fan** [singerdmx/flutter-quill#1084]
My issue is about [Mobile]

Device : iPhone 14 Pro Max Simulator (iOS 16.2)
Flutter : 3.3.10
Dart : 2.18.6

pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^6.3.2
  flutter_quill_extensions: ^0.1.0
```

Error Message
```
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/toolbar/quill_font_size_button.dart:113:41: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try accessing using ?. instead.
    final overlay = Overlay.of(context).context.findRenderObject() as RenderBox;
                                        ^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/toolbar/quill_font_family_button.dart:112:41: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try accessing using ?. instead.
    final overlay = Overlay.of(context).context.findRenderObject() as RenderBox;
                                        ^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:87:61: Error: The argument type 'OverlayState?' can't be assigned to the parameter type 'TickerProvider' because 'OverlayState?' is nullable and 'TickerProvider' isn't.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
 - 'TickerProvider' is from 'package:flutter/src/scheduler/ticker.dart' ('../../../development/flutter/packages/flutter/lib/src/scheduler/ticker.dart').
        duration: const Duration(milliseconds: 150), vsync: overlay);
                                                            ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:225:10: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try calling using ?. instead.
        .insert(toolbar!);
         ^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:316:10: Error: 'TextSelectionPoint' isn't a type.
    List<TextSelectionPoint> endpoints;
         ^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:410:10: Error: Method 'insertAll' cannot be called on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try calling using ?. instead.
        .insertAll(_handles!);
         ^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:7: Error: Type 'TextInputControl' not found.
      TextInputControl? oldControl, TextInputControl? newControl) {
      ^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:37: Error: Type 'TextInputControl' not found.
      TextInputControl? oldControl, TextInputControl? newControl) {
                                    ^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:7: Error: 'TextInputControl' isn't a type.
      TextInputControl? oldControl, TextInputControl? newControl) {
      ^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:37: Error: 'TextInputControl' isn't a type.
      TextInputControl? oldControl, TextInputControl? newControl) {
                                    ^^^^^^^^^^^^^^^^
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```
i have build error... how can i solve it?

**Comment by osmansimsek** [comment]
do you have any solution to this problem?

**Comment by redvelvet-fan** [comment]
> do you have any solution to this problem? @redvelvet-fan 

no i don't
i try search about this problem but could not find any answer

so i upgrade flutter version to lastest from 3.2.0

i'll try agian next afternoon 😂

**Comment by redvelvet-fan** [comment]
> > do you have any solution to this problem? @redvelvet-fan
> 
> no i don't i try search about this problem but could not find any answer
> 
> so i upgrade flutter version to lastest from 3.2.0
> 
> i'll try agian next afternoon 😂

i solve this problem by update flutter lastest version

flutter doctor result
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by freshtechtips** [comment]
> My issue is about [Mobile]
> 
> Device : iPhone 14 Pro Max Simulator (iOS 16.2) Flutter : 3.3.10 Dart : 2.18.6
> 
> pubspec.yaml
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
>   flutter_quill: ^6.3.2
>   flutter_quill_extensions: ^0.1.0
> ```
> 
> Error Message
> 
> ```
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/toolbar/quill_font_size_button.dart:113:41: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
>  - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
> Try accessing using ?. instead.
>     final overlay = Overlay.of(context).context.findRenderObject() as RenderBox;
>                                         ^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/toolbar/quill_font_family_button.dart:112:41: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
>  - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
> Try accessing using ?. instead.
>     final overlay = Overlay.of(context).context.findRenderObject() as RenderBox;
>                                         ^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:87:61: Error: The argument type 'OverlayState?' can't be assigned to the parameter type 'TickerProvider' because 'OverlayState?' is nullable and 'TickerProvider' isn't.
>  - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
>  - 'TickerProvider' is from 'package:flutter/src/scheduler/ticker.dart' ('../../../development/flutter/packages/flutter/lib/src/scheduler/ticker.dart').
>         duration: const Duration(milliseconds: 150), vsync: overlay);
>                                                             ^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:225:10: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
>  - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
> Try calling using ?. instead.
>         .insert(toolbar!);
>          ^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:316:10: Error: 'TextSelectionPoint' isn't a type.
>     List<TextSelectionPoint> endpoints;
>          ^^^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/text_selection.dart:410:10: Error: Method 'insertAll' cannot be called on 'OverlayState?' because it is potentially null.
>  - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/overlay.dart').
> Try calling using ?. instead.
>         .insertAll(_handles!);
>          ^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:7: Error: Type 'TextInputControl' not found.
>       TextInputControl? oldControl, TextInputControl? newControl) {
>       ^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:37: Error: Type 'TextInputControl' not found.
>       TextInputControl? oldControl, TextInputControl? newControl) {
>                                     ^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:7: Error: 'TextInputControl' isn't a type.
>       TextInputControl? oldControl, TextInputControl? newControl) {
>       ^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-6.3.2/lib/src/widgets/raw_editor.dart:1428:37: Error: 'TextInputControl' isn't a type.
>       TextInputControl? oldControl, TextInputControl? newControl) {
>                                     ^^^^^^^^^^^^^^^^
> ```
> 
> flutter doctor
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale ko-KR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.2)
> [✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
> [✓] VS Code (version 1.73.1)
> [✓] Connected device (4 available)
> [✓] HTTP Host Availability
> 
> • No issues found!
> ```
> 
> i have build error... how can i solve it?

This issue has been fixed, if you still facing this issue or any others, feel free to contact us on GitHub
