### ISSUE TITLE
[Mobile] Image cannot be self-aligned.

### ISSUE THREAD

**Issue by redvelvet-fan** [singerdmx/flutter-quill#1090]
My issue is about [Mobile]
image not align it self

images need at least different text on the same line for align

### Only Image Example 
![image](https://user-images.githubusercontent.com/62102969/217468870-0b59ac33-74f0-473e-b5e2-fc80b0abcc1d.png)
JSON
```
[{insert: Example 
}, {insert: {image: localImagePath}, attributes: {style: mobileWidth: 235.64000000000001; mobileHeight: 117.432; }}, {insert: 
, attributes: {align: left}}]
```

### With WhiteSpace Example
![image](https://user-images.githubusercontent.com/62102969/217469675-14ebf219-4395-4e1e-8aed-9646e2a60bfb.png)
JSON
```
[{insert: Example 
}, {insert: {image: localImagePath}, attributes: {style: mobileWidth: 235.64000000000001; mobileHeight: 117.432; }}, {insert:  }, {insert: 
, attributes: {align: left}}]
```

**Comment by z59497830** [comment]
Same question, and after adjusting the size and converting it to HTML, the size will not be saved

**Comment by CatHood0** [comment]
@redvelvet-fan  I think this is not really an issue that is currently happening. I will close by now. Please, reopen if the issue persists.
