### ISSUE TITLE
[Mobile] Change color of CustomIcon icon

### ISSUE THREAD

**Issue by Tzanou123** [singerdmx/flutter-quill#1095]
My issue is about [Mobile]

Hello,

It is not possible to change the customIcon icon since it is an IconData !
Do you think it is possible to change that for letting put an Icon instead of an IconData or add argument to set the icon colors ?

Thanks

**Comment by freshtechtips** [comment]
Thank you for the report. I was thinking about that but it will require us to introduce a breaking change

**Comment by freshtechtips** [comment]
This issue has been fixed in `8.4.0`

if you have any questions feel free to ask at any time
