### ISSUE TITLE
[Mobile] Input Chinese and click the end of the paragraph or line to focus on the last. The cursor is always at the penultimate Chinese character of each line

### ISSUE THREAD

**Issue by dt-wonder** [singerdmx/flutter-quill#1098]
My issue is about [Mobile]  IOS
flutter 3.7
flutter_quill 6.3.5

Input Chinese and click the end of the paragraph or line to focus on the last. The cursor is always at the penultimate Chinese character of each line
@singerdmx

**Comment by proxy2501** [comment]
Having this same problem with links.

When a link text is the last in a paragraph, the cursor focuses the next-to-last character in the link text.

This issue seems to only manifest on iOS, and not on Android.

**Comment by Cierra-Runis** [comment]
> Having this same problem with links.
> 
> When a link text is the last in a paragraph, the cursor focuses the next-to-last character in the link text.
> 
> This issue seems to only manifest on iOS, and not on Android.

Yep, I am using android and it also appered.

**Comment by Cierra-Runis** [comment]
> Having this same problem with links.
> 
> When a link text is the last in a paragraph, the cursor focuses the next-to-last character in the link text.
> 
> This issue seems to only manifest on iOS, and not on Android.

Oh, it seems that depend on your TargetPlatform, I changed it to iOS at my android device.

```dart
    ThemeData theme = ThemeData(
      useMaterial3: true,
      colorScheme: lightColorScheme,
      platform: TargetPlatform.iOS,
      pageTransitionsTheme: const PageTransitionsTheme(builders: {
        TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
      }),
      fontFamily: 'Saira',
    );

    ThemeData darkTheme = ThemeData(
      useMaterial3: true,
      colorScheme: darkColorScheme,
      platform: TargetPlatform.iOS,
      pageTransitionsTheme: const PageTransitionsTheme(builders: {
        TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
      }),
      fontFamily: 'Saira',
    );
```

**Comment by Cierra-Runis** [comment]
@singerdmx here can close issue now
