### ISSUE TITLE
how to set placeholder?

### ISSUE THREAD

**Issue by muyu2019** [singerdmx/flutter-quill#11]
hello, I don't know how to set placeholder, I don't find document and properties about it

**Comment by singerdmx** [comment]
What do you mean by placeholder?

**Comment by singerdmx** [comment]
@muyu2019 if you want to load initial content, follow https://github.com/singerdmx/flutter-quill/blob/master/app/lib/pages/home_page.dart#L31 to do the same

**Comment by muyu2019** [comment]
@singerdmx  thank you for your apply, placeholder  is not initial value, that suggests what  input the field accepts. like TextField widget's hintText property, placeholder will be clean when user input some text. 
quilljs editor also has this property
```
var options = {
  debug: 'info',
  modules: {
    toolbar: '#toolbar'
  },
  placeholder: 'Compose an epic...',       <-- this one
  readOnly: true,
  theme: 'snow'
};
```

**Comment by singerdmx** [comment]
That seems a nice feature to have though we don't have that yet.
We will have this in our backlog.
If you can't wait, you are welcome to submit a pull request for it.
We will update this once we started working on it.

**Comment by singerdmx** [comment]
@muyu2019 I have a [change](https://github.com/singerdmx/flutter-quill/pull/34) that gets most working. Needs final touch

**Comment by singerdmx** [comment]
@muyu2019   OK, my [change](https://github.com/singerdmx/flutter-quill/pull/34/files) is done now. I tested it on my phone and it is working. 
All you need to do is this:
![image](https://user-images.githubusercontent.com/122956/108603779-ca1dc200-735e-11eb-9d1f-8e433fd003cb.png)

**Comment by li3317** [comment]
@muyu2019 Hello ! Our repo now supports placeholder, here's an example of what it looks like :
![151430107_289821215825210_5622744891969403627_n](https://user-images.githubusercontent.com/46685982/108614774-890fc700-73cb-11eb-819f-559fe72bed40.jpg)

**Comment by muyu2019** [comment]
Thanks @li3317  @singerdmx

**Comment by hiteshshimpi-55** [comment]
> that

Is there any way to change its style

**Comment by vinz-mehra** [comment]
> > that
> 
> Is there any way to change its style?

Did you figure it out?

**Comment by WaheedHussainHaans** [comment]
> > > that
> > 
> > 
> > Is there any way to change its style?
> 
> Did you figure it out?

Here is the code to change placeholder style

`QuillEditor.basic(
                          focusNode: _textFocusNode,
                          configurations: QuillEditorConfigurations(
                            placeholder: 'Your email text',
                            controller: quillController,
                            padding: EdgeInsets.symmetric(vertical: 4),
                            customStyles: DefaultStyles(
                              placeHolder: DefaultTextBlockStyle(
                                appTheme.textTheme.bodySmall!,
                                VerticalSpacing(15, 15),
                                VerticalSpacing(15, 15),
                                null,
                              ),
                            ),
                            autoFocus: false,
                            sharedConfigurations: QuillSharedConfigurations(),
                          ),
                        ),`
