### ISSUE TITLE
[Web], [Mobile] and [Desktop] Widgets vertical alignment along the text line

### ISSUE THREAD

**Issue by krishnaprasadgandrath-nooor** [singerdmx/flutter-quill#1117]
My issue is about [CustomBlockEmbed] alignment

I have tried running `example` directory successfully before creating an issue here. 

I want to be able to align the custom widgets that i can embed in line with the text previously I copied the quill source code  and changed [WidgetSpan] alignment in `text_line.dart`. However   I want to know whether  I can change widget vertical alignment with latest version.
![Screenshot 2023-02-23 at 6 34 29 PM](https://user-images.githubusercontent.com/94034275/220914356-510e2f6b-324e-4741-8965-2c937fc50961.png)
I need the   above image  to be alligned `vertically centered` with the text line. 

I nee following alignment :
![Screenshot 2023-02-23 at 7 15 17 PM](https://user-images.githubusercontent.com/94034275/220925035-830d0aff-fc08-4a26-8e9d-7f07c34fb41c.png)

**Comment by EchoEllet** [comment]
I don't remember closing this issue as completed, the new issue is #2486.
