### ISSUE TITLE
Paste menu not working

### ISSUE THREAD

**Issue by wesleytoshio** [singerdmx/flutter-quill#112]
Why can't I get texts copied from another location to the editor? the menu not displaying

**Comment by wesleytoshio** [comment]
After a lot of testing I found the problem, it happens due to the new versions, starting from version 1.1.0 copying, pasting and selecting texts doesn't work when you press the editor. I really need the new versions, I saw that you added a lot of new things : null safety. and Base64 support... help me?
![image](https://user-images.githubusercontent.com/7057737/112726528-a836d280-8efc-11eb-8967-dce2360e6112.png)

**Comment by singerdmx** [comment]
Can you track which line change breaks it?

**Comment by singerdmx** [comment]
Is this web or mobile?

**Comment by wesleytoshio** [comment]
I can't tell you which line, the only thing I know is that starting with version 1.1.0 it doesn't work anymore.

I'm using mobile

**Comment by singerdmx** [comment]
Just apply later changes one by one
You will find which one breaks

**Comment by wesleytoshio** [comment]
I will wait for some guardian angel to correct this problem, I will postpone the launch of my application

**Comment by singerdmx** [comment]
check out https://github.com/singerdmx/flutter-quill/commit/ace4fd4deb929e37128f78252a9d5310dafe7d33

**Comment by singerdmx** [comment]
@friebetill are you able to figure this out?

**Comment by friebetill** [comment]
I can take a look :)

**Comment by singerdmx** [comment]
The breaking change is https://github.com/singerdmx/flutter-quill/pull/87

**Comment by wesleytoshio** [comment]
waiting for news, thanks to all of you for your time and dedication to this problem. A great weekend for you.

**Comment by singerdmx** [comment]
Can u check if issue is gone? @wesleytoshio

**Comment by wesleytoshio** [comment]
Everything works fine using ^1.1.4 version. Thanks for all
