### ISSUE TITLE
[Mobile] Toolbar Font & Size appear under other widgets

### ISSUE THREAD

**Issue by saconger** [singerdmx/flutter-quill#1120]
[Mobile]

When using the QuillToolbar, the Font and Size dropdown appear under other widgets.

If I place the toolbar at the top, the Font & Size dropdown will often appear under the highlighted words [cut, copy, paste] menu. For example, when I highlight the first sentence.

If I place the toolbar at the bottom or above the keyboard, the Font & Size dropdown will appear under the keyboard. On Android, this is not a major issue, as you can close the keyboard. But on iOS, you can not and thus can't even select the font or size.

These problems are more common if you have a longer font and size list than the default one.

**Comment by hoangsang17th** [comment]
I can't reproduce your error. Add more images for the issue and your code so I can help you.

**Comment by saconger** [comment]
Here are three screenshots. You can see the font & size show under the keyboard. The Font does not scroll. The size seems to make an attempt to scroll but not enough to see all options on the list.

![Simulator Screenshot - iPhone 13 mini - 2023-09-03 at 22 05 00](https://github.com/singerdmx/flutter-quill/assets/7672114/4ba2ec51-d82a-47d5-983a-5e7ec7e41807)
![Simulator Screenshot - iPhone 13 mini - 2023-09-03 at 22 06 00](https://github.com/singerdmx/flutter-quill/assets/7672114/5d2f73cd-29a5-4071-ba21-7cca79386347)
![Simulator Screenshot - iPhone 13 mini - 2023-09-03 at 22 06 30](https://github.com/singerdmx/flutter-quill/assets/7672114/86445f56-2383-470e-874b-4de577a3ef37)

**Comment by saconger** [comment]
In this screenshot you can see that cut copy paste appears over the quill toolbar options. The result is you can not change the font or color on the first few lines of what is being typed.

![Simulator Screenshot - iPhone 13 mini - 2023-09-03 at 22 11 49](https://github.com/singerdmx/flutter-quill/assets/7672114/401d362d-b64e-4830-8e46-306951bceef7)
