### ISSUE TITLE
Package page does not list Android as one of the supported platforms.

### ISSUE THREAD

**Issue by Tanthus** [singerdmx/flutter-quill#1124]
This is a minor detail but the [flutter package page](https://pub.dev/packages/flutter_quill) does not list Android as one of the supported platforms.

**Comment by hedali** [comment]
Looking forward to support Android as well.

**Comment by Tanthus** [comment]
Note: the library does work on Android.   Thus the bug report.   As it works, I'm not sure why the platform is not listed in the Platforms

**Comment by hedali** [comment]
It works on Android is a good news for me. Thanks buddy @Tanthus.

**Comment by freshtechtips** [comment]
> Note: the library does work on Android. Thus the bug report. As it works, I'm not sure why the platform is not listed in the Platforms

Hi, because we didn't include Android as a supported platform in `pubspec.yaml`, we have done that recently, 
This issue has been fixed, if you still facing this issue or any others, feel free to contact us on GitHub
