### ISSUE TITLE
 [Mobile] Custom context menus from flutter 3.7 doesn't work in flutter quill 6.4.4

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#1126]
My issue is about [Mobile]

Custom context menus from flutter 3.7 doesn't work in flutter quill 6.4.4, I noticed that flutter quill uses a class called TextSelectionConstrols that doesn't work anymore to customize text selection

**Comment by freshtechtips** [comment]
This issue has been fixed, if you still facing this issue or any others, feel free to contact us on GitHub
