### ISSUE TITLE
[Mobile] add TextWidthBasis Parameter

### ISSUE THREAD

**Issue by AlexBower** [singerdmx/flutter-quill#1130]
My issue is about [Mobile]

I am using this library to display html messages in a chat format and would like to be able to set the TextWidthBasis on a QuillEditor so it will change the RichTextProxy's TextWidthBasis from TextWidthBasis.parent, to TextWidthBasis.longestLine so the chat bubbles will not be larger than they need to be.

**Comment by freshtechtips** [comment]
Thank you for the report, we will take a look at it soon!

**Comment by freshtechtips** [comment]
> to display html messages in a chat format and would like to be able to set the

Hi, can you use the new feature request template?? as it requires more info in order for us to understand what you mean in a little bit more detail, thank you for the report

**Comment by AlexBower** [comment]
https://github.com/singerdmx/flutter-quill/issues/1548

**Comment by CatHood0** [comment]
This issue is duplicated.

**Comment by EchoEllet** [comment]
> [CatHood0](/CatHood0)

Using labels will make it easier to go into issues, I have created `critical`, `major`, and `minor` which give each issue a priority. The other labels are GitHub default. Also, we may want to discuss this and see if will create labels for each platform (`android`, `linux`)

I have noticed we're not labeling the issues, if it's duplicated should label it with `duplicate`, if solved use `resolved`.

**Comment by CatHood0** [comment]
> Using labels will make it easier to go into issues, I have created critical, major, and minor which give each issue a priority. The other labels are GitHub default. Also, we may want to discuss this and see if will create labels for each platform (android, linux)

I think this would be great. At this moment the labels are not too useful for describe the issues. We need to discuss tbis definitely
