### ISSUE TITLE
 - TextInputClient.didChangeInputControl  - TextInputClient.performSelector Try to either  - provide an implementation,  - inherit an implementation from a superclass or mixin,  - mark the class as abstract, or  - provide a 'noSuchMethod' implementation.  class RawEditorState extends EditorState       ^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by Malay1121** [singerdmx/flutter-quill#1132]
My issue is about Web
![image](https://user-images.githubusercontent.com/56907997/225525465-fd850b06-6b48-4db4-be53-cb6d6a01d652.png)

 - TextInputClient.didChangeInputControl
 - TextInputClient.performSelector
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^

**Comment by tes735** [comment]
I'm having the same error about : Error: The non-abstract class 'RawEditorState' is missing implementations for these members: and I'm working on an osx app, not web. I used the simple 
    QuillController _controller = QuillController.basic();
    
    QuillToolbar.basic(controller: _controller),
        Expanded(
          child: Container(
            child: QuillEditor.basic(
              controller: _controller,
              readOnly: false, // true for view only mode
            ),
          ),
        )

**Comment by RomanIvn** [comment]
Same here
