### ISSUE TITLE
Version 7 & flutter_quill_extensions

### ISSUE THREAD

**Issue by vd3d** [singerdmx/flutter-quill#1135]
Hi,

I have upgrade to the version 7.x of flutter Quill, but it seems incompatible with flutter_quill_extensions 0.1.0

In the documentation here https://pub.dev/packages/flutter_quill, there is a mention only for version 6.x, but nothing for the 7.x version.

So, what is the right way to have the embeds from the extension again?

**Comment by hoangsang17th** [comment]
Please upgrade `flutter_quill_extensions` into version: 0.4.1

**Comment by freshtechtips** [comment]
if you still facing this issue or any others, feel free to contact us on GitHub
