### ISSUE TITLE
[Mobile] Upgrade delta_markdown to 0.8.0.

### ISSUE THREAD

**Issue by QuangLM75** [singerdmx/flutter-quill#1138]
My issue is about [Mobile]

I have uprade to flutter_quill: ^7.0.1 but my delta_markdown: ^0.8.0 depended on flutter_quill: ^6.0.0.  Please upgrade dependencies

**Comment by Ibtesam-Mahmood** [comment]
Running into the same issue, even with the `flutter_quill_extensions` package

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
