### ISSUE TITLE
Add html to delta format when paste text

### ISSUE THREAD

**Issue by alihassan143** [singerdmx/flutter-quill#1143]
My issue is about [Web]
My issue is about [Mobile]
My issue is about [Desktop]

**Comment by alihassan143** [comment]
@singerdmx  we can take help from the Appflowy editor regarding this issue
[Appflowy html to document converter](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/lib/src/infra/html_converter.dart)

**Comment by freshtechtips** [comment]
Thank you for the report, since there were no interactions with the issue for a while I had to close it. feel free to ask us any questions at any time, if you still facing this issue or any other questions then you can open a new issue

**Comment by alihassan143** [comment]
@freshtechtips  this feature need to be implemented even quill editor support pasting rich text

**Comment by freshtechtips** [comment]
> @freshtechtips  this feature need to be implemented even quill editor support pasting rich text

Please open a new issue if you still want to submit a feature request.
