### ISSUE TITLE
[Feature] Is There anyway to add subscript,superscript and line height features to quill?

### ISSUE THREAD

**Issue by krishnaprasadgandrath-nooor** [singerdmx/flutter-quill#1155]
My issue is about [Text Editing Features] like [Subscript] ,[Script] and [Line Height].

I have tried adding custom rules but didn't succeeed.
Please let me know if any one tried it already.

Thanks.
![Screenshot 2023-04-03 at 12 11 40 PM](https://user-images.githubusercontent.com/94034275/229430937-34331dc8-3f4c-4e0c-9694-ba73b0a54f69.png)

**Comment by freshtechtips** [comment]
> My issue is about [Text Editing Features] like [Subscript] ,[Script] and [Line Height].
> 
> I have tried adding custom rules but didn't succeeed. Please let me know if any one tried it already.
> 
> Thanks. ![Screenshot 2023-04-03 at 12 11 40 PM](https://user-images.githubusercontent.com/94034275/229430937-34331dc8-3f4c-4e0c-9694-ba73b0a54f69.png)

Hi, can you explain what you mean by line-height features?

**Comment by freshtechtips** [comment]
> My issue is about [Text Editing Features] like [Subscript] ,[Script] and [Line Height].
> 
> I have tried adding custom rules but didn't succeeed. Please let me know if any one tried it already.
> 
> Thanks. ![Screenshot 2023-04-03 at 12 11 40 PM](https://user-images.githubusercontent.com/94034275/229430937-34331dc8-3f4c-4e0c-9694-ba73b0a54f69.png)

It's already there in the latest versions, if you have any questions feel free to ask us at any time.
