### ISSUE TITLE
[Mobile] The cursor cannot be moved to the end of the content！

### ISSUE THREAD

**Issue by kzl19950907** [singerdmx/flutter-quill#1156]
i had download the latest demo, run the demo on my iphone.  
when i input some Chinese content ,  move the cursor to the begaining of the content, but when i tap the end of the content ,the cursor
move to the previous text at the end of the content. only double tap can move to the end of the content.

Flutter Doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 12.6.1 21G217 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by Cierra-Runis** [comment]
> .

suppose to be the same issue https://github.com/singerdmx/flutter-quill/issues/1098

**Comment by kzl19950907** [comment]
#1168  it works!
