### ISSUE TITLE
Override default rules to remove some rules

### ISSUE THREAD

**Issue by Ibtesam-Mahmood** [singerdmx/flutter-quill#1162]
I can see that the `setCustomRules` function can be used to append a list of custom rules. However, what am i supposed to do if I want to remove some of the default rules to match my use case. Is there a way to do this within the current build?

**Comment by Guillergood** [comment]
With this PR you will be able to create your own ``setCustomRules``, creating something like:
``class QuillCustomDeleteRule extends Rule``
Then passing it to the ``setCustomRules`` like: ``setCustomRules: [QuillCustomDeleteRule()]``
