### ISSUE TITLE
Allow to add custom context menu  item instead of flutter default

### ISSUE THREAD

**Issue by alihassan143** [singerdmx/flutter-quill#1165]
If i want to customize the context menu how i can do 
currently i will able to customize by cloning repo and apply changes according to my need 
but their is need to be an option for full customization so any one can apply custom context menu according to their need

**Comment by freshtechtips** [comment]
Hi, thank you for the report, we will provide this option soon!

**Comment by freshtechtips** [comment]
> If i want to customize the context menu how i can do currently i will able to customize by cloning repo and apply changes according to my need but their is need to be an option for full customization so any one can apply custom context menu according to their need

Hi again
if you meant The copy/cut, select all, and paste context menu builder for the text selection

we already have the option to have a custom widget

If you still facing any other issues or have any other issues feel free to contact us on GitHub
