### ISSUE TITLE
No Drag Handles

### ISSUE THREAD

**Issue by esDotDev** [singerdmx/flutter-quill#1172]
I am not seeing any drag handles for text, so the only thing you can do is "Select All". Long pressing a word does not select anything, once I select all, I can not modify the selected region after that.

Is this intentional? Some screenshots from the past show TextHandles, so I'm confused:
https://github.com/singerdmx/flutter-quill/issues/5

Is there a way to enable this? Or has it been removed in recent versions? 

Testing on iOS w/ the /example demo and latest `stable`.

https://user-images.githubusercontent.com/736973/231244261-f010d3bd-07c6-4e15-9a1e-4f116e9d2239.mp4

**Comment by AtlasAutocode** [comment]
This is working in the current version.
If you update to the current version and still have a problem, please reopen this issue and give us more information so we can reproduce the problem.
