### ISSUE TITLE
[Desktop] Cursor position  is wrong when note widget fill in one line.

### ISSUE THREAD

**Issue by chifandeyu** [singerdmx/flutter-quill#1176]
My issue is about [Desktop]
Flutter: 3.3.8
OS: macOS 12.3.1
flutter-quill: 6.3.5

Enter the text before the custom widget, and the cursor stays in front of the widget without following the actual text content.
Want the note widget fill in the whole line. The cursor enters the text and automatically switches to previous line of words. The cursor needs to automatically jump to the position of 2.
![img_v2_4c5538e9-86f5-429a-97ab-c5a0e3b11f4g](https://user-images.githubusercontent.com/15946864/232044976-f910a49b-739b-4ea5-8032-1e5e18c0f325.png)

https://user-images.githubusercontent.com/15946864/232045125-ec23179a-9ee3-4b9c-be8f-13ee40ff8f1b.mp4

**Comment by CatHood0** [comment]
@chifandeyu does this issue persists? As far as i check, this was fixed on some of thr lastest versions of the package. I will close this. Please, if the issue was not fixed, reopen it.
