### ISSUE TITLE
could not add initial value to quillcontroller [Mobile]

### ISSUE THREAD

**Issue by shobith10** [singerdmx/flutter-quill#1180]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here. 

Please note that we are using <b>latest</b> flutter version in stable channel on branch master. If you are using beta or master channel, or you are not using <b>latest</b> flutter version in stable channel, you may experience error

i was trying to add voice to text, added the voice string as insert and delta attribution, see the code below
===>
 controller.voicetoText.value = result.recognizedWords;

               var myJSON = jsonDecode(
            '''[
            {
              "insert": "${controller.voicetoText.value}",
              "attributes": {
                "bold": "false"
                }
              }
              ]''');
    
            controller.newFilequaliController.value = quill.QuillController(
            
              document: quill.Document.fromJson(myJSON),
              selection: const TextSelection.collapsed(offset: 0),
            );

            print("${controller.newFilequaliController.value.plainTextEditingValue.text}+gg");
          }
====>
recognizedWords as the string data from voice and newFilequaliControlleris the QuillController value, but i cannot get data in newFilequaliController which i have printed in the last line of above code

**Comment by Juliotati** [comment]
@shobith10 is this what you're looking for?

```dart
import 'package:flutter_quill/flutter_quill.dart' as quill;

// initialise controller
 _controller = quill.QuillController(
    document: quill.Document()..insert(0, 'INITIAL_TEXT_HERE');
    selection: const TextSelection.collapsed(offset: 0),
 );
             
final String newText = 'YOUR_TEXT_AS_SIMPLE_STRING';
final int validRange = _controller.document.length - 1;

/// insert text
_controller.document.insert(validRange, newText);

/// replace text
_controller.document.replace(validRange, newText);
```

**Comment by Juliotati** [comment]
@shobith10 feel free to close this issue if that fixes the problem you faced

**Comment by AtlasAutocode** [comment]
If this is still a problem, please open a new issue with details.
