### ISSUE TITLE
[Web/Mobile/Desktop] copy tooltip does not work

### ISSUE THREAD

**Issue by AlexanderShniperson** [singerdmx/flutter-quill#1190]
The problem: 
- when I select a part of the text in the editor, the "copy/select all" menu does not appear;
- when I select all the text in the editor, sometimes a menu appears in which you can select the "copy / select all" item, copying to the clipboard occurs only if you press "select all", if you press "copy" immediately, nothing goes to the clipboard;

used version: 7.1.11

the code i use:
```
import 'package:flutter_quill/flutter_quill.dart' as quill;
...
   quill.QuillEditor(
      controller: quill.QuillController(
        document: quill.Document()..insert(0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
        selection: const TextSelection.collapsed(offset: 0),
      ),
      showCursor: false,
      readOnly: true,
      focusNode: FocusNode(),
      scrollController: ScrollController(),
      scrollable: false,
      padding: EdgeInsets.zero,
      autoFocus: false,
      expands: false,
    );
```

[as described here](https://github.com/singerdmx/flutter-quill/issues/878), there is some problem in your code

**Comment by freshtechtips** [comment]
Hi, thank you for the report, we had to close this issue since there are no interactions with it, please let me know if it should be reopened. feel free to ask us any other questions on GitHub
