### ISSUE TITLE
Tab button doesn't increase indents for each line in selection separately

### ISSUE THREAD

**Issue by bohdanudreambit** [singerdmx/flutter-quill#1193]
I'm working on the web, but it is also related to the desktop.

### Steps to reproduce:
1. Create numbered/marked list with different indents.
2. Select multiple list items.
3. Tap `tab` or `shift+tab` button.

### Expected result (example from Google sites):

Indents should be increased/decreased separately.

https://user-images.githubusercontent.com/68739850/234912066-6a3f7b53-cb68-4123-997f-582e9d6ccda7.mov

### Actual result:

https://user-images.githubusercontent.com/68739850/234920117-12768fef-7b9b-49f6-b352-4f4131960ad7.mov

### Technical details:

There is `_handleTabKey` method in `RawEditor` class that executes `controller.indentSelection` method of `QuillController`.
In turn, `indentSelection`
1) takes the current selection indent: `final indent = getSelectionStyle().attributes[Attribute.indent.key];`
2) increments or decrements value
3) applies the new value for each line in the selection.

**Comment by bohdanudreambit** [comment]
@nilskroe 
That PR didn't work. I've updated it today, and it partially works, but there is one more issue.

**Comment by AtlasAutocode** [comment]
Numerous updates have addressed this issue.
If this is still a problem, please open a new issue with details.
