### ISSUE TITLE
How to add custom Text Styles, Embed images from device storage?

### ISSUE THREAD

**Issue by ArjanAswal** [singerdmx/flutter-quill#12]
I am porting my app from Zeyfr Editor to this wonderful plugin and I am stuck with a couple of problems.

1] How can I add custom styles to the text. I looked at `QuillStyles()` but didn't understand anything.

2] Whenever I open Notus document files (created by Zeyfr) with your package, it shows an error : 
`Invalid argument (key "heading" not found.): "heading".` 
Any idea how to fix it?

3] How can I embed images from device storage? My current implementation (not working) is this : 
```  
Future<String> uploadImageCallBack(File file) async {
    if (file == null) return null;
    return file.path;
}
``` 

Again Thank you for this wonderful package.

**Comment by singerdmx** [comment]
Let me try to answer one at a time.
1] How can I add custom styles to the text. I looked at QuillStyles() but didn't understand anything.
The code is at https://github.com/singerdmx/flutter-quill/blob/master/lib/widgets/default_styles.dart#L44 
We haven't add option to provide custom styles, but certainly we can add that functionality

**Comment by singerdmx** [comment]
2] Whenever I open Notus document files (created by Zeyfr) with your package, it shows an error :
Invalid argument (key "heading" not found.): "heading".
Any idea how to fix it?

Note that our library is 100% compatible with quilljs, see below:

  INLINE, // refer to https://quilljs.com/docs/formats/#inline
  BLOCK, // refer to https://quilljs.com/docs/formats/#block
  EMBEDS, // refer to https://quilljs.com/docs/formats/#embeds

![image](https://user-images.githubusercontent.com/122956/107124279-c7e43f80-6857-11eb-816f-f358fd3a2822.png)

Check out https://github.com/singerdmx/flutter-quill/blob/master/app/assets/sample_data.json#L7

**Comment by singerdmx** [comment]
3] How can I embed images from device storage? My current implementation (not working) is this :

Future<String> uploadImageCallBack(File file) async {
    if (file == null) return null;
    return file.path;
}

We provide that functionality by default and you should not need to add anything.

Try run the code in https://github.com/singerdmx/flutter-quill/tree/master/app and try opening the editor there. And try embed image and let us know if it is what you want

**Comment by ArjanAswal** [comment]
1] I see. So to add the custom styles, I have to modify the source code. It would be really helpful if this feature to provide custom styles can be added. If you were to do it, can you provide a rough timeline of approximately when this feature will be available?

2] This is interesting... 
Zeyfr document creates 'heading' instead of 'header'. I wonder why.
Regardless, thank you for solving this. I would replace 'heading' with 'header'.

3] I saw the source code, but it seems like it loads a network image, that does work. Instead, I want to show the image from the device which the user picks. I am confused about how to do it?

```
I/flutter (  566): The following ArgumentError was thrown resolving an image codec:
I/flutter (  566): Invalid argument(s): No host specified in URI
I/flutter (  566): file:///data/user/0/com.package.name/cache/image_picker7265803038528231401.jpg
```

**Comment by singerdmx** [comment]
1] I see. So to add the custom styles, I have to modify the source code. It would be really helpful if this feature to provide custom styles can be added. If you were to do it, can you provide a rough timeline of approximately when this feature will be available?

We will add it. Should take one or two days. At most one week

**Comment by singerdmx** [comment]
2] This is interesting...
Zeyfr document creates 'heading' instead of 'header'. I wonder why.
Regardless, thank you for solving this. I would replace 'heading' with 'header'.

Zeyfr is defining its own rules regarding those, which we really hate.
This is part of the reasons we had to build another library that is 100% compliant with quilljs. That is our standard.

**Comment by singerdmx** [comment]
3] I saw the source code, but it seems like it loads a network image, that does work. Instead, I want to show the image from the device which the user picks. I am confused about how to do it?

![image](https://user-images.githubusercontent.com/122956/107125027-185d9c00-685c-11eb-86a8-cc853c8e029f.png)


Which button did you try?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107125039-36c39780-685c-11eb-988d-aa9a11cf27a5.png)


![image](https://user-images.githubusercontent.com/122956/107125042-3c20e200-685c-11eb-8527-6a297d445349.png)

This is what I got.
` show the image from the device which the user picks` I don't fully understand what you want here.

**Comment by ArjanAswal** [comment]
1] Thank you. This feature will be very important for the package and would make the package even more powerful.

2] Wow I didn't know that. I thought the differences were because of different quill versions.
Any idea how I can replace the words without messing with the users document ( If they wrote _heading_ in their text and I accidentally replaced that word with _header_)?

3] Let me explain : 

When you picked the image by pressing the _gallery_ button from the toolbar and selected it, did it got rendered in the editor? In my case, it doesn't and [this image](https://user-images.githubusercontent.com/122956/72955931-ccc07900-3d52-11ea-89b1-d468a6e2aa2b.png) gets shown instead.

**Comment by singerdmx** [comment]
2] Wow I didn't know that. I thought the differences were because of different quill versions.
Any idea how I can replace the words without messing with the users document ( If they wrote heading in their text and I accidentally replaced that word with header)?

Check out https://github.com/singerdmx/flutter-quill/blob/master/app/assets/sample_data.json#L7
This is part of attribute. It CANNOT be text as in "insert".

**Comment by singerdmx** [comment]
3] Let me explain :

When you picked the image by pressing the gallery button from the toolbar and selected it, did it got rendered in the editor? In my case, it doesn't and this image gets shown instead.

Oh I get it. 

Check out https://github.com/singerdmx/flutter-quill/blob/master/app/lib/pages/home_page.dart#L99
You need to implement UploadImageCallBack

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107125331-2d3b2f00-685e-11eb-959f-2b2087a991ec.png)


This is the code in our Bullet Journal Mobile App https://bulletjournal.us/home/index.html

**Comment by singerdmx** [comment]
@ArjanAswal code submitted https://github.com/singerdmx/flutter-quill/commit/95c4df54324bccc60e273526296676cba67be7cc

Once you confirm it works, we will publish a new version on pub

**Comment by ArjanAswal** [comment]
Oh, I see. So basically you have to first upload the image file to the internet to display the image.
In my case, it is a local image so `NetworkImage` won't work. Looks like the source code needs to be modified for it.
A pretty important feature in my humble opinion.

> @ArjanAswal code submitted 95c4df5
> Once you confirm it works, we will publish a new version on pub

I am testing it right away.

**Comment by singerdmx** [comment]
`In my case, it is a local image so NetworkImage won't work.`

I see. I think it is being asked by others as well.
But then it is a totally different workflow. Then when are you going to upload the image?

**Comment by singerdmx** [comment]
`By the way, can you add an option for AssetImage as well before publishing so that our image problem is solved as well?`

We definitely want to support this but unsure how it should play out.
It would be nice if you can submit a pull request.
Or you can wait - I will discuss how to solve this with other team mates.

**Comment by singerdmx** [comment]
@ArjanAswal I can point you to where the code is. Maybe you can submit a pull request?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107125879-337eda80-6861-11eb-972f-99a9aa3fb06d.png)


Would this work?

**Comment by singerdmx** [comment]
All you need to do is pass the UploadImageCallBack function to return url string that is pointing to local device storage

**Comment by singerdmx** [comment]
check out https://github.com/singerdmx/flutter-quill/commit/b04f31e118dc568e7492d228679960eb94336b49

**Comment by ArjanAswal** [comment]
> check out b04f31e

Amazing, now it is working. It is good that now we have both options to render image.
My code: 
```
  Future<String> uploadImageCallBack(File file) async {
    if (file == null) return null;
    return file.path.toString();
  }
```

> @ArjanAswal code submitted 95c4df5
Once you confirm it works, we will publish a new version on pub

This is not working. I have changed the font but it is not showing in the editor.

**Comment by singerdmx** [comment]
Can u provide your code?
And what u expect in the UI

**Comment by ArjanAswal** [comment]
> Can u provide your code?
And what u expect in the UI

```
QuillEditor(
                    controller: controller,
                    scrollController: scrollController,
                    autoFocus: true,
                    expands: true,
                    scrollable: true,
                    focusNode: focusNode,
                    customStyles: DefaultStyles(
                      h1: DefaultTextBlockStyle(
                          GoogleFonts.getFont(
                            settings.getBodyFont(),
                            color: Theme.of(context).primaryColorDark,
                            fontSize: settings.getFontSize() * 2.125,
                            letterSpacing: 0.1 *
                                settings.getLetterSpacing() *
                                settings.getLetterSpacing() *
                                settings.getLetterSpacing() *
                                settings.getLetterSpacing(),
                            height: 1.15 * settings.getLineHeight(),
                          ),
                          Tuple2(16.0, 0.0),
                          Tuple2(0.0, 0.0),
                          null),
                    ),
                    enableInteractiveSelection: true,
                    padding: MediaQuery.of(context).orientation ==
                            Orientation.portrait
                        ? EdgeInsets.symmetric(vertical: 40, horizontal: 20)
                        : EdgeInsets.symmetric(vertical: 5, horizontal: 20),
                    readOnly: false,
                  ),
```

The _H1_ heading should change its font but it is unable to.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107126456-f0266b00-6864-11eb-9b4f-2aa129e448d7.png)


It looks like for header we only takes paragraph.
Let me try adding font

**Comment by singerdmx** [comment]
@ArjanAswal check out https://github.com/singerdmx/flutter-quill/commit/4213aa108708f05c196b923d26545456c82030f0

**Comment by ArjanAswal** [comment]
> @ArjanAswal check out 4213aa1

The changed font is now working. But the font size is not working. Notice that I changed the font size as well.
The _h1, h2, h3_ have the same font size currently.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107127074-84de9800-6868-11eb-927e-64ffd9ae1413.png)


hmm it works for me

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107127136-eacb1f80-6868-11eb-998c-4b3dc91a9d04.png)
It should work

**Comment by ArjanAswal** [comment]
> hmm it works for me

Working for me now as well...weird.

By the way, when I add color into the text from the toolbar, it colors the text background instead of the text itself. Is that expected or an error?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107127179-3087e800-6869-11eb-8cf2-3515fe28d02d.png)


this button

**Comment by ArjanAswal** [comment]
> this button

Oh ok, I think we can change that Icon as people can easily confuse it with underline icon.

**Comment by singerdmx** [comment]
Check out https://quilljs.com/docs/formats/

![image](https://user-images.githubusercontent.com/122956/107127223-8492cc80-6869-11eb-8308-dcedcd897e05.png)


If you can find icon that is similar to web

**Comment by ArjanAswal** [comment]
> Check out https://quilljs.com/docs/formats/

Very well. I will just fork it and create any custom changes just required by me such as icon size, toolbar size/color, etc.

By the way any idea how should I make Zeyfr files compatible with this plugin?

**Comment by singerdmx** [comment]
There is no plan for that.
As you can see, underlying format is different

**Comment by singerdmx** [comment]
You are welcome to submit pull request.
We plan to make text color button selected if attribute has color.


![image](https://user-images.githubusercontent.com/122956/107127373-83ae6a80-686a-11eb-86e6-8d134745261c.png)

That may reduce the confusion

**Comment by ArjanAswal** [comment]
> You are welcome to submit pull request.
We plan to make text color button selected if attribute has color.

Yes, I just forked the repo. Currently looking into all of it. There is a specific icon for color, let me check.

**Comment by singerdmx** [comment]
I mean toolbar's color button should be highlighted with the color if the text has attribute **color**

**Comment by singerdmx** [comment]
@ArjanAswal pub new version is available https://pub.dev/packages/flutter_quill

**Comment by ArjanAswal** [comment]
@singerdmx Will [Icons.color_lens](https://material.io/resources/icons/?search=color_lens&icon=color_lens&style=baseline) be fine?

**Comment by singerdmx** [comment]
OK, we can change that along with the highlighting change

**Comment by ArjanAswal** [comment]
Any other considerations for the icons? Or only this icon?

**Comment by singerdmx** [comment]
We don't have plans now.
You can always propose new idea.

**Comment by ArjanAswal** [comment]
[Check out the PR](https://github.com/singerdmx/flutter-quill/pull/13#issue-568852919)

**Comment by singerdmx** [comment]
@ArjanAswal new pub version is published
