### ISSUE TITLE
[Feature request] Scale checkboxes with line height

### ISSUE THREAD

**Issue by adil192** [singerdmx/flutter-quill#1203]
# Current behaviour
Checkboxes have a fixed size regardless of the font size. This means when the font size is big (e.g. to be readable on mobile), the checkboxes are still small and hard to tap.

# Desired behaviour
Bigger text has correspondingly bigger checkboxes and vice versa.

# Screenshots 
![Screenshot_20230507-182807](https://user-images.githubusercontent.com/21128619/236693169-b2e18102-aa5c-4a12-9793-696b7051d0e1.png)
![Screenshot_20230507-182845](https://user-images.githubusercontent.com/21128619/236693170-a6591f1c-0cab-46ee-bbba-b7b987eca376.png)

**Comment by singerdmx** [comment]
Probably according to line height right?

**Comment by singerdmx** [comment]
I mean max line height - even on the same line you may have different font size
