### ISSUE TITLE
The height of highlight when selecting text is different on different language

### ISSUE THREAD

**Issue by theacheng** [singerdmx/flutter-quill#121]
### QuillEditor:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/29684683/112747206-012a6780-8fde-11eb-8ed8-f6fc50e7c76a.png">

### TextField:
There is an option and it is work on `TextField`
```dart
TextField(
  selectionHeightStyle: BoxHeightStyle.max,
  ....
),
```
<img width="320" alt="image" src="https://user-images.githubusercontent.com/29684683/112747194-f66fd280-8fdd-11eb-8c44-ee6211dce194.png">

https://github.com/flutter/flutter/issues/54935

**Comment by singerdmx** [comment]
Not sure we want max

**Comment by theacheng** [comment]
But that will help UI look better.

![telegram-cloud-photo-size-5-6271406702276488131-x](https://user-images.githubusercontent.com/29684683/112781768-afcdb700-9075-11eb-9fba-5c4f2b271be7.jpg)

**Comment by singerdmx** [comment]
OK, you can submit a pull request
