### ISSUE TITLE
flutter_quill >=7.0.1 depends on i18n_extension ^8.0.0 which depends on intl ^0.17.0

### ISSUE THREAD

**Issue by YawarOsman** [singerdmx/flutter-quill#1213]
I have upgraded my flutter version just to 3.10 and the packages too but flutter_quill package required i18_extension idk why, which that package required inlt 0.17, but flutter 3.10 requires intl 0.18.

what do i have to do?

**Comment by gcostaapps** [comment]
Same here, can't upgrade flutter_quill version becauseof that, need to be on 6.0.0

**Comment by DaBaser123** [comment]
This issue seem to still be present with flutter_quill 7.1.18

**Comment by ddxl123** [comment]
Has it not been resolved yet?

**Comment by gbmiranda** [comment]
same here!
