### ISSUE TITLE
Mobile: Dependency conflict with flutter_quill and chewie packages after Flutter 3.10 upgrade

### ISSUE THREAD

**Issue by BrahimAkar** [singerdmx/flutter-quill#1216]
After upgrading Flutter to version 3.10, I'm encountering a dependency conflict in my project, when trying to use both the flutter_quill (version 7.1.18) and chewie (version 1.5.0) packages.

**Here's the error message I receive during the build process:**

`Resolving dependencies...
Because no versions of wakelock_windows match >0.2.1 <0.3.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, wakelock_windows <0.2.1-∞ or >0.2.1 <0.3.0 requires win32 ^2.0.0.
And because wakelock_windows 0.2.1 depends on win32 ^3.0.0, wakelock_windows <0.3.0 requires win32 ^2.0.0 or ^3.0.0.
Because flutter_quill 7.1.18 depends on device_info_plus ^9.0.0 which depends on win32 ^4.1.4, flutter_quill 7.1.18 requires win32 ^4.1.4.
Thus, flutter_quill 7.1.18 is incompatible with wakelock_windows <0.3.0.
And because wakelock 0.6.2 depends on wakelock_windows ^0.2.0, flutter_quill 7.1.18 is incompatible with wakelock 0.6.2.
Because no versions of wakelock match >0.6.2 <0.7.0 and chewie 1.5.0 depends on wakelock ^0.6.2, chewie 1.5.0 requires wakelock 0.6.2.
Thus, flutter_quill 7.1.18 is incompatible with chewie 1.5.0.
So, because app depends on both chewie 1.5.0 and flutter_quill 7.1.18, version solving failed.
exit code 1
`

Any guidance on resolving this issue would be greatly appreciated!

**Comment by Cierra-Runis** [comment]
It seems that the wakelock_windows package is using a outdated win32 package , you might suppose to create an issue at that package first. @BrahimAkar
