### ISSUE TITLE
Select all not working?

### ISSUE THREAD

**Issue by wesleytoshio** [singerdmx/flutter-quill#122]
The **Select all** not woking in **readyOnly**, any idea?

**Comment by wesleytoshio** [comment]
I need to use this function to select in **read-only** mode

**Comment by singerdmx** [comment]
@friebetill  could you figure it out, please?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/112782454-e669ea00-9001-11eb-8211-efe5d51d2a30.png)
Hmm... by default this is true

**Comment by singerdmx** [comment]
@wesleytoshio if you hack all these fields to be true, what happen?

**Comment by singerdmx** [comment]
@friebetill I think we want to enable "Select", "Select All" and "Copy" in read-only mode. "Cut" is not enabled

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/112784224-ed92f700-9005-11eb-827b-266a02b5754f.png)

Might be this

**Comment by singerdmx** [comment]
Fixed in https://github.com/singerdmx/flutter-quill/commit/2bf7b8b585a040bf0769ec443d501546ade14d26

**Comment by wesleytoshio** [comment]
this is normal? I have to try several times :(

**CHECK THIS VIDEO PLEASE**
https://user-images.githubusercontent.com/7057737/112914182-b427bd80-90d1-11eb-9c4e-4402c8ffaa34.mp4

**Comment by wesleytoshio** [comment]
Sorry for the delay, I was traveling.

**Comment by wesleytoshio** [comment]
Any suggestion?
