### ISSUE TITLE
How can I set an HTML text as initial content to QuillController  [Desktop]

### ISSUE THREAD

**Issue by snehaet** [singerdmx/flutter-quill#1220]
Hi,
I am using Flutter version 3.7.1 for a desktop application.
My use case is to be able to show and edit a field which is retrieved as html text from api.
I am able to use flutter_quill as editor control and convert delta into html which is fine but need also to convert html to delta so as to show as initial content for the controller.

Thank you,
Sneha

**Comment by nmojarro-squaresix** [comment]
@snehaet Did you ever find a solution for this? Sadly [vsc_quill_delta_to_html](https://pub.dev/packages/vsc_quill_delta_to_html) only works one way. :(

**Comment by AndreyKuzmenko** [comment]
+1

**Comment by snehaet** [comment]
> @snehaet Did you ever find a solution for this? Sadly [vsc_quill_delta_to_html](https://pub.dev/packages/vsc_quill_delta_to_html) only works one way. :(

I worked it out by converting html to markdown and then markdown to quill using   html2md: ^1.2.6
  quill_markdown: ^0.1.0 packages
Hope it helps.
