### ISSUE TITLE
ERROR: void insertContent(KeyboardInsertedContent content) {} [Desktop]

### ISSUE THREAD

**Issue by hmamigo** [singerdmx/flutter-quill#1224]
My issue is about Desktop

![error](https://github.com/singerdmx/flutter-quill/assets/39767824/2304ce56-ecfe-4c30-aad7-dfe6b7173036)

Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (4 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by salesandrey** [comment]
Same problem in android

**Comment by guilhermeramos0603** [comment]
Same problem here

**Comment by Chandu-bs** [comment]
Try Flutter upgrade and run, it works!
