### ISSUE TITLE
Unable to apply Style to leaf with custom attribute

### ISSUE THREAD

**Issue by huqigu** [singerdmx/flutter-quill#1227]
My issue is about [Mobile]

<img width="511" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/10161096/db4072c2-072f-49dd-ba96-bb15b90c77f5">

Why is such an assertion needed here? When I have a custom attribute, its scope is IGNORE, even if I specify INLINE when creating its attribute, and then when a section of text contains both my custom attribute and any INLINE attribute, an exception will be thrown here. Do I have any methods to solve this problem?

<img width="1207" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/10161096/f621cbfd-1158-4643-9b86-9bfcfc941d57">

**Comment by ddxl123** [comment]
me too

**Comment by khylenko** [comment]
same

**Comment by deminearchiver** [comment]
I'm having the same issue

**Comment by CatHood0** [comment]
This was fixed at the lastest version of the package. Please update to the last version of the package and test if this issue was fixed to you. If not, please reopen this.
