### ISSUE TITLE
 Flutter Mobile issue on extensions

### ISSUE THREAD

**Issue by hallowcard13** [singerdmx/flutter-quill#1228]
I'm getting the error below, Whenever i add the extension package, to cater to video content

 **Error (Xcode): ../../.pub-cache/hosted/pub.dev/universal_html-2.2.1/lib/src/html/dom/element_subclasses.dart:2752:30: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
element_subclasses.dart:2752
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.**

I'm using 
 flutter_quill: ^7.1.19
 flutter_quill_extensions: ^0.3.2
Flutter 3.10.1 • channel stable

**Comment by bigfox563** [comment]
I also encountered the same question，i use this [https://github.com/dint-dev/universal_html/issues/76](url) solve my question

**Comment by bigfox563** [comment]
I also encountered the same question，i use this [url](https://github.com/dint-dev/universal_html/issues/76) solve my question

**Comment by hallowcard13** [comment]
> I also encountered the same question，i use this [url](https://github.com/dint-dev/universal_html/issues/76) solve my question

Thank for you reply @bigfox563 , I installed the csslib as mentioned on the link,  but i'm getting error 

../../.pub-cache/hosted/pub.dev/flutter_quill_extensions-0.3.2/lib/embeds/builders.dart:25:10: Error: The method 'ImageEmbedBuilder.build' has fewer positional arguments than those of overridden method 'EmbedBuilder.build'.
builders.dart:25
Could not build the application for the simulator.

Any Ideas how to solve this ?
