### ISSUE TITLE
[Web] and [Mobile] and [Desktop] "keepStyleOnNewLine: true" in QuillController does not work 

### ISSUE THREAD

**Issue by thanhdatvo** [singerdmx/flutter-quill#1235]
I have tried running `example` directory successfully in master branch before creating an issue here. 

How to produce: 
1. Set keepStyleOnNewLine: true in QuillController. 
2. Set a style (for example Bold) for a line.
3. Then enter to go to next line

Expected: the style remained the same as previous line (for example Bold)
Actual:  the style was reset to normal

**Comment by anujyadav140** [comment]
facing this same issue ...

**Comment by AtlasAutocode** [comment]
Numerous updates have addressed this issue.
If this is still a problem, please open a new issue with details.
