### ISSUE TITLE
How do I customize the selection area in flutter_quill

### ISSUE THREAD

**Issue by bloveamber-zl** [singerdmx/flutter-quill#1244]
My issue is about [Mobile]

I wanted to have an experience in flutter_quill similar to selection area in iOS Memo. And you want to customize the selection area's button group.

**Comment by hoangsang17th** [comment]
`And you want`?

With your issue, you can fork this repo and update this file followed by your demand

![image](https://github.com/singerdmx/flutter-quill/assets/56586682/462da9d7-52cb-4826-8d1c-4d9b7a77e422)

**Comment by freshtechtips** [comment]
This issue has been fixed, thank you for the report!!
