### ISSUE TITLE
Best way to achieve this ? Read / show more text - Mobile

### ISSUE THREAD

**Issue by ToddZeil** [singerdmx/flutter-quill#1254]
My issue is about Mobile
 
Is there any way to achieve this functionality with flutter quill editor ? (as seen in picture)
 
<img width="419" alt="readMoreText" src="https://github.com/singerdmx/flutter-quill/assets/120418414/d8166ce8-5b66-4316-9c94-57811d448cd8">

**Comment by danchengash** [comment]
By using this package

[https://pub.dev/packages/readmore](readmore)

**Comment by ToddZeil** [comment]
It looks like that package uses plain text though ?

**Comment by singerdmx** [comment]
I guess we can introduce a callback to the editor itself when a particular text or link is hit

**Comment by freshtechtips** [comment]
Hi, since there were no interactions to this issue for some time we had to close it, let me know if we should reopen it or if you still facing any other issues or have any other questions feel free to ask on GitHub
