### ISSUE TITLE
[Mobile][Web] [Desktop] List for different icons

### ISSUE THREAD

**Issue by EgorK0rshun** [singerdmx/flutter-quill#1255]
it's possible to use your own symbols for lists? 
there is an attribute implementation for a list with accepted value ,
```
class ListAttribute extends Attribute<String?> {
  const ListAttribute(String? val) : super('list', AttributeScope.BLOCK, val);
}
```
 but if you specify any value other than the available values, the list is a characterless construct.
 
Right now the implementation is only for lists with dots, numbers and checkboxes. What can I override, so that for the attribute to match my widget to the left of the text in the list.
there is only one validation in `text_block.dart`
```
if (attrs[Attribute.list.key] == Attribute.ol) {
  return QuillNumberPoint(
```
```
if (attrs[Attribute.list.key] == Attribute.ul) {
  return QuillBulletPoint(
 ```
 ```
 if (attrs[Attribute.list.key] == Attribute.checked) {
  return CheckboxPoint(
  ```
  ```
  if (attrs.containsKey(Attribute.codeBlock.key)) {
  return QuillNumberPoint(
  ```
  
  There was an i[ssue about checkboxes](  https://github.com/singerdmx/flutter-quill/issues/7), I would like to have this for icons passed by ColorAttribute example.
Do you plan to change the interaction with the lists a little bit soon?

**Comment by hoangsang17th** [comment]
You can follow below the code

![image](https://github.com/singerdmx/flutter-quill/assets/56586682/4be7acab-c13e-43d8-bc2f-854f7d26f5d7)
![image](https://github.com/singerdmx/flutter-quill/assets/56586682/baaf4352-3c92-4a39-99e1-4cd2e600f12c)

**Comment by EgorK0rshun** [comment]
@hoangsang17th ,maybe you know if you can somehow get around the problem with the fact that after applying the AlignAttribute, the left side of the lists (icons) remains in the same place?

**Comment by hoangsang17th** [comment]
@EgorK0rshun Sorry for this delay! 
I don't have the answer, please close this issue and open a new issue for your question.

**Comment by EgorK0rshun** [comment]
https://github.com/singerdmx/flutter-quill/issues/1258
