### ISSUE TITLE
[Web] and [Desktop] Color picker now includes alpha channel in color values

### ISSUE THREAD

**Issue by ndcube** [singerdmx/flutter-quill#1257]
My issue is about [Web] and [Desktop] (have not tested Mobile)
flutter_quill 7.2.1

The default color pickers in `QuillToolbar.basic` now include the alpha channel in the selected color - `ARGB` format, instead of just `RGB`. For example delta now looks like this `insert⟨ hello ⟩ + {color: #FF5E35B1}` instead of `insert⟨ hello ⟩ + {color: #5E35B1}`
I have realized this when I tried to convert the document delta to html format using `vsc_quill_delta_to_html` as it rejected the `argb` color values. I have created an issue for that there https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/issues/3 but according to them this must be a bug introduced in `flutter_quill 7.2.x` because in **"Quill doc/code, hex colors should always be 3 or 6 digits"**.

So now html conversion looses all colors because it expects them to be in the format `RGB` but now the quill delta does not conform to the expected format.

**Comment by dsyrstad** [comment]
@singerdmx It's disappointing that this is closed. Based on what I see in the official Quill doc/code, hex colors should always be 3 or 6 digits.

**Comment by freshtechtips** [comment]
> @singerdmx It's disappointing that this is closed. Based on what I see in the official Quill doc/code, hex colors should always be 3 or 6 digits.

Don't worry, it's reopened now

**Comment by freshtechtips** [comment]
> @singerdmx It's disappointing that this is closed. Based on what I see in the official Quill doc/code, hex colors should always be 3 or 6 digits.

If you are interested, you can open a new issue using the new templates because it requires more information, which is needed to understand the issue more by anyone

So I close this issue and redirect to the new one and then we will try to provides a fixes

**Comment by deffs** [comment]
I agree that it should be 6 digits so it matches `quill_js`. When my web app saves quill changes it is 6 digits but when it is saved on mobile it as saved as 8 digits with the transparency.

**Comment by viet-tran-0159** [comment]
Has anyone solved this problem yet?
