### ISSUE TITLE
[Desktop] Links are not clickable until the "Control" key is pressed

### ISSUE THREAD

**Issue by Nightbl927** [singerdmx/flutter-quill#1271]
On Desktop (macOS and Windows) a link is not clickable until I hit the control key on the keyboard. Once I hit control, the mouse cursor will change to the hand pointer and allow me to click into the link. Is this the expected behaviour?

**Comment by Albert-Jan** [comment]
Any news on this issue?

**Comment by Albert-Jan** [comment]
This is expected behavior. Links are only tappable when the editor is in edit mode.

**Comment by AtlasAutocode** [comment]
Current behavior is:
Edit mode: requires control key to execute link (otherwise it selects the link to allow editing of the link)
Read-only mode: simple click will open the link target.
