### ISSUE TITLE
[Desktop] How to get the specific coordinates of the cursor?

### ISSUE THREAD

**Issue by hezhong0711** [singerdmx/flutter-quill#1273]
[Desktop]
I want to show an overlay at the position of the cursor when I type a '/' charactor, like notion.
how can I get the specific coordinates of the cursor?

**Comment by hoangsang17th** [comment]
You can get the position of the cursor by `getLocalRectForCaret()`. Please read [this file](https://github.com/singerdmx/flutter-quill/blob/master/CodeIntroduction.md)

**Comment by alexrabin-sentracam** [comment]
@hoangsang17th that file you linked to doesn't exist. Was it moved?

**Comment by alexrabin-sentracam** [comment]
Here is the updated location of the doc for others who may need it: https://github.com/singerdmx/flutter-quill/blob/master/doc/code_introduction.md

**Comment by karroze** [comment]
> Here is the updated location of the doc for others who may need it: https://github.com/singerdmx/flutter-quill/blob/master/doc/code_introduction.md

This document gives zero information on how to solve the issue described by the OP

**Comment by alexrabin-sentracam** [comment]
@karroze the document above references the `getLocalRectForCaret` function. Here is how to use it:

```dart
final GlobalKey<EditorState> editorKey;
final QuillController controller;

final location = editorKey.currentState != null
        ? editorKey.currentState!.renderEditor.getLocalRectForCaret(
            TextPosition(offset: controller.selection.baseOffset))
        : null;

```
