### ISSUE TITLE
BuildToolbar issue on Web

### ISSUE THREAD

**Issue by arjun-ckpatel** [singerdmx/flutter-quill#128]
./../../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-0.3.5/lib/widgets/text_selection.dart:201:43: Error: Too few positional arguments: 8 required, 7 given.
        child: selectionCtrls.buildToolbar(
                                          ^
what issue this ?

**Comment by singerdmx** [comment]
Use master channel
