### ISSUE TITLE
[Mobile] Customize icons on the toolbar

### ISSUE THREAD

**Issue by hoangpv-3229** [singerdmx/flutter-quill#1281]
How can I customize the icons on the toolbar?
 Does flutter_quill supports this?

Thank you guys for your helps

**Comment by hoangsang17th** [comment]
No, flutter_quill isn't supported this. But you can fork the repo and update `toolbar.dart` and `quill_icon_button.dart` files
![image](https://github.com/singerdmx/flutter-quill/assets/56586682/daa35ffe-eccc-4c18-90f3-671505d97365)
