### ISSUE TITLE
[Mobile] Input Chinese on iPad, the editor and quill bar are unresponsive

### ISSUE THREAD

**Issue by RejectMediocrity** [singerdmx/flutter-quill#1285]
When I type Chinese on the iPad, the text doesn't appear on the editor, and the action bar click is unresponsive. iPad version simulator iOS16.2

**Comment by liam-duan** [comment]
Same here. This editor doesn't work on iPad I'd say.

**Comment by liam-duan** [comment]
Not only Chinese, but all input will be unavailable if you enter quickly and with multiple line breaks.

**Comment by freshtechtips** [comment]
Hi, thank you for the report, we had to close this issue since there are no interactions with it, please let me know if it should be reopened. feel free to ask us any other questions on GitHub
