### ISSUE TITLE
[Mobile] or [Desktop]: app craches after inserting URL

### ISSUE THREAD

**Issue by Alspb** [singerdmx/flutter-quill#1288]
App crashes after inserting URL (failed assertion).
Steps to reproduce:

1. Run the example (from `example` directory)
2. Place the cursor right after "diff-match-patch"
3. Press "Insert URL" button, enter text and URL and press "OK"

**Comment by freshtechtips** [comment]
Hi, thank you for the report, this issue has been fixed, if you still facing any other issues or have any other questions feel free to ask us on GitHub
