### ISSUE TITLE
[Mobile] Keyboard closes when selecting Header Style

### ISSUE THREAD

**Issue by gaganyadav80** [singerdmx/flutter-quill#129]
My issue is about [Mobile]

Keyboard closes everytime I click on the SelectHeaderStyleButton which open a drop down and after selecting a heading style the keyboard opens up again which is weird.

**Comment by singerdmx** [comment]
Read only mode?

**Comment by gaganyadav80** [comment]
Read only as FALSE.
(I had the same issue when using zefyr 1.0.0-dev.2.0. If it helps.)
 
Below is the code used: 
```dart
class EditorScreen extends StatefulWidget {
  EditorScreen({Key key}) : super(key: key);

  @override
  _EditorScreenState createState() => _EditorScreenState();
}

class _EditorScreenState extends State<EditorScreen> {
  QuillController _quillController = QuillController.basic();

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        return true;
      },
      child: SafeArea(
        child: Scaffold(
          body: Column(
            children: [
              Expanded(
                child: Container(
                  child: QuillEditor.basic(
                    controller: _quillController,
                    readOnly: false,
                  ),
                ),
              ),
              QuillToolbar.basic(controller: _quillController),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by singerdmx** [comment]
I think it is not an issue
It is normal

**Comment by ArjanAswal** [comment]
This issue is the duplicate of [this](https://github.com/singerdmx/flutter-quill/issues/38).
It is pretty frustrating that the keyboard pops up unnecessarily when we click heading.

**Comment by gaganyadav80** [comment]
I have changed the dropdown (as I didn't looked into it) and to show the heading options on the toolbar instead. Occupies more space but looks much cleaner and simple to use.

If you want to see the screenshot you can checkout the discussions tab.
