### ISSUE TITLE
[Mobile] or [Desktop] Subscript and superscript don't work

### ISSUE THREAD

**Issue by Alspb** [singerdmx/flutter-quill#1290]
My issue is about [Mobile] and [Desktop].

"Subscript" and "superscript" buttons don't work, they do nothing.

**Comment by singerdmx** [comment]
Is it still an issue in latest version?

**Comment by singerdmx** [comment]
This functionality is added by PR.
Can you find who submitted the PR and reach out?

**Comment by singerdmx** [comment]
@huqigu this is added by you. It is working right?

**Comment by huqigu** [comment]
> @huqigu this is added by you. It is working right?

yes, It is working right

**Comment by huqigu** [comment]
Subscript and superscript support letters, numbers and a few other characters， and it is related to the font of the mobile phone system,  it is working right in iOS.   When you want to run on Android or Desktop, you may need to import a font library

**Comment by singerdmx** [comment]
Thanks

**Comment by singerdmx** [comment]
@Alspb if you can update sample project for Android to add this, it would be great
