### ISSUE TITLE
Feature request: add case-insensitive search and wrap around

### ISSUE THREAD

**Issue by Alspb** [singerdmx/flutter-quill#1291]
Feature request: please add a setting/config to make the search case-insensitive.
Ideally, also add wrap around setting/config to be able to go from the last search result to the first one by pressing "Next".

**Comment by singerdmx** [comment]
We have search functionality already

**Comment by singerdmx** [comment]
That should be an easy change. Can you submit a PR for it?
Make it options that user can choose
