### ISSUE TITLE
[Mobile] Please add support for text magnifier for cursor movement

### ISSUE THREAD

**Issue by tschiekdev** [singerdmx/flutter-quill#1296]
On Flutter 3.7 they have implemented "Text Magnifier" while dragging the cursor in the text field around.

Please see here:
[https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c](https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c)

Can you please add this to flutter quill?

**Comment by tschiekdev** [comment]
What did "PR please" mean?!?!

**Comment by singerdmx** [comment]
Pull Request

**Comment by freshtechtips** [comment]
Hi, thank you for the report, there are already other issues that we have discussed some things so I have to close the old ones to avoid confusion, please check [this](https://github.com/singerdmx/flutter-quill/issues/1504)
