### ISSUE TITLE
How to get html value from Editor ?

### ISSUE THREAD

**Issue by arjun-ckpatel** [singerdmx/flutter-quill#130]
We are successfully setup Editor but can't enter space key .

suppose , user write HTML text and add style so how to get all html text in flutter web ?

**Comment by singerdmx** [comment]
see https://github.com/singerdmx/flutter-quill/issues/15

**Comment by dsyrstad** [comment]
@chirag-dt https://pub.dev/packages/vsc_quill_delta_to_html provides a robust delta to HTML conversion.
