### ISSUE TITLE
Add new line after adding photo on mobile

### ISSUE THREAD

**Issue by basicemotions** [singerdmx/flutter-quill#1300]
### Discussed in https://github.com/singerdmx/flutter-quill/discussions/1293

<div type='discussions-op-text'>

<sup>Originally posted by **basicemotions** July  5, 2023</sup>
In mobile version (especially iOS) adding photos from quill_extensions feels very uncomfortable because of cursor position after photo add. Cursor is to the right from photo (that takes a full screen width after adding btw). And user can't tap screen on cursor to open keyboard and continue typing. User have to tap on previous line and move cursor by holing a space button. It'd be very comfortable to create an option foк developer to add new line after adding photo.</div>

**Comment by singerdmx** [comment]
I think this is already supported. A Boolean parameter of the editor.
