### ISSUE TITLE
[Mobile] Option to display all the data in app including format instead of just plain text

### ISSUE THREAD

**Issue by milindgoel15** [singerdmx/flutter-quill#1303]
My issue is about [Mobile]

Basically, according to the documentation, we can add documents by encoding to delta and then to json. And to display it back in the quill, we just decode it and pass it back to the quill controller. But to show this data on app say on gridview like a note, we have to use toPlainText which removes all the formatting. 

Can you add an option to keep the formatting here? or is there already an option?

I have tried running `example` directory successfully before creating an issue here. 

Please note that we are using <b>latest</b> flutter version in stable channel on branch master. If you are using beta or master channel, or you are not using <b>latest</b> flutter version in stable channel, you may experience error.

**Comment by singerdmx** [comment]
Are you asking to expose some method?

**Comment by singerdmx** [comment]
var json = jsonEncode(_controller.document.toDelta().toJson());

**Comment by milindgoel15** [comment]
That method encodes it and stores as json which can only be viewed back in only quill editor.

 But I am asking for a method that can store data with formatting.

**Comment by singerdmx** [comment]
Take the json string and do your processing to get what you need

**Comment by milindgoel15** [comment]
That method encodes it and stores as json which can only be viewed back in only quill editor.

 But I am asking for a method that can store data with formatting.

Something like:

```dart
var data= _controller.document.toFormatted();

```

And this can be displayed in text

`Text(data)`

**Comment by singerdmx** [comment]
Alright I think you can create a PR if you really want it.
Just follow how toPlainText is done
