### ISSUE TITLE
[Mobile] Overflow error on using search dialog

### ISSUE THREAD

**Issue by milindgoel15** [singerdmx/flutter-quill#1304]
My issue is about [Mobile]

![image](https://github.com/singerdmx/flutter-quill/assets/45682747/8e389ba8-f502-4bf9-b9df-9f20760f7321)

Please suggest some solution.

**Comment by singerdmx** [comment]
It has to do with the device you use

**Comment by milindgoel15** [comment]
So how can I fix it? Please suggest.
