### ISSUE TITLE
No signature of method

### ISSUE THREAD

**Issue by disburden** [singerdmx/flutter-quill#1305]
My issue is about [Mobile]

I cloned the project and ran it directly without making any changes, resulting in the following error.
I roughly know that there should be a problem with the "build. gradle" file,I commented everything under 'Android',
only 'compileSdkVersion' was retained, and it is still this error.
how to solve the problem?

No signature of method: build_b7zqlle2w8l2vmk413563vu9j.android() is applicable for argument types: 
(build_b7zqlle2w8l2vmk413563vu9j$_run_closure2) values: [build_b7zqlle2w8l2vmk413563vu9j$_run_closure2@34ac80b6]

**Comment by singerdmx** [comment]
is it from sample app?

**Comment by disburden** [comment]
> is it from sample app?

Yes,run the example as soon as it is cloned, nothing has changed

**Comment by singerdmx** [comment]
Not sure. Can you ask chatGpt?

**Comment by disburden** [comment]
I changed it casually and now it’s fine, i’m not sure where the problem is :(
