### ISSUE TITLE
text editing bar does not work with samsung S PEN, 

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#1311]
problem started when I updated flutter to version 3.10,
I have an application that uses flutter quill, attached the video showing the problem

https://github.com/singerdmx/flutter-quill/assets/22117346/18b76fdb-6c53-4de8-8fc5-84261dc7884c

**Comment by singerdmx** [comment]
This is not something we can work on since we don't use Samsung
