### ISSUE TITLE
[Web] and [Mobile] 'RawEditorState' is missing

### ISSUE THREAD

**Issue by Antoigne** [singerdmx/flutter-quill#1327]
My issue is about [Web]
My issue is about [Mobile]

../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.2.18/lib/src/widgets/raw_editor.dart:283:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.liveTextInputEnabled
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

Please note that we are using <b>latest</b> flutter version in stable channel on branch master.

**Comment by churchnotesapp** [comment]
Any help with this?

**Comment by AlanPGDev** [comment]
Any updates? I have the same error: Error (Xcode): /Users/dev/.pub-cache/hosted/pub.dev/flutter_quill-7.2.1/lib/src/widgets/raw_editor.dart:283:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:

**Comment by AlanPGDev** [comment]
I changed from the beta channel to the stable channel and it resolved the issue.

**Comment by churchnotesapp** [comment]
Yeah it didn't work for me - do you mind sharing your flutter version? I'll try reproduce the same setup

**Comment by AlanPGDev** [comment]
> Yeah it didn't work for me - do you mind sharing your flutter version? I'll try reproduce the same setup

Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (4 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

**Comment by Muhammed-Rahif** [comment]
The issue still persists, even on latest stable version (^7.4.1).

**Comment by AlanPGDev** [comment]
Still running stable channel and updated to 3.13.2 and got the error again. Did a flutter clean, updated version of flutter_quill to 7.4.4, and it compiled.

**Comment by T-P-F** [comment]
Re macos but likely other platforms as well...

### Command PhaseScriptExecution failed with a nonzero exit code

As Flutter merged, this is now happening on `stable`, meaning anyone who runs `flutter upgrade` then cleans and compiles will see the following and the build will fail.

```
Flutter 3.14.0-14.0.pre.181 • channel master • https://github.com/flutter/flutter.git
Framework • revision d73e1b69f7 (15 hours ago) • 2023-09-08 13:43:20 -0400
Engine • revision 47a79306ee
Tools • Dart 3.2.0 (build 3.2.0-134.0.dev) • DevTools 2.27.0
```

On build of runner (macos):

```
Showing Recent Messages
../../../.pub-cache/hosted/pub.dev/flutter_quill-7.4.6/lib/src/widgets/raw_editor.dart:283:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:

 - TextSelectionDelegate.lookUpEnabled
 - TextSelectionDelegate.searchWebEnabled
 - TextSelectionDelegate.shareEnabled

Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^

../../flutter/packages/flutter/lib/src/services/text_input.dart:1054:12: Context: 'TextSelectionDelegate.lookUpEnabled' is defined here.

  bool get lookUpEnabled => true;
           ^^^^^^^^^^^^^

../../flutter/packages/flutter/lib/src/services/text_input.dart:1057:12: Context: 'TextSelectionDelegate.searchWebEnabled' is defined here.

  bool get searchWebEnabled => true;
           ^^^^^^^^^^^^^^^^

../../flutter/packages/flutter/lib/src/services/text_input.dart:1060:12: Context: 'TextSelectionDelegate.shareEnabled' is defined here.

  bool get shareEnabled => true;
           ^^^^^^^^^^^^

../../../.pub-cache/hosted/pub.dev/flutter_quill-7.4.6/lib/src/widgets/raw_editor.dart:351:47: Error: Required named parameter 'onLookUp' must be provided.

    return EditableText.getEditableButtonItems(

../../flutter/packages/flutter/lib/src/widgets/editable_text.dart:1869:38: Context: Found this candidate, but the arguments don't match.

  static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Vedsaga** [comment]
Nope, 

> Still running stable channel and updated to 3.13.2 and got the error again. Did a flutter clean, updated version of flutter_quill to 7.4.4, and it compiled.

It doesn't work for `3.13.2` or higher versions.

**Comment by freshtechtips** [comment]
Hi, thank you for the report, this issue has been fixed, if you still facing any other issues or have any other questions feel free to ask us on GitHub
