### ISSUE TITLE
Add a method to set TextInputAction

### ISSUE THREAD

**Issue by dashuaiqin** [singerdmx/flutter-quill#1328]
My issue is about [Mobile]

A very useful plugin.
Can you please add a way to set a keyboard's TextInputAction？

**Comment by singerdmx** [comment]
What do you mean?

**Comment by dashuaiqin** [comment]
<img width="407" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/11640638/91cee669-45b3-444f-a70c-004ce2effc70">
I mean this action type

**Comment by xalanq** [comment]
Any update?

**Comment by freshtechtips** [comment]
> My issue is about [Mobile]
> 
> A very useful plugin. Can you please add a way to set a keyboard's TextInputAction？

Thank you for the report. It's a good idea, thank you for providing that to our intention, we will look into that soon

**Comment by dumasrobert13** [comment]
any updates about this enhancement?

**Comment by ellet0** [comment]
> any updates about this enhancement?

We already added it, I heard about some issues about it when chaning it to amything other than newLine but I don't remember much

**Comment by huandu** [comment]
@EchoEllet There should be a bug in `QuillEditorState`. When creating new `QuillRawEditorConfigurations`, `configurations.textInputAction` should be assigned to `textInputAction`.

https://github.com/singerdmx/flutter-quill/blob/faf8f558a8e52a2ce59d37883d1f4b1b3d1edcdb/lib/src/editor/editor.dart#L235-L302

**Comment by huandu** [comment]
I create a PR #2057 to fix this issue.
