### ISSUE TITLE
Crash on iOS when typing

### ISSUE THREAD

**Issue by amit20897** [singerdmx/flutter-quill#1333]
Latest version causes mysterious app crashes on iOS when typing inside the field, it doesn't happen always and happens in a release build more often than in a debug build.

The error I get is:
Fatal Exception: NSInvalidArgumentException
*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

Stack trace:
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9cb4 __exceptionPreprocess
1  libobjc.A.dylib                0x183d0 objc_exception_throw
2  CoreFoundation                 0x1aff84 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1ac51c -[__NSArrayM insertObject:atIndex:].cold.2
4  CoreFoundation                 0x140a8 -[__NSArrayM insertObject:atIndex:]
5  Flutter                        0x35420 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
6  Flutter                        0x3dd820 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
7  Flutter                        0x3dda78 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
8  Flutter                        0x2e4afc (Missing UUID 4c4c444555553144a19d3dfde98674e8)
9  Flutter                        0x3dd194 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
10 Flutter                        0x3de9c0 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
11 Flutter                        0x3ddcb8 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
12 Flutter                        0x3f3e24 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
13 Flutter                        0x2e3134 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
14 Flutter                        0x2e6460 (Missing UUID 4c4c444555553144a19d3dfde98674e8)
15 CoreFoundation                 0xcb624 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
16 CoreFoundation                 0x88f4c __CFRunLoopDoTimer
17 CoreFoundation                 0x2e71c __CFRunLoopDoTimers
18 CoreFoundation                 0x7a4d4 __CFRunLoopRun
19 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific
20 GraphicsServices               0x135c GSEventRunModal
21 UIKitCore                      0x39d6e8 -[UIApplication _run]
22 UIKitCore                      0x39d34c UIApplicationMain
23 Runner                         0x54a8 main + 5 (AppDelegate.swift:5)
24 ???                            0x1e00c6dec (Missing)

**Comment by freshtechtips** [comment]
Thank you for the report, the issue has been fixed
