### ISSUE TITLE
[Mobile]  i get it with translation error

### ISSUE THREAD

**Issue by kadirgulluoglu** [singerdmx/flutter-quill#1334]
My issue is about [Mobile]

flutter: ➜ Translation key in 'en' is missing: "OK".
flutter: ➜ There are no translations in 'tr' for "Material".
flutter: ➜ There are no translations in 'tr' for "Color".
flutter: ➜ There are no translations in 'tr' for "Hex".

**Comment by singerdmx** [comment]
Check out https://github.com/singerdmx/flutter-quill#translation
You can submit a PR to add missing ones
