### ISSUE TITLE
[Mobile] boolean enableUnfocusOnTapOutside does not do anything

### ISSUE THREAD

**Issue by milindgoel15** [singerdmx/flutter-quill#1337]
My issue is about [Mobile]

the boolean enableUnfocusOnTapOutside does not do anything. When set to true, if we are typing something, on tapping outside, it does not unfocus the editor.

Flutter_quill version: 7.2.18

**Comment by DyNamite-TNT-1** [comment]
They comment that:
![image](https://github.com/singerdmx/flutter-quill/assets/104590526/b81df92b-01a0-4aa4-9464-99fc54e10635)
You can fork this repo to make it right follow your purpose.

**Comment by milindgoel15** [comment]
Oh, kinda meaningless to not have an unfocus feature supported for Android/mobile when basic input fields support it without issues. 

Perhaps this behaviour could be changed.

**Comment by DyNamite-TNT-1** [comment]
I agree with you. So that I forked this repo to fix it.

**Comment by milindgoel15** [comment]
Does your fork version include the tapoutside code for Android?

**Comment by DyNamite-TNT-1** [comment]
This is original code.
![image](https://github.com/singerdmx/flutter-quill/assets/104590526/2923aa08-4644-425e-9795-783fb8f20c49)
You just delete from line 455 to line 458, it's working.

**Comment by freshtechtips** [comment]
Hi, thank you for the report, this issue has been fixed, if you still facing any other issues or have any other questions feel free to ask us on GitHub
