### ISSUE TITLE
Disable text selection in read only mode

### ISSUE THREAD

**Issue by FelixMittermeier** [singerdmx/flutter-quill#134]
One of the recent commits kind of breaks my application:
https://github.com/singerdmx/flutter-quill/commit/2bf7b8b585a040bf0769ec443d501546ade14d26

The users of my app should not be able to select and copy the text in read only mode. This commit seems to remove the functionality to disable the functionality. Is there any new way to disable it?

**Comment by singerdmx** [comment]
I am afraid this is not a common case that needs to be supported

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/113496264-c1b3bd80-94ac-11eb-8b57-d8c75162edca.png)
If the above helps, let me know

**Comment by FelixMittermeier** [comment]
Yeah that would definitely be great. So I am able to allow the copy paste functionality in editing mode but not in read-only mode 👍🏻

**Comment by singerdmx** [comment]
done

**Comment by FelixMittermeier** [comment]
Wow that was quick. Thank you very much for the great maintenance ☺️
Really appreciated.
