### ISSUE TITLE
How can I put it directly into the widget without using a QuillController?

### ISSUE THREAD

**Issue by ddxl123** [singerdmx/flutter-quill#1346]
I have a list and each element needs to use QuillEditor. But a QuillEditor can only use one QuillController. How can I put it directly into the widget without using a QuillController?

**Comment by DyNamite-TNT-1** [comment]
I think no, but u can minimize it like
` final doc = Document();
    _controller = QuillController(
      document: doc,
      selection: const TextSelection.collapsed(offset: 0),
    )`

**Comment by qingchengl** [comment]
Similarly, I also have such a need, how to put QuillEditor into the rich text editing list?

**Comment by AtlasAutocode** [comment]
Each instance of QuillEditor needs its own instance of QuillController.
For your case:
1. convert the text you want to display to a Document
2. add the document to QuillController
3. add controller to QuillEditor

```
QuillEditor.basic(
   controller: QuillController ( document: <convert text_to_document> etc.
```
Copy the segment for each instance of the editor.
Can we close this issue?
