### ISSUE TITLE
[Web] Tab key inserts spaces even in readOnly mode

### ISSUE THREAD

**Issue by bill-95** [singerdmx/flutter-quill#1348]
My issue is about [Web] and all platforms.

Observed behavior
I am running the read-only example and when I press the tab key, it edits the read-only content.

Expected behavior:
Pressing the tab key should not edit/modify the read-only content.

See here I pressed 4x tab key:

![image](https://github.com/singerdmx/flutter-quill/assets/13008126/40923998-2d7e-4c18-b3f3-7e2c9e9db449)

**Comment by carly-goodandbeautiful** [comment]
I fixed this in https://github.com/singerdmx/flutter-quill/pull/1433

**Comment by AtlasAutocode** [comment]
Closed as fixed.
If this is still an issue, please reopen and let us know what is still broken.
