### ISSUE TITLE
Gallery Saver Conflict

### ISSUE THREAD

**Issue by themumy10** [singerdmx/flutter-quill#1349]
Gallery Saver plugin on pubspec file uses http:0.13.1 and conflicts other plugins that i used.
Could you update this gallery saver with something else because it s not updated over 22 months.
Thanks for the effort in advance

**Comment by hectorAguero** [comment]
Already commented a bit here, https://github.com/singerdmx/flutter-quill/issues/1350

The package should be changed for https://pub.dev/packages/image_gallery_saver  but it need to implement the download of url images manually.

**Comment by freshtechtips** [comment]
Thank you for the report, the flutter quill team has migrated to `gal`

The issue should be fixed, feel free to ask us any questions at any time
