### ISSUE TITLE
image_picker ^1.0.2 and flutter_quill_extensions ^0.4.0

### ISSUE THREAD

**Issue by cgzcgb** [singerdmx/flutter-quill#1350]
Because flutter_quill_extensions 0.4.0 depends on image_picker ^0.8.5+3 and no versions of flutter_quill_extensions match >0.4.0 <0.5.0, flutter_quill_extensions ^0.4.0 requires image_picker ^0.8.5+3.
So, because xxxx depends on both image_picker ^1.0.2 and flutter_quill_extensions ^0.4.0, version solving failed.

**Comment by themumy10** [comment]
Same for gallery_saver plugin. Please update or change dependecies

**Comment by ddxl123** [comment]
I have the same problem.
Because aaa depends on flutter_quill_extensions ^0.4.0 which depends on image_picker ^0.8.5+3, image_picker ^0.8.5+3 is required.
So, because aaa depends on image_picker ^1.0.1, version solving failed.

**Comment by hectorAguero** [comment]
The actual gallery_saver package also doesn't have web support, because they are saving the image to the "Gallery", that's not needed in web/desktop.
