### ISSUE TITLE
Flutter QuillEditor integration with Forms and Validation

### ISSUE THREAD

**Issue by pepefcardoso** [singerdmx/flutter-quill#1359]
I'm trying to integrate a QuillEditor widget inside a Form in Flutter, but I've been having some issues.

My goal is to make the widget behave like a default TextFormField when there's a request to validate a form.

Is there any way to do it?

I've tried to use QuillController's onSelectionChanged and extend FormField/FormFieldState in the widgets, but none off them seems to work.

Would appreciate some help :)

**Comment by LucienCorreia** [comment]
up

**Comment by gbtb16** [comment]
upup

**Comment by BrunoAlvez** [comment]
up

**Comment by itbrunoms** [comment]
up

**Comment by DyNamite-TNT-1** [comment]
QuillController is more complex than TextEditingController. I think you can get all text when onSelectionChanged to validate it. To get all text, you can try this: 
![image](https://github.com/singerdmx/flutter-quill/assets/104590526/0c1ae9fa-6993-42e8-ab4a-50395966f5d4)
Hope this helps you!
