### ISSUE TITLE
Infinite loop in _updateSizeAndTransform

### ISSUE THREAD

**Issue by szotp-lc** [singerdmx/flutter-quill#1364]
I have stumbled upon this when reviewing your code: https://github.com/singerdmx/flutter-quill/blob/5dca6008cde707beb46291b6fbf71af6dbbf7bfb/lib/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart#L336-L346

_updateSizeAndTransform is getting called every frame, is this necessary?

Also the comment seems to be stale.

**Comment by freshtechtips** [comment]
Hi, thank you for the report, we had to close this issue since there are no interactions with it, please let me know if it should be reopened.
