### ISSUE TITLE
[Mobile] korean can't input after imbeded image

### ISSUE THREAD

**Issue by hyein-jay** [singerdmx/flutter-quill#1365]
My issue is about [Mobile]

lastest version when i test is 7.0.3

https://github.com/singerdmx/flutter-quill/assets/104044212/48046ee4-b6bc-4f16-9dd2-c576881bb014

i have many korean input issue. this is one of them.

it happened IOS 16.2 and doesn't happened at android or under IOS 15.4.

the cursor that just after imbeded image is stuck at consonant. space is ok. consonant+ consonant is ok. consonant + vowel is never pass to next index. the point is it doesn't happened when escape just that position.

is there any issue about recent ios version? and do you have a plan to fix it?

**Comment by freshtechtips** [comment]
Hi, thank you for the report, we had to close this issue since there are no interactions with it, please let me know if it should be reopened. feel free to ask us any other questions on GitHub
