### ISSUE TITLE
Mobile copy with formatting between different flutter quill editors

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#1366]
I have 2 flutter quill text editors next to each other, can someone explain to me how I can change the code so that when I copy from one editor to the other, it copies the formatting together?

**Comment by DyNamite-TNT-1** [comment]
I already have tried to run example of this. And I can copy from Home page and pasted to read only page. So, I thinks this can copy paste from 2 quill editors each other.

**Comment by hoangsang17th** [comment]
No. It did not copy the formatting. Before, when the user selects a paragraph and copies it, the Quill will copy the format into a variable, and when the user pastes it, Quill will merge it. (Look at the picture)

However, now the variable is not used, you only copy the text and paste it.

If you want to implement this feature, I can help you, naturally, I can't give you my code (Company policies)
![image](https://github.com/singerdmx/flutter-quill/assets/56586682/879940e0-9dee-45ea-a329-c149ae53aca6)

**Comment by Gkemon** [comment]
@hoangsang17th  can you please help me? I want to implement it.

**Comment by AtlasAutocode** [comment]
The current version does not have this problem. Copying formatted text between editors is supported.
If the problem still exists, please reopen and let us know how to reproduce the program.
