### ISSUE TITLE
there is a bug about i18n when in toolbar tooltip

### ISSUE THREAD

**Issue by ASD271** [singerdmx/flutter-quill#1369]
i found the tooltip is not correct language when mouse point,for example in demo, when you set language zh_cn, the QuillFontFamilyButton will show right label '字体', but show wrong language tool tip 'font family'.
i personal think this is because the author create tool bar widget in QuillToolbar children attribute, where i18n is settle yet.

**Comment by ASD271** [comment]
<img width="139" alt="123" src="https://github.com/singerdmx/flutter-quill/assets/80188412/45bd28ce-ac0b-4538-88aa-4fd239d8317f">

**Comment by freshtechtips** [comment]
> i found the tooltip is not correct language when mouse point,for example in demo, when you set language zh_cn, the QuillFontFamilyButton will show right label '字体', but show wrong language tool tip 'font family'. i personal think this is because the author create tool bar widget in QuillToolbar children attribute, where i18n is settle yet.

Hi, do you still facing this issue or any other issues?

**Comment by freshtechtips** [comment]
Hi, thank you for the report, we had to close this issue since there are no interactions with it, please let me know if it should be reopened. feel free to ask us any other questions on GitHub
