### ISSUE TITLE
issue of flutter quill integration in web but after that can not run web or mobile as well.

### ISSUE THREAD

**Issue by deeppatel1211** [singerdmx/flutter-quill#1370]
flutter version:- 3.14.0-9.0.pre.70
flutter_quill version: 7.4.1

../../../.pub-cache/hosted/pub.dev/flutter_quill-7.4.1/lib/src/widgets/raw_editor.dart:353:7: Error: No named parameter with the name 'onLiveTextInput'.
      onLiveTextInput: null,
      ^^^^^^^^^^^^^^^
../../../development/flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.
  static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/jstechno-mac-mini/development/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/jstechno-mac-mini/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s

Need Help. Please any one have solution for this ?

**Comment by Collins21** [comment]
Facing the same problem, any luck with resolving this issue...?

**Comment by iniwf** [comment]
sdk: '>=3.0.5 <4.0.0'  Facing the same problem. modify pubspec.yaml,  environment: sdk: '>=2.18.5 <3.0.0'

**Comment by JaredEzz** [comment]
I'm having this issue too. environment:  sdk: ">=3.0.0 <4.0.0"

**Comment by alaincruz06** [comment]
If you keep facing the same bug you could use my [forked version](https://github.com/alaincruz06/flutter-quill.git), I fixed the onLiveTextInput and downgraded to match my Flutter SDK (3.10.6) & Dart SDK (3.0.6)

**Comment by freshtechtips** [comment]
Thank you for the report, the issue has been fixed, feel free to ask us any questions at anytime
