### ISSUE TITLE
Mobile: Create a dropdown to list header styles and other attributes

### ISSUE THREAD

**Issue by AravindBG** [singerdmx/flutter-quill#1371]
My issue is about the Mobile.

I'm trying to create a dropdown in the toolbar something similar to the attached screenshot.
But I couldn't find any components to create a dropdown or add the header styles and similar attributes in **flutter_quill: ^7.4.1**.

**Flutter 3.13.0**

<img width="430" alt="Screenshot 2023-08-24 at 7 57 41 PM" src="https://github.com/singerdmx/flutter-quill/assets/5819939/91b8547c-d7dc-421b-b630-29dbd57bd52b">

**Comment by freshtechtips** [comment]
Hi, thanks for the report, please provide us with more information about the issue or feature request so we can help you the best we can

**Comment by AtlasAutocode** [comment]
The example app provides how to do this.
Look for `QuillToolbarSelectHeaderStyleDropdownButton`
