### ISSUE TITLE
[Mobile] Dark Overlay when using Search Option

### ISSUE THREAD

**Issue by tschiekdev** [singerdmx/flutter-quill#1375]
The first picture shows the app in its normal state.

In the second image, the search function is active and the entire area is darkened.

Why?

The last picture shows how it looks in dark mode. You can't see anything anymore.

can you fix this please?

![Bildschirmfoto 2023-08-25 um 22 15 21](https://github.com/singerdmx/flutter-quill/assets/11464255/c402faab-3737-45d2-99b2-1327bc4a7364)

![Bildschirmfoto 2023-08-25 um 22 14 49](https://github.com/singerdmx/flutter-quill/assets/11464255/dbd5bd42-c715-4da2-b9e7-f8d26a3056b5)

![Bildschirmfoto 2023-08-25 um 22 13 39](https://github.com/singerdmx/flutter-quill/assets/11464255/fa94ee16-2642-4d59-96ad-13218e28e375)

**Comment by hoangsang17th** [comment]
Clone this package and change it
![image](https://github.com/singerdmx/flutter-quill/assets/56586682/d08e132e-9ae1-4874-b4bf-f64d9b2b240f)

**Comment by freshtechtips** [comment]
This issue has been solved, you can now customize the dialog barrier color, the dialog widget and you even have a callback for showing custom dialog
