### ISSUE TITLE
[flutter_quill_extensions] outdated dependency `gallery_saver`

### ISSUE THREAD

**Issue by santiagos01** [singerdmx/flutter-quill#1377]
`flutter_quill_extensions` currently depends on [`gallery_saver: ^2.3.2`](https://github.com/singerdmx/flutter-quill/blob/787c7a845facf13ea886f74c608cdbfd4bfd2b95/flutter_quill_extensions/pubspec.yaml#L21).

But the package is no longer maintained, and it's now causing issue due to outdated `http` version (https://github.com/CarnegieTechnologies/gallery_saver/issues/205).

**Proposal**
Update to use it's replacement: https://pub.dev/packages/gal

**Comment by singerdmx** [comment]
Looks good. Could you please submit a PR?

**Comment by hectorAguero** [comment]
The difference between gallery saver in other packages like gal or image_gallery_saver is that we need to download the image first if is is a url link.

So a PR should switch from gallery_saver to the choice package + the implementation to download an image, would be good if doesn't use any package, but using http is fine too.

**Comment by santiagos01** [comment]
Sflr, have been occupied with other things. Just created #1403 to resolve this.
