### ISSUE TITLE
[Web] - Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by arjun-ckpatel** [singerdmx/flutter-quill#138]
we are using quill and Editor are working fine but when we start to deploy on web then it's getting issue.

#Issue
main.dart.js:72075 Uncaught TypeError: Cannot read property 'toString' of null

Please find Screenshot

![Screenshot from 2021-04-04 15-15-21](https://user-images.githubusercontent.com/43512427/113504867-bf0ea200-9558-11eb-8e40-7d5d794298cf.png)

**Comment by singerdmx** [comment]
closing due to no repro
