### ISSUE TITLE
buuuuug !!!!!!

### ISSUE THREAD

**Issue by MahdiHRH1194** [singerdmx/flutter-quill#1383]
raw_editor.dart:353:7: Error: No named parameter with the name 'onLiveTextInput'.
      onLiveTextInput: null,
      ^^^^^^^^^^^^^^^
/F:/Android/Flutter%203.10.2/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.
  static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^

Please fix it :(

Add these features
Adjust the left or right alignment of the text
and the size and font of the text editor, which can be set as defaults via code

**Comment by DyNamite-TNT-1** [comment]
See #1384 about "onLiveTextInput" bug.

**Comment by singerdmx** [comment]
Use old version of flutter quill if you are not using latest version of flutter

**Comment by freshtechtips** [comment]
> raw_editor.dart:353:7: Error: No named parameter with the name 'onLiveTextInput'. onLiveTextInput: null, ^^^^^^^^^^^^^^^ /F:/Android/Flutter%203.10.2/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match. static List getEditableButtonItems({ ^^^^^^^^^^^^^^^^^^^^^^
> 
> Please fix it :(
> 
> Add these features Adjust the left or right alignment of the text and the size and font of the text editor, which can be set as defaults via code

if you still facing this issue or any others, feel free to contact us on Github
