### ISSUE TITLE
Major bug on android 

### ISSUE THREAD

**Issue by Gilles-kpn** [singerdmx/flutter-quill#1384]
My issue is about [Mobile]

Flutter app not build after installing this dependency. 
```dart
[+1388 ms] [+2195 ms] ../../.pub-cache/hosted/pub.dev/flutter_quill-7.4.4/lib/src/widgets/raw_editor.dart:353:7: Error: No named parameter with the name 'onLiveTextInput'.
[   +1 ms] [   +1 ms]       onLiveTextInput: null,
[        ] [        ]       ^^^^^^^^^^^^^^^
[        ] [        ] ../../.flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   static List<ContextMenuButtonItem> getEditableButtonItems({
[        ] [        ]                                      ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by DyNamite-TNT-1** [comment]
This issue because pub update to fit with flutter sdk 3.13. 
You need to update your flutter sdk to lastest. 
@singerdmx Is there another way?

**Comment by Gilles-kpn** [comment]
I try using version 7.2.0, 7.3.0 but the error occured each time of build or run .
 I can't update flutter sdk ubtil i verify if nothing will be broken on project 
Any suggestions??/

**Comment by singerdmx** [comment]
Use old version of flutter quill if you are not using latest version of flutter

**Comment by DyNamite-TNT-1** [comment]
> I try using version 7.2.0, 7.3.0 but the error occured each time of build or run . I can't update flutter sdk ubtil i verify if nothing will be broken on project Any suggestions?? @DyNamite-TNT-1

"use version below 7.4.0." means version of flutter quill.

**Comment by Guervyl** [comment]
This is a bug from flutter-quill. It just not working with latest flutter version. 

This is flutter doctor: I'm using the latest flutter version. And I installed the `flutter_quill: ^7.4.6`
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.0)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.81.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

It is impossible to run the web project with this error:

```
../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.4.6/lib/src/widgets/raw_editor.dart:353:7: Error: No named parameter with the name 'onLiveTextInput'.
      onLiveTextInput: null,
      ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.
  static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.

```

**Comment by Eduardocoutto** [comment]
I have the same problem when running on flutter web. The problem is compatibility with flutter.

**Comment by iHamza7** [comment]
i face the same issue for 2 days and after upgrading my flutter sdk from 3.0.0 to 3.13.0 it work and make sure after upgrading the sdk save changes to the project environment sdk as well

**Comment by freshtechtips** [comment]
Thank you for the report, the issue has been fixed
