### ISSUE TITLE
is support table? and I want transform to table tag display in web.

### ISSUE THREAD

**Issue by SinglTown** [singerdmx/flutter-quill#1388]
how to do that?

**Comment by wildsurfer** [comment]
+1

**Comment by Gowsalyanatraj** [comment]
+1

**Comment by iremceliksena** [comment]
Hello,
I also have html containing <table>. I want to reflect the HTML codes as they are and edit them in the editor. How can I do this, or can I do it? Can it only detect parameters such as <p>?

**Comment by singerdmx** [comment]
Duplicate of https://github.com/singerdmx/flutter-quill/issues/1735
