### ISSUE TITLE
[Mobile] auto focus after insert

### ISSUE THREAD

**Issue by binvb** [singerdmx/flutter-quill#1391]
My issue is about [Mobile]

same at example

i don't want auto focus after inserted(e.g. image), how can i prevent this behavior， thank you very much.

**Comment by NguyenPhatBG** [comment]
sam like me

**Comment by freshtechtips** [comment]
Hi, can you explain in more detail with pictures?? how is that image inserted?? is it inserted using the controller or toolbar button??

**Comment by freshtechtips** [comment]
> My issue is about [Mobile]
> 
> same at example
> 
> i don't want auto focus after inserted(e.g. image), how can i prevent this behavior， thank you very much.

if you still facing this issue or any others, please tell us

**Comment by freshtechtips** [comment]
@singerdmx Consider adding Github action that will close the issue if it hasn't been updated, changed or any reaction for a while

**Comment by singerdmx** [comment]
Not sure how to do that.
Here I added this https://github.com/singerdmx/flutter-quill/blob/master/.github/workflows/publish.yml to automatically publish package

**Comment by freshtechtips** [comment]
If you have any other questions feel free to ask us on GitHub

We are working on improving the library in general to fit your needs and the others needs
