### ISSUE TITLE
How to open link in editor?

### ISSUE THREAD

**Issue by ArjanAswal** [singerdmx/flutter-quill#14]
What does `onLaunchUrl` do? How can I launch URL form the editor?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107141262-716d1480-68dc-11eb-96e8-121f8c03b06a.png)


It's what happens when url link is clicked

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107141274-834eb780-68dc-11eb-8eb5-55c691e7793b.png)

By default we use url_launcher package to open webview

**Comment by ArjanAswal** [comment]
> By default we use url_launcher package to open webview

There is a problem with this, what if the user types _google.com_ instead of _https://www.google.com_ ? Most users would do that.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107141348-ff48ff80-68dc-11eb-883c-1fe36c71db63.png)

**Comment by ArjanAswal** [comment]
The url is not launching.
I have passed the `_onLaunchUrl_` function but it is not doing anything.

**Comment by singerdmx** [comment]
Why do you even need to pass anything?

**Comment by singerdmx** [comment]
Why do you need custom behavior?
By default it already works

**Comment by singerdmx** [comment]
It only launch in readonly mode

**Comment by ArjanAswal** [comment]
> Why do you need custom behavior?
By default it already works

I removed the function... It is not working even then.

**Comment by ArjanAswal** [comment]
> It only launch in readonly mode

Oh now it is working. Thanks.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107141477-c52c2d80-68dd-11eb-990e-17627f2aed8c.png)

**Comment by Tristan-2021** [comment]
I have tried using OnLauncher, but I don't know how to implement it correctly, since when clicking on the link, the Url should open and it doesn't

**Comment by rajenderK7** [comment]
> ![image](https://user-images.githubusercontent.com/122956/107141274-834eb780-68dc-11eb-8eb5-55c691e7793b.png)
> 
> By default we use url_launcher package to open webview

How can we open the link in a browser instead of webview?

**Comment by rajenderK7** [comment]
> 

I'm stuck at this. Is there way already present to do it?
