### ISSUE TITLE
Web - Exception caught by scheduler library Unexpected null value Flutter quill

### ISSUE THREAD

**Issue by arjun-ckpatel** [singerdmx/flutter-quill#140]
i'm using [Flutter Quil](https://github.com/singerdmx/flutter-quill) Editor but always return null error.

════════ Exception caught by scheduler library ═════════════════════════════════
Unexpected null value.
════════════════════════════════════════════════════════════════════════════════

please check screenshot

![Screenshot from 2021-04-08 16-18-44](https://user-images.githubusercontent.com/43512427/114014532-58ee8b80-9886-11eb-8147-126a078e0a05.png)

**Comment by florianh01** [comment]
Please provide some additional information like, stacktrace, flutter version, flutter-quill version...

**Comment by arjun-ckpatel** [comment]
` Column(
              children: <Widget>[
                QuillToolbar.basic(controller: _controller),
                Container(
                  height: 200,
                  padding: EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.all(Radius.circular(5)),
                    border: Border.all(color: Colors.grey[300], width: 1.0),
                  ),
                  child: QuillEditor.basic(
                    controller: _controller,
                    readOnly: false, // true for view only mode
                  ),
                )
              ],
            ),
            `
            
 #version
  flutter_quill: ^1.1.7
  
  #Flutter version
    flutter 2.0.4

**Comment by florianh01** [comment]
Please provide also the stacktrace. 

Also try this editor:
```
QuillEditor(
              expands: false,
              controller: _controller,
              scrollController: ScrollController(),
              scrollable: true,
              focusNode: _focusNode,
              autoFocus: true,
              readOnly: false,
            ),
```

**Comment by arjun-ckpatel** [comment]
How to open stacktrace ? where it is ? sorry but i'm begginer.
Thanks to quick reply

**Comment by singerdmx** [comment]
closing due to no repro

**Comment by arjun-ckpatel** [comment]
i can't find stacktrace...

**Comment by arjun-ckpatel** [comment]
i also try QuillEditor but not working...can you give sample demo
