### ISSUE TITLE
[Mobile] -- Upgrade incompatibility  issue     MAJOR ERROR

### ISSUE THREAD

**Issue by Twapa** [singerdmx/flutter-quill#1415]
My issue is about [Mobile]

I have tried running version 5.2.11 successfully before creating an issue here. 

After upgrade latest version flutter version stable channel.  many run errors pop up..

`/C:/Users/../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-6.4.2/lib/src/widgets/text_selection.dart:716:9: Error: Type 'DragSelectionUpdateCallback' not found.
  final DragSelectionUpdateCallback? onDragSelectionUpdate;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-6.4.2/lib/src/widgets/raw_editor.dart:253:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextInputClient.insertContent
 - TextSelectionDelegate.liveTextInputEnabled
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:1124:8: Context: 'TextInputClient.insertContent' is defined here. 
  void insertContent(KeyboardInsertedContent content) {}
       ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:1058:12: Context: 'TextSelectionDelegate.liveTextInputEnabled' is defined here.
  bool get liveTextInputEnabled => false;
           ^^^^^^^^^^^^^^^^^^^^
/C:/Users/../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-6.4.2/lib/src/widgets/raw_editor.dart:309:47: Error: Required named parameter 'onLiveTextInput' must be provided.
    return EditableText.getEditableButtonItems(
                                              ^
/C:/flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.
  static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-6.4.2/lib/src/widgets/text_selection.dart:716:9: Error: 'DragSelectionUpdateCallback' isn't a type.
  final DragSelectionUpdateCallback? onDragSelectionUpdate;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^`
**### Please help**

**Comment by KannugoPrithvi** [comment]
Even I'm getting the same issue after upgrading flutter version. I'm using 6.4.4. I could not update to latest version due sub package version collision with wakelock.

**Comment by asturgeon123** [comment]
I am also getting the same error

**Comment by alaincruz06** [comment]
You could use my [forked version](https://github.com/alaincruz06/flutter-quill.git), I fixed the onLiveTextInput and downgraded to match my Flutter SDK (3.10.6) & Dart SDK (3.0.6)

**Comment by sattiramyasri7** [comment]
**I am using flutter 3.13.0 .**
**flutter_quill I am using [7.1.16+1] version .**
I tried downgrading versions till 7.0.0 .still I am getting same error .
**can any one help me**
This is my console.

Launching lib/main.dart on sdk gphone x86 64 in debug mode...
../../.pub-cache/hosted/pub.dev/flutter_quill-7.1.16+1/lib/src/widgets/text_selection.dart:716:9: Error: Type 'DragSelectionUpdateCallback' not found.
final DragSelectionUpdateCallback? onDragSelectionUpdate;
^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_quill-7.1.16+1/lib/src/widgets/text_selection.dart:716:9: Error: 'DragSelectionUpdateCallback' isn't a type.
final DragSelectionUpdateCallback? onDragSelectionUpdate;
^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_quill-7.1.16+1/lib/src/widgets/raw_editor.dart:277:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:

TextInputClient.insertContent
TextSelectionDelegate.liveTextInputEnabled
Try to either
provide an implementation,
inherit an implementation from a superclass or mixin,
mark the class as abstract, or
provide a 'noSuchMethod' implementation.
class RawEditorState extends EditorState
^^^^^^^^^^^^^^
../../tools/flutter/packages/flutter/lib/src/services/text_input.dart:1124:8: Context: 'TextInputClient.insertContent' is defined here.
void insertContent(KeyboardInsertedContent content) {}
^^^^^^^^^^^^^
../../tools/flutter/packages/flutter/lib/src/services/text_input.dart:1058:12: Context: 'TextSelectionDelegate.liveTextInputEnabled' is defined here.
bool get liveTextInputEnabled => false;
^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_quill-7.1.16+1/lib/src/widgets/raw_editor.dart:333:47: Error: Required named parameter 'onLiveTextInput' must be provided.
return EditableText.getEditableButtonItems(
^
../../tools/flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.
static List getEditableButtonItems({
^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
FAILURE: Build failed with an exception.

Where:
Script '/Users/sattiramyasri/tools/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

What went wrong:
Execution failed for task ':app:compileFlutterBuildStagingDebug'.

Process 'command '/Users/sattiramyasri/tools/flutter/bin/flutter'' finished with non-zero exit value 1
Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
Get more help at https://help.gradle.org/
BUILD FAILED in 12s
Exception: Gradle task assembleStagingDebug failed with exit code 1

Exited (1).

Thanks in Advance
