### ISSUE TITLE
Deprecated getter field on the Web (the solution is simple)

### ISSUE THREAD

**Issue by freshtechtips** [singerdmx/flutter-quill#1418]
My issue is about [Web]

There is a warning on the web:
`The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.`

I could try to fix it myself and send a pull request but if there is anyone
who just getting started with open source and want to try pull request

then he/she is more than welcome to do it

but if no one fixes it then I will have to fix it myself later

Thank you for your time and efforts.

**Comment by singerdmx** [comment]
Please go ahead. Thanks

**Comment by ahmedhnewa** [comment]
> Please go ahead. Thanks

I will but I'm busy adding more features and utilities 
and improve the support for macOS/web

so I think it might be helpful for someone who is new to dealing with
open source projects

**Comment by freshtechtips** [comment]
I fixed it since no one did. It should be fixed in the new version if my pull request gets approved
