### ISSUE TITLE
[Mobile] Null check operator used on a null value

### ISSUE THREAD

**Issue by Guillergood** [singerdmx/flutter-quill#1423]
My issue is about [Mobile]

Step to reproduce:
Create a QuillController
Tap on it
Also when writting.

Stacktrace:

Null check operator used on a null value

======== Exception caught by foundation library ====================================================
The following _TypeError was thrown while dispatching notifications for QuillController:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
0      RawEditorState.renderEditor (package:flutter_quill/src/widgets/raw_editor.dart:1366:32)
1      RawEditorStateTextInputClientMixin._updateSizeAndTransform (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:340:20)
2      RawEditorStateTextInputClientMixin.openConnectionIfNeeded (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:68:7)
3      RawEditorState.requestKeyboard (package:flutter_quill/src/widgets/raw_editor.dart:1383:7)
4      RawEditorState._didChangeTextEditingValue (package:flutter_quill/src/widgets/raw_editor.dart:1209:7)
5      RawEditorState.initState.<anonymous closure> (package:flutter_quill/src/widgets/raw_editor.dart:1031:7)
6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
7      QuillController.replaceText (package:flutter_quill/src/widgets/controller.dart:286:5)
8      RawEditorStateTextInputClientMixin.updateEditingValue (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:192:25)
9      TextInput._updateEditingValue (package:flutter/src/services/text_input.dart:2019:43)
10     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1852:29)
11     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
12     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:55)
13     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:34)
14     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
15     _invoke2 (dart:ui/hooks.dart:202:13)
16     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
17     _Channel.push (dart:ui/channel_buffers.dart:135:31)
18     ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
19     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
20     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
The QuillController sending notification was: Instance of 'QuillController'

IMAGES

![Flutter_quill null](https://github.com/singerdmx/flutter-quill/assets/16701917/0c11c07e-1d47-4983-a842-d9ccf1579ff0)

**Comment by freshtechtips** [comment]
Hi, can you explain in a little more detail?? what do you mean by tap on the controller?? do you mean the editor??

**Comment by Guillergood** [comment]
Yes, I mean that in an example project with simple QuillEditor instantiated (QuillController), by tapping on it, throws that exception.

**Comment by freshtechtips** [comment]
> Yes, I mean that in an example project with simple QuillEditor instantiated (QuillController), by tapping on it, throws that exception.

Thank you for the report, I will try to address that in the next pull request, but I might ask you more info if you don't mind so we can fix it as soon as possible

**Comment by freshtechtips** [comment]
> Yes, I mean that in an example project with simple QuillEditor instantiated (QuillController), by tapping on it, throws that exception.

Hi again, can you provide us a details steps to encounter this issue step by step??

**Comment by freshtechtips** [comment]
> My issue is about [Mobile]
> 
> Step to reproduce: Create a QuillController Tap on it Also when writting.
> 
> Stacktrace:
> 
> Null check operator used on a null value
> 
> ======== Exception caught by foundation library ==================================================== The following _TypeError was thrown while dispatching notifications for QuillController: Null check operator used on a null value
> 
> When the exception was thrown, this was the stack: 0 RawEditorState.renderEditor (package:flutter_quill/src/widgets/raw_editor.dart:1366:32) 1 RawEditorStateTextInputClientMixin._updateSizeAndTransform (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:340:20) 2 RawEditorStateTextInputClientMixin.openConnectionIfNeeded (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:68:7) 3 RawEditorState.requestKeyboard (package:flutter_quill/src/widgets/raw_editor.dart:1383:7) 4 RawEditorState._didChangeTextEditingValue (package:flutter_quill/src/widgets/raw_editor.dart:1209:7) 5 RawEditorState.initState. (package:flutter_quill/src/widgets/raw_editor.dart:1031:7) 6 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24) 7 QuillController.replaceText (package:flutter_quill/src/widgets/controller.dart:286:5) 8 RawEditorStateTextInputClientMixin.updateEditingValue (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:192:25) 9 TextInput._updateEditingValue (package:flutter/src/services/text_input.dart:2019:43) 10 TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1852:29) 11 TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20) 12 MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:55) 13 MethodChannel.setMethodCallHandler. (package:flutter/src/services/platform_channel.dart:540:34) 14 _DefaultBinaryMessenger.setMessageHandler. (package:flutter/src/services/binding.dart:567:35) 15 _invoke2 (dart:ui/hooks.dart:202:13) 16 _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5) 17 _Channel.push (dart:ui/channel_buffers.dart:135:31) 18 ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17) 19 PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22) 20 _dispatchPlatformMessage (dart:ui/hooks.dart:114:31) The QuillController sending notification was: Instance of 'QuillController'
> 
> IMAGES
> 
> ![Flutter_quill null](https://user-images.githubusercontent.com/16701917/275578616-0c11c07e-1d47-4983-a842-d9ccf1579ff0.png)

Please let me know if you still facing the issue or if any others

**Comment by Guillergood** [comment]
Hello @freshtechtips aparently everything is working now, when I upgraded the dependencies. I rhink it may be some cached thing. Sorry for the inconvenience. :smile:

**Comment by Guillergood** [comment]
I couldn't reproduce it, but still happens. I found a simpler way not to call the ! operator so that an exception is not raised. Also less code and improved readability, please check it out.
