### ISSUE TITLE
[Feature Request] More UI customisation options 

### ISSUE THREAD

**Issue by milindgoel15** [singerdmx/flutter-quill#1431]
So currently, I built a fluentUI-based Windows app and also have a material design 3 app for Android. During my testing on windows environment: 

- Quill Editor:
I found that when selecting text, the highlight is blue and text becomes invisible. Tried looking at custom styles but couldn't find something for text highlight color. This is my current editor code:

<details>
<summary>editor code</summary>

```dart
quill.QuillEditor(
        controller: controller,
        showCursor: true,
        scrollController: ScrollController(),
        scrollable: true,
        focusNode: FocusNode(),
        enableUnfocusOnTapOutside: true,
        onLaunchUrl: (value) {
          openLinksHandler(context, value);
        },
        minHeight: 200,
        autoFocus: false,
        placeholder: 'Start writing content here',
        expands: false,
        padding: const EdgeInsets.all(20),
        readOnly: !makeNoteEditable,
        // customStyles: quill.DefaultStyles(
        //   color: isDesktop
        //       ? fluent.Colors.red
        //       : Theme.of(context).colorScheme.error,
        // ),
      ),
```

</details>

- quill toolbar

Allow for shape customisations for applying box decoration to the toolbar

**Comment by freshtechtips** [comment]
I'm working on a new pull request for further improvements, can you tell me more about what you would like to do in more detail??

Personally, I don't recommend flutent_ui as it is buggy but I get what you mean
Currently, the library is not platform adaptive as it depends on the material design system I do plan on working on that, but is it what you want to change the highlight color and customize it?
it would be helpful if you share images about that issue so that others can understand it more

Either by edit this issue or in a new comment

**Comment by freshtechtips** [comment]
> Windows environment feel like native. So using fluent_ui was the best option available. It's not so buggy in my experience but yes, things could be

Copying an image from another application is another feature and probably requires native code but we will address it in the future

**Comment by milindgoel15** [comment]
> > Windows environment feel like native. So using fluent_ui was the best option available. It's not so buggy in my experience but yes, things could be
> 
> Copying an image from another application is another feature and probably requires native code but we will address it in the future

The context doesn't match your reply.

**Comment by freshtechtips** [comment]
> > > Windows environment feel like native. So using fluent_ui was the best option available. It's not so buggy in my experience but yes, things could be
> > 
> > 
> > Copying an image from another application is another feature and probably requires native code but we will address it in the future
> 
> The context doesn't match your reply.

I'm trying to reply to the end of your message, I'm working on this feature right now

**Comment by milindgoel15** [comment]
> I'm trying to reply to the end of your message

Oh then I wasn't talking about copying an image from another app. I was talking about copying text from other apps/websites.

**Comment by freshtechtips** [comment]
> > I'm trying to reply to the end of your message
> 
> Oh then I wasn't talking about copying an image from another app. I was talking about copying text from other apps/websites.

Websites runs in browser which is a application,

can you send me the snippet code that you are using for the quill editor configurations?? and also your fluent app configurations

**Comment by milindgoel15** [comment]
> Websites run in a browser which is an application,

Well, still in such cases, copying an image is different from copying a text. Check out this demo:
https://github.com/singerdmx/flutter-quill/assets/45682747/8ee12741-5682-4d64-bb61-5601120569a5

Also, using a different editor like super_editor copies the text markdowns and doesn't paste as plain text.

> and also your fluent app configurations

https://katb.in/ifozucubuza

> can you send me the snippet code that you are using for the quill editor configurations??

I shared my editor code in my OP message.

**Comment by milindgoel15** [comment]
Just an update, made my own fork and checked the property responsible for the text selection color and fixed it.
![image](https://github.com/singerdmx/flutter-quill/assets/45682747/a1b22c20-fda2-4550-b90c-6265171b5cf5)

I might just fix my toolbar issue as well.

**Comment by freshtechtips** [comment]
You might want to fix the toolbar issue only because I already did it and we will have merge conflict in the future, I can't undo because I have other changes, of course that is up to you and I don't mind fixing merge conflicts

**Comment by freshtechtips** [comment]
> Just an update, made my own fork and checked the property responsible for the text selection color and fixed it. ![image](https://user-images.githubusercontent.com/45682747/276574594-a1b22c20-fda2-4550-b90c-6265171b5cf5.png)
> 
> I might just fix my toolbar issue as well.

Perfect, I already fixed it but you are more than welcome to do it

**Comment by milindgoel15** [comment]
> Perfect, I already fixed it but you are more than welcome to do it

Maybe we can do one thing, could u review my changed code and see if my solution aligns/matches well with your change? If in case, its the same, I will wait for your PR to be created and merged and till then, I will use my fork.

**Comment by freshtechtips** [comment]
> > Perfect, I already fixed it but you are more than welcome to do it
> 
> Maybe we can do one thing, could u review my changed code and see if my solution aligns/matches well with your change? If in case, its the same, I will wait for your PR to be created and merged and till then, I will use my fork.

I was planning on making more changes but if that is the case then I will create the [pull request](https://github.com/singerdmx/flutter-quill/pull/1437) now, see if it fits your needs and if there is anything else you want just tell me and I will do it or you can send a pull request if you want to

**Comment by freshtechtips** [comment]
> > Perfect, I already fixed it but you are more than welcome to do it
> 
> Maybe we can do one thing, could u review my changed code and see if my solution aligns/matches well with your change? If in case, its the same, I will wait for your PR to be created and merged and till then, I will use my fork.

I was planning on making more changes but if that is the case then I had to create the [pull request](https://github.com/singerdmx/flutter-quill/pull/1437) to avoid merge conflicts, but I did a little bit different from your approach, I add the option to override the text selection theme and if it's not set then it will use the default one, see if it fits your needs and if there is anything else you want just tell me and I will do it or you can send a pull request if you want to

**Comment by freshtechtips** [comment]
> > Perfect, I already fixed it but you are more than welcome to do it
> 
> Maybe we can do one thing, could u review my changed code and see if my solution aligns/matches well with your change? If in case, its the same, I will wait for your PR to be created and merged and till then, I will use my fork.

Fell free to send me your code so I can review it

**Comment by milindgoel15** [comment]
> f you do plan on fixing the toolbar issue then please tell me so I don't do it, send your pull request after that so everyone can use your feature

I fixed my toolbar issue in [this commit in my fork](https://github.com/milindgoel15/flutter-quill/commit/036ac4c740ba32a8c5a65f85e50a38266143e766). 

Created my PR in https://github.com/singerdmx/flutter-quill/pull/1438

**Comment by milindgoel15** [comment]
@freshtechtips another thing i faced while on android, whenever I change the value of the checkbox, the keyboard pops up if it was hidden. Could you do something such that, if the checkbox value is changed and keyboard is not in focus, it doesn't pop up.

I couldn't find the code for this so maybe you can handle it.

**Comment by freshtechtips** [comment]
@milindgoel15 Hi, can you close this issue as it's no longer an issue in the latest version??

**Comment by freshtechtips** [comment]
> @freshtechtips another thing i faced while on android,
> 
> * whenever I change the value of the checkbox, the keyboard pops up if it was hidden. Could you do something such that, if the checkbox value is changed and keyboard is not in focus, it doesn't pop up. I couldn't find the code for this so maybe you can handle it.
> * The searchbar UI of the toolbar is really terrible.
>   ![image](https://user-images.githubusercontent.com/45682747/276611591-5d0b090c-5376-43e6-ab44-a51ec48c85a0.png)
> * Could you [fix this issue](https://github.com/singerdmx/flutter-quill/issues/1337) as well.

I forgot about it, I will look into it now

**Comment by milindgoel15** [comment]
> It's hard enough to put all this together on a smartphone screen.

Perhaps the UI could be design liked this:
![Screenshot_2023-10-23-08-00-14-686_com.android.chrome.jpg](https://github.com/singerdmx/flutter-quill/assets/45682747/1279acd3-6375-48d7-a819-ce4768fe9fdb)

> Probably it's possible to add bottom paddings to all the buttons to have all the searchbar elements at one line, it should look a bit prettier.

I would make the search box size the same as its parent height. To match its height with the container height. Adding padding to other side icons is not necessary.

Although I would prefer my design prototype as it displays the search bar and having a three dot menu or expandable icon to show different search options makes it easier to implement more options.

**Comment by freshtechtips** [comment]
> > It's hard enough to put all this together on a smartphone screen.
> 
> Perhaps the UI could be design liked this:
> ![Screenshot_2023-10-23-08-00-14-686_com.android.chrome.jpg](https://github.com/singerdmx/flutter-quill/assets/45682747/1279acd3-6375-48d7-a819-ce4768fe9fdb)
> 
> > Probably it's possible to add bottom paddings to all the buttons to have all the searchbar elements at one line, it should look a bit prettier.
> 
> I would make the search box size the same as its parent height. To match its height with the container height. Adding padding to other side icons is not necessary.
> 
> Although I would prefer my design prototype as it displays the search bar and having a three dot menu or expandable icon to show different search options makes it easier to implement more options.

I will look into that in the pull request that will be sent today

I will probably add a callback to that
