### ISSUE TITLE
Pasting paragraph with links doesn't linkify

### ISSUE THREAD

**Issue by jezell** [singerdmx/flutter-quill#1432]
If you paste a link directly, it gets linkified. However, if you paste a larger amount of text which contains links in the middle, the links in the text don't get linkified.

**Comment by singerdmx** [comment]
The logic is using regex to recognize the string

**Comment by jezell** [comment]
@singerdmx yes, but the regex doesn't seem to be applying properly against parts of the text. For example, pasting: "this is a test https://www.google.com" doesn't get linkified, but pasting "https://www.google.com" does

**Comment by mboyamike** [comment]
Is there a way to modify the regex that is exposed by the API?

**Comment by freshtechtips** [comment]
> Is there a way to modify the regex that is exposed by the API?

Hi, I will look into that and if not I will add it as feature

**Comment by freshtechtips** [comment]
> If you paste a link directly, it gets linkified. However, if you paste a larger amount of text which contains links in the middle, the links in the text don't get linkified.

Issue fixed and I also will provide a way to override the regex

**Comment by freshtechtips** [comment]
> The logic is using regex to recognize the string

If you merge the last pull request then you might want to consider closing this issue since there are too many issues that aren't closed and it's already solved

**Comment by mboyamike** [comment]
Thank you @freshtechtips

**Comment by freshtechtips** [comment]
> If you paste a link directly, it gets linkified. However, if you paste a larger amount of text which contains links in the middle, the links in the text don't get linkified.

You can try the latest version:
```yaml
flutter_quill: ^7.4.15
```
it should be fixed

**Comment by freshtechtips** [comment]
Hi @singerdmx, can you close this issue as it's not an issue anymore?? you can test it and see

**Comment by freshtechtips** [comment]
> If you paste a link directly, it gets linkified. However, if you paste a larger amount of text which contains links in the middle, the links in the text don't get linkified.

Hi, can you close this issue as it's not an issue anymore?? you can test it and see
