### ISSUE TITLE
We will get exception in AdaptiveTextSelectionToolbar widget when using custom app that doesn't have DefaultCupertinoLocalizations.delegate

### ISSUE THREAD

**Issue by freshtechtips** [singerdmx/flutter-quill#1435]
I must mention to anyone new to this library like me, that we are using the AdaptiveTextSelectionToolbar widget and it requires those four delegates in the localizationsDelegates

If you are using a custom app like FluentApp you need to override the **localizationsDelegates**

with the following:

```dart
localizationsDelegates: const [
        DefaultCupertinoLocalizations.delegate,
        DefaultMaterialLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
```
and make sure to add the other delegates if needed

I have sent a [pull request](https://github.com/bdlukaa/fluent_ui/pull/946/) to them and if it gets approved by [fluent_ui](https://pub.dev/packages/fluent_ui) maintainers then you don't have to do this but still good to mention to anyone who could face this issue in the future if he uses a different app widget

and also I have more fixes to compatibility with FluentApp and should be available in the next pull request in this repository

**Comment by milindgoel15** [comment]
You probably experienced the issue since you were on mac platform and mac uses Cupertino locales (ig). Hence the issue. 


Does every platform need to use their own locale system?

**Comment by freshtechtips** [comment]
> You probably experienced the issue since you were on mac platform and mac uses Cupertino locales (ig). Hence the issue. 
> 
> 
> Does every platform need to use their own locale system? 

Yes, and fluent app widgets don't include Cupertino localizations by default, so you have to do this manually

The same error applies to iOS.

Can you go to the discussion and see the latest vote there??
