### ISSUE TITLE
Failed assertion: line 895 pos 12: '!debugNeedsLayout': is not true. in text_selectation.dart

### ISSUE THREAD

**Issue by EchoEllet** [singerdmx/flutter-quill#1436]
I'm not sure about this one but to fix it I need to understand the library in more deep details

so I will leave it for someone else for now

```
Restarted application in 761ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#6e322](dirty, state: _OverlayEntryWidgetState#57b84):
'package:flutter/src/rendering/paragraph.dart': Failed assertion: line 895 pos 12: '!debugNeedsLayout': is not true.

The relevant error-causing widget was
FluentApp
When the exception was thrown, this was the stack
#2      RenderParagraph.getOffsetForCaret
#3      RenderParagraphProxy.getOffsetForCaret
#4      RenderEditableTextLine.getOffsetForCaret
#5      RenderEditableTextLine.getLocalRectForCaret
#6      RenderEditor.getLocalRectForCaret
#7      RawEditorState._getGlyphHeights
#8      RawEditorState.contextMenuAnchors
#9      RawEditor.defaultContextMenuBuilder
#10     RawEditorState._updateOrDisposeSelectionOverlayIfNeeded.<anonymous closure>
#11     EditorTextSelectionOverlay.showToolbar.<anonymous closure>
#12     _OverlayEntryWidgetState.build
#13     StatefulElement.build
#14     ComponentElement.performRebuild
#15     StatefulElement.performRebuild
#16     Element.rebuild
#17     StatefulElement.update
#18     Element.updateChild
#19     Element.updateChildren
#20     MultiChildRenderObjectElement.update
#21     Element.updateChild
#22     ComponentElement.performRebuild
#23     StatefulElement.performRebuild
#24     Element.rebuild
#25     StatefulElement.update
#26     Element.updateChild
#27     ComponentElement.performRebuild
#28     Element.rebuild
#29     ProxyElement.update
#30     Element.updateChild
#31     ComponentElement.performRebuild
#32     Element.rebuild
#33     ProxyElement.update
#34     _InheritedNotifierElement.update
#35     Element.updateChild
#36     ComponentElement.performRebuild
#37     StatefulElement.performRebuild
#38     Element.rebuild
#39     StatefulElement.update
#40     Element.updateChild
#41     ComponentElement.performRebuild
#42     Element.rebuild
#43     ProxyElement.update
#44     _InheritedNotifierElement.update
#45     Element.updateChild
#46     ComponentElement.performRebuild
#47     StatefulElement.performRebuild
#48     Element.rebuild
#49     StatefulElement.update
#50     Element.updateChild
#51     ComponentElement.performRebuild
#52     StatefulElement.performRebuild
#53     Element.rebuild
#54     StatefulElement.update
#55     Element.updateChild
#56     SingleChildRenderObjectElement.update
#57     Element.updateChild
#58     SingleChildRenderObjectElement.update
#59     Element.updateChild
#60     ComponentElement.performRebuild
#61     Element.rebuild
#62     ProxyElement.update
#63     Element.updateChild
#64     ComponentElement.performRebuild
#65     StatefulElement.performRebuild
#66     Element.rebuild
#67     StatefulElement.update
#68     Element.updateChild
#69     ComponentElement.performRebuild
#70     Element.rebuild
#71     ProxyElement.update
#72     _InheritedNotifierElement.update
#73     Element.updateChild
#74     SingleChildRenderObjectElement.update
#75     Element.updateChild
#76     ComponentElement.performRebuild
#77     StatefulElement.performRebuild
#78     Element.rebuild
#79     StatefulElement.update
#80     Element.updateChild
#81     ComponentElement.performRebuild
#82     Element.rebuild
#83     ProxyElement.update
#84     Element.updateChild
#85     ComponentElement.performRebuild
#86     Element.rebuild
#87     ProxyElement.update
#88     Element.updateChild
#89     ComponentElement.performRebuild
#90     Element.rebuild
#91     ProxyElement.update
#92     Element.updateChild
#93     ComponentElement.performRebuild
#94     Element.rebuild
#95     StatelessElement.update
#96     Element.updateChild
#97     ComponentElement.performRebuild
#98     StatefulElement.performRebuild
#99     Element.rebuild
#100    StatefulElement.update
#101    Element.updateChild
#102    ComponentElement.performRebuild
#103    Element.rebuild
#104    ProxyElement.update
#105    Element.updateChild
#106    ComponentElement.performRebuild
#107    Element.rebuild
#108    ProxyElement.update
#109    Element.updateChild
#110    ComponentElement.performRebuild
#111    Element.rebuild
#112    ProxyElement.update
#113    Element.updateChild
#114    ComponentElement.performRebuild
#115    Element.rebuild
#116    ProxyElement.update
#117    Element.updateChild
#118    ComponentElement.performRebuild
#119    Element.rebuild
#120    StatelessElement.update
#121    Element.updateChild
#122    ComponentElement.performRebuild
#123    Element.rebuild
#124    ProxyElement.update
#125    Element.updateChild
#126    ComponentElement.performRebuild
#127    Element.rebuild
#128    StatelessElement.update
#129    Element.updateChild
#130    ComponentElement.performRebuild
#131    StatefulElement.performRebuild
#132    Element.rebuild
#133    StatefulElement.update
#134    Element.updateChild
#135    ComponentElement.performRebuild
#136    Element.rebuild
#137    StatelessElement.update
#138    Element.updateChild
#139    SingleChildRenderObjectElement.update
#140    Element.updateChild
#141    ComponentElement.performRebuild
#142    Element.rebuild
#143    StatelessElement.update
#144    Element.updateChild
#145    ComponentElement.performRebuild
#146    Element.rebuild
#147    StatelessElement.update
#148    Element.updateChild
#149    ComponentElement.performRebuild
#150    Element.rebuild
#151    StatelessElement.update
#152    Element.updateChild
#153    ComponentElement.performRebuild
#154    Element.rebuild
#155    ProxyElement.update
#156    Element.updateChild
#157    ComponentElement.performRebuild
#158    Element.rebuild
#159    ProxyElement.update
#160    Element.updateChild
#161    SingleChildRenderObjectElement.update
#162    Element.updateChild
#163    ComponentElement.performRebuild
#164    StatefulElement.performRebuild
#165    Element.rebuild
#166    StatefulElement.update
#167    Element.updateChild
#168    SingleChildRenderObjectElement.update
#169    Element.updateChild
#170    ComponentElement.performRebuild
#171    Element.rebuild
#172    ProxyElement.update
#173    _InheritedNotifierElement.update
#174    Element.updateChild
#175    ComponentElement.performRebuild
#176    StatefulElement.performRebuild
#177    Element.rebuild
#178    StatefulElement.update
#179    Element.updateChild
#180    ComponentElement.performRebuild
#181    StatefulElement.performRebuild
#182    Element.rebuild
#183    StatefulElement.update
#184    Element.updateChild
#185    ComponentElement.performRebuild
#186    Element.rebuild
#187    ProxyElement.update
#188    Element.updateChild
#189    ComponentElement.performRebuild
#190    StatefulElement.performRebuild
#191    Element.rebuild
#192    StatefulElement.update
#193    Element.updateChild
#194    SingleChildRenderObjectElement.update
#195    Element.updateChild
#196    ComponentElement.performRebuild
#197    Element.rebuild
#198    ProxyElement.update
#199    _InheritedNotifierElement.update
#200    Element.updateChild
#201    ComponentElement.performRebuild
#202    StatefulElement.performRebuild
#203    Element.rebuild
#204    StatefulElement.update
#205    Element.updateChild
#206    ComponentElement.performRebuild
#207    StatefulElement.performRebuild
#208    Element.rebuild
#209    StatefulElement.update
#210    Element.updateChild
#211    ComponentElement.performRebuild
#212    Element.rebuild
#213    ProxyElement.update
#214    Element.updateChild
#215    ComponentElement.performRebuild
#216    StatefulElement.performRebuild
#217    Element.rebuild
#218    StatefulElement.update
#219    Element.updateChild
#220    SingleChildRenderObjectElement.update
#221    Element.updateChild
#222    ComponentElement.performRebuild
#223    Element.rebuild
#224    ProxyElement.update
#225    _InheritedNotifierElement.update
#226    Element.updateChild
#227    ComponentElement.performRebuild
#228    StatefulElement.performRebuild
#229    Element.rebuild
#230    StatefulElement.update
#231    Element.updateChild
#232    ComponentElement.performRebuild
#233    StatefulElement.performRebuild
#234    Element.rebuild
#235    StatefulElement.update
#236    Element.updateChild
#237    SingleChildRenderObjectElement.update
#238    Element.updateChild
#239    ComponentElement.performRebuild
#240    Element.rebuild
#241    ProxyElement.update
#242    _InheritedNotifierElement.update
#243    Element.updateChild
#244    ComponentElement.performRebuild
#245    StatefulElement.performRebuild
#246    Element.rebuild
#247    StatefulElement.update
#248    Element.updateChild
#249    ComponentElement.performRebuild
#250    StatefulElement.performRebuild
#251    Element.rebuild
#252    StatefulElement.update
#253    Element.updateChild
#254    ComponentElement.performRebuild
#255    Element.rebuild
#256    StatelessElement.update
#257    Element.updateChild
#258    SingleChildRenderObjectElement.update
#259    Element.updateChild
#260    ComponentElement.performRebuild
#261    Element.rebuild
#262    ProxyElement.update
#263    _InheritedNotifierElement.update
#264    Element.updateChild
#265    ComponentElement.performRebuild
#266    StatefulElement.performRebuild
#267    Element.rebuild
#268    StatefulElement.update
#269    Element.updateChild
#270    ComponentElement.performRebuild
#271    StatefulElement.performRebuild
#272    Element.rebuild
#273    StatefulElement.update
#274    Element.updateChild
#275    ComponentElement.performRebuild
#276    Element.rebuild
#277    ProxyElement.update
#278    Element.updateChild
#279    ComponentElement.performRebuild
#280    StatefulElement.performRebuild
#281    Element.rebuild
#282    StatefulElement.update
#283    Element.updateChild
#284    ComponentElement.performRebuild
#285    Element.rebuild
#286    ProxyElement.update
#287    Element.updateChild
#288    ComponentElement.performRebuild
#289    StatefulElement.performRebuild
#290    Element.rebuild
#291    StatefulElement.update
#292    Element.updateChild
#293    ComponentElement.performRebuild
#294    Element.rebuild
#295    ProxyElement.update
#296    Element.updateChild
#297    ComponentElement.performRebuild
#298    StatefulElement.performRebuild
#299    Element.rebuild
#300    StatefulElement.update
#301    Element.updateChild
#302    ComponentElement.performRebuild
#303    StatefulElement.performRebuild
#304    Element.rebuild
#305    StatefulElement.update
#306    Element.updateChild
#307    ComponentElement.performRebuild
#308    Element.rebuild
#309    ProxyElement.update
#310    Element.updateChild
#311    ComponentElement.performRebuild
#312    Element.rebuild
#313    ProxyElement.update
#314    Element.updateChild
#315    ComponentElement.performRebuild
#316    StatefulElement.performRebuild
#317    Element.rebuild
#318    StatefulElement.update
#319    Element.updateChild
#320    ComponentElement.performRebuild
#321    StatefulElement.performRebuild
#322    Element.rebuild
#323    BuildOwner.buildScope
#324    WidgetsBinding.drawFrame
#325    RendererBinding._handlePersistentFrameCallback
#326    SchedulerBinding._invokeFrameCallback
#327    SchedulerBinding.handleDrawFrame
#328    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
#332    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 2027 libraries in 482ms (compile: 32 ms, reload: 72 ms, reassemble: 164 ms).

```

**Comment by milindgoel15** [comment]
Also faced this while testing on my fork in fluentapp. Tho i can't remember if I faced this exact same issue on Android.

**Comment by dushuning** [comment]
======== Exception caught by gestures library ======================================================
The following assertion was thrown while handling a pointer data packet:
'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 2926 pos 12: '!debugNeedsLayout': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2926:12)
#3      RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2913:12)
#4      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#5      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#6      RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:88:24)
#7      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#8      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:83:21)
#9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#10     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#12     RenderClipRect.hitTest (package:flutter/src/rendering/proxy_box.dart:1530:18)
#13     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2861:25)
#14     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#15     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2856:33)
#16     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:632:12)
#17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#18     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2861:25)
#19     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#20     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2856:33)
#21     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:632:12)
#22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#23     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:350:19)
#24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#25     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#26     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#27     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#28     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:559:18)
#29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#32     RenderPhysicalShape.hitTest (package:flutter/src/rendering/proxy_box.dart:2104:18)
#33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#34     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:173:19)
#35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#37     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2861:25)
#38     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#39     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2856:33)
#40     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:414:12)
#41     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#42     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:88:24)
#43     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#44     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:83:21)
#45     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#46     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2861:25)
#47     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#48     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2856:33)
#49     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:632:12)
#50     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#51     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2861:25)
#52     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#53     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2856:33)
#54     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:414:12)
#55     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#56     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#57     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#58     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#59     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#60     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1990:18)
#61     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#62     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#63     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#65     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3604:31)
#66     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#67     RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2522:22)
#68     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:836:31)
#69     BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:766:12)
#70     RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2518:19)
#71     RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2512:12)
#72     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#73     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#74     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#75     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#76     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#77     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#78     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3734:31)
#79     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#80     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#81     _RenderTheaterMixin.hitTestChildren.childHitTest (package:flutter/src/widgets/overlay.dart:985:81)
#82     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#83     _RenderTheaterMixin.hitTestChildren (package:flutter/src/widgets/overlay.dart:986:22)
#84     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#85     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#86     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#87     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3857:17)
#88     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#89     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:173:19)
#90     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#91     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#92     _RenderTheaterMixin.hitTestChildren.childHitTest (package:flutter/src/widgets/overlay.dart:985:81)
#93     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#94     _RenderTheaterMixin.hitTestChildren (package:flutter/src/widgets/overlay.dart:986:22)
#95     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#96     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#97     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#98     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#99     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#100    RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1990:18)
#101    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#102    RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:559:18)
#103    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#104    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#105    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#106    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#107    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#108    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#109    RenderTapRegionSurface.hitTest (package:flutter/src/widgets/tap_region.dart:214:28)
#110    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#111    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#112    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#113    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#114    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#115    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#116    RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2861:25)
#117    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#118    RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2856:33)
#119    RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:632:12)
#120    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#121    RenderView.hitTest (package:flutter/src/rendering/view.dart:211:14)
#122    RendererBinding.hitTestInView (package:flutter/src/rendering/binding.dart:615:34)
#123    GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:391:7)
#124    GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#125    GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#126    GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#127    _invoke1 (dart:ui/hooks.dart:328:13)
#128    PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#129    _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

please help， how to fix it?

**Comment by EchoEllet** [comment]
This issue has been closed, consider filing a new issue if you're still facing this in the latest version.
