### ISSUE TITLE
 [Mobile]

### ISSUE THREAD

**Issue by Ajy74** [singerdmx/flutter-quill#1445]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here.

./../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.5.0/lib/src/widgets/raw_editor/raw_editor.dart:364:7: Error: No named parameter with the name 'onLiveTextInput'.
      onLiveTextInput: null,
      ^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.

static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\mourya\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Ajy74** [comment]
please suggest solution

**Comment by freshtechtips** [comment]
Hi, did you try to clean the project and flutter pub again?? make sure to use the latest version of flutter, flutter_quill_extensions, and flutter_quill

Also, try
```yaml
flutter_quill: ^7.4.16
```

even though I'm pretty sure I didn't touch that in the latest version `7.5.0`

if it's still doesn't help,
please delete
`./../AppData/Local/Pub/Cache/hosted/pub.dev/`
folder and try again

**Comment by Ajy74** [comment]
i have tried already clean the project and flutter pub again . even i tried by downgrading sdk , upgrading sdk and also from stable to beta switch but all time something different happened  .  

also it is not specific to android only also same for web

**Comment by freshtechtips** [comment]
> i have tried already clean the project and flutter pub again . even i tried by downgrading sdk , upgrading sdk and also from stable to beta switch but all time something different happened  .  
> 
> also it is not specific to android only also same for web  .

Did you try the old version of Flutter Quill??

Did you try to delete the pub cache folder??

**Comment by freshtechtips** [comment]
> ^^^^^^^^^^^^^^^

Can you send the error message for the web because gradle is not available for the Flutter web?

**Comment by freshtechtips** [comment]
> i have tried already clean the project and flutter pub again . even i tried by downgrading sdk , upgrading sdk and also from stable to beta switch but all time something different happened .
> 
> also it is not specific to android only also same for web .

Please let me know if you still facing the issue.

**Comment by freshtechtips** [comment]
> My issue is about [Mobile]
> 
> I have tried running `example` directory successfully before creating an issue here.
> 
> ./../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.5.0/lib/src/widgets/raw_editor/raw_editor.dart:364:7: Error: No named parameter with the name 'onLiveTextInput'. onLiveTextInput: null, ^^^^^^^^^^^^^^^ ../../flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.
> 
> static List getEditableButtonItems({ ^^^^^^^^^^^^^^^^^^^^^^ Target kernel_snapshot failed: Exception
> 
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command 'C:\Users\mourya\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 11s Exception: Gradle task assembleDebug failed with exit code 1

I just checked this issue and it has been solved, if you still face this issue or any others
Do not hesitate to contact us
