### ISSUE TITLE
[Web] Toolbar - the font-family dropdown's label is huge

### ISSUE THREAD

**Issue by sundar-rajavelu** [singerdmx/flutter-quill#1450]
In the toolbar, the font-family dropdown's label is huge and there seems to be noway to reduce this size.
The following was tested for the flutter Web. Here is the sample code:
```
        QuillController _controller = QuillController.basic();
        QuillProvider(
          configurations: QuillConfigurations(
            controller: _controller,
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              QuillToolbar.basic(),
              Expanded(
                child: QuillEditor.basic(
                  readOnly: false,
                ),
              )
            ],
          ),
        ),
```
<img width="1271" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/38674104/e690857d-9942-4f78-8e89-8af41bfaff93">

**Comment by freshtechtips** [comment]
I was refactoring things and the default was 40 I don't know why so I made it 40 as the default 
in the new pull request that I sent today, I have changed this and made the icon size just like the others and you can customize it in the following way:

<img width="1092" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/73608287/6e50a6c7-8fce-467b-9dc8-3608a9d194ff">

it will by default be the same as the base option

if you still have any issues, open a new issue and we will do our best to solve the issues

Do not hesitate to contact us if you want to

**Comment by sundar-rajavelu** [comment]
It works like a charm now. Thank you!

**Comment by freshtechtips** [comment]
> It works like a charm now. Thank you!

You are welcome!!
