### ISSUE TITLE
[Web] Changing the font-family list has no effect

### ISSUE THREAD

**Issue by sundar-rajavelu** [singerdmx/flutter-quill#1451]
Changing the list of font families through toolbar configuration has no effect on the list of the font families listed in the dropdown. Please see the following sample code and the image.
```
        QuillController _controller = QuillController.basic();
        QuillProvider(
          configurations: QuillConfigurations(
            controller: _controller,
            toolbarConfigurations: const QuillToolbarConfigurations(
              fontFamilyValues: {
                'Sans Serif': 'Sans Serif',
                'Courier New': 'Courier New',
                'Times New Roman': 'Times New Roman',
                'Clear': 'Clear'
              },
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              QuillToolbar.basic(),
              Expanded(
                child: QuillEditor.basic(
                  readOnly: false,
                ),
              )
            ],
          ),
        ),
```
The following was tested with Flutter-web. 

<img width="520" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/38674104/9df59552-1be8-493a-8bf3-74e73ff873e7">

**Comment by freshtechtips** [comment]
Thank you for the report. This issue has been fixed today, please upgrade to 

```yaml
flutter_quill: ^7.7.0
```

if you still face this issue or other issue please open a new issue.

**Comment by sundar-rajavelu** [comment]
Great, Thank you!

**Comment by freshtechtips** [comment]
> Great, Thank you!

Don't mention it, I cause that bug in the first place, so it's my responsibility to fix it

Thank you again for the report.

**Comment by freshtechtips** [comment]
> Changing the list of font families through toolbar configuration has no effect on the list of the font families listed in the dropdown. Please see the following sample code and the image.
> ```
>         QuillController _controller = QuillController.basic();
>         QuillProvider(
>           configurations: QuillConfigurations(
>             controller: _controller,
>             toolbarConfigurations: const QuillToolbarConfigurations(
>               fontFamilyValues: {
>                 'Sans Serif': 'Sans Serif',
>                 'Courier New': 'Courier New',
>                 'Times New Roman': 'Times New Roman',
>                 'Clear': 'Clear'
>               },
>             ),
>           ),
>           child: Column(
>             mainAxisSize: MainAxisSize.min,
>             children: [
>               QuillToolbar.basic(),
>               Expanded(
>                 child: QuillEditor.basic(
>                   readOnly: false,
>                 ),
>               )
>             ],
>           ),
>         ),
> ```
> The following was tested with Flutter-web. 
> 
> <img width="520" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/38674104/9df59552-1be8-493a-8bf3-74e73ff873e7">
> 
> 

Hey @singerdmx, shouldn't we define the font family values in the shared configurations instead?? So we use it in the editor too?? The previous implementation was defining the font family values in the toolbar only, so I kept it that way.

**Comment by freshtechtips** [comment]
Hey @singerdmx, shouldn't we define the font family values in the shared configurations instead?? So we use it in the editor too?? The previous implementation was defining the font family values in the toolbar only, so I kept it that way.
