### ISSUE TITLE
[Mobile] QuillIconTheme totally broken

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1460]
What have you guys done? :)

QuillIconTheme does not working (colors, size, border radius)

**Comment by freshtechtips** [comment]
This is not a stable release yet we had to break things to refactor others, give us just more days and we will make sure to fix everything

**Comment by freshtechtips** [comment]
> What have you guys done? :)
> 
> QuillIconTheme does not working (colors, size, border radius)

Can you tell me how you are customizing the buttons?? because in version 7.10.0 we have removed the old way of customizing things

**Comment by freshtechtips** [comment]
<img width="1284" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/73608287/6e35e989-8448-4e0a-b9d8-d03a28a11d08">
Everything seems to be working. please update to the latest version since a lot of the old configurations is no deprecated or removed so the logic can't missbehave

**Comment by freshtechtips** [comment]
I just checked this issue and it has been solved, if you still face this issue or any others
Do not hesitate to contact us

Thank you once again for the reports.

**Comment by mark8044** [comment]
This is working, thanks 👍
