### ISSUE TITLE
QuillBaseToolbarConfigurations not found when using QuillBaseToolbar

### ISSUE THREAD

**Issue by FelixYew** [singerdmx/flutter-quill#1463]
QuillBaseToolbarConfigurations not found when using QuillBaseToolbar

I think is related to base_configurations.dart not export

**Comment by freshtechtips** [comment]
Thank you for the report, the issue has been solved and should be updated in the next pull request

**Comment by freshtechtips** [comment]
There are other issues that we just solved today

**Comment by freshtechtips** [comment]
This issue will be closed as it is fixed (we will publish the changes soon)
 but if you have any other questions or issues
Please do not hesitate to contact us
