### ISSUE TITLE
[Mobile] Error: The method 'QuillIconButton' isn't defined for the class 'CameraButton'.

### ISSUE THREAD

**Issue by wkdgus1164** [singerdmx/flutter-quill#1465]
My issue is about Android.

### 1. Situation:
- Firstly, used latest version of `flutter_quill` and `flutter_quill_extensions`.
- Encountered error same as below.
- Changed package version to stable release mentioned from documentation:
```yaml
flutter_quill: ^7.4.16
flutter_quill_extensions: ^0.5.0
```

<details>
  <summary>Other packages:</summary>

```dart
cupertino_icons: ^1.0.2
image_picker: ^1.0.4
path_provider: ^2.1.1
filesystem_picker: ^4.0.0
file_picker: ^6.0.0
path: ^1.8.3
flutter_quill: ^7.4.16
flutter_quill_extensions: ^0.5.0
  ```
</details>

### 2. Error log:
```bash
/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-0.5.0/lib/embeds/toolbar/formula_button.dart:37:12: Error: The method 'QuillIconButton' isn't defined for the class 'FormulaButton'.
- 'FormulaButton' is from 'package:flutter_quill_extensions/embeds/toolbar/formula_button.dart' ('/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-0.5.0/lib/embeds/toolbar/formula_button.dart').
formula_button.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'QuillIconButton'.
    return QuillIconButton(
           ^^^^^^^^^^^^^^^
```
![image](https://github.com/singerdmx/flutter-quill/assets/22370829/6a109eae-21e5-437f-9145-7f31e0682c94)

### 3. What I did:
- Removed `embedButtons` which provides image upload, video upload I think. Basic functions are running well.
- After adding extensions package, and added `embedButtons` option on `QuilToolbar`'s `configuration` and `QuillEditor`'s `configuration`, an error above has been encountered.

**Comment by freshtechtips** [comment]
Thank you for the report, sorry but flutter_quill_extensions hasn't been updated for a while and in order to fix all of this we need to update it first, try using version

```yaml
7.4.14
```

**Comment by wkdgus1164** [comment]
Thanks for the fast reply.
I tried to use `7.4.14`, and I could not use `QuillProvider` with wrapping `QuillToolbar` and `QuillEditor`.

Is this correct I cannot use 'QuillProvider`?
If then, how can I confugure customize options?

![image](https://github.com/singerdmx/flutter-quill/assets/22370829/65422ac4-1830-49e0-b635-ca8f81d1c721)

### Error log:
```
The method 'QuillProvider' isn't defined for the type '_EditorViewState'.\nTry correcting the name to the name of an existing method, or defining a method named 'QuillProvider'."
```

**Comment by freshtechtips** [comment]
> Thanks for the fast reply. I tried to use `7.4.14`, and I could not use `QuillProvider` with wrapping `QuillToolbar` and `QuillEditor`.
> 
> Is this correct I cannot use `QuillProvider`? If then, how can I confugure customize options?
> 
> ![image](https://user-images.githubusercontent.com/22370829/277735874-65422ac4-1830-49e0-b635-ca8f81d1c721.png)
> 
> ### Error log:
> ```
> The method 'QuillProvider' isn't defined for the type '_EditorViewState'.
> Try correcting the name to the name of an existing method, or defining a method named 'QuillProvider'.
> ```
> 
> If this way is not stable for production level, it would be appreciate to recommend me a latest stable version which are running completely with `flutter_quill_extensions`.

If you use old versions of quill then you will need to migrate to the old configurations approach and jut remove the QuillProvider

**Comment by freshtechtips** [comment]
> Thanks for the fast reply. I tried to use `7.4.14`, and I could not use `QuillProvider` with wrapping `QuillToolbar` and `QuillEditor`.
> 
> Is this correct I cannot use `QuillProvider`? If then, how can I confugure customize options?
> 
> ![image](https://user-images.githubusercontent.com/22370829/277735874-65422ac4-1830-49e0-b635-ca8f81d1c721.png)
> 
> ### Error log:
> ```
> The method 'QuillProvider' isn't defined for the type '_EditorViewState'.
> Try correcting the name to the name of an existing method, or defining a method named 'QuillProvider'.
> ```
> 
> If this way is not stable for production level, it would be appreciate to recommend me a latest stable version which are running completely with `flutter_quill_extensions`.

I'm working on alternative flutter quill extensions which will be temporary alternative for the one from @Jon-Salmon 
it should be published in the next 7 hours

**Comment by wkdgus1164** [comment]
> If you use old versions of Flutter Quill then you will need to migrate to the old configurations approach and just remove the QuillProvider and define everything in QuillEditor and QuillToolbar

How can I get some guidance for old version migration?

**Comment by freshtechtips** [comment]
> > If you use old versions of Flutter Quill then you will need to migrate to the old configurations approach and just remove the QuillProvider and define everything in QuillEditor and QuillToolbar
> 
> How can I get some guidance for old version migration?

For your case in the image you sent, just remove the`QuillProvider` and you should be ready to go, we don't have migration guide yet because we are in the middle of the process but you can ask us anything and we will do our best to make sure the problem is solved

**Comment by wkdgus1164** [comment]
Yes, after removing `QuillProvider`, everything is just fine.

But I need some guide for
- customzing button disabling (I don't need some button features),
- customizing some buttons' component style,
- image/video upload feature which was enabled in `flutter_quill_extensions` package.

**Comment by freshtechtips** [comment]
> Yes, after removing `QuillProvider`, everything is just fine.
> 
> But I need some guide for
> 
> * customzing button disabling (I don't need some button features),
> * customizing some buttons' component style,
> * image/video upload feature which was enabled in `flutter_quill_extensions` package.

This is why we are refactoring things because the old configurations were hard to customize things for the developer side and the maintainers side

But can you explain which buttons you want to style and disable so I can help you better??? for flutter_quill_extensions we are working on refactoring things, as soon it get released we will all be able to customize everything to fit your needs

**Comment by wkdgus1164** [comment]
I hope to use this package because,
- In my app on this situation, provides only plain text upload feature.

### 1st requirement:
- I hope to add `Link to text` feature to textfield with `flutter_quill`'s `QuillToolbar` and `QuillEditor`.
  - For example, I write `click here!` text in my editor, and make it a text block (double click), and click `Link` button in `QuillToolbar`.
- And because my app only requires `Link to text`, I have to customize `Link to text` button to `Icon + Text` button because users' cannot recognize there is `Link to text` button if there are only one Icon button so small.

### 2nd requirement:
- I hope to attach some images and videos through editor.
- I recognized that `flutter_quill_extensions` package provides `embedButtons` so the user can attach images and videos coded here from [example project](https://github.com/singerdmx/flutter-quill/blob/45b43fa1328c1cbc008fca1941594110158100e8/example/lib/pages/home_page.dart#L302C50-L302C50) i think.

Of couse I need callback functions for my custom styled button and image select, video select.

**Comment by freshtechtips** [comment]
> I hope to use this package because,
> 
> * In my app on this situation, provides only plain text upload feature.
> 
> ### 1st requirement:
> * I hope to add `Link to text` feature to textfield with `flutter_quill`'s `QuillToolbar` and `QuillEditor`.
>   
>   * For example, I write `click here!` text in my editor, and make it a text block (double click), and click `Link` button in `QuillToolbar`.
> * And because my app only requires `Link to text`, I have to customize `Link to text` button to `Icon + Text` button because users' cannot recognize there is `Link to text` button if there are only one Icon button so small.
> 
> ### 2nd requirement:
> * I hope to attach some images and videos through editor.
> * I recognized that `flutter_quill_extensions` package provides `embedButtons` so the user can attach images and videos coded here from [example project](https://github.com/singerdmx/flutter-quill/blob/45b43fa1328c1cbc008fca1941594110158100e8/example/lib/pages/home_page.dart#L302C50-L302C50) i think.
> 
> Of couse I need callback functions for my custom styled button and image select, video select.

Thank you for the report. I will get back to you after some time because the work is still in progress and we hope to add more customizations and features to fit all developers needs

**Comment by wkdgus1164** [comment]
One more time, thanks for fast reply.
I will wait for version update if it will be resolved soon.

**Comment by freshtechtips** [comment]
> One more time, thanks for fast reply. I will wait for version update if it will be resolved soon.

You are welcome. Thank you for your patience.

**Comment by freshtechtips** [comment]
> One more time, thanks for fast reply. I will wait for version update if it will be resolved soon.

This issue will be closed but if you have any other questions or issues
Do not hesitate to contact us

**Comment by wkdgus1164** [comment]
Does the `quill_html_editor` in [pub.dev](https://pub.dev/packages/quill_html_editor) provides similar features with `flutter_quill` package?
I'm not sure you can answer this question, but I am asking because both packages are starting with `quill`.

**Comment by freshtechtips** [comment]
> Does the `quill_html_editor` in [pub.dev](https://pub.dev/packages/quill_html_editor) provides similar features with `flutter_quill` package?
> I'm not sure you can answer this question, but I am asking because both packages are starting with `quill`.

It's seems to be implementation for Quill
They both have the same purpose

Feel free to try both and choose the one that fits your needs

They both should use the same schema of quill delta

Except for some properties we added like mobileWidth, which is not party of the official quill

**Comment by wkdgus1164** [comment]
I'm curious about if I use custom file picker (not using `flutter_quill_extensions` package), can I embed selected image / video to QuillEditor.
