### ISSUE TITLE
[Web] [Mobile] [Desktop] - API breaking changes without major version change

### ISSUE THREAD

**Issue by sundar-rajavelu** [singerdmx/flutter-quill#1472]
Hey note that you are pushing in API breaking changes, without changing the major version number, which is causing issues with our build, when we add your package dependency using ^.

**Comment by singerdmx** [comment]
I wanted to bump the major version 
But different people have different opinions

**Comment by freshtechtips** [comment]
> I wanted to bump the major version But different people have different opinions

I personally don't mind

**Comment by freshtechtips** [comment]
> I wanted to bump the major version But different people have different opinions

I think it's time to add a migration guide, what do you say??

**Comment by singerdmx** [comment]
Of course

**Comment by singerdmx** [comment]
Let's make it a standalone file

**Comment by singerdmx** [comment]
And refer to it in readme

**Comment by freshtechtips** [comment]
> Let's make it a standalone file

Of course

**Comment by freshtechtips** [comment]
> Hey note that you are pushing in API breaking changes, without changing the major version number, which is causing issues with our build, when we add your package dependency using ^.

We have fixed this issue and it should be published after 7 hours as soon this [pull request](https://github.com/singerdmx/flutter-quill/pull/1473) published

**Comment by freshtechtips** [comment]
> Hey note that you are pushing in API breaking changes, without changing the major version number, which is causing issues with our build, when we add your package dependency using ^.

The pull request has been merged and it will be published in less than 7 hours, if you still facing this issue or any other issues or have any questions please feel free to contact us

**Comment by sundar-rajavelu** [comment]
Thanks - Remember to update pub.dev as well for 8.0.0.

**Comment by freshtechtips** [comment]
> Thanks - Remember to update pub.dev as well for 8.0.0.

@singerdmx You know what to do

**Comment by singerdmx** [comment]
published
