### ISSUE TITLE
icon display style have problem

### ISSUE THREAD

**Issue by stoneLee81** [singerdmx/flutter-quill#148]
![image](https://user-images.githubusercontent.com/18001708/114732410-11c83500-9d75-11eb-835c-42d79939e314.png)
There is a problem with the display style, under flutter web

**Comment by gaganyadav80** [comment]
Is it on the web or mobile?
Also share the code snippet of your editor. 
And if you see any error of overflow or something also do share them.

**Comment by stoneLee81** [comment]
I executed flutter-quill demo directly under the web; The os font is chinese, flutter Channel stable, 2.0.4
