### ISSUE TITLE
[Mobile] Autofocus is always triggered

### ISSUE THREAD

**Issue by coolswood** [singerdmx/flutter-quill#1481]
In the latest version, when opening a page with QuillEditor, it is always automatically focused on, I pass the `autoFocus: false` parameter.
I also added the `enableUnfocusOnTapOutside: true` field, but the focus does not go away when clicking outside.

Version: 8.0.0

**Comment by freshtechtips** [comment]
Hi thank you for the report I will debug and check that out as soon as I can

While upgrading flutter SDK to latest version some files got corrected and I had to download them again all with the other tools

![telegram-cloud-photo-size-2-5319116597673185816-y](https://github.com/singerdmx/flutter-quill/assets/73608287/b48acc6e-7e77-4adf-9b57-c03add6002b7)

It take almost half a day to download it again in my local area

give me some time and I will check it out for you

**Comment by freshtechtips** [comment]
> In the latest version, when opening a page with QuillEditor, it is always automatically focused on, I pass the `autoFocus: false` parameter. I also added the `enableUnfocusOnTapOutside: true` field, but the focus does not go away when clicking outside.
> 
> Version: 8.0.0

Hi again, can you send me the code snippet you are using to setup the configuration of the `QuillEditor`?? so I can help you better

**Comment by freshtechtips** [comment]
> In the latest version, when opening a page with QuillEditor, it is always automatically focused on, I pass the `autoFocus: false` parameter. I also added the `enableUnfocusOnTapOutside: true` field, but the focus does not go away when clicking outside.
> 
> Version: 8.0.0

I'm unable to encounter the issue, can you tell me which platform you are testing on?? it would be helpful to send the configurations of quill editor

**Comment by coolswood** [comment]
@freshtechtips 

Yeah, I apologize. I cleaned the cache, rebuilt the project and now autofocus works as it should. 
However, when clicking outside the input field, the focus is still not lost. I'm using the Iphone 15 emulator
```
QuillEditor.basic(
                        configurations: const QuillEditorConfigurations(
                          readOnly: false,
                          autoFocus: false,
                          enableUnfocusOnTapOutside: true,
                        ),
                      ),
```

**Comment by freshtechtips** [comment]
> @freshtechtips
> 
> Yeah, I apologize. I cleaned the cache, rebuilt the project and now autofocus works as it should. However, when clicking outside the input field, the focus is still not lost. I'm using the Iphone 15 emulator
> 
> ```
> QuillEditor.basic(
>                         configurations: const QuillEditorConfigurations(
>                           readOnly: false,
>                           autoFocus: true,
>                           enableUnfocusOnTapOutside: true,
>                         ),
>                       ),
> ```

Hi again, I haven't touch property `enableUnfocusOnTapOutside` yet

currently I have other tasks
but I will add this issue to my todo list and I will fix it as soon as possible

**Comment by singerdmx** [comment]
yeah

**Comment by freshtechtips** [comment]
> yeah

Good, give me a moment to test this on all platforms then let's publish 8.1.0 since we added a new property and removed old one which doesn't make much sense

the new code will be

```dart
const QuillEditorConfigurations(
  autoFocus: true,
  isOnTapOutsideEnabled: true,
  // onTapOutside: (event, focusNode) {
  //   focusNode.unfocus();
  // },
)
```
if the onTapOutside is null then it will only unfocus on the desktop and web, otherwise, we will use the custom callback

if the developer doesn't want to do anything at all he can just pass false to `isOnTapOutsideEnabled`

**Comment by freshtechtips** [comment]
> In the latest version, when opening a page with QuillEditor, it is always automatically focused on, I pass the `autoFocus: false` parameter.
> I also added the `enableUnfocusOnTapOutside: true` field, but the focus does not go away when clicking outside.
> 
> Version: 8.0.0

The bug you are facing is fixed. Please let us know if you face any other issues

Feel free to contact us on GitHub for any questions.
