### ISSUE TITLE
Docx file

### ISSUE THREAD

**Issue by mayank21061** [singerdmx/flutter-quill#1491]
How i can open and edit existing docx file in my flutter app

**Comment by freshtechtips** [comment]
> How i can open and edit existing docx files in my Flutter app

Hi, you need to convert the data of the Microsoft office word file to quill delta and then open it, after made the changes you need to convert it back to Microsoft office word

currently this feature is not supported but thank you for bring that to our attention, we might do this in the future, if you still have any other questions feel free to ask

Thank you for the report

**Comment by iykechukwu** [comment]
Hi?

I am currently working on a project for a customized word processor; I am using Flutter Quill, opening, editing, and storing .docx files seem to be a big challenge, I have managed to convert to Delta but it doesn't pick the formats, any progress on this from your end?
