### ISSUE TITLE
Insert Picture Cropping Function

### ISSUE THREAD

**Issue by molihuan** [singerdmx/flutter-quill#1494]
Can you support the function of inserting and cropping images? I think this function will be very convenient for users.

**Comment by freshtechtips** [comment]
> Can you support the function of inserting and cropping images? I think this function will be very convenient for users.

Hi, thank you for the report, it's on our todo list

**Comment by molihuan** [comment]
> > Can you support the function of inserting and cropping images? I think this function will be very convenient for users.
> 
> Hi, thank you for the report, it's on our todo list

Thank you.

**Comment by freshtechtips** [comment]
This feature will probably be supported in `0.6.5` of `flutter_quill_extensions`

**Comment by freshtechtips** [comment]
> Can you support the function of inserting and cropping images? I think this function will be very convenient for users.

Hi again, this feature is now implemented in the `example`
that requires us to change some things in `flutter_quill` and `flutter_quill_extensions` to allow the developer to support this feature but now you can do it and implement it very easily

If you still have any other questions feel free to ask us on GitHub at any time.
