### ISSUE TITLE
Issue in [Mobile]: Image Pick with 'flutter_quill_extensions'

### ISSUE THREAD

**Issue by jasamin** [singerdmx/flutter-quill#1500]
Hi,
I want to add embedButtons to pick images,but when I run my project,it print some error in 'run console window',so how to fix this ?

> flutter_quill_extensions : ^0.5.0
> flutter_quill: ^7.10.2

```
QuillToolbarConfigurations(
      embedButtons: FlutterQuillEmbeds.buttons(
        onImagePickCallback: _onImagePickCallback,
        showVideoButton: false,
        showCameraButton: false,
        showFormulaButton: false,
        showImageButton: true
      ),
)
```

```
  Future<String> _onImagePickCallback(File file) async {
    final appDocDir = await getApplicationDocumentsDirectory();
    final copiedFile =
    await file.copy('${appDocDir.path}/${path.basename(file.path)}');
    return copiedFile.path.toString();
  }

```

```
../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill_extensions-0.5.0/lib/embeds/toolbar/video_button.dart:56:12: Error: The method **'QuillIconButton'** isn't defined for the class **'VideoButton'.**
 - 'VideoButton' is from 'package:flutter_quill_extensions/embeds/toolbar/video_button.dart' ('../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill_extensions-0.5.0/lib/embeds/toolbar/video_button.dart').
Try correcting the name to the name of an existing method, or defining a method named 'QuillIconButton'.
    return QuillIconButton(
           ^^^^^^^^^^^^^^^
```

**Comment by freshtechtips** [comment]
> Hi, I want to add embedButtons to pick images,but when I run my project,it print some error in 'run console window',so how to fix this ?
> 
> > flutter_quill_extensions : ^0.5.0
> > flutter_quill: ^7.10.2
> 
> ```
> QuillToolbarConfigurations(
>       embedButtons: FlutterQuillEmbeds.buttons(
>         onImagePickCallback: _onImagePickCallback,
>         showVideoButton: false,
>         showCameraButton: false,
>         showFormulaButton: false,
>         showImageButton: true
>       ),
> )
> ```
> 
> ```
>   Future<String> _onImagePickCallback(File file) async {
>     final appDocDir = await getApplicationDocumentsDirectory();
>     final copiedFile =
>     await file.copy('${appDocDir.path}/${path.basename(file.path)}');
>     return copiedFile.path.toString();
>   }
> ```
> 
> ```
> ../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill_extensions-0.5.0/lib/embeds/toolbar/video_button.dart:56:12: Error: The method **'QuillIconButton'** isn't defined for the class **'VideoButton'.**
>  - 'VideoButton' is from 'package:flutter_quill_extensions/embeds/toolbar/video_button.dart' ('../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill_extensions-0.5.0/lib/embeds/toolbar/video_button.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'QuillIconButton'.
>     return QuillIconButton(
>            ^^^^^^^^^^^^^^^
> ```

Hi, unfortunately you can't use the latest stable version of `flutter_quill_extensions` right now, please use `fresh_quill_extensions` instead as temporary alternative or try using the dev version of `flutter_quill_extensions`

**Comment by freshtechtips** [comment]
Please use the latest versions of both flutter_quill and fresh_quill_extensions

```yaml
fresh_quill_extensions: ^0.0.4
flutter_quill: ^8.1.4
```

and everything should work fine, just replace the import package `flutter_quill_extensions` with `fresh_quill_extensions`

but don't worry it will be temporary

let me know if you still facing the issue

**Comment by freshtechtips** [comment]
This issue has been fixed, use the latest pre-release of `flutter_quill_extensions`

if you still facing the issue or have any other issues feel free to ask us

**Comment by jasamin** [comment]
It worked. Thank you for your support !👍

**Comment by jasamin** [comment]
> This issue has been fixed, use the latest pre-release of `flutter_quill_extensions`
> 
> if you still facing the issue or have any other issues feel free to ask us

It worked ! Thank you for your support !

**Comment by freshtechtips** [comment]
> > This issue has been fixed, use the latest pre-release of `flutter_quill_extensions`
> > 
> > if you still facing the issue or have any other issues feel free to ask us
> 
> It worked ! Thank you for your support !
> 

You are welcome.
