### ISSUE TITLE
Flutter does not support the non-standard locale form zh_cn (which might be zh_CN)

### ISSUE THREAD

**Issue by 2426232528** [singerdmx/flutter-quill#1525]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

 flutter_quill: ^8.5.1:  

i am update to 8.5.1, and the page report bug directly 

### Expected results

null

### Actual results

null

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output (optional)

<details><summary>Doctor output</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building FlutterQuillLocalizationsWidget(dependencies:
[QuillProvider, _LocalizationsScope-[GlobalKey#9218f]]):
Flutter does not support the non-standard locale form zh_cn (which might be zh_CN
'package:flutter_localizations/src/material_localizations.dart':
Failed assertion: line 732 pos 9: 'locale.toString() == localeName'

The relevant error-causing widget was:
  FlutterQuillLocalizationsWidget
  FlutterQuillLocalizationsWidget:file:///C:/Users/Administrator.DESKTOP-GV6BOEH/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.5.1/lib/src/widgets/editor/editor.dart:243:19  

When the exception was thrown, this was the stack:
#2      _MaterialLocalizationsDelegate.load.<anonymous closure> (package:flutter_localizations/src/material_localizations.dart:732:9)
#3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#4      _MaterialLocalizationsDelegate.load (package:flutter_localizations/src/material_localizations.dart:727:32)
#5      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
#6      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:589:62)
#7      _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:554:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430:55)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
...     Normal element mounting (61 frames)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#71     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#72     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
...     Normal element mounting (323 frames)
#395    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#396    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#397    Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
#398    Element.updateChildren (package:flutter/src/widgets/framework.dart:3894:32)
#399    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594:17)
#400    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#401    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#402    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#403    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#404    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#405    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#406    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#407    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#408    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#409    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#410    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#411    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#412    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#413    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#414    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#415    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#416    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#417    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#418    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#419    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#420    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#421    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#422    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#423    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#424    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#425    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#426    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#427    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#428    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#429    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#430    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#431    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#432    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#433    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#434    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#435    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#436    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#437    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#438    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#439    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#440    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#441    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#442    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#443    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#444    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#445    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#446    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
#447    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
#448    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#449    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#450    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#451    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#452    _invoke (dart:ui/hooks.dart:170:13)
#453    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#454    _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Flutter does not support the non-standard locale form zh_cn (which might be zh_CN

```

</details>

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by singerdmx** [comment]
zh_cn is supported 
Have you checked translation section of readme?

**Comment by singerdmx** [comment]
Locale('zh', 'cn'), Locale('zh', 'hk')

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Steps to reproduce
> 
> i am update to 8.5.1, and the page report bug directly 
> 
> ### Expected results
> 
> null
> 
> ### Actual results
> 
> null
> 
> ### Code sample
> 
> <details><summary>Code sample</summary>
> 
> ```dart
> [Paste your code here]
> ```
> 
> </details>
> 
> 
> ### Screenshots or Video
> 
> <details>
> <summary>Screenshots / Video demonstration</summary>
> 
> [Upload media here]
> 
> </details>
> 
> 
> ### Logs
> 
> <details><summary>Logs</summary>
> 
> ```console
> [Paste your logs here]
> ```
> 
> </details>
> 
> 
> ### Flutter Doctor output (optional)
> 
> <details><summary>Doctor output</summary>
> 
> ```console
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> The following assertion was thrown building FlutterQuillLocalizationsWidget(dependencies:
> [QuillProvider, _LocalizationsScope-[GlobalKey#9218f]]):
> Flutter does not support the non-standard locale form zh_cn (which might be zh_CN
> 'package:flutter_localizations/src/material_localizations.dart':
> Failed assertion: line 732 pos 9: 'locale.toString() == localeName'
> 
> The relevant error-causing widget was:
>   FlutterQuillLocalizationsWidget
>   FlutterQuillLocalizationsWidget:file:///C:/Users/Administrator.DESKTOP-GV6BOEH/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.5.1/lib/src/widgets/editor/editor.dart:243:19  
> 
> When the exception was thrown, this was the stack:
> #2      _MaterialLocalizationsDelegate.load.<anonymous closure> (package:flutter_localizations/src/material_localizations.dart:732:9)
> #3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
> #4      _MaterialLocalizationsDelegate.load (package:flutter_localizations/src/material_localizations.dart:727:32)
> #5      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
> #6      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:589:62)
> #7      _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:554:5)
> #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430:55)
> #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
> ...     Normal element mounting (61 frames)
> #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
> #71     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
> #72     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
> ...     Normal element mounting (323 frames)
> #395    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
> #396    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
> #397    Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
> #398    Element.updateChildren (package:flutter/src/widgets/framework.dart:3894:32)
> #399    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594:17)
> #400    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #401    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #402    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
> #403    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #404    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
> #405    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #406    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #407    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #408    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
> #409    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #410    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #411    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #412    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
> #413    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
> #414    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #415    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #416    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
> #417    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #418    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
> #419    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #420    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #421    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #422    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
> #423    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
> #424    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #425    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #426    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
> #427    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #428    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
> #429    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #430    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #431    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
> #432    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #433    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
> #434    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #435    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
> #436    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #437    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
> #438    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #439    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #440    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #441    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
> #442    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
> #443    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
> #444    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
> #445    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
> #446    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
> #447    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
> #448    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
> #449    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
> #450    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
> #451    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
> #452    _invoke (dart:ui/hooks.dart:170:13)
> #453    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
> #454    _drawFrame (dart:ui/hooks.dart:140:31)
> (elided 2 frames from class _AssertionError)
> 
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> 
> Another exception was thrown: Flutter does not support the non-standard locale form zh_cn (which might be zh_CN
> 
> ```
> 
> </details>
> 

Hi, thank you for the report, we will check it out soon!

**Comment by 2426232528** [comment]
Thank you so much. You reminded me. I found how to resolve this.

in flutter_quill  8.4.1, Locale('zh', 'cn') works well. When I upgrade to 8.5.1, it is not work.  I change to Locale('zh', 'CN'), it works again

My flutter and dart info:
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision d211f42860 (3 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

Thanks again!

**Comment by singerdmx** [comment]
Oh we should update Readme for this

**Comment by freshtechtips** [comment]
> Thank you so much. You reminded me. I found how to resolve this.
> 
> in flutter_quill  8.4.1, Locale('zh', 'cn') works well. When I upgrade to 8.5.1, it is not work.  I change to Locale('zh', 'CN'), it works again
> 
> My flutter and dart info:
> Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git 
> Framework • revision d211f42860 (3 weeks ago) • 2023-10-25 13:42:25 -0700
> Engine • revision 0545f8705d
> Tools • Dart 3.1.5 • DevTools 2.25.0
> 
> Thanks again!

We are glad to hear the code is now working like expected, but can you send us samples code of the working and non working code??

**Comment by 2426232528** [comment]
@freshtechtips 
ok
`
QuillProvider(
        configurations: QuillConfigurations(
          controller: controller.quillController,
          sharedConfigurations: const QuillSharedConfigurations(
            locale: Locale('zh', 'cn'), // in flutter_quill 8.5.1 not work. useing Locale('zh','CN') it works.
          ),
        ),
        child: Scaffold(
          appBar: AppBar(
            systemOverlayStyle: SystemUiOverlayStyle.dark,
            backgroundColor: Colors.transparent,
            excludeHeaderSemantics: true,
            leading: IconButton(
              icon: const Icon(
                // Icons.arrow_back_ios_new_rounded,
                CupertinoIcons.chevron_back,
                // size: 19,
              ),
              onPressed: () {
                Get.back();
              },
            ),
            title: Text(
              '新增',
              style: Theme.of(context).textTheme.titleMedium,
            ),
            elevation: 0,
          ),
       body: ......
`

**Comment by freshtechtips** [comment]
> @freshtechtips ok
> 
> ```
> QuillProvider(
>         configurations: QuillConfigurations(
>           controller: controller.quillController,
>           sharedConfigurations: const QuillSharedConfigurations(
>             locale: Locale('zh', 'cn'), // in flutter_quill 8.5.1 not work. useing Locale('zh','CN') it works.
>           ),
>         ),
>         child: Scaffold(
>           appBar: AppBar(
>             systemOverlayStyle: SystemUiOverlayStyle.dark,
>             backgroundColor: Colors.transparent,
>             excludeHeaderSemantics: true,
>             leading: IconButton(
>               icon: const Icon(
>                 // Icons.arrow_back_ios_new_rounded,
>                 CupertinoIcons.chevron_back,
>                 // size: 19,
>               ),
>               onPressed: () {
>                 Get.back();
>               },
>             ),
>             title: Text(
>               '新增',
>               style: Theme.of(context).textTheme.titleMedium,
>             ),
>             elevation: 0,
>           ),
>        body: ......
> ```

That's because the name of the locales are:

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/ad5c8c34-b412-4656-857b-2c08cda7490c)

**Comment by freshtechtips** [comment]
@singerdmx 
Should we change them??

**Comment by singerdmx** [comment]
No need. I already updated Readme

**Comment by freshtechtips** [comment]
This issue will be closed as we already found the solution, if you still facing any other issues or have any other questions feel free to ask us at anytime
