### ISSUE TITLE
Flutter_Quill_Extention-> Image-> If to use the zoom option from the image embed menu, we get the red screen Quill Provider is null

### ISSUE THREAD

**Issue by munibkhanali** [singerdmx/flutter-quill#1527]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

Use the Example Project in this repository

Once the application is loaded 
1) Add an image form Gallery is not present in Quill Editor 
2) Click on the image (you will see a popup)
3) Click on the **Zoom** button 

you will see the following screen.

![Simulator Screen Shot - iPhone 14 Pro - 2023-11-13 at 18 28 50](https://github.com/singerdmx/flutter-quill/assets/10357553/19bf71a6-0cd7-4915-989e-983b20883b52)

### Expected results

Application Should not crash

### Actual results

Application is Crashing

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output (optional)

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment]
Thank you for the report, it looks like you have used the master branch which might have things that haven't been released and tested yet, we will take a look at it soon.
