### ISSUE TITLE
Cannot use `QuillBaseToolbar` because `QuillBaseToolbarConfigurations` is not exported

### ISSUE THREAD

**Issue by bambinoua** [singerdmx/flutter-quill#1532]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

I tried to use `QuillBaseToolbar` to specify my own sequence of toolbar buttons but I cound not use it because `QuillBaseToolbarConfigurations` is not exported from package.

### Expected results

```dart
QuillBaseToolbar(
  configuration: QuillBaseToolbarConfigurations(),
)
```

### Actual results

```dart
QuillBaseToolbar(
  configuration: QuillBaseToolbarConfigurations(), // QuillBaseToolbarConfigurations isn't defined
)
```

### Code sample

No code

**Comment by freshtechtips** [comment]
> QuillBaseToolbar

Hi again, did you used the latest version of flutter quill?

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Steps to reproduce
> I tried to use `QuillBaseToolbar` to specify my own sequence of toolbar buttons but I cound not use it because `QuillBaseToolbarConfigurations` is not exported from package.
> 
> ### Expected results
> ```dart
> QuillBaseToolbar(
>   configuration: QuillBaseToolbarConfigurations(),
> )
> ```
> 
> ### Actual results
> ```dart
> QuillBaseToolbar(
>   configuration: QuillBaseToolbarConfigurations(), // QuillBaseToolbarConfigurations isn't defined
> )
> ```
> 
> ### Code sample
> No code
> 
> ### Screenshots or Video
> _No response_
> 
> ### Logs
> _No response_
> 
> ### Flutter Doctor output (optional)
> _No response_

This issue is fixed in the latest versions of `flutter_quill` I think you are using 8.2.0 or something like this

Please try to using the latest version instead which is `8.5.5`
