### ISSUE TITLE
Could not load localizations for Link edit dialog

### ISSUE THREAD

**Issue by bambinoua** [singerdmx/flutter-quill#1534]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

1. Select a portion of text.
2. Press on `Link` button to create an HTML link
3. Get a crash `The instance of FlutterQuillLocalizations.of(context) is null and it is required...`

### Expected results

Link dialog open is expected

### Actual results

Red flutter scree

### Code sample

```dart
MaterialApp(
  localizationDelegates: [
    GlobalMaterialLocalizations.delegate,
    FlutterQuillLocalizations.delegate,    // it is specified!
  ],
),
```

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Steps to reproduce
> 1. Select a portion of text.
> 2. Press on `Link` button to create an HTML link
> 3. Get a crash `The instance of FlutterQuillLocalizations.of(context) is null and it is required...`
> 
> ### Expected results
> Link dialog open is expected
> 
> ### Actual results
> Red flutter scree
> 
> ### Code sample
> ```dart
> MaterialApp(
>   localizationDelegates: [
>     GlobalMaterialLocalizations.delegate,
>     FlutterQuillLocalizations.delegate,    // it is specified!
>   ],
> ),
> ```
> 
> ### Screenshots or Video
> _No response_
> 
> ### Logs
> _No response_
> 
> ### Flutter Doctor output (optional)
> _No response_

Thank you for the report, we will check it out soon

**Comment by freshtechtips** [comment]
I'm unable to get the bug you are facing

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/f9e3792f-928d-4f56-9578-f3b050b0a60f)

Can you update the sample code?

**Comment by freshtechtips** [comment]
> ```dart
> FlutterQuillLocalizations
> ```

Are you running the example code?? if not then are you using a custom toolbar??

**Comment by freshtechtips** [comment]
I'm only able to encounter the issue when removing the 

```dart
FlutterQuillLocalizations.delegate
```

**Comment by bambinoua** [comment]
Ok. I tested on forked and reverted branch. Looks working.
