### ISSUE TITLE
Could not run app using version `8.5.6` on flutter version less than `3.16`

### ISSUE THREAD

**Issue by bambinoua** [singerdmx/flutter-quill#1537]
I could not run the web application because of crash. I think you use `TextScaler` from the latest flutter version? But I used the flutter `3.13.9`. 

So you did **_breaking changes_** without notification.

![Без имени](https://github.com/singerdmx/flutter-quill/assets/45417992/4060dd9f-437e-4492-87a2-5d9ba6ca75e2)

**Comment by freshtechtips** [comment]
> I could not run the web application because of crash. I think you use `TextScaler` from the latest flutter version? But I used the flutter `3.13.9`. 
> 
> So you did **_breaking changes_** without notification.
> 
> ![Без имени](https://github.com/singerdmx/flutter-quill/assets/45417992/4060dd9f-437e-4492-87a2-5d9ba6ca75e2)
> 

Yes, I know we changed the major version, but if we continue this way, the version number will be too high in no time. It's only temporary 

Please update to flutter 3.16

**Comment by freshtechtips** [comment]
> I could not run the web application because of crash. I think you use `TextScaler` from the latest flutter version? But I used the flutter `3.13.9`.
> 
> So you did **_breaking changes_** without notification.
> 
> ![Без имени](https://user-images.githubusercontent.com/45417992/283424032-4060dd9f-437e-4492-87a2-5d9ba6ca75e2.jpg)

Done, we have changed the version to `8.6.0`
Please tell us if you still facing any other issues or have any other questions
