### ISSUE TITLE
`QuillToolbarFontFamilyButton` requires `QuillToolbarProvider` when is used in `QuillBaseToolbar`

### ISSUE THREAD

**Issue by bambinoua** [singerdmx/flutter-quill#1540]
I use `QuillBaseToobar` where I can customize the sequence of toolbar buttons but I get a crash because some buttons (like `QuillToolbarFontFamilyButton`) required `QuillToolbarProvider`. I think it is not required because `QuillBaseToobar` has its own `configurations`.

Actually it is not a bug because I can provide the `QuillToolbarProvider` but it confuses because now I have 2 similar configurations. One is from `QuillToolbarProvider` and another from `QuillBaseToobar`.

**Comment by freshtechtips** [comment]
> I use `QuillBaseToobar` where I can customize the sequence of toolbar buttons but I get a crash because some buttons (like `QuillToolbarFontFamilyButton`) required `QuillToolbarProvider`. I think it is not required because `QuillBaseToobar` has its own `configurations`.
> 
> Actually it is not a bug because I can provide the `QuillToolbarProvider` but it confuses because now I have 2 similar configurations. One is from `QuillToolbarProvider` and another from `QuillBaseToobar`.

Hi, thank you for the report, we will take a look at it soon.

**Comment by freshtechtips** [comment]
> I use `QuillBaseToobar` where I can customize the sequence of toolbar buttons but I get a crash because some buttons (like `QuillToolbarFontFamilyButton`) required `QuillToolbarProvider`. I think it is not required because `QuillBaseToobar` has its own `configurations`.
> 
> Actually it is not a bug because I can provide the `QuillToolbarProvider` but it confuses because now I have 2 similar configurations. One is from `QuillToolbarProvider` and another from `QuillBaseToobar`.



> I use `QuillBaseToobar` where I can customize the sequence of toolbar buttons but I get a crash because some buttons (like `QuillToolbarFontFamilyButton`) required `QuillToolbarProvider`. I think it is not required because `QuillBaseToobar` has its own `configurations`.
> 
> Actually it is not a bug because I can provide the `QuillToolbarProvider` but it confuses because now I have 2 similar configurations. One is from `QuillToolbarProvider` and another from `QuillBaseToobar`.

This issue has been fixed in `8.6.0`, please tell us if you still facing this issue

**Comment by freshtechtips** [comment]
> QuillToolbarProvider

You no longer need to use `QuillToolbarProvider` to use the buttons

**Comment by freshtechtips** [comment]
> I use `QuillBaseToobar` where I can customize the sequence of toolbar buttons but I get a crash because some buttons (like `QuillToolbarFontFamilyButton`) required `QuillToolbarProvider`. I think it is not required because `QuillBaseToobar` has its own `configurations`.
> 
> Actually it is not a bug because I can provide the `QuillToolbarProvider` but it confuses because now I have 2 similar configurations. One is from `QuillToolbarProvider` and another from `QuillBaseToobar`.

This issue has been fixed, if you still face it please let us know

Feel free to ask us any questions at anytime.
