### ISSUE TITLE
Allow click on URL only when `Control` key is pressed

### ISSUE THREAD

**Issue by bambinoua** [singerdmx/flutter-quill#1542]
Now if the text which is marked as a link is clicked the browser opens at once. But if I just need to change the target URL I have a redundant action. It would be good if single click on link just opens Link dialog and single click with presses `Control` opens browser. I think it is a wide known feature.

**Comment by freshtechtips** [comment]
> Now if the text which is marked as a link is clicked the browser opens at once. But if I just need to change the target URL I have a redundant action. It would be good if single click on link just opens Link dialog and single click with presses `Control` opens browser. I think it is a wide known feature.
> 

Hi, thanks for the report

Are you using macOS or Windows??
Or the enhancement could be applied to all desktop platforms.

**Comment by bambinoua** [comment]
I use both platforms and I think it should be applied for both ones. The difference is in using `Control` or `Command` keys I think.
