### ISSUE TITLE
Superscript/subscript attribute is not applied

### ISSUE THREAD

**Issue by bambinoua** [singerdmx/flutter-quill#1543]
### Steps to reproduce

1. Select a number
2. Press on `Superscript` toggle
3. No visual result

<details>
<summary>Video demonstration</summary>

https://github.com/singerdmx/flutter-quill/assets/45417992/0f854453-aaac-41af-8447-d11fecb87647

</details>

### Flutter Quill version

8.6.0 and below (at lease on 8.5.5, 8.5.6)

**Comment by freshtechtips** [comment]
> ### Steps to reproduce
> 
> 1. Select a number
> 2. Press on `Superscript` toggle
> 3. No visual result
> 
> <details>
> <summary>Video demonstration</summary>
> 
> https://github.com/singerdmx/flutter-quill/assets/45417992/0f854453-aaac-41af-8447-d11fecb87647
> 
> </details>
> 
> ### Flutter Quill version
> 
> 8.6.0 and below (at lease on 8.5.5, 8.5.6)

Thank you for the report, I will take a look at it soon.

**Comment by freshtechtips** [comment]
My apologies, I'm unable to encounter the issue, I didn't try it on the web, maybe it's platform-specific?? or happens only with specific configurations.

**Comment by bambinoua** [comment]
@freshtechtips so I think you should ;)

**Comment by salahmak** [comment]
I'm having the same issue on both Android and Linux.

**Comment by AtlasAutocode** [comment]
Sub and superscript used to depend on selecting a font that implemented these features!
This has been corrected in the current version.
If this is still a problem, please reopen this issue
