### ISSUE TITLE
is there any api to parse title from the document?

### ISSUE THREAD

**Issue by kingrmb** [singerdmx/flutter-quill#1544]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

is there any api to parse title from the document?

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by kingrmb** [comment]
`
    var plainText = _controller.document.toPlainText();
    String title = plainText.trimLeft().split('\n')[0];
`
can this method built in flutter-quill, thans

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### The question
> 
> is there any api to parse title from the document?

Hi, thank you for the report

Actually, there are not, but you can build this very easily, and I see you already did

**Comment by freshtechtips** [comment]
> `
>     var plainText = _controller.document.toPlainText();
>     String title = plainText.trimLeft().split('\n')[0];
> `
> can this method built in flutter-quill, thans

Unfortunately, we can't. It's not up to me 

Because the purpose of this library is to confirm the original Quill JS

and we should keep it that way to not affect the current users as well the previous ones

Please let me know if you have any other questions.

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### The question
> 
> is there any api to parse title from the document?

If you have any other questions, feel free to ask us at any time.
