### ISSUE TITLE
upgrade to 8.6.0 from 8.5.1 , and flutter run failed, my vscode have no report code error.

### ISSUE THREAD

**Issue by 2426232528** [singerdmx/flutter-quill#1545]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

8.6.0

### Other Flutter Quill packages versions

flutter_quill: ^8.6.0

### Steps to reproduce

--

### Expected results

--

### Actual results

--

### Code sample

<details><summary>Code sample</summary>

```dart
QuillProvider(
        configurations: QuillConfigurations(
          controller: controller.quillController,
          sharedConfigurations: const QuillSharedConfigurations(
            locale: Locale('zh', 'CN'),
          ),
        ),
        child: Scaffold(
          body: SizedBox(
            height: double.infinity,
            width: double.infinity,
            child: Stack(
              children: [
                Column(
                  children: [
                    const Divider(thickness: 1),
                    Expanded(
                      child: QuillEditor(
                        configurations: QuillEditorConfigurations(
                          readOnly: false,
                          scrollPhysics: const BouncingScrollPhysics(),
                          padding: EdgeInsets.symmetric(
                              horizontal: 3.6.w, vertical: 1.8.h), // true for view only mode
                          autoFocus: controller.action == RouteActionType.create ? true : false,
                          scrollable: true,
                          expands: false,
                          customStyles: FlutterQuillDefaultStyles.style(context),
                          textSelectionThemeData: TextSelectionThemeData(
                            cursorColor: Theme.of(context).focusColor,
                          ),
                        ),
                        focusNode: controller.focusNode,
                        scrollController: controller.scrollController,
                      ),
                    ),
                  ],
                ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
PS D:\flutter3\examples> flutter run
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!  
Launching lib\main.dart on V1911A in debug mode...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/raw_editor/raw_editor_state.dart:136:7: Error: No named parameter with the name 'onLookUp'.        
      onLookUp: null,
      ^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, 
but the arguments don't match.
  static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/text_line.dart:175:30: Error: Member not found: 'MediaQuery.textScalerOf'.
      textScaler: MediaQuery.textScalerOf(context),
                             ^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/text_line.dart:175:7: Error: No named parameter with the name 'textScaler'.
      textScaler: MediaQuery.textScalerOf(context),
      ^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/basic.dart:5718:3: Context: Found this candidate, but the arguments don't match.
  RichText({
  ^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:149:9: Error: Type 'TextScaler' not found.
  final TextScaler textScaler;
        ^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:183:5: Error: Type 'TextScaler' not found.
    TextScaler textScaler,
    ^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:225:18: Error: Type 'TextScaler' not found.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:192:11: Error: No named parameter with the name 'textScaler'.
          textScaler: textScaler,
          ^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:489:3: Context: Found this candidate, but the arguments don't match.
  TextPainter({
  ^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:140:29: Error: Couldn't find constructor 'TextScaler.linear'.
    this.textScaler = const TextScaler.linear(1),
                            ^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:149:9: Error: 'TextScaler' isn't a type.
  final TextScaler textScaler;
        ^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:183:5: Error: 'TextScaler' isn't a type.
    TextScaler textScaler,
    ^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:225:18: Error: 'TextScaler' isn't a type.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:226:27: Error: The getter 'textScaler' isn't defined for the class 'TextPainter'.       
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
    if (_prototypePainter.textScaler == value) {
                          ^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:229:23: Error: The setter 'textScaler' isn't defined for the class 'TextPainter'.       
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.
    _prototypePainter.textScaler = value;
                      ^^^^^^^^^^
Target kernel_snapshot failed: Exception
```

</details>

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Flutter Quill version
> 
> 8.6.0
> 
> ### Other Flutter Quill packages versions
> 
> flutter_quill: ^8.6.0
> 
> ### Steps to reproduce
> 
> --
> 
> ### Expected results
> 
> --
> 
> ### Actual results
> 
> --
> 
> ### Code sample
> 
> <details><summary>Code sample</summary>
> 
> ```dart
> QuillProvider(
>         configurations: QuillConfigurations(
>           controller: controller.quillController,
>           sharedConfigurations: const QuillSharedConfigurations(
>             locale: Locale('zh', 'CN'),
>           ),
>         ),
>         child: Scaffold(
>           body: SizedBox(
>             height: double.infinity,
>             width: double.infinity,
>             child: Stack(
>               children: [
>                 Column(
>                   children: [
>                     const Divider(thickness: 1),
>                     Expanded(
>                       child: QuillEditor(
>                         configurations: QuillEditorConfigurations(
>                           readOnly: false,
>                           scrollPhysics: const BouncingScrollPhysics(),
>                           padding: EdgeInsets.symmetric(
>                               horizontal: 3.6.w, vertical: 1.8.h), // true for view only mode
>                           autoFocus: controller.action == RouteActionType.create ? true : false,
>                           scrollable: true,
>                           expands: false,
>                           customStyles: FlutterQuillDefaultStyles.style(context),
>                           textSelectionThemeData: TextSelectionThemeData(
>                             cursorColor: Theme.of(context).focusColor,
>                           ),
>                         ),
>                         focusNode: controller.focusNode,
>                         scrollController: controller.scrollController,
>                       ),
>                     ),
>                   ],
>                 ),
> ```
> 
> </details>
> 
> 
> ### Screenshots or Video
> 
> <details>
> <summary>Screenshots / Video demonstration</summary>
> 
> [Upload media here]
> 
> </details>
> 
> 
> ### Logs
> 
> <details><summary>Logs</summary>
> 
> ```console
> PS D:\flutter3\examples> flutter run
> Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!  
> Launching lib\main.dart on V1911A in debug mode...
> Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/raw_editor/raw_editor_state.dart:136:7: Error: No named parameter with the name 'onLookUp'.        
>       onLookUp: null,
>       ^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, 
> but the arguments don't match.
>   static List<ContextMenuButtonItem> getEditableButtonItems({
>                                      ^^^^^^^^^^^^^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/text_line.dart:175:30: Error: Member not found: 'MediaQuery.textScalerOf'.
>       textScaler: MediaQuery.textScalerOf(context),
>                              ^^^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/text_line.dart:175:7: Error: No named parameter with the name 'textScaler'.
>       textScaler: MediaQuery.textScalerOf(context),
>       ^^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/widgets/basic.dart:5718:3: Context: Found this candidate, but the arguments don't match.
>   RichText({
>   ^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:149:9: Error: Type 'TextScaler' not found.
>   final TextScaler textScaler;
>         ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:183:5: Error: Type 'TextScaler' not found.
>     TextScaler textScaler,
>     ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:225:18: Error: Type 'TextScaler' not found.
>   set textScaler(TextScaler value) {
>                  ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:192:11: Error: No named parameter with the name 'textScaler'.
>           textScaler: textScaler,
>           ^^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:489:3: Context: Found this candidate, but the arguments don't match.
>   TextPainter({
>   ^^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:140:29: Error: Couldn't find constructor 'TextScaler.linear'.
>     this.textScaler = const TextScaler.linear(1),
>                             ^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:149:9: Error: 'TextScaler' isn't a type.
>   final TextScaler textScaler;
>         ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:183:5: Error: 'TextScaler' isn't a type.
>     TextScaler textScaler,
>     ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:225:18: Error: 'TextScaler' isn't a type.
>   set textScaler(TextScaler value) {
>                  ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:226:27: Error: The getter 'textScaler' isn't defined for the class 'TextPainter'.       
>  - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
>     if (_prototypePainter.textScaler == value) {
>                           ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:229:23: Error: The setter 'textScaler' isn't defined for the class 'TextPainter'.       
>  - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart').
> Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.
>     _prototypePainter.textScaler = value;
>                       ^^^^^^^^^^
> Target kernel_snapshot failed: Exception
> ```
> 
> </details>
> 

Thank you for the report.
Please upgrade the flutter sdk version to 3.16

The 8.6.0 has breaking change in order to support 3.16

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Flutter Quill version
> 
> 8.6.0
> 
> ### Other Flutter Quill packages versions
> 
> flutter_quill: ^8.6.0
> 
> ### Steps to reproduce
> 
> --
> 
> ### Expected results
> 
> --
> 
> ### Actual results
> 
> --
> 
> ### Code sample
> 
> <details><summary>Code sample</summary>
> 
> ```dart
> QuillProvider(
>         configurations: QuillConfigurations(
>           controller: controller.quillController,
>           sharedConfigurations: const QuillSharedConfigurations(
>             locale: Locale('zh', 'CN'),
>           ),
>         ),
>         child: Scaffold(
>           body: SizedBox(
>             height: double.infinity,
>             width: double.infinity,
>             child: Stack(
>               children: [
>                 Column(
>                   children: [
>                     const Divider(thickness: 1),
>                     Expanded(
>                       child: QuillEditor(
>                         configurations: QuillEditorConfigurations(
>                           readOnly: false,
>                           scrollPhysics: const BouncingScrollPhysics(),
>                           padding: EdgeInsets.symmetric(
>                               horizontal: 3.6.w, vertical: 1.8.h), // true for view only mode
>                           autoFocus: controller.action == RouteActionType.create ? true : false,
>                           scrollable: true,
>                           expands: false,
>                           customStyles: FlutterQuillDefaultStyles.style(context),
>                           textSelectionThemeData: TextSelectionThemeData(
>                             cursorColor: Theme.of(context).focusColor,
>                           ),
>                         ),
>                         focusNode: controller.focusNode,
>                         scrollController: controller.scrollController,
>                       ),
>                     ),
>                   ],
>                 ),
> ```
> 
> </details>
> 
> 
> ### Screenshots or Video
> 
> <details>
> <summary>Screenshots / Video demonstration</summary>
> 
> [Upload media here]
> 
> </details>
> 
> 
> ### Logs
> 
> <details><summary>Logs</summary>
> 
> ```console
> PS D:\flutter3\examples> flutter run
> Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!  
> Launching lib\main.dart on V1911A in debug mode...
> Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/raw_editor/raw_editor_state.dart:136:7: Error: No named parameter with the name 'onLookUp'.        
>       onLookUp: null,
>       ^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, 
> but the arguments don't match.
>   static List<ContextMenuButtonItem> getEditableButtonItems({
>                                      ^^^^^^^^^^^^^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/text_line.dart:175:30: Error: Member not found: 'MediaQuery.textScalerOf'.
>       textScaler: MediaQuery.textScalerOf(context),
>                              ^^^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/text_line.dart:175:7: Error: No named parameter with the name 'textScaler'.
>       textScaler: MediaQuery.textScalerOf(context),
>       ^^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/widgets/basic.dart:5718:3: Context: Found this candidate, but the arguments don't match.
>   RichText({
>   ^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:149:9: Error: Type 'TextScaler' not found.
>   final TextScaler textScaler;
>         ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:183:5: Error: Type 'TextScaler' not found.
>     TextScaler textScaler,
>     ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:225:18: Error: Type 'TextScaler' not found.
>   set textScaler(TextScaler value) {
>                  ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:192:11: Error: No named parameter with the name 'textScaler'.
>           textScaler: textScaler,
>           ^^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:489:3: Context: Found this candidate, but the arguments don't match.
>   TextPainter({
>   ^^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:140:29: Error: Couldn't find constructor 'TextScaler.linear'.
>     this.textScaler = const TextScaler.linear(1),
>                             ^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:149:9: Error: 'TextScaler' isn't a type.
>   final TextScaler textScaler;
>         ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:183:5: Error: 'TextScaler' isn't a type.
>     TextScaler textScaler,
>     ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:225:18: Error: 'TextScaler' isn't a type.
>   set textScaler(TextScaler value) {
>                  ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:226:27: Error: The getter 'textScaler' isn't defined for the class 'TextPainter'.       
>  - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
>     if (_prototypePainter.textScaler == value) {
>                           ^^^^^^^^^^
> /C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-8.6.0/lib/src/widgets/proxy.dart:229:23: Error: The setter 'textScaler' isn't defined for the class 'TextPainter'.       
>  - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart').
> Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.
>     _prototypePainter.textScaler = value;
>                       ^^^^^^^^^^
> Target kernel_snapshot failed: Exception
> ```
> 
> </details>
> 

If you are still facing this issue or any others

Or if you have any questions, feel free to contact us at any time
