### ISSUE TITLE
Mobile  - Is there away to add maxLength and TextInputFormatter in QuillEditor similar to TextFormField

### ISSUE THREAD

**Issue by singhmukesh2023** [singerdmx/flutter-quill#1549]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

 I need to add character limit and formatter in QuillEditor. Let me know how to achieve it. 

     QuillEditor get quillEditor {
            return QuillEditor(
                focusNode: _focusNode,
                scrollController: ScrollController(),
                configurations: const QuillEditorConfigurations(
                    readOnly: false,
                    placeholder: 'Type here...',
                    scrollable: true,
                    autoFocus: false,
                    expands: true,
                    padding: EdgeInsets.all(8),
                    maxContentWidth: 500,
                    customStyles: DefaultStyles(
                      color: AppColor.textFieldLabelGrey,
                      h1: DefaultTextBlockStyle(
                          TextStyle(
                              fontSize: 32,
                              color: AppColor.textFieldLabelGrey,
                              fontWeight: FontWeight.w300,
                              fontFamily: 'Hind'),
                          VerticalSpacing(16, 0),
                          VerticalSpacing(0, 0),
                          null),
                      sizeSmall: TextStyle(fontSize: 9, fontFamily: 'Hind'),
                      subscript: TextStyle(
                        fontFamily: 'Hind',
                        fontFeatures: [FontFeature.subscripts()],
                      ),
                      superscript: TextStyle(
                        fontFamily: 'Hind',
                        fontFeatures: [FontFeature.superscripts()],
                      ),
                    )));
          }

**Comment by chenjiangmin126** [comment]
I am also looking for this feature

**Comment by freshtechtips** [comment]
Hi, thank you for the report. As far as I know, we can't use TextInputFormatter in the `QuillRawEditor` as there are widgets in the editor and it will apply only for the `EditableTextLine`

**Comment by mtiendat** [comment]
same
