### ISSUE TITLE
Error: No named parameter with the name 'onLiveTextInput 

### ISSUE THREAD

**Issue by Devlonoah** [singerdmx/flutter-quill#1552]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

8.1.1

### Steps to reproduce

```
Install [specify version package version number in pubspec.yaml file]
Run pub get to fetch package
Run flutter run
```

### Expected results

Expected the app to run after depending on the package

### Actual results

[   +6 ms] Failed to build iOS app
[        ] Error (Xcode): [ +711 ms]
../../.pub-cache/hosted/pub.dev/flutter_quill-8.1.1/lib/src/widgets/raw_editor/raw_editor.dart:363:7:
           Error: No named parameter with the name 'onLiveTextInput'.
           
[   +2 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 12 mini.

<img width="947" alt="Screenshot 2023-11-25 at 22 42 11" src="https://github.com/singerdmx/flutter-quill/assets/55284278/57763954-9e17-429a-85da-a4a135549757">

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<img width="947" alt="Screenshot 2023-11-25 at 22 42 11" src="https://github.com/singerdmx/flutter-quill/assets/55284278/4c7fe961-1baf-4f85-b3d4-3d250a3748f9">

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment]
Hi, thank you for the report. Please use the latest version `8.6.3` and let me know if you still facing the issue

**Comment by freshtechtips** [comment]
Hi again, this is no longer an issue in the latest version, if you still facing it or have any questions feel free to ask us at any time.
