### ISSUE TITLE
The dependencies of the `flutter_quill_extensions` library are incompatible with gradle 8.

### ISSUE THREAD

**Issue by kjxbyz** [singerdmx/flutter-quill#1553]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

The dependencies of the `flutter_quill_extensions` library are incompatible with gradle 8.

### Proposal

The dependencies of the `flutter_quill_extensions` library are incompatible with gradle 8.

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Use case
> The dependencies of the `flutter_quill_extensions` library are incompatible with gradle 8.
> 
> ### Proposal
> The dependencies of the `flutter_quill_extensions` library are incompatible with gradle 8.

Hi, thank you for the report, Do you mean the plugins?

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Use case
> The dependencies of the `flutter_quill_extensions` library are incompatible with gradle 8.
> 
> ### Proposal
> The dependencies of the `flutter_quill_extensions` library are incompatible with gradle 8.

We are able to use all Flutter plugins with the newest versions of Kotlin, AGP 8.1.4, and gradle 8.5
But it requires us to change some configurations in `build.gradle`

Follow this [gist](https://gist.github.com/freshtechtips/93fefb39e48c40592bda3931e05fd35c) for more info

Unfortunately, it's not up to us to fix this issue, we can only fix it from our side by removing it

If you have any other questions feel free to ask at any time.
