### ISSUE TITLE
How to get all delta inside a selection?

### ISSUE THREAD

**Issue by NhaPCS** [singerdmx/flutter-quill#1556]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I am trying to get the list of delta for a selection. Please tell me if anyone knows how to do that.

Thank you so much!

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by NhaPCS** [comment]
I knew the answer.
I used the function `slice(selection.start, selection.end)` of the Delta.

Thanks for your notice! I will close this question

**Comment by NhaPCS** [comment]
close it now
