### ISSUE TITLE
Changing shape of QuillToolBar and background color of buttons within QuillToolBar

### ISSUE THREAD

**Issue by DavidHajum** [singerdmx/flutter-quill#1558]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi,

I have implemented a custom QuillToolBar but haven't found any options to change the shape of the toolbar neither the background color of a button.

My Toolbar currently looks like this:

![grafik](https://github.com/singerdmx/flutter-quill/assets/51359586/f5f13130-1ce0-431a-a611-7f8ff28b07c7)

It is implemented as the bottomSheet of my Scaffold.

The chevron button on the right is a custom button, the image button on the left is an embedded button. The link button is the default one. I want match the link buttons background color to the color of the toolbar.

Also, I would like to remove the rounded corners. I have tried so by adjusting the decoration parameter of the toobar. I set the  borderRadius to BorderRadius.zero and the shape to BoxShape.rectangle but both options did not have the desired effect.

Any help would be greatly appreciated.

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### The question
> Hi,
> 
> I have implemented a custom QuillToolBar but haven't found any options to change the shape of the toolbar neither the background color of a button.
> 
> My Toolbar currently looks like this:
> 
> ![grafik](https://private-user-images.githubusercontent.com/51359586/286654857-f5f13130-1ce0-431a-a611-7f8ff28b07c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODYxNTcsIm5iZiI6MTcwMTM4NTg1NywicGF0aCI6Ii81MTM1OTU4Ni8yODY2NTQ4NTctZjVmMTMxMzAtMWNlMC00MzFhLWE2MTEtN2Y4ZmYyOGIwN2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIzMTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NmQ5NTg0N2FiY2JlODEyNjY3MzgzMmFiNzgwODhjODJmZjdhYzQzMDgwNDk1NzkyZDQxNzJhM2RiZWJiOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dOopm_zf1g27p2UjTlBVUG53EFSadfzFDBeFfpHxSHI)
> 
> It is implemented as the bottomSheet of my Scaffold.
> 
> The chevron button on the right is a custom button, the image button on the left is an embedded button. The link button is the default one. I want match the link buttons background color to the color of the toolbar.
> 
> Also, I would like to remove the rounded corners. I have tried so by adjusting the decoration parameter of the toobar. I set the borderRadius to BorderRadius.zero and the shape to BoxShape.rectangle but both options did not have the desired effect.
> 
> Any help would be greatly appreciated.

Hi, thank you for the report, please use the base button options to customize everything for all the buttons at once

**Comment by freshtechtips** [comment]
If you want to completely replace a button but still use the same state and functionality, please use the `childBuilder`

**Comment by freshtechtips** [comment]
The question has been answered and as far as I know, it's not an issue but we wasn't clear in the README.md and the docs

but we will work on that soon, feel free to ask any other questions.
