### ISSUE TITLE
文档过时

### ISSUE THREAD

**Issue by Jinxishihenian** [singerdmx/flutter-quill#1559]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

8.6.2

### Other Flutter Quill packages versions

Document obsolescence
```
QuillEditor.basic(

controller: quillEditorController,

readOnly: false,

)
```

The parameters of this constructor have changed.

### Steps to reproduce

![Snipaste_2023-12-02_10-37-59](https://github.com/singerdmx/flutter-quill/assets/44466363/98edeec5-3ae0-42e8-b72d-e4611d618f00)

### Expected results

Correct parameter documentation

### Actual results

According to the demo provided in the document, syntax exceptions occur

### Code sample

<details><summary>Code sample</summary>

```dart
showDialog(
    context: context,
    builder: (context) => AlertDialog(
      titlePadding: const EdgeInsets.only(left: 16, top: 8),
      title: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text('${isEditing ? 'Edit' : 'Add'} note'),
          IconButton(
            onPressed: () => Navigator.of(context).pop(),
            icon: const Icon(Icons.close),
          )
        ],
      ),
      content: QuillEditor.basic(
        controller: quillEditorController,
        readOnly: false,
      ),
    ),
  )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment]
Updated the outdated doc, thank you for the report
