### ISSUE TITLE
Where to put quillController argument after updating from 7.4.16 to 7.10.2?

### ISSUE THREAD

**Issue by Wizzel1** [singerdmx/flutter-quill#1561]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

In 7.4.16 I used a QuillController argument for the editor but it seems that does no longer exist. I didn't see a note in the changelog.

**Comment by freshtechtips** [comment]
Thank you for the report.

The `CHANGELOG.md` of the versions before 8.0.0 was messed up for some reason so I recommend you to take a look at [migration guide](https://github.com/singerdmx/flutter-quill/blob/master/doc/migration.md)

You need to use the QuillProvider

You can take a look at the example if you want to

**Comment by freshtechtips** [comment]
If you have any other questions feel free to ask.
