### ISSUE TITLE
The color for Bullets/Numbered lists counts/dots doesn't follow it's text.

### ISSUE THREAD

**Issue by adnan-nazir** [singerdmx/flutter-quill#1562]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

flutter_quill: ^8.6.4

### Steps to reproduce

flutter_quill is not giving support to change the color of dots and numbers for both Bullets and Numbered Lists. There should be the ability to set the colors for this.
<img width="361" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/107183643/11122e93-1710-4d34-b5d5-dc7a10235d33">

### Expected results

There should be the ability to set the colors for Bullets/Numbered list counts/dots.

### Actual results

There should be the ability to set the colors for Bullets/Numbered list counts/dots.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<img width="361" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/107183643/1ad2c8d1-6bf8-4c0c-8360-6cd4f44f9136">
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment]
Hi, thank you for the report, until now I'm not a Quill js expert and I haven't taken a deep look at QuillRawEditor yet

but tell me if you want me to ask another maintainer to take a look at this

@adil192 You might be interested

**Comment by adnan-nazir** [comment]
Hey @freshtechtips, can you please confirm if it's assigned to someone?

**Comment by freshtechtips** [comment]
> Hey @freshtechtips, can you please confirm if it's assigned to someone?

Sorry, I really can't right now it's not up to me, well I can assign it to myself, but it will take a few months

Do you still want me to?

**Comment by freshtechtips** [comment]
Example of customizing the color:

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/de243c08-ce5b-4d04-a4db-77f93bd172a0)

We just added that option in the dev branch

If that's what you want please confirm so I close the issue but it will take a while before it will published and breaking changes may introduced

If not, please tell me how we can help you?

**Comment by freshtechtips** [comment]
> Thanks dear, yes. Just one thing is this dynamic? Like if i select a color red and start adding this list then both number/dot and list test will should be red.

No, it's static, you choose the color for all the items, and you have two options, one for the ordered and unordered list, and you change the font color as well background

is there anything else you want to?

**Comment by adnan-nazir** [comment]
It should be dynamic as I mentioned above for smooth experience

**Comment by freshtechtips** [comment]
> Thanks dear, yes. Just one thing is this dynamic? Like if i select a color red and start adding this list then both number/dot and list test will should be red.

Wait, you mean select the color red as a user to any item the user selects? that's not what we did and we can but we will have to change the quill delta and add more custom data so I don't think that's confirm to Quill Js

If you mean you want to change it and customize it then that's it

but if you want a different color for each item, then can I ask how will you pick a different color for each item?? you don't have much info

**Comment by adnan-nazir** [comment]
1¹32q3³

**Comment by freshtechtips** [comment]
> It should be dynamic as I mentioned above for smooth experience

I'm not sure what you mean by dynamic?

**Comment by freshtechtips** [comment]
> 1¹32q3³

Is this a typo or something? because I still can't understand what you mean

**Comment by adnan-nazir** [comment]
Check attached screenshot, This is how its currently working.
Text is in red but numbers color is black that should also be red if I selected red color from toolbar or by controller.

If you think it will effect the other users then you can add a bool parameter instead of the parameters you added to enable and disable this functionality.



![Screenshot_2023_1206_234251](https://github.com/singerdmx/flutter-quill/assets/107183643/0355906a-42bd-45e6-bd8f-f4ce1da720b0)

**Comment by freshtechtips** [comment]
> Sorry for the typo.
> 
> Don't use your new changes you just made, ignore it.
> Have you tried adding the lists after changing color to red?
> Like select color to red from toolbar and add numbered lists you will see all the text in red but the color of numbers will be black. Numbers color should also be red.
> Just give it a try please.

Hi, by adding the lists after changing the color to red. What do you mean by that? Can you explain in more detail?
We are in the middle of other processes, so we can't get you very easily 

That's why I want to ask you to explain in more deep and simple details

Because in the screenshots you attached, 

I get it. You just want to change the font and background color


If that's not what you meant, then can you edit the issue

**Comment by freshtechtips** [comment]
> Hey @freshtechtips, Any update over this

We will work on it later

**Comment by freshtechtips** [comment]
It turns out this bug is pretty easy to fix

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/10cbb67c-94f5-488a-a6d0-7371c1bca474)

**Comment by freshtechtips** [comment]
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/9bd18065-c716-46b4-8252-4a49c229aa93)

Is this what you expected?

**Comment by ellet0** [comment]
Hi again, I'm closing the issue as solved, if you have the time please confirm if it worked like you expected it to work.

**Comment by max-pfi** [comment]
@ellet0 
Hi, would it maybe be possible to also implement the static version for the color customization, like in the one screenshot you posted? In my case I don't use the colors in the quill editor but rather set the textstyle according to my current background so the dots/numbers always stay black.

**Comment by 1SagarSharma7** [comment]
Not able to spot the backgroundColor property in the QuillEditorOrderedListElementOptions or QuillEditorUnOrderedListElementOptions, 
in version 10.4.5

![image](https://github.com/user-attachments/assets/e92fb089-7725-49ea-a061-5de51961d139)
