### ISSUE TITLE
Handle multiple QuillEditors

### ISSUE THREAD

**Issue by naifalharbi202** [singerdmx/flutter-quill#1563]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I have two separated QuillEditors in my Flutter app. But whatever I type in the first one automatically appears in the second one. I know it's a matter of controllers but I really couldn't find a way to control them separately. I am using the latest version of the package.

**Comment by binhtran93** [comment]
You can wrap QuillProvider for each QuillEditor, that is what I did for my app. If you want all editors to use a same toolbar, then wrap that toolbar with another QuillProvider, and use ChangeNotifier + focusNode to switch the controller

By the way, quill has a lot of issues regarding performance and unnecessary editor rebuild. After spend many days with Quill, I decided to switch to this one https://github.com/fleather-editor/fleather/tree/master/packages/fleather/lib/src

**Comment by naifalharbi202** [comment]
> You can wrap QuillProvider for each QuillEditor, that is what I did for my app. If you want all editors to use a same toolbar, then wrap that toolbar with another QuillProvider, and use ChangeNotifier + focusNode to switch the controller
> 
> By the way, quill has a lot of issues (they are changing a lot of code, that is understandable) regarding performance and unnecessary editor rebuild, and I also don't like the idea of QuillProvider, its hard to use for many usecases. After spent many days with Quill, I decided to switch to this one https://github.com/fleather-editor/fleather/tree/master/packages/fleather/lib/src

Thank you very much @binhtran93. Yes, I agree the idea of QuillProvider on every QuillEditor isn't a good way to handle multiple QuillEditors. It should be like TextFormFields where every one has its own controller but same toolbar.

**Comment by freshtechtips** [comment]
> You can wrap QuillProvider for each QuillEditor, that is what I did for my app. If you want all editors to use a same toolbar, then wrap that toolbar with another QuillProvider, and use ChangeNotifier + focusNode to switch the controller
> 
> By the way, quill has a lot of issues (they are changing a lot of code, that is understandable) regarding performance and unnecessary editor rebuild, and I also don't like the idea of QuillProvider, its hard to use for many usecases. After spent many days with Quill, I decided to switch to this one https://github.com/fleather-editor/fleather/tree/master/packages/fleather/lib/src

Thank you for the report, we will consider this
regarding the performance and unnecessary editor rebuild it was an old issue from the older versions and we are working on it

**Comment by freshtechtips** [comment]
Thank you for the feedbacks, we are already working on a new major version

**Comment by freshtechtips** [comment]
The issue has been fixed in the `dev` branch but it will take a few months before release

We are working on improving the raw quill editor

**Comment by freshtechtips** [comment]
> > You can wrap QuillProvider for each QuillEditor, that is what I did for my app. If you want all editors to use a same toolbar, then wrap that toolbar with another QuillProvider, and use ChangeNotifier + focusNode to switch the controller
> > By the way, quill has a lot of issues (they are changing a lot of code, that is understandable) regarding performance and unnecessary editor rebuild, and I also don't like the idea of QuillProvider, its hard to use for many usecases. After spent many days with Quill, I decided to switch to this one https://github.com/fleather-editor/fleather/tree/master/packages/fleather/lib/src
> 
> Thank you very much @binhtran93. Yes, I agree the idea of QuillProvider on every QuillEditor isn't a good way to handle multiple QuillEditors. It should be like TextFormFields where every one has its own controller but same toolbar.

Thank you, guys, for the feedback, we already dropped the support and use for `QuillProvider`
Regarding the performance issues we are working on it, we did a lot of breaking changes but that's only in versions 7.0.0 to 8.0.0

Now we will only work in the dev branch for a while and provide hotfixes for the master

The code changes should not affect the developer much unless it was fixes or breaking changes

**Comment by naifalharbi202** [comment]
> dev

Thank you very much. I will give it a look later today and you will have my feedback soon.

**Comment by naifalharbi202** [comment]
> > I have two separated QuillEditors in my Flutter app. But whatever I type in the first one automatically appears in the second one. I know it's a matter of controllers but I really couldn't find a way to control them separately. I am using the latest version of the package.
> 
> Can you give the [latest](https://pub.dev/packages/flutter_quill/versions/9.0.0-dev-6) dev version a try? Tell me if it fixed the issue and handle it more efficiently

I was really busy lately, so I am sorry for being late.. But I just updated to the latest version .. I can see that you dropped the support for QuillProvider. However, the problem of handling multiple Quill Editors seperately is still there.. One single controller for QuillToolbar and one QuillEditor. If you want to have multiple QuillEditors on the same screen with one QuillToolbar that controls all of them seperately, you can't. 

As for your last reply here, I can see the dev verison now has been updated 60 days ago.

**Comment by AtlasAutocode** [comment]
At present, each QuillEditor must have its own QuillController and associated QuillToolbar.
You can use code to show the toolbar for the active editor and hide the toolbars for non-active editors.
