### ISSUE TITLE
Cursor size is not consistented with font size.

### ISSUE THREAD

**Issue by MacDeveloper1** [singerdmx/flutter-quill#1568]
You see the text with font size 36 but the cursor size is not changed but it should.

![image](https://github.com/singerdmx/flutter-quill/assets/130981115/5b217563-f45f-49a0-bff3-6eefae2022b9)

**Comment by Paul-creator** [comment]
Here is a little video which shows the issue in the repo using the example project.
[Video on Google Drive](https://drive.google.com/file/d/19-1W1O4V-Nv2iD4ZNdMuMcyBALmi0Ail/view?usp=drive_link)

**Comment by EchoEllet** [comment]
This bug hasn't been fixed. Moving the discussion to #2169.
