### ISSUE TITLE
i am getting this errot while trying to debug the app.

### ISSUE THREAD

**Issue by rajcrack** [singerdmx/flutter-quill#1570]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

This is the error which i get in the console after running the debug in the android emulator.
`        ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:183:5: Error: Type 'TextScaler' not found.
    TextScaler textScaler,
    ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:225:18: Error: Type 'TextScaler' not found.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:192:11: Error: No named parameter with the name 'textScaler'.
          textScaler: textScaler,
          ^^^^^^^^^^
../../flutter/packages/flutter/lib/src/painting/text_painter.dart:489:3: Context: Found this candidate, but the arguments don't match.
  TextPainter({
  ^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:140:29: Error: Couldn't find constructor 'TextScaler.linear'.
    this.textScaler = const TextScaler.linear(1),
                            ^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:149:9: Error: 'TextScaler' isn't a type.
  final TextScaler textScaler;
        ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:183:5: Error: 'TextScaler' isn't a type.
    TextScaler textScaler,
    ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:225:18: Error: 'TextScaler' isn't a type.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:226:27: Error: The getter 'textScaler' isn't defined for the class 'TextPainter'.
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('../../flutter/packages/flutter/lib/src/painting/text_painter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
    if (_prototypePainter.textScaler == value) {
                          ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-8.6.2/lib/src/widgets/proxy.dart:229:23: Error: The setter 'textScaler' isn't defined for the class 'TextPainter'.
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('../../flutter/packages/flutter/lib/src/painting/text_painter.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.
    _prototypePainter.textScaler = value;`

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by rajcrack** [comment]
does someone know what is the solution for this . or i have to downgrade the project??

**Comment by freshtechtips** [comment]
This issue should be fixed once you upgrade your flutter SDK, if you have any other questions feel free to ask at any time.
