### ISSUE TITLE
Not possible to select specified characters

### ISSUE THREAD

**Issue by FlashTang** [singerdmx/flutter-quill#1571]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi there
Not possible to select specified characters ?
there is only "SelectAll" button on iOS , is this a BUG ? 
ios : 15.6
flutter: 3.16.2
quill_flutter: 8.6.4
here is the screenshoot 
![897E7B6DD50CE8D33972095009964F7F](https://github.com/singerdmx/flutter-quill/assets/920751/dcc13d50-2bba-4b60-9488-beeb0846529b)

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment]
Hi, thank you for the report, can you try the dev version on pub.dev or in the GitHub dev branch to confirm if this issue exists?

**Comment by FlashTang** [comment]
> Hi, thank you for the report, can you try the dev version on pub.dev or in the GitHub dev branch to confirm if this issue exists?

Hi @freshtechtips
Just tested the dev version, it's the same, no "select" button
p.s.  there is a mistake in ios info.plist, the NSMicrophoneUsageDescription key is not closed properly
screenshoot :
from left to right : "Cut" "Copy" "Paste" "Select All"
![IMG_2540](https://github.com/singerdmx/flutter-quill/assets/920751/da996d41-87b8-4478-ad01-f324bc866cdc)
Thank you.

**Comment by freshtechtips** [comment]
> > Hi, thank you for the report, can you try the dev version on pub.dev or in the GitHub dev branch to confirm if this issue exists?
> 
> Hi @freshtechtips
> Just tested the dev version, it's the same, no "select" button
> p.s.  there is a mistake in ios info.plist, the NSMicrophoneUsageDescription key is not closed properly
> screenshoot :
> from left to right : "Cut" "Copy" "Paste" "Select All"
> ![IMG_2540](https://github.com/singerdmx/flutter-quill/assets/920751/da996d41-87b8-4478-ad01-f324bc866cdc)
> Thank you.
> 
> 

Thanks, I will check it, but tell me
What exactly do you want to select?? We didn't implement the select button and don't know what is that

Is it specific to iOS?

**Comment by FlashTang** [comment]
> > > Hi, thank you for the report, can you try the dev version on pub.dev or in the GitHub dev branch to confirm if this issue exists?
> > 
> > 
> > Hi @freshtechtips
> > Just tested the dev version, it's the same, no "select" button
> > p.s.  there is a mistake in ios info.plist, the NSMicrophoneUsageDescription key is not closed properly
> > screenshoot :
> > from left to right : "Cut" "Copy" "Paste" "Select All"
> > ![IMG_2540](https://private-user-images.githubusercontent.com/920751/288459328-da996d41-87b8-4478-ad01-f324bc866cdc.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzczMjYsIm5iZiI6MTcwMTg3NzAyNiwicGF0aCI6Ii85MjA3NTEvMjg4NDU5MzI4LWRhOTk2ZDQxLTg3YjgtNDQ3OC1hZDAxLWYzMjRiYzg2NmNkYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxNTM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTg1NDMxMjM2NTIyOTM1MWM0OWJjYzc4OWM4MzhjNzM3N2IxNzUyYjJiZjlhZGYyNGE0ODNiODk0ZTNiODRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XsErK66y-yPxiG2BN7jqeT7iNnm8dNcDj2rCpjjUvIc)
> > Thank you.
> 
> Thanks, I will check it, but tell me What exactly do you want to select?? We didn't implement the select button and don't know what is that
> 
> Is it specific to iOS?

I think it's not specific to iOS , it's also available on Android, it's a common feature
screenshoots here (quill_html_editor) 
![IMG_2542](https://github.com/singerdmx/flutter-quill/assets/920751/f27be58c-6cbf-4081-a76e-8a36da327bf2)
//+++++++++++++++++
![IMG_2543](https://github.com/singerdmx/flutter-quill/assets/920751/efed28f9-b4ab-43b4-b84a-0526a2f1937f)

**Comment by freshtechtips** [comment]
Do you know what does it selects?

**Comment by FlashTang** [comment]
> Do you know what does it selects?

If you tap select , it selects the "last word"
e.g. "This is a text"  the last "text" will be selected 
and the "range chooser handle" will be shown. like the image I posted above

**Comment by freshtechtips** [comment]
Flutter only supports the following by default:

```dart
    required final ClipboardStatus? clipboardStatus,
    required final VoidCallback? onCopy,
    required final VoidCallback? onCut,
    required final VoidCallback? onPaste,
    required final VoidCallback? onSelectAll,
    required final VoidCallback? onLookUp,
    required final VoidCallback? onSearchWeb,
    required final VoidCallback? onShare,
    required final VoidCallback? onLiveTextInput,
```

Yes we can add more but that's the default editable text button items(ContextMenuButtonItem)

**Comment by FlashTang** [comment]
> Flutter only supports the following by default:
> 
> ```dart
>     required final ClipboardStatus? clipboardStatus,
>     required final VoidCallback? onCopy,
>     required final VoidCallback? onCut,
>     required final VoidCallback? onPaste,
>     required final VoidCallback? onSelectAll,
>     required final VoidCallback? onLookUp,
>     required final VoidCallback? onSearchWeb,
>     required final VoidCallback? onShare,
>     required final VoidCallback? onLiveTextInput,
> ```
> 
> Yes we can add more but that's the default editable text button items(ContextMenuButtonItem)

Indeed, flutter has no "select" button, but it has "range selector" (two draggable dots) where flutter quill doesn't have
screenshoot:
![IMG_2544(20231207-113255)](https://github.com/singerdmx/flutter-quill/assets/920751/923994e7-d2db-4461-a965-1769d3c70efd)

**Comment by freshtechtips** [comment]
> > Flutter only supports the following by default:
> > 
> > ```dart
> >     required final ClipboardStatus? clipboardStatus,
> >     required final VoidCallback? onCopy,
> >     required final VoidCallback? onCut,
> >     required final VoidCallback? onPaste,
> >     required final VoidCallback? onSelectAll,
> >     required final VoidCallback? onLookUp,
> >     required final VoidCallback? onSearchWeb,
> >     required final VoidCallback? onShare,
> >     required final VoidCallback? onLiveTextInput,
> > ```
> > 
> > Yes we can add more but that's the default editable text button items(ContextMenuButtonItem)
> 
> Indeed, flutter has no "select" button, but it has "range selector" (two draggable dots) where flutter quill doesn't have
> screenshoot:
> ![IMG_2544(20231207-113255)](https://github.com/singerdmx/flutter-quill/assets/920751/923994e7-d2db-4461-a965-1769d3c70efd)
> 
> 

Can you send me an app that I can try on my own?? Is there any app on store or GitHub repo

Because I still can't see the button select

**Comment by FlashTang** [comment]
> > there is a mistake in ios info.plist, the NSMicrophoneUsageDescription key is not closed properly
> 
> Hi, I just checked it and it seems it closed properly.



> > > Flutter only supports the following by default:
> > > ```dart
> > >     required final ClipboardStatus? clipboardStatus,
> > >     required final VoidCallback? onCopy,
> > >     required final VoidCallback? onCut,
> > >     required final VoidCallback? onPaste,
> > >     required final VoidCallback? onSelectAll,
> > >     required final VoidCallback? onLookUp,
> > >     required final VoidCallback? onSearchWeb,
> > >     required final VoidCallback? onShare,
> > >     required final VoidCallback? onLiveTextInput,
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Yes we can add more but that's the default editable text button items(ContextMenuButtonItem)
> > 
> > 
> > Indeed, flutter has no "select" button, but it has "range selector" (two draggable dots) where flutter quill doesn't have
> > screenshoot:
> > ![IMG_2544(20231207-113255)](https://private-user-images.githubusercontent.com/920751/288621350-923994e7-d2db-4461-a965-1769d3c70efd.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTg4MjMsIm5iZiI6MTcwMTk1ODUyMywicGF0aCI6Ii85MjA3NTEvMjg4NjIxMzUwLTkyMzk5NGU3LWQyZGItNDQ2MS1hOTY1LTE3NjlkM2M3MGVmZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QxNDE1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmU3NmMyNGI2ODcyZjhjZGYwYWUxNjA1NzI3NDg2MDRlMzY4ZjZkMzJlNjM5MDM5Mjg0ZmEwZjlkMTMxNzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uGBHjTovQjXDyh9Bm6r0386ATkZJQ6T68Xju15tf3bo)
> 
> Can you send me an app that I can try on my own?? Is there any app on store or GitHub repo
> 
> Because I still can't see the button select

Yes , flutter has no select button (even Android native) , but you can adjust the range  after text is selected 
<img width="226" alt="Screen Shot 2023-12-07 at 22 18 16" src="https://github.com/singerdmx/flutter-quill/assets/920751/9dbac418-d555-432b-83f4-f3229a89a582">

But seems flutter quill can't

**Comment by CatHood0** [comment]
I will close this since we have no responses if the issue still persisting. Please, reopen if your issue persists.
