### ISSUE TITLE
Only value received is '"[{insert: \n}]"'

### ISSUE THREAD

**Issue by matboy82** [singerdmx/flutter-quill#1579]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I'm a noob at flutter so maybe I'm just all screwed up, but when I call `_controller.document.toDelta()` to get what I typed in, I only ever get the insert key, I've tried toPlainText() and even converting via toHtml (that returned <p><br/</p>).

My widget:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:quill_html_converter/quill_html_converter.dart';

class RichTextEditor extends StatelessWidget {
  RichTextEditor({super.key});

  final QuillController _controller = QuillController.basic();
 
  @override
  Widget build(BuildContext context) {
    return QuillProvider(
      configurations: QuillConfigurations(
        controller: _controller,
        sharedConfigurations: const QuillSharedConfigurations(
          locale: Locale('en', 'US'),
        ),
      ),
      child: ListView(
      shrinkWrap: true,
      children: [
        const QuillToolbar(),
        
        QuillEditor.basic(
            configurations: const QuillEditorConfigurations(
              readOnly: false,
              minHeight: 200,
              maxHeight: 500,
              showCursor: true,
              )
            ),
      ],
    ),
    );
  }

String getJsonDocument() {
  var delta = _controller.document.toDelta().toHtml();
  return delta;
}

  void dispose() {
    _controller.dispose();
  }
}

```

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by freshtechtips** [comment]
Hi, thank you for the report, can you explain what you mean by only insert key?? can you send us the result and input? some images will help us understand the question

**Comment by matboy82** [comment]
> Hi, thank you for the report, can you explain what you mean by only insert key?? can you send us the result and input? some images will help us understand the question

It looks like a json key, debug output from the call is `[{insert: `
![debug](https://github.com/singerdmx/flutter-quill/assets/83370205/405f4951-3987-49a6-accd-ddbf70a26477)
![debug2](https://github.com/singerdmx/flutter-quill/assets/83370205/11dbbde6-7ac8-4229-bddd-ecdab76d0bbc)
![debug3](https://github.com/singerdmx/flutter-quill/assets/83370205/95289371-b595-44a3-9f17-18b79f55b894)

**Comment by freshtechtips** [comment]
> > Hi, thank you for the report, can you explain what you mean by only insert key?? can you send us the result and input? some images will help us understand the question
> 
> It looks like a json key, debug output from the call is `[{insert: `
> ![debug](https://github.com/singerdmx/flutter-quill/assets/83370205/405f4951-3987-49a6-accd-ddbf70a26477)
> ![debug2](https://github.com/singerdmx/flutter-quill/assets/83370205/11dbbde6-7ac8-4229-bddd-ecdab76d0bbc)
> ![debug3](https://github.com/singerdmx/flutter-quill/assets/83370205/95289371-b595-44a3-9f17-18b79f55b894)
> 
> 
> 
> 
> 

You should use jsonEncode instead of toString

**Comment by matboy82** [comment]
Thank you for responding fast! I made the change, but still getting just the insert. 

![debug](https://github.com/singerdmx/flutter-quill/assets/83370205/4da24065-77bf-4024-afc2-f292fa07cae7)

**Comment by freshtechtips** [comment]
> Thank you for responding fast! I made the change, but still getting just the insert. 
> 
> ![debug](https://github.com/singerdmx/flutter-quill/assets/83370205/4da24065-77bf-4024-afc2-f292fa07cae7)
> 
> 
> 

Can you send me the GitHub repo so we can investigate it further?

**Comment by matboy82** [comment]
Invite sent, thank you!

**Comment by CatHood0** [comment]
I will close because was no updated since 2023. Reopen this issue if still persisting
