### ISSUE TITLE
Checkbox not work on tapping

### ISSUE THREAD

**Issue by theacheng** [singerdmx/flutter-quill#158]
I need to click at near text to make checkbox work.

![test1](https://user-images.githubusercontent.com/29684683/115368504-57f81b00-a1f1-11eb-8598-f732be1bd663.gif)

This checkbox update on this method: `bool _onTapping(TapUpDetails details) {...}`
But when I click on checkbox, it call `void onTapDown(TapDownDetails details)` instead. 

Desire result is to update checkbox on tap up.

**Comment by singerdmx** [comment]
@theacheng the problem is how to figure out when the checkbox is clicked - we compromised to use beginning of the line since we were unable to find a way to know when checkbox is hit

**Comment by kevinDespoulains** [comment]
Hi, 

I made this PR : https://github.com/singerdmx/flutter-quill/pull/186, could you please check if it fits your needs ?

**Comment by theacheng** [comment]
That works well for me. Thank you!

![test1](https://user-images.githubusercontent.com/29684683/116063732-82dde580-a6af-11eb-836c-7ef165543bc6.gif)

-----

But it would be better if we are able to hold it and update on tapping up. (I'm not sure if this is good behavior). 
This is when we holding it:

![test1](https://user-images.githubusercontent.com/29684683/116064344-20d1b000-a6b0-11eb-8c5c-5566bc2647e4.gif)

**Comment by kevinDespoulains** [comment]
I added the behavior you asked by wrapping the checkboxes in a GestureDetector.

I also added the usage of a key on the checkboxes widgets because clicking on the first checkbox with some other checkboxes selected under it had a bad side effect (An unwanted animation on the checkboxes was triggered).

Let me know if it is working as you want ;)

**Comment by theacheng** [comment]
It looks good without that animation for the first checkbox (that's fair for other checkboxes :D)
Thank you again!

![test1](https://user-images.githubusercontent.com/29684683/116070395-c4be5a00-a6b6-11eb-9888-fd361fa194dc.gif)

**Comment by singerdmx** [comment]
@kevinDespoulains thanks so much
