### ISSUE TITLE
Wasted space between toolbar icons

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1587]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.x

### Other Flutter Quill packages versions

9.x

### Steps to reproduce

Another mistake: 
- You have added a widget forcing a space between icons, for no apparent reason and even more wasted memory holding empty widget reference

### Expected results

Less memory usage for a blank area

### Actual results

Wasting memory and developer time

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Flutter Quill version
> 9.x
> 
> ### Other Flutter Quill packages versions
> 9.x
> 
> ### Steps to reproduce
> Another mistake:
> 
> * You have added a widget forcing a space between icons, for no apparent reason and even more wasted memory holding empty widget reference
> 
> ### Expected results
> Less memory usage for a blank area
> 
> ### Actual results
> Wasting memory and developer time
> 
> ### Code sample
> Code sample
> ### Screenshots or Video
> Screenshots / Video demonstration
> ### Logs
> Logs

That's a PR in 8.0.0 and I was about to remove it

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Flutter Quill version
> 9.x
> 
> ### Other Flutter Quill packages versions
> 9.x
> 
> ### Steps to reproduce
> Another mistake:
> 
> * You have added a widget forcing a space between icons, for no apparent reason and even more wasted memory holding empty widget reference
> 
> ### Expected results
> Less memory usage for a blank area
> 
> ### Actual results
> Wasting memory and developer time
> 
> ### Code sample
> Code sample
> ### Screenshots or Video
> Screenshots / Video demonstration
> ### Logs
> Logs

Removed in the dev branch, if you have any questions please feel free to ask us at any time.
