### ISSUE TITLE
Toolbar icon colors when selected, unselected, etc are not respected

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1589]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.x

### Other Flutter Quill packages versions

9.x

### Steps to reproduce

The colors for the selected, unselected toolbar icons are not respected when placed into the button options, the amount of padding is also much to much.

Major regression

### Expected results

Non regressive code

### Actual results

Regressive code

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Flutter Quill version
> 9.x
> 
> ### Other Flutter Quill packages versions
> 9.x
> 
> ### Steps to reproduce
> The colors for the selected, unselected toolbar icons are not respected when placed into the button options, the amount of padding is also much to much.
> 
> Major regression
> 
> ### Expected results
> Non regressive code
> 
> ### Actual results
> Regressive code
> 
> ### Code sample
> Code sample
> ### Screenshots or Video
> Screenshots / Video demonstration
> ### Logs
> Logs

Correct and that's because the version is not ready yet as we said but we were forced to publish

**Comment by freshtechtips** [comment]
> the amount of padding is also much to much.

You are not sharing any info, please share screenshots or steps to encounter the issues

**Comment by freshtechtips** [comment]
> The colors for the selected, unselected toolbar icons are not respected when placed into the button options, the amount of padding is also much to much.

True but remember it will follow the one in the theme data of the app widget so it will be more constant, but sure we will add an option to change it as well
