### ISSUE TITLE
More regressions: Base toolbar options not respected

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1590]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.x

### Other Flutter Quill packages versions

9.x

### Steps to reproduce

`base` toolbar options are ignored and not respected by the simple toolbar.

Yet another regression.  Im sure it will be removed.  And then added back in after 10 more breaking changes, along with new memory leaks 

### Expected results

Options that actually work

### Actual results

Options that do not work and result is breaking changes and regressions

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by freshtechtips** [comment]
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/d4234401-5894-4d4c-bb6e-488222924578)
It's been used as far as I tested. can you share more info?

**Comment by freshtechtips** [comment]
Do you mean the quill icon theme?

**Comment by Sesa1988** [comment]
Hey, great editor!

I noticed this bug too. Almost all properties are not respected for the "simple"-constructor except the "show" ones like "multiRowsDisplay". I tried to set icon size and other style properties but this has no effect at all.

I noticed also another bug when the toolbar is one row the icon is not in the center of the bubble and it looks weird.

**Comment by ellet0** [comment]
> Hey, great editor!
> 
> I noticed this bug too. Almost all properties are not respected for the "simple"-constructor except the "show" ones like "multiRowsDisplay". I tried to set icon size and other style properties but that had no effect at all.
> 
> I noticed also another bug when the toolbar is one row the icon is not in the center of the bubble and it looks weird.

Can you tell me which properties are not respected?

**Comment by ellet0** [comment]
Hi again, can you share more info about which properties for example?

**Comment by ellet0** [comment]
> Hey, great editor!
> 
> I noticed this bug too. Almost all properties are not respected for the "simple"-constructor except the "show" ones like "multiRowsDisplay". I tried to set icon size and other style properties but that had no effect at all.
> 
> I noticed also another bug when the toolbar is one row the icon is not in the center of the bubble and it looks weird.

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/b263640b-019a-40db-9f87-479966c66569)

Just tried out the `multiRowsDisplay` and it's not being ignored as far as I see, can you share more info?? a code sample

**Comment by ellet0** [comment]
> size and other style properties

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/edc43c6f-3e32-41c0-aa24-dda7b40de61c)
I tested the icon size and it's being applied, can you share more details?

**Comment by ellet0** [comment]
It's now fixed by add material 3 icon button style in the dev version, if you still think this is a bug please let me know
