### ISSUE TITLE
Significant amount of splash animation jank

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1591]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.x

### Other Flutter Quill packages versions

9.x

### Steps to reproduce

Well for some unknown reason this package has turned from lightweight to heavyweight.
As already mentioned, there are significant memory leaks going on, but also performance loss, irrespective of the nonsense QuillProvider.  SO much so that there is no visible jank in the splash animations.  

Makes an app look childish, whereas the rest of flutter has become for the most part jank free

### Expected results

No jank from an editor that does not use platform views or custom animations

### Actual results

Jank from a basic splash effect on an Icon?  How....

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Flutter Quill version
> 9.x
> 
> ### Other Flutter Quill packages versions
> 9.x
> 
> ### Steps to reproduce
> Well for some unknown reason this package has turned from lightweight to heavyweight. As already mentioned, there are significant memory leaks going on, but also performance loss, irrespective of the nonsense QuillProvider. SO much so that there is no visible jank in the splash animations.
> 
> Makes an app look childish, whereas the rest of flutter has become for the most part jank free
> 
> ### Expected results
> No jank from an editor that does not use platform views or custom animations
> 
> ### Actual results
> Jank from a basic splash effect on an Icon? How....
> 
> ### Code sample
> Code sample
> ### Screenshots or Video
> Screenshots / Video demonstration
> ### Logs
> Logs

We are not using any animations in 9.0.0, are you sure it is because of 9.0.0?

**Comment by freshtechtips** [comment]
> irrespective of the nonsense QuillProvider

The quill provider has been removed

**Comment by freshtechtips** [comment]
> No jank from an editor that does not use platform views or custom animations

We are not using platform views, only for YouTube video player and that was from the beginning as there are no alternatives, and in web

**Comment by freshtechtips** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Flutter Quill version
> 9.x
> 
> ### Other Flutter Quill packages versions
> 9.x
> 
> ### Steps to reproduce
> Well for some unknown reason this package has turned from lightweight to heavyweight. As already mentioned, there are significant memory leaks going on, but also performance loss, irrespective of the nonsense QuillProvider. SO much so that there is no visible jank in the splash animations.
> 
> Makes an app look childish, whereas the rest of flutter has become for the most part jank free
> 
> ### Expected results
> No jank from an editor that does not use platform views or custom animations
> 
> ### Actual results
> Jank from a basic splash effect on an Icon? How....
> 
> ### Code sample
> Code sample
> ### Screenshots or Video
> Screenshots / Video demonstration
> ### Logs
> Logs

Consider sharing videos or screenshots about the issue

**Comment by CatHood0** [comment]
I will close this issue since we have no responses from the OP. Please, if the issue persists on the last version of Flutter Quill, reopen this.
