### ISSUE TITLE
[Mobile] Indented position not holding while editing

### ISSUE THREAD

**Issue by BMonsalvatge** [singerdmx/flutter-quill#160]
My issue is about [Mobile]

When indenting and going to a new line, the indented position isn't held.  This is happening locally and when testing on bulletjournal:

![image](https://user-images.githubusercontent.com/1095871/115649146-c4a80e00-a2f4-11eb-86f7-15ec7b84d3f1.png)

What I expected was that the current indented position would be held when going to a new line, and that the new line would be at the same indentation level.

Example:

![image](https://user-images.githubusercontent.com/1095871/115649282-089b1300-a2f5-11eb-893e-623b5a92d602.png)

Let me know if there's any other details needed.

**Comment by singerdmx** [comment]
Are you talking about second level nesting?

**Comment by BMonsalvatge** [comment]
Yea I believe that's the case.  I am not familiar with the term.

To clarify, I am referencing while editing and hitting enter (newline) the previous line will lose its indentation.

**Comment by matuella** [comment]
Happening with me as well, when a new unordered/ordered list is nested inside any block that is already indented and, after skipping to the "next element", the previous one loses its indentation, just like @BMonsalvatge explained.

Tried with version `1.2.0` on `macOS`, `web` and `iOS`, flutter `2.0.3`.

**Comment by singerdmx** [comment]
@li3317 @friebetill @florianh01 the issue lies in method **getBlockExceptHeader** 
This method returns a single attribute, which could be `"list": "ordered" `or `"indent": "1"`
We need to return all block attributes and handle accordingly

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/115793936-e9969280-a381-11eb-9fa8-2ad581b08a4c.png)

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/115795192-4c892900-a384-11eb-8976-a807b957d450.png)

**Comment by singerdmx** [comment]
https://github.com/singerdmx/flutter-quill/commit/900d0f2489ed2c731b52ae8594af80da617df1a4
