### ISSUE TITLE
branch compatible with flutter master/dev?

### ISSUE THREAD

**Issue by m-j-g** [singerdmx/flutter-quill#161]
Flutter team recently provided a solution to iOS startup jank on the master branch, and so I am trying to get a build together.  I ran into a problem with flutter_quill on the master branch and was curious if there is a branch I could point to that would compile with master flutter?  Thanks for the help

../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.0/lib/widgets/raw_editor.dart:97:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.userUpdateTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.0/lib/widgets/raw_editor.dart:1029:8: Error: The method 'RawEditorState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
  void hideToolbar() {
       ^
../flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);
       ^
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.0/lib/widgets/raw_editor.dart:713:51: Error: A value of type 'bool' can't be returned from a function with return type 'KeyEventResult'.
 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('../flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
        onKey: (node, event) => _keyboardListener.handleRawKeyEvent(event));
                                                  ^
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.0/lib/widgets/raw_editor.dart:759:53: Error: A value of type 'bool' can't be returned from a function with return type 'KeyEventResult'.
 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('../flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
          onKey: (node, event) => _keyboardListener.handleRawKeyEvent(event));

**Comment by singerdmx** [comment]
I have added you add collaborator so you can fork off a branch and maintain it

**Comment by singerdmx** [comment]
Please use branch `dev`
See https://github.com/singerdmx/flutter-quill/commits/dev

**Comment by m-j-g** [comment]
User dev branch of flutter-quill will still throw this error on flutter master:
 ../flutter/.pub-cache/git/flutter-quill-5892e4c828dd1b26a3fcba034d62af70dfa2e3ea/lib/widgets/raw_editor.dart:715:51: Error: A value of type 'bool' can't be returned from a function with return type 'KeyEventResult'.
 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('../flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
        onKey: (node, event) => _keyboardListener.handleRawKeyEvent(event));

**Comment by jonmountjoy** [comment]
Interestingly, using this branch `dev` and using Flutter 2.2.0-10.3pre, I can get everything working in the simulator.  When doing `flutter build ios` however, the build process always fails with an obscure `../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 3186: error: unreachable code`.  

It took a day or two to figure out that this was the culprit in my app.

I haven't been able to figure out any more than that, but would be interesting to see if others reproduce.

**Comment by m-j-g** [comment]
now that these changes have been promoted to flutter stable, this issue isn't just in master/dev, but all branches of flutter

**Comment by friebetill** [comment]
Close this issue in favor of https://github.com/singerdmx/flutter-quill/issues/225.
