### ISSUE TITLE
Superscript and Subscript is not working on non numeric words.

### ISSUE THREAD

**Issue by IsmailHosenIsmailJames** [singerdmx/flutter-quill#1610]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.0.3

### Steps to reproduce

I have created a flutter project just for test the package. The version of flutter_quill is 9.0.3 . I run it on Ubuntu 23.10.1 and it works pretty well on numeric number. But not working on non numeric words. For example as superscript and subscript is not working for x, y , z etc. 

### Expected results

Superscript and subscript should work on anything.

### Actual results

Superscript and subscript is not working. It is showing plane text. I mean there is no effect of superscript and subscript on non numeric words.

### Code sample

<details><summary>Code sample</summary>

```dart

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  QuillController x = QuillController.basic();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: QuillEditor.basic(
                configurations: QuillEditorConfigurations(controller: x),
              ),
            ),
            QuillToolbar.simple(
              configurations: QuillSimpleToolbarConfigurations(controller: x),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
web
[Screencast from 2023-12-18 10-51-17.webm](https://github.com/singerdmx/flutter-quill/assets/99122172/b76db6bf-04f2-4401-914f-0a8be331aef8)
android
[Screencast from 2023-12-18 10-56-08.webm](https://github.com/singerdmx/flutter-quill/assets/99122172/2e643848-36d6-4cdb-8717-5a01d6efddf6)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!
