### ISSUE TITLE
Ability to add custom icons for lists

### ISSUE THREAD

**Issue by EgorK0rshun** [singerdmx/flutter-quill#1611]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

It helps to expand the use of lists. You often need to move away from the usual patterns and use something of your own, design lists with the icon you like. 
Besides, this is now a very frequent request from users in different applications.

### Proposal

<img width="414" alt="example" src="https://github.com/singerdmx/flutter-quill/assets/120365747/1aa58548-9e45-4e64-91fd-bcc27a89b387">

**Comment by ellet0** [comment]
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/5cd4a06e-22c9-4da0-a3c2-e298b6bf3789)

Is that what you meant?

**Comment by EgorK0rshun** [comment]
@ellet0 , Yes, [icons](https://api.flutter.dev/flutter/material/Icons-class.html) are already very cool and can be  enough. But if there's going to be an option to add svg, it's going to be a completely closed enquiry

**Comment by ellet0** [comment]
> @ellet0 , Yes, [icons](https://api.flutter.dev/flutter/material/Icons-class.html) are already very cool and can be enough. But if there's going to be an option to add svg, it's going to be a completely closed enquiry

You can use any widget and not just an Icon from Icons

**Comment by EgorK0rshun** [comment]
@ellet0 , sorry for the distraction, but can you tell me how I can make it so that several types of lists with custom icons coexist?

I can override it like you suggested. 
```
elementOptions: const QuillEditorElementOptions(
          orderedList: QuillEditorOrderedListElementOptions(
            customWidget: Icon(Icons.add),
          ),
```
But then it will apply to all lists. It should be possible to combine them or show different ones

**Comment by ellet0** [comment]
> @ellet0 , sorry for the distraction, but can you tell me how I can make it so that several types of lists with custom icons coexist?
> 
> I can override it like you suggested. 
> ```
> elementOptions: const QuillEditorElementOptions(
>           orderedList: QuillEditorOrderedListElementOptions(
>             customWidget: Icon(Icons.add),
>           ),
> ```
> But then it will apply to all lists. It should be possible to combine them or show different ones

There is no need to be sorry. In fact, I'm the one who should be sorry

I decided to quit maintaining the library because the lack of time and lost interest in flutter because of kmp

I will only try to fix important bugs and fix my bugs if I caused any

I didn't understand what you mean by combine them? Can you share more info?

**Comment by EgorK0rshun** [comment]
@ellet0 ,I'm sorry to hear that, I really am. I hope you'll be okay. 

About what I wanted:
I wanted the ability to add multiple types of lists. Stars, squares, hearts and so on. So that you could apply these types of lists to the text and they would be equivalent. 

Now, with this implementation, it is possible to use one of them, but I want all kinds of lists to be available to users.
<img width="189" alt="Снимок экрана 2024-01-10 в 13 02 09" src="https://github.com/singerdmx/flutter-quill/assets/120365747/e11cf05f-4403-4892-96a8-b5faab3f58fb">
