### ISSUE TITLE
How can I  make flutter quill (readOnly) can be expandable  like expandable_text when content is long ?

### ISSUE THREAD

**Issue by KP-story** [singerdmx/flutter-quill#1614]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How i do  ?.
https://pub.dev/packages/expandable_text

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by salba360496** [comment]
return ConstraintBox(
        constraints:
            BoxConstraints(minHeight: cHeight(widget.minHeight ?? 1), maxHeight: widget.maxHeight != null ? widget.maxHeight: double.infinity),   child: QuillEditor.basic(configurations:
                QuillEditorConfigurations(readOnly: true, autoFocus: false, controller: _controller)));

**Comment by CatHood0** [comment]
Does this issue still persists? If it does, please reopen this issue.
