### ISSUE TITLE
Where is `QuillToolbarSelectAlignmentButton`?!

### ISSUE THREAD

**Issue by bambinoua** [singerdmx/flutter-quill#1615]
My app is not compiled because of missing `QuillToolbarSelectAlignmentButton`.

Latest update actually breaks the look and app. See #1616

**Comment by ellet0** [comment]
> My app is not compiled because of missing `QuillToolbarSelectAlignmentButton`.
> 
> Latest update actually breaks the look and app. See #1616

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/af52fd3a-e54a-40ab-9771-8b121c613b8e)
It's already there

**Comment by ellet0** [comment]
Fixed

**Comment by ellet0** [comment]
The `QuillToolbarSelectAlignmentButton` is a dropdown button, the `QuillToolbarSelectAlignmentButtons` that has all the buttons in a row
