### ISSUE TITLE
Latest version is REALLY BREAKING (Quill Simple toolbar looks different)

### ISSUE THREAD

**Issue by MacDeveloper1** [singerdmx/flutter-quill#1616]
Here it is how toolbar looked before update to latest version:

![image](https://github.com/singerdmx/flutter-quill/assets/130981115/4b772dac-31e6-47d3-805c-2e2c65e9c832)

Here it is how toolbar looks after update to latest version **(with the same code)**:

![image](https://github.com/singerdmx/flutter-quill/assets/130981115/9d369e56-7b7f-4f8c-aeae-025b3e854db9)

There was a correct rounded rectangle highlighing for buttons but now it is circle and inherited from `InkWell`. There was a button for change alignment. There were correct button and icons sizes. 

Before:
![image](https://github.com/singerdmx/flutter-quill/assets/130981115/3d35e36a-bb1e-4f61-ba35-4018429b4d5c)

After:
![image](https://github.com/singerdmx/flutter-quill/assets/130981115/4aa75fc7-440d-483c-abab-1f06f4e91544)

My dropdown button PR #1575  contained more options like `padding`, `style`, `width`, `itemHeight`, `defaultItemColor`, `renderItemTextStyle`. Those properties were taken from similar dropdown buttons for font families and for sizes? Why do you remove them?

Please restore all  feel&look as it was.

**Comment by ellet0** [comment]
> Here it is how toolbar looked before update to latest version:
> 
> ![image](https://private-user-images.githubusercontent.com/130981115/291530637-4b772dac-31e6-47d3-805c-2e2c65e9c832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTQ2NTMsIm5iZiI6MTcwMjk5NDM1MywicGF0aCI6Ii8xMzA5ODExMTUvMjkxNTMwNjM3LTRiNzcyZGFjLTMxZTYtNDdkMy04MDVjLTJlMmM2NWU5YzgzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMzU5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDlkMDIxYWQwMmUwZGUxNjY1ZWIyYmNiNmY5NTc5OWQ4ZjVkZjFkMTQwN2U0M2I4NTYxMzJkODI3OWNmOTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qsNiIJtc3eDR5E8X45WpmQlI4mADV535oh4YAQkZMAo)
> 
> Here it is how toolbar looks after update to latest version **(with the same code)**:
> 
> ![image](https://private-user-images.githubusercontent.com/130981115/291530896-9d369e56-7b7f-4f8c-aeae-025b3e854db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTQ2NTMsIm5iZiI6MTcwMjk5NDM1MywicGF0aCI6Ii8xMzA5ODExMTUvMjkxNTMwODk2LTlkMzY5ZTU2LTdiN2YtNGY4Yy1hZWFlLTAyNWIzZTg1NGRiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMzU5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmRlMTU0NDk0N2Q2YjY3MDVhYmVlN2ZlZmQwOGIwOWI0MjYwZDQ5ZjA4Njg2ZWIwOWZmY2JkOTgyOGMxZjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ij6iD0CdnL918E0Tt1zxijlxGFGNVwze28y2bmNb_dM)
> 
> There was a correct rounded rectangle highlighing for buttons but now it is circle and inherited from `InkWell`. There was a button for change alignment. There were correct button and icons sizes.
> 
> Before: ![image](https://private-user-images.githubusercontent.com/130981115/291536449-3d35e36a-bb1e-4f61-ba35-4018429b4d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTQ2NTMsIm5iZiI6MTcwMjk5NDM1MywicGF0aCI6Ii8xMzA5ODExMTUvMjkxNTM2NDQ5LTNkMzVlMzZhLWJiMWUtNGY2MS1iYTM1LTQwMTg0MjliNGQ1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMzU5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDM1MjM4OTg0MDMzNjlmOTMwZjE3OGExN2RlMmM1ODhiNTdjMzhmN2U3YTI1NWI1Yjk2MjIzOTU5MDY5MjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GnZ2yxBeZl9PVKjow_55mq_vuhugsSo4CmHYSoQ_epI)
> 
> After: ![image](https://private-user-images.githubusercontent.com/130981115/291536276-4aa75fc7-440d-483c-abab-1f06f4e91544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTQ2NTMsIm5iZiI6MTcwMjk5NDM1MywicGF0aCI6Ii8xMzA5ODExMTUvMjkxNTM2Mjc2LTRhYTc1ZmM3LTQ0MGQtNDgzYy1hYmFiLTFmMDZmNGU5MTU0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMzU5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmQ2MmJjYzUxZWEwYjRiNjQ0NWRjMDk5ZjY0ZjZmYWNhMjZlYjNhMjYwZDBjODg3MmU4M2NjOTU2NzY3MjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fy3uJVMjDlXSNnXlEIlRd-LwDIuCI6TzMkhs-s9MCGE)
> 
> My dropdown button PR #1575 contained more options like `padding`, `style`, `width`, `itemHeight`, `defaultItemColor`, `renderItemTextStyle`. Those properties were taken from similar dropdown buttons for font families and for sizes? Why do you remove them?
> 
> Please restore all feel&look as it was.

Can you share the code sample of the code in your app?

**Comment by MacDeveloper1** [comment]
@ellet0 

> Which version exactly are you using?

I use the pacakge for web. Did you test the package in web? The web platform has hover color, click color etc.

> Because it looks fine in my local machine

It must looks fine on users' machines but not on developer's machine.

This is my code which is not working anymore because of your changes.

```dart
 QuillToolbarSelectHeaderStyleDropdownButton(
    controller: _controller,
    options:
        QuillToolbarSelectHeaderStyleDropdownButtonOptions(
      iconSize: _kIconSize,
      iconTheme: iconTheme,
      tooltip: t.headers,
      padding:
          const EdgeInsets.symmetric(horizontal: 4),   // I NEED THIS
      style: context
          .theme.inputDecorationTheme.labelStyle!
          .copyWith(
              color: kTextColor, fontSize: 12),  // I NEED THIS
      width: 90,  // I NEED THIS
      itemHeight: 36,  // I NEED THIS
      renderItemTextStyle: true,  // I NEED THIS
      defaultItemColor:
          context.theme.colorScheme.primary,  // I NEED THIS
    ),
  ),
  _kSectionDivider,
  QuillToolbarToggleStyleButton(
    attribute: Attribute.bold,
    controller: _controller,
    options: QuillToolbarToggleStyleButtonOptions(
      iconSize: _kIconSize,
      iconTheme: iconTheme,
      tooltip: t.bold,
    ),
),
```

**Comment by MacDeveloper1** [comment]
> Can you share the code sample of the code in your app?

You had those code as it was in PR and you should not change it.

**Comment by EchoEllet** [comment]
> It must looks fine on users' machines but not on developer's machine.

We don't hace access to the users' apps and the code, and since we don't have different examples covering different use cases and without the requested simple, we're only able to test changes on the `example`

> You had those code as it was in PR and you should not change it.

We do review the PRs and might request changes to ensure consistency and having a default that work for most use cases, targeting the latest technologies provided by the Flutter Team

> I use the pacakge for web. Did you test the package in web? The web platform has hover color, click color etc.

The changes seems to be platform independent, though we have tested the changes as well to ensure the layout, responsiveness and the size that fit the other platform screens (on Mobile)
