### ISSUE TITLE
How do I convert HTML to JSON  !!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by chenganlgong** [singerdmx/flutter-quill#1617]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How do I convert HTML to JSON

i try that methods  but error
![image](https://github.com/singerdmx/flutter-quill/assets/83775130/4cfff21c-24a3-43d2-8714-445ad32bcd78)

If you see it, please reply. Thank you

**Comment by ellet0** [comment]
Hi, this feature has been merged into `flutter_quill`

Use Document.fromHtml

it has been removed using a PR, as we said converting and dealing with HTML is experimental and could be removed once again

**Comment by chenganlgong** [comment]
![image](https://github.com/singerdmx/flutter-quill/assets/83775130/58653a81-d5d5-4754-8f58-b8bac14d4e44)


But my Flutter_ Quill also doesn't have Document.fromHtml

**Comment by chenganlgong** [comment]
![Uploading image.png…]()

**Comment by chenganlgong** [comment]
![image](https://github.com/singerdmx/flutter-quill/assets/83775130/8b429734-a534-460d-af53-e70ec7d0beec)

**Comment by chenganlgong** [comment]
> > ![image](https://private-user-images.githubusercontent.com/83775130/291800070-58653a81-d5d5-4754-8f58-b8bac14d4e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjMyNDksIm5iZiI6MTcwMzA2Mjk0OSwicGF0aCI6Ii84Mzc3NTEzMC8yOTE4MDAwNzAtNTg2NTNhODEtZDVkNS00NzU0LThmNTgtYjhiYWMxNGQ0ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NmZiZjYyYjA3Y2JiNjBlNTFlNDI1ZDI0MjRkYWZlYTJhMjljZTZjNGZjN2ZkZTZmZDRiYjY3NjlmNTI3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wDi0KQ2sY4e77nhB_3vNDy27Egw-Qnv3z-vbYWZFpq4)
> > But my Flutter_ Quill also doesn't have Document.fromHtml
> 
> Then please downgrade `quill_html_converter`

I have used quill before_ HTML_ Converter ，but still reporting errors

![image](https://github.com/singerdmx/flutter-quill/assets/83775130/65acd918-ba93-401c-9b60-f563070fac42)
![image](https://github.com/singerdmx/flutter-quill/assets/83775130/2d7dc5ed-a8be-4ef0-ae65-922d3ef48875)

I checked and there is no method from Html in DeltaHtmlExt

**Comment by chenganlgong** [comment]
If I take Flutter_ If the Quill version is upgraded to 9, the project will directly report an error， so my project is v8.6.4 version

**Comment by ellet0** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/83775130/291800070-58653a81-d5d5-4754-8f58-b8bac14d4e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjMyNDksIm5iZiI6MTcwMzA2Mjk0OSwicGF0aCI6Ii84Mzc3NTEzMC8yOTE4MDAwNzAtNTg2NTNhODEtZDVkNS00NzU0LThmNTgtYjhiYWMxNGQ0ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NmZiZjYyYjA3Y2JiNjBlNTFlNDI1ZDI0MjRkYWZlYTJhMjljZTZjNGZjN2ZkZTZmZDRiYjY3NjlmNTI3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wDi0KQ2sY4e77nhB_3vNDy27Egw-Qnv3z-vbYWZFpq4)
> > > But my Flutter_ Quill also doesn't have Document.fromHtml
> > 
> > Then please downgrade `quill_html_converter`
> 
> I have used quill before_ HTML_ Converter ，but still reporting errors
> 
> ![image](https://github.com/singerdmx/flutter-quill/assets/83775130/65acd918-ba93-401c-9b60-f563070fac42)
> ![image](https://github.com/singerdmx/flutter-quill/assets/83775130/2d7dc5ed-a8be-4ef0-ae65-922d3ef48875)
> 
> I checked and there is no method from Html in DeltaHtmlExt
> 
> 

Use Document.fromJson directory

**Comment by chenganlgong** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/83775130/291800070-58653a81-d5d5-4754-8f58-b8bac14d4e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjMyNDksIm5iZiI6MTcwMzA2Mjk0OSwicGF0aCI6Ii84Mzc3NTEzMC8yOTE4MDAwNzAtNTg2NTNhODEtZDVkNS00NzU0LThmNTgtYjhiYWMxNGQ0ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NmZiZjYyYjA3Y2JiNjBlNTFlNDI1ZDI0MjRkYWZlYTJhMjljZTZjNGZjN2ZkZTZmZDRiYjY3NjlmNTI3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wDi0KQ2sY4e77nhB_3vNDy27Egw-Qnv3z-vbYWZFpq4)
> > > > But my Flutter_ Quill also doesn't have Document.fromHtml
> > > 
> > > 
> > > Then please downgrade `quill_html_converter`
> > 
> > 
> > I have used quill before_ HTML_ Converter ，but still reporting errors
> > ![image](https://private-user-images.githubusercontent.com/83775130/292147352-65acd918-ba93-401c-9b60-f563070fac42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjAwNzgsIm5iZiI6MTcwMzE1OTc3OCwicGF0aCI6Ii84Mzc3NTEzMC8yOTIxNDczNTItNjVhY2Q5MTgtYmE5My00MDFjLTliNjAtZjU2MzA3MGZhYzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDExNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNGQ5ZjU5YzRlN2M3NDQ3OWEzOGQ0NGI0YTA2ZWEwMTk0MDMxZjUxNzFjYmMxNjU0YTQ2YzM2ODJmMmI3NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y78CO_VapekqWQNq1ZtSHCiMUkKYQlihzT1y8G74RE4)
> > ![image](https://private-user-images.githubusercontent.com/83775130/292147349-2d7dc5ed-a8be-4ef0-ae65-922d3ef48875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjAwNzgsIm5iZiI6MTcwMzE1OTc3OCwicGF0aCI6Ii84Mzc3NTEzMC8yOTIxNDczNDktMmQ3ZGM1ZWQtYThiZS00ZWYwLWFlNjUtOTIyZDNlZjQ4ODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDExNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNGE0YjgwYzkyMzE1ZWY0YTFjOGU2YTMyM2U2YTBmNzJiNWUwOGNhOTJlYzhjZWZlYWVkNWUzZGMwODI4ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XPfOtV5AVdbA_EUbe-waRumSgc90iDjgWt5Cy0zDeQU)
> > I checked and there is no method from Html in DeltaHtmlExt
> 
> Use Document.fromJson directory
![image](https://github.com/singerdmx/flutter-quill/assets/83775130/873fcf34-4190-49b9-9a73-f03991cc7fe4)
Can you write a complete one for me to see
