### ISSUE TITLE
How do I pick image using file_picker plugin and then insert it into the editor and upload it to Firebase storage

### ISSUE THREAD

**Issue by rajcrack** [singerdmx/flutter-quill#1618]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

in flutter  have to add image in the flutter_quill 8.6.4 and flutter_quill_extension 0.7.2 by using filepicker package and then storing the image  on firebase and then  inserting the image in the quill controller's  text field with image  width same  of the device with a gap of 16 . and then converting the whole data of quill controller along with image to the html so that it can be shown anywhere by just parsing the html data  . how can i do that?

**Comment by ellet0** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### The question
> in flutter have to add image in the flutter_quill 8.6.4 and flutter_quill_extension 0.7.2 by using filepicker package and then storing the image on firebase and then inserting the image in the quill controller's text field with image width same of the device with a gap of 16 . and then converting the whole data of quill controller along with image to the html so that it can be shown anywhere by just parsing the html data . how can i do that?

Take a look at the example

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/9a31d32d-9d2d-44a5-878b-6c8b7228123b)


The `QuillToolbarImageConfigurations` has a few methods that you can use to insert your image and do things to fit your needs, if you have more specific questions feel free to ask.
