### ISSUE TITLE
The package `flutter_quill_extensions` has wrong history of changes

### ISSUE THREAD

**Issue by bambinoua** [singerdmx/flutter-quill#1619]
History of changes of `flutter_quill_extensions` is wrong and copied from `flutter_quill`.

P.S. Actually is it not a bug of package but confusion when you read about changes of classes that are not there.

**Comment by ellet0** [comment]
Correct but we have to because we changed the versioning system to automated the publishing in GitHub and make it easier to notice which version is compatible with another

We had no choice but to start fresh

Feel free to ask more questions
