### ISSUE TITLE
Icon fill Colors not changing in QuillToolbar with QuillIconTheme

### ISSUE THREAD

**Issue by sobimor** [singerdmx/flutter-quill#1620]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.0.3

### Other Flutter Quill packages versions

I've encountered an issue with the QuillToolbar in a Flutter project where the icon fill color does not change as expected. The problem arises when trying to use the `iconSelectedFillColor` and `iconUnselectedFillColor` properties within the `QuillIconTheme`.

Here's a snippet of the code I'm using:

```dart
QuillToolbar.simple(
  configurations: QuillSimpleToolbarConfigurations(
    controller: controller,
    buttonOptions: QuillSimpleToolbarButtonOptions(
      base: QuillToolbarBaseButtonOptions(
        iconTheme: QuillIconTheme(
          iconSelectedFillColor: Colors.red,
          iconUnselectedFillColor: Colors.yellow,
        ),
      ),
    ),
    // Additional configurations...
  ),
),

### Steps to reproduce

1. Use `QuillToolbar.simple`
2. Try to change `iconSelectedFillColor` or `iconUnselectedFillColor` in `QuillIconTheme` of `QuillToolbarBaseButtonOptions`

### Expected results

The icons in the `QuillToolbar` should change their fill colors. Specifically, unselected icons should display `Colors.yellow` (as defined in `iconUnselectedFillColor`), and selected icons should turn `Colors.red` (as set in `iconSelectedFillColor`)

### Actual results

Instead, they retain the default colors from the app's `IconButtonThemeData`, ignoring the custom settings.

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by ellet0** [comment]
That's quite easy to fix, please wait until we fix it

**Comment by ellet0** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Flutter Quill version
> 9.0.3
> 
> ### Other Flutter Quill packages versions
> I've encountered an issue with the QuillToolbar in a Flutter project where the icon fill color does not change as expected. The problem arises when trying to use the `iconSelectedFillColor` and `iconUnselectedFillColor` properties within the `QuillIconTheme`.
> 
> Here's a snippet of the code I'm using:
> 
> ```dart
> QuillToolbar.simple(
>   configurations: QuillSimpleToolbarConfigurations(
>     controller: controller,
>     buttonOptions: QuillSimpleToolbarButtonOptions(
>       base: QuillToolbarBaseButtonOptions(
>         iconTheme: QuillIconTheme(
>           iconSelectedFillColor: Colors.red,
>           iconUnselectedFillColor: Colors.yellow,
>         ),
>       ),
>     ),
>     // Additional configurations...
>   ),
> ),
> 
> ### Steps to reproduce
> 
> 1. Use `QuillToolbar.simple`
> 2. Try to change `iconSelectedFillColor` or `iconUnselectedFillColor` in `QuillIconTheme` of `QuillToolbarBaseButtonOptions`
> 
> ### Expected results
> 
> The icons in the `QuillToolbar` should change their fill colors. Specifically, unselected icons should display `Colors.yellow` (as defined in `iconUnselectedFillColor`), and selected icons should turn `Colors.red` (as set in `iconSelectedFillColor`)
> 
> ### Actual results
> 
> Instead, they retain the default colors from the app's `IconButtonThemeData`, ignoring the custom settings.
> ```

The new way is by settings the primary color scheme in your `ThemeData` in your `MaterialApp`
and it will picked automatically

**Comment by ellet0** [comment]
@singerdmx 
Should we delete the old properties like:

`iconSelectedFillColor`
and 
`iconUnselectedFillColor`

And depends on the `MaterialApp` theme data instead? or update it to use the ones from the old unused properties??

**Comment by thanglq1** [comment]
> @singerdmx Should we delete the old properties like:
> 
> `iconSelectedFillColor` and `iconUnselectedFillColor`
> 
> And depends on the `MaterialApp` theme data instead? or update it to use the ones from the old unused properties??

I think should update it instead of delete so developer can change icon color, not always color of ThemeData.

**Comment by ellet0** [comment]
> > @singerdmx Should we delete the old properties like:
> > `iconSelectedFillColor` and `iconUnselectedFillColor`
> > And depends on the `MaterialApp` theme data instead? or update it to use the ones from the old unused properties??
> 
> I think should update it instead of delete so developer can change icon color, not always color of ThemeData.

The bug is fixed, we will release dev version soon.

**Comment by ellet0** [comment]
Hi @sobimor 

Can you test the latest pre release and see if it fit your needs?

**Comment by sobimor** [comment]
> Hi @sobimor
> 
> Can you test the latest pre release and see if it fit your needs?

Just tested; works properly and fits our needs.

Thanks for the quick update :)

**Comment by ellet0** [comment]
> > Hi @sobimor
> > Can you test the latest pre release and see if it fit your needs?
> 
> Just tested; works properly and fits our needs.
> 
> Thanks for the quick update :)

No needs to thank me, it was my bug after all :)

**Comment by Huando22222** [comment]
@EchoEllet  sir . in version 11.4.1 this issue happens again 🤦‍♂️. Only divider work

**Comment by Nafis71** [comment]
@EchoEllet This issue still persists in 11.4.1

**Comment by EchoEllet** [comment]
Sorry, I'm no longer a project maintainer at this point.
