### ISSUE TITLE
how to insert a new block in quill ?

### ISSUE THREAD

**Issue by rajcrack** [singerdmx/flutter-quill#1629]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

using flutter_quill 9.0.5 i want that on clicking a button i want to insert a small block in quill editor and the rest of line will be empty. the block will have minute rounded corners and background is black and on it there is a word written dynamically

**Comment by ellet0** [comment]
Hi, can you take a look at [this](https://github.com/singerdmx/flutter-quill/blob/master/doc/custom_embed_blocks.md) and see if it solve your question?

**Comment by rajcrack** [comment]
it worked but when i try to convert the quillcontroller which have  customembed block and convert it to html using the  quill_html_converter: ^9.0.5 it does not convert  the custom block into the html is there any way by using which it  can be converted into htnl or i have to use any other ???

**Comment by ellet0** [comment]
> it worked but when i try to convert the quillcontroller which have customembed block and convert it to html using the quill_html_converter: ^9.0.5 it does not convert the custom block into the html is there any way by using which it can be converted into htnl or i have to use any other ???

Unfortunately, the support for quill_html_converter is experimental

**Comment by rajcrack** [comment]
then which one i have to use it to convert to html or in which type i can get the  same like original one after sending from one device to another
