### ISSUE TITLE
There is no quick way to reset the colors for the background and font color

### ISSUE THREAD

**Issue by ellet0** [singerdmx/flutter-quill#1632]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.x.x

### Steps to reproduce

The issue can be happen on any quill version

1. Select a background and font color
2. type some text
3. Now we want to reset it and enter more text

### Expected results

We should be able to reset the colors

### Actual results

We can't reset the colors

### Code sample

No needs for code sample

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/35137270-5bc3-4504-8af5-48dc6f954c59)

</details>

**Comment by brightknight08** [comment]
how do you plan to implement this @ellet0 ?

**Comment by ellet0** [comment]
> how do you plan to implement this @ellet0 ? 

By updating the buttons and add a way to reset the colors

Once I have the time I will start

**Comment by ellet0** [comment]
I added a new button for clear the color and reset back to default
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/a43922d3-f1de-4536-88bf-4d31b383b88a)

It should fix the issue, however the buttons needs to be remade but I don't think the users will like this so I will pass
