### ISSUE TITLE
Compile error at Linux since version 9.0.1 : error: use of undeclared identifier 'gettid' (irondash_engine_context/linux/irondash_engine_context_plugin.cc:30:20:)

### ISSUE THREAD

**Issue by leisu1** [singerdmx/flutter-quill#1637]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.0.1

### Steps to reproduce

1.Compile : Click Debug button or use command flutter run -d linux、flutter build linux

### Expected results

Compile success

### Actual results

Compile failed

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![image](https://github.com/singerdmx/flutter-quill/assets/19525360/3f68db09-6719-431b-a710-df19fe818565)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment]
Hello there, on behalf the Flutter Quill Team I would like to thank you for opening your first issue. Your inputs and insights are valuable in shaping a stable and reliable version for all our users. Thank you for being part of the open-source community!

**Comment by ellet0** [comment]
Before every release, we test building the app on all platforms, you can take a look at [this](https://github.com/singerdmx/flutter-quill/actions/runs/7280210407/job/19838163851)

It build successfully for Linux, it might something wrong in your local configurations or something on our side.

**Comment by leisu1** [comment]
> Before every release, we test building the app on all platforms, you can take a look at [this](https://github.com/singerdmx/flutter-quill/actions/runs/7280210407/job/19838163851)
> 
> It build successfully for Linux, it might something wrong in your local configurations or something on our side.
> 
> in either case we need more info to be fix the issue

Thank you for your response, in my machine the lib libstdc++ is too old.

**Comment by ellet0** [comment]
> > Before every release, we test building the app on all platforms, you can take a look at [this](https://github.com/singerdmx/flutter-quill/actions/runs/7280210407/job/19838163851)
> > It build successfully for Linux, it might something wrong in your local configurations or something on our side.
> > in either case we need more info to be fix the issue
> 
> Thank you for your response, in my machine the lib libstdc++ is too old.

So were you able to fix it?

**Comment by leisu1** [comment]
> > > Before every release, we test building the app on all platforms, you can take a look at [this](https://github.com/singerdmx/flutter-quill/actions/runs/7280210407/job/19838163851)
> > > It build successfully for Linux, it might something wrong in your local configurations or something on our side.
> > > in either case we need more info to be fix the issue
> > 
> > 
> > Thank you for your response, in my machine the lib libstdc++ is too old.
> 
> So were you able to fix it?

Havn't solve till now. The distribution my company used is Deepin which support up to stdlibc++-8-dev. I have tried to switch to ubuntu sources, but many of the system's dependencies rely on the lower version, so it failed. Any suggestions?

**Comment by leisu1** [comment]
@ellet0  I contacted the author of the super_native_extensions library, which has been fixed in version 0.8.1, and quill will also be able to fix it after using the new version. I will use the local path dependency for the time being, and expect your new version.

**Comment by ellet0** [comment]
> @ellet0  I contacted the author of the super_native_extensions library, which has been fixed in version 0.8.1, and quill will also be able to fix it after using the new version. I will use the local path dependency for the time being, and expect your new version. 

Thanks!

**Comment by ellet0** [comment]
> @ellet0 I contacted the author of the super_native_extensions library, which has been fixed in version 0.8.1, and quill will also be able to fix it after using the new version. I will use the local path dependency for the time being, and expect your new version.

Done, you can try `9.1.1`

**Comment by ellet0** [comment]
Let me know if the issue didn't got fixed

**Comment by leisu1** [comment]
> Let me know if the issue didn't got fixed

Yeah. LGTM since 9.1.1
