### ISSUE TITLE
The issue of upgrading to a larger version

### ISSUE THREAD

**Issue by chenganlgong** [singerdmx/flutter-quill#1638]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

  flutter_quill: ^8.6.4   ----->         flutter_quill: ^9.0.3

### Proposal

![image](https://github.com/singerdmx/flutter-quill/assets/83775130/790e0230-b96d-4262-b12d-a0d40837b7a1)
I will encounter this error when upgrading from 8.6.4 to 9.0.3

![image](https://github.com/singerdmx/flutter-quill/assets/83775130/24e7ff91-1b38-4f51-89f2-2817b9425923)
![image](https://github.com/singerdmx/flutter-quill/assets/83775130/afae9d95-18b7-4ffa-a68c-6f8a50c39ec6)
![image](https://github.com/singerdmx/flutter-quill/assets/83775130/8785f7e4-6d3d-4aba-827d-88785c0a0450)
![image](https://github.com/singerdmx/flutter-quill/assets/83775130/eb2dd994-e0d7-4015-95c3-0404c890b095)

**Comment by chenganlgong** [comment]
> Clean the project, rerun `flutter pub get` and the issue should be solved, even though I didn't have to in the example so I don't know why
> 
> can you share more info?

I have tried the first method, but it's not possible

> can you share more info?
The example is possible, but when combined with other packages, it may conflict

**Comment by the-best-is-best** [comment]
yes package issue with me the same in v 9.x.x and it work in mac os but windows not work

**Comment by ellet0** [comment]
Please make sure to follow the [instructions](https://pub.dev/packages/super_clipboard#getting-started) on super clipboard plugin

**Comment by CatHood0** [comment]
This will be closed since we have no responses from the OP. Please, reopen if is needed (i think that wont be the case since we remove `quill_html_converter` and `super_clipboard` is being removed from the `fluter_quill_extensions`).
