### ISSUE TITLE
Cannot convert delta to markdown

### ISSUE THREAD

**Issue by hnvn** [singerdmx/flutter-quill#1644]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.0.1

### Steps to reproduce

Convert Delta to Markdown by using `DeltaToMarkdown()`

```
final delta = _quillController.document.toDelta();
final content = DeltaToMarkdown().convert(delta);
```

Error:
```
Exception: Container of type Root cannot be visited
#0      _NodeX.accept (package:flutter_quill/src/packages/quill_markdown/delta_to_markdown.dart:324:5)
#1      DeltaToMarkdown.convert (package:flutter_quill/src/packages/quill_markdown/delta_to_markdown.dart:57:42)
```

### Expected results

Markdown document

### Actual results

Exception
```
Exception: Container of type Root cannot be visited
```

### Code sample

<details><summary>Code sample</summary>

```dart
Widget _editor() {
    final locale = Localizations.localeOf(context);
    return SliverPadding(
      padding: const EdgeInsets.only(bottom: 24.0),
      sliver: SliverToBoxAdapter(
        child: IntrinsicHeight(
          child: ConstrainedBox(
            constraints: const BoxConstraints(
              minHeight: 100.0,
            ),
            child: QuillEditor.basic(
              focusNode: _focusNode,
              configurations: QuillEditorConfigurations(
                controller: _quillController,
                readOnly: false,
                scrollable: false,
                padding: const EdgeInsets.symmetric(horizontal: 16.0),
                minHeight: 100.0,
                placeholder: S.of(context).messageShareSomething,
                sharedConfigurations: QuillSharedConfigurations(
                  locale: locale,
                ),
                customStyles: DefaultStyles(
                  placeHolder: DefaultTextBlockStyle(
                    Theme.of(context)
                        .textTheme
                        .bodyMedium!
                        .copyWith(color: AppColors.textHint),
                    const VerticalSpacing(0, 0),
                    const VerticalSpacing(0, 0),
                    null,
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
  
  void _submit() {
      final delta = _quillController.document.toDelta();
      final content = DeltaToMarkdown().convert(delta);
      debugPrint(content);
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by hnvn** [comment]
UPDATE: I upgrade to `v9.1.0`, the exception doesn't happen anymore, instead the function `DeltaToMarkdown().convert(delta)` is freezed (running forever)

**Comment by ellet0** [comment]
Hi, `DeltaToMarkdown` is external package that's a little bit out of date because of the breaking changes we made, we used it only for pasting content from external websites into the editor

**Comment by ellet0** [comment]
The [original package](https://pub.dev/packages/markdown_quill)

**Comment by TarekkMA** [comment]
Hello, I'm the maintainer of markdown_quill; I've updated the package to work with the latest flutter_quill version.

I aim to provide more testing and fix all issues in the subsequent few versions of markdown_quill.

Sorry about the long wait; I got busy with life.

**Comment by hnvn** [comment]
@TarekkMA , great work, thank you 🤝
