### ISSUE TITLE
Load html directly into editor or convert HTML into Delta

### ISSUE THREAD

**Issue by Tokenizer94** [singerdmx/flutter-quill#1645]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi. I want to load a HTML string into the editor. If it's not possible then how can i convert my HTML string into Delta?

**Comment by Jinxishihenian** [comment]
I think this will help you
```
_controller.document =  Document.fromDelta(Document.fromHtml(html))
```
This is the API they provide, but the actual effect is not very good, a lot of style loss, strikers, alignment, color......

**Comment by ellet0** [comment]
> This is the API they provide, but the actual effect is not very good, a lot of style loss, strikers, alignment, color......
> 
> #1100

Hi @Jinxishihenian, this is designed to be used only for pasting content from external websites

**Comment by ellet0** [comment]
I reopened the original issue, closing this as it duplicated, but feel free to report more issues or questions

- The original #1100

**Comment by ellet0** [comment]
I reopened the original issue, closing this as it duplicated, but feel free to report more issues or questions

- The original https://github.com/singerdmx/flutter-quill/issues/1100
