### ISSUE TITLE
Is it possible to add maxline and overflow just like Text() widget.

### ISSUE THREAD

**Issue by SM-SHIFAT** [singerdmx/flutter-quill#1660]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

Usecase is, i have a small preview screen where i want to show max 4 line of text then ```...``` at the end. And when user press on it it show full then on the second page. So this is why i need the max line feature. or any way to stop showing more than 4 line of text. 

### Proposal

![image](https://github.com/singerdmx/flutter-quill/assets/60544576/710b8810-915f-487c-98f1-8d591ea633fa)
just like the above picture i want to show only 4 line of text. Suppose it have 10 line of text but only restrict it to show only 4 line of it.

**Comment by adrianHerreraa** [comment]
Does anyone know if this can be done already (I'm on flutter_quill version: ^9.5.15) or not yet?

**Comment by flodaniel** [comment]
I am also trying to build something similar. Could any of you two find a solution @SM-SHIFAT @adrianHerreraa ?

**Comment by CatHood0** [comment]
Currently we have not a way to implement max lines lenght and probably we have no plans to add this.
