### ISSUE TITLE
Toggled Style issue conflict between new line and selection change

### ISSUE THREAD

**Issue by krishnaprasadgandrath-nooor** [singerdmx/flutter-quill#1661]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

latest

### Steps to reproduce

1. Create a Quill with "Keep Style on New line" to true
2. Enter text and add styles and add new lines , the editor will retail styles on new line
3. add one more line and toggle any style on that new line
4. now place cursor anywhere other than last entered line
5. The editor will now has last toggled style "On" and it doesnt match style with existing line style

### Expected results

Editor should be able to differentiate while retaining styles for new line and for change cursor position in existing text

### Actual results

Editor retains style for new line and also retains style for when cursor position is placed in existing text 

### Code sample

///

### Screenshots or Video

Observe Text Unerline when cursor is placed at previously entered line

https://github.com/singerdmx/flutter-quill/assets/94034275/42e913d4-2330-4e55-94f0-7b3440ee38f5

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
This has been fixed in the current version.
If this is still a problem, can you reopen this issue and give us more information about how to reproduce the problem.
