### ISSUE TITLE
Is there a way to add custom items in the right-click menu? 

### ISSUE THREAD

**Issue by kaimatzu** [singerdmx/flutter-quill#1662]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I was looking for a way to add custom right-click items (if that's even possible with quill). I wanna add some sort of custom module that will apply custom transformations to highlighted text and I want to do it via the right click instead of the toolbar

**Comment by kaimatzu** [comment]
nvm i got it

**Comment by szetakyu** [comment]
Can you share on how you did it?

> nvm i got it

**Comment by szetakyu** [comment]
ok, thanks for that
