### ISSUE TITLE
Image Icon Not Found 

### ISSUE THREAD

**Issue by Shivamchauhan29** [singerdmx/flutter-quill#1680]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.5

### Steps to reproduce

I am not getting the image icon in editor tool bar , so i am getting issue in inserting the images to the editor.

Please fix the issue.

### Expected results

i want to get the image icon with its functionality.

### Actual results

I am neither getting the image icon nor image functionality in the editor.

### Code sample

<details><summary>Code sample</summary>

```dart
body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: QuillToolbar.simple(
                configurations: QuillSimpleToolbarConfigurations(
                  multiRowsDisplay: true,
                  showSubscript: false,
                  showSuperscript: false,
                  controller: _controller,
                ),
              ),
            ),
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Container(
                decoration: const BoxDecoration(color: Colors.white),
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: QuillEditor.basic(
                    configurations: QuillEditorConfigurations(
                      sharedConfigurations: _sharedConfigurations,
                      controller: _controller,
                      readOnly: false,
                      customStyles: const DefaultStyles(),
                      elementOptions: const QuillEditorElementOptions(
                        codeBlock: QuillEditorCodeBlockElementOptions(
                          enableLineNumbers: true,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ellet0** [comment]
Hi, which image icon can't be found? can you explain?

**Comment by Shivamchauhan29** [comment]
Image Icon in QuillToolbar to Insert the image into the editor is missing.


I am using this code 

body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: QuillToolbar.simple(
                configurations: QuillSimpleToolbarConfigurations(
                  multiRowsDisplay: true,
                  showSubscript: false,
                  showSuperscript: false,
                  controller: _controller,
                ),
              ),
            ),
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Container(
                decoration: const BoxDecoration(color: Colors.white),
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: QuillEditor.basic(
                    configurations: QuillEditorConfigurations(
                      sharedConfigurations: _sharedConfigurations,
                      controller: _controller,
                      readOnly: false,
                      customStyles: const DefaultStyles(),
                      elementOptions: const QuillEditorElementOptions(
                        codeBlock: QuillEditorCodeBlockElementOptions(
                          enableLineNumbers: true,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          )

**Comment by singerdmx** [comment]
Please try the latest version. Open a new issue if it still exists.
