### ISSUE TITLE
How make selection handles that does not exceed the viewable area of the editor

### ISSUE THREAD

**Issue by chifandeyu** [singerdmx/flutter-quill#1687]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

The selection handles goes out of the editor but area and floats above the other widgets when the editor scrolls.

Screenshot video：
https://github.com/singerdmx/flutter-quill/assets/15946864/7c0ff800-041b-4871-a566-91cd7a806692

**Comment by CatHood0** [comment]
I think this was fixed. So, i will close it. Please, reopen if the issue persists.

**Comment by EchoEllet** [comment]
@chifandeyu Can you confirm if the recent version fixed the issue for for you?
