### ISSUE TITLE
Paste via ctrl+v have some problems when the clipboard has styled text

### ISSUE THREAD

**Issue by X-SLAYER** [singerdmx/flutter-quill#1690]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

flutter_quill: ^9.2.6

### Steps to reproduce

1. Just try to paste the text inside QUilEditor with Ctrl+V

### Expected results

**- First Expectation**
 The text should be pasted where I'm focusing on the editor for example in the 3rd line 
 
**- Second Expectation:**
the QuillController .changes.listen should trigger an event
 

### Actual results

**1 Expectation :** 
The text pasted in the end of lines of the texts

**2 Expectation :** 
the event listener is not being triggered 

### Code sample

```dart

  // Controller
  QuillController _controller = QuillController.basic();
  
  // Listener not veing triggred on Ctrl+V
    docListener = _controller.changes.listen((event) {
      logger.t('${_controller.document.toDelta().toJson()}');
      $collection.setContent(
        widget.note.id,
        jsonEncode(
          _controller.document.toDelta().toJson(),
        ),
      );
    });
  
  // Widget 
    QuillToolbar.simple(
                configurations: QuillSimpleToolbarConfigurations(
                  controller: _controller,
                  showAlignmentButtons: true,
                  showRedo: false,
                  showUndo: false,
                  showSubscript: false,
                  showSuperscript: false,
                  showIndent: false,
                  color: $styles.colors.accent2,
                  embedButtons: [
                    ...FlutterQuillEmbeds.toolbarButtons(
                      videoButtonOptions: null,
                    ),
                  ],
                ),
              ),
```

### Logs

In the previous version I was using  **flutter_quill: ^9.2.2** and I didn't face these problems

**Comment by ellet0** [comment]
Does the text has styling? if yes then this is known issue and I already added a todo for it

**Comment by X-SLAYER** [comment]
Yes I tried it from the search bar as a simple text it works but when I tried to copy from the website or vs-code not working

**Comment by ellet0** [comment]
Fixed
