### ISSUE TITLE
Problems with pasting text into the editor when the clipboard has styled text

### ISSUE THREAD

**Issue by ellet0** [singerdmx/flutter-quill#1696]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.10

### Steps to reproduce

1. Copy a text from some website that has styles (html text)
2. Paste it into the editor

### Expected results

It should paste where we the cursor focus and not at the end of the document

### Actual results

It paste at the end of the document

### Code sample

<details><summary>Code sample</summary>

```dart
final clipboard = SystemClipboard.instance;

    if (clipboard != null) {
      // TODO: Bug, Doesn't replace the selected text, it just add a new one
      final reader = await clipboard.read();
      if (reader.canProvide(Formats.htmlText)) {
        final html = await reader.readValue(Formats.htmlText);
        if (html == null) {
          return;
        }
        final htmlBody = html_parser.parse(html).body?.outerHtml;
        final deltaFromClipboard = Document.fromHtml(htmlBody ?? html);

        var newDelta = Delta();
        newDelta = newDelta.compose(deltaFromClipboard);
        if (!controller.document.isEmpty()) {
          newDelta = newDelta.compose(controller.document.toDelta());
        }

        controller
          ..setContents(
            newDelta,
          )
          ..updateSelection(
            TextSelection.collapsed(
              offset: controller.document.length,
            ),
            ChangeSource.local,
          );

        bringIntoView(textEditingValue.selection.extent);

        // Collapse the selection and hide the toolbar and handles.
        userUpdateTextEditingValue(
          TextEditingValue(
            text: textEditingValue.text,
            selection: TextSelection.collapsed(
              offset: textEditingValue.selection.end,
            ),
          ),
          cause,
        );

        return;
      }
    }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/5400b81c-219f-4d07-952b-8863208cba6a)

</details>

**Comment by mtallenca** [comment]
FYI - this type of paste is using setContents, which creates a new underlying document.  Any change listeners on the old document are not moved nor notified - so future document changes never notify the change listeners on the original document.
