### ISSUE TITLE
Impossibility to delete the first character of the list in an empty document

### ISSUE THREAD

**Issue by EgorK0rshun** [singerdmx/flutter-quill#1700]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.10

### Steps to reproduce

1. Add list without text
2. Try deleting by attempting to erase

### Expected results

The first item in the list will be deleted

### Actual results

The first element of the list remains without the possibility of deletion

### Code sample

<details><summary>Code sample</summary>

```dart
 QuillEditorConfigurations(
        controller: controller,
        scrollable: scrollable,
        padding: padding,
        autoFocus: autofocus,
        expands: expands,
        readOnly: readOnly,
        showCursor: showCursor,
        elementOptions: QuillEditorElementOptions(
          orderedList: QuillEditorOrderedListElementOptions(
            customWidget: Center(child: MyCustomWidget()),
          ),
        ),
       ...
       );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots </summary>

![example](https://github.com/singerdmx/flutter-quill/assets/120365747/3a62e150-a8dd-4de4-9c4d-e0c32396387e)

cannot be deleted with the "delete" button

</details>

**Comment by j-robin-hunter** [comment]
If you read the Delta spec there is no empty document. It has at least a '\n'

**Comment by AtlasAutocode** [comment]
I assume by erasing you are using the backspace key.
This does not work because there is no text to erase - list is an attribute.

I agree that this is not expected if you create the list by entering the keys '1' then '.' then space which auto-converts to list. Others have commented that this auto-conversion should not occur.

You can erase the list by pressing the enter key or using the toolbar button.

**Comment by EgorK0rshun** [comment]
@AtlasAutocode , is it possible to delete using a system button, without using a custom toolbar? My application does not provide such functionality and it looks pretentious

**Comment by AtlasAutocode** [comment]
Are there any questions?
Can I close this issue?
