### ISSUE TITLE
broken link to sample page in readme

### ISSUE THREAD

**Issue by jason-downs** [singerdmx/flutter-quill#1702]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

(latest on master branch)

### Steps to reproduce

On github readme, there is the sentence: "Check out [Sample Page](https://github.com/singerdmx/flutter-quill/blob/master/example/lib/presentation/quill/quill_screen.dart) for more advanced usage."

This goes to a 404 not found page.

### Expected results

Should link properly.

### Actual results

goes to 404 not found, instead of Samples page as intended

### Code sample

(not code-related)

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ellet0** [comment]
Fixed
