### ISSUE TITLE
 [Mobile] copy and paste text with formatting mess up formatting with correct video here #1313 

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#1704]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.10

### Steps to reproduce

1-write any text

2- put part of the text as bold and another part change the color of the text

3- copy and paste this text

### Expected results

text style pasted text be the same

### Actual results

the text style is all messed up

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here

https://github.com/singerdmx/flutter-quill/assets/22117346/fbf7d4b6-19a1-47fd-9fe0-57db8c223f46

]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ellet0** [comment]
Do you want to disable support for styled text or add the option to? it will only paste plain text just like version 8.6.4 and older versions

**Comment by jonasbernardo** [comment]
This problem existed before, it was fixed but it came back 
here is the link to when it was fixed
https://github.com/singerdmx/flutter-quill/issues/1313

**Comment by jonasbernardo** [comment]
here another link
https://github.com/singerdmx/flutter-quill/pull/1321

**Comment by jonasbernardo** [comment]
Is it possible to fix this problem?

**Comment by ellet0** [comment]
> Is it possible to fix this problem?

Try out [this](https://github.com/singerdmx/flutter-quill/tree/disable-html-styling) branch and tell me if it fix the issue

**Comment by jonasbernardo** [comment]
I found the problem, in the master channel of the flutter-quill, it happens that when pasting, the editor buttons are not deactivated, see the video below 

https://github.com/singerdmx/flutter-quill/assets/22117346/0db79539-dd42-46e0-9581-5b31fd909da2

**Comment by EchoEllet** [comment]
@jonasbernardo Can you confirm if this is still an issue?

**Comment by CatHood0** [comment]
@EchoEllet I doubt that this is a problem in itself. The OP does not seem to realize that when he pastes the text, in reality the line from the beginning has the bold attribute applied, which causes the text to take that attribute when copied.
