### ISSUE TITLE
[Web] Any way to disable the clipboard share permission request?

### ISSUE THREAD

**Issue by c-seeger** [singerdmx/flutter-quill#1714]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

When using web by default quill shows a permission notification asking for "See text and images copied to the clipboard". Is there any way to disable this feature completely? I don't want to bother my users with this request at all.

**Comment by darwin-morocho** [comment]
@singerdmx

**Comment by darwin-morocho** [comment]
@c-seeger maybe this can help if you only want to show your delta list

```dart
import 'package:flutter/material.dart';
import 'package:flutter_quill/markdown_quill.dart';
import 'package:flutter_quill/quill_delta.dart';
import 'package:markdown_widget/markdown_widget.dart';

class QuillViewer extends StatelessWidget {
  const QuillViewer({
    super.key,
    required this.data,
  });
  final List data;

  @override
  Widget build(BuildContext context) {
    return MarkdownBlock(
      data: DeltaToMarkdown().convert(
        Delta.fromJson(data),
      ),
    );
  }
}
```

**Comment by IWantToKnowAboutThis** [comment]
I want to use readOnly mode.
I don't know why I keep trying Clipboard share permissions requests on my web browser. 
Does anyone know how to fix this?
😢
