### ISSUE TITLE
Toggling a formatting option in toolbar does not indicate that the option is selected, Button has no "selected" state.

### ISSUE THREAD

**Issue by Wizzel1** [singerdmx/flutter-quill#1716]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.10

### Steps to reproduce

Create a page with this widget

```dart
QuillEditor(
                  configurations: QuillEditorConfigurations(
                    controller: _controller!,
                    scrollable: false,
                    readOnly: readOnly,
                    placeholder:
                        readOnly ? null : T.of(context).richTextNoteHint,
                    padding:
                        kIsWeb ? EdgeInsets.zero : const EdgeInsets.all(20),
                  ),
                ),
```

and toggle Bold, Talic or underlined. 

### Expected results

I expected the buttons of the selected buttons to be hightlighted

### Actual results

Buttons had no "selected" state

**Comment by szuwest** [comment]
I found that you have to use useMaterial3 ThemeData for the selected state...

**Comment by Wizzel1** [comment]
> I found that you have to use useMaterial3 ThemeData for the selected state...

Can you please provide a working example?

**Comment by CatHood0** [comment]
Update to the last version of the editor (10.0.2). This issue is a issue from the version

**Comment by Wizzel1** [comment]
> Update to the last version of the editor (10.0.2). This issue is from that version

The update didn't change anything. I still don't have a toggled formatting button 
![IMG_0288](https://github.com/user-attachments/assets/119f9261-fb14-40e3-afff-729f3bdae76b)

**Comment by CatHood0** [comment]
> The update didn't change anything. 

I made the same but, i get the expected behavior with the version 10.0.2

![Screenshot_20240722-115403~2](https://github.com/user-attachments/assets/a6e04361-ea35-4ec5-9aa5-310101550344)

**Comment by szuwest** [comment]
> > I found that you have to use useMaterial3 ThemeData for the selected state...
> 
> Can you please provide an example? Its not working for me even if I wrap it in a material 3 theme

If you don't want to use material3, you have to set this
QuillToolbar.simple(
          configurations: QuillSimpleToolbarConfigurations(
              buttonOptions: QuillSimpleToolbarButtonOptions(
                  base: QuillToolbarBaseButtonOptions(
                      iconTheme: QuillIconTheme(
                          color: Color.red //import here

**Comment by Wizzel1** [comment]
> > > I found that you have to use useMaterial3 ThemeData for the selected state...
> > 
> > 
> > Can you please provide an example? Its not working for me even if I wrap it in a material 3 theme
> 
> If you don't want to use material3, you have to set this QuillToolbar.simple( configurations: QuillSimpleToolbarConfigurations( buttonOptions: QuillSimpleToolbarButtonOptions( base: QuillToolbarBaseButtonOptions( iconTheme: QuillIconTheme( color: Color.red //important here

Thanks that is working for me!
