### ISSUE TITLE
Error: The method 'GalPluginLinux.putImageBytes' has fewer named arguments than those of overridden method 'GalPlatform.putImageBytes'.

### ISSUE THREAD

**Issue by rt234cw** [singerdmx/flutter-quill#1725]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

```
./../../.pub-cache/hosted/pub.dev/gal_linux-0.0.1/lib/src/gal_linux.dart:25:16: Error: The method 'GalPluginLinux.putImageBytes' has fewer named arguments than those of overridden method 'GalPlatform.putImageBytes'.
  Future<void> putImageBytes(Uint8List bytes, {String? album}) =>
               ^
../../../.pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
  Future<void> putImageBytes(Uint8List bytes,
```

I'm not sure if this is the right place to post, but I've encountered an error after upgrading packages, which prevents me from installing the app on my phone. However, if I comment out `flutter_quill_extension`, the app runs normally. This issue arises because `flutter_quill_extension` depends on `gal_linux-0.0.1`, and it seems this problem cannot be resolved by upgrading.

**Comment by gcjjyy** [comment]
I resolved this problem via adding gal dependency override. like this:

```
dependency_overrides:
  gal: ^2.3.0
  flutter_keyboard_visibility: ^6.0.0
```

**Comment by gcjjyy** [comment]
I resolved this issue via adding dependency overrides to pubspec.yaml like below:
```
dependency_overrides:
  gal: ^2.3.0
  gal_linux: ^0.1.0
```

**Comment by rt234cw** [comment]
> I resolved this issue via adding dependency overrides to pubspec.yaml like below:
> 
> ```
> dependency_overrides:
>   gal: ^2.3.0
>   gal_linux: ^0.1.0
> ```

Thanks!
It solves my problem
