### ISSUE TITLE
Disable context menu after selection for desktop platform

### ISSUE THREAD

**Issue by kamilkarp** [singerdmx/flutter-quill#1742]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How could I change default behaviour of context menu showing after selection? On desktop platforms context menu is showing after user selects the text, selects all with double click etc. I think this is not normal behaviour on desktop and all of our users think that this is weird.

How can I make it that for desktop platform context menu for selection will show only when right clicking the selection?

**Comment by AnAlpaca** [comment]
I too am trying to solve this issue as I have the exact same problems. Users just dont find it natural and I often receive complaints from users about this. Any assistance would be greatly appreciaited.

**Comment by marcio-ota** [comment]
```
contextMenuBuilder: (context, state) {
  return const SizedBox.shrink();
},
```

**Comment by moconchobhair** [comment]
Thanks @marcio-ota for the tip, that does solve the immediate issue. 

Unfortunately, it also seems to disable context menus altogether, which means no copy/paste functionality. 

The correct behaviour would be to display the context menu on a tap or right click of selected text. Has anyone figured out how to make that happen?

thanks again!

**Comment by changguangyu** [comment]
Same issue here, context menu always shows after selection.
