### ISSUE TITLE
Quill HTML converter version solving failed

### ISSUE THREAD

**Issue by duck-dev-go** [singerdmx/flutter-quill#1748]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.0

### Steps to reproduce

Install flutter_quill and then install quill_html_converter 9.0.0

### Expected results

quill_html_converter install correctly

### Actual results

Getting a version mismatch

### Code sample

<details>
</details>

### Logs

Because quill_html_converter >=9.0.0 depends on dart_quill_delta ^0.0.1 and flutter_quill 9.3.0 depends on dart_quill_delta ^9.2.10, quill_html_converter >=9.0.0 is incompatible with flutter_quill 9.3.0.
Because no versions of flutter_quill match >9.3.0 <9.3.1 and flutter_quill >=9.3.1 requires Flutter SDK version >=3.19.0, flutter_quill >9.3.0 is forbidden.
Thus, quill_html_converter >=9.0.0 is incompatible with flutter_quill >=9.3.0.
So, because games_builder_editor depends on both flutter_quill ^9.3.0 and quill_html_converter ^9.3.1, version solving failed.

**Comment by Mina-Nashaat10** [comment]
any updates ??

**Comment by Abdul-rehman0045** [comment]
I am also getting the same error.
