### ISSUE TITLE
DeltaX not recognized

### ISSUE THREAD

**Issue by SSoetaert** [singerdmx/flutter-quill#1750]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.1

### Steps to reproduce

_Breaking change: Document.fromHtml(html) is now returns Document instead of Delta, use DeltaX.fromHtml to return Delta_

When using DeltaX.fromHtml, this isn't recognized.
How can we create a Delta from HTML after recent changes?

### Expected results

DeltaX.fromHtml can be used

### Actual results

DeltaX.fromHtml is not recognized

### Code sample

<details><summary>Code sample</summary>

```dart
DeltaX.fromHtml(comment),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by sort72** [comment]
Up

It seems they forgot to add delta_x to exports in https://github.com/singerdmx/flutter-quill/blob/master/lib/flutter_quill.dart

**Comment by EchoEllet** [comment]
> It seems they forgot to add delta_x to exports in https://github.com/singerdmx/flutter-quill/blob/master/lib/flutter_quill.dart

Actually, we didn't since this is meant to be used as part of the internal API and we don't plan on maintain it for the public use as breaking changes can be introduced, it's being removed and it has been 3 months since we deprecated it.
