### ISSUE TITLE
How to use more than QuillEditor on the same screen? 

### ISSUE THREAD

**Issue by naifalharbi202** [singerdmx/flutter-quill#1751]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi,

I have a Flutter app where I need to use multiple Text Rich Fields ( QuillEditors) in the same screen. However, QuillToolBar and QuillEditor have the same controller as shown in the documentation as well :

QuillController _controller = QuillController.basic();

This means, if I create another QuillEditor in the same screen.. Whatever I edit in the first QuillEditor will automatically be applied to the other one/s.

How to deal with this issue? I would totally appreciate if you just can show a simple example for that.

Thank you in advance.

**Comment by Cierra-Runis** [comment]
One editor one controller, did you pass one controller to different editor?

**Comment by Cierra-Runis** [comment]
Is that you want to use one toolbar for two editor?

**Comment by naifalharbi202** [comment]
> Is that you want to use one toolbar for two editors? Two controller are still necessary, maybe you can pass the controller which editor is focused to the toolbar.

Yes, how to do that?

**Comment by naifalharbi202** [comment]
I am still waiting a solution for this issue.

I tried to figure out what function is really triggered when a user type something like onChanged for example so I can implement a workaround for that but I couldn't find one.

onTapDown 
onTapUp 

and all onTap functions don't trigger what I want.

**Comment by naifalharbi202** [comment]
I managed to solve it using QuillController's TextSelection property which is not there in QuillController.basic. 

It's triggered everytime you type something, there I managed to do some logic which enabled me to control QuillEditors separately.

**Comment by softwaredementor** [comment]
> I managed to solve it using QuillController's TextSelection property which is not there in QuillController.basic.
> 
> It's triggered every time you type something, there I managed to do some logic which enabled me to control QuillEditors separately.

Hello, thanks for creating this thread. I've run into a similar issue and looking for solutions to solve this. Can you please share a basic example of how you solved it?
