### ISSUE TITLE
[Bug] Mouse cursor is still text insertion type when `readOnly` is `false`

### ISSUE THREAD

**Issue by Cierra-Runis** [singerdmx/flutter-quill#1752]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.1

### Steps to reproduce

Set `readOnly` to `false` and move mouse cursor above text.

### Expected results

Mouse cursor should be normal type when `readOnly` is `false`.

### Actual results

![IMG_20240222_173530](https://github.com/singerdmx/flutter-quill/assets/29329988/b5148850-fbde-42df-ba60-8ebd2f31bb56)

### Code sample

None.

**Comment by geronimol** [comment]
Is there any workaround for this?

**Comment by Cierra-Runis** [comment]
> Is there any workaround for this?

I will try to fix it tomorrow.

**Comment by geronimol** [comment]
I just tested this fix on Web and MacOS using flutter_quill 9.3.20, but didn't work for me.

Am I doing something wrong?

```dart
_controller = QuillController(
        document: delta,
        selection: const TextSelection.collapsed(offset: 0),
        readOnly: true,
      );
```

```dart
return QuillEditor.basic(
      configurations: QuillEditorConfigurations(
        controller: _controller,
        scrollable: false,
        enableInteractiveSelection: false,
        readOnlyMouseCursor: SystemMouseCursors.wait,
        // readOnly: true,
        // enableSelectionToolbar: false,
        // showCursor: false,
      ),
    );
 ```

**Comment by Cierra-Runis** [comment]
I test it on my mac, and it doesn't work too. I tried other cursor type and some of them are worked.

I check the comment of `SystemMouseCursors.wait`, and it mentions that:

> This cursor is not available as a system cursor on macOS. Although macOS displays a "spinning ball" cursor when busy, it's handled by the OS and not exposed for applications to choose.

I noticed that `SystemMouseCursors.progress` is similar to `SystemMouseCursors.wait`, you can try it on Linux.

**Comment by geronimol** [comment]
Tried that cursor and others but didn't work on web and macOS. Is it working on web for you? Thanks
