### ISSUE TITLE
Font And Font size, Bold, etc not work

### ISSUE THREAD

**Issue by 5566** [singerdmx/flutter-quill#1757]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.1

### Steps to reproduce

Why I changed the font size，then start input， but the font size of input string is not use the selected font size。。。。。and when I selected some string，then change the font size，the font size of selected strings will changed

### Expected results

font and size can work

### Actual results

change font and size not work

### Code sample

<details><summary>Code sample</summary>

var quillToolbar = QuillToolbar.simple(
        configurations: QuillSimpleToolbarConfigurations(
          controller: _quillController,
          showAlignmentButtons: true,
          showSmallButton: true,
          multiRowsDisplay: false,
          fontSizesValues: {
            '14': '14',
            '16': '16',
            '18': '18',
            '20': '20',
            '22': '22',
            '24': '24',
            '30': '30',
            '48': '48',
          },
          embedButtons: FlutterQuillEmbeds.toolbarButtons(),
          // embedButtons: FlutterQuillEmbeds.toolbarButtons(
          //     imageButtonOptions: QuillToolbarImageButtonOptions(
          //         imageButtonConfigurations: QuillToolbarImageConfigurations()),)
        ),
    );

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

</details>

**Comment by OHeroJ** [comment]
+1, the same issue

**Comment by AtlasAutocode** [comment]
There have been a number of updates relating to this kind of problem.
If the current version does not fix this issue, please reopen with details of what is still not working.
