### ISSUE TITLE
Tripple click should select the entire paragraph

### ISSUE THREAD

**Issue by jezell** [singerdmx/flutter-quill#1758]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

People are trying to triple click to select paragraphs because that's how it works in every other editor.

### Proposal

Tripple click should select the entire paragraph

**Comment by EchoEllet** [comment]
@jezell Can you confirm if this is still an issue in future releases?
