### ISSUE TITLE
Saving image file should say where it has been saved on desktop

### ISSUE THREAD

**Issue by Muhammed-Rahif** [singerdmx/flutter-quill#1759]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

Follow:
1. Add image
2. Click on the added image, image menu popup will appear
3. From the image menu click on save 
4. A result snackbar will appear

On the result snackbar it should say where the image file has been saved, otherwise on different platforms it hard to find where it. The result snackbar should say something like: `"The image has been saved at: path/to/location"`

The current message is `"Saved using the network"`. 

I was using flutter quill on linux, after saving the image file I have searched it on all folders to find it. After some effort I found it was [`gal`](https://pub.dev/packages/gal) or [`gal_linux`](https://pub.dev/packages/gal_linux) is saving it on `/tmp/gal/image.png'.

**Comment by ellet0** [comment]
I might do this for desktop but for mobile it's not a good idea as the app is sandboxed and the path will be useless

**Comment by Muhammed-Rahif** [comment]
I see this has implemented on https://github.com/singerdmx/flutter-quill/blob/b7711bb46d6ad3e4f0d6942335a753b6818e28c0/flutter_quill_extensions/lib/embeds/image/editor/image_menu.dart#L172

**Comment by Muhammed-Rahif** [comment]
> I might do this for desktop but for mobile it's not a good idea as the app is sandboxed and the path will be useless

Does this work on mobile devices now or only for desktop as previously said?

**Comment by EchoEllet** [comment]
> Does this work on mobile devices now or only for desktop as previously said?

Previously for mobile, desktop support was broken or confusing, and the web was not supported.

It works on all platforms now (not merged or published yet), including the web. The message is slightly different based on the platform, and no longer shows `Saved using the network` (messages have been improved).

As for the image file path (where it has been saved), currently, it shows the Snackbar message with an action (labeled `Open File Location`) that opens the file in the system file explorer. I do plan on making some changes before publishing:

* Whether it should show the image file path in the message itself; it's no longer useful, the button can open it within the system file explorer.
* Whether the action should open the directory of that saved file or the file itself, this can be slightly different based on the platform.

The Snackbar message:

* Desktop: `Image saved successfully.` with action labeled `Open File Location`.
* Web: `Image downloaded successfully.` with no action; it's not needed.
* Gallery image save (supports mobile platforms + macOS): `Image saved to your gallery.` with action labeled `Open Gallery`.

Refer to #2403 for more details.
