### ISSUE TITLE
I'm trying to run the application on the Android emulator, but it gives an ndkVersion error

### ISSUE THREAD

**Issue by Leonardo1952** [singerdmx/flutter-quill#1767]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

![Captura de tela 2024-03-11 103518](https://github.com/singerdmx/flutter-quill/assets/53130191/2d590d25-3c8b-4d2c-b7e6-30b2a4020630)

**Comment by AtlasAutocode** [comment]
I recently had an ndkVersion error.
I was able to fix the problem when I found the following block was missing from the main android\build.gradle file

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

No idea why it was missing or why it cured the problem! I assume it was a path problem.

**Comment by Leonardo1952** [comment]
I managed to solve the problem, it was a problem related to settings due to the application's superclipboard. I configured the file `android/app/build.gradle` and `android/app/src/main/AndroidManifest.xml`
