### ISSUE TITLE
Why the controller of the QuillEditor does not have an insert text method?

### ISSUE THREAD

**Issue by szetakyu** [singerdmx/flutter-quill#1769]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Why the controller of the QuillEditor does not have an insert text method?

**Comment by mrmhthegreat** [comment]
controller.document.insert(controller.index,text)

**Comment by szetakyu** [comment]
Thanks!
