### ISSUE TITLE
How to add image in flutter 9.2.14 

### ISSUE THREAD

**Issue by MaheshManoharan** [singerdmx/flutter-quill#1770]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

i have been creating an app. I tried to add image in flutter_quill 9.2.14 version. older version it was fine to add image. but now I can't add it. It shows "A GlobalKey was used multiple times inside one widget's child list. The offending Globalkey was [Globalkey #17087] . The parent of the widgets with that key was: ScribbleFocusable .  I just did below. 

` QuillToolbar.simple(
              configurations: QuillSimpleToolbarConfigurations(
                controller: _controller,               
                embedButtons: FlutterQuillEmbeds.toolbarButtons(
                  imageButtonOptions: QuillToolbarImageButtonOptions(
                    afterButtonPressed: () {
//pickImage uses delta as to store image which picked from gallery.
                   _pickImage();
                    },
                  ),
                ),
                sharedConfigurations: const QuillSharedConfigurations(
                  locale: Locale('de'),
                ),
              ),`

what to do just give me an idea. I searched through stackoverflow. but didnt found anything new. Thanks

**Comment by singerdmx** [comment]
Try the latest version and open a new issue if it still exists
