### ISSUE TITLE
heading 

### ISSUE THREAD

**Issue by charbeltohme13** [singerdmx/flutter-quill#1773]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

why the delta for the heading is like that [{insert: heading 1}, {insert: 
      , attributes: {header: 1}}, how i can get it like bold {insert: bold, attributes: {bold: true}} i want to have the delta json in heading like that {insert: heading 1, attributes: {header: 1}}

**Comment by AtlasAutocode** [comment]
header is a block-attribute and is attached to the '\\n' - it cannot be attached to text.
bold is an inline-attribute and is associated with the text it applies to.

As far as I understand it, it would be illegal to do what you want.

**Comment by jingfeng-cheah** [comment]
@AtlasAutocode However, because the Header Attribute is a block attribute, it makes it impossible to copy that line of text and copy to another line with the Header attribute data. How can we change the Header Attribute to use inline instead of block?

**Comment by AtlasAutocode** [comment]
The header attribute is associated with the '\n' at end of line. To copy a header with attribute, make sure to include the full line including the '\n' and not just the text on the line.

> Header
next line

Select from the 'H' up to 'n' which includes the '\n'. Copy-paste will now copy the header with header attribute.
If you select from the 'H' up to the 'r', you will only be copying the text 'Header' that does not include the header attribute.

> How can we change the Header Attribute to use inline instead of block?

Seems like this would be a major break from the whole quill editor definition. I guess you could define a new custom attribute and implement the code yourself. I defer to those more knowledgeable than me.

**Comment by jingfeng-cheah** [comment]
@AtlasAutocode Thank you for your prompt reply. May I know how I can modify the package to copy the full line including the '\n'? Because I can't seem to find the implementation for the copying of text with the Header attribute. I've been searching the whole day in the codebase and it shows different functionalities when copying block and inline attributes but I just can't find the one for Header.

**Comment by AtlasAutocode** [comment]
The end user needs to include the full line in what they select. 
You can't modify the package.
(Well technically, you can do anything you want! - you could examine the selection and recognize that the next unselected character is a newline with header attribute and then extend the selection by 1 character.)
I regret that I cannot help you any further. I suggest you open a new issue to get feedback from others who are more knowledgeable than me.
