### ISSUE TITLE
flutter quill Bold not work

### ISSUE THREAD

**Issue by SEELELancelot** [singerdmx/flutter-quill#1775]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.1

### Steps to reproduce

Windows platform ,
download the https://github.com/singerdmx/flutter-quill/ 
run the example, the bold button does not correctly work 

### Expected results

When the bold button clicked, the text bold or cancel bold

### Actual results

the bold button does not correctly work 

### Code sample

<details><summary>Code sample</summary>

```dart
  QuillToolbarToggleStyleButton(
                    options: const QuillToolbarToggleStyleButtonOptions(),
                    controller: controller,
                    attribute: Attribute.bold,
                  ),

QuillEditor.basic(
              configurations: QuillEditorConfigurations(
                controller: _controller,
                padding: const EdgeInsets.all(16),
              ),
            ),

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/singerdmx/flutter-quill/assets/36724474/8150293b-09c7-4d6d-a50f-5d34ecb70997

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by kongpf8848** [comment]
please set **keepStyleOnNewLine** value is false for QuillController，like below:

```dart
QuillController(
    keepStyleOnNewLine: false,
    document: Document(),
    selection: const TextSelection.collapsed(offset: 0),
)
```
