### ISSUE TITLE
How to customize FontSize/Family and color, on the context menu?

### ISSUE THREAD

**Issue by marcio-ota** [singerdmx/flutter-quill#1777]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I already customized the button on the taskbar (font size, options), but I can't find how to do it in the menu...
 ```
QuillToolbarFontSizeButton(
  controller: controller,
  options: const QuillToolbarFontSizeButtonOptions(
    attribute: Attribute.font,
    initialValue: 'Normal',
    style: TextStyle(fontSize: 14),
    rawItemsMap: { 'Normal': '14, 'Small': '8, 'Large': '16' },
  ),
),
```
![print](https://github.com/singerdmx/flutter-quill/assets/13367274/1e833e55-5824-4d57-9922-c55329339852)

**Comment by ellet0** [comment]
Developing a 100% customizable library requires a lot of effort, you can use your own button or customize it, we already have Apis for interacting with the editor, you just have to use them to fit your needs

**Comment by saconger** [comment]
```
    _fontFamilies = {
      'Amatic': GoogleFonts.amaticSc().fontFamily!,
      'Annie': GoogleFonts.annieUseYourTelescope().fontFamily!,
      'Formal': GoogleFonts.petitFormalScript().fontFamily!,
      'Roboto': GoogleFonts.roboto().fontFamily!
    };
```

```
 QuillToolbar.simple(
        configurations: QuillSimpleToolbarConfigurations(
            buttonOptions: QuillSimpleToolbarButtonOptions(
                fontFamily: QuillToolbarFontFamilyButtonOptions(rawItemsMap: _fontFamilies, iconSize: 16),
                fontSize: QuillToolbarFontSizeButtonOptions(rawItemsMap: _fontSizes, iconSize: 16),
```



<img width="387" alt="Screenshot 2024-05-31 at 1 44 48 PM" src="https://github.com/singerdmx/flutter-quill/assets/7672114/bf5096da-ceaf-4d91-905d-f56be50f18e3">

**Comment by AtlasAutocode** [comment]
Closed as answered.
