### ISSUE TITLE
how to change the default text color

### ISSUE THREAD

**Issue by cledsonv** [singerdmx/flutter-quill#1778]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How can I change the color of text written in QuilEditor by default and also change the color of the point and numbers of numbered lists and list bullets

**Comment by 10MoSi01** [comment]
You could try wrapping the `QuillEditor` inside a `Theme` widget and play around with `ThemeData`.
This works, at-least for the text color...

**Comment by saconger** [comment]
```
QuillEditor(
    customStyles: DefaultStyles(
       paragraph: DefaultListBlockStyle( //default text color here
       list: //default list style here
```

**Comment by geronimol** [comment]
```dart
_controller.formatTextStyle(0, 0, Style.fromJson({'color': '#fcba03', 'size': 24.0})); 
```

**Comment by CatHood0** [comment]
This is duplicated.
