### ISSUE TITLE
Keyboard jumps when QuillEditor gains focus

### ISSUE THREAD

**Issue by oligazar** [singerdmx/flutter-quill#1779]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.3

### Steps to reproduce

There're a TextField and a QuillEditor on the page
1. Type in some text in the TextField. The keyboard is visible on the screen
2. Switch focus to the QuillEditor by tapping on it

### Expected results

Keyboard shouldn't jump when switching from TextField to QuillEditor.

### Actual results

The issue is when selecting QuillEditor the keyboard starts 'close' animation briefly and then returns back resulting in keyboard jump. 

The reason appears to be that QuillController first notifies `_didChangeTextEditingValueListener` which results in marking the editor as dirty. And then in `_handleFocusChanged` instead of requesting keyboard immediately it's done in a post frame callback due to the editor's 'dirty' state.

If I simply comment out those lines in `raw_editor_state`, keyboard doesn't jump anymore:
```
void _handleFocusChanged() {
    // if (dirty) {
    //   SchedulerBinding.instance
    //       .addPostFrameCallback((_) => _handleFocusChanged());
    //   return;
    // }
    openOrCloseConnection();
...
}
```
But I suppose there's a reason to have the check there.

It also seems like if QuillController would notify about changes after `onSingleTapUp` event, the issue wouldn't happen.
So, how do you see this issue fixed, what do you think?

### Code sample

<details><summary>Code sample</summary>

```dart
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _focusNode = FocusNode();
  final _scrollController = ScrollController();
  final _quillController = QuillController.basic();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const TextField(
              decoration: InputDecoration(
                labelText: 'Text',
              ),
            ),
            QuillEditor(
              focusNode: _focusNode,
              configurations: QuillEditorConfigurations(
                controller: _quillController,
                minHeight: 300,
              ),
              scrollController: _scrollController,
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/singerdmx/flutter-quill/assets/10890674/e9103d3a-c3eb-47e0-9cf4-385aa1e8f91f

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by badayumut** [comment]
i think this package maintained while drunk
