### ISSUE TITLE
Caret isn't interactable on mobile devices

### ISSUE THREAD

**Issue by 10MoSi01** [singerdmx/flutter-quill#1780]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

On mobile devices, the caret can be moved by tapping on the desired position, but it can’t be grabbed and dragged around. Additionally, it should also display magnified text.

Is there any setup required or are there parameters that need changing?
Or have these features not been implemented yet?

**Comment by 10MoSi01** [comment]
P.S I'm aware magnification is stated as TODO in features.
But I am not sure about the caret/cursor intractability.

**Comment by CatHood0** [comment]
This was fixed on the last version. Please update to this last one. Reopen if it does not works for you.
