### ISSUE TITLE
Quil Delta to Docx, is it possible to convert the quil delta to docx format?

### ISSUE THREAD

**Issue by lordethyed** [singerdmx/flutter-quill#1787]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

It will be really useful because it will add feature as downloading the text and etc

### Proposal

Personally it will help me to make a new feature with quil :)

**Comment by ellet0** [comment]
The current implementation of converting to HTML and PDF is already experimental and messy, I don't think it's a good idea to make a new feature for this, but you can always convert the quill delta yourself, if you have any questions just ask it and we will do our best, but anything is related to Microsoft format I'm not familiar with

**Comment by CatHood0** [comment]
You need to use `docx_template` package, and create your own implementation to create that feature
