### ISSUE TITLE
[Quill_Html_Converter] - Converting from delta to HTML incorrectly converts HTML codes into their corresponding characters.

### ISSUE THREAD

**Issue by bradfrizzell** [singerdmx/flutter-quill#1792]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

1. Create a flutter quill editor instance
2. In the document, type in any HTML character code, for example `&#49;`. 
3. Use the controller of the document to extract the delta `delta = controller.document.toDelta()`
4. Convert the delta to HTML - `delta.toHtml()` 

### Expected results

You should keep the characters as the user input them into the document, e.g. toHtml should output `&#49;`

### Actual results

It will output the corresponding character, in this case `1`

### Code sample

<details><summary>Code sample</summary>

```dart
    var text = quillController.document.toDelta().toHtml();
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
I will close this issue since we remove and deprecate any thing related woth HTML and Markdown convertions
