### ISSUE TITLE
How to add table in flutter quill

### ISSUE THREAD

**Issue by Palimoraihan** [singerdmx/flutter-quill#1802]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How i can add some table in flutter quill, and convert the result to html

**Comment by iamlucy18** [comment]
+1

**Comment by wudiplk** [comment]
+1

**Comment by singerdmx** [comment]
Duplicate of https://github.com/singerdmx/flutter-quill/issues/1735
