### ISSUE TITLE
Doble space after a pasted link add an unwanted dot 

### ISSUE THREAD

**Issue by mbenci** [singerdmx/flutter-quill#1804]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.6

### Steps to reproduce

1. in case of physical android device make sure your keyboard has the "double space per period" setting enabled, but you can reproduce the error also in android and ios simulator
2. copy a link (for example https://github.com) from the browser 
3. open the quill example app, empty section 
4. paste the link
5. immediately after the link add two spaces

### Expected results

Text: https://github.com
Link: https://github.com

### Actual results

Text: https://github.com
Link: https://github.com.

Notice: these is a point at the end of a link which can make the link invalid but the writer doesn't notice

### Code sample

No changes to the sample code

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="411" alt="Screenshot 2024-04-05 alle 10 10 38" src="https://github.com/singerdmx/flutter-quill/assets/1177947/0bdd64fc-d6f6-48f2-9f2a-12e865275c91">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
Does this issue still persists? I will close it. If it does, please reopen.

**Comment by EchoEllet** [comment]
@mbenci Can you confirm if this still an issue?
