### ISSUE TITLE
Even though I marked the text with code, it shows html

### ISSUE THREAD

**Issue by tekink** [singerdmx/flutter-quill#1808]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.6

### Steps to reproduce

This is code
![11](https://github.com/singerdmx/flutter-quill/assets/88088517/8141297e-6813-47e4-93bc-f63e456a63f2)

### Expected results

I expect it to say < integer > next to the one marked with code.

### Actual results

![12](https://github.com/singerdmx/flutter-quill/assets/88088517/b1927b41-b1a6-4cbb-8c02-6bef1ea3a352)

### Code sample

<details><summary>Code sample</summary>

```dart
   List deltaJson = htmlController.document.toDelta().toJson();
   String html= DeltaToHTML.encodeJson(deltaJson);
```
html is equal to with debugPrint
`test<pre><code style='color:#3F51B5; background-color:#f1f1f1; padding: 0px 4px;'>test<integer></code></pre>test<br><br> `
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ellet0** [comment]
Which package are you using to convert to Html?

**Comment by tekink** [comment]
> Which package are you using to convert to Html?

flutter_quill and flutter_widget_from_html, same result.

**Comment by CatHood0** [comment]
I think this is outdated. I will close it since the implementation from HTML was removed or deprecated.

**Comment by EchoEllet** [comment]
> deprecated

Until now it's deprecated and not part of the project.
