### ISSUE TITLE
intl ^0.19.0

### ISSUE THREAD

**Issue by cgzcgb** [singerdmx/flutter-quill#1813]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Resolving dependencies...
Because flutter_quill >=9.2.4 depends on intl ^0.18.1 and nnbq depends on intl ^0.19.0, flutter_quill >=9.2.4 is forbidden.
So, because nnbq depends on flutter_quill ^9.3.6, version solving failed.

**Comment by Strain-solutions** [comment]
As an update in case it is useful, Im building for web and attempted to override the intl in pubspec.yml

`dependency_overrides:
  intl: ^0.19.0

`

While that appears to work it then throws errors for flutter-colorpicker 

`../.pub-cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/colorpicker.dart:659:53: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter_sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                        Theme.of(context).textTheme.bodyText1,
                                                    ^^^^^^^^^
../.pub-cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/colorpicker.dart:669:53: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter_sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
                        Theme.of(context).textTheme.bodyText2,
                                                    ^^^^^^^^^
../.pub-cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/palette.dart:951:55: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter_sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                          Theme.of(context).textTheme.bodyText1,
                                                      ^^^^^^^^^
../.pub-cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/palette.dart:960:57: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter_sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
                            Theme.of(context).textTheme.bodyText2,
                                                        ^^^^^^^^^
../.pub-cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/palette.dart:1042:58: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter_sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
          Text('Hex', style: Theme.of(context).textTheme.bodyText1),
                                                         ^^^^^^^^^
../.pub-cache/hosted/pub.dev/flutter_colorpicker-1.0.3/lib/src/palette.dart:1045:47: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter_sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
          width: (Theme.of(context).textTheme.bodyText2?.fontSize ?? 14) * 10,
                                              ^^^^^^^^^`

It seems that the flutter-colorPicker hasn't been updated in a couple of years.

[✓] Flutter (Channel beta, 3.22.0-0.1.pre, on macOS 13.5 22G74 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.86.0)
[✓] Connected device (5 available)
[✓] Network resources

**Comment by quicktime** [comment]
@Strain-solutions You can workaround that by overriding flutter_colorpicker as well. The master branch has fixes for the deprecation of those fields.

```
dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master
  intl: ^0.19.0
```

**Comment by singerdmx** [comment]
oh NVM.  I see https://github.com/singerdmx/flutter-quill/pull/1877/files#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25
