### ISSUE TITLE
Cannot re-apply style after removing it on a new line

### ISSUE THREAD

**Issue by chrallard** [singerdmx/flutter-quill#1814]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.6

### Steps to reproduce

Possibly related to #1805.

1. Insert some text, ie "First"
2. Select "First" and apply a style, ie bold
3. Deselect and go to a new line
4. Insert some text, ie "Second"
5. Select "Second" and remove the style
6. **Try to apply the bold style again, and it won't apply**

### Expected results

The text should have the style applied to it.

### Actual results

The text does not get the style applied to it.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart' as quill;

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: RichTextEditor(),
      ),
    );
  }
}

class RichTextEditor extends StatefulWidget {
  const RichTextEditor({Key? key}) : super(key: key);

  @override
  State<RichTextEditor> createState() => _RichTextEditorState();
}

class _RichTextEditorState extends State<RichTextEditor> {
  final _focusNode = FocusNode();
  final _controller = quill.QuillController(
    document: quill.Document(),
    selection: const TextSelection(baseOffset: 0, extentOffset: 0),
  );

  @override
  void dispose() {
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        quill.QuillToolbar.simple(
          configurations: quill.QuillSimpleToolbarConfigurations(
            controller: _controller,
          ),
        ),
        Expanded(
          child: quill.QuillEditor(
            scrollController: ScrollController(),
            focusNode: _focusNode,
            configurations: quill.QuillEditorConfigurations(
              controller: _controller,
            ),
          ),
        )
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/singerdmx/flutter-quill/assets/43067479/a85cbcea-f662-4abc-a8a9-b9fc609915fa

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by OHeroJ** [comment]
+1

**Comment by AtlasAutocode** [comment]
Try 9.3.7 which fixed some issues with style selection.

**Comment by chrallard** [comment]
> Try 9.3.7 which fixed some issues with style selection.

Looks to be resolved 👍
