### ISSUE TITLE
Azerbaijani language and image pick for windows 

### ISSUE THREAD

**Issue by rradjab** [singerdmx/flutter-quill#1820]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

Can you add Azerbaijani (will glad to help with translation) and can you fix the bug with adding image in windows.
because here 2024-04-14T18:49:05.332779.jpg   filename cant contains ":" in  windows (  final dateTimeString =
          DateTime.now().toIso8601String();
Thank you!

### Proposal

![image](https://github.com/singerdmx/flutter-quill/assets/37322862/73073b4b-851c-4114-a855-3c427ddcd861)

**Comment by CatHood0** [comment]
Does this issue still persists? If it does, reopen this.
