### ISSUE TITLE
How should I customize image rendering?

### ISSUE THREAD

**Issue by Vacanas** [singerdmx/flutter-quill#1832]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

When previewing content in the editor, I would like to wrap images using GestureDetector and Hero widgets to implement a picture preview functionality. How can this be achieved, considering I am currently using the latest version of flutter_quill and within QuillEditorImageEmbedConfigurations, only imageProviderBuilder is available, which does not allow returning a Widget?

**Comment by CatHood0** [comment]
The unique way to make this is copying the implementation of the image embed from `flutter_quill_extension` and modify it to your preferences. By now we have no plans to change the current implementation or a wrapper. If you have any clue, you can comment it.
