### ISSUE TITLE
Placeholder String doesn't take control characters in string.

### ISSUE THREAD

**Issue by SMH-Lily** [singerdmx/flutter-quill#1839]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.4

### Steps to reproduce

 placeholder: '''Here are a few ideas:

• Daily Goals
• Client Insights...

 Make the most of it!''',
 
or: 
placeholder: 'Here are a few ideas:\n\n• Daily Goals\n• Client Insights...\n\nMake the most of it!',

### Expected results

![image](https://github.com/singerdmx/flutter-quill/assets/56062878/8665e8e5-768d-47fa-b87e-a3510eb281b9)

### Actual results

![image](https://github.com/singerdmx/flutter-quill/assets/56062878/30d16b41-a225-4e5e-b963-33c1053440ca)

### Code sample

<details><summary>Code sample</summary>

```dart
Column(
                          children: [
                            Expanded(
                              child: QuillEditor.basic(
                                configurations: QuillEditorConfigurations(
                                  controller: _controller,
                                  readOnly: false,
                                  placeholder: '''Here are a few ideas: 
                                      • Daily Goals
                                      • Client Insights...
                                      Make the most of it!''',
                                  customStyles: DefaultStyles(
                                      placeHolder: DefaultListBlockStyle(
                                          TextStyle(
                                              fontSize: 16,
                                              color:
                                                  Colors.grey.withOpacity(.7)),
                                          const VerticalSpacing(1, 1),
                                          const VerticalSpacing(1, 1),
                                          null,
                                          null)),
                                  sharedConfigurations:
                                      const QuillSharedConfigurations(
                                          locale: Locale('en')),
                                ),
                              ),
                            ),
                            QuillToolbar.simple(
                              configurations: QuillSimpleToolbarConfigurations(
                                controller: _controller,
                                sharedConfigurations:
                                    const QuillSharedConfigurations(
                                  locale: Locale('en'),
                                ),
                              ),
                            ),
                          ],
                        )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
Your problem is due to \n. When placed intrinsically in the string, the string will add or print new lines (whatever we want, but causing problems) as it should. But you need to pass a string like:

r"Here are some ideas:\n\n• Daily goals\n• Client insights...\n\nMake the most of it!'"

EITHER

"Here are some ideas:\\n\\n• Daily goals\\n• Client insights...\\n\\nMake the most of it!'"

With these ropes you can solve this problem. This happens because the delta needs to have only \n as characters, in the string instead of intrinsic newlines.
