### ISSUE TITLE
oopsy buggy

### ISSUE THREAD

**Issue by aliabuthahir** [singerdmx/flutter-quill#184]
Launching lib\main.dart on Chrome in debug mode...
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.1/lib/widgets/raw_editor.dart:97:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.userUpdateTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^

../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.1/lib/widgets/raw_editor.dart:1036:8: Error: The method 'RawEditorState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
  void hideToolbar() {
       ^
../../flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);
       ^

Failed to compile application.
Exited (sigterm)

**Comment by matuella** [comment]
Hello @aliabuthahir, please take a look at the issue #161
