### ISSUE TITLE
 QuillEditorConfigurations: Error: No named parameter with the name 'readOnly'

### ISSUE THREAD

**Issue by maxfornacon** [singerdmx/flutter-quill#1845]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.10

### Steps to reproduce

Upgrade to version 9.3.10 from 9.3.9

### Expected results

Since no breaking change is mentioned in changelog I wouldn't expect anything to break.

### Actual results

It throws an error `Error: No named parameter with the name 'readOnly'`.

### Code sample

<details><summary>Code sample</summary>

```dart
QuillEditorConfigurations(
   controller: _controller,
    readOnly: false,
    sharedConfigurations: const QuillSharedConfigurations(
      locale: Locale('de'),
     ),
),
```

</details>

**Comment by kairan77** [comment]
the setting moved from configuration to controller, now you can set your readonly state in the controller

**Comment by MagnoDaza** [comment]
> the setting moved from configuration to controller, now you can set your readonly state in the controller

can you show an example code, please

**Comment by AtlasAutocode** [comment]
Code is shown in the example application
quill_screen.dart Line 62:
    _controller.readOnly = _isReadOnly;

Originally was set in QuillEditorConfigurations( readOnly: _isReadOnly  (quill_screen.dart line 150-ish)

**Comment by maxfornacon** [comment]
> Code is shown in the example application

The readme should be updated too.

Changes like this should be announced by being marked as deprecated and should be mentioned in the changelog.

**Comment by amorenew** [comment]
You don’t need to do anything as the default is false now in the controller
<img width="251" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/2842459/90fdccd9-dfa6-46b4-94cc-d0a8796edce3">
