### ISSUE TITLE
Powers issue

### ISSUE THREAD

**Issue by Prashanthkumar1998** [singerdmx/flutter-quill#1846]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

1

### Steps to reproduce

on click x powers and entering values power is not displaying as excepted.

### Expected results

x²

### Actual results

x2

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
ki

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
ii

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
;lii

**Comment by AtlasAutocode** [comment]
I have found code commented out in the 'example' application to be helpful in these cases:
File = my_quill_toolbar.dart
Under section:  configurations: QuillSimpleToolbarConfigurations(
Uncomment:  
            // buttonOptions: QuillSimpleToolbarButtonOptions(
            //   base: QuillToolbarBaseButtonOptions(
            //   afterButtonPressed: focusNode.requestFocus,

This forces the focus to return to the editor when you click a toolbar button.

Your code should look like:
        return QuillToolbar.simple(
          configurations: QuillSimpleToolbarConfigurations(
             buttonOptions: QuillSimpleToolbarButtonOptions(
               base: QuillToolbarBaseButtonOptions(
               afterButtonPressed: focusNode.requestFocus,
              )))),

**Comment by singerdmx** [comment]
I think this is resolved in latest release. Feel free to reopen if the issue still exists.
