### ISSUE TITLE
The toolbar fails when multiple characters are entered in Chinese calligraphy

### ISSUE THREAD

**Issue by lz5577** [singerdmx/flutter-quill#1850]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.10

### Steps to reproduce

1,  Run the Flutter Quill example
2, The input method is switched to Chinese mode
3,  Toolbar selects bold mode
4, Input more than 2 Chinese characters at a time

### Expected results

The input is bold text

### Actual results

The input is normal text, and the bold check in the toolbar is reset to unchecked

### Code sample

Flutter-quill  example

### Screenshots or Video

Chinese input method, when more than 2 characters are entered at a time, the bold state will be reset to the unselected state.

https://github.com/singerdmx/flutter-quill/assets/22974077/b8c59209-549e-419a-8b7b-13da3a76505d

QuillController line 276
![WX20240507-102225](https://github.com/singerdmx/flutter-quill/assets/22974077/b4fb7e17-4eae-4074-89e2-51c767326741)

**Comment by crasowas** [comment]
This issue has been fixed in #1890.
