### ISSUE TITLE
Quill editor overflows ConstrainedBox

### ISSUE THREAD

**Issue by 781flyingdutchman** [singerdmx/flutter-quill#1851]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.5

### Steps to reproduce

I use the following widget to render the editor contents within a constrained box, within a Card. The Card shows that the contrainedBox is working: it grows with the contents up to the desired 300 height. The text from the editor however somehow overflows the sizedBox (to the bottom) and extends to the full length of the available text, well beyond the 300.

```
Card(child:
ConstrainedBox(
        constraints: const BoxConstraints(minHeight: 0, maxHeight: 300),
        child: QuillEditor.basic(
        focusNode: focusNode,
        scrollController: scrollController,
        configurations: QuillEditorConfigurations(
          scrollable: false,
          expands: false,
          controller: controller,
          sharedConfigurations:
              QuillSharedConfigurations(locale: Localizations.localeOf(context)),
        ),
      )
)
```

### Expected results

Expect the editor to stay within the parent ConstrainedBox

### Actual results

Editor overflows the ContrainedBox (and Card)

### Code sample

```dart
Card(child:
ConstrainedBox(
        constraints: const BoxConstraints(minHeight: 0, maxHeight: 300),
        child: QuillEditor.basic(
        focusNode: focusNode,
        scrollController: scrollController,
        configurations: QuillEditorConfigurations(
          scrollable: false,
          expands: false,
          controller: controller,
          sharedConfigurations:
              QuillSharedConfigurations(locale: Localizations.localeOf(context)),
        ),
      )
)
```

**Comment by hoangsang17th** [comment]
You can using `maxHeigh, minHeight` in QuillEditor alternative for `ConstrainedBox`
![image](https://github.com/singerdmx/flutter-quill/assets/56586682/7a100d31-4f98-4019-aa2e-74b4cf9c655b)

**Comment by 781flyingdutchman** [comment]
Thanks - it affects the height communicated to the parent (a `Card` widget in my case, which shrinks to the size set by `maxHeight`) but the actual text is still visible below the card, so this does not solve the problem.  See screenshot
![Screenshot from 2024-05-17 01-02-23](https://github.com/singerdmx/flutter-quill/assets/24858911/64633dea-d6a1-424b-b135-16bec208802a)

**Comment by hoangsang17th** [comment]
That my mistake, with the new issue, u can wrap`Card` by a `ClipRRect`

**Comment by hoangsang17th** [comment]
If still have issues, please comment with a mention of me
