### ISSUE TITLE
Converting Markdown to Quill document (Delta) format

### ISSUE THREAD

**Issue by 781flyingdutchman** [singerdmx/flutter-quill#1852]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I am trying to convert basic MarkDown to a formatted Quill document, but the approach that I believe is right only parses the in-line markdown (like *bold* and _italics_) and not markdown like headers and block markdown like an ordered list.  What am I doing wrong?

Code snippet:
```dart
final markdownDocument = md.Document(inlineSyntaxes: [ // not sure I need to specify these, but I did
            md.EmphasisSyntax.asterisk(),
            md.EmphasisSyntax.underscore()
          ], blockSyntaxes: const [ // similarly, not sure I need to specify these as they are pretty standard
            md.HeaderSyntax(),
            md.UnorderedListSyntax(),
            md.OrderedListSyntax()
          ]);
          final quillDocDelta =
              MarkdownToDelta(markdownDocument: markdownDocument)
                  .convert(markDownString); // markDownString is a typical markdown formatted document
          result = jsonEncode(quillDocDelta.toJson());
```

The `result` can be used to create a Quill document, but as described above, only some of the formatting makes it into the document.

**Comment by singerdmx** [comment]
Thanks @hoangsang17th . It looks like your question is answered.
