### ISSUE TITLE
read only not found in QuillEditorConfigurations

### ISSUE THREAD

**Issue by the-best-is-best** [singerdmx/flutter-quill#1858]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.11

### Steps to reproduce

nun

### Expected results

nun

### Actual results

nun

### Code sample

QuillEditor.basic(
              configurations: QuillEditorConfigurations(
                controller: widget.controller ?? QuillController.basic(),

                readOnly: !widget.edit,
               
                scrollable: true,
                autoFocus: false,
                showCursor: widget.edit,
                expands: false,
                // maxHeight: MediaQuery.of(context).size.height * 0.25,
                padding: EdgeInsets.zero,
                sharedConfigurations: const QuillSharedConfigurations(
                  locale: Locale('ar'),
                ),
              ),
            )

**Comment by hoangsang17th** [comment]
Update a litte in your code:

```dart
QuillEditor.basic(
   configurations: QuillEditorConfigurations(
      controller: widget.controller ?? QuillController(
         readOnly: !widget.edit, // <= Migrate to this
      ),
      scrollable: true,
      autoFocus: false,
      showCursor: widget.edit,
      expands: false,
      // maxHeight: MediaQuery.of(context).size.height * 0.25,
      padding: EdgeInsets.zero,
      sharedConfigurations: const QuillSharedConfigurations(
      locale: Locale('ar'),
   ),
),

**Comment by apoleo88** [comment]
It made more sense before, why the (breaking) change?

**Comment by hoangsang17th** [comment]
> It made more sense before, why the (breaking) change?

I don't know :))

**Comment by felix-mittermeier** [comment]
This is indeed a breaking change and it's not even mentioned inside the release notes :D

**Comment by hoangsang17th** [comment]
@the-best-is-best Please mark done for this issue

**Comment by buonzz** [comment]
even the provided example doesn't work...

```
QuillController(
         readOnly: true
      )
```

it says **The named parameter 'document' is required, but there's no corresponding argument.**

**Comment by EchoEllet** [comment]
This breaking was made by #1843, and it we shouldn't have introduced this breaking change. There is almost no reason.

```dart
_controller.readOnly = true;
```
