### ISSUE TITLE
Cut-copy-paste menu overlaps text and/or toolbar

### ISSUE THREAD

**Issue by Alspb** [singerdmx/flutter-quill#1861]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

master

### Steps to reproduce

Select text on the top line.

### Expected results

The cut-copy-paste menu is moved a bit not to overlap the selection.
Ideally the menu is draggable (as it is the case for the default text selection menu on Android).

### Actual results

The cut-copy-paste menu appeared overlaps the toolbar on mobile platforms and overlaps the selected text on desktop platforms.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

**Mobile:**

![Bubble overrides text issue - Mobile](https://github.com/singerdmx/flutter-quill/assets/73047043/42e16450-f82b-480f-8c17-4b8e9d6092b0)

**Desktop:**

![Bubble overrides text issue - Desktop](https://github.com/singerdmx/flutter-quill/assets/73047043/f3953096-2192-4ae0-82fa-6b11fa11a8aa)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment]
Thanks for the fix
