### ISSUE TITLE
Swype typing style bug (Android)

### ISSUE THREAD

**Issue by Alspb** [singerdmx/flutter-quill#1863]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

master

### Steps to reproduce

Scenario 1:
1. Put the cursor right after a bold text.
2. Switch bold off (via toolbar).
3. Swipe type some word.

Scenario 2:
1. Put the cursor right after a non-bold text.
2. Switch bold on (via toolbar).
3. Swipe type some word.

### Expected results

Scenario 1: the word typed shouldn't be bold.

Scenario 2: the word typed should be bold.

### Actual results

Scenario 1: the word typed turns out to be bold.

Scenario 2: the word typed turns out to be non-bold.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![Swype typing style bug](https://github.com/singerdmx/flutter-quill/assets/73047043/b5edc3c2-0e52-42cc-aa63-9002fc24e9e9)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ellet0** [comment]
> I found that the issue appeared in version 9.0.0-dev.
> @ellet0 , could you please check what caused the problem?

I will see what I can do as soon as I can.
