### ISSUE TITLE
When inputting more than 2 characters at a time, the toolbar style change will be invalid.

### ISSUE THREAD

**Issue by Buzhifanji** [singerdmx/flutter-quill#1864]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.11

### Steps to reproduce

1. Enter any text you want, as long as there are candidates in the input method that are more than 2 characters long.
2. Toolbar switches font size or color。
3. Click on the candidate content of more than 2 characters in the input method
4. The style selected in the second step does not take effect

### Expected results

No matter how much text is entered, the toolbar switching style will take effect

### Actual results

When more than two characters are entered at one time, the switching style will not take effect.

### Code sample

[After a day of hard work, I have found the code location that caused the bug.](https://github.com/singerdmx/flutter-quill/blob/9d84ef65439c93b4ee90ad1e8e5eddae587ad3d7/lib/src/widgets/quill/quill_controller.dart#L276)

This judgment condition will result in that when the user inputs more than 2 words, the toggledStyle cannot be obtained.

You should distinguish between user pasting and candidate input. The pasted content has styles, while the candidate content in the input method has no style.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by BowieY** [comment]
I have the same problem, is there any temporary solution?
