### ISSUE TITLE
Can we add inline comment in Quill editor?

### ISSUE THREAD

**Issue by Instadex** [singerdmx/flutter-quill#1869]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi,

Is there a way that we can add inline comments in text editor similar to the feature that we have in notion editor.
Here's the screenshot:
![Image (5)](https://github.com/singerdmx/flutter-quill/assets/20140833/b0839a3d-20a7-45e8-97fc-b29f83958025)
After commenting the text gets highlighted and on clicking on comment it can be seen in next screen.

It would be very helpful as I have been trying different approach on this from past 1 week. Thanks!

**Comment by CatHood0** [comment]
You need to make your own custom attribute implementation to make this,

The attribute could be like:

```dart
class CommentAttr extends Attribute<Map<String, dynamic>?> {
  static const String commentKey = 'comment';
  static const AttributeScope _scope = AttributeScope.inline;
  CommentAttr(Map<String, dynamic>? value) : super(commentKey, _scope, value);
}
```

And, use `customStyleBuilder` to recognize this attribute, and apply your text styles. If you want to add also gestures where the attribute is applied, use `customRecognizerBuilder`
