### ISSUE TITLE
Styling bug in the CI automated CHANGELOG files generation 

### ISSUE THREAD

**Issue by ellet0** [singerdmx/flutter-quill#1880]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.16

### Steps to reproduce

If you create a GitHub release and use some styling like `this` (inline code formatting), in the release notes it appears correctly:
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/639ff379-39e4-45fc-87b4-6365c407f743)

But if you take a look at any of the `CHANGELOG.md` files:
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/51599c38-ddb5-456b-ad55-cc126d257069)

You will notice the `lints` word is not there and is replaced with empty space

### Expected results

The exact same text and styling for the release notes body should be used in the `CHANGELOG.md` for each release

### Actual results

Empty space instead of `lints`

### Code sample

This is not a bug related to the actual package.

### Screenshots or Video

The issue is probably not with the `CHANGELOG_DATA.json` or how the script handles the `CHANGELOG.md` generation, it could be because how we pass the data to the script arguments
![image](https://github.com/singerdmx/flutter-quill/assets/73608287/87d6a4ac-2a5b-416b-b3cd-fdb11518fe9e)

**Comment by ellet0** [comment]
The issue is not from the GitHub rest API side, the data is returned correctly:

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/f01ef6cd-8e02-46be-8188-96d69283038c)

**Comment by ellet0** [comment]
The bug is here:

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/47ccb815-02b7-41d8-9876-4a9bd7ab57f9)

As expected, the problem with how we pass the data to the script and it's related to the code in the `publish.yml`

**Comment by ellet0** [comment]
Fixed but there might be other bugs.

I tested it with the following release notes:

```markdown

- This version is released for **testing** the `GitHub publish workflow`, there are other solutions to test the workflows but we had reasons to do it this way, please ignore this version.

"Test", "World", `Hello`, [Link](https://github.com/singerdmx/flutter-quill/compare/v9.3.16...v9.3.16-experimental)

**Full Changelog**: https://github.com/singerdmx/flutter-quill/compare/v9.3.16...v9.3.16-experimental

```

and it works as expected.

**Comment by ayyoub-coder** [comment]
https://github.com/superlistapp/super_native_extensions/issues/362
