### ISSUE TITLE
CI automated  failed build caused by super_clipboard

### ISSUE THREAD

**Issue by ayyoub-coder** [singerdmx/flutter-quill#1882]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

upgrade super_clipboard version from 0.8.13 to 0.8.14

### Proposal

super_clipboard version from 0.8.13 to 0.8.14  https://github.com/superlistapp/super_native_extensions/issues/362

**Comment by berhili098** [comment]
yup i think this would fix the problem i am facing

**Comment by ellet0** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
> 
> ### Use case
> upgrade super_clipboard version from 0.8.13 to 0.8.14
> 
> ### Proposal
> super_clipboard version from 0.8.13 to 0.8.14 [superlistapp/super_native_extensions#362](https://github.com/superlistapp/super_native_extensions/issues/362)

Hi, I'm not sure what you mean by this. Do you mean the CI of the Flutter Quill repo? because it's succeeding without any issues

**Comment by ayyoub-coder** [comment]
Sorry for the confusion. I meant to ask if you could please upgrade the version of super_clipboard to 0.18.5   https://github.com/superlistapp/super_native_extensions/issues/362

**Comment by ellet0** [comment]
Published in [25183393942](https://github.com/singerdmx/flutter-quill/actions/runs/9160532900/job/25183393942), you can now use [9.3.17](https://github.com/singerdmx/flutter-quill/releases/tag/v9.3.17)
