### ISSUE TITLE
[Mobile] toolbarIconSize value ignored by certain toolbar buttons

### ISSUE THREAD

**Issue by jongkb** [singerdmx/flutter-quill#189]
When setting **toolbarIconSize** to a value other than the default value in **QuillToolbar.basic()**, certain buttons like bold, italic, underline, and a few others, do not assume the specified size.

Example:
`
 QuillToolbar.basic(
          controller: _controller,
          toolbarIconSize: 48.0
        )
`

Thanks.

**Comment by axgalache** [comment]
+1
I'm having this problem too

**Comment by pavel-birdy** [comment]
yeah ☹️
<img width="423" alt="Screenshot 2021-05-03 at 05 33 22" src="https://user-images.githubusercontent.com/53362329/116832107-15f7ad80-abd1-11eb-8486-6689e57630f1.png">
