### ISSUE TITLE
Overflow ERROR in flutter_quill toolbar menus

### ISSUE THREAD

**Issue by Abner-Jaasiel** [singerdmx/flutter-quill#1891]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

The default button menus of QuillSimpleToolbar appear below the keyboard. This is strange since it didn't happen in previous versions.

    return Column(
      children: [
        QuillEditorWidget(
          padding: padding,
          newNote: newNote,
          quillController: _quillController,
        ),
        QuillSimpleToolbar(
          configurations: QuillSimpleToolbarConfigurations(
            controller: _quillController,
            toolbarSectionSpacing: 10.0,
          ),
        ),

    
      ],
    );

[enter image description here](https://i.sstatic.net/LhS3VEDd.jpg)

[enter image description here](https://i.sstatic.net/LhZ9oukd.jpg)

In previous versions, I used the QuillToolbar widget, which lost some parameters, and I didn't understand its new logic very well. So, I tried to find other options like QuillToolbar.simple, but I also missed some parameters until I managed to find QuillSimpleToolbar, which had the same parameters. I only had to copy and paste my code. Then I encountered the mentioned error, which I'm sure also happened with the previous widgets. I tried various ways but couldn't achieve anything. I wonder... maybe flutter_quill implemented some parameter to overlay the internal menus of the toolbar, and I can't find it...

Some more changes: Due to updates, flutter_quill removed the QuillProvider widget, which might have something to do with it or not... in this case, I have removed it and only left a column with the editor and the toolbar.

before:
  

    return QuillProvider(
      configurations: QuillConfigurations(
        controller: _quillController,
        sharedConfigurations: QuillSharedConfigurations(
          locale: Locale(S.current.code_locate),
        ),
      ),
      child: Column(
        children: [
          QuillEditorWidget(
            padding: padding,
            newNote: newNote,
            quillController: _quillController,
          ),
          QuillToolbarWidget(
            scrollController: scrollController,
            quillController: _quillController,
            noteId: noteId,
            newNote: newNote,
          ),
        ],
      ),
    );

now: 

    return Column(
      children: [
        QuillEditorWidget(
          padding: padding,
          newNote: newNote,
          quillController: _quillController,
        ),
        QuillSimpleToolbar(
          configurations: QuillSimpleToolbarConfigurations(
            controller: _quillController,
            toolbarSectionSpacing: 10.0,
          ),
        ),

    
      ],
    );

These are some of the changes I made in the new version of flutter_quill.

Also with the aim of finding an alternative solution, I placed another "gesturedetector" widget on top of the toolbar widget. The gesture was not detected in onTap(){FocusScope.of(context).unfocus();} in the items, I guess because the widget stops working when the onPress already exists on it

packages:
[https://pub.dev/packages/flutter_quill][1]

  [1]: https://pub.dev/packages/flutter_quill

**Comment by salba360496** [comment]
wrap the QuillEditorWidget in expanded
