### ISSUE TITLE
../../../.pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes'). Future putImageBytes(Uint8List bytes,

### ISSUE THREAD

**Issue by hina06botify** [singerdmx/flutter-quill#1896]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

../../../.pub-cache/hosted/pub.dev/gal_linux-0.0.1/lib/src/gal_linux.dart:25:16: Error: The method 'GalPluginLinux.putImageBytes' has fewer named arguments than those of overridden method 'GalPlatform.putImageBytes'.
  Future<void> putImageBytes(Uint8List bytes, {String? album}) =>
               ^
../../../.pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
  Future<void> putImageBytes(Uint8List bytes,
               ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/keval/Documents/development/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1419

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/keval/Documents/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Error: Gradle task assembleDebug failed with exit code 1
how can solve this error  bcoz my project not run after adding this package 
  flutter_quill: ^9.1.1
  flutter_quill_extensions: ^9.1.1

**Comment by ellet0** [comment]
Hi, can you provide more details about the title? how to reproduce, what is the expected and the actual behavior?
What version of Flutter? it's pointing to `gal` plugin

```
../../../.pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
Future putImageBytes(Uint8List bytes,
^
```

But still would like to get more information

**Comment by hina06botify** [comment]
my flutter version is 3.19.3 and I'm trying to put an image in Quill editor but got this error:-
 ../../../.pub-cache/hosted/pub.dev/gal_linux-0.0.1/lib/src/gal_linux.dart:25:16: Error: The method 'GalPluginLinux.putImageBytes' has fewer named arguments than those of overridden method 'GalPlatform.putImageBytes'.
  Future<void> putImageBytes(Uint8List bytes, {String? album}) =>
               ^
../../../.pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
  Future<void> putImageBytes(Uint8List bytes,
               ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/keval/Documents/development/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1419

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/keval/Documents/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by singerdmx** [comment]
Please fix the title

**Comment by EchoEllet** [comment]
Thank you for the report. Should be no longer an issue.
