### ISSUE TITLE
Can't able to build with the new version

### ISSUE THREAD

**Issue by Prajit7** [singerdmx/flutter-quill#1900]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.11

### Steps to reproduce

When used the above version could not build the app.

### Expected results

App should build

### Actual results

App is not building

### Code sample

QuillEditor(
                  focusNode: _focusNode,
                  scrollController: bodyScrollController,
                  configurations: QuillEditorConfigurations(
                    controller: quillController,
                    showCursor: true,
                    textSelectionThemeData: TextSelectionThemeData(
                      selectionColor: Colors.blue.withOpacity(0.2),
                    ),
                    onTapDown: (details, p1) {
                      // subjectFnode.unfocus();

                      _focusNode.hasFocus ? _focusNode.requestFocus() : null;
                      return true;
                    },
                    autoFocus: false,
                    expands: false,
                    padding: const EdgeInsets.all(16),
                    scrollable: true,
                    minHeight: MediaQuery.of(context).size.height - 250,
                    textInputAction: TextInputAction.newline,
                    placeholder: "Add Message",
                    customStyles: const DefaultStyles(
                      placeHolder: DefaultTextBlockStyle(
                        TextStyle(
                          fontSize: 18,
                          color: Colors.grey,
                        ),
                        VerticalSpacing(0, 0),
                        VerticalSpacing(0, 0),
                        BoxDecoration(),
                      ),
                    ),
                  ),
         
                ),

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: HandshakeException: Connection terminated during handshake
SEVERE: --------------------------------------------------------------------------------
SEVERE:
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: HandshakeException: Connection terminated during handshake
SEVERE: --------------------------------------------------------------------------------
SEVERE:
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================
```

</details>

**Comment by ellet0** [comment]
Should be fixed with `9.4.x.` and latest version of `super_clipboard`
