### ISSUE TITLE
How to create a table using flutter_quill: ^9.3.21

### ISSUE THREAD

**Issue by Avinashk1231** [singerdmx/flutter-quill#1901]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I am not able to create the table. Is there any way to customise or add the table.

I trying to do below design, but i am not able to achieve the border, is there any way to do in flutter.

<img width="747" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/147474627/3dfe28fa-263a-4785-8f0f-64cce0b10345">

**Comment by singerdmx** [comment]
I don't think we are supporting table. This should be a feature request, not issue.
