### ISSUE TITLE
Prevent Pasting BlockEmbed.imageType with Ctrl + V on Desktop from Creating a Block

### ISSUE THREAD

**Issue by sandapilarius** [singerdmx/flutter-quill#1905]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

When attempting to paste using Ctrl + V on desktop, I want it to do nothing if it is BlockEmbed.imageType. Therefore, I created an EmbedBuilder as shown below, but it creates a line block. Is there a method that can do absolutely nothing without forcing the return of a Widget?

```
class ImageEmbedBuilder extends EmbedBuilder {
  @override
  String get key => BlockEmbed.imageType;

  @override
  bool get expanded => false;

  @override
  Widget build(
    BuildContext context,
    QuillController controller,
    Embed node,
    bool readOnly,
    bool inline,
    TextStyle textStyle,
  ) {
    return const SizedBox.shrink();
  }
}
```

**Comment by AtlasAutocode** [comment]
I see that no one has responded to this request. 
So, I guess, we need more information to understand what the question is.

For example, you say you are pasting a BlockEmbed.imageType - but this implies you have copied BlockEmbed.imageType in the first place! I don't understand why you copy and then don't want to paste? Can you explain what you are trying to do?

**Comment by CatHood0** [comment]
If he want to avoid pasting for Embed blocks, then he shouldn't use `FlutterQuillExtensions.useSuperClipboardPlugin()`

**Comment by AtlasAutocode** [comment]
Interesting. I know you can copy-paste embeds within the editor, but I didn't know you could copy-paste embeds between apps using the extensions.
We need to know why the OP wants to do this and what they are doing.

**Comment by CatHood0** [comment]
I will close this since we don't have any responde from the OP. If this issue persists, please reopen.
