### ISSUE TITLE
 QuillToolbarToggleStyleButton unable to click when icon is changed by QuillToolbarToggleStyleButtonOptions.childBuilder

### ISSUE THREAD

**Issue by mtiendat** [singerdmx/flutter-quill#1908]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.11

### Steps to reproduce

1. Create QuillToolbar
2. Custom QuillToolbarToggleStyleButton with attribute: Attribute.bold, and change icon by  options: QuillToolbarToggleStyleButtonOptions.childBuilder

### Expected results

able to click QuillToolbarToggleStyleButton even change icon 

### Actual results

unable to click QuillToolbarToggleStyleButton when change icon by childBuilder

### Code sample

```
 QuillToolbar(
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  QuillToolbarToggleStyleButton(
                    controller: _qcontroller,
                    attribute: Attribute.bold,
                    options: QuillToolbarToggleStyleButtonOptions(
                      childBuilder: (options, extraOptions) {
                        return ImagePath.bold.image(
                          color: extraOptions.isToggled
                              ? AppColors.blue
                              : AppColors.textSecondary,
                        );
                      },
                    ),
                  ),
                 
                ],
              ),
            ),
          ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/singerdmx/flutter-quill/assets/73454933/4b2698c1-7dd9-4b43-ad79-19297cc195bb

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
When you use childBuilder, you are responsible for implementing function as well as appearance.

Your example gives a nice appearance, but an Icon/Image is not clickable.
You need to return something like:
>  IconButton(icon: const Icon(Icons.format_bold), onPressed: extraOptions.onPressed,);

Notice the onPressed parameter which enables the built in toggle function.

Future thoughts: you seem to be designing a different color theme for toggle buttons. Would it make sense to implement this as an option in the base QuillToolbarIconButton class?

**Comment by mtiendat** [comment]
@AtlasAutocode I want to custom QuillToolbarToggleStyleButton bold icon by own image use png. And I want it can click with bold function. So I use childBuilder to change icon bold default to image png. is it able? if can, how can I achieve it?

**Comment by AtlasAutocode** [comment]
Do an internet search for 'flutter clickable image'
The first example I got was
> GestureDetector(
onTap: () {}, // Image tapped
child: Image.asset(
'assets/cat.jpg',
fit: BoxFit.cover, // Fixes border issues
width: 110.0,
height: 110.0,),)

onTap could then be: () => extraOptions.onPressed
Replace the child parameter with whatever you want

**Comment by mtiendat** [comment]
@AtlasAutocode thanks for support! it work now!

**Comment by AtlasAutocode** [comment]
Update your InkWell.onTap function to call the onPressed function:
> extraOptions.onPressed **?.call();**

Now everything gets called.
A trick I've learned is to place a breakpoint on the line. When the debugger hits the breakpoint you can verify that the function is not null and you can then use the debugger to 'step-in'. When it doesn't step into the expected function, you know you've forgotten to actually call the function. (I kick myself every time I do this.)

**Comment by S2V** [comment]
@AtlasAutocode, man, you destroy me and save my day )
