### ISSUE TITLE
[Mobile] Clear format does not work on mixed formatted and unformatted text

### ISSUE THREAD

**Issue by jongkb** [singerdmx/flutter-quill#191]
Example - type the below (apply bold to the second word):
Hello **world**

If the text selection spans "**world**" only, clear format works as expected.
When text selection spans the entire "Hello **world**", clear format seems to do nothing. 

For reference on the expected behavior, I've tested out QuillJs for the web and clear format cleared any formatting contained in a selected text of mixed unformatted and formatted text.

Thanks.

**Comment by singerdmx** [comment]
I can repro
Will work on the fix

**Comment by li3317** [comment]
Hello, an update is available in this commit https://github.com/singerdmx/flutter-quill/commit/6751472a55b2cc7d1aade08e253259b44e1ffbe2 . Thank you!
