### ISSUE TITLE
Able to set max length for QuillEditor? 

### ISSUE THREAD

**Issue by mtiendat** [singerdmx/flutter-quill#1910]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Example: I want to limit 10 characters user can input, I tried onReplaceText to return true/false, but I face with a problem that user paste from clipboard of device, onReplaceText not work with this case. 
Video Issue
https://github.com/singerdmx/flutter-quill/assets/73454933/d99b0073-678f-42b9-b7aa-2ad65727def2

```_qcontroller = QuillController(
      selection: const TextSelection.collapsed(offset: 0),
      document: Document(),
      onReplaceText: (index, length, text) =>
         index < maxLength
    );```

**Comment by singerdmx** [comment]
Refer to https://github.com/singerdmx/flutter-quill/discussions/860
