### ISSUE TITLE
Read only not effective

### ISSUE THREAD

**Issue by herowws** [singerdmx/flutter-quill#1918]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

<img width="1268" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/41428542/c5ff8eaa-5ff8-43ea-9f45-2683eb312c28">

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (5 available)
[✓] Network resources
  flutter_quill: ^9.4.0
  flutter_quill_extensions: ^9.4.0

**Comment by salba360496** [comment]
readOnly is moved to controller properties try to set it in init state like 
@override
  void initState() {
    super.initState();
   controller.readOnly  = true;
  }

**Comment by singerdmx** [comment]
@herowws this can be closed?
