### ISSUE TITLE
The named parameter 'embedButtons' isn't defined.

### ISSUE THREAD

**Issue by SlickSlime** [singerdmx/flutter-quill#1920]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

The documentation shows the following code snippet but it is not working:
```
QuillToolbar(
  configurations: QuillToolbarConfigurations(
    embedButtons: FlutterQuillEmbeds.toolbarButtons(),
  ),
),
```

I am using `flutter_quill: 9.4.1` & `flutter_quill_extensions: 9.4.1` but there is no parameter `embedButtons` for the `QuillToolbarConfigurations` object.

**Comment by salba360496** [comment]
try to use 
 configurations: QuillSimpleToolbarConfigurations()

**Comment by SlickSlime** [comment]
@salba360496 Yes, that works. Maybe we should consider updating the README?

**Comment by ellet0** [comment]
It seems that the `README.md` is outdated, thank you for pointing out this, I will update it.
