### ISSUE TITLE
problems when using languages ​​that use ltr instead of rtl

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#1928]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.4.2

### Steps to reproduce

problem with languages ​​that use ltr instead of rtl,   DirectionAttribute('ltr');
When I touch the enumerated list or checkbox option, even when using ltr in languages ​​like Hebrew, the checkboxes and enumerated lists do not change, they remain in the position as if using rtl

### Expected results

checkbox and the list number go to the beginning of the line on the right side

### Actual results

checkbox and list number are at the beginning of the line on the left side

### Code sample

default quill

**Comment by AtlasAutocode** [comment]
In my exploring the code, I have found that lists are implemented by hard coding the checkbox (or list number) into the left edge of the display irrespective of ltr or rtl.
You can see this if you change the text alignment to center or right - the checkbox stays on the left edge with the text floating in the center - which looks weird!
Fixing that is not trivial.
More complex is the issue you raise of Hebrew with LTR but checkboxes on the right which would need some kind of language lookup.
I think the whole concept of lists and alignments needs review.
Anyone have any comments or solutions?

**Comment by CatHood0** [comment]
I see the direction attribute but just work by one way. I you want to force the content be `RTL` then the `Attribute` must be: `DirectionAttribute('ltr')`, but, i just want to content just be on the `LTR`, then just need to pass `null` (by default this is the value to force `LTR`)

You can see this on Attribute file:

```dart
// "attributes":{"direction":"rtl"}
static const Attribute<String?> rtl = DirectionAttribute('rtl');
```

And this is the default attribute:

```dart
static const DirectionAttribute direction = DirectionAttribute(null);
```

**Comment by CatHood0** [comment]
You also can see this on https://github.com/singerdmx/flutter-quill/blob/6ecd377b26649a18d26d6b8fa77e5cf66d68f0d0/lib/src/editor/widgets/text/text_block.dart#L187

This get the `Direction` from the text using this method from [delta_diff](https://github.com/singerdmx/flutter-quill/blob/master/lib/src/delta/delta_diff.dart#L92):

https://github.com/singerdmx/flutter-quill/blob/6ecd377b26649a18d26d6b8fa77e5cf66d68f0d0/lib/src/delta/delta_diff.dart#L92

**Comment by AtlasAutocode** [comment]
We need an expert in right-to-left to get involved with a review of the whole concept.

 @CatHood0 you can look at EditableTextLine in text_line.dart which contains a widget called 'leading'.
Lists have the bullet or number hard coded to appear on the left irrespective of ltr or rtl. - see enum TextLineSlot.

**Comment by CatHood0** [comment]
> We need an expert in right-to-left to get involved with a review of the whole concept.

I think the same too.

> @CatHood0 you can look at EditableTextLine in text_line.dart which contains a widget called 'leading'.

I'll try to fix it. 

Need i use a language that use LTR direction or RTL? I could not undertanting all about the issue of the OP.

**Comment by CatHood0** [comment]
i think this could be the part that is displaying wrong direction:

```dart
  @override
  void paint(PaintingContext context, Offset offset) {
    if (_leading != null) {
      if (textDirection == TextDirection.ltr) {
        final parentData = _leading!.parentData as BoxParentData;
        final effectiveOffset = offset + parentData.offset;
        context.paintChild(_leading!, effectiveOffset);
      } else {
        final parentData = _leading!.parentData as BoxParentData;
        final effectiveOffset = offset + parentData.offset;
        context.paintChild(
          _leading!,
          Offset(
            size.width - _leading!.size.width,
            effectiveOffset.dy,
          ),
        );
      }
    }

```

**Comment by CatHood0** [comment]
Most of the widgets has this issue: 
![Screenshot_۲۰۲۴۰۷۲۳-۲۰۵۲۳۳](https://github.com/user-attachments/assets/bbfe72ec-89bb-42b0-a1f1-1c3290f5c56a)

**Comment by CatHood0** [comment]
This will be complex

**Comment by CatHood0** [comment]
@AtlasAutocode what do you think about this:

![Screenshot_۲۰۲۴۰۷۲۳-۲۱۰۸۱۷](https://github.com/user-attachments/assets/17dbb047-3be1-4093-8a2a-3bb9a82c321e)

**Comment by CatHood0** [comment]
@AtlasAutocode what do you think about this result:

![Screenshot_۲۰۲۴۰۷۲۳-۲۱۱۷۳۸](https://github.com/user-attachments/assets/dc76d07d-dfe6-4b49-8c59-03a513060d47)

**Comment by CatHood0** [comment]
> This will be complex

It was more easy that i thinked

**Comment by EchoEllet** [comment]
By default, the editor will use the same local as the one in the `WidgetsApp` or `MaterialApp`.

Which will use the same direction as the local, the local can be overridden, I'm not sure why this fix manually check the language or why currently we have a bug.

**Comment by CatHood0** [comment]
>  I'm not sure why this fix manually check the language 

I didn't have idea about `Directionality.of(context)` how works. I already make a fix to avoid manually checking the language

> why currently we have a bug

This is because on `raw_editor_state` file, we use the Directionality from `getDirectionOfNode` instead validate the current system direction and the direction attribute from the node.
