### ISSUE TITLE
How to only show QuillToolbar when is editing?

### ISSUE THREAD

**Issue by toknT** [singerdmx/flutter-quill#1932]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I want show toolbar after user tap the html so do it like this , but it not work.

```dart
  bool _showToolBar = false;
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 300,
      clipBehavior: Clip.antiAlias,
      padding: const EdgeInsets.symmetric(vertical: 3),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(7),
        border: Border.all(
          color: Colors.grey,
          width: 1,
        ),
      ),
      child: Column(
        children: [
          _showToolBar
              ? QuillToolbar.simple(
                  configurations: QuillSimpleToolbarConfigurations(
                    embedButtons: FlutterQuillEmbeds.toolbarButtons(),
                    controller: _controller,
                  ),
                )
              : const SizedBox.shrink(),
          Expanded(
            child: GestureDetector(
              onTap: () {
                setState(() {
                  _showToolBar = true;
                });
              },
              child: QuillEditor.basic(
                configurations: QuillEditorConfigurations(
                  controller: _controller,
                  embedBuilders: kIsWeb
                      ? FlutterQuillEmbeds.editorWebBuilders()
                      : FlutterQuillEmbeds.editorBuilders(),
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
```

**Comment by salba360496** [comment]
try this
 final ValueNotifier<bool> _showToolBar = ValueNotifier(false);
  final QuillController _controller = QuillController.basic();
  late final FocusNode _fcNode ;

  @override
  void initState() {
    _fcNode = FocusNode()..addListener(() {
      setState(() {
        _showToolBar.value = _fcNode.hasFocus ? true :false;
      });
    });
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        height: 300,
        clipBehavior: Clip.antiAlias,
        padding: const EdgeInsets.symmetric(vertical: 3),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(7),
          border: Border.all(
            color: Colors.grey,
            width: 1,
          ),
        ),
        child: Column(
          children: [
          ValueListenableBuilder<bool>(
          valueListenable: _showToolBar,
          builder: (context, value, child) =>_showToolBar.value ==true
                ? QuillToolbar.simple(
              configurations: QuillSimpleToolbarConfigurations(
                embedButtons: FlutterQuillEmbeds.toolbarButtons(),
                controller: _controller,
              ),
            )
                : const SizedBox.shrink()),
            Expanded(
              child: QuillEditor.basic(
                focusNode: _fcNode,
                configurations: QuillEditorConfigurations(
                  autoFocus: false,
                  controller: _controller,
                  embedBuilders: kIsWeb
                      ? FlutterQuillEmbeds.editorWebBuilders()
                      : FlutterQuillEmbeds.editorBuilders(),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

**Comment by toknT** [comment]
@salba360496 Use `focuseNode` and `addListener` solved , thanks.
