### ISSUE TITLE
How to change the mouse hover cursor for ```readOnly``` mode?

### ISSUE THREAD

**Issue by geronimol** [singerdmx/flutter-quill#1935]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Tried this on Web and MacOS using flutter_quill 9.4.4, but didn't work for me.

Am I doing something wrong?

```dart
_controller = QuillController(
        document: delta,
        selection: const TextSelection.collapsed(offset: 0),
        readOnly: true,
      );
```

```dart
return QuillEditor.basic(
      configurations: QuillEditorConfigurations(
        controller: _controller,
        scrollable: false,
        enableInteractiveSelection: false,
        readOnlyMouseCursor: SystemMouseCursors.grab,
      ),
    );
 ```

**Comment by CatHood0** [comment]
If you want to change from the `controller`then just try:

```dart
_controller.readOnly = true; //or false if you need it
```

This will change `readOnly` mode for your editor

**Comment by geronimol** [comment]
> If you want to change from the `controller`then just try:
> 
> ```dart
> _controller.readOnly = true; //or false if you need it
> ```
> 
> This will change `readOnly` mode for your editor

I am asking how to change the mouse cursor for when you hover the text in readOnly mode. Please check the above code

**Comment by geronimol** [comment]
Reported #1970
