### ISSUE TITLE
Converting from HTML not rendering the videos and the iframes

### ISSUE THREAD

**Issue by hagiosolat** [singerdmx/flutter-quill#1945]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How do I go about this, I want to convert from HTML, the text and the Images are working but the videos and the iframes were not showing at all.

**Comment by CatHood0** [comment]
Videos need to be implemented, but, iframes implementation is so far to be implemented. I think that it could be added if we just add a parser of html to flutter widgets as a custom block embed.

@ellet0 what do you think?

**Comment by ellet0** [comment]
> Videos need to be implemented, but, iframes implementation is so far to be implemented. I think that it could be added if we just add a parser of html to flutter widgets as a custom block embed.
> 
> @ellet0 what do you think?

Missed the notification for some reason. Generally, I prefer to convert from HTML to Delta directly.

**Comment by CatHood0** [comment]
> I prefer to convert from HTML to Delta directly.

That's exactly why I took the time to create the `flutter_quill_delta_from_html` package

**Comment by ellet0** [comment]
> > I prefer to convert from HTML to Delta directly.
> 
> That's exactly why I took the time to create the `flutter_quill_delta_from_html` package

Thank you for your time and efforts.
