### ISSUE TITLE
Embed Table Question

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#1948]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I am trying to implement embed tables, however, there is something that I cannot understand (since I don't understand all of the base code). How could I add text blocks that use the original Flutter Quill styles? I mean adding blocks that are editable (just like Headers or Paragraphs). I still don't know what part of the code is responsible for this or if I should create it manually.

I can perfectly create the table block but I would have to eliminate the main feature why this package exists: The styles, and i don't want it

**Comment by CatHood0** [comment]
@AtlasAutocode can you take a look at this?

**Comment by AtlasAutocode** [comment]
How are you creating your text blocks?
How do you invoke editing?
If you are using a TextFormField then you could try replacing it with a QuillEditor popup.

**Comment by CatHood0** [comment]
> How are you creating your text blocks?

So far I have not created anything in the table itself yet. First I try to clear up doubts and understand more how some parts of the package work inside.

> If you are using a TextFormField then you could try replacing it with a QuillEditor popup.

I don't quite understand what you mean by using a QuillEditor popup. I mean, I don't understand if you mean using a QuillEditor for each cell in the table. If it's the latter, I don't really know if it would be a good idea because the performance of using tables of considerable size could affect performance (this is what I believe, if my belief turns out not to be true, please explain to me why)

**Comment by AtlasAutocode** [comment]
I suggest you look up the closed issues relating to 'table'.
From the many requests and lack of implementation you should conclude that this is an extremely complex issue!
ellet0 has suggested using 'Embed' to encapsulate a package implementing a table. 
This is the best/easiest method but display and editing of cell content is performed by the table package and not by Flutter-Quill.
To give you editing styles you would need to render and edit each cell with a QuillEditor!

Your concept of using styles like header sounds good but wouldn't it involve creating new block styles, adding a new concept of within-block styles, implementing columns for layout and all of the hit testing, exporting and other matters?
I hope you are successful as I would really like to have a table....

**Comment by CatHood0** [comment]
Thanks for your answer. I know now what i need to do
