### ISSUE TITLE
add readOnly property in QuillEditorConfigurations

### ISSUE THREAD

**Issue by AsadKhan261** [singerdmx/flutter-quill#1950]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

Please add a readOnly property again ...

### Proposal

   configurations: QuillEditorConfigurations(
                            readOnly: true,

                            isOnTapOutsideEnabled: false,

                            disableClipboard: true,

                            controller: _controller,
                            autoFocus: false,

                            checkBoxReadOnly: true,

                            expands: false,
                            padding: EdgeInsets.zero,
                            customStyles: DefaultStyles(
                              h1: DefaultTextBlockStyle(
                                  GoogleFonts.montserrat(
                                    fontSize: 16,
                                    color: Colors.black,
                                    height: 1.15,
                                    fontWeight: FontWeight.w300,
                                  ),
                                  const VerticalSpacing(16, 0),
                                  const VerticalSpacing(0, 0),
                                  null),
                              sizeSmall: GoogleFonts.roboto(
                                  fontSize: 12, fontWeight: FontWeight.w300),
                            ),
                          ),

**Comment by CatHood0** [comment]
At the current version of Flutter Quill, `readOnly` option was moved to `QuillController`. If you want to call it, then just try:

´´´dart
final controller = QuillController.basic();
controller.readOnly = false;
´´´

**Comment by AsadKhan261** [comment]
Hi Cat,

Thank you for the guidance on moving the readOnly option to the QuillController. I have implemented the change as suggested:

QuillController _controller = QuillController.basic();

@override
void initState() {
  findTrainingProvider.getTrainingDetail();
  authProvider.getCustomerCard();
  _controller.readOnly = false;
  super.initState();
}


However, I am facing an issue. When users navigate to this screen, they are able to cut text from the Quill editor. I want the editor to be in read-only mode when displaying the details so that users cannot perform any actions like cutting text.

How can I ensure the Quill editor is read-only when displaying the details, and only editable when necessary? Any guidance or examples would be greatly appreciated.

Thank you!

**Comment by CatHood0** [comment]
This is the default behavior. `Cut`, and `select all text` from the editor are always available. I will take a look how remove this popup options to the users

**Comment by CatHood0** [comment]
Use this options in you:

```dart
QuillEditorConfigurations(
        showCursor: false, //hide the cursor
        enableInteractiveSelection: false, //removes all interactions (selection text, and popup with cut, copy, and select all)
)
```

**Comment by AsadKhan261** [comment]
Thank you for your help! I added the enableInteractiveSelection: false option, and it successfully removed all interactions, including text selection and the cut, copy, and select all popup. The editor is now working as intended in read-only mode.

I appreciate your prompt assistance!

**Comment by maxencealluin** [comment]
You might consider updating the docs since literally all snippets from the github or pub.dev don't work with the latest version. It is very hard to find up to date code examples for this library.
