### ISSUE TITLE
All font settings and styles are lost when you press Enter twice

### ISSUE THREAD

**Issue by geronimol** [singerdmx/flutter-quill#1951]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.4.5

### Steps to reproduce

I think this issue is related to #1119

The styles seem to be kept when pressing enter one time, but they lost if you press twice.

### Expected results

Keep styles after pressing Enter twice

### Actual results

Styles are lost pressing Enter twice

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Captura de pantalla 2024-06-26 a la(s) 16 01 35](https://github.com/singerdmx/flutter-quill/assets/56521222/46a28841-1913-45f0-b220-307a7480a005)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
I've looked into this issue and the problem appears to be that styles are associated with characters (content).
Empty lines do not have characters and therefore do not have styles.
When you create a new line (pressing Enter key) the style has to be 'got' from somewhere.

I have been able to update the code to get the style by looking-back past empty lines (but there may be a better way of doing this). This solves your double-enter problem BUT I am concerned that it might introduce undesirable side effects for other users and need more time to explore consequences before submitting a PR.

Please let me know if you have found other 'unexpected' style effects so we can look into them as well.

**Comment by geronimol** [comment]
@AtlasAutocode Thanks. I think this is an important issue since it is common behavior in text editors. Will wait for a fix.

This is another "issue" related to styles: #1925 . Not sure if there is another way to change the default style.

**Comment by geronimol** [comment]
@AtlasAutocode Thanks for the fix. It seems to work to keep styles, but the problem still happens when using a custom font, it changes it to normal.

![Captura de pantalla 2024-07-01 a la(s) 11 11 56](https://github.com/singerdmx/flutter-quill/assets/56521222/c74f924e-26ab-4000-bb72-a295396ae461)
