### ISSUE TITLE
Add additional information to selection

### ISSUE THREAD

**Issue by DavidHajum** [singerdmx/flutter-quill#1952]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I currently set my selection as a link like this:

`
    quillController.formatSelection(LinkAttribute('https://www.test.de/user/$value'));
`

If applied to the text @123, this would result in this output:

`<p><a href="https://www.test.de/user/123 " target="_blank">@123 </a></p>`

I would now like to add additional classes, for example to also store an ID or an avatarUrl.

I tried this code

`
quillController.formatSelection(Attribute('id', AttributeScope.inline, asd));
`

but it always gives me the error

`
Unable to apply Style to leaf: {Attribute{key: link, scope: AttributeScope.inline, value: https://www.test.de/user/123 }, Attribute{key: id, scope: AttributeScope.ignore, value: asd}}
'package:flutter_quill/src/models/documents/nodes/leaf.dart':
Failed assertion: line 31 pos 12: 'value.isInline || value.isIgnored || value.isEmpty'
`

Any help would be appreciated.

**Comment by CatHood0** [comment]
Which version are you using?

**Comment by DavidHajum** [comment]
Thank you very much for your answer.

I updated the package and the error is gone now, but the output still has not changed.

Instead of 

`<p><a href="https://www.test.de/user/123 " target="_blank">@123 </a></p>`

I would expect something like this:

`<p><a href="https://www.test.de/user/123" target="_blank" id="asd">@123 </a></p>`

Or is my code completely wrong here?

**Comment by CatHood0** [comment]
This is happening since you're not configure the vsc_quill_delta_to_html package. This package is used at this one, but, is limited on the documentation. I suggest use manually the package (vsc_quill_delta_to_html) and read the offical docs to render you custom attributes
