### ISSUE TITLE
italic tag in the middle of a word

### ISSUE THREAD

**Issue by adrianHerreraa** [singerdmx/flutter-quill#1953]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

1.- Wrap a word in a `<p>`, and a certain part of the word in `<em>`.

`<p>Exam<em>ple</em> text</p>`

### Expected results

should:
<p>Exam<em>ple</em> text</p>

the section on the word ple, is in italics, and the other text is not.

### Actual results

the label is replaced by underscore and displayed as follows:

<p>Exam_ple_ text</p>

### Code sample

<details><summary>Code sample</summary>

```dart
'<p>This is a normal sentence, and this section has greater emp<em>hasis.</em></p>',
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="586" alt="Captura de pantalla 2024-06-27 a la(s) 11 21 23 a m" src="https://github.com/singerdmx/flutter-quill/assets/31979901/1401d867-0a31-4f4f-a1f5-e2249ce46510">

</details>

### Logs

<details><summary>Logs</summary>

```console
no errors or related errors in console
```

</details>

**Comment by CatHood0** [comment]
Can you pass any example about this? I cannot reproduce this issue.

**Comment by adrianHerreraa** [comment]
> ¿Puedes dar algún ejemplo sobre esto? Me refiero al json que estás usando para esto, porque no puedo reproducir este problema.

yes, 
_controller.document = Document.fromDelta(
        DeltaHtmlExt.fromHtml(
         '<p>This is a normal sentence, and this section has greater emp<em>hasis.</em></p>',
        ),
      );

**Comment by CatHood0** [comment]
It could be an issue from html2md that is used to convert first html to markdown by this package. This error is common (i had the same issue but fix configuring rules from html2md). I'll take a look and make a pr if is necessary

**Comment by adrianHerreraa** [comment]
> It could be an issue from html2md that is used to convert first html to markdown by this package. This error is common (i had the same issue but fix configuring rules from html2md). I'll take a look and make a pr if is necessary.
> 
> This part of code needs "u" or "ins" tag to detect underline. If it is there, then your "emp_hasis._" would see like: "emphasis"
> 
> ```dart
> final _elementToInlineAttr = <String, ElementToAttributeConvertor>{
>     'em': (_) => [Attribute.italic],
>     'strong': (_) => [Attribute.bold],
>     'del': (_) => [Attribute.strikeThrough],
>     'a': (element) => [LinkAttribute(element.attributes['href'])],
>     'code': (_) => [Attribute.inlineCode],
>   };
> ```

yes, but I'm trying to use italics not underlining

**Comment by CatHood0** [comment]
What's the delta that the fromHtml give to you?
