### ISSUE TITLE
Feature: Line height attribute

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#1956]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Proposal

I propose creating an attribute to be able to modify the space between lines, of course, I am not just proposing whether to do my part. I already have the implementation done with the button next to the attribute, however, I would like to know if there are plans to implement this feature, since I have seen several ones (like me) that for their applications, an attribute like line-height , it would be very good for us, since it makes the editor more complete (and the spice between words and letters is another story.

The issue is that, if it is planned, I would like to know where I could start looking to add it natively to the project.

This is how work by now:

https://github.com/singerdmx/flutter-quill/assets/114286961/927836e4-5c6c-4835-8124-90d4aac911fe

**Comment by singerdmx** [comment]
I wonder how this is handled in [react-quill](https://www.npmjs.com/package/react-quill)

**Comment by singerdmx** [comment]
Below is the reply from ChatGPT:

React Quill does not have a built-in attribute specifically for setting line height directly through its API. Instead, you can adjust line height and other styles by applying custom CSS to the editor content.

Here’s how you can adjust line heights in React Quill:

	1.	Define your CSS for the desired line height, for example:
```
.ql-editor {
  line-height: 1.5;  /* Adjust the value as needed */
}
```
2.	Ensure this CSS is loaded into the component where React Quill is used. This could be in your global stylesheet or scoped styles depending on your setup.

**Comment by singerdmx** [comment]
If we cannot find this being enabled elsewhere, we may have to create a new attribute with a good name

**Comment by CatHood0** [comment]
On my implementation i called as:

```dart
class LineHeightAttribute extends Attribute<String?> {
  const LineHeightAttribute({String? value = "1.0"})
      : super(
          'line-height',
          AttributeScope.block,
          value,
        );
}
```

**Comment by singerdmx** [comment]
What would the corresponding json data look like?

**Comment by CatHood0** [comment]
Looks like:

![Screenshot_20240628-225308~2](https://github.com/singerdmx/flutter-quill/assets/114286961/e2c8ff64-8b90-46ff-b5dc-214c97323151)

**Comment by singerdmx** [comment]
I am fine with `line-height`
But would the number mean differently for different platform such as web v.s. mobile?

**Comment by singerdmx** [comment]
Here is what ChatGPT says:

it is a multiplier applied to the current font size to determine the height of the line boxes in which the text is placed. Here’s what that number represents:

	•	Unitless value (e.g., 1.5): This is a multiplier applied to the element’s font size. For example, if the font size is 16px, a line-height of 1.5 means the actual line height will be 24px (1.5 times 16). This is the preferred method because it maintains the line height proportional to the font size, making it easier to manage across different font sizes and on responsive designs.
	•	Percentage value (e.g., 150%): This also acts as a multiplier but is based directly on the percentage of the font size. Like the unitless value, 150% of a 16px font size results in a 24px line height. The effect is similar to using a unitless value, but it’s explicitly tied to a percentage.
	•	Length value (e.g., 20px): This sets the line height to a fixed value, regardless of the font size. This can be useful for achieving specific spacing effects but is less flexible when dealing with varying text sizes or responsive layouts.

**Comment by singerdmx** [comment]
So we will only support Unitless value for now?

**Comment by CatHood0** [comment]
I think on this feature using always Unitless, but, idk about web platform. I'll need to take a look to watch the behavior

**Comment by singerdmx** [comment]
Just unitless value should be fine.
I just want you to be aware the existence of the other two.

**Comment by singerdmx** [comment]
Actually try not to make this overcomplicated and only supporting unitless value should be good

**Comment by CatHood0** [comment]
I know, i think this works better using unitless because is easy to maintain, instead calculating percentage or the length value. I'll do the pr soon

**Comment by CatHood0** [comment]
@singerdmx i already make the attribute, add the style in `DefaultStyles`, the dropdown button, even the translations for all languages. But, it is not applied when i select a option. Was I missing something?
