### ISSUE TITLE
Weird behavior on use TextField and QuillEditor on same screen

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#1957]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.4.8

### Steps to reproduce

Just add a Textfield and a QuillEditor in different parts of the screen
Write something on the Textfield
Move to QuillEditor and you should see a double cursor instead focus just QuillEditor

### Expected results

Focus correctly between QuillEditor and Textfield

### Actual results

The QuillEditor and Textfield are focused both

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/singerdmx/flutter-quill/assets/114286961/d91c48e2-1281-4330-8d2a-ac13bfdb217e

</details>

### Logs

<details><summary>Logs</summary>

```console
No logs at this error are showed
```

</details>

**Comment by singerdmx** [comment]
Is it possible to repo this with a simpler use case?
I mean, does this issue happen without the use of table?

**Comment by CatHood0** [comment]
Yeah, give me some time to create a minimal reproducible case

**Comment by ellet0** [comment]
Though it will not fix the bug as it's unrelated, did you try using `EditableText`? This widget is used internally by material `TextField` and is available on `widgets.dart` and doesn't require `material.dart`

**Comment by CatHood0** [comment]
> Though it will not fix the bug as it's unrelated, did you try using EditableText? This widget is used internally by material TextField and is available on widgets.dart and doesn't require material.dart

I'll try this

**Comment by CatHood0** [comment]
This issue could be related #1899

**Comment by CatHood0** [comment]
> Though it will not fix the bug as it's unrelated, did you try using EditableText? This widget is used internally by material TextField and is available on widgets.dart and doesn't require material.dart

It works better than the `TextField,` but, if you focus first at the table cell `(EditableText)`, and after try to focus the `QuillEditor` then the visual bug persist
