### ISSUE TITLE
What's the correct way to abort an insertion?

### ISSUE THREAD

**Issue by oligazar** [singerdmx/flutter-quill#1959]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I need to implement text length limit in quill editor. As there's no way to set the limit afaik, I created an InsertRule, which should not allow to insert data into the document if the length limit is reached. The code looks like this
```
@override
  Delta? applyRule(
    Delta document,
    int index, {
    int? len,
    Object? data,
    Attribute<dynamic>? attribute,
  }) {
    final dataLength = data is String ? data.length : 0;
    final shouldAbort = textLength + dataLength > contentLengthLimit;
    if (shouldAbort) {
      // abort the changes
      return Delta();
    }
    // allow the changes
    return null;
  }
```
To avoid the document change an empty Delta is returned. But this results in Failed assertion
```
The following assertion was thrown during method call TextInputClient.updateEditingState:
'package:flutter_quill/src/models/documents/document.dart': Failed assertion: line 309 pos 12: 'delta.isNotEmpty': is not true.
```

So what would be the intended way of implementing this?

**Comment by CatHood0** [comment]
Delta always need a new line at last operation. If you want a empty document, just clear it, and insert a new line. All should be fine

**Comment by oligazar** [comment]
@CatHood0 But I don't need a new line. I need to leave the document exactly the way it was before

**Comment by CatHood0** [comment]
The new line is just a necessary thing, and it doesn't have any effect on the view. If you still want to maintain your document empty, we cannot do nothing about it. Delta works of that way

**Comment by oligazar** [comment]
@CatHood0 can you please give me a code example?
Because I'm trying to do it like this, and it's definitely inserting a new line, which a want to avoid
```
if (shouldAbort) {
      if (dataLength > 1) {
        AppToasts.info(
          message: 'Unable to insert.\nContent length limit is reached.',
        ).show(get<AppRouter>().navigatorContext!);
      }
      return Delta()
        ..retain(index)
        ..insert('\n');
    }
```

**Comment by CatHood0** [comment]
Which version are you using? Could be an error from the version

> if (shouldAbort) {
      if (dataLength > 1) {
        AppToasts.info(
          message: 'Unable to insert.\nContent length limit is reached.',
        ).show(get<AppRouter>().navigatorContext!);
      }
      return Delta()
        ..retain(index)
        ..insert('\n');
    }

It looks like if the Delta just don't do the insertion. I think could be or a version error, or a wrong logic implementation at your code

This is the line that throws the error
```dart
assert(delta.isNotEmpty)
```

And this is how delta verify if your operations aren't empty

```dart
/// Returns `true` if this delta is not empty.
bool get isNotEmpty => operations.isNotEmpty;
```

**Comment by oligazar** [comment]
You're correct, returning `Delta()` fails the assertion as it doesn't have operations. You suggested inserting a new line saying it will leave the document as it was before. I did it like this:
```
eturn Delta()
..retain(index)
..insert('\n');
```
But it's inserting a new line. How can I avoid any unwanted changes to the document not getting any exceptions? 

Maybe it's better to create PR, replacing `assert(delta.isNotEmpty)` with `if (delta.isEmpty) return;`? Would that work?

**Comment by CatHood0** [comment]
@ellet0  can you see this?

**Comment by ellet0** [comment]
>   @ellet0  can you see this? 
> 

I'm unfamiliar with the code that's related to how Delta rules work, I think we could provide an option to ignore this rule of new rule. It doesn't confirm to Quill. Developers expect to have the compatible underline data with similar behavior, so I would suggest to have the current rule as default.

The issue of having one line in the last delta operation, it shouldn't change the view or user experience. I remember there was a static const that represents an empty document that already has one line in the last operation.

**Comment by CatHood0** [comment]
Does this issue still persists? If it does, please reopen this issue

**Comment by EchoEllet** [comment]
@oligazar Can you confirm if this still an issue?
