### ISSUE TITLE
Need to know how to set html and get html 

### ISSUE THREAD

**Issue by Aruljebaraj** [singerdmx/flutter-quill#1963]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I need to use richtext box editor unfortunately most of them are not supported for windows here I need an option to set the html text from api and user can edit can add style and should able to get edited html any idea to achieve this

**Comment by CatHood0** [comment]
What are you mean? I think you are talking about get Delta from a `HTML` inpu (like from a `API`) and convert the `Delta` to `HTML` too.

When you want to get a Delta from a HTML input use this class:

```dart
final Delta delta = DeltaX.fromHtml(htmlText)
```

and if you want to create a `HTML` from your Delta, then you use `toHtml` method that is used by `Delta` class.

```dart
final String html = quillController.document.toDelta().toHtml();
//or
final String html = yourDelta.toHtml();
```
