### ISSUE TITLE
How to show only one heading option?

### ISSUE THREAD

**Issue by kawsaramin101** [singerdmx/flutter-quill#1965]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I want to create a minimal rich text editor. Now there are three options for heading (Heading 1, Heading 2, Heading 3). I only want one heading option and I don't even want the normal option. Like github does it 
![Screenshot_20240519_1401592](https://github.com/singerdmx/flutter-quill/assets/71335212/3a06397c-4ded-4740-9ee6-5e94427ad2b4)

 How can I achieve this?

**Comment by CatHood0** [comment]
You can just make your own custom button and at the `onPress`, add this:

```dart
quillController.formatSelection(Attribute.h1);
```

**Comment by digitalheartxs** [comment]
I still have troubles making it work correctly

that's my current code:
```
                  QuillToolbarIconButton(
                    tooltip: 'Header',
                    onPressed: () {
                      if(controller.getSelectionStyle().attributes['header'] == null) {
                        controller.formatSelection(Attribute.h1);
                      } else {
                        // TODO how to remove Attribute.h1?
                      }
                    },
                    icon: Text('H'),
                    isSelected: controller.getSelectionStyle().attributes['header'] != null, //TODO isSelected is not refreshing correctly
                    iconTheme: null,
                  ),
```

1. How to toggle/remove attribute.h1 correctly?
2. `isSelected` is not refreshing correctly and `H` icon selection is not appearing, how to implement it properly?

**Comment by CatHood0** [comment]
@digitalheartxs use `getSelectionStyle()` to get all attributes into the current position of the caret and check if the attributes contains the attribute that you want to check.

```dart
widget.controller
            .getSelectionStyle()
            .attributes[<the attribute key>];
```
