### ISSUE TITLE
Add a config to disable the markdown style auto converts 

### ISSUE THREAD

**Issue by haorendashu** [singerdmx/flutter-quill#1966]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

If you input '1.' and space or input '-' and space. It will auto convert to the markdown style.

I think there should be a config can disable these style convert.

The feature i have open an issue #1949 and i was thought it was a bug. I will close it. 

### Proposal

For sometimes, dev use flutter-quill for a normal text editor not a markdown editor, these auto convert will make some issue for text editor.

**Comment by CatHood0** [comment]
@AtlasAutocode Are you familiar with this? Idk what part of the code is responsible for doing this.

**Comment by AtlasAutocode** [comment]
It is implemented in raw_editor_state.dart
Line 789 recognizes '1.' and '-' and converts to list.
It would be relatively simply to add a configuration option to QuillRawEditorConfigurations.
But watch out for line 797 so you return the correct KeyEventResult.

There are several questions:
1. Should this auto-convert to list be done at all? It is very convenient for ordered list and people are probably using this without knowing that it is coded! For bullet lists my feeling is 'iffy' - it's OK but not intuitive.
2. Or should it be left with an option to disable? Should the default be enabled or disabled?
3. Adding yet another configuration option increases complexity and people (including me!) are already struggling with not knowing that there are options and where to set options. Also, if a configuration is set in the wrong place and has to be moved at a later date, people using the original will have their code break.
4. It is always easy to add yet another option, but at some point, the options start to conflict with each other.

It is a pity we don't have a way of debating these issues to get a consensus of what the majority want.
Good luck on deciding.

**Comment by AtlasAutocode** [comment]
Further thought:
The OP was concerned with input '-' and space
We could disable this conversion and leave the input '1.' and space.
We would not need to add a configuration option and tests.

Would this solve the OP problem?
If anyone complained, we would know that people are using the '-' and space conversion and we would know we need a configuration.

Any comments?

**Comment by CatHood0** [comment]
I'll take a look about this

**Comment by CatHood0** [comment]
@AtlasAutocode thanks for help me to find where was the issue
