### ISSUE TITLE
How to change background of toggle.

### ISSUE THREAD

**Issue by Itrainlcincom** [singerdmx/flutter-quill#1968]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

1. Create button as below
```
QuillToolbarToggleStyleButton(
                      options: const QuillToolbarToggleStyleButtonOptions(),
                    controller: controller,
                    attribute: Attribute.bold,
                  ),
```
3. When tap button
![IMG_0372](https://github.com/singerdmx/flutter-quill/assets/82483606/c07d7675-51d0-4be8-b748-499a33a026c9)

4. Background of [B] button  with color as image at step 3.

### Expected results

I would like to change background of [B] button to blue color. Please help me this issue

### Actual results

Background of [B] button  with color as image at step 3.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
No log.
```

</details>

**Comment by CatHood0** [comment]
You need just pass this configuration to you `QuillToolbarToggleStyleButtonOptions`:

```dart
   QuillToolbarToggleStyleButtonOptions(
          iconTheme: QuillIconTheme(
          iconButtonUnselectedData: IconButtonData(color: Colors.black),
            iconButtonSelectedData:
                IconButtonData(color: Colors.blue),
         ),
    ),
```
