### ISSUE TITLE
`readOnlyMouseCursor` doesn't work

### ISSUE THREAD

**Issue by geronimol** [singerdmx/flutter-quill#1970]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.3

### Steps to reproduce

Tested on Web(Chrome) and MacOS

```dart
return QuillEditor.basic(
      configurations: QuillEditorConfigurations(
        controller: _controller,
        scrollable: false,
        enableInteractiveSelection: false,
        readOnlyMouseCursor: SystemMouseCursors.grab,
      ),
    );
```

### Expected results

Default mouse cursor should change when hovering text.

### Actual results

Default mouse cursor not changing when hovering the text.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment]
Does this issue still exist?

**Comment by geronimol** [comment]
@singerdmx This wasn't fixed. Should I create a new issue for this?
