### ISSUE TITLE
`customStyles` are not saved

### ISSUE THREAD

**Issue by geronimol** [singerdmx/flutter-quill#1971]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.3

### Steps to reproduce

I want to set the default text color to red:
```dart
QuillEditor.basic(
  configurations: QuillEditorConfigurations(
    controller: _controller,
    autoFocus: true,
    customStyles: const DefaultStyles(
      paragraph: DefaultListBlockStyle(
        TextStyle(color: Colors.red),
        VerticalSpacing(0, 0),
        VerticalSpacing(0, 0),
        null,
        null,
      ),
    ),
  ),
),
```

The editor shows default text color as red
![Captura de pantalla 2024-07-04 a la(s) 17 12 16](https://github.com/singerdmx/flutter-quill/assets/56521222/6345180d-9b35-4fc9-86ac-5be804a31a1e)

But when I save it using
```dart
_controller.document.toDelta()
```
print()
![Captura de pantalla 2024-07-04 a la(s) 17 13 11](https://github.com/singerdmx/flutter-quill/assets/56521222/446e14ca-0aaf-4414-83f5-3ff9548fe216)
---
```dart
_controller.document.toDelta().toJson()
```
print()
![Captura de pantalla 2024-07-04 a la(s) 17 13 27](https://github.com/singerdmx/flutter-quill/assets/56521222/f7a20c2a-c842-4ef6-a8f5-d145b73e37fc)
---
Related: #1925

### Expected results

Using `controller.document.toDelta()` should save the `customStyles`

### Actual results

`customStyles` aren't saved when using `controller.document.toDelta()`

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
Custom styles is just a visual configurations, them never have any effect on the Delta result

**Comment by ellet0** [comment]
> Custom styles is just a visual configurations, them never have any effect on the Delta result

I think what he might try to do is to have the same content style as Delta JS (#1925), I would suggest changing the style in the Quill JS Editor Element/Component.
