### ISSUE TITLE
How to remove ol/ul‘ s indents?

### ISSUE THREAD

**Issue by jinyu0712** [singerdmx/flutter-quill#1973]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How to remove ol/ul‘ s indents? Thanks🙏

**Comment by CatHood0** [comment]
It can't be removed, but, you can create your own button for indent, and when it's pressed first validate if the current cursor position is not into a list block

**Comment by jinyu0712** [comment]
> I have another question, how to splice a String at the cursor? Thanks🙏

state.controller.replaceText helped

**Comment by CatHood0** [comment]
> state.controller.replaceText helped

Actually that's the method you probably always need when you want to splice 2 strings together.
