### ISSUE TITLE
HTML Conversion of Link

### ISSUE THREAD

**Issue by Nightbl927** [singerdmx/flutter-quill#1977]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.5

### Steps to reproduce

1. Create a string: `x = '<a href="https://www.google.com">'`
2. Set up  quillController.document = Document.fromHtml(x);
3. Display the quill editor

### Expected results

The delta should be: {"insert":"https://www.google.com","attributes":{"link":"https://www.google.com"}},{"insert":"\n"}

### Actual results

The delta is: [{"insert":{"video":"https://www.macrumors.com/"}},{"insert":"\n"}]

### Code sample

```
QuillController _quillController = QuillController.basic();

String x = '<a href="https://www.macrumors.com/" type="text/html">fdsfsd</a>';

_quillController.document = Document.fromHtml(x);

//display
QuillEditor.basic(
  configurations: QuillEditorConfigurations(
    embedBuilders: kIsWeb ? FlutterQuillEmbeds.editorWebBuilders() : FlutterQuillEmbeds.editorBuilders(),
    enableScribble: true,
    customStyles: const DefaultStyles(
      link: TextStyle(color: Colors.blue),
    ),
    controller: _quillController,
    sharedConfigurations: const QuillSharedConfigurations(
      locale: Locale('en'),
    ),
  ),
),
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by Nightbl927** [comment]
I would expect the fromHTML() to convert the <a> tag to a link rather than a video.

**Comment by CatHood0** [comment]
this could be a issue that i implemented when was added fromHtml to videos

**Comment by Nightbl927** [comment]
Thank you for the quick fix, @CatHood0!

I am also doing a test with the video tag where the src isn't a youtube link.

```
<video src="https://media.geeksforgeeks.org/wp-content/uploads/20220418201419/iconButton.mp4">Your browser does not support the video tag.</video>
<video><source src="https://media.geeksforgeeks.org/wp-content/uploads/20220418201419/iconButton.mp4">Your browser does not support the video tag.</video> 
```

On all of the !_youtubeVideoUrlValidator it either returns the <video>${child.outerHTML}</video> or node.outerHTML. Both of which do not convert to a video player delta. However if we change those to show the "[![" it will play the video. What are your thoughts on that logic?

**Comment by CatHood0** [comment]
> I am also doing a test with the video tag where the src isn't a youtube link.

I had not seen this, and I don't know why he didn't notify me. Anyway, as you may already know, in the current version the implementation was replaced by [flutter_quill_delta_from_html](https://github.com/CatHood0/flutter_quill_delta_from_html) which is a package dedicated exclusively to dealing with Deltas and pure HTML, so what any resulting problem, you would have to warn it in the corresponding package
