### ISSUE TITLE
[Web] 

### ISSUE THREAD

**Issue by buimanhhungit** [singerdmx/flutter-quill#198]
My issue is about [Web]

 Space key not working in some cases.

**Comment by GyuriMajercsik** [comment]
Try override the default shortcuts. You can do that in the following way: 

```
MaterialApp(
      shortcuts: {
        ...WidgetsApp.defaultShortcuts,
        if (PlatformUtils.isWeb)
          LogicalKeySet(LogicalKeyboardKey.space): null,
      },
...
```

**Comment by buimanhhungit** [comment]
![image](https://user-images.githubusercontent.com/51559988/116678217-42de7180-a9d3-11eb-8005-1ca43528d4e8.png)
Not working

**Comment by buimanhhungit** [comment]
Up, down, left, right key not working some case
