### ISSUE TITLE
LineHeight toolbar button popup menu appears disconnected

### ISSUE THREAD

**Issue by AtlasAutocode** [singerdmx/flutter-quill#1981]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.7

### Steps to reproduce

This is a good addition to flutter quill editor.

1. Enable showing line height toolbar button in example application:     (this.showLineHeightButton = true,)
2. Click button and popup menu appears in wrong place.

### Expected results

Popup menu should be connected to the toolbar button.
The other font selection buttons have the popup connected to the button.

### Actual results

Placement of the menu popup depends on the location of the button within the toolbar.
If the button is at the left then placement is usually correct.
If the button is at the right then placement is flush right which is OK.
If the button is somewhere in the middle, the popup appears a long distance to the right and disconnected from the button
(This is shown in the screenshot)

### Code sample

<details><summary>Code sample</summary>

```dart
simple_toolbar_configurations.dart
class QuillSimpleToolbarConfigurations
    this.showLineHeightButton = true,
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![Screenshot 2024-07-06 125947](https://github.com/singerdmx/flutter-quill/assets/165201146/2552ee91-3eac-4498-a169-1b79ca381bf5)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by singerdmx** [comment]
@CatHood0 do you want to take a look?

**Comment by CatHood0** [comment]
@AtlasAutocode  can you provide any screenshot?

**Comment by AtlasAutocode** [comment]
[Screenshot](https://github.com/singerdmx/flutter-quill/assets/165201146/2552ee91-3eac-4498-a169-1b79ca381bf5)

You can see the toolbar button at ~25% left and the popup is ~75% right. I should say this in on Windows - desktop and edge browser.
The popups for font, size and headers are attached to the buttons. Does that help?

**Comment by ellet0** [comment]
> of the `PopupMenu`

Though this is not related, I would recommend to try using `MenuBar` or `MenuAnchor`, those introduced in Material 3 and as stable as Flutter 3.16 released. See [Flutter Material 3 Migration New Componenets](https://docs.flutter.dev/release/breaking-changes/material-3-migration#new-components)

> Menus are anchored by a MenuBar or a MenuAnchor. The new menu system isn't something that existing applications must migrate to, however applications that are deployed on the web or on desktop platforms should consider using it instead of PopupMenuButton (and related) classes.

It seems that those two widgets are recommended to use on Flutter Desktop or Web, also some `QuillToolbar` buttons already using them, so we might want to consider either using the new widgets or revert to the old ones for consistency.

**Comment by AtlasAutocode** [comment]
As a desktop developer, I would vote to use the newer MenuAnchor that is already being used for font, size and header.
Since I am the one asking for this, would it be helpful if I attempt the conversion?

**Comment by ellet0** [comment]
> As a desktop developer, I would vote to use the newer MenuAnchor that is already being used for font, size and header. Since I am the one asking for this, would it be helpful if I attempt the conversion?

You can give it a try if you prefer, we will take care of it at later point once the related bug on Flutter repository fixed.

**Comment by CatHood0** [comment]
> You can see the toolbar button at ~25% left and the popup is ~75% right. I should say this in on Windows - desktop and edge browser

I use MediaQuery to calculate where must be rendered the position of the PopupMenu. This causes it to be imprecise probably due to poor implementation on my part. I'm still trying to figure it out

**Comment by singerdmx** [comment]
> As a desktop developer, I would vote to use the newer MenuAnchor that is already being used for font, size and header. Since I am the one asking for this, would it be helpful if I attempt the conversion?

As long as the issue is addressed. I believe we are bound to make further changes in the future
