### ISSUE TITLE
Should we now change the current implementation for get Delta from HTML input text?

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#1982]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I know that at this point, we have an implementation that works as we expect in terms of how the html is converted to Delta, however, I would like to know your opinion if we should start to find a more effective solution, since we first converted the `HTML` to `Markdown`, and then many `HTML` styles that could be useful to users are lost.

To solve this, i create a [package](https://github.com/CatHood0/flutter_quill_delta_from_html) that supports most of the attributes used by the package, and that converts most of the `HTML` input (without parse to `Markdown`) into usable and "correct" (I think) `Delta.`

**Comment by singerdmx** [comment]
Are you suggesting to move logic from your package to this repo?
Not exactly sure what you want to do

**Comment by singerdmx** [comment]
I think you can go ahead to create PRs following what you described

**Comment by CatHood0** [comment]
In itself we do not need to move any logic. The package that I published [flutter_quill_delta_from_html](https://pub.dev/packages/flutter_quill_delta_from_html) is already published in pub dev, and we would only have to import it without adding more weight to the project (taking into account that `flutter_quill_delta_from_html` anyway It's a really small package)

**Comment by singerdmx** [comment]
Sure. We can import it or just copy everything over. Your call
