### ISSUE TITLE
Cargokit BuildTool failed with error

### ISSUE THREAD

**Issue by herowws** [singerdmx/flutter-quill#1991]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

 flutter doctor   
 
<img width="1534" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/41428542/4250c7f0-00d7-4b35-a624-f2f51a09f9d2">

### Expected results

<img width="1610" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/41428542/68313436-9029-4de1-b6d6-b65ee5c66718">

### Actual results

<img width="1610" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/41428542/68313436-9029-4de1-b6d6-b65ee5c66718">

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by herowws** [comment]
flutter_quill: 9.4.0
  flutter_quill_extensions: 9.4.0

**Comment by CatHood0** [comment]
Can you update to the last version (9.5.12) and test if this issue persist?

**Comment by hungryemon** [comment]
Android support 

The NDK version used is specified in `android/app/build.gradle` of your Flutter project.

```
android {
    // by default the project uses NDK version from flutter plugin.
    ndkVersion flutter.ndkVersion
```
If you have older Flutter android project, you will need to specify a reasonably recent minimal SDK version in `android/app/build.gradle`:

```
android {
    defaultConfig {
        minSdkVersion 23
```
To be able to write images and other custom data to Android clipboard you need to declare a content provider in `AndroidManifest.xml`:

```
<manifest>
    <application>
        ...
        <provider
            android:name="com.superlist.super_native_extensions.DataProvider"
            android:authorities="<your-package-name>.SuperClipboardDataProvider"
            android:exported="true"
            android:grantUriPermissions="true" >
        </provider>
        ...
    </application>
</manifest>
```
Be sure to replace <your-package-name> in the snippet with your actual package name.

**Comment by EchoEllet** [comment]
This should be no longer an issue when using `flutter_quill` without `flutter_quill_extensions` (See #1914).

New versions have been released, I will update `flutter_quill_extensions` to use the latest version of `super_clipboard` (`0.8.20`) as the new minimum version. Feel free to open a new issue if this issue persists.

**Comment by mny459** [comment]
```
* Where:
Script '/Users/a/.pub-cache/hosted/pub.dev/super_native_extensions-0.8.20/cargokit/gradle/plugin.gradle' line: 65

* What went wrong:
Execution failed for task ':super_native_extensions:cargokitCargoBuildSuper_native_extensionsRelease'.
> Process 'command '/Users/a/.pub-cache/hosted/pub.dev/super_native_extensions-0.8.20/cargokit/gradle/../run_build_tool.sh'' finished with non-zero exit value 69

```

```
  flutter_quill: ^10.5.9
  flutter_quill_extensions: ^10.5.9
```

Seems still exist @EchoEllet

**Comment by EchoEllet** [comment]
- Can you share on which platform you're building the app?
- Have you ran `flutter clean` and then `flutter pub get --verbose` and share the full output (on GitHub Gist or [Hastebin](https://www.toptal.com/developers/hastebin))?
- Can you run `flutter doctor -v` and share the output?
- Can you confirm if you have updated Android SDK to the latest version (both `SDK Platforms` and `SDK Tools`)? By opening the **SDK Manager** and then confirm the **SDK Components Setup**

**Comment by mny459** [comment]
> * Can you share on which platform you're building the app?
> * Have you ran `flutter clean` and then `flutter pub get --verbose` and share the full output (on GitHub Gist or [Hastebin](https://www.toptal.com/developers/hastebin))?
> * Can you run `flutter doctor -v` and share the output?
> * Can you confirm if you have updated Android SDK to the latest version (both `SDK Platforms` and `SDK Tools`)? By opening the **SDK Manager** and then confirming the **SDK Components Setup** once you click on **Edit**.
> * Do you have **Rust** installed? The `supper_clipboard` plugin will automatically download precompiled binaries for the target platform.

Thank you for reply.

I find the wrong document, by install rust, everything works now. Thank you.

Have a good day.
