### ISSUE TITLE
Does flutter quill select text size?

### ISSUE THREAD

**Issue by viet-tran-0159** [singerdmx/flutter-quill#1992]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

![image](https://github.com/singerdmx/flutter-quill/assets/149549280/6392c356-a40c-4ec8-baac-e50b74797e55)

I want to set text size but can't find it in flutter quill

**Comment by AtlasAutocode** [comment]
You can set the default text style using QuillEditorConfigurations.customStyles.
In the example app code in file lib\screens\quill\my_quill_editor.dart line 48 shows how the h1 style is set. You could add a style for paragraph:

Code snippet:

> defaultTextStyle.style.copyWith(fontSize: 32, ),
```
  Widget build(BuildContext context) {
    final defaultTextStyle = DefaultTextStyle.of(context);
    return QuillEditor(
        configurations: configurations.copyWith(
                customStyles: DefaultStyles(
                  paragraph: DefaultTextBlockStyle(
                    defaultTextStyle.style.copyWith(fontSize: 32, ),
                    const VerticalSpacing(0, 0),
                    const VerticalSpacing(0, 0),
                    null,
                  ),
                ),
```
