### ISSUE TITLE
When you type Chinese into the Mac Chrome browser, a long blue line appears

### ISSUE THREAD

**Issue by Winstonokk** [singerdmx/flutter-quill#1993]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

A long blue line appears when you type Chinese into the Mac Chrome browser, but windows browsers work fine
![2dc310bb0a6170d5858c1a5529fd8506](https://github.com/singerdmx/flutter-quill/assets/16253450/99dd14cb-8294-4b79-995f-88e253fc579b)

**Comment by AtlasAutocode** [comment]
That looks like a horizontal scroll bar.
Perhaps associated with the pop up?
Can you drag it?

**Comment by Winstonokk** [comment]
I can't drag it. It appears only when the input Chinese has not been confirmed, and when the confirmed input Chinese content will disappear, it looks like a pre-entered selection

**Comment by singerdmx** [comment]
I am unsure it is actually the issue with flutter-quill.
I think you need to investigate this on your own.
It may have to do how you embed flutter-quill in your app.
I am going to close this.
