### ISSUE TITLE
If div in html - html to quill won't render anything 

### ISSUE THREAD

**Issue by HeropolisDa2ny** [singerdmx/flutter-quill#1994]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

flutter_quill: ^9.5.12 quill_html_converter: ^9.5.12 flutter_quill_extensions: ^9.5.12

### Steps to reproduce

1. Init the controller : `final QuillController _controller = QuillController.basic();`
2. Init the document controller : 
```
_controller.document = Document.fromDelta(
        Document.fromHtml('<html><body><div>Name : Test</div></body></html>')
            .toDelta());
```
3. log(_controller.document.isEmpty().toString());
4. Result: true

If we remove the div from the HTML it works fine. (but I need the divs)

### Expected results

<img width="226" alt="Screenshot 2024-07-09 at 9 34 01" src="https://github.com/singerdmx/flutter-quill/assets/128067748/b806ad78-8c0b-4749-bb92-be6568b2d244">

### Actual results

<img width="216" alt="Screenshot 2024-07-09 at 9 34 08" src="https://github.com/singerdmx/flutter-quill/assets/128067748/996bd160-a6b7-4e4c-8743-332126128765">

### Code sample

<details><summary>Code sample</summary>

```dart
final QuillController _controller = QuillController.basic(
    configurations: QuillControllerConfigurations(),
  );

  @override
  void initState() {
    _controller.document = Document.fromDelta(
      Document.fromHtml('<html><body><div>Name : Test</div></body></html>').toDelta(),
    );
    _controller.readOnly = false;

    log(_controller.document.toPlainText().toString());

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return QuillEditor.basic(
      configurations: QuillEditorConfigurations(
        controller: _controller,
        enableScribble: false,
        enableInteractiveSelection: false,
        sharedConfigurations: QuillSharedConfigurations(
          locale: Locale(Localizations.localeOf(context).languageCode),
        ),
        embedBuilders: kIsWeb
            ? FlutterQuillEmbeds.editorWebBuilders()
            : FlutterQuillEmbeds.editorBuilders(),
      ),
    );
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
@HeropolisDa2ny this isn't directly related with the package. The issue comes from [flutter_quill_delta_from_html](https://github.com/CatHood0/flutter_quill_delta_from_html) that not support `<div>` tags. At this moment this is a opened issue related with <div> and html wrapped within it [issue](https://github.com/CatHood0/flutter_quill_delta_from_html/issues/3)

**Comment by CatHood0** [comment]
I already make a PR to resolve this
