### ISSUE TITLE
please add alignment and direction support for this great package

### ISSUE THREAD

**Issue by T-Shamspour** [singerdmx/flutter-quill#2]
please add alignment and direction support for this great package

**Comment by singerdmx** [comment]
We did add alignment, see https://github.com/singerdmx/flutter-quill/blob/master/lib/widgets/text_line.dart#L64
But it seems not working. Still trying to figure this out.
Need help if someone can contribute a pull request if possible.

**Comment by singerdmx** [comment]
Actually found the fix https://github.com/singerdmx/flutter-quill/commit/486b823d35df31b5c9856dbb2c9ccf757ad087a6

Need to add toolbar button next.

Then figure out the text direction.

**Comment by singerdmx** [comment]
@T-Shamspour We currently don't have plan regarding text direction.
It seems a bare use.
But if you need it, you can submit a pull request.

**Comment by singerdmx** [comment]
No plan to support alignment. Dropping it

**Comment by yuxiang-projz** [comment]
alignment is important, please consider to support it @singerdmx

**Comment by boinxi** [comment]
Hi, is there any chance this feature can be be considered again?
This could be very helpful fur me and many others.
without this feature bullet lists and numerical lists are on the opposite side of the text
![image](https://user-images.githubusercontent.com/57293916/144238369-5fddb4c2-da33-4d53-9b3c-3aeaa80d55af.png)

**Comment by schehata** [comment]
I would also like to have this feature, to build an editor for RTL languages. @singerdmx why aren't you considering it? it would be very useful for devs in the other parts of the world. 

There are 12 languages that are written from the right to the left:

    Arabic
    Aramaic
    Azeri
    Divehi
    Fula
    Hebrew
    Kurdish
    N'ko
    Persian
    Rohingya
    Syriac
    Urdu

**Comment by xinyuezhang0402** [comment]
You can submit PR

**Comment by xinyuezhang0402** [comment]
This is the last effort we are going to spend on this

https://github.com/singerdmx/flutter-quill/commit/4f9ee27f7dc8baf64d36784d4d74c6feb1e18ece

If it has bugs, please figure it out and submit fix
