### ISSUE TITLE
Image attribute shows broken image icon when clicked

### ISSUE THREAD

**Issue by ArjanAswal** [singerdmx/flutter-quill#20]
When I click the image rendered on the editor, it shows a [broken image](https://www.materialui.co/icon/broken-image) icon.

**Comment by singerdmx** [comment]
Are you using sample delta json?

**Comment by ArjanAswal** [comment]
No, my own images and text.

**Comment by singerdmx** [comment]
By far we don't have this issue. I think we are using uploaded network image while yours is on local.

**Comment by singerdmx** [comment]
I think the current code only works for uploaded network image

**Comment by ArjanAswal** [comment]
> I think the current code only works for uploaded network image
> 

Yes that might be the problem.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107547078-ec0a8e00-6b81-11eb-89e4-be876fc9f60e.png)
The code is here.
Can you submit a pull request?
You can check if image url starts with "http". Do if else

**Comment by singerdmx** [comment]
@ArjanAswal Default branch master is on channel master. To use channel stable, switch to branch stable.
I think your PR can go to branch `stable`

**Comment by singerdmx** [comment]
@ArjanAswal I have added you as collaborator so you can directly push without our approval if you feel confident (no need to submit a PR).
Note that you want to use branch stable for channel stable

**Comment by ArjanAswal** [comment]
> @ArjanAswal I have added you as collaborator so you can directly push without our approval if you feel confident (no need to submit a PR).

Thank you for this, looking forward to contributing to this package.

For now, I have filed this [PR](https://github.com/singerdmx/flutter-quill/pull/21/commits/c2999edbdb1924800f26956e7d99c8bc24be099b) to solve the stated issue.
