### ISSUE TITLE
[Web] it does not function properly when wrapping by listview

### ISSUE THREAD

**Issue by buimanhhungit** [singerdmx/flutter-quill#200]
It does not function properly when wrapping by listview
Space, up, down, left, right key... not working.

This is my code.
![image](https://user-images.githubusercontent.com/51559988/116688417-dd917d00-a9e0-11eb-952c-7c6308387b08.png)

**Comment by GyuriMajercsik** [comment]
Please use GitHub's formatted code not images so that we can copy and try it locally.

**Comment by buimanhhungit** [comment]
`Scaffold(
        appBar: AppBar(
          title: Text('Application'),
        ),
        body: ListView(
          children: <Widget>[    

            Padding(
              padding: EdgeInsets.only(left: 8, right: 8, bottom: 8,top: 16),
              child: InputDecorator(
                decoration: InputDecoration(labelText: 'Introduction'),
                child: Container(
                  height: 400,
                  margin: EdgeInsets.symmetric(vertical: 16),
                  child: Column(
                    children: [
                      QuillToolbar.basic(controller: applicationProvider.controller),
                      Expanded(
                        child: Container(
                          child: QuillEditor(
                            scrollController: ScrollController(),
                            scrollable: true,
                            autoFocus: false,
                            expands: false,
                            padding: EdgeInsets.zero,
                            focusNode: FocusNode(),
                            controller: applicationProvider.controller,
                            readOnly: false,
                          ),
                        ),
                      )
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
        floatingActionButton: SpeedDial(
          // both default to 16
          marginEnd: 10,
          marginBottom: 20,
          animatedIcon: AnimatedIcons.menu_close,
          animatedIconTheme: IconThemeData(size: 22.0),
          // this is ignored if animatedIcon is non null
          // child: Icon(Icons.add),
          visible: true,
          // If true user is forced to close dial manually
          // by tapping main button and overlay is not rendered.
          closeManually: false,
          curve: Curves.bounceIn,
          overlayColor: Colors.black,
          overlayOpacity: 0.5,
          onOpen: () => print('OPENING DIAL'),
          onClose: () => print('DIAL CLOSED'),
          tooltip: 'Menu',
          backgroundColor: Colors.blue,
          foregroundColor: Colors.white,
          elevation: 8.0,
          shape: CircleBorder(),
          children: [
            SpeedDialChild(
                child: Icon(Icons.delete_forever),
                backgroundColor: Colors.red,
                label: 'Delete',
                labelStyle: TextStyle(fontSize: 18.0),
                labelBackgroundColor: isDark ? Colors.black87 : Colors.white,
                onTap: () {
                  applicationProvider.deleteApp();
                }),
            SpeedDialChild(
              child: Icon(Icons.save),
              backgroundColor: Colors.cyan,
              label: 'Save',
              labelStyle: TextStyle(fontSize: 18.0),
              labelBackgroundColor: isDark ? Colors.black87 : Colors.white,
              onTap: () {
                applicationProvider.save();
              },
            ),
          ],
        ),
      ),`

**Comment by GyuriMajercsik** [comment]
Do you have a `MaterialApp` in your app ? If so, did you override the shortcuts as I suggested ?

**Comment by buimanhhungit** [comment]
Yes, I have a materialappp... and i did override the shortcuts... but can
not..

Vào 15:26, T.7, 1 Th5, 2021 Gyuri Majercsik ***@***.***> đã
viết:

**Comment by GyuriMajercsik** [comment]
It is working for me. Please create an example app where you can reproduce it, one `main.dart` file containing everything.

**Comment by buimanhhungit** [comment]
I'm using Flutter 2.0. This is my code.


```

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:flutter_quill/widgets/controller.dart';
import 'package:flutter_quill/widgets/editor.dart';
import 'package:flutter_quill/widgets/toolbar.dart';
import 'package:permission20/login/loginNew.dart';
import 'package:provider/provider.dart';

import 'helper/AppData.dart';
import 'helper/JHelper.dart';
import 'home/profile/ProfileProvider.dart';

main() {
  checkPlatform();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);

    return GestureDetector(
      onTap: () {
        hideKeyBoard();
      },
      child: MultiProvider(
        providers: [
          ChangeNotifierProvider<ProfileProvider>(
            create: (_) => ProfileProvider(),
          ),
        ],
        child: Builder(
          builder: (context) {
            ProfileProvider profileProvider = Provider.of(context);

            return MaterialApp(
              shortcuts: ignoredNavigationShortcuts(),
              navigatorKey: keyNavigator,
              debugShowCheckedModeBanner: false,
              theme: isDark ? profileProvider.darkTheme : profileProvider.lightTheme,
              home: ListView(
                children: <Widget>[

                  Padding(
                    padding: EdgeInsets.only(left: 8, right: 8, bottom: 8,top: 16),
                    child: InputDecorator(
                      decoration: InputDecoration(labelText: 'Introduction'),
                      child: Container(
                        height: 400,
                        margin: EdgeInsets.symmetric(vertical: 16),
                        child: Column(
                          children: [
                            QuillToolbar.basic(controller: QuillController.basic()),
                            Expanded(
                              child: Container(
                                child: QuillEditor(
                                  scrollController: ScrollController(),
                                  scrollable: true,
                                  autoFocus: false,
                                  expands: false,
                                  padding: EdgeInsets.zero,
                                  focusNode: FocusNode(),
                                  controller: QuillController.basic(),
                                  readOnly: false,
                                ),
                              ),
                            )
                          ],
                        ),
                      ),
                    ),
                  ),
                ],
              ),
              // home: HomePortal(),
              // builder: EasyLoading.init(),
            );
          },
        ),
      ),
    );
  }
}


Map<LogicalKeySet, Intent> ignoredNavigationShortcuts() {
  Map<LogicalKeySet, Intent> shortcuts = Map.from(WidgetsApp.defaultShortcuts);
  if (kIsWeb) {
    shortcuts.remove(LogicalKeyboardKey.space);
    shortcuts.remove(LogicalKeyboardKey.arrowUp);
    shortcuts.remove(LogicalKeyboardKey.arrowDown);
    shortcuts.remove(LogicalKeyboardKey.arrowLeft);
    shortcuts.remove(LogicalKeyboardKey.arrowRight);
  }
  return shortcuts;
}
```

**Comment by buimanhhungit** [comment]
/Users/hungbuimanh/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H1030 darwin-x64, locale en)
    • Flutter version 2.0.5 at /Users/hungbuimanh/flutter
    • Framework revision adc687823a (2 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hungbuimanh/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
Process finished with exit code 0

**Comment by GyuriMajercsik** [comment]
Please use the following method: 

```
Map<LogicalKeySet, Intent> ignoredNavigationShortcuts() {
  Map<LogicalKeySet, Intent> shortcuts = Map.from(WidgetsApp.defaultShortcuts);
  if (kIsWeb) {
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.space));
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowUp));
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowDown));
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowLeft));
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowRight));
  }
  return shortcuts;
}
```

**Comment by buimanhhungit** [comment]
Thanks. It's working.

**Comment by buimanhhungit** [comment]
I'm using the following method. It's working also


```
Map<LogicalKeySet, Intent> ignoredNavigationShortcuts() {
  Map<LogicalKeySet, Intent> shortcuts = Map.from(WidgetsApp.defaultShortcuts);
  if (kIsWeb) {
    // shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.space));
    // shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowUp));
    // shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowDown));
    // shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowLeft));
    // shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowRight));
    shortcuts[LogicalKeySet(LogicalKeyboardKey.space)] = ActivateIntent();
    shortcuts[LogicalKeySet(LogicalKeyboardKey.arrowUp)] = ActivateIntent();
    shortcuts[LogicalKeySet(LogicalKeyboardKey.arrowDown)] = ActivateIntent();
    shortcuts[LogicalKeySet(LogicalKeyboardKey.arrowLeft)] = ActivateIntent();
    shortcuts[LogicalKeySet(LogicalKeyboardKey.arrowRight)] = ActivateIntent();
  }
  return shortcuts;
}
```

**Comment by buimanhhungit** [comment]
I have found the link https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart.
Share it with anyone need

**Comment by Uni2K** [comment]
> 
> 
> Please use the following method:
> 
> ```
> Map<LogicalKeySet, Intent> ignoredNavigationShortcuts() {
>   Map<LogicalKeySet, Intent> shortcuts = Map.from(WidgetsApp.defaultShortcuts);
>   if (kIsWeb) {
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.space));
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowUp));
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowDown));
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowLeft));
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowRight));
>   }
>   return shortcuts;
> }
> ```

This won't work with the master version of Flutter Web, since the return of defaultShortcuts is different (now objects).
So, basically you need to remove the shortcuts using the keyLabel.


```
Map<ShortcutActivator, Intent> ignoredNavigationShortcuts() {
    Map<ShortcutActivator, Intent> shortcuts =
        Map.from(WidgetsApp.defaultShortcuts);
    shortcuts.removeWhere((key, value) {
      return key.triggers.first.keyLabel ==
              LogicalKeyboardKey.arrowUp.keyLabel ||
          key.triggers.first.keyLabel ==
              LogicalKeyboardKey.arrowDown.keyLabel ||
          key.triggers.first.keyLabel ==
              LogicalKeyboardKey.arrowLeft.keyLabel ||
          key.triggers.first.keyLabel ==
              LogicalKeyboardKey.arrowRight.keyLabel ||
          key.triggers.first.keyLabel == LogicalKeyboardKey.space.keyLabel;
    });

    return shortcuts
  }
```

**Comment by Gagoo** [comment]
> Please use the following method:
> 
> ```
> Map<LogicalKeySet, Intent> ignoredNavigationShortcuts() {
>   Map<LogicalKeySet, Intent> shortcuts = Map.from(WidgetsApp.defaultShortcuts);
>   if (kIsWeb) {
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.space));
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowUp));
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowDown));
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowLeft));
>     shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowRight));
>   }
>   return shortcuts;
> }
> ```

Thank you @GyuriMajercsik, saved my day !

**Comment by reke592** [comment]
in my case
```
  Map<ShortcutActivator, Intent> myAppShortcuts() {
    Map<ShortcutActivator, Intent> shortcuts = Map.from(WidgetsApp.defaultShortcuts);
    if (kIsWeb) {
      shortcuts.clear();
    }
    
    return shortcuts;
  }
```
