### ISSUE TITLE
Most Font Families Are Showing No Effect on New/Selected Text

### ISSUE THREAD

**Issue by SalhabNoman** [singerdmx/flutter-quill#2003]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.15

### Steps to reproduce

1. Write Text.
2. Select Text.
3. Change Font Family to Any of (Ibarra Real Nova, SquarePeg, Nunito, Pacifico, Roboto Mono).
4. Nothing Happens.

### Expected results

For The Selected/Newly Added Text to Have The Chosen Font Family. 

### Actual results

No Change At All.

### Code sample

No Code Sample Available.

**Comment by CatHood0** [comment]
You have these Fonts installed on your pubspec.yaml?
