### ISSUE TITLE
Change course color

### ISSUE THREAD

**Issue by adrianHerreraa** [singerdmx/flutter-quill#2007]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How can I change the cursor color?
It appears purple.

**Comment by adrianHerreraa** [comment]
Sorry, I found the solution, I leave it here in case someone else needs it:

```
textSelectionThemeData: TextSelectionThemeData(
          cursorColor: Colors.white,
        ),
```

**Comment by EchoEllet** [comment]
> Sorry, I found the solution, I leave it here in case someone else needs it:
> 
> ```
> textSelectionThemeData: TextSelectionThemeData(
>           cursorColor: Colors.white,
>         ),
> ```

Thank you for the report.

We should document the library at some point, using either GitHub wikis or a docs website.

**Comment by adrianHerreraa** [comment]
> > Lo siento, encontré la solución, la dejo aquí en caso de que alguien más la necesite: > > ``` > > textSelectionThemeData: TextSelectionThemeData( > > cursorColor: Colores.blanco, > > ), > > ``` > > Gracias por el informe. > > Deberíamos documentar la biblioteca en algún momento, utilizando wikis de GitHub o un sitio web de documentos. 


Thank you very much. I would like to help with the documentation, send me a message if you need a hand.
