### ISSUE TITLE
Always add new line when open screen contains block flutter quill

### ISSUE THREAD

**Issue by viet-tran-0159** [singerdmx/flutter-quill#2015]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I open screen contains block flutter quill and it always add new line, after i convert it to html and save, if action perform continoustly, block extend the height as image i show

Is there any way to fix the fact that it always goes down 1 line when opened?

Thank you everyone

![image](https://github.com/user-attachments/assets/4f870140-8a23-48eb-92c0-222638d6837a)

**Comment by CatHood0** [comment]
Which version of flutter quill are you using?

**Comment by viet-tran-0159** [comment]
@CatHood0 it always add "\n" when flutter quill render

**Comment by CatHood0** [comment]
I already know where is the issue. I'll make a PR soon to fix this
