### ISSUE TITLE
Unable to submit PR, build for web fails

### ISSUE THREAD

**Issue by AtlasAutocode** [singerdmx/flutter-quill#2019]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.20

### Steps to reproduce

Run before_push.sh
cd example
flutter build web --release --dart-define=CI=true
Fails

### Expected results

To be able to compile for web to submit a PR.

### Actual results

> cd example
> flutter build web --release --dart-define=CI=true

Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
Error: Couldn't resolve the package 'printing' in 'package:printing/printing_web.dart'.
.dart_tool/flutter_build/5cd7aab0e629905740c94de93388d24d/web_plugin_registrant.dart:16:8:
Error: Not found: 'package:printing/printing_web.dart'
import 'package:printing/printing_web.dart';
       ^
.dart_tool/flutter_build/5cd7aab0e629905740c94de93388d24d/web_plugin_registrant.dart:32:3:
Error: Undefined name 'PrintingPlugin'.
  PrintingPlugin.registerWith(registrar);
  ^^^^^^^^^^^^^^
Error: Compilation failed.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
Do you run first flutter clean? I think it could be some remaining file that was left in `.dart_tool` and is causing you problems

**Comment by EchoEllet** [comment]
Same issue in #2009, you need to use conditional import to import packages that's specific to wrb, such as `web` (which is the new package alternative to support Wasm)

See usages of this as an example: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions/lib/utils/dart_ui

**Comment by AtlasAutocode** [comment]
> Do you run first flutter clean? I think it could be some remaining file that was left in .dart_tool and is causing you problems

Ran flutter clean and did not solve the problem.

> Similar to the issue in https://github.com/singerdmx/flutter-quill/pull/2009, you need to use conditional import

I'm sorry, I don't understand. This is my clone of the main flutter_quill repository updated to 9.5.20. I am trying to compile the flutter-quill example app (using before_push script). If I modify the build command for windows, it compiles OK, but web does not and gives the missing package error.
How do I modify the example app or before_push.sh to cope with web?
I could not find any reference to the package in flutter_quill.

**Comment by EchoEllet** [comment]
> How do I modify the example app or before_push.sh to cope with web?
I could not find any reference to the package in flutter_quill.

There seems to be an issue with building the app on the web. The issue is coming from `flutter_quill`, so changes in `before_push` or the example are not needed.

We just need a type safe way to import web or non-web specific packages correctly with conditional imports.
