### ISSUE TITLE
[Mobile] style reset when keyboard auto suggest text

### ISSUE THREAD

**Issue by WingCH** [singerdmx/flutter-quill#202]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here.

keyboard: Gboard
Android: 11

Reproduce Step
1. run `example`
2. select `red` color
3. input Wrong word, for example `appla`
4. click `enter` go to next line
5. keyboard will auto fix word to `apple`
6. `appl` is red color, `e` is blank color

The same problem will not only appear in `color`, `bold`etc also have

Demo video:

https://user-images.githubusercontent.com/19588517/116811273-12393c00-ab7b-11eb-9636-cde7cec7168b.mp4

**Comment by singerdmx** [comment]
Cannot repro
Maybe issue is gone
