### ISSUE TITLE
No cursor is showing after typing

### ISSUE THREAD

**Issue by viet-tran-0159** [singerdmx/flutter-quill#2022]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

The cursor is simply disappearing after I start typing as shown in the attached video clip

https://github.com/user-attachments/assets/0dfc6eac-510d-451a-a15c-ebb3e2ea6ec1

**Comment by CatHood0** [comment]
Can you provide any reproducible example of code and the version that are you using of it?

**Comment by viet-tran-0159** [comment]
@CatHood0 
I will provide more images and example code, looking forward to receiving your help. Thank you 

This is my example of code:
class CommonBlockHeading extends StatefulWidget {
  CommonBlockHeading({super.key, this.text, this.styleModel});

  String? text;
  StyleModel? styleModel;

  @override
  State<CommonBlockHeading> createState() => _CommonBlockHeadingState();
}

class _CommonBlockHeadingState extends State<CommonBlockHeading> {
  QuillController controller = QuillController.basic();

  @override
  void initState() {
    controller = QuillController(
      document: Document.fromDelta(
        Delta().htmlToDelta(widget.text ?? ''),
      ),
      selection: const TextSelection.collapsed(offset: 0),
    );
    super.initState();
    controller.document.changes.listen((docChange) {
      _onTextChanged();
    });
  }

  void _onTextChanged() {
    var temp = QuillDeltaToHtmlConverter(
      controller.document.toDelta().toJson(),
      ConverterOptions()..sanitizerOptions.allow8DigitHexColors = true,
    ).convert();
    temp = temp.parseHtml(temp);
    widget.text = temp;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
          borderRadius: const BorderRadius.all(Radius.circular(DimensRes.sp5)),
          border: Border.all(
            width: 1,
            color: ColorsRes.borderGray,
          )),
      child: Column(
        children: [
          QuillToolbar.simple(
            configurations: QuillSimpleToolbarConfigurations(
              showDividers: true,
              showUnderLineButton: true,
              showStrikeThrough: true,
              showColorButton: true,
              fontSizesValues: const {
                '8pt': '8.0',
                '9pt': '9.0',
                '10pt': '10.0',
                '11pt': '11.0',
                '12pt': '12.0',
                '14pt': '14.0',
                '16pt': '16.0',
                '18pt': '18.0',
                '20pt': '20.0',
                '22pt': '22.0',
                '24pt': '24.0',
                '30pt': '30.0',
                '36pt': '36.0',
                '48pt': '48.0',
                '60pt': '60.0',
                '72pt': '72.0',
                '96pt': '96.0',
              },
              showFontSize: true,
              showBackgroundColorButton: true,
              showClearFormat: true,
              showAlignmentButtons: true,
              showLeftAlignment: true,
              showCenterAlignment: true,
              showRightAlignment: true,
              showHeaderStyle: true,
              showListNumbers: true,
              showListBullets: true,
              showLink: true,
              decoration: const BoxDecoration(
                  borderRadius: BorderRadius.only(
                topRight: Radius.circular(DimensRes.sp5),
                topLeft: Radius.circular(DimensRes.sp5),
              )),
              controller: controller,
            ),
          ),
          Container(
            color: ColorsRes.borderGray,
            width: double.infinity,
            height: 1,
          ),
          Padding(
            padding: const EdgeInsets.all(DimensRes.sp5),
            child: ConstrainedBox(
              constraints: const BoxConstraints(
                minHeight: DimensRes.sp140,
              ),
              child: QuillEditor.basic(
                configurations: QuillEditorConfigurations(
                  controller: controller,
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
}
![image](https://github.com/user-attachments/assets/d5987e05-c1ca-491d-bb58-b945216fa19f)

**Comment by CatHood0** [comment]
I'll take a look about  it

**Comment by viet-tran-0159** [comment]
@CatHood0 Have you solved this problem yet?
I see that if it (flutter quill) is an element of ReorderableListView, it will not have this cursor error? I do not know why?

Example of code:
IconButton(
                            onPressed: () {
                              setState(() {
                                if (isClickHeading == true) {
                                  _items.insert(0, {
                                    0: CommonBlockHeading(),
                                  });
                                  updateValueKey();
                                }
                                 });
                            },
 Visibility(
                          visible: _items.isNotEmpty,
                          child: ReorderableListView.builder(
                            shrinkWrap: true,
                            physics: const NeverScrollableScrollPhysics(),
                            itemBuilder: (BuildContext context, int index) {
                              return buildContent(index);
                            },
                            itemCount: _items.length,
                            onReorder: (int oldIndex, int newIndex) {
                              if (_items.length > 1) {
                                setState(
                                  () {
                                    if (oldIndex < newIndex) {
                                      newIndex -= 1;
                                    }
                                    final item = _items.removeAt(oldIndex);
                                    _items.insert(newIndex, item);
                                    updateValueKey();
                                  },
                                );
                              }
                            },
                          ),
                        ),

**Comment by viet-tran-0159** [comment]
I have solved this problem
Here's the solution if you have the same problem as me

In QuillEdtior.basic, you need to set focusNode.
Example of code:
FocusNode _myFocusNode = FocusNode();
QuillEditor.basic(
                      focusNode: _myFocusNode ,
                      configurations: QuillEditorConfigurations(
                        controller: _myController,
                      ),
                    ),
