### ISSUE TITLE
how to implement codox.io realtime collabration tool  in flutter quill editor 

### ISSUE THREAD

**Issue by sathis008** [singerdmx/flutter-quill#2024]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

how to implement codox.io realtime collabration tool  in flutter quill editor

**Comment by CatHood0** [comment]
You'll need to make your on integration since this is a external tool that isn't a standard of Quill Js.

You can take this [video](https://www.youtube.com/watch?v=0_GJ1w_iG44) as an example.
