### ISSUE TITLE
Disable  user input empty content like `<p><br><br></p>` .

### ISSUE THREAD

**Issue by toknT** [singerdmx/flutter-quill#2030]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

Disable  user input empty content .

### Proposal

```dart
QuillEditor.basic(allowEmptyContent:false)
```

**Comment by CatHood0** [comment]
I don't know what are you meaning. Can you provide more information avoid this?
