### ISSUE TITLE
How to customize the distance between buttons in QuillToolbar？

### ISSUE THREAD

**Issue by 2426232528** [singerdmx/flutter-quill#2038]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How to customize the distance between buttons in QuillToolbar？

**Comment by singerdmx** [comment]
This is not be exposed I think

**Comment by AtlasAutocode** [comment]
My first thought was you would need to build a custom toolbar.
While exploring how to do that, I stumbled upon a configuration option:

Look at QuillSimpleToolbarConfigurations
It has options like:  toolbarSectionSpacing and toolbarRunSpacing
These appear to be used when using the toolbar with multiRowsDisplay=true (default) and are used to control the Wrap widget that contains the buttons.

I have no idea what these do - perhaps you could try them and let us know?

**Comment by AtlasAutocode** [comment]
I can confirm that QuillSimpleToolbarConfigurations.toolbarSectionSpacing adjusts the toolbar spacing.
