### ISSUE TITLE
[Mobile] How to theme code block?

### ISSUE THREAD

**Issue by pavel-birdy** [singerdmx/flutter-quill#204]
My issue is about [Mobile]

Thanks for maintaining the library. I couldn’t change the background color.  It looks ugly with my theme. 

![Screenshot_1619998984](https://user-images.githubusercontent.com/53362329/116831864-8f8e9c00-abcf-11eb-99f9-a740e008e43a.png)
![Screenshot_1619999045](https://user-images.githubusercontent.com/53362329/116831866-97e6d700-abcf-11eb-85f7-9c6afcf4329b.png)

**Comment by singerdmx** [comment]
If you check out our demo app, background color works fine

![image](https://user-images.githubusercontent.com/122956/116832054-01cb9600-ab68-11eb-835c-8bf8ed9f93d9.png)

**Comment by pavel-birdy** [comment]
I don't see any background color property in `QuillEditor` my problem is only with code block the screenshot you shared I don't see any code block. What I am missing?

**Comment by friebetill** [comment]
The `QuillEditor` has an attribute `customStyles`, where you can pass your own `DefaultStyle`, e.g.:
```dart
QuillEditor(
  /* ... */
  customStyles: DefaultStyles(
    code: DefaultTextBlockStyle(
      DefaultTextStyle.of(context).copyWith(
        color: Colors.blue,
      ),
      Tuple2<double, double>(6, 0),
      const Tuple2(0, 0),
      BoxDecoration(
        color:  Theme.of(context).brightness == Brightness.light
            ? Colors.blueGrey.shade50
            : Colors.blueGrey.shade900,
        borderRadius: BorderRadius.circular(2),
      ),
    ),
  ),
  /* ... */
);
```
