### ISSUE TITLE
Selection menu doesn't display after drag

### ISSUE THREAD

**Issue by mtallenca** [singerdmx/flutter-quill#2046]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.0.2

### Steps to reproduce

1. Create a note with lots of text.
2. Long press a word 
3. Drag one of the selection handles
4. End the drag

### Expected results

I'm expecting the selection menu to reappear after the drag is finished.

### Actual results

The selection menu does not reappear.  So after selecting text, no way to cut/copy.

**Comment by CatHood0** [comment]
@demoYang can you take a look about this?

**Comment by mtallenca** [comment]
FYI - testing possible fix at https://github.com/mtallenca/flutter-quill/commit/da42d0110ca66d1bf26f6ae488f79d38a5a78ce9

**Comment by CatHood0** [comment]
> FYI - testing possible fix at https://github.com/mtallenca/flutter-quill/commit/da42d0110ca66d1bf26f6ae488f79d38a5a78ce9

You can make a PR with these changes

**Comment by erturkTranskriptor** [comment]
when this fix will be released ?
