### ISSUE TITLE
Why does flutter quill block always come before 1 character & How to set maximum character

### ISSUE THREAD

**Issue by viet-tran-0159** [singerdmx/flutter-quill#2047]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

![image](https://github.com/user-attachments/assets/6043a4a2-7808-4e34-93a4-f7aa997399e1)
its always counts 1 character after render bloc flutter quill

& how to set maximum?
I handled it like that:
void onDocumentChanged() {
    final documentLength = _headLineCtrl.document.length;

    if (documentLength > 500) {
      int latestIndex = 500 - 1;

      _headLineCtrl.replaceText(
        latestIndex,
        documentLength - 500,
        '',
        TextSelection.collapsed(offset: latestIndex),
      );
    } else {
      _eventDetailController.countHeading.value = documentLength;
    }
  }
  
  but i typing icon at position 499/500, it's bug: Invalid argument(s): string is not well-formed UTF-16

**Comment by AtlasAutocode** [comment]
I don't know if this answers your question, but it appears that a quill document is required to have at least 1 newline '\n' character at the end of the document. An empty document would then have a length of 1!
This could explain why your starting length is 1 and why you get an error if you try to delete that final newline character.

**Comment by viet-tran-0159** [comment]
@AtlasAutocode Thanks for explaining it to me, thank you , i won't count the last character
