### ISSUE TITLE
There are several unexpected behaviors, the person just wants to copy the text without formatting or with formatting and neither of them works

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#2052]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.23

### Steps to reproduce

write anything, put a background color

skip a line write something and put a color in the text

copy and paste everything written

### Expected results

text is copied with the same formatting or without formatting

### Actual results

the text style is all messed up

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

https://github.com/user-attachments/assets/e853ea6e-235b-4c6e-9c2f-fa8f119e859b

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by jonasbernardo** [comment]
inside the code, it says the following in quill_controller.dart
/// Clipboard caches last copy to allow paste with styles. Static to allow paste between multiple instances of editor.
This works, but only if the text has a one type of style if have more than one, copying the text with the style even disabling the style buttons after copying leaves everything messy

**Comment by CatHood0** [comment]
This seems the same confusion. You need to look the toolbar when you append a new line, you will notice of the `color` and `background` styles still are applied. On mobile devices the Clipboard just copy plain text

**Comment by CatHood0** [comment]
It's weird, Clipboard on mobile devices should just copy plain text

**Comment by CatHood0** [comment]
I couldn't reproduce your error.


https://github.com/user-attachments/assets/5587c7d1-2847-4bee-b50c-556603e06dea

**Comment by jonasbernardo** [comment]
I used this package with my own modifications, and the app copied with smooth formatting, even between several instances of Flutter Quill, but my modifications only worked until 9.3.9, after I merge them into the others it no longer works.

**Comment by CatHood0** [comment]
Then we can't help you, sorry. We just limit our work to contribute to this repository. We can't just focus into your implementation since is used only by you and is outdated with the current stable branch.

**Comment by jonasbernardo** [comment]
I could provide the code with the changes I made, I don't know how to fix this in the main version, would that be possible?
