### ISSUE TITLE
  Clipboard copy allow paste with styles and allow paste between multiple instances of editor in Android and IOS

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#2055]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

I don't have a solution, in an old version I made some random modifications that worked

### Proposal

When copying text that has a style, paste the text with the style and not just the text without a style, do this with the clipboard to make it possible to copy between instances of flutter quill

**Comment by singerdmx** [comment]
I don't think it is in scope of support
