### ISSUE TITLE
Document.FromHtml is shown as deprecated

### ISSUE THREAD

**Issue by adrianHerreraa** [singerdmx/flutter-quill#2059]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi, now it shows me Document.FromHtml as deprecated, it shows me the following message:

'fromHtml' is deprecated and should not be used. Experimental support for HTML conversion has been dropped and will be removed in future releases, consider using alternatives such as https://pub.dev/packages/flutter_quill_delta_from_html.

Try to replace the deprecated member usage with the replacement.dartdeprecated_member_use

Is this fixed by dartdeprecated_member_use alone, or is it an upgrade?

I appreciate your guidance, thank you.

**Comment by singerdmx** [comment]
@EchoEllet you have the answer?

**Comment by EchoEllet** [comment]
Thank you for the report, we have dropped the support for HTML, Markdown, and PDF support in #1997 with the list of alternatives.

Take a look at the package [flutter_quill_delta_from_html](https://pub.dev/packages/flutter_quill_delta_from_html).

I will close this issue though if you have more questions or issues, we can continue the conversation here or in a new thread.

**Comment by adrianHerreraa** [comment]
> Thank you for the report, we have dropped the support for HTML, Markdown, and PDF support in #1997 with the list of alternatives.
> 
> Take a look at the package [flutter_quill_delta_from_html](https://pub.dev/packages/flutter_quill_delta_from_html).
> 
> I will close this issue though if you have more questions or issues, we can continue the conversation here or in a new thread.



ok, I understand, now I see that I can convert html to delta, but how do I convert delta to html?

**Comment by EchoEllet** [comment]
>  how do I convert delta to html?

You can use the package [vsc_quill_delta_to_html](https://pub.dev/packages/vsc_quill_delta_to_html)

**Comment by adrianHerreraa** [comment]
> > how do I convert delta to html?
> 
> You can use the package [vsc_quill_delta_to_html](https://pub.dev/packages/vsc_quill_delta_to_html)



ahh, I understand, then the issue is with flutter_quill, where this is shown:
![Captura de pantalla 2024-07-23 a la(s) 12 42 16 p m](https://github.com/user-attachments/assets/3c36c202-9ca6-4056-aef5-77bcdc4714eb)


then that's why it shows me this?:
![Captura de pantalla 2024-07-23 a la(s) 12 46 07 p m](https://github.com/user-attachments/assets/974c42e8-6022-47c4-99ea-dbf919f00d0d)

![Captura de pantalla 2024-07-23 a la(s) 12 46 54 p m](https://github.com/user-attachments/assets/0198b284-30d4-49f2-ae96-451bb3efaacd)

**Comment by EchoEllet** [comment]
We previously have those packages as dependencies and expose a public API that depends on them.

> then that's why it shows me this?

Those experimental methods are deprecated for now and will be removed in a future breaking release.

**Comment by adrianHerreraa** [comment]
> Those experimental methods are deprecated for now and will be removed in a future breaking release.

ok, then I will be able to find it, or will there be a replacement?

**Comment by EchoEllet** [comment]
> ok, then I will be able to find it, or will there be a replacement?

You can use the following alternatives, the `flutter_quill` will no longer support HTML conversion 

- [`vsc_quill_delta_to_html`](https://pub.dev/packages/vsc_quill_delta_to_html): To convert **Delta**
   to HTML.
- [`flutter_quill_delta_from_html`](https://pub.dev/packages/flutter_quill_delta_from_html): To Convert **HTML** to **Delta**. This package is used internally in `flutter_quill` to support rich text pasting, if you want to use it functionalities, you can explicitly include it in uour `pubspec.yaml`
