### ISSUE TITLE
Should we use a simpler way to read the Flutter Qull documentation

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#2064]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

As @EchoEllet had mentioned in the [discussion](https://github.com/singerdmx/flutter-quill/discussions/2016), the current way of reading the documentation is a bit clunky and not all users might feel like it. reading between files with a Markdown format. In addition, it is often complicated to move from one file to another.

## What do I propose?

We could use some pages for documentation such as [GitBook](https://www.gitbook.com/) or Github Wiki or build a website designed especially for the documentation of the Flutter Quill.

_This point was also discussed in this [comment](https://github.com/singerdmx/flutter-quill/discussions/2016#discussioncomment-10055313)_

I can give as an example that I use GitBook (which allows Github to be synchronized with the platform in question) to create an example of how we could have a dedicated documentation page [here](https://flutter-quill.gitbook.io/flutter-quill-documentation)

**Comment by singerdmx** [comment]
@EchoEllet already started a gitbook

**Comment by EchoEllet** [comment]
> @EchoEllet already started a gitbook
> 

@CatHood0 already started it before me. I deleted the account since it was for experimenting purposes .

**Comment by singerdmx** [comment]
@CatHood0 please continue the gitbook. If you need anything from me or @EchoEllet , please let us know

**Comment by CatHood0** [comment]
Here's a link to convert to a member: https://app.gitbook.com/invite/G9ZKJjmLw8NP8ri0wLcW/OD27YhceFY5JeBzAIcMy

**Comment by CatHood0** [comment]
> Just a quick heads-up! Since you invited someone to your GitBook organization, you’ve surpassed the limits of our Free plan (1 user). We’ve automatically placed you on a 14-day trial of our Plus plan so you have some time to try some of the great collaboration features in GitBook.
> 
> At the end of the 14 days we’ll automatically move you back to the Free plan unless you’ve chosen to upgrade. Any additional members in your organization will no longer be able to contribute to your content. 

We should need to see others alternatives. Having one person for just modify or create documentation could make this process too slow.

**Comment by CatHood0** [comment]
Another alternative suggested by @EchoEllet could be create a page with [Kobweb](https://kobweb.varabyte.com/)

**Comment by EchoEllet** [comment]
Another alternative is [MkDocs](https://www.mkdocs.org/). Kobweb is meant for a full web application from scratch and requires more work before we start writing the docs, also it would require basic knowledge of Kotlin, JS, CSS, and HTML.

**Comment by CatHood0** [comment]
> obweb is meant for a full web application from scratch and requires more work before we start writing the docs, also it would require basic knowledge of Kotlin, JS, CSS, and HTML.

You have a point. Building a web application just for documentation with Kobweb will require too much time.

> Another alternative is [MkDocs](https://www.mkdocs.org/)

I'll take a look at it as soon as I have time. From what I've read and seen about MkDocs, it looks like a good free alternative.
