### ISSUE TITLE
toPlainText method from any Embeddable return text that cannot be used outside of the editor

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#2065]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I watch this code on [Line](https://github.com/singerdmx/flutter-quill/blob/master/lib/src/document/nodes/line.dart) class:
```dart
  int _getNodeText(Leaf node, StringBuffer buffer, int offset, int remaining) {
    final text = node.toPlainText();
    if (text == Embed.kObjectReplacementCharacter) {
      buffer.write(Embed.kObjectReplacementCharacter); 
      return remaining - node.length;
    }

    final end = math.min(offset + remaining, text.length);
    buffer.write(text.substring(offset, end));
    return remaining - (end - offset);
  }
```

It's really useful the `Embed` can be copied and paste multiple times, but, it's difficult if you have just a `CustomBlockEmbed` with just plainText and this text is not copied on the clipboard as plainText. I don't know if i already fully explain what is exactly the issue, then you can see this #2050 to undertand better this.

If you try to copy any `Embed` , you can see the text is just empty even the `Embed` contains data as `String` or the `toPlainText` from the `EmbedBuilder` is overrided. I fixed this partially adding this part of code:

```dart
    if (text == Embed.kObjectReplacementCharacter) {
      final nodeValue = node.value;
      if (nodeValue is Embeddable && !['video','image','custom','formula','table'].contains(nodeValue.type) && nodeValue.data != null && nodeValue.data is String) {
        buffer.write(nodeValue.data);
      } else {
        buffer.write(Embed.kObjectReplacementCharacter);
      }
      return remaining - node.length;
    }
```

But i prefer the root error. Could anyone suggest where should i take a look?

**Comment by CatHood0** [comment]
@EchoEllet  are you familiar with these parts of code?

**Comment by EchoEllet** [comment]
> @EchoEllet  are you familiar with these parts of code?

I didn't work on them, and I was planning to before. I moved some parts to different files for organization.

**Comment by CatHood0** [comment]
> I didn't work on them, and I was planning to before

I fix partially to copy just the plain text for custom embeds, but, this could break the feature that let the editor paste the Embeds to the editor

**Comment by singerdmx** [comment]
`toPlainText` is more of debugging purpose like dumping the log

**Comment by singerdmx** [comment]
Copy/paste embed was not supported in the beginning. This is more of enhancement.
And you don't have to rely on `toPlainText` method to do that.
I mean you can either change the behavior of `toPlainText` or just create some new method.

**Comment by CatHood0** [comment]
> I mean you can either change the behavior of toPlainText or just create some new method.

At this case, the OP has a issue where he cannot copy the plain text from him custom implementation of a `Embeddable`. I try to see if there's a issue on toPlainText but seems this cannot be the case.

**Comment by singerdmx** [comment]
Honestly copy/paste was barely working in the beginning, let alone copy/paste embed.
I suggest to deal with this problem with a new method instead of using `toPlainText`

**Comment by CatHood0** [comment]
> I suggest to deal with this problem with a new method instead of using `toPlainText`

I will try to do this. Thanks for the suggestion

**Comment by singerdmx** [comment]
If we can get copy/paste of embed working, it would be a significant new feature

**Comment by singerdmx** [comment]
@CatHood0 `toPlainText` returns string. I wonder if we should define a method that returns more than just string since string is pretty limited in the info it can convey.

**Comment by CatHood0** [comment]
I added a method to make the same but need to ve overrided by the developer to get custom data, but, this isn't working. I don't know why any custom embeddable doesn't have the functions that i overrided

**Comment by singerdmx** [comment]
Maybe @EchoEllet knows

**Comment by CatHood0** [comment]
I'm thinking the option where we could have a service (like Clipboard) to this new feature to make more easy extend from it or just override the default operations
