### ISSUE TITLE
Delta displays wrong colour in text input screen 

### ISSUE THREAD

**Issue by JamesAllgood** [singerdmx/flutter-quill#2069]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.1.0

### Steps to reproduce

The following delta data doesn't display its colours correctly in the text input screen 

Use the following code to setup a text display for quill and it sets the text to the wrong colours 

### Expected results

"This is just pink" should have pink text colour 

"this is just blue" should be blue text colour 

### Actual results

The colour blue is only display and that's for the first item. Not the second that is actually blue?

![Screenshot 2024-07-25 at 19 53 42](https://github.com/user-attachments/assets/8c05a14c-ab94-4df0-8315-0a0bf6ff4cd7)

### Code sample

<details><summary>Code sample</summary>

```dart
      final deletadata = Delta()
        ..insert('This is just pink ', {"color": "#F06292FF"})
        ..insert('\n\n')
        ..insert( "This is just blue", {"color": "#4DD0E1FF"})
        ..insert('\n');
      _quillController.document = Document.fromDelta(deletadata);
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
I don't really know why this could be happening. The part encharged to parse any `String` to `Flutter Color` is [this](https://github.com/singerdmx/flutter-quill/blob/master/lib/src/common/utils/color.dart):   
```dart
var hex = s.replaceFirst('#', '');
  hex = hex.length == 6 ? 'ff$hex' : hex;
  final val = int.parse(hex, radix: 16);
  return Color(val);
```

**Comment by JamesAllgood** [comment]
Its strange because if you swaped the lines around the colour swaps. 

almost like its only taking the last colour seen and setting that

**Comment by AtlasAutocode** [comment]
I think the problem might be that colors are expressed as ARGB whereas your values are RGBA.

#4DD0E1FF is red=D0, green=E1, blue=FF with an opacity of 4D - that is a very pale blue.

If you use #FFF06292 you get pink and with #FF4DD0E1 you get blue

**Comment by JamesAllgood** [comment]
That makes sense! 

When saving the delta to html its saving as 8bit colour mode. 

Is there a way for the quill code to account for both ARGB and RGBA I guess?

**Comment by AtlasAutocode** [comment]
Can't help you with html.
I suggest you look at the code you are using to convert delta to html and then html to delta.
One of them is flipping the byte order, or not flipping when it should.
