### ISSUE TITLE
Mobile - Is it possible to create an InlineEmbed class?

### ISSUE THREAD

**Issue by luscuissiatto** [singerdmx/flutter-quill#207]
I use [this package](https://github.com/afry/quill-mention) in the web version and wanted to continue using the same structure in the mobile app.

It generates the following structure:
`{"insert":{"mention":{"id":"1","value":"Basil","denotationChar":"@"}}}`

**Comment by WWLy** [comment]
I have the same question. Can anyone answer it? I don’t want add '\n'.

**Comment by singerdmx** [comment]
Mention is a big feature 
PR is welcome

**Comment by ketan10592** [comment]
@[luscuissiatto] check my example here, I have add Mention feature in this example.
<img width="445" alt="Screenshot 2022-05-02 at 6 00 32 PM" src="https://user-images.githubusercontent.com/60574739/166249980-ec81ab14-0f42-475a-ba8a-62131b99de1e.png">
