### ISSUE TITLE
Font Size  and font item color on tool bar

### ISSUE THREAD

**Issue by chileanne** [singerdmx/flutter-quill#2070]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

the defaull item color does not change the color of all items. it only changes the color of the last item

**Comment by CatHood0** [comment]
Can you provide any video or example? Your description doesn't explain too much about your issue

**Comment by chileanne** [comment]
<img width="1440" alt="Screenshot 2024-07-25 at 8 39 47 PM" src="https://github.com/user-attachments/assets/b67eb88f-bf72-45d0-9737-25178b741374">
<img width="1440" alt="Screenshot 2024-07-25 at 8 39 58 PM" src="https://github.com/user-attachments/assets/0eb41ec0-0474-4b20-957f-ab7fe293185a">

when i click on the font size or font icons , the bottom modal that appears  is always white and the color of the items cannot be changed

**Comment by chileanne** [comment]
<img width="1440" alt="Screenshot 2024-07-25 at 8 39 47 PM" src="https://github.com/user-attachments/assets/ee7c1bd8-01bb-4173-86b2-9a2a1678e798">
<img width="1440" alt="Screenshot 2024-07-25 at 8 39 58 PM" src="https://github.com/user-attachments/assets/015117b6-b7b0-499c-86c4-758b1e05767f">

**Comment by CatHood0** [comment]
Are you using a custom theme for you.example? I guess this could be your issue

**Comment by chileanne** [comment]
yh you correct, thanks. 

A big thank you for this package
