### ISSUE TITLE
I would like copying and pasting text with formatting on Android and iOS

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#2072]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

copy and paste with formatting between different instances of flutter quill

**Comment by AtlasAutocode** [comment]
This should work. I assume your different instances of flutter quill are within the same app?
Are you using the latest version?
I am currently working to fix a problem with copying multiple line selections with attributes which is broke.
Can you provide more information on what your problem is?

**Comment by jonasbernardo** [comment]
Yes, I have several instances on the same screen in the same app
That's exactly the problem copying multiple line selections with attributes

**Comment by AtlasAutocode** [comment]
Good.
The current behavior applies the styles for the whole selection to **each line** of the pasted text which results in some really weird output.
I have fixed that, but the positioning of the caret after paste is not being calculated correctly.

**Comment by jonasbernardo** [comment]
I made some changes to a previous version and it works, but I don't really understand what I did to make it work, these changes I made work until version 9.3.9, after changes made in version 9.3.10 it no longer works

**Comment by jonasbernardo** [comment]
I think this calculation was changed in this version 9.3.10, could you take a look at the changes that were made in this version, maybe you can get something that can be used

**Comment by jonasbernardo** [comment]
Look at the code in the line.dart file, quillcontroller.dart and raw_editor_state.dart, I think it was these changes that broke it
https://github.com/singerdmx/flutter-quill/commit/1a4109fb7a56859ec95a28ca4350ead409294efe
