### ISSUE TITLE
Unexpected paste as HTML

### ISSUE THREAD

**Issue by AtlasAutocode** [singerdmx/flutter-quill#2073]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.0.9

### Steps to reproduce

Start the example app and select 'Empty'.
Type in any text.

In Android Studio select some simple plain text and copy to the clipboard.
Paste into the quill editor.

### Expected results

The plain text that was copied to the clipboard

### Actual results

Text appears with the code-block attribute

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Additional Context

Editor shows 'updateEditor' text in a CodeBlock attribute:
![HTML Paste as codeblock](https://github.com/user-attachments/assets/e5330aeb-248b-4f61-9f65-efb4c37a2173)

Content of clipboard:
```
<html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"></head><body><div style="background-color:#ffffff;color:#000000"><pre style="font-family:'JetBrains Mono',monospace;font-size:9.8pt;">updateEditor</pre></div></body></html>
```

**Comment by CatHood0** [comment]
But the code block is applied.

**Comment by CatHood0** [comment]
The image already shows the text in a code-block, but if you are wondering why is not showing the line number, it is because the line number appears below the text for some reason (i see this display error since the version 9.3.0)

**Comment by AtlasAutocode** [comment]
> The image already shows the text in a code-block, but if you are wondering why is not showing the line number, it is because the line number appears below the text for some reason (i see this display error since the version 9.3.0)

Yes, it's been on my list to fix for a while - never get the time!
Another oddity - if you add an ordered list after it, the list starts with 2. (code block is 1. - there is a configuration to suppress line numbers in code block)

> But the code block is applied.

That's the point. Why is the code block applied when I paste in plain html?
Another thing I noticed: if you select **#2307** on a browser (I copied an issue number including the #) and copy/paste then the text appears in color.

**Comment by CatHood0** [comment]
> Why is the code block applied when I paste in plain html?

I'm unfamiliar with how works the Clipboard pasting feature. @EchoEllet knows better about it

**Comment by AtlasAutocode** [comment]
This is caused by the processing of the <pre> tag which is converted to the code-block attribute.
Since HTML import by Flutter-Quill is deprecated, I am closing this issue.

**Comment by CatHood0** [comment]
This is a feature from the `Clipboard` that check if the text that will be pasted is HTML and transform it using my package `flutter_quill_delta_from_html`. The same thing happens with `Markdown` (as far i know)

**Comment by AtlasAutocode** [comment]
I think the whole matter of clipboard pasting is subject to debate and is on my list to look into when I get some free time.
Others have requested a 'paste as plain text' option, and this is what is probably needed.

In this case, I thought I was just copying a couple of words of plain text and was surprised that Android Studio also copied HTML text which gave the surprising result. I think the only question is: should \<pre> be converted to code-block attribute or ignored? I leave that to your better judgement.

Word processors have a 'paste as plain text' option, and I am beginning to understand why.
