### ISSUE TITLE
Custom content cannot be searched.

### ISSUE THREAD

**Issue by lingyun000** [singerdmx/flutter-quill#2075]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

<img width="810" alt="352365054-713b593a-caaf-4e71-aaba-67a30c6490b1" src="https://github.com/user-attachments/assets/d6ba2bd1-bf60-49bd-a0a4-3716202fd68a">

**Comment by AtlasAutocode** [comment]
This is a good question and one I should be asking myself shortly!

@lingyun000 have you overridden 'toPlainText' in your EmbedBuilder? I suspect this would be the only way to allow text search of the content of Embed nodes.

**Comment by lingyun000** [comment]
No, I haven't overridden 'toPlainText'. Can you provide a reference example?

**Comment by AtlasAutocode** [comment]
At present, the search function does not have any way of accessing the content of embedded objects.

It is possible to add code to search within an embed using an override to the toPlainText method.
The difficulty is going to be how to show the user what the selection for the search hit is.

Your example shows a simple '123' text. If I search for '23' what is expected?

1. The easiest is to select the whole embedded object which is misleading as you did not search for '123'
2. You would probably prefer to show a highlight covering '23'. The editor has no way to do this, so the only way would be to require you to handle the selection and store the selection in your data (ugh!)

A more complex example is an image embed where the data is the path to the file and is not visible to the user. I would want to search for a part of the filename, but what do I show for the selection?

There are probably other ways of solving the problem which (hopefully) will become obvious in due course....

Example:
```
class MyEmbedBuilder extends EmbedBuilder {
  @override
  String toPlainText(Embed node) {
    /// Optional: verify it really is our Embed
    assert ( node.value.type == MyBlockEmbed.nodeType);
    /// Convert generic node to our type
    final m = MyBlockEmbed(node.value.data);
    /// Use MyBlockEmbed to access what I want to be used for search
    return  m.name;  // or: m.data or whatever
  }

```

I am most interested in your thoughts about how to handle searching within custom content.

**Comment by lingyun000** [comment]
I don't have a good idea either. 
Expose the content that can be searched in the custom component and display the number on the custom component.

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/51d5ff89-2370-41bd-a2a3-e6217a71f243">

**Comment by AtlasAutocode** [comment]
I've submitted a PR.
Please refer to the documentation for how to enable search.
(Link will be available when PR is merged: https://github.com/singerdmx/flutter-quill/blob/master/doc/configurations/search.md)
You should be notified when PR posts and this issue will be closed.
