### ISSUE TITLE
Toggle State Freezes on New Line without Text in Flutter Quill

### ISSUE THREAD

**Issue by Gabianne01** [singerdmx/flutter-quill#2077]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.1.2

### Steps to reproduce

1. Initialize a Flutter Quill editor with a toolbar containing ToggleStyleButton for list and/or alignment styles.
2. Toggle an alignment style (e.g., center alignment).
3. Add some text.
4. Press enter to create a new line without typing any text.
5. Attempt to toggle to a different alignment style (e.g., left alignment).

### Expected results

The toggle button should correctly reflect the new alignment style when toggled, even on a new line without text.

### Actual results

The toggle state remains frozen, showing the previously selected style, and does not update to reflect the new selection, unless there is typed text. 

### Code sample

///

### Additional Context

The preserve style on new line is set to true. I also tried downgrading the flutter quill version, which also did not help.

Environment:

Flutter version: 3.22
flutter_quill version: 10.1.2
OS: Android
![Flutter_quill_toggle_style_alignment-list-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/b312122e-8569-43e4-92c9-046dfa512d90)

**Comment by AtlasAutocode** [comment]
Confirmed.
This also applies to switching between different list types.
Have you found any other situation where this occurs?
I have a tentative fix, just need to test to see what else needs fixing.

**Comment by Gabianne01** [comment]
Thank you for your quick answer. It appears that the toggle freezing issue only affects the groups that are switchable, specifically the list and alignment groups. The standalone toggle buttons, such as bold, italic, font sizes, font families, text color, and background color, are updating the styles correctly.

In the case of lists and alignment, even though switching between the styles doesn't update the toggled state, I can still toggle off the style that gets frozen from the previous line. However, I cannot switch between the different styles within these groups.

**Comment by Gabianne01** [comment]
Thank you for the fix. I have tested it and found some remaining issues. Here are the details:

**What is Fixed:**
List Inside a List:
Choose any list type, type some text, hit enter, and try to change the list type without typing anything. The toggle states are now correct.
Alignments:
Choose any alignment, type some text, hit enter, and choose a different alignment. The toggle states are correct.

**What is Not Working:**
Initial Toggle on New Line:
Add some text to the first line without toggling any alignment or list, hit enter, and then try to set the alignment style or any list style. The toggles won't work in this case. 
The same behavior applies when toggling one but not the other (list or alignment), whichever group that does not have any style toggled in the first line, it's toggled state will not work on the second line.

**Comment by AtlasAutocode** [comment]
I will look into this as soon as I can.
In the meantime, are there any other aspects of the problem that I should be looking at?

**Comment by Gabianne01** [comment]
Thank you for your response and for looking into this issue.
The issue consistently occurs when adding text to the first line and then attempting to set styles on the subsequent line without any initial style toggles. This behavior affects both list styles and alignment styles.

### Observations

- **Toggle Behavior**: It seems the toggle state logic doesn't account for scenarios where a new line starts without any styles, which might be impacting the initial style setting for that line.
  
- **Temporary Workaround**: As a workaround, entering any character on the new line before applying styles temporarily resolves the issue.

I believe these are the core aspects of the issue. However, if there's any additional testing you would like me to conduct, please let me know, and I'll be happy to assist.

**Comment by AtlasAutocode** [comment]
I've submitted a PR that should fix the remaining issue.
PR relates to searching within custom embed objects.

**Comment by Gabianne01** [comment]
Works perfectly, thank you!
