### ISSUE TITLE
HardwareKeyBoard and isAltPressed

### ISSUE THREAD

**Issue by SatoshiGNJA** [singerdmx/flutter-quill#2084]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.0

### Steps to reproduce

Normal how I create the Quill Code just copy paste my code using 9.3.0 Quill

### Expected results

Should Run Normally

### Actual results

Error (Xcode): ../.pub-cache/hosted/pub.dev/flutter_quill-9.3.0/lib/src/widgets/raw_editor/raw_editor_state.dart:803:35: Error: The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard'.

Could not build the application for the simulator.
Error launching application on iPad Pro (12.9-inch) (6th generation).

### Code sample

import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart' as quill;
import 'package:flutter_quill/flutter_quill.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final _controller = quill.QuillController.basic();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Demo Home Page'),
      ),
      body: Column(
        children: [
          Expanded(
              child: Container(
                  color: Colors.grey,
                  padding: EdgeInsets.all(16),
                  child: quill.QuillEditor.basic(
                      configurations: QuillEditorConfigurations(
                    controller: _controller,
                    readOnly: false,
                    autoFocus: false,
                    expands: false,
                    padding: EdgeInsets.zero,
                    scrollable: true,
                    showCursor: true,
                  ))))
        ],
      ),
    );
  }
}

**Comment by AtlasAutocode** [comment]
My guess is that your development environment is 'wonky'.
That is one problem with the whole flutter eco-system.
When one part updates, it often breaks something else until you get everything up to date.
There was a major update to flutter recently that could have caused this kind of problem.

You can try:
Check that your flutter installation is up to date.
flutter clean
flutter pub upgrade
Can you use the current version 10 for flutter-quill?

**Comment by AtlasAutocode** [comment]
Is this still a problem?
Can I close this issue?
