### ISSUE TITLE
Facing an issue with insert Html Text

### ISSUE THREAD

**Issue by Aruljebaraj** [singerdmx/flutter-quill#2087]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.0.3

### Steps to reproduce

assume I have html :

<img width="594" alt="Screenshot 2024-08-02 at 12 14 32 pm" src="https://github.com/user-attachments/assets/d8d66c5f-90ba-4e78-b174-7f2b3f41eba7">

and I have a custom button on tool bar and it this content should appear on selected area on a button press 

tried :
```dart
final selection = _controller.selection;

                                    // Insert the delta at the current cursor position
                                    final Delta imageDelta = Delta()
                                      ..retain(selection.start)
                                      // Insert a new line before the image
                                      ..insert("\n")
                                      // Insert the image data as a map
                                      ..insert({
                                        // 'image' key represents the image data, in this case, the file path
                                        'image':
                                            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNwD-geCtaIaqxMoMoBNpvonJNKKqwiko5nA&s',
                                      })

                                      // Insert a new line after the image
                                      ..insert("\n");
                                    _controller.compose(
                                      imageDelta, // Delta representing the image
                                      // Set the text selection to the end of the inserted image
                                      TextSelection.collapsed(
                                          offset: imageDelta.length),
                                      // Specify that the change was made locally
                                      ChangeSource.local,
                                    );
```

it works for images bt in my case text should appear with all attribute

### Expected results

need to add text on selected area on a button press along with a selected attribute

### Actual results

just plain text appears if try to insert

### Code sample
```dart
final selection = _controller.selection;

                                    // Insert the delta at the current cursor position
                                    final Delta imageDelta = Delta()
                                      ..retain(selection.start)
                                      // Insert a new line before the image
                                      ..insert("\n")
                                      // Insert the image data as a map
                                      ..insert({
                                        // 'image' key represents the image data, in this case, the file path
                                        'image':
                                            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNwD-geCtaIaqxMoMoBNpvonJNKKqwiko5nA&s',
                                      })

                                      // Insert a new line after the image
                                      ..insert("\n");
                                    _controller.compose(
                                      imageDelta, // Delta representing the image
                                      // Set the text selection to the end of the inserted image
                                      TextSelection.collapsed(
                                          offset: imageDelta.length),
                                      // Specify that the change was made locally
                                      ChangeSource.local,
                                    );
```
### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by Aruljebaraj** [comment]
final selection = _controller.selection;
                                    String empty =
                                        "<br>${state.commentTemplates[index].description.toString()}";
                                    var val =
                                        empty; //this is to avoid bad state exception
                                    _controller.compose(
                                        Document.fromHtml(val).toDelta(),
                                        TextSelection.collapsed(
                                            offset:selection.baseOffset),
                                        ChangeSource.local); tried this

**Comment by CatHood0** [comment]
The only way to get a `Delta` from HTML is pasting that `HTML` from the `Clipboard`. If you want to do this, but, without the `Clipboard`, you need to use [flutter_quill_delta_from_html](https://pub.dev/packages/flutter_quill_delta_from_html) because only the `Clipboard` can access to the functionality to convert `HTML` to `Delta`.

**Comment by Aruljebaraj** [comment]
@CatHood0   The text was not being added at the cursor position. need help on that

**Comment by CatHood0** [comment]
What is the code that are you trying? Using this should put the text at the position of the caret:
```dart
int index = _controller.selection.baseOffset;
// You will need to add your own logic to move the cursor at the required position
_controller..moveCursorToPosition(index + 1);
```

**Comment by Aruljebaraj** [comment]
assume that have 3 points in bullet

1. sbsbjbs
2. snnsknkns
3. jkojjsinkknks
and on button new line need to be added  below one of point were there is an cursor and bullet point shouldn't break

in one of the editor I achieved this using by inserting 
'<br>&nbsp;
here I was difficult to retain and insert this

**Comment by CatHood0** [comment]
Can you provide any video example? When you add any new line (using the keyboard of the device) always should try to persist the block attribute (at least on `List` attribute). If you need to add a new line from a button on the toolbar, you need to know follow the standard of the [Quill Delta](https://quilljs.com/docs/delta/):

```dart
//Following you example the Delta should be:
Delta()
 ..insert('sbsbjbs')
 ..insert('\n', {"list":"ordered"})
 ..insert('snnsknkns')
 ..insert('\n', {"list":"ordered"})
 ..insert('jkojjsinkknks')
 ..insert('\n', {"list":"ordered"});
```

So, to add a new line without break the block style, you just need to add a that new line but, with the block attribute.

```dart
//You have two options:

//1: 
Delta()
 ..insert('sbsbjbs')
 ..insert('\n\n', {"list":"ordered"});
//2:
Delta()
 ..insert('sbsbjbs')
 ..insert('\n', {"list":"ordered"})
 ..insert('\n', {"list":"ordered"});
```

Idk if this solve your questions, but, i guess you will need to take a look of [PreserveBlockStyleOnInsertRule](https://github.com/singerdmx/flutter-quill/blob/1cc6a7cdc1b03b60d1120e82d367c5731eeb8a89/lib/src/rules/insert.dart#L81). This rule retain the content that was inserted before, and insert any new content on the `Delta` preserving (obviusly) the block attributes (as far i know).

**Comment by Aruljebaraj** [comment]
@CatHood0  can I get an example how to use rules I have no idea

**Comment by CatHood0** [comment]
I suggest you use logic in the `Rule`, you don't need to use any `Rule` since your insertion is coming from a button. You just need to take the code of that `Rule` and modify it in such a way that it helps you achieve the behavior you want.

**Comment by Aruljebaraj** [comment]
achieved using ` final int currentOffset =
                                      _controller.selection.baseOffset;

                                  // Create a Delta to insert a new line at the current cursor position
                                  final Delta delta = Delta()
                                    ..retain(
                                        currentOffset) // Retain the position up to the current cursor
                                    ..insert(
                                        '\n'); // Insert a new line character

                                  // Apply the Delta to the document
                                  _controller.compose(
                                    delta,
                                    _controller.selection.copyWith(
                                      baseOffset: currentOffset + 1,
                                      // Move the cursor to the next line
                                      extentOffset: currentOffset + 1,
                                    ),
                                    ChangeSource.local,
                                  );
                                  _controller
                                      .moveCursorToPosition(currentOffset + 1);`
