### ISSUE TITLE
Error: The non-abstract class 'RawEditorState' is missing implementations for these members:  - TextSelectionDelegate.userUpdateTextEditingValue

### ISSUE THREAD

**Issue by enomars** [singerdmx/flutter-quill#210]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.2/lib/widgets/raw_editor.dart:97:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.userUpdateTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.2/lib/widgets/raw_editor.dart:1050:8: Error: The method 'RawEditorState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
  void hideToolbar() {
       ^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);
       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.2/lib/widgets/raw_editor.dart:729:51: Error: A value of type 'bool' can't be returned from a function with return type 'KeyEventResult'.
 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
        onKey: (node, event) => _keyboardListener.handleRawKeyEvent(event));
                                                  ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.2.2/lib/widgets/raw_editor.dart:775:53: Error: A value of type 'bool' can't be returned from a function with return type 'KeyEventResult'.
 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
          onKey: (node, event) => _keyboardListener.handleRawKeyEvent(event));
                                                    ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by mcmikecreations** [comment]
There was little context provided by the OP, so here's my `flutter doctor -v` when trying to build for Android. I'm encountering the same issue. While I can edit the pub cache to add the missing positional argument of `hideToolbar`, I wasn't able to find `userUpdateTextEditingValue` in the flutter source code, so I'm looking forward for a fix. Maybe @hyouuu or @singerdmx have encountered this issue?
```
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.1.0-12.2.pre
    • Framework revision 5bedb7b1d5 (9 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Platform android-30, build-tools 30.0.1
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
```

**Comment by mcmikecreations** [comment]
I've temporarily patched this editing the `raw_editor.dart` file. I've added
```
@override
  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause) {
    textEditingValue = value;
  }
```
and `[bool hideHandles = true]` where needed. But this seems like a botched solution. Maybe there is a better way?

**Comment by imSaharukh** [comment]
> I've temporarily patched this editing the `raw_editor.dart` file. I've added
> 
> ```
> @override
>   void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause) {
>     textEditingValue = value;
>   }
> ```
> 
> and `[bool hideHandles = true]` where needed. But this seems like a botched solution. Maybe there is a better way?

in which class?
