### ISSUE TITLE
Migrating from simple text to quill

### ISSUE THREAD

**Issue by Abolfazl-MI** [singerdmx/flutter-quill#2107]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I have developed a simple note application which stored title and body of note in Raw text like this "this is body!"
Now how should I read data and show in the editor
I know I have to use fromjson but how I have to use it??

**Comment by CatHood0** [comment]
You should try to read the [delta_introduction](https://github.com/singerdmx/flutter-quill/blob/master/doc/delta_introduction.md) doc
