### ISSUE TITLE
Open a .docx file , edit and save.

### ISSUE THREAD

**Issue by iykechukwu** [singerdmx/flutter-quill#2112]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi?

I am currently working on a project for a customized word processor; I am using Flutter Quill; opening, editing, and storing .docx files seem to be a big challenge, I have managed to convert to Delta and load texts but the file doesn't load with the formats, tables do not show as well.

**Comment by CatHood0** [comment]
Getting/editing/saving Deltas from/to a Docx file is not a standard from Quill Js (the same thing for PDF, LATEX, EPUB, etc), and it's not planned.

You will need to describe more about your issue if you want some help about it

**Comment by EchoEllet** [comment]
You will need to convert the Delta to and from Microsoft docx.

You can take a look at how other packages handle this conversation (to a similar formats):

-[vsc_quill_delta_to_html](https://pub.dev/packages)/vsc_quill_delta_to_html
- [flutter_quill_delta_from_html](https://pub.dev/packages/flutter_quill_delta_from_html)
- [flutter_quill_to_pdf](https://pub.dev/packages/flutter_quill_to_pdf)
- [markdown_quill](https://pub.dev/packages/markdown_quill)


Also, take a look at [docx_template](https://pub.dev/packages/docx_template).
