### ISSUE TITLE
Context Menu Position Covers the Selected Text.

### ISSUE THREAD

**Issue by SalhabNoman** [singerdmx/flutter-quill#2115]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.2.0

### Steps to reproduce

1- Write any text.
2- Long press on any word to select it.
3- The word/sentence is no longer visible due to the context menu showing right above it.

### Expected results

For the context menu to be rendered but with a bottom/top padding for the selected text to still be visible to the user.

### Actual results

The text is being covered by the menu's appearance position.

### Code sample

No Code Sample Available.

### Additional Context
![Screenshot (1362)](https://github.com/user-attachments/assets/2e50bf76-d51e-424c-85b2-af2ca79fdf19)

**Comment by CatHood0** [comment]
I think this issue was fixed at some of the lastest versions of the package. If the issue persists, please reopen this issue again.

**Comment by EchoEllet** [comment]
@SalhabNoman Can you confirm is this still an issue in recent versions?
