### ISSUE TITLE
Alignment changes when multiple enter inputs

### ISSUE THREAD

**Issue by n7484443** [singerdmx/flutter-quill#2119]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.3.0

### Steps to reproduce

1. change alignment to center
2. input 'abc'
3. enter key
4. enter key

### Expected results

Alignment could not change even enter multiple.

### Actual results

https://github.com/user-attachments/assets/4bfea873-e229-4973-b4a3-3c5601046a81

Alignment changes enter twice.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
It's normal. This is a normal behavior from the editor. This exact behavior is handle thanks of `AutoExitBlockRule`.

You can see this at the definition of this `Rule`:
```dart
/// Heuristic rule to exit current block when user inserts two consecutive
/// newlines.
///
/// This rule is only applied when the cursor is on the last line of a block.
/// When the cursor is in the middle of a block we allow adding empty lines
/// and preserving the block's style.
@immutable
class AutoExitBlockRule extends InsertRule {
``
