### ISSUE TITLE
Error while building the app in windows 

### ISSUE THREAD

**Issue by Aruljebaraj** [singerdmx/flutter-quill#2123]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.3.1

### Steps to reproduce

Tried to build on windows desktop got this error
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux.dart:4:8: Error: Error when reading '/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart': The system cannot find the path specified.

import 'package:gal/src/gal_platform_interface.dart';
       ^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:5:8: Error: Error when reading '/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal-2.3.0/lib/gal.dart': The system cannot find the path specified.

import 'package:gal/gal.dart';
       ^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:2:8: Error: Error when reading '/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal-2.3.0/lib/gal.dart': The system cannot find the path specified.

import 'package:gal/gal.dart' show Gal, GalException, GalExceptionType;
       ^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux.dart:8:36: Error: Type 'GalPlatform' not found.
final class GalPluginLinux extends GalPlatform {
                                   ^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:64:34: Error: Type 'GalExceptionType' not found.
extension GalExceptionTypeExt on GalExceptionType {
                                 ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux.dart:10:5: Error: Undefined name 'GalPlatform'.
    GalPlatform.instance = GalPluginLinux();
    ^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:60:21: Error: Undefined name 'GalExceptionType'.
              type: GalExceptionType.unexpected,
                    ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:62:23: Error: Undefined name 'GalExceptionType'.
                code: GalExceptionType.unexpected.code,
                      ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:59:17: Error: Method not found: 'GalException'.
          throw GalException(
                ^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:105:15: Error: Undefined name 'GalExceptionType'.
        type: GalExceptionType.unexpected,
              ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:104:13: Error: Method not found: 'GalException'.
      throw GalException(
            ^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:116:15: Error: Undefined name 'GalExceptionType'.
        type: GalExceptionType.unexpected,
              ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:115:13: Error: Method not found: 'GalException'.
      throw GalException(
            ^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:131:15: Error: Undefined name 'GalExceptionType'.
        type: GalExceptionType.unexpected,
              ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:133:17: Error: Undefined name 'GalExceptionType'.
          code: GalExceptionType.unexpected.code,
                ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:130:14: Error: Method not found: 'GalException'.
      (throw GalException(
             ^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:181:15: Error: Undefined name 'GalExceptionType'.
        type: GalExceptionType.unexpected,
              ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/gal_linux-0.1.0/lib/src/gal_linux_impl.dart:180:13: Error: Method not found: 'GalException'.
      throw GalException(
            ^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:23:10: Error: 'GalException' isn't a type.
    } on GalException catch (e) {
         ^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:22:13: Error: The getter 'Gal' isn't defined for the class 'ImageSaverGalImpl'.
 - 'ImageSaverGalImpl' is from 'package:flutter_quill_extensions/src/editor_toolbar_shared/image_saver/packages/gal.dart' ('/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Gal'.
      await Gal.putImageBytes(imageBytes);
            ^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:40:10: Error: 'GalException' isn't a type.
    } on GalException catch (e) {
         ^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:39:13: Error: The getter 'Gal' isn't defined for the class 'ImageSaverGalImpl'.
 - 'ImageSaverGalImpl' is from 'package:flutter_quill_extensions/src/editor_toolbar_shared/image_saver/packages/gal.dart' ('/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Gal'.
      await Gal.putImage(imageUrl);
            ^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:55:12: Error: The getter 'Gal' isn't defined for the class 'ImageSaverGalImpl'.
 - 'ImageSaverGalImpl' is from 'package:flutter_quill_extensions/src/editor_toolbar_shared/image_saver/packages/gal.dart' ('/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Gal'.
    return Gal.hasAccess(toAlbum: toAlbum);
           ^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:60:12: Error: The getter 'Gal' isn't defined for the class 'ImageSaverGalImpl'.
 - 'ImageSaverGalImpl' is from 'package:flutter_quill_extensions/src/editor_toolbar_shared/image_saver/packages/gal.dart' ('/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Gal'.
    return Gal.requestAccess(toAlbum: toAlbum);
           ^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:67:12: Error: Undefined name 'GalExceptionType'.
      case GalExceptionType.accessDenied:
           ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:69:12: Error: Undefined name 'GalExceptionType'.
      case GalExceptionType.notEnoughSpace:
           ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:71:12: Error: Undefined name 'GalExceptionType'.
      case GalExceptionType.notSupportedFormat:
           ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:73:12: Error: Undefined name 'GalExceptionType'.
      case GalExceptionType.unexpected:
           ^^^^^^^^^^^^^^^^
/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/packages/gal.dart:65:27: Error: A non-null value must be returned since the return type 'ImageSaverExceptionType' doesn't allow null.
 - 'ImageSaverExceptionType' is from 'package:flutter_quill_extensions/src/editor_toolbar_shared/image_saver/exceptions.dart' ('/C:/Users/devus/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill_extensions-10.3.1/lib/src/editor_toolbar_shared/image_saver/exceptions.dart').
  ImageSaverExceptionType toImageSaverExceptionType() {

### Expected results

Execpted to build without any error

### Actual results

Got error

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
Can you give us more information? I have no problems compiling on windows desktop.

Are you trying to compile the example app in the repository or your own app?
Are you compiling to run on microsoft windows desktop or linux or android or what?

Have you run flutter clean? flutter pub upgrade?

From your error list it looks like your local cache may have become corrupt. On Android Studio you can try menu File, Invalidate Cache. Sometimes, simply restarting your computer can resolve problems.

**Comment by Aruljebaraj** [comment]
This issue is been caused by Flutter Quill Extension add tried adding the latest version still getting this while doing pub get

**Comment by Aruljebaraj** [comment]
fixed this by adding gal 2.3.0
