### ISSUE TITLE
SuperClipboard  feature need to be disable in flutter_quill_extensions

### ISSUE THREAD

**Issue by rashmi-key** [singerdmx/flutter-quill#2129]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

flutter_quill_extensions: 10.1.10

### Steps to reproduce

SuperClipboard  feature need to be disable in flutter_quill_extensions

### Expected results

In flutter_quill_extensions can we disable the superclipboard feature in flutter

### Actual results

In flutter_quill_extensions can we disable the superclipboard feature in flutter

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by rashmi-key** [comment]
@jezell @richardmarshall @vishna @singerdmx  any update on this

**Comment by EchoEllet** [comment]
It's already disabled by default, do you mean excluding `super_clipboard` dependency from `flutter_quill_extensions`?

Related issues:

- https://github.com/singerdmx/flutter-quill/pull/1914
- https://github.com/singerdmx/flutter-quill/issues/1991#issuecomment-2217253131

We initially wanted to move `super_clipboard` plugin implementation into its own package `flutter_quill_super_clipboard` (or `quill_super_clipboard`) to use it instead, which allows the users of `flutter_quill` to use `super_clipboard` without `flutter_quill` and to also using`flutter_quill_extensions` without `super_clipboard` as a dependency.

I'm interested into knowing more about you meant. Closing this issue to follow up in #1914
