### ISSUE TITLE
[Mobile] Is It Possible to Add Custom Blots and Attributors 

### ISSUE THREAD

**Issue by BMonsalvatge** [singerdmx/flutter-quill#214]
Hi,

I am reviewing the QuillJS documentation and I am trying to determine if there's a similar way to add custom Attributors and Blots with this package: https://quilljs.com/guides/how-to-customize-quill/#content-and-formatting

If it helps, I am currently trying to add a type of formatting that will be a clickable piece of text (similar to a link) but instead open up a dialog box inside the UI.

**Comment by singerdmx** [comment]
You can submit PR
