### ISSUE TITLE
TextInputClient throws exceptions by attributes assertion

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#2140]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.4.2

### Steps to reproduce

I don't really know exactly why or when exactly this happens. Just stop working at any point. I running this on Linux. See the video.

### Expected results

Write without issues

### Actual results

Unexpected exceptions

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/14d1895b-0274-4cd0-9578-e20d749c838e

</details>

<details><summary>Logs</summary>

```console
** (example:68521): WARNING **: 03:04:17.933: Failed to call TextInputClient.updateEditingState: Remote code returned error error: 'package:flutter_quill/src/document/node
s/line.dart': Failed assertion: line 147 pos 14: 'style.values.every((attr) =>
          attr.scope == AttributeScope.inline ||
          attr.scope == AttributeScope.ignore)': is not true.
```

</details>

**Comment by CatHood0** [comment]
I'll take a look what could be happening

**Comment by singerdmx** [comment]
Is this a regression?

**Comment by CatHood0** [comment]
I think it is. I will fix another thing first and after i'll fix this. I guess that could be a issue with logic.

**Comment by singerdmx** [comment]
If this is a regression, we can figure out which commit caused this and potentially revert that commit

**Comment by singerdmx** [comment]
Possibly this PR? https://github.com/singerdmx/flutter-quill/pull/2144

**Comment by CatHood0** [comment]
I'll take a look if that PR could be the issue
