### ISSUE TITLE
Make spell checker package optional

### ISSUE THREAD

**Issue by jonafeucht** [singerdmx/flutter-quill#2142]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

Latest

### Steps to reproduce

The simple_spell_checker package should be optional, it has ballooned my app from sub 70mb to >150mb, adding around 80mb more.

From what I can tell this is because of all the language dictionaries:

<img width="1678" alt="Screenshot 2024-08-23 at 16 50 54" src="https://github.com/user-attachments/assets/cd9d1734-51a3-431a-b382-36bfe62fd305">

My suggestion would be to just make platform specific api calls. Apple for example provides https://developer.apple.com/documentation/uikit/uitextchecker for iOS. Android and other platforms should have equivalent apis.

### Expected results

Small app size

### Actual results

Large app size

**Comment by CatHood0** [comment]
The idea of ​​this spell checker is to be a client-side service. But the size is a problem... For now I prefer to see what other developers suggest to avoid this.

**Comment by jonafeucht** [comment]
> The idea of ​​this spell checker is to be a client-side service. I'm interested in knowing how we can make it optional, can you explain about it?

Both Apple and Google apis are client side. I would expect Microsoft to have an equivalent api for Windows. No idea about the web, but having the package as a hard dependency there wouldn't be a problem, as the code lives server side.

My problem, when it primarily comes to mobile devices, is that the package is trying to reinvent the wheel. That's why I would prefer direct api calls to the platform provided apis.
- iOS: https://developer.apple.com/documentation/uikit/uitextchecker
- Android: https://developer.android.com/develop/ui/views/touch-and-input/spell-checker-framework

My suggestion for a temporary solution would be to separate the package and make it standalone without it being a hard dependency of flutter_quill_extensions. And just point developers to the package if they need spell checking.

**Comment by CatHood0** [comment]
@EchoEllet @singerdmx what do you think? Should we move any implementation of `simple_spell_checker` to the example app to avoud this?

**Comment by EchoEllet** [comment]
> do you think? what do you think? Should we move any implementation of simple_spell_checker to the example app to avoud this?

Yes, we could separate this feature in its own package that depends on `simple_spell_checker`, which has Flutter Quill specific code, or you could make the package only for `flutter_quill` which will require more steps to use the package without `flutter_quill` as a dependency. 

Or we could make it specific for the example app.

As for the bundle size, we have already discussed this. However, we should have mentioned this in the `CHANGELOG` regarding the bundle size, users already using the package and don't expect such change in a minor update, we can't make another major release either.

@CatHood0 I can handle this since it it doesn't require changing much or leaving it up to you to decide.

I prefer to keep the `flutter_quill_spell_checker` package (which haven't been created yet) in the same repository as `simple_spell_checker` so you can get more control and publish releases without submitting PRs to this repository. Creating a new package in this repository is an option as well.

**Comment by CatHood0** [comment]
@EchoEllet then I leave you in your command. Thank you!

**Comment by EchoEllet** [comment]
I will start as soon as I can. It might be 1-2 days before I do.

**Comment by EchoEllet** [comment]
I have tried `SpellCheckerSession` on Android (platform-specific API) and in my case, it didn't work quite well, on the emulator it takes longer than expected to return the result, on a real device (I have used only one that's Android 14) and it returns an empty list.

![image](https://github.com/user-attachments/assets/5b9da5f0-fc9d-43d6-b9e5-4219a92020fc)

Flutter `DefaultSpellCheckService` didn't work at all for the emulator and real device.

I haven't looked into this issue much however we can probably implement it only on iOS and Android using system API.

>  the package is for those who want to manage the state of the language within the service without use the language that comes from the system

Can you clarify what you mean by this?

> in Flutter's native SpellCheckerService it is not possible (not that I have seen)

Did you try it on Android or iOS?

**Comment by CatHood0** [comment]
I noticed that this could be useful. I was made a similar suggestion to have `simple_spell_checker` also have an instance that uses the native system services (in case of IOS or Android). I haven't taken the time to do this yet, but it's on my list of things I could do

> Can you clarify what you mean by this?

This part refers to the fact that we can handle languages ​​not only created by the users themselves (through the `LanguageIdentifier` class) but it also allows us to change at any time to a language that the operating system is not using. You can see it as if in Word, we changed the spell checker from English to Italian, even if the system is not using these languages. i clarify that i don't know if this same thing is already allowed with Flutter's native `SpellCheckService` service, although as far as I looked, there was nothing like that.

> Did you try it on Android or iOS?

I tried it only on Android. Unfortunately I don't have the availability to use an iOS device, but still at no time was I able to get either a `TextField`/`TextFormField` or an `EditableTextLine` to work as I expected. I tried with or without an internet connection, and at no time did it give me results. But, as I said above, maybe it was some bad configuration on my part.

**Comment by EchoEllet** [comment]
> This part refers to the fact that we can handle languages ​​not only created by the users themselves (through the LanguageIdentifier class) but it also allows us to change at any time to a language that the operating system is not using. You can see it as if in Word, we changed the spell checker from English to Italian, even if the system is not using these languages.

It's already possible to choose a different local than the system default, I haven't tried it out before though.

> Flutter's native SpellCheckService service, although as far as I looked, there was nothing like that.

I tried `DefaultSpellCheckService` and wasn't able to get it working at all while it uses the same API that I used in native Android using `MethodChannel`.

**Comment by CatHood0** [comment]
> It's already possible to choose a different local than the system default, I haven't tried it out before though.

Thanks for letting me know. I'll take a look at it as soon as i can, as i might be able to make some kind of weird monster between the native and the implementation i created to eliminate the problem i have with the package's heaviness.

**Comment by CatHood0** [comment]
> I tried DefaultSpellCheckService and wasn't able to get it working at all while it uses the same API that I used in native Android using MethodChannel.

I really think it might be a Flutter issue that this aspect is not working properly. Could it be that internally the service is not being used even if we pass it in the parameters?

**Comment by EchoEllet** [comment]
> Could it be that internally the service is not being used even if we pass it in the parameters?

I forgot to mention that I used `fetchSpellCheckSuggestions(locale, text)` directly without `TextField` or `EditableTextLine`.

**Comment by EchoEllet** [comment]
I think we need to refactor our `SpellCheckService` a bit. We probably want to extends it from Flutter [`SpellCheckService`](https://github.com/flutter/flutter/blob/a7cd788d80ccb238e9b70316d89d2717fdc0c928/packages/flutter/lib/src/services/spell_check.dart#L101).

This will require breaking changes which is a bit unfortunate, we need to make it experimental first by marking it with `@experimental`, adding docs comment, and in `README` for a while as I expect more breaking changes.
