### ISSUE TITLE
Functionality to change the color of the dialog box of toolbar options eg: link

### ISSUE THREAD

**Issue by 1SagarSharma7** [singerdmx/flutter-quill#2148]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

I wanted to change the color of the dialog box to cyan , 
which does not lies in the default theme of light and dark,

### Proposal

will it be possible to add the feature of changing the dailog box color,
like how we can do for alertDialog widget

![image](https://github.com/user-attachments/assets/7865c03c-6626-412c-8736-c5959b0b94b5)

**Comment by CatHood0** [comment]
I think is always better use the `Theme` class and change it from your `MaterialApp` widget to adapt the dialog to your preferences

**Comment by Zambrella** [comment]
There's a `dialogTheme` property in the `QuillSimpleToolbarConfigurations` class. However, I have found that this doesn't seem to change anything. Is this an old property?
