### ISSUE TITLE
[Web] Keyboard not working

### ISSUE THREAD

**Issue by m-j-g** [singerdmx/flutter-quill#215]
Everything is working perfectly on iOS / Android, but when I run it on the web it doesn't respond to any of the keyboard inputs.  I added this to my material app that I saw in another post
Map<LogicalKeySet, Intent> ignoredNavigationShortcuts() {
  Map<LogicalKeySet, Intent> shortcuts = Map.from(WidgetsApp.defaultShortcuts);
  if (kIsWeb) {
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.space));
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowUp));
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowDown));
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowLeft));
    shortcuts.remove(LogicalKeySet(LogicalKeyboardKey.arrowRight));
  }
  return shortcuts;
}

Didn't change anything for me.  Also, its not just these special keys, but letters as well.  Can't type anything.  Is there something special that I need to do to setup web that is different then iOS/android?

**Comment by m-j-g** [comment]
setting "autoFocus: true" causes keyboard not to work on web.

**Comment by wliumelb** [comment]
So this is still not fixed? I found that when focusing with the FocusNode.requestFocus method, the keyboard is not working.

**Comment by amitozalvo** [comment]
Why is it closed? it's not working at all...
