### ISSUE TITLE
[Web] Unexpected null value

### ISSUE THREAD

**Issue by AjayOrx** [singerdmx/flutter-quill#216]
My issue is about [Web]

@singerdmx 
Arrow Keys not working, Space key not working Color selection also not working
I'm working in this version
flutter_quill: ^1.2.2
![Capture](https://user-images.githubusercontent.com/84171651/118392760-d4e3ac80-b658-11eb-80e5-0f15ab9dfef1.PNG)

**Comment by sleepreading** [comment]
same problem! click anywhere will produce this exception!

**Comment by mordivgor** [comment]
Shall work with 1.3.3 version.
