### ISSUE TITLE
Localization: Search button options not localized

### ISSUE THREAD

**Issue by EMUNES** [singerdmx/flutter-quill#2166]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.5.0

### Steps to reproduce

1. click search button in the flutter editor
2. click the vertical more button to show search options
3. the options are still English, not localized to other languages (like Chinese for the test case)

### Expected results

Search button actions should be localized, like other flutter quill buttons.

### Actual results

Still English.

### Code sample

<details><summary>Code sample</summary>

```dart
final toolbarConfigurations =
      const QuillToolbarConfigurations();

 // To search.
  IconButton(
    onPressed: () {
      final menuDisplayed =
          currentMenu == ToolBarMenuType.search;
      final newState = menuDisplayed
          ? ToolBarMenuType.hidden
          : ToolBarMenuType.search;

      setState(() {
        currentMenu = newState;
      });
    },
    tooltip: "Search text",
    icon: QuillSearchButton(widget.controller,
        toolbarConfigurations: toolbarConfigurations),
  ),
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
Implementing localizations consist of 2 parts:
1. Enabling localization for a word or phrase - this has been completed
2. Translating it into each language - this needs to be done by someone with knowledge of the language.

Please refer to the documentation [translations](https://github.com/singerdmx/flutter-quill/blob/master/doc/translation.md) for how to contribute.

**Comment by EchoEllet** [comment]
We might automate the process of translations using AI, as we don't have any knowledge of all of the languages that are supported by the contributions, most of them are not localized.

As for now, feel free to send a PR to add support for the languages that are available in your app. See the [translation
](https://github.com/singerdmx/flutter-quill/blob/master/doc/translation.md) page as mentioned above.
