### ISSUE TITLE
[Mobile] Editor does not autoscroll when selecting long text

### ISSUE THREAD

**Issue by jongkb** [singerdmx/flutter-quill#217]
(Observed on Android)

**The issue**
It is impossible to drag-select long blocks of text at one go.

**Actual behavior**
While dragging to select long blocks of text, the editor does not autoscroll to ensure the bottom text selection handle is always visible. The bottom selection handle goes under the keyboard panel instead. 

**Expected behavior**
Editor autoscrolls when selecting long blocks of text; bottom text selection handle is always visible while dragging.

Thank you.

**Comment by pavel-birdy** [comment]
There are two issues I found here.
1.  You don't see a cursor "text_select_handle"
<img width="424" alt="Screenshot 2021-05-20 at 17 22 34" src="https://user-images.githubusercontent.com/53362329/118974280-42ad1280-b990-11eb-903d-c1ecc42e6a35.png">

expected result: 
![photo_2021-05-20 20 05 24](https://user-images.githubusercontent.com/53362329/118998102-ca9e1700-b9a6-11eb-864b-36d0b9cf72dc.jpeg)


2. Here if you select any word and try to drag the "text_select_handle_left" (start cursor) and "textSelectHandleRight" (end cursor) it will always remember the first selected location. Also a little buggy.
<img width="424" alt="Screenshot 2021-05-20 at 17 24 05" src="https://user-images.githubusercontent.com/53362329/118995945-2a93be00-b9a5-11eb-8303-476a5d676b5c.png">

**Comment by phuongtinhbien** [comment]
actually, I tested in both IOS and Android. It worked
