### ISSUE TITLE
Text selection handles misaligned or missing after scrolling in QuillEditor on iOS/Android

### ISSUE THREAD

**Issue by agata** [singerdmx/flutter-quill#2173]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

flutter_quill 10.4.7 higher

### Steps to reproduce

1. Display enough text in the `QuillEditor` to enable scrolling.
2. Double-tap on the text to select it. At this point, the Text Selection Handles are displayed, allowing the selection range to be adjusted.
3. While the Text Selection Handles are displayed, scroll within the editor. The Text Selection Handles become misaligned and stay in the wrong position.
4. After this, double-tap to select text again. After doing this a few times, you’ll find that the text can be selected, but the Text Selection Handles for adjusting the selection range do not appear. The issue may resolve after some interaction, but once it occurs, it tends to persist for a while.

### Expected results

The Text Selection Handles should remain aligned even when scrolling occurs during text selection.

### Actual results

When scrolling occurs during text selection, the Text Selection Handles become misaligned, and afterward, they may not appear or remain misaligned when selecting text.

When scrolling occurs during text selection, the Text Selection Handles become misaligned, and afterward, they may not appear or remain misaligned when selecting text.

### Additional Context

This behavior is similar to #2167, but in this case, the issue occurs when scrolling.

### Version Behavior:

- `10.5.2` -> Issue present
- `10.5.0` -> Issue present
- `10.4.7` -> Issue present
- `10.4.6` -> No issue
- `10.2.0` -> No issue

I was using Flutter 2.4.1.

I am attaching a screencast showing the issue occurring with version `10.4.7` and another showing no issue with version `10.4.6`.

10.4.7
https://github.com/user-attachments/assets/632a019d-c90c-4677-b0b9-4c582445b270

10.4.6
https://github.com/user-attachments/assets/d0cff493-5cd7-497e-97d9-fa52b1c3f587

**Comment by AtlasAutocode** [comment]
Thanks for reporting this issue. I will take a look.
