### ISSUE TITLE
[Mobile] Caret is obliterated by colored text background

### ISSUE THREAD

**Issue by jongkb** [singerdmx/flutter-quill#218]
(Observed on Android)

**Actual**
Caret appears behind colored text background, making the caret partially visible.

![Screenshot_20210517-124431](https://user-images.githubusercontent.com/1127628/118433699-2601a800-b70e-11eb-8555-a1f3defc30ee.png)

**Expected**
Caret appears on top of colored text background.

Thank you.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/125176610-91ee1300-e189-11eb-96fa-4d854c5d403c.png)
 code is here

**Comment by singerdmx** [comment]
This is basically how to add background color for TextSpan that will not be obliterated by cursor

@florianh01 @friebetill  any thought?

**Comment by singerdmx** [comment]
Hmm, it is probably some setting when `buildToolbar`

![image](https://user-images.githubusercontent.com/122956/125177016-62d9a080-e18d-11eb-897c-93ed1f7f77a0.png)

**Comment by xinyuezhang0402** [comment]
Likely the `canvas.drawRRect` method

![image](https://user-images.githubusercontent.com/40752995/125179040-5f4f1500-e19f-11eb-9b0d-570106112232.png)

**Comment by singerdmx** [comment]
You are right
Need to figure out how canvas works

**Comment by singerdmx** [comment]
Probably has to do with `LayerLink`

![image](https://user-images.githubusercontent.com/122956/125181790-38074080-e1bd-11eb-8a95-73fdb179080f.png)
