### ISSUE TITLE
Is it possible to customise image editing menu?

### ISSUE THREAD

**Issue by digitalheartxs** [singerdmx/flutter-quill#2186]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I would like to remove resize option, change icons, etc. of image editing menu. Is it possible?

<img width="323" alt="Screenshot 2024-09-05 at 14 52 18" src="https://github.com/user-attachments/assets/8fe0933d-cffc-44e4-9ec3-8948a6478024">

**Comment by EchoEllet** [comment]
The `ImageOptionsMenu` widget itself isn't customizable however you can have your custom `onImageClicked`:

```dart
QuillEditorImageEmbedConfigurations(
  onImageClicked: (imageSource) {},
)
```

and show a different menu.

**Comment by CatHood0** [comment]
@EchoEllet should we add a new way to customize the image menu?

**Comment by EchoEllet** [comment]
> @EchoEllet should we add a new way to customize the image menu?

We probably should document on how to show a different dialog with an example.
