### ISSUE TITLE
Insert Table don't work in flutter web and flutter web-server

### ISSUE THREAD

**Issue by Paiolus** [singerdmx/flutter-quill#2193]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.0.0 on all flutter_quill packages

### Steps to reproduce

When you use the "insertTable" button, it throws an error of rendering...

A RenderEditor expected a child of type RenderEditableBox but received a child of type RenderErrorBox.
RenderObjects expect specific types of children because they coordinate with their children during layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a RenderSliver does not understand the RenderBox layout protocol.
The RenderEditor that expected a RenderEditableBox child was created by:
QuillRawEditorMultiChildRenderObject-GlobalKey#fa320] - MouseRegion - Composited TransformTarget -_SingleChildViewport - IgnorePointer-[GlobalKey#a466d] -
Semantics < Listener +
_GestureSemantics + RawGestureDetector-LabeledGlobalKey<RawGestureDetectorState>#09d2) - Listener - _ScrollableScope +
_ScrollSemantics [GlobalKey#c09c5| - ••
The RenderErrorBox that did not match the expected child type was created by:
ErrorWidget #08827 - Directionality - QuillRawEditorMultiChildRenderObject-[GlobalKey#fa320] - MouseRegion + Composited TransformTarget +
_SingleChildViewport + IgnorePointer-[GlobalKey#a466d] - Semantics + Listener - _GestureSemantics + RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#09d2] - Listener + •••
See also: https://docs.flutter.dev/testing/errors

<img width="1496" alt="Captura de pantalla 2024-09-07 a las 16 57 40" src="https://github.com/user-attachments/assets/18986a43-65e3-4273-b596-74b85e4195f8">
<img width="1504" alt="Captura de pantalla 2024-09-07 a las 16 57 33" src="https://github.com/user-attachments/assets/6201fab6-baf2-401a-a31e-b963138fcce1">
<img width="1499" alt="Captura de pantalla 2024-09-07 a las 16 57 15" src="https://github.com/user-attachments/assets/c1332215-f99e-40d1-ba52-6596a9697fd2">

### Expected results

You expect to insert a table, such as it happens in flutter web:
<img width="222" alt="Captura de pantalla 2024-09-07 a las 16 59 46" src="https://github.com/user-attachments/assets/f8780345-4ed4-4fd1-ad0d-90bf28c04446">
<img width="198" alt="Captura de pantalla 2024-09-07 a las 16 59 59" src="https://github.com/user-attachments/assets/6927412f-0246-4a4b-a31c-00f294b07472">

### Actual results

as explained above, it throws an exception. It occurs in all browsers, no matter if it's Brave, Safari, Mozilla, etc.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
This happens because the flutter quill extensions do not actually implement tables for the web. So far it has not been implemented due to time constraints. If you prefer, you can try to implement this for the web.
