### ISSUE TITLE
长按拖拽选中手柄，复制弹窗会自动消失！

### ISSUE THREAD

**Issue by yangzai100** [singerdmx/flutter-quill#2203]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.5.13

### Steps to reproduce

1.长按文本，出现复制弹窗
2.拖拽手柄，弹窗消失

### Expected results

希望拖拽手柄后，复制弹窗还能出现

### Actual results

拖拽手柄，弹窗消失

https://github.com/user-attachments/assets/72a4329f-caec-4635-b1e5-780d234baead

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by yangzai100** [comment]
1.我这边又测试了一下，如果打开放大镜就复制弹窗就正常（偶尔也会消失）。但是放大镜中的文本不是当前选中的文本，有时候是空的。

**Comment by yangzai100** [comment]
2.我这每一段文本使用了一个flutter quill，当我滚动页面，复制弹窗不会跟着选中文本

**Comment by yangzai100** [comment]
3.我这每一段文本使用了一个flutter quill，当我选中一段文本后，我再选中下一个quill，之前那个quill选中的文本还会有背景色

**Comment by AtlasAutocode** [comment]
Changes made to the magnifying glass have broken a number of aspects of the popup selection toolbar.
See #2153 and #2191
I suspect the problem was introduced in 10.0.10 (#2066) but I am probably wrong.
It's on my list to look into, but I don't program for mobile, so I don't know when I will get time.
HTH

**Comment by EchoEllet** [comment]
Thank you for the report. Could you update the issue to be in English?

感谢您的报告，您能否将问题编辑为英文？

**Comment by demoYang** [comment]
![image](https://github.com/user-attachments/assets/cad4a424-3708-4e93-a647-64049972cf3e)
@yangzai100  这3段代码注释了
