### ISSUE TITLE
Text color not worked.

### ISSUE THREAD

**Issue by toknT** [singerdmx/flutter-quill#2204]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.4.4

### Steps to reproduce

1 . install quill
2 . add editor

### Expected results

in line css text color in html

### Actual results

the log pring in listen event
```sh
I/flutter ( 3972): html: <p>text with co</p>
I/flutter ( 3972): html: <p>text with col</p>
I/flutter ( 3972): html: <p>text with colo</p>
I/flutter ( 3972): html: <p>text with color</p>
```

### Code sample

```dart
    void listenHtmlChange() {
      QuillDeltaToHtmlConverter converter = QuillDeltaToHtmlConverter(
        controller.value.document.toDelta().toJson(),
      );
      String html = converter.convert();
      print('html: $html');
      ref.read(editingImportPreviewQuestionProvider.notifier).updateBody(html);
    }

      controller.value.addListener(listenHtmlChange);

```

**Comment by CatHood0** [comment]
This is not an issue from Flutter Quill. You will need to report this on [vsc_quill_delta_to_html](https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html)

**Comment by EchoEllet** [comment]
Thank you for the report, please report this issue to [vsc_quill_delta_to_html](https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html) repository as it's not part of the Flutter Quill project.
