### ISSUE TITLE
Not show list-mark on empty editor

### ISSUE THREAD

**Issue by hjkim-mango** [singerdmx/flutter-quill#2209]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.5.13

### Steps to reproduce

1. Set/unset numbered-list on empty editor.
2. Set/unset bulleted-list on empty editor.
3. Set numbered-list on empty editor and then input any characters.(delete them)
4. Input any characters(just return-key on movie) and then set numbered-list.

### Expected results

The list mark(number or bullet) is shown whenever setting numbered-list or bulleted-list.

### Actual results

Any mark is not shown when setting numbered-list or bulleted-list on cases of empty editor.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart' as quill;

class FlutterQuillWidget extends StatefulWidget {
  const FlutterQuillWidget({super.key});

  @override
  State<FlutterQuillWidget> createState() => _FlutterQuillWidgetState();
}

class _FlutterQuillWidgetState extends State<FlutterQuillWidget> {
  late quill.QuillController _controller;

  @override
  void initState() {
    super.initState();

    _controller = quill.QuillController(
        document: quill.Document(),
        selection: const TextSelection.collapsed(offset: 0));
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        resizeToAvoidBottomInset: false,
        appBar: AppBar(
          title: const Text('Flutter Quill'),
        ),
        body: Column(children: [
          quill.QuillToolbar.simple(controller: _controller),
          quill.QuillEditor(
            controller: _controller,
            scrollController: ScrollController(),
            focusNode: FocusNode(),
            configurations: const quill.QuillEditorConfigurations(
                scrollable: true,
                autoFocus: false,
                expands: false,
                placeholder: "Add your data here..."),
          ),
        ]));
  }
}

```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/7b4b6d62-e9e2-4db8-a48f-de036f424f13

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
I'll fix it.

**Comment by hjkim-mango** [comment]
Thanks to fast fix.
I've confirmed it on the latest version.
