### ISSUE TITLE
[flutter_quill_extensions] Cannot configure QuillToolbarCameraButtonOptions "cameraConfigurations" because QuillToolbarCameraConfigurations is not exposed in the package.

### ISSUE THREAD

**Issue by raimkulovr** [singerdmx/flutter-quill#2213]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

1. Define QuillSimpleToolbar as in "Code sample" section;

### Expected results

QuillToolbarCameraConfigurations is imported and configurable

### Actual results

Error: The method 'QuillToolbarCameraConfigurations' isn't defined for the class '_MyWidgetState'

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter_quill/flutter_quill.dart';
import 'package:flutter_quill_extensions/flutter_quill_extensions.dart';

QuillSimpleToolbar(
    controller: _controller,
    configurations: QuillSimpleToolbarConfigurations(
      embedButtons: FlutterQuillEmbeds.toolbarButtons(
        videoButtonOptions: null,
        cameraButtonOptions: QuillToolbarCameraButtonOptions(
          //(IDE): The method 'QuillToolbarCameraConfigurations' isn't defined
          cameraConfigurations: QuillToolbarCameraConfigurations(), 
        )
      )
    ),
  )
```
</details>

### Additional Context

Possible solution:
add 
```dart
export 'src/toolbar/camera/camera_types.dart';
```
here:
https://github.com/singerdmx/flutter-quill/blob/5ff6c164260e46e1dad41345331d3d809bcb7a75/flutter_quill_extensions/lib/flutter_quill_extensions.dart#L28-L29

or remove cameraConfigurations from QuillToolbarCameraButtonOptions constructor.

What I actually wanted to do is to remove "Video" option here, and turn image from camera to base64; It would be nice to pass "useRootNavigator: true" somewhere .
![image](https://github.com/user-attachments/assets/30fcb62e-a406-4e88-b56e-b27268b156f8)

**Comment by EchoEllet** [comment]
Thank you for the report, fixed in [49d2e883c3ae85edf...](https://github.com/singerdmx/flutter-quill/commit/49d2e883c3ae85edf1bfa310be2b1e77a39347ee).

Related #2106
