### ISSUE TITLE
QuillToolbarToggleStyleButton， QuillToolbarToggleStyleButton Switching failure  on macOS

### ISSUE THREAD

**Issue by zhaofeixaing** [singerdmx/flutter-quill#2216]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

flutter_quill: ^10.5.16

### Steps to reproduce

First, add a task list and input the content, then press enter to create a new empty task list. 
Then, delete this new task list and return to the first list.
 Finally, switch to QuillToolbarToggleCheckListButton
At this point, clicking on the switch event will render it invalid

### Expected results

Click to switch states correctly

### Actual results

First, add a task list and input the content, then press enter to create a new empty task list. Then, delete this new task list and return to the first list. Finally, switch to QuillToolbarToggleCheckListButton
At this point, clicking on the switch event will render it invalid

### Code sample

<details><summary>Code sample</summary>
I am using the demo from the Flutter_quill library
```dart
      QuillToolbarToggleCheckListButton(
                    controller: controller,
                  ),
                  QuillToolbarToggleStyleButton(
                    controller: controller,
                    attribute: Attribute.ol,
                  ),
                  QuillToolbarToggleStyleButton(
                    controller: controller,
                    attribute: Attribute.ul,
                  ),
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
[新标签页.webm](https://github.com/user-attachments/assets/4d02ff04-bfbe-4930-a07d-12c1353bdddf)

**Comment by AtlasAutocode** [comment]
At a quick look, it looks like an issue with the toolbar state.
If I understand your instructions, even though the toolbar is incorrect, the expected list style is applied when you press enter and enter the next list entry.
> clicking on the switch event will render it invalid

What do you mean by invalid? Simply incorrect or something else?

**Comment by zhaofeixaing** [comment]
@AtlasAutocode What I mean is, click on the list and enter the first line, then enter to generate a new message, such as
1.adcd
two
The second point is that I do not write the task content and then delete it. At this point, the cursor returns to 1,
1.adcd
When switching the list type to not a list, it is because the content type has changed but the style of the bar has not changed. When changing it to a list, it will not change,
When clicking on other list types, the style of the bar remains unchanged, but the content type of the clicked bar remains the same
