### ISSUE TITLE
Android Gradle build failure related to Cargokit on Linux when using flutter_quill_extensions

### ISSUE THREAD

**Issue by zhangwenxia** [singerdmx/flutter-quill#2224]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

  flutter_quill: ^10.5.18 、flutter_quill_extensions: ^10.5.18

### Steps to reproduce

flutter build apk

### Expected results

Run successfully

### Actual results

1、flutter build apk 

Error reported as follows：
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: ClientException with SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = objects.githubusercontent.com, port = 61413, uri=https://github.com/irondash/irondash/releases/download/precompiled_c8cbb92de1e8b3dc787cdf8cb122c753/i686-linux-android_libirondash_engine_context_native.so.sig
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      IOClient.send (package:http/src/io_client.dart:119:7)
SEVERE: <asynchronous suspension>
SEVERE: #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
SEVERE: <asynchronous suspension>
SEVERE: #2      _withClient (package:http/http.dart:166:12)
SEVERE: <asynchronous suspension>
SEVERE: #3      ArtifactProvider._get (package:build_tool/src/artifacts_provider.dart:165:16)
SEVERE: <asynchronous suspension>
SEVERE: #4      ArtifactProvider._tryDownloadArtifacts (package:build_tool/src/artifacts_provider.dart:192:23)
SEVERE: <asynchronous suspension>
SEVERE: #5      ArtifactProvider._getPrecompiledArtifacts (package:build_tool/src/artifacts_provider.dart:133:11)
SEVERE: <asynchronous suspension>
SEVERE: #6      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:54:20)
SEVERE: <asynchronous suspension>
SEVERE: #7      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #8      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #9      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #11     runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/Users/zhangwenxia/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/irondash_engine_context-0.5.4/cargokit/gradle/plugin.gradle' line: 65

* What went wrong:
Execution failed for task ':irondash_engine_context:cargokitCargoBuildIrondash_engine_context_nativeDebug'.
> Process 'command '/Users/zhangwenxia/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/irondash_engine_context-0.5.4/cargokit/gradle/../run_build_tool.sh'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

**Comment by EchoEllet** [comment]
It seems like a connection issue
- Does this error occur in older version of the project (if you were using them)?
- Can you try again with a different network and see if the issue persists?
- Can you open this link: https://github.com/irondash/irondash/releases/download/precompiled_c8cbb92de1e8b3dc787cdf8cb122c753/i686-linux-android_libirondash_engine_context_native.so.sig
Could you see if the browser will start downloading the file without any issues?
- Have you manually installed Rust?

A workaround for now is to exclude the `flutter_quill_extensions` or `super_clipboard` plugin from the extensions package.

I might move `super_clipboard` to a new package `quill_super_clipboard` (to make it optional) and provide some default implementation in `quill_native_bridge` for Android and iOS.

**Comment by zhangwenxia** [comment]
> It seems like a connection issue
> 
> * Does this error occur in older versions of the project (if you were using them)?
> * Can you try again with a different network and see if the issue persists?
> * Can you open this link: https://github.com/irondash/irondash/releases/download/precompiled_c8cbb92de1e8b3dc787cdf8cb122c753/i686-linux-android_libirondash_engine_context_native.so.sig
>   Could you see if the browser will start downloading the file without any issues?
> * Have you manually installed Rust?
> * Does this error occurs when running the app on Android using `flutter run`? Does it also occurs when using `flutter build appbundle`?
> 
> A workaround for now is to exclude the `flutter_quill_extensions` or `super_clipboard` plugin from the extensions package.
> 
> I might move `super_clipboard` to a new package `quill_super_clipboard` (to make it optional) and provide some default implementation in `quill_native_bridge` for Android and iOS.

>*  https://github.com/irondash/irondash/releases/download/precompiled_c8cbb92de1e8b3dc787cdf8cb122c753/i686-linux-android_libirondash_engine_context_native.so.sig   Can download normally
>*   uninstalled Rust

**Comment by EchoEllet** [comment]
To confirm, does excluding `flutter_quill_extensions` fixes the issue?

**Comment by zhangwenxia** [comment]
> To confirm, does excluding `flutter_quill_extensions` fixes the issue?

 excluding `flutter_quill_extensions` running successfully
The project encountered an error after upgrading from version 3.7.12 to 3.24.2
Thank you very much for your answer. Thank you

**Comment by EchoEllet** [comment]
You're welcome.

**Comment by ApodJun** [comment]
Hi, i meet the same error with flutter_quill_extensions (even latest version 10.8.5).
I can not exclude flutter_quill_extensions from my project ,because i used the feathers of this plugin, it important for me. 
So how could i solve this problem. 
I need help...
