### ISSUE TITLE
Hide Default Configuration

### ISSUE THREAD

**Issue by kawad852** [singerdmx/flutter-quill#2225]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How do i hide the white block inside the editor (This is TheHTML) ? 
i managed to hide from the toolBar by setting  showCodeBlock: false, but did figure out how to hide it from the editor. 

this is my code: 

Column(
              children: [
                QuillSimpleToolbar(
                  controller: controller,
                  configurations: const QuillSimpleToolbarConfigurations(
                    showCodeBlock: false,
                  ),
                ),
                const SizedBox(height: 10),
                QuillEditor.basic(
                  controller: controller,
                  configurations: const QuillEditorConfigurations(minHeight: 300),
                ),
              ],
            )
            
<img width="1106" alt="Screenshot 2024-09-14 at 9 59 34 AM" src="https://github.com/user-attachments/assets/7f569eae-52ef-4bce-9a50-4e480db77dc1">

**Comment by AtlasAutocode** [comment]
I have run into this before [#2073](https://github.com/singerdmx/flutter-quill/issues/2073#issuecomment-2254225084)
I assume you are importing/pasting text from a source that is providing HTML.
In my cases, the paste process converted \<pre> to the code block attribute that appears as your white box.

Since I don't use HTML and the status of pasting HTML is being deprecated, I have not pursued this further.
@CatHood0 knows more about this than I do. Can you confirm that this is what you are doing?

**Comment by CatHood0** [comment]
I'll first add a new version for `flutter_quill_delta_from_html` to allow plain paste from html nodes and then we will need to add a new configuration for this in the editor. Give some time to make this.

**Comment by kawad852** [comment]
This is the html i'm trying to display inside the editor: 
"This is the <code>HTML</code> section of the email body."

it does not include <pre> 

and this is how i convert it: 

    _quillCtrl = QuillController(
      document: Document.fromDelta(HtmlToDelta().convert("This is the <code>HTML</code> section of the email body.")),
      selection: const TextSelection.collapsed(offset: 0),
    );

**Comment by CatHood0** [comment]
We know it. But,this is the default behavior. As soon as possible this will be changed

**Comment by AtlasAutocode** [comment]
> This is the <code>HTML</code> section of the email body.

1. Do you want to **_remove_** the white box? In this case, remove the \<code> tag and you should not have a problem. It seems that the Quill editor is working correctly and showing the \<code> tag as a code-block (block attribute).
2. Do you want to **_show the box as a different color and inline_**? In this case you want to convert the \<code> tag to an inline code-block (inline attribute). It is confusing that there are 2 attributes for code blocks and they have very different properties.

**Comment by kawad852** [comment]
@AtlasAutocode  

Yes i want to remove the white box.
i was just confused of this box because i've been using this package for a while now, and it's the first time i see this box (for the same html content). 
i guess they made some changes recently, 
Anyway, Thank you for your help, I appreciate it.
