### ISSUE TITLE
How is the placeholder ignored by the selection?

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#2233]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I'm trying to figure out where these events start from so I can handle this better.

A little context, I'm creating a new feature that will allow us to have virtual text (like for example, in Neovim there are parts or blocks of text that are ignored by the selection). This feature would allow us to later extend the feature to be even more than just virtual text (see how we can add autocomplete. Although it's clear that it's not standard and would be more of an extension of the package).

So, with that said, I know that `TextLine` and `EditableTextLine` handle these events quite well where the offset needed for the cursor to appear in the text is calculated, however, in itself, no matter how hard I try I can't find a way to make it so we can ignore it as if it were a placeholder.

Any advice or suggestion is welcome

**Comment by EchoEllet** [comment]
Around 40 issues have been closed today? We should not close outdated issues if that's what we're doing. Many of them are still applicable.
