### ISSUE TITLE
Applying indent attribute throws `container.containsOffset(position.offset)` fail assertion

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#2253]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.6.5

### Steps to reproduce

* Insert a header at the beginning of the document (write whatever you want).
* Create a new line.
* ​​Below the new line you created in the previous step, write some text.
* Apply the `indent` attribute to this last line (any that is not the first one) and you will see how this happens.

### Expected results

Apply indent to any line without exception calls.

### Actual results

When apply indent to any line that is not the first one, `text_line` throws an exception by the container is not registering the current offset position.

### _This is outdated. By now we found now the cause of the issue. Please scroll to the last comments to see which is the reason of this issue existence._

It seems that when we try to indent a line `text_line` throws the typical exception "`container.containsOffset(position.offset)`" which seems to tell us that the node we are selecting is not at the offset that the position is telling the editor.

But, I was wrong, I thought that the `Offset` was reloaded, instead of keeping the values ​​it had before applying the indentation attribute.

it seems that there is a problem with the `childAtPosition` function of `RenderEditableContainerBox` which compares in a while if the target we currently have corresponds to the node found through the `queryChild` method. But, is this not right? Yes, but it seems that there is an error at the level of `equals` and `hashcode` (this last one is still a theory that I am testing).

This would be the function in question: 

```dart
RenderEditableBox childAtPosition(TextPosition position) { 
  assert(firstChild != null);
  final targetNode = container.queryChild(position.offset, false).node;

  var targetChild = firstChild;
  while (targetChild != null) { 
    /// The issue is here with the equality
    if (targetChild.container == targetNode) { 
       break;
    } 
    final newChild = childAfter(targetChild);
    if (newChild == null) { 
       // At start of document fails to find the position 
       // here is where the issue start
       targetChild = childAtOffset(const Offset(0, 0));
       break;
    }
    targetChild = newChild;
  } 

  if (targetChild == null) { 
     throw 'targetChild should not be null';
  } 
  return targetChild;
}
```

####  What happens with this? 

Let's take an example, let's assume that the editor has a text such that (I'll use `markdown` syntax to not complicate the example using `Deltas`):

```markdown
# First header

any content
```

Supposing that we are right at the beginning of the third line (i.e. where "any content" starts), the caret should be with a `TextPosition` with an offset of 13. Having this value now, if we apply indent to the third line, the error will now occur. Why? Obviously the position was not updated neither in `QuillController's` `updateSelection` nor much less from our `raw_editor_state_text_input_client_mixin` since the latter is the one that maintained this last value.

Since we mentioned our `text_input_client` we have to mention that when we apply the indent, it goes and calls `_updateComposingRectIfNeeded` which our editor calls `getLocalRectForCaret` to get the current `Rect` of the caret. Why do I mention `getLocalRectForCaret`? This is because when it is called, then at the same time, in order to have which node is selected it calls `childAtPosition`. Do you see the problem? Every time we update the position of the caret, the node is searched, at this point there is no problem.

But, it seems that when we apply indent, something changes inside the editor, which is not able to determine if the node we obtained is really the one found through the `targetChild` of the code sample I showed before. It's strange, isn't it? Even though `queryChild` DOES find the node, when the loop is executed and we compare the `RenderEditableBox` container, it is not able to know if it is really equal or not. This only happens if indent is applied. With any other attribute it doesn't seem to be happening (although I've noticed that link sometimes suffers from this problem as well).

Concluding with this, it seems that since it is not able to properly compare the node obtained (which is the one we are actually selecting) with the node that `childAtPosition` returns, then it throws an error. This is mostly because since it is not able to obtain any new value that satisfies the condition, then it takes the first node it finds from the document and returns it, which causes this problem, since it is clear that it is more than likely that the first node is not or does not contain the offset in which we are.

I have a theory that the `RenderEditableBox` isn't updated fast enough so that when the editor gets it, it can compare the new value to the old one.

Having said that, it looks like we'll have to figure out if this is just an equality issue or something like one part being updated way before the other.

https://github.com/user-attachments/assets/f00d5df8-f035-4469-ac38-cfb9a665d991

**Comment by CatHood0** [comment]
@singerdmx @EchoEllet 

What I'm going to say is subject to change, because I'm going to test if this could be an update bug. However, should we add a new way to identify our nodes? That is, add something like an identifier or something that allows us to go directly to them without having to compare nodes that may have changed between them but are basically the same.

This is just an example of how we could do it (not equally, because the `Delta` structure we have is the **Quill js** standard and will stay that way) as BlockNote does in its node structure.

![Captura de pantalla_2024-09-20_15-09-21](https://github.com/user-attachments/assets/98eed121-b359-4442-9f4c-8323b8cc5502)

However, I'm not 100% sure about this as it would bring greater complexity as it is quite certain that we will have to change many parts of the code due to this new way of identifying the nodes.

Most likely we will have to review the code and see that everything is correct and that it is just a mistake that was accidentally implemented while other errors were being fixed.

**Comment by CatHood0** [comment]
**Update:** i added id property (it's auto generated when the node is created) and it solves the issue with the indent (because searching by id makes more easy compare). But comes with issues because if we split a line, then now the nodes takes a new id and throws error.

**Comment by CatHood0** [comment]
**Update:** I managed to notice that we don't need to add a complicated structure with ids (I managed to fix the problem where splitting a line into two parts anyway). It seems that the `QuillRawEditor` is directly updating itself before the `RenderEditableContainerBox` which makes it not notice the changes and this error occurs.

**Comment by CatHood0** [comment]
By now, i switching between versions to watch which version does not throw this error.

**Comment by CatHood0** [comment]
Finally! I get where the issue start. #2239 fix the composing range rect but, also add the discussed issue.

**Comment by EchoEllet** [comment]
If the change is not documented or clear, then I would suggest reveting the change and asking them for more details. New changes should be possible to understand from other developers' perspectives.

**Comment by CatHood0** [comment]
It seems the issue comes from giving the selection of the `QuillController` to the composingRange var. Removing that part of code makes the code run without issues.
