### ISSUE TITLE
Help For onTextChanged 

### ISSUE THREAD

**Issue by utkudenis** [singerdmx/flutter-quill#2268]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi guys, 
default quil html editor has onTextChanged functionality. it calls on every change. 
now, i'm trying to change quil_html_editor 2.8.8 to flutter_quil_html_editor. 

I need a function like this : 
 onTextChanged: (val) {
            textEditorProvider.updateWordCount(val);
          },

Can you help me ? 
Thanks a lot

**Comment by EchoEllet** [comment]
Is `flutter_quil_html_editor` a package? [`quil_html_editor`](https://pub.dev/packages/quill_html_editor) is a separate package that's not part of this repo and issues/discussions should be on a separate repo.

If you have any questions, don't hesitate to contact.

**Comment by utkudenis** [comment]
> Is `flutter_quil_html_editor` a package? [`quil_html_editor`](https://pub.dev/packages/quill_html_editor) is a separate package that's not part of this repo and issues/discussions should be on a separate repo.
> 
> If you have any questions, don't hesitate to contact.

sorry for misunderstading. I"m trying to switch flutter_quill: ^10.7.5.

**Comment by EchoEllet** [comment]
> sorry
No need to be.
> I"m trying to switch flutter_quill
If it's a issue or question related to the project, can you explain or provide more details?
