### ISSUE TITLE
No named parameter with the name 'onPopInvokedWithResult' , if still using flutter 3.22 .

### ISSUE THREAD

**Issue by toknT** [singerdmx/flutter-quill#2289]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.6.0

### Steps to reproduce

1 . install flutter 3.22
2 . create a new project
3.  install and use `flutter_quill` `flutter_quill_extensions` as example
3 . build ios

### Expected results

build success

### Actual results

Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/youtube_player_flutter-9.0.4/lib/src/widgets/youtube_player_builder.dart:78:9: Error: No named parameter with the name
'onPopInvokedWithResult'.

### Additional Context

this issue is caused by youtube_player_flutter . https://github.com/sarbagyastha/youtube_player_flutter/issues/978 . However I am not using video in editor.

**Comment by EchoEllet** [comment]
We have removed `youtube_player_flutter` and `flutter_inappwebview` in `10.8.0` from `flutter_quill_extensions`.

Should be fixed in the latest version. Can you confirm if this is an issue with `10.8.0`?
