### ISSUE TITLE
flutter_quill

### ISSUE THREAD

**Issue by Piyushg1994** [singerdmx/flutter-quill#2304]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Please update latest version flutter_quill

**Comment by EchoEllet** [comment]
Can you include more details about the issue? What to update or solve?

**Comment by EchoEllet** [comment]
Closing the issue as we don't have details about the issue. Feel free to open more issues if you're facing any.
