### ISSUE TITLE
Hashtags style

### ISSUE THREAD

**Issue by m-1226** [singerdmx/flutter-quill#2305]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

how Cani make when write # in the editor to have a custom style in it ? 
like #flutter_quill to take another color

**Comment by EchoEllet** [comment]
Currently, this is not a supported feature and is likely to be not supported anytime soon as we have extensibility, scalability, readability, maintainability, and many other bugs and critical issues that we need to prioritize.

#2160 Is a similar issue.

Noticed that I have seen developers that were able to implement it without having it built-in in the project using [custom embed blocks](https://github.com/singerdmx/flutter-quill/blob/master/doc/custom_embed_blocks.md).

See #637, [this example](https://github.com/ketan10592/flutter_quill_example), [this PR](https://github.com/memspace/zefyr/pull/594) and #1330


If you have any questions or more issues, feel free to open more issues or discussions.
