### ISSUE TITLE
Undefined name 'QuillToolbarSelectLineHeightStyleDropdownButtonOptions'.

### ISSUE THREAD

**Issue by ddxl123** [singerdmx/flutter-quill#2333]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

   flutter_quill: ^10.5.5   flutter_quill_extensions: ^10.5.5   vsc_quill_delta_to_html: ^1.0.5

### Steps to reproduce

Undefined name 'QuillToolbarSelectLineHeightStyleDropdownButtonOptions'. (Documentation)  Try correcting the name to one that is defined, or defining the name.

**Comment by EchoEllet** [comment]
Fixed in [release/v11](https://github.com/singerdmx/flutter-quill/blob/release/v11/lib/src/toolbar/config/simple_toolbar_config.dart).
