### ISSUE TITLE
When there are custom blocks, I want to customize the text content of these custom blocks when calling Document.toPlainText. How can I achieve this?

### ISSUE THREAD

**Issue by ddxl123** [singerdmx/flutter-quill#2349]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I tried using the toPlainText method inherited from EmbedBuilder, but when calling Document.toPlainText, it still displays an obj icon.
```
class BlankEmbedBuilder extends q.EmbedBuilder {
  BlankEmbedBuilder({required this.blankFragmentContent, required this.isEditable});

  final BlankFragmentContent blankFragmentContent;
  final bool isEditable;

  @override
  String toPlainText(q.Embed node) {
    return "xxxx";
  }
  @override
  String get key => BlankBlockEmbed.blankBlock;

  ...
}
```

**Comment by matt3o** [comment]
@ddxl123  Not a maintainer, but I think you may have to pass in the cutom builder into the Document.toPlainText() call, see the function header:
`String toPlainText([Iterable<EmbedBuilder>? embedBuilders, EmbedBuilder? unknownEmbedBuilder])`
Maybe that helps to correctly convert the custom embed? Good luck! Matthias
