### ISSUE TITLE
Cannot build on iOS: Error (Xcode): Framework 'quill_native_bridge' not found

### ISSUE THREAD

**Issue by bloemy7** [singerdmx/flutter-quill#2352]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.8.5

### Steps to reproduce

1. Added 10.8.5 flutter_quill to my `pubspec.yaml`
2. Run `flutter run` on a physical iOS device

### Expected results

The app would build

### Actual results

The app fails with:
```
Could not build the precompiled application for the device.
Error (Xcode): Framework 'quill_native_bridge' not found
```

### Additional Context

This just started happening to me, I'm not sure if it's due to a flutter version change or anything else but now I'm unable to build anymore. Any thoughts? Thanks!

**Comment by bloemy7** [comment]
I don't even know exactly why but after resetting a bunch of stuff it's working again for now.

**Comment by EchoEllet** [comment]
> why but after resetting a bunch of stuff 

Running `flutter pub upgrade` should fix any related issues.
