### ISSUE TITLE
Error type Null is not a subject of type 'Object'

### ISSUE THREAD

**Issue by rymesaint** [singerdmx/flutter-quill#2357]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.8.5

### Steps to reproduce

Create ordered list
1. A
2. B
3. C

### Expected results

1. A
2. B
3. C

### Actual results

Error Null is not subtype of type 'Object'

This is how the result of database

[{"insert": "A"}, {"insert": null, "attributes": {"list": "ordered"}}, {"insert": "B"}, {"insert": null, "attributes": {"list": "ordered"}}, {"insert": "C"}, {"insert": null, "attributes": {"list": "ordered"}}, {"insert": "D"}, {"insert": null, "attributes": {"list": "ordered"}}, {"insert": "E"}, {"insert": null, "attributes": {"list": "ordered"}}]

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by EchoEllet** [comment]
@rymesaint 

This is still an issue, why it was closed?

**Comment by rymesaint** [comment]
i've found the problem the documentation is using jsonEncode method to make {"insert" : null} into {"insert":  "\n"} which i did it before like this 
```dart
document.toDelta().toJson()
```
when it should be like this
```dart
jsonEncode(document.toDelta().toJson())
```
