### ISSUE TITLE
 [Mobile] How do I customize RawKeyboardListener? 

### ISSUE THREAD

**Issue by phuongtinhbien** [singerdmx/flutter-quill#237]
How do I customize RawKeyboardListener. I did the same in example but QuillEditor uses the different FocusNode with RawKeyboardListener. So that it can't listen any key's event when typing.

Please support keyboard listener.

**Comment by mbenci** [comment]
In the example only on web RawKeyboardListener triggers event onKey, on android and iOS does not triggered events.
