### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by boinxi** [singerdmx/flutter-quill#238]
Hey, I came across this project and tried it out a few days ago.
I tried using it for editing RTL rich text and found some weird behavior happaning.
My Code:

``` dart
class _MyHomePageState extends State<MyHomePage> {
  QuillController _controller = QuillController.basic();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Directionality(
        textDirection: TextDirection.rtl,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              QuillToolbar.basic(controller: _controller),
              Expanded(
                child: Container(
                  child: QuillEditor.basic(
                    controller: _controller,
                    readOnly: false,
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
````

# The resault:
The problem here is that bulletpoints, numbered list and checkboxes are aligned to the left instead of being to the ritgh of the text.  

![exmpl](https://user-images.githubusercontent.com/57293916/119458083-0b9a8080-bd45-11eb-8529-b372b375bd65.jpeg)

Did someone had a similar issue or a fix for the problem?
Thanks for your time.

**Comment by jongkb** [comment]
+1 I'm seeing this issue too.

Similar issue was also reported in #152. I'm not sure why that issue was closed though.

**Comment by boinxi** [comment]
The mentioned issue (#152) was marked as duplicate.
The duplicate issue i assumed he was talking about is (#196 ) and it was closed after the author of the issue found a fix for the problem he had.
I think the #196 issue is referring to a totally different problem and was mistakenly closed.

The text alighnment bug is still occurring and i cannot get it right even after wrapping my widget in Directionality so this issue should stay oped...
Thanks again for any help regarding this issue.

**Comment by boinxi** [comment]
anyone here?

**Comment by singerdmx** [comment]
not supporting

**Comment by mehrdad-shokri** [comment]
Please do

**Comment by ketan10592** [comment]
@mehrdad-shokri you can find your Solution here,
Check out my example here : https://github.com/ketan10592/flutter_quill_example
you can also find how to add (@)mention and (#)HashTag in flutter_quill.
<img width="445" alt="Screenshot 2022-05-02 at 6 00 32 PM" src="https://user-images.githubusercontent.com/60574739/166249339-74ccecb2-2205-4fbe-9e4c-0655c5a527c6.png">
