### ISSUE TITLE
Show image and video upload button on web

### ISSUE THREAD

**Issue by Tsovinar2000** [singerdmx/flutter-quill#2380]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I don't see image and video buttons on tool bar

**Comment by EchoEllet** [comment]
Can you provide more context? Such as what you did, code snippet, a screenshot.

**Comment by Tsovinar2000** [comment]
> Can you provide more context? Such as what you did, code snippet, a screenshot.

Sure. This is the code 
![image](https://github.com/user-attachments/assets/f2e7668f-95ab-4e51-9beb-19ce456f35ae)

And this is the result 

![image](https://github.com/user-attachments/assets/e7cdcfd9-2eaf-428e-ad4d-eee7f9de2bad)

**Comment by Tsovinar2000** [comment]
> The image and video embed buttons are provided in [flutter_quill_extensions](https://pub.dev/packages/flutter_quill_extensions):
> 
> ```dart
> QuillToolbar.simple(
>   configurations: QuillSimpleToolbarConfigurations(
>     embedButtons: FlutterQuillEmbeds.toolbarButtons(),
>   ),
> ),
> ```

seems it has issue with the web 

![image](https://github.com/user-attachments/assets/bd9ae5d1-83b8-4909-9e9f-5111ecf49283)

**Comment by EchoEllet** [comment]
Use the latest version of `flutter_quill` and `flutter_quill_extensions` (10.8.5) and run `flutter pub upgrade`.

**Comment by Tsovinar2000** [comment]
> Use the latest version of `flutter_quill` and `flutter_quill_extensions` (10.8.5) and run `flutter pub upgrade`.

Thanks package installed after updating.
But during adding image appears error

https://github.com/user-attachments/assets/512b112b-392b-425d-ad32-9156b7ebcb00

**Comment by EchoEllet** [comment]
Did you pass the embed builders of the image and video to the `QuillEditor`?

```dart
Expanded(
  child: QuillEditor.basic(
    configurations: QuillEditorConfigurations(
      embedBuilders: kIsWeb ? FlutterQuillEmbeds.editorWebBuilders() : FlutterQuillEmbeds.editorBuilders(),
    ),
  ),
)
```

Refer to the [usage instruction of flutter_quill_extensions](https://pub.dev/packages/flutter_quill_extensions#-usage).

If you already did, I need the full stack trace with the log and the platform you're using (likely running on Windows).

**Comment by Tsovinar2000** [comment]
> Did you pass the embed builders of the image and video to the `QuillEditor`?
> 
> ```dart
> Expanded(
>   child: QuillEditor.basic(
>     configurations: QuillEditorConfigurations(
>       embedBuilders: kIsWeb ? FlutterQuillEmbeds.editorWebBuilders() : FlutterQuillEmbeds.editorBuilders(),
>     ),
>   ),
> )
> ```
> 
> Refer to the [usage instruction of flutter_quill_extensions](https://pub.dev/packages/flutter_quill_extensions#-usage).
> 
> If you already did, I need the full stack trace with the log, the platform you're using (likely running on Windows), and the related code snippet of the usage.

Thanks so much! It helped me to build editor. 
And last question . After sending cotoller vallue to backend, how then I can show it with view mode only ?

**Comment by EchoEllet** [comment]
**To save the document**:

```dart
final String json = jsonEncode(_controller.document.toDelta().toJson());
// Submit the JSON Delta
```

**To load the document**:
```dart
// Load the previously stored JSON Delta
final String json = ...;

_controller.document = Document.fromJson(jsonDecode(json));
```

**To change the read-only mode**:

```dart
_controller.readOnly = true; // Or false
```

**Comment by Tsovinar2000** [comment]
> **To save the document**:
> 
> ```dart
> final String json = jsonEncode(_controller.document.toDelta().toJson());
> // Submit the JSON Delta
> ```
> 
> **To load the document**:
> 
> ```dart
> // Load the previously stored JSON Delta
> final String json = ...;
> 
> _controller.document = Document.fromJson(jsonDecode(json));
> ```
> 
> **To change the read-only mode**:
> 
> ```dart
> _controller.readOnly = true; // Or false
> ```

Thanks!!
