### ISSUE TITLE
Clipboard image pasting not working correctly due to plainText check before

### ISSUE THREAD

**Issue by Maksim-Nikolaev** [singerdmx/flutter-quill#2383]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

11.0.0-dev.12

### Steps to reproduce

1. Install the example from https://github.com/singerdmx/flutter-quill/blob/master/example/lib/main.dart
2. Get image into clipboard, for example by taking a screenshot on Android
3. Paste the image into the editor
4. Image data is transcribed as plain text and is not inserted as image block

### Expected results

Insert an image if "onImagePaste" is defined. (Currently only works with network images / img urls)

* On the video is expected result, fixed locally.
https://github.com/user-attachments/assets/c202ba4e-8881-4283-99a8-34fe9d70f838

### Actual results

Currently that will be ignored due to check of "plainText", which is not null when we have image data in clipboard.

* Here is the video with current result
https://github.com/user-attachments/assets/5f557de6-d858-4cdc-aac2-0ed7bdd04825

**Comment by EchoEllet** [comment]
This is the same issue as #2323?

**Comment by Maksim-Nikolaev** [comment]
After double checking you are right, the issue & source of problem seems to be the same. I probably overlooked it due to phrasing before creating my own issue.

> The image URL will be stored in the document JSON, and how it will be loaded depends on your image embed implementation. If you're using flutter_quill_extensions, you can overimage provider builder.

What I meant with that the current implementation only works with network images is that when we grab the image from the web it gets the "image url" property which is pasted as plain text and then rendered within the image embed. If you would pass an image from paint, like in #2385 , the mechanism doesn't work. 

And probably my wording was incorrect here: 

> Insert an image if "onImagePaste" is defined. (Currently only works with network images / img urls)

Since the image pasting still worked via **plainText** and not **onImagePaste** in case with network images.
