### ISSUE TITLE
App crash without throwing error when insert serveral utf-8 emoji characters

### ISSUE THREAD

**Issue by Danny-Hoang** [singerdmx/flutter-quill#2386]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.8.2

### Steps to reproduce

I just have a quill editor with basic setup, and some button to insert emoji to the editor on clicked. 
When click at very low speed, it seems ok. But, when insert emoji at normal speed, the app crashed after serveral emojis inserted. Emoji characters is just utf-8 emoji.

### Expected results

The app does not crashed when insert emoji characters.

### Actual results

The app crashed when insert  emoji characters.

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by Danny-Hoang** [comment]
I did fixed it by when insert an emoji I insert an "empty space" next to it:
Sample code:
onSelect: (emoji) {
          insertCharacterAtCursor(
              "$emoji\u200B"); // \u200B is empty space character
        }
But you can investigate why. Because this is a hacky way to resolve the issue.

**Comment by EchoEllet** [comment]
Can you share the console log or the output of the error that occurs on the crash?

**Comment by EchoEllet** [comment]
We don’t have enough details to investigate and resolve this issue. Closing it for now, but feel free to open a new issue with more information.
