### ISSUE TITLE
这个编辑器能不能支持一下鸿蒙系统啊现在需要非常大呀

### ISSUE THREAD

**Issue by shanshen6** [singerdmx/flutter-quill#2388]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

希望支持鸿蒙系统

### Proposal

希望支持鸿蒙系统

**Comment by EchoEllet** [comment]
Currently, it's unsupported, need more details about the issue to solve.

Consider sharing them in English. Closing the issue though feel free to file a new issue.

**Comment by EchoEllet** [comment]
Related #2389
