### ISSUE TITLE
Resize image

### ISSUE THREAD

**Issue by ajxcodergit** [singerdmx/flutter-quill#2397]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.8.5

### Steps to reproduce

Hi, I'm using quill to insert images. But when I resize the image (especially after uploading it via Delta) it doesn't work or creates too much space. I'd like to know how to solve it. Thanks,

### Expected results

When making the change, resize the image correctly, and do not create a margin between the items above it.

### Actual results

The first insertion (without editing) generates extra space, and when I edit it, it doesn't work.

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
Can you provide a video or a image example about this?

**Comment by EchoEllet** [comment]
Closing the issue as we didn't receive a response, however, if you still have a question, consider creating a discussion. Related #2248
