### ISSUE TITLE
markdown to quill 

### ISSUE THREAD

**Issue by hina06botify** [singerdmx/flutter-quill#2398]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.23

### Steps to reproduce

  Future<quill.QuillController> getQuillControllerFromMarkdown(String markdown) async {
    // Create a Markdown document with required configurations
    final markdownDocument =
        md.Document(encodeHtml: true, withDefaultBlockSyntaxes: true, withDefaultInlineSyntaxes: true);
// Parse the markdown string to build the document structure
    markdownDocument.parseLines(markdown.split('\n')); // Splitting the markdown string by line and parsing it

    // Pass the Markdown document to MarkdownToDelta
    final converter = MarkdownToDelta(markdownDocument: markdownDocument);

    // Convert Markdown to Delta
    final delta = converter.convert(markdown);
    print("json delta:---------${delta.toJson()}");
    // Convert Delta to JSON (List<dynamic>)
    final deltaJson = delta.toJson();
    print("json deltaJson:---------$deltaJson");

    // Create and return a QuillController
    return quill.QuillController(
      document: quill.Document.fromJson(deltaJson),
      selection: const TextSelection.collapsed(offset: 0),
    );
  }

  Future<void> _loadMarkdown() async {
    _controller = await getQuillControllerFromMarkdown(widget.resultTxt);
    setState(() {});
  }
  this is my logic to use markdown in quill editor but header,italic,bold etc style not comes with given markdown responce 

### Expected results

![Screenshot 2024-11-26 at 12 25 02 PM](https://github.com/user-attachments/assets/3f7bb697-86a4-4e07-b4e6-caae76387e8c)
i want same as it 
markdown render in quilleditor 

### Actual results

![Screenshot 2024-11-26 at 12 28 29 PM](https://github.com/user-attachments/assets/72d3edd4-83f2-47e5-90a0-0c303034d301)
this is my responce in this markdown not render with all style 

### Additional Context

I/flutter (16940): json delta:---------[{insert: # Exploring the Life and Legacy of Mahatma Gandhi
I/flutter (16940): 
I/flutter (16940): Mahatma Gandhi's life and work stand as a poignant testament to the power of peaceful resistance and social change. Born in 1869 in Porbandar, India, Mohandas Karamchand Gandhi would become an enduring symbol of non-violent protest and a catalyst for global movements advocating civil rights and justice. Gandhi's journey was marked by a steadfast belief in the potential of non-violence, a principle he would call &quot;Ahimsa,&quot; to challenge oppression and bring about transformative societal shifts. His role as a leader of India's struggle for independence from British rule has left indelible footprints on history's sands, solidifying his status as a paragon of ethical leadership and change }, {insert: (IJELS), attributes: {link: https://ijels.com/upload_document/issue_files/13IJELS-103202431-Footprints.pdf}}, {insert: 
I/flutter (16940): . In an era rife with conflict and division, Gandhi's life and ideology continue to inspire individuals and

**Comment by EchoEllet** [comment]
Thank you for the report, markdown is no longer supported on newer versions, it has been deprecated and removed in v11, consider the alternative [markdown_quill](https://pub.dev/packages/markdown_quill). 

> Flutter Quill version
> 9.5.23

BTW, what is the blocker that prevents using newer versions? If it's a compatibility issue we may be able to solve it.

**Comment by hina06botify** [comment]
nothing else, i'm already send u photo markdown not display with style it's display look like normal text

**Comment by hina06botify** [comment]
and also a new version of how can display markdown give me example plz

**Comment by EchoEllet** [comment]
Could you clarify why you're using an outdated version of Flutter Quill?

>  i'm already send u photo markdown not display with style it's display look like normal text

You're using the experimental support of markdown support, which has been deprecated and is no longer supported, removed in version `11.x.x`.

> and also a new version of how can display markdown give me example plz

Refer to the package [markdown_quill](https://pub.dev/packages/markdown_quill), I'm not sure what you mean, but if you want to load markdown, convert the markdown to `Delta` and then load it. See [Input / Output](https://github.com/singerdmx/flutter-quill#-input--output) for more details.
