### ISSUE TITLE
How can I support formulas?

### ISSUE THREAD

**Issue by ddxl123** [singerdmx/flutter-quill#2399]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How can I support formulas? I saw that the merged content has an `https://github.com/singerdmx/flutter-quill/issues/155` attribute, but I actually couldn’t find this attribute in practice. `showFormulaButton `

**Comment by EchoEllet** [comment]
They are no longer supported, deprecated, and removed in v11. Refer to [Custom Embed Blocks](https://github.com/singerdmx/flutter-quill/blob/master/doc/custom_embed_blocks.md) to implement them.
