### ISSUE TITLE
[Web] 

### ISSUE THREAD

**Issue by guruprakashIT** [singerdmx/flutter-quill#242]
My issue is about [Web] **Color Picker Pop context**

I have tried running `example` directory successfully before creating an issue here.

When i choose a color in color picker, instead of pop the current context, it will pop out the background page context

![image](https://user-images.githubusercontent.com/41444416/119665859-6cfc4580-be52-11eb-966a-eab32bbc0562.png)

it will redirect to previouse page

here is the issue **rootNavigator**

Like in datepicker useRootNavigator

**Comment by reke592** [comment]
Hi, my issue in web is I can't scroll the color picker to reset the color to black.

![image](https://user-images.githubusercontent.com/17094894/133019577-092e0cc4-f951-41a0-9e1d-dfb16d07eb8c.png)
