### ISSUE TITLE
[Mobile]targetChild should not be null

### ISSUE THREAD

**Issue by cbahai** [singerdmx/flutter-quill#243]
A quick delete in the editor will cause this error.

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following message was thrown building _TextSelectionHandleOverlay(dirty, dependencies:
flutter: [_EffectiveTickerMode, _InheritedCupertinoTheme], state:
flutter: _TextSelectionHandleOverlayState#446ea(ticker inactive)):
flutter: targetChild should not be null
flutter:
flutter: The relevant error-causing widget was:
flutter:   MediaQuery
flutter:   file:///Users/mac/Desktop/workplace/Projects/flutter/app/main/lib/application.dart:222:26
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderEditableContainerBox.childAtPosition (package:flutter_quill/src/widgets/editor.dart:1002:7)
flutter: #1      RenderEditor.preferredLineHeight (package:flutter_quill/src/widgets/editor.dart:877:19)
flutter: #2      _TextSelectionHandleOverlayState.build (package:flutter_quill/src/widgets/text_selection.dart:396:45)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
flutter: #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
flutter: #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
flutter: #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
flutter: #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
flutter: #19     StatelessElement.update (package:flutter/src/widgets/framework.dart:4655:5)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
flutter: #22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
flutter: #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
flutter: #26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5596:32)
flutter: #27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
flutter: #30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
flutter: #32     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
flutter: #33     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
flutter: #34     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
flutter: #35     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #36     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #37     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter: #41     _invoke (dart:ui/hooks.dart:163:10)
flutter: #42     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
flutter: #43     _drawFrame (dart:ui/hooks.dart:126:31)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by isiyemijoe** [comment]
Please has there been aby fix to this

**Comment by adamkoch** [comment]
Also seeing this issue, @singerdmx - any reason why it was closed? Is it fixed?

**Comment by singerdmx** [comment]
Whoever simply pastes error message without any other information should be ashamed

**Comment by adamkoch** [comment]
I can't comment for the original poster, but I am happy to try and repro and provide more details.

**Comment by adamkoch** [comment]
I am able to reproduce in the iOS simulator. I couldn't seem to get it to trigger on a real iPhone but I was using a production build so the error may be suppressed or end up in crash reporting. It also doesn't appear to repro every single time.

I am using flutter-quill 1.9.1.

1. Open up screen with flutter-quill editor
2. Type some text
3. Double-click to select all text
4. Hit delete on keyboard to remove text

This leads to exception thrown:
https://github.com/singerdmx/flutter-quill/blob/master/lib/src/widgets/editor.dart#L1140

Which traces back to `preferredLineHeight()`:
https://github.com/singerdmx/flutter-quill/blob/master/lib/src/widgets/editor.dart#L989

Called in `build()` of `text_selection.dart`:
https://github.com/singerdmx/flutter-quill/blob/master/lib/src/widgets/text_selection.dart#L447

```
The following message was thrown building _TextSelectionHandleOverlay(dirty, dependencies: [_InheritedCupertinoTheme, _EffectiveTickerMode], state: _TextSelectionHandleOverlayState#421eb(ticker inactive)):
targetChild should not be null

The relevant error-causing widget was: 
  MaterialApp file:///Users/adam/src/app/lib/screens/root.dart:192:12
When the exception was thrown, this was the stack: 
#0      RenderEditableContainerBox.childAtPosition (package:flutter_quill/src/widgets/editor.dart:1140:7)
#1      RenderEditor.preferredLineHeight (package:flutter_quill/src/widgets/editor.dart:989:19)
#2      _TextSelectionHandleOverlayState.build (package:flutter_quill/src/widgets/text_selection.dart:447:45)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
...
====================================================================================================
```

**Comment by cbahai** [comment]
@singerdmx I already said that, a quick delete in the editor will cause this error. You can copy a piece of text and then hold down the delete key. This happens on iOS emulators.
Do you have any comprehension problems, or your inability to solve the problem. I see the source code is written very bad, standard updates are often not followed. I've already considered giving up using your plugin.
