### ISSUE TITLE
[Mobile] Saving the text to device storage as file (ex. txt)

### ISSUE THREAD

**Issue by mocchalatte99** [singerdmx/flutter-quill#244]
this is actually not an issue, i just started learning flutter a view weeks ago.
i created an Android App for my project.

so, i've created an editor page succesfully, and i want to save the data that have been typed on the editor to my device storage and after it's saved, i can access the file from my device file manager.
the file must be saved as extension file (ex: txt files).

i hope i got a detail explaination for this,.. 
and hope somebody could help me, i really need it!

sorry for my bad english.

**Comment by friebetill** [comment]
To access the text, you must assign a `QuillController` to the `QuillEditor`:
```dart
  late QuillController _controller;
  @override
  void initState() {
    super.initState();
    _controller = QuillController.basic();
  }

  @override
  Widget build(BuildContext context) {
    return QuillEditor(
        controller: _controller,
        /* ... */
    );
  }
```

You can then access the text using `_controller`:
```dart
final text = _controller.document.toPlainText();
```
Look [here](https://flutter.dev/docs/cookbook/persistence/reading-writing-files) to save `text` to disk and read it.

**Comment by mocchalatte99** [comment]
thanks for the advice..
i'll try the code from path_provider library you'd mention..
if it's if not troublesome for you i'll ask some advice if some problem hapens later!

thank you very much..

**Comment by mocchalatte99** [comment]
haii... @friebetill 
i've tried your advice before and follow the tutorial about how to read and write data to file using path_provider Library.
but after all code i'd build, my save button did not work at all..
i try a lot of method to save data to a file in youtube but didn;'t work either..

im really confuse..
can you give me a code as example to implement flutter_quill and path_provider, then save the data i've type to a file in local directory with a button..

i really need your help.. 
thank you...
