### ISSUE TITLE
[Mobile] Warning: Operand of null-aware operation '!'

### ISSUE THREAD

**Issue by jemaineosia** [singerdmx/flutter-quill#246]
My issue is about [Mobile]

[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-SG)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

C:/Users/Jemaine/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_quill-1.3.1/lib/src/widgets/toolbar/image_button.dart:90:41:        
           Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
[        ]     final fileName = result.files.first.name!;

Please note that we are using stable channel.

**Comment by MoLuoPro** [comment]
C:/Users/Name/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-1.3.1/lib/src/widgets/toolbar/image_button.dart
in this source file
90: final fileName = result.files.first.name!;
It should be changed to ‘ final fileName = result.files.first.name; ’

Then it's OK , and could be exported to Android platform

**Comment by jemaineosia** [comment]
> C:/Users/Name/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_quill-1.3.1/lib/src/widgets/toolbar/image_button.dart
> in this source file
> 90: final fileName = result.files.first.name!;
> It should be changed to ‘ final fileName = result.files.first.name; ’
> 
> Then it's OK , and could be exported to Android platform

thank you! :)

**Comment by chainchelliah** [comment]
I too faced the same issue. This issue should be fixed since it prevents generating an APK file.

**Comment by friebetill** [comment]
Closed by https://github.com/singerdmx/flutter-quill/commit/ff93000041d8c4ca64a3b555cd8074441d5f1905, but a new version has yet to be released.

If you disagree, post a comment and I'll reopen the issue.
