### ISSUE TITLE
Title has a mistake

### ISSUE THREAD

**Issue by MoLuoPro** [singerdmx/flutter-quill#247]
![20210531174028](https://user-images.githubusercontent.com/55039286/120175206-888f9380-c238-11eb-8cc7-c6afb929ac28.png)
in fact, it should be:
![yes](https://user-images.githubusercontent.com/55039286/120175414-ca203e80-c238-11eb-9001-1325463c4f31.png)
In this version, it is normal to export windows, web and other platforms

and flutter_quill-1.3.1/lib/src/widgets/toolbar/image_button.dart 
 has an error in exporting to android
row90: final fileName = result.files.first.name!;
changing to “ final fileName = result.files.first.name; ” is OK

**Comment by MoLuoPro** [comment]
"flutter run" is ok,
but there are still mistakes in "flutter build apk"

**Comment by singerdmx** [comment]
PR is welcome
