### ISSUE TITLE
Link error in editor page

### ISSUE THREAD

**Issue by mbenci** [singerdmx/flutter-quill#248]
Abnormal behavior in the sample app when I try to insert a link in the editor page.
I select a word, insert link and apply, the word now has the link style, but if I reselecting it and click again on the link button the link field is empty and I can not remove the link style.

**Comment by VladimirMitso** [comment]
Hi @singerdmx. I'm also experiencing this issue in `1.7.2`. Please let us know about progress on this. Thanks.

**Comment by li3317** [comment]
Hello @mbenci @VladimirMitso would you mind explaining what you mean by cannot remove the link style ? Is the clear format button not working or what's the expected behavior you're hoping to achive? Thanks!

**Comment by VladimirMitso** [comment]
Hi @li3317. Main issue for me was link wasn't working. By clicking on it nothing was happening.

**Comment by singerdmx** [comment]
It only happens in read only

**Comment by singerdmx** [comment]
> Abnormal behavior in the sample app when I try to insert a link in the editor page.
> I select a word, insert link and apply, the word now has the link style, but if I reselecting it and click again on the link button the link field is empty and I can not remove the link style.

@mbenci Can you clarify how to repro?

**Comment by singerdmx** [comment]
Closing due to no response
