### ISSUE TITLE
toolbarIconSize Does Not Apply To Every Icon

### ISSUE THREAD

**Issue by Splashman777** [singerdmx/flutter-quill#251]
I am using QuillToolbar.basic() with toolbarIconSize of 24.0 but this size change only applies to about half of the icons. The bold/italics/unerdline/strikethrough icons remain the default size.

**Comment by friebetill** [comment]
Which version are you using? This should be fixed from version 1.3.1.

**Comment by Splashman777** [comment]
That fixed it! I was on version 1.3.0
