### ISSUE TITLE
[Mobile] Feature Request: Table View and editor

### ISSUE THREAD

**Issue by anshul-daffodil** [singerdmx/flutter-quill#253]
It would be great if we can support the table view in this. Assume we are using it as a blog where the user wishes to make a table inside the widget. This would be great add on

**Comment by Blquinn** [comment]
Does this issue being closed mean that there is a built in table editor?

**Comment by singerdmx** [comment]
It means it will not be done

**Comment by Tokenizer94** [comment]
This guy is so rude and close issues without any explanation.
