### ISSUE TITLE
Save Written Data to firebase

### ISSUE THREAD

**Issue by devDonald** [singerdmx/flutter-quill#26]
I am trying to build an article app and I need to save the data inputted to firebase or any server then retrieve it back. How can this be done?

**Comment by singerdmx** [comment]
check out https://github.com/singerdmx/flutter-quill/blob/master/app/lib/main.dart

**Comment by singerdmx** [comment]
https://github.com/singerdmx/flutter-quill/issues/4

**Comment by ArjanAswal** [comment]
@devDonald Extract the quill formatted data by `controller.document.toDelta()` and then save this data to Firestore. Or save the document and then upload it to firebase storage.

**Comment by devDonald** [comment]
Thank you for the quick response. I really appreciate. Let me try it out

**Comment by elaishane** [comment]
Hye dude I am not getting how to get the file from firebase storage and upload it. Can anybody send the codes for it?

**Comment by elaishane** [comment]
And it would be helpful if it could be asap. I need to submit this project by midnight

**Comment by singerdmx** [comment]
This is already answered above

**Comment by WingCH** [comment]
https://github.com/singerdmx/flutter-quill/issues/4#issuecomment-792231136
