### ISSUE TITLE
[Mobile] How can the code change the position of the cursor？

### ISSUE THREAD

**Issue by quinoxz** [singerdmx/flutter-quill#262]
My issue is about [Mobile]

How can the code change the position of the cursor, such as moving forward or backward, or making the cursor always at the end of the text after calling the controller. Document. Insert method? be deeply grateful

**Comment by Tristan-2021** [comment]
I show you a part of the code----
 return FutureBuilder<List<Feedst>>(
     future: _sericeCllFeets.getfeedPost(),
     builder: (context, snapshot) {
       if(!snapshot.hasData){
         return Center(child: CircularProgressIndicator(),);
       }
       List<Feedst> feets = snapshot.data!; 
       return _list( feets, _defaulStyles, context);
     }  
   );
  }
Widget  _list( List<Feedst> feets, _defaulStyles, context){
   return ListView.builder(
         itemCount: feets.length,
         itemBuilder: (context , index) {
      Document doc = Document.fromJson(jsonDecode(feets[index].data!));  
   
     _control.QuillController _controller = _control.QuillController(
       document: doc, selection: TextSelection.collapsed(offset: 0)  
     ); 
          return Column(
          mainAxisAlignment: MainAxisAlignment.start,   
          children : [
          SizedBox(height: 20.0,),
            SizedBox(height:10.0),
          Container(
            child: ListTile(
            title: Text('Jhon Roiguez', style: TextStyle(fontSize: 18.0),),
            leading:CircleAvatar() ,
            ),
          ),
          QuillSimpleViewer(
           controller: _controller, 
           truncateWidth: double.infinity,
           truncateHeight: 300,
          scrollBottomInset: 9.4,
          truncate: true,
           padding: EdgeInsets.all(10.0),
           customStyles: _defaulStyles,  
           ),
