### ISSUE TITLE
Newline character ("\n") takes a lot of space.

### ISSUE THREAD

**Issue by ArjanAswal** [singerdmx/flutter-quill#27]
The newline character takes a lot of space and fills the entire screen pretty quickly.
In my opinion it should take as much space as the normal line in a paragraph does.
Right now it is taking twice as much.

**Comment by singerdmx** [comment]
The code should be in default_styles, I suppose

**Comment by singerdmx** [comment]
Yeah, I agree. Are u able to find the fix?

**Comment by ArjanAswal** [comment]
`
  DefaultTextBlockStyle(
      this.style, this.verticalSpacing, this.lineSpacing, this.decoration);`

@singerdmx  Is it this [parameter?](https://github.com/singerdmx/flutter-quill/blob/9a0df5fd09ea9d4009911db57961b9b8942065f9/lib/widgets/default_styles.dart#L41)

**Comment by singerdmx** [comment]
Possible. Just try changing it

**Comment by singerdmx** [comment]
Possibly the verticalSpacing

**Comment by ArjanAswal** [comment]
@singerdmx  In the source code the 3rd parameter (which is lineSpacing) is set to Tuple2(0.0, 0.0). Then how come the newlines are so greatly spaced?

```
        paragraph: DefaultTextBlockStyle(
            baseStyle, baseSpacing, Tuple2(0.0, 0.0), null),
```

**Comment by singerdmx** [comment]
Let me double check one thing: is it between text block?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/108095079-5749d980-7034-11eb-81c2-d91c636370d7.png)


The code may be here

**Comment by ArjanAswal** [comment]
I have solved the issue by changing 

`
    Tuple2<double, double> baseSpacing = Tuple2(6.0, 10);
`

to:

`    
Tuple2<double, double> baseSpacing = Tuple2(0, 0);
`

**Comment by singerdmx** [comment]
If the rendering is satisfactory (if it does not break other components), just submit it

**Comment by ArjanAswal** [comment]
Rendering is satisfactory.

I just changed all the `baseSpacing` styles in my personal projects (heading 1,2,3 ... paragraph, list, bold, italic, etc) to ` Tuple2(0, 0)`.
I suggest we do the same in the source code as we don't want to assign any extra line spacing ourselves and leave that to the developer or user.

Should I proceed with this?

**Comment by singerdmx** [comment]
Yes, go ahead

**Comment by singerdmx** [comment]
Can you submit it to stable branch?

**Comment by ArjanAswal** [comment]
@singerdmx I only changed the baseSpacing of the paragraph attribute as other implementations were looking quite cramped.

**Comment by singerdmx** [comment]
Actually I think `Tuple2<double, double> baseSpacing = Tuple2(6.0, 0)` is better when it comes to checkbox

**Comment by singerdmx** [comment]
Tuple2(6.0, 0) macthes checkbox's style, which I think is better

**Comment by ArjanAswal** [comment]
> Actually I think `Tuple2<double, double> baseSpacing = Tuple2(6.0, 0)` is better when it comes to checkbox

You are right baseSpacing is actually pretty much necessary for checkboxes and lists. I was testing it out resently.
That is why in the commit I only changed the baseSpacing of the paragraph.

**Comment by singerdmx** [comment]
Oh I see

**Comment by singerdmx** [comment]
I submitted https://github.com/singerdmx/flutter-quill/commit/a5ce03501d9aa42d81d452184a06f5def0fd735e
Let me know if there is any issue

**Comment by ArjanAswal** [comment]
> I submitted https://github.com/singerdmx/flutter-quill/commit/a5ce03501d9aa42d81d452184a06f5def0fd735e
> Let me know if there is any issue

@singerdmx What attributes will be affected by this and to what degree?

**Comment by singerdmx** [comment]
I think it affects the spacing between text blocks

**Comment by ArjanAswal** [comment]
I actually tried manipulating this variable which you just changed in the commit.

The paragraph was looking normal and the newline character wasn't taking extra space. However, the checkboxes and the list became cramped. Hence, I only changed the paragraph spacing.

So you might wanna check that.

**Comment by singerdmx** [comment]
Cramped? hmm... it looks fine to me

**Comment by ArjanAswal** [comment]
> Cramped? hmm... it looks fine to me

Maybe I was just used to the previous styling in which everything was sort of spaced out.

Also, any chance we can replace tuple with normal line height parameter? Would make things a lot simpler in my opinion.

**Comment by singerdmx** [comment]
Yes, I agree. We should replace Tuple
