### ISSUE TITLE
[Mobile] FlutterQuillView

### ISSUE THREAD

**Issue by DonnC** [singerdmx/flutter-quill#272]
My issue is on Mobile

Hello, great package 🔥
I would like to view my flutter quill documents (call them, notes) in a list view, like a list of my notes which are rendered same as in the editor like how these github issues shows. 
I would like to know how to go about it or if there is any Implementation for this without using the editor,  something similar to ZefyrView just for rendering notes in a column or list or grid like displaying ToDos or notes.
Similar issue to [this zefyr issue](https://github.com/memspace/zefyr/issues/26)

**Comment by Tristan-2021** [comment]
return FutureBuilder<List<Feedst>>(
     future: _sericeCllFeets.getfeedPost(),
     builder: (context, snapshot) {
       if(!snapshot.hasData){
         return Center(child: CircularProgressIndicator(),);
       }
       List<Feedst> feets = snapshot.data!; 
       return _list( feets, _defaulStyles, context);
     }  
   );
  }
 Widget  _list( List<Feedst> feets, _defaulStyles, context){
   return ListView.builder(
         itemCount: feets.length,
         itemBuilder: (context , index) {
      Document doc = Document.fromJson(jsonDecode(feets[index].data!));  
   
     _control.QuillController _controller = _control.QuillController(
       document: doc, selection: TextSelection.collapsed(offset: 0)  
     ); 
          return Column(
          mainAxisAlignment: MainAxisAlignment.start,   
          children : [
          SizedBox(height: 20.0,),
            SizedBox(height:10.0),
          Container(
            child: ListTile(
            title: Text('Jhon Roiguez', style: TextStyle(fontSize: 18.0),),
            leading:CircleAvatar() ,
            ),
          ),
          QuillSimpleViewer(
           controller: _controller, 
           truncateWidth: double.infinity,
           truncateHeight: 300,
          scrollBottomInset: 9.4,
          truncate: true,
           padding: EdgeInsets.all(10.0),
           customStyles: _defaulStyles,  
           ),

**Comment by Tristan-2021** [comment]
I show you a part of the code----
return FutureBuilder<List>(
future: _sericeCllFeets.getfeedPost(),
builder: (context, snapshot) {
if(!snapshot.hasData){
return Center(child: CircularProgressIndicator(),);
}
List feets = snapshot.data!;
return _list( feets, _defaulStyles, context);
}
);
}
Widget _list( List feets, _defaulStyles, context){
return ListView.builder(
itemCount: feets.length,
itemBuilder: (context , index) {
Document doc = Document.fromJson(jsonDecode(feets[index].data!));

 _control.QuillController _controller = _control.QuillController(
   document: doc, selection: TextSelection.collapsed(offset: 0)  
 ); 
      return Column(
      mainAxisAlignment: MainAxisAlignment.start,   
      children : [
      SizedBox(height: 20.0,),
        SizedBox(height:10.0),
      Container(
        child: ListTile(
        title: Text('Jhon Roiguez', style: TextStyle(fontSize: 18.0),),
        leading:CircleAvatar() ,
        ),
      ),
      QuillSimpleViewer(
       controller: _controller, 
       truncateWidth: double.infinity,
       truncateHeight: 300,
      scrollBottomInset: 9.4,
      truncate: true,
       padding: EdgeInsets.all(10.0),
       customStyles: _defaulStyles,  
       ),
