### ISSUE TITLE
How to disable softwrap  and enable horizontal scroll  ？

### ISSUE THREAD

**Issue by muyuballs** [singerdmx/flutter-quill#285]
My issue is about [Mobile]

How to disable softwrap  and enable horizontal scroll  ？

**Comment by florianh01** [comment]
Set 

`multiRowsDisplay: false,`

in QuillToolbar.basic()

**Comment by muyuballs** [comment]
> Set
> 
> `multiRowsDisplay: false,`
> 
> in QuillToolbar.basic()

not QuillToolbar，how to disable QuillEditor  content softwrap？

**Comment by singerdmx** [comment]
Not supported

**Comment by muyuballs** [comment]
> Not supported

tks
