### ISSUE TITLE
Cancel last character typed

### ISSUE THREAD

**Issue by dalton5** [singerdmx/flutter-quill#287]
Hi,

How can I cancel the last character typed?

I am using this but can't cancel the last character.

How can I do it?

        `RawKeyboardListener(
              focusNode: FocusNode(),
              onKey: (event) {
                if ( controller.richTextController.plainTextEditingValue.text.length >
                    10) {
                  FlushBarNotifierService.instance.streamController.add(
                      FlushBarNotifierModel(NotifType.Api,
                          title: L.localize('Maximum characters reached')));
            // cancel last character
                }`

**Comment by dalton5** [comment]
Hi,

You closed the issue but is there a solution?

**Comment by singerdmx** [comment]
You are welcome to submit a PR.
But we are not planning to support it.

**Comment by dalton5** [comment]
Is there then a possibility to define maximum count of characters?
