### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by tony-bringardner** [singerdmx/flutter-quill#297]
My issue is about [Mobile]

I have tried running `example` directory but it fails to build.

When I try to build for android OR IOS I get the following error.

Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../Work/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../Work/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
                            ^
../../.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../Work/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../Work/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);

### I am using the master channel. Here is the git info.

flutter-quill % git checkout master && git log 
M	example/ios/Pod-file
M	example/ios/Runner.xcodeproj/project.pbxproj
M	example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
M	example/ios/Runner.xcworkspace/contents.xcworkspacedata
D	example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
M	example/lib/pages/home_page.dart
M	example/lib/widgets/demo_scaffold.dart
M	example/pubspec.yaml
Already on 'master'
Your branch is up to date with 'origin/master'.
commit 2aa577ca58ff3400cc7ab6b37097883f978bf752 (HEAD -> master, origin/master, origin/HEAD)
Author: Xin Yao <singerdmx@gmail.com>
Date:   Tue Jul 13 09:26:13 2021 -0700

                            ^
### My Flutter environment looks like this:
octor --verbose
[✓] Flutter (Channel master, 2.4.0-5.0.pre.78, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.4.0-5.0.pre.78 at /Users/tony/Work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aeb251e1d0 (9 hours ago), 2021-07-16 06:21:04 -0400
    • Engine revision 32e3e844cd
    • Dart version 2.14.0 (build 2.14.0-321.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tony/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile)                    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPad Pro (12.9-inch) (5th generation) (mobile) • 58A83C59-E553-4EEA-A3A6-FD49AAE3BFD7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)                                • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

### I'm using Android Studio running on an iMac.
Android Studio 4.2.2
Build #AI-202.7660.26.42.7486908, built on June 23, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: external.system.auto.import.disabled=true, suggest.all.run.configurations.from.context=true
Non-Bundled Plugins: CVS, Dart, org.jetbrains.kotlin, io.flutter

**Comment by singerdmx** [comment]
Use stable

**Comment by tony-bringardner** [comment]
I'm sure I should understand your response but, I missing something.
I only see master and dev channels.  I'm not a git-guru so how can I get the stable version?

**Comment by singerdmx** [comment]
Stable channel

**Comment by tony-bringardner** [comment]
I do not see a Stable channel in git.  Can you help me find it?

Here’s what I get when I try to check it out.

flutter-quill % git checkout Stable
error: pathspec 'Stable' did not match any file(s) known to git

git checkout stable
error: pathspec 'stable' did not match any file(s) known to git
