### ISSUE TITLE
indent take effect for all lines not only first line.

### ISSUE THREAD

**Issue by li-xiaoyin** [singerdmx/flutter-quill#3]

**Comment by singerdmx** [comment]
looking into it

**Comment by singerdmx** [comment]
Indentation works, not just in the first line.
Could you provide examples to clarify the issue please?

**Comment by singerdmx** [comment]
Could you provide delta string for us to look into?

**Comment by li-xiaoyin** [comment]
if the line is too long, all of auto wrapped lines will be take indent effect. i expect only first line has indent and other auto wrapped lines not.

**Comment by singerdmx** [comment]
Understood. But our behavior has to be the same as React Quill.

![image](https://user-images.githubusercontent.com/122956/104185013-35bc5900-53c9-11eb-92c5-bb79dcde8f6c.png)


You can try http://jsfiddle.net/JoshAshby/92r4C/3/

**Comment by singerdmx** [comment]
It seems that on the web React Quill is doing the same. Then we do not want to make any difference.

**Comment by li-xiaoyin** [comment]
ok thx . and can you give me some suggestion for implements this effect.  like custom attributes and so on . how to do this.

**Comment by singerdmx** [comment]
You seem to want to add two spaces in front of the line?

**Comment by li-xiaoyin** [comment]
yes i attempt to add \t or space in the front of the line, but is looks not very well. The effect of Indent is good but i can not find the source code about that. how can i implements the effect as same as indent?

**Comment by singerdmx** [comment]
I don't know

**Comment by li-xiaoyin** [comment]
Thank you all the same
