### ISSUE TITLE
Default keyboard has no auto-correction etc.

### ISSUE THREAD

**Issue by jonmountjoy** [singerdmx/flutter-quill#30]
Hello!

Can I change the default keyboard type that Flutter Quill is using?  It's current one seems quite strange.

The default keyboard doesn't seem to understand the language I'm typing in.  In general, I'd expect to see auto-correction etc. as one does when types in a box.

In a Flutter textfield, I can specify a keyboard type to use with `keyboardType: TextInputType.text,`.  

Searching this repo, I don't even find the word "keyboard". 

Any advice appreciated!

**Comment by singerdmx** [comment]
Is it about web or mobile?

**Comment by jonmountjoy** [comment]
Mobile - sorry that I didn't specify.

**Comment by singerdmx** [comment]
Isn't it determined by mobile OS?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/108539810-52379500-7295-11eb-985f-93015996a847.png)


Maybe it is here?

**Comment by jonmountjoy** [comment]
Thank you for pointing the way, @singerdmx  - the problem is on line 377 where autocorrect is set to `false` for some reason.  Setting it to true makes everything behave much more sensibly!

**Comment by singerdmx** [comment]
@jonmountjoy do you want to submit a pull request for this?

**Comment by jonmountjoy** [comment]
@singerdmx you beat me to it!  As thanks, I would like to offer some extensions to the documentation:

https://github.com/singerdmx/flutter-quill/pull/33

**Comment by singerdmx** [comment]
Merged. Appreciate it :)
