### ISSUE TITLE
When the cursor is placed in front of bolded or italicized text, the buttons are highlighted respectively, but new signs added are not affected by this formatting

### ISSUE THREAD

**Issue by Rao2** [singerdmx/flutter-quill#312]
<img width="418" alt="Screenshot 2021-07-27 at 5 04 33 PM" src="https://user-images.githubusercontent.com/86937828/127150518-4e952ab1-c5b9-4706-9b77-5deb538cce69.png">

**Comment by singerdmx** [comment]
I think this behavior is expected
