### ISSUE TITLE
[Mobile] keyboard did not popup after image inserted

### ISSUE THREAD

**Issue by victor-bao** [singerdmx/flutter-quill#314]
In my app, I tried to insert an image and the problem is after that the keyboard did not show again. I listened the focus and console showed _focusNode.hasFocus is true. In this case, the only way get keyboard back is changing some text color. I am not sure it's a problem in my side or a library's bug, would you like to give me some suggestion? Thanks.

by the way, it happened in iOS, not simulator.

**Comment by phuongtinhbien** [comment]
```dart
    widget.focusNode.hasFocus ? widget.focusNode : FocusNode();
    FocusScope.of(context).unfocus();
    Timer(const Duration(milliseconds: 1), () {
      FocusScope.of(context).requestFocus(currentFocus);
    });
```
Add this code after handle image in order to focus on editor.

**Comment by victor-bao** [comment]
@phuongtinhbien Thanks a lot for your code, it works for me! 

May I have another question? Is any way to listen users delete the image they upload before submitting?

**Comment by singerdmx** [comment]
> ```dart
>     widget.focusNode.hasFocus ? widget.focusNode : FocusNode();
>     FocusScope.of(context).unfocus();
>     Timer(const Duration(milliseconds: 1), () {
>       FocusScope.of(context).requestFocus(currentFocus);
>     });
> ```
> 
> Add this code after handle image in order to focus on editor.

Should this code be in the repo? If you believe so, PR is welcome
