### ISSUE TITLE
Cursor does not move to the next line when the [Enter] button is pressed.

### ISSUE THREAD

**Issue by ArjanAswal** [singerdmx/flutter-quill#32]
In the flutter quill for web, this issue appears. However the new line gets appended. Cursor remains in the same position.

**Comment by singerdmx** [comment]
This is not issue on mobile, right?

**Comment by singerdmx** [comment]
Oops, wrong button closing it.

**Comment by ArjanAswal** [comment]
> This is not issue on mobile, right?

This issue is from the [link](https://bulletjournal.us/collab/?uid=W4LOcDQo) you referenced

**Comment by singerdmx** [comment]
That is quilljs's issue then.
That library is not something we maintain

**Comment by ArjanAswal** [comment]
> That is quilljs's issue then.
> That library is not something we maintain

quilljs is pretty stable though. I don't think an issue as basic as this could happen for a stable library. Also of that was the case, then this issue should appear in mobile as well.

**Comment by singerdmx** [comment]
So among the following three:

1. Flutter on mobile
2. Flutter on web
3. Quilljs on web

Which does this issue appear?

**Comment by ArjanAswal** [comment]
> So among the following three:
> 
> 1. Flutter on mobile
> 2. Flutter on web
> 3. Quilljs on web
> 
> Which does this issue appear?

The issue is appearing for the editor in the link you mentioned. Is that created in flutter quill?

![Screenrecorder-2021-02-20-01-19-03-556.gif](https://user-images.githubusercontent.com/64231789/108555113-0e876e80-731b-11eb-9ac5-4c9dce22ac9d.gif)

**Comment by singerdmx** [comment]
No it is not.
It is React-Quill https://www.npmjs.com/package/react-quill

**Comment by ArjanAswal** [comment]
Oh ok.
But if this is your project, you might wanna do something about this problem. Seems pretty serious to me. Maybe open the same issue on the bullet journal repo?
Closing.
