### ISSUE TITLE
 [Mobile] Attribute.justifyAlignment and Attribute.leftAlignment have problems in display

### ISSUE THREAD

**Issue by lanwufeng** [singerdmx/flutter-quill#320]
hello，I found that Attribute.justifyAlignment and Attribute.leftAlignment have problems in display，as this picture shows
https://i.loli.net/2021/08/04/B5jAJFDd8nkeslU.jpg

**Comment by gtyhn** [comment]
https://github.com/flutter/flutter/issues/35734
