### ISSUE TITLE
[Mobile][iOS] The keyboard not showing up after the image is chosen from the device

### ISSUE THREAD

**Issue by SeasonLeee** [singerdmx/flutter-quill#341]
The main problem is as stated in the title.

My issue is about [Mobile], and it's iOS specifically

I have tried running `example` directory successfully before creating an issue here.

And the issue reproduced in both the example from the package and our environment.

For further demonstration, here's a video recording of this case:

https://user-images.githubusercontent.com/13610283/129296896-0e270d11-5c39-43e5-b979-9343ee0a2446.MP4

As you can see, after the image is chosen from the device, the keyboard not showing up anymore no matter how I tap on the input area.

I have tried to use code like this to try to raise the keyboard up but none of the `requestFocus` method works...

```dart

      _quillController.addListener(() {

        if (MediaQuery.of(context).viewInsets.bottom == 0) {
         // method one:
          _editorFocusNode.requestFocus();
         // method two: and this two method I used them separately 
         // but the keyboard just fail to show up
          FocusScope.of(context).requestFocus(_editorFocusNode);
        }

      });

```

**Comment by li3317** [comment]
Hello, we can't seem to run into this issue on our end.
