### ISSUE TITLE
[Mobile] Is there any method to scroll to some word/offset ?

### ISSUE THREAD

**Issue by sagarkardani** [singerdmx/flutter-quill#345]
I want to find and highlight some words. Probably I would be able to highlight words somehow with controller or via some other methods.

Another thing I want is to jump to/scroll to previous and next instance of found words. I am unable to find any methods like `_controller.scrollToPosition()` or `_controller.scrollToOffset()`. Is there any such methods available in controller ?

Below is the screenrecording of expected behaviour.

https://user-images.githubusercontent.com/60609139/129385745-6beab317-0be9-44ca-94b7-c0b94cca4a44.mp4

Regards,
Sagar

**Comment by singerdmx** [comment]
You are welcome to submit a PR
