### ISSUE TITLE
[Mobile] Error: The method 'userUpdateTextEditingValue' isn't defined for the class 'TextSelectionDelegate'

### ISSUE THREAD

**Issue by vbabaria** [singerdmx/flutter-quill#347]
My issue is about [Mobile] on iOS simulator

When I try to run main.dart from example folder on fresh git copy, I get following error.
My speculation is somehow latest version conflicts with "TextSelectionDelegate" class from material library but I could be totally wrong since I am newbie on flutter. Would really appreciate any pointers here.

**Error: The method 'userUpdateTextEditingValue' isn't defined for the class 'TextSelectionDelegate'.**

**Detailed error stack**
  _/Users/vijay/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/ios/Storyboards/WebView.storyboard:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
    ../lib/src/widgets/text_selection.dart:206:9: Error: The method 'userUpdateTextEditingValue' isn't defined for the class 'TextSelectionDelegate'.
     - 'TextSelectionDelegate' is from 'package:flutter/src/services/text_input.dart' ('../../../../development/flutter/packages/flutter/lib/src/services/text_input.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'userUpdateTextEditingValue'._

I have tried running `example` directory successfully before creating an issue here.
yes - this error is on latest and fresh copy from git.

Please note that we are using stable channel on branch master. If you are using beta or master channel, use branch dev.
ok

**Details of my current flutter and dart versions**

Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (4 months ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3

**Comment by skotadia** [comment]
+1 - I have similar issue.

**Comment by singerdmx** [comment]
Please upgrade to Flutter 2.2.3 • channel stable

**Comment by vbabaria** [comment]
Thanks for the quick response. Our project has other third party widgets that don't work on latest flutter stable version (2.2.3) yet and i guess we are in a deadlock situation for upgrade : (

**Comment by vbabaria** [comment]
> Please upgrade to Flutter 2.2.3 • channel stable

Thanks for the quick response. Our project has other third party widgets that don't work on latest flutter stable version (2.2.3) yet and i guess we are in a deadlock situation for upgrade : (

**Comment by singerdmx** [comment]
Take a fork and revert this change https://github.com/singerdmx/flutter-quill/pull/271/files
