### ISSUE TITLE
[Mobile] Exception type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'num'

### ISSUE THREAD

**Issue by mtallenca** [singerdmx/flutter-quill#365]
Using version 1.9.3 of flutter_quill on iOS latest version, iPhone 12, flutter stable release build

document, nested bullets with indentation and last 2 bullets have only \n ...  on exit getting the json via

`  final json = _controller.document.toDelta().toJson() 

the delta 108 of 109 has incorrect attributes - list & indent look nested

{"insert":"\n","attributes":{"list":{"list":"bullet"},"indent":{"indent":1}}},
{"insert":"\n","attributes":{"list":"bullet","indent":1}}

loading the document - throws _InternalLinkedHashMap is not a int attempting to read the indent value

Please note that we are using <b>latest</b> flutter version in stable channel on branch master.

**Comment by yzxben** [comment]
In case anyone is interested, after playing around with this for a while I got an exact list of steps that cause this issue:

1. Write something in a bullet
2. Press Enter, write something else, and indent right
3. Press Enter, Enter, Backspace (cursor is now back on line 2), then again Enter, Enter
