### ISSUE TITLE
[Mobile] after inserting the image, the cursor should appear after the image instead of before it

### ISSUE THREAD

**Issue by SeasonLeee** [singerdmx/flutter-quill#366]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here. 

As stated in the title, and you can also see in this recorded video:

https://user-images.githubusercontent.com/13610283/130929124-b4d9922d-1bc4-46ca-889a-99894a765418.MP4

If the cursor placed before the image, it will make it really hard to create a new line for more content because it's really hard to place the cursor after the image inserted...

Thank you.

**Comment by singerdmx** [comment]
Try flutter_quill: ^2.0.3, see if it still appears

**Comment by singerdmx** [comment]
If you click on the area behind the image, the cursor will be behind it
