### ISSUE TITLE
Android Platform

### ISSUE THREAD

**Issue by sria-the-fury** [singerdmx/flutter-quill#368]
I have been facing a problem while implementing flutter_quill on the Android Platform
I have used` flutter_quill: ^1.9.5`

while I compile this code to getDeltaValue the cursor disappears after starting to write.
 ```dart
@override
void initState(){
    super.initState();
   _quillController.addListener((){
        setState((){
         setDeltaText = _quillController.document.toDelta();
         });
     });
}
```

Why is this happening?

**Comment by singerdmx** [comment]
Can you find out which version started this?
Try 1.9.4

**Comment by singerdmx** [comment]
can you try 1.9.0 and 1.9.1 and see which version is working?

**Comment by sria-the-fury** [comment]
I have tried these versions you told me.

> `flutter_quill: ^1.9.4`
> `flutter_quill: ^1.9.1`
> `flutter_quill: ^1.9.0`

The cursor disappears while starting to write.
Look at the Screencast


https://user-images.githubusercontent.com/40123204/131239396-153d286c-fc53-4cc9-939c-62d59de522d8.mp4



Is there any way to get updated deltaValue from QuillEditor without using this method?
 ```dart
@override
void initState(){
    super.initState();
   _quillController.addListener((){
        setState((){
         setDeltaText = _quillController.document.toDelta();
         });
     });
}
```

**Comment by singerdmx** [comment]
This is your own issue.
None of us have it
