### ISSUE TITLE
[Web] [Mobile] [Desktop] What is the hard-coded "32.0" in EditableTextBlock._getIndentWidth() for?

### ISSUE THREAD

**Issue by aldycool** [singerdmx/flutter-quill#373]
Hi,

My issue exists in [Web] + [Mobile] + [Desktop].

I cannot reproduce the issue in the `example` directory, because what I'm trying to do is not exist in the `example`, and  it is repeatedly mentioned "not supported" everywhere 😁 , which is the **Text Alignment** feature. I know it is not supported, but, this is kinda _badly_ needed, so... Well, anyway...

I'm implementing toolbars for left + center + right alignment, they all works perfectly, BUT, there's always a 32.0 pixel gap on the left side like the following screenshots (left alignment + centered + right alignment):

![image](https://user-images.githubusercontent.com/8155468/131515430-42e8aaa5-9a38-4f2b-96b4-db85b0111e91.png)

![image](https://user-images.githubusercontent.com/8155468/131515572-d69edc5a-6eb4-4273-bab9-e7ce5904ea72.png)

![image](https://user-images.githubusercontent.com/8155468/131515633-9ca27109-85d6-4b7e-a16a-42321c8086e3.png)

I've found the reason why there's a 32.0 gap, which is caused by this:

https://github.com/singerdmx/flutter-quill/blob/a585a880cf9f7c3d65014dc52f8511676c420d94/lib/src/widgets/text_block.dart#L220

The method above first checks that if the text block attributes contains `indent` or `blockQuote`, then some additional indentation is applied. This is alright and make sense. But, at the end, if it is not either of them, there's always an additional 32.0 pixel indent that is always applied to the returned value.  **The question is**: am I missing something here,  what is the reasoning for this default 32.0 pixel value?? Thanks.

**Comment by singerdmx** [comment]
You can submit a PR for web only. Use `kIsWeb`

**Comment by aldycool** [comment]
Hi @singerdmx, alright I will make the PR. But, is there a reason why only for `kIsWeb`? Why not for all platforms? If the reason is something that would be too troublesome to describe, I'll understand.

**Comment by singerdmx** [comment]
I thought this issue is web only.
If you are able to test all three platforms - [Web] [Mobile] [Desktop], then you don't need `kIsWeb`

**Comment by aldycool** [comment]
Alright, understood, I'm able to test on all platforms (macos, android, ios, web, windows , linux). 

About the text alignment support (left + center + right + justify), since I've finished implementing it in my fork, should I include them in the PR? Probably by demontrating it in the `example`, of course it will be checked first on all platforms.

But, if you only allow just the removal of `32.0` in the PR, it's also fine for me. What do you think?

**Comment by singerdmx** [comment]
Sure you can include it.
I thought we already have support for alignment, don't we?

**Comment by aldycool** [comment]
Yes, we do already have support, you already have `Attributes` for `align`. But, there is no example on how to use it easily in the `example`. In fact, in the toolbar button classes located in `lib/src/widgets/toolbar` folder, I cannot find a suitable button class for alignment purpose, so I've created one here.

I'll send the PR as soon as it is ready, thanks for your insights!

**Comment by singerdmx** [comment]
https://github.com/singerdmx/flutter-quill/blob/master/example/assets/sample_data.json#L221-L247

We don't have toolbar button yet but data format is supported

**Comment by aldycool** [comment]
Yes correct, that means now it's just the buttons. Hopefully nothing goes wrong in the tests. I'll let you know.
