### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by ArjanAswal** [singerdmx/flutter-quill#38]
There are 3 areas where the UX of editor can be improved :

1. When checking / unchecking the checkboxes, the text line moves up / down.

2. Keyboard pops when clicking the heading dropdown button unnecessarily.

3. Tab button doesn't moves the text to the far right end and stops mid-way.

**Comment by singerdmx** [comment]
Regarding #2, what do you mean?
Regarding #3, is that about web?

**Comment by ArjanAswal** [comment]
#2 Whenever I want to change the text size to heading 1 or 2,3... the keyboard pops.

#3 This happens in mobile. Maybe the button is not called tab but margin I am not sure.

**Comment by singerdmx** [comment]
Mobile has "Tab" button?

**Comment by singerdmx** [comment]
#1 is tracked in https://github.com/singerdmx/flutter-quill/issues/28

**Comment by ArjanAswal** [comment]
> Mobile has "Tab" button?

[This button](https://material.io/resources/icons/?search=format_indent&style=baseline)

**Comment by singerdmx** [comment]
2 is resolved.
Please create individual issues for 1 and 3 if they still apply
