### ISSUE TITLE
Unintended major version bump with 2.x.x releases breaks semantic versioning for dependencies

### ISSUE THREAD

**Issue by mgyarmathy** [singerdmx/flutter-quill#383]
With the recent major version bump in this project from `1.9.6` to `2.0.0`, some dependent packages (such as [delta_markdown](https://github.com/friebetill/delta_markdown/blob/master/pubspec.yaml)) are no longer considered compatible with future releases. In order to adhere to Semantic Versioning guidelines (https://semver.org/), I'd suggest backporting any `2.0.x` releases to `1.10.x`, since the `2.0.x` releases did not introduce any incompatible API changes.

**Comment by singerdmx** [comment]
The behavior of `block` is changed in version 2.x.x
