### ISSUE TITLE
ERROR:flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43: Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer

### ISSUE THREAD

**Issue by bestprize999** [singerdmx/flutter-quill#385]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
/D:/download/flutter_v2.2.3/.pub-cache/hosted/pub.flutter-io.cn/flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43: Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent', which does not match the corresponding type, 'PointerEvent', in the overridden method, 'DragGestureRecognizer.addAllowedPointer'.
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/D:/download/flutter_v2.2.3/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/D:/download/flutter_v2.2.3/packages/flutter/lib/src/gestures/events.dart').
Change to a supertype of 'PointerEvent', or, for a covariant parameter, a subtype.
  void addAllowedPointer(PointerDownEvent event) {
                                          ^
/D:/download/flutter_v2.2.3/packages/flutter/lib/src/gestures/monodrag.dart:256:8: Context: This is the overridden method ('addAllowedPointer').
  void addAllowedPointer(PointerEvent event) {
       ^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\download\flutter_v2.2.3\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\download\flutter_v2.2.3\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by bestprize999** [comment]
D:\AndroidStudioProjects\gongdao>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

**Comment by bestprize999** [comment]
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pull_to_refresh: ^2.0.0
  provider: ^6.0.0
  dio: ^4.0.0
  http: ^0.13.3
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  dio_http2_adapter: ^2.0.0
  shared_preferences: ^2.0.7
  flutter_quill: ^2.0.3
  path_provider: ^2.0.3
  filesystem_picker: ^2.0.0-nullsafety.0
  file_picker: ^4.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by singerdmx** [comment]
Upgrade flutter to 2.5.0
