### ISSUE TITLE
Editor view bounces in 0.3.1

### ISSUE THREAD

**Issue by JimTim** [singerdmx/flutter-quill#39]
In the new 0.3.1 release, unfortunately, the view always jumps up. Probably it scrolls to the bottom every time a letter is entered. This brings a constant scrolling effect.

https://user-images.githubusercontent.com/6737248/108962235-c056d000-7678-11eb-87cf-fa90b94c9ad4.mp4

I think it has to do with the following commit: https://github.com/singerdmx/flutter-quill/commit/471c1cb7ee542977b777b0fc10cbaa5cfb35ddea

In version 0.3.0 the problem does not occur and therefore I went back to this release. So no stress.

**Comment by singerdmx** [comment]
> the view always jumps up

Do you mean the keyboard jumps up?

**Comment by singerdmx** [comment]
OK, let me look into this

**Comment by singerdmx** [comment]
I cannot repro what you have.
Can you try "app" folder code, please?
Also I am unsure why the placeholder "Add Content" does not go away.

**Comment by singerdmx** [comment]
Is there something special about the "Title"? It seems to have a light blue background.
What exactly is its attribute?
Something is different than what we have.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/108963766-67167e80-762f-11eb-9a42-b6dfd30af4bd.png)

**Comment by singerdmx** [comment]
@JimTim submitted https://github.com/singerdmx/flutter-quill/commit/a5e1194bb34c8436454e70e6b474dbc1c9fe23df
