### ISSUE TITLE
flutter_colorpicker error

### ISSUE THREAD

**Issue by stephane-couget** [singerdmx/flutter-quill#391]
Hello everyone,

﻿I just installed flutter_quill and at compile time I got this kind of error.

> ../../.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43: Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent', which does not match the corresponding type, 'PointerEvent', in the overridden method, 'DragGestureRecognizer.addAllowedPointer'.
[        ]  - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../development/flutter/packages/flutter/lib/src/gestures/events.dart').
[        ]  - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../development/flutter/packages/flutter/lib/src/gestures/events.dart').
[        ] Change to a supertype of 'PointerEvent', or, for a covariant parameter, a subtype.
[        ]   void addAllowedPointer(PointerDownEvent event) {
[        ]                                           ^
[        ] ../../development/flutter/packages/flutter/lib/src/gestures/monodrag.dart:256:8: Context: This is the overridden method ('addAllowedPointer').
[        ]   void addAllowedPointer(PointerEvent event) {

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)

 flutter_colorpicker: '>=0.5.0 <=0.6.0'

I love your plugin, see you soon

**Comment by singerdmx** [comment]
Upgrade flutter to stable 2.5.0
