### ISSUE TITLE
Question : Value

### ISSUE THREAD

**Issue by angwandi** [singerdmx/flutter-quill#4]
What's the best way to get the exact value from QuillEditor then save to firebase or something? 

And also, how to display the exact value back from Firebase or some sort of backend?

I am using _controller.document.toPlainText(); and saving only simple string

**Comment by singerdmx** [comment]
What do you mean by the exact value from QuillEditor ?
You can get delta of the document.

**Comment by angwandi** [comment]
@singerdmx I used this `_controller.document.toDelta().toString();`  to only get :

"insert⟨ Thanks for the invite and I ⟩ insert⟨ ⏎ ⟩ + {indent: 1} insert⟨ Thank u for ⟩ insert⟨ ⏎ ⟩ + {indent: 1, list: ordered} insert⟨ Best friend ⟩ insert⟨ ⏎ ⟩ + {indent: 1, list: ordered} insert⟨ Thanks for the invite and I appreciate it and I appreciate it and ⟩ insert⟨ ⏎⏎ ⟩ + {indent: 1}"

**Comment by levy0601** [comment]
@angwandi 

1. If you want to store the plain text (which mean it will lose all the format info like list, code block and link), you can use  `_controller.document.toPlainText()`
2. This library use `quill_delta` as an internal data type to store all the formatting information as well as the text. Therefore, what you see from the `_controller.document.toDelta().toString();` is the representation of the Delta data type.  If you want to store the get the exact value from QuillEditor, you should use `_controller.document.toDelta().toJson().` Noted that you will need to use an additional library to show the exact format from Detla to see what you see in the screenshot. 

![](https://user-images.githubusercontent.com/31923567/104321671-ff7bf800-54f4-11eb-8938-3a59e93a8b3e.png)

check out [https://quilljs.com/docs/delta/](url) playground section for more information

**Comment by angwandi** [comment]
@levy0601 thank you so much. any suggestions for library to display in flutter?

**Comment by levy0601** [comment]
@angwandi 

> Noted that you will need to use an additional library to show the exact format from Detla to see what you see in the screenshot.

What I mean by the additional library is to show the delta in the web browser 

If you are talking about display it in Flutter, you can just use our library. 

check the following example for display a delta in flutter-quill;

```
Document _document =Document.fromJson( delta );
QuillController _controller = QuillController(
            document: _document, selection: TextSelection.collapsed(offset: 0));
FocusNode _focusNode = FocusNode();
QuillEditor(
            controller: _controller,
            scrollController: ScrollController(),
            scrollable: true,
            focusNode: _focusNode,
            autoFocus: true,
            readOnly: true,
            enableInteractiveSelection: true,
            expands: false,
            padding: EdgeInsets.zero,
          )
 ```

you can also set the QuillEditor as ReadOnly view by passing in `readOnly: true,`

**Comment by angwandi** [comment]
@levy0601 thank you. let me give it a go.

**Comment by singerdmx** [comment]
@angwandi let us know if you have any issue. We are happy to resolve it for you.

**Comment by angwandi** [comment]
@singerdmx 

`E/flutter (10374): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument: Instance of 'Operation'
E/flutter (10374): #0      convertPlatformException (package:cloud_firestore_platform_interface/src/method_channel/utils/exception.dart:13:5)
E/flutter (10374): #1      MethodChannelDocumentReference.set (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:43:13)
E/flutter (10374): <asynchronous suspension>
E/flutter (10374): #2      CollectionReference.add (package:cloud_firestore/src/collection_reference.dart:45:5)
E/flutter (10374): <asynchronous suspension>`

getting this error when trying to save on Firestore using :
`data[AppEventFields.longDescription] =
                    _longDescriptionQuillController.document.toDelta().toJson();`

**Comment by singerdmx** [comment]
This seems more of Filestore issue, which we are unfamiliar with

**Comment by WingCH** [comment]
in example [sample_data.json](https://github.com/singerdmx/flutter-quill/blob/master/app/assets/sample_data.json)
![image](https://user-images.githubusercontent.com/19588517/110232090-a1005280-7f56-11eb-82c8-8345426662ac.png)

when i call `_controller.document.toDelta().toJson()`

![image](https://user-images.githubusercontent.com/19588517/110232079-93e36380-7f56-11eb-91cc-26e8255f87d0.png)

How can I get the same format as sample_data.json?

**Comment by singerdmx** [comment]
This is more of a question how to prettify json string. You can check out https://pub.dev/packages/pretty_json
Those questions are not related to flutter-quill and please DO NOT ask those here.

**Comment by WingCH** [comment]
thanks for your quick reply.

I think I understand the real problem with @angwandi 
we need use`jsonEncode` to convert `Delta` to json format and then save to firebase

```
String jsonString = jsonEncode(_controller.document.toDelta().toJson());
```

**Comment by ArjanAswal** [comment]
> This is more of a question how to prettify json string. You can check out https://pub.dev/packages/pretty_json
> Those questions are not related to flutter-quill and please DO NOT ask those here.

@singerdmx I think we should pin the firebase issue as it is pretty common.
Also I think we should create a issue template so that people don't ask unrelated questions.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/110232568-51c50e00-7ed3-11eb-867a-1cdcc493eded.png)


This is already in README
