### ISSUE TITLE
How to get only String to Display it in TextField ?

### ISSUE THREAD

**Issue by c49is** [singerdmx/flutter-quill#40]
This is not an issue. Just a doubt. I just store data from quill editor as json in sqflite database and retrieve it, show it in Text widget.  But what happens, it shows unknown characters when image or something stored in data. when extracted through toPlainText() method.

So how to get only text which typed not any customizations. Thanks

**Comment by singerdmx** [comment]
Could you paste what u got for `toPlainText`? And point out where is the issue?

**Comment by singerdmx** [comment]
Also did you try` jsonEncode(_controller.document.toDelta().toJson())`

**Comment by c49is** [comment]
`var content = jsonEncode(_controller.document.toDelta().toJson());` 

I just stored content in sqflite database and retrieved it like below.

` var contentjson = jsonDecode(content);
    Document document = Document.fromJson(contentjson);
    String plainText = document.toPlainText();
`
I got this 

<img width="379" alt="image file" src="https://user-images.githubusercontent.com/79581617/109084327-98757400-772d-11eb-858d-c2fb479d95d9.png">

**Comment by singerdmx** [comment]
Weird, are you sure you are using our code?
The special space comes from Zefyr

**Comment by c49is** [comment]
no way... There is no zefyr package in my pubspec.yaml. 

`
  Expanded(
              child: Container(
                padding: EdgeInsets.all(8.0),
                child: QuillEditor.basic(
                  controller: _controller,
                  readOnly: readMode, // change to true to be view only mode
                ),
              ),
            ),
`

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/109086721-06378680-76c1-11eb-8378-1608177a3ee2.png)


Found it

**Comment by c49is** [comment]
Thank god.. I was checking my whole code and cleaned the project.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/109087066-9bd31600-76c1-11eb-9432-6016d1db76e5.png)

What do you want here?

**Comment by singerdmx** [comment]
`value.type` is `image`
`value.data` is `url of image`

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/109087166-d046d200-76c1-11eb-8041-12524d1d1c6a.png)

**Comment by c49is** [comment]
here you are returning URL or type of image. but I want only plain text. if the image is found no need to show image URL. just avoid that and paste only user typed text as normal content.

**Comment by singerdmx** [comment]
So what exactly do you want as output of toPlainText() for image node?

**Comment by c49is** [comment]
just an empty space character or '' .

**Comment by c49is** [comment]
may be \u200B -

**Comment by singerdmx** [comment]
Oh, could u send a pull request?

**Comment by c49is** [comment]
I am so noob with git. So I doubt it. If I change toPlainText() Embed in with empty space, is that okay? That will work just Like I said?

**Comment by singerdmx** [comment]
Are you able to test it with your change?
You can just paste screen shot here of your change

**Comment by c49is** [comment]
yes I can do that.

**Comment by singerdmx** [comment]
after you verified it, I will submit your change

**Comment by c49is** [comment]
I just changed toPlainText() - to a blank space. it works but with a little long space and occured a image loading exception. So I am checking now is it wrong with my code or yours. I will comment later.

**Comment by c49is** [comment]
unable to load asset image exception

**Comment by singerdmx** [comment]
I am closing this since I am unsure what to do about it

**Comment by CatHood0** [comment]
This issue persists? I think that this can be do it directly using [dart-quill-delta-simplify.](https://pub.dev/packages/dart_quill_delta_simplify) You can see `toPlain` method [here](https://github.com/FlutterQuill/dart-quill-delta-simplify/blob/master/documentation/extras.md)
