### ISSUE TITLE
In Quill Editor not work proper for Bold, Italic and Underline [Mobile]

### ISSUE THREAD

**Issue by Ak23598** [singerdmx/flutter-quill#404]
I use latest flutter_quill in my flutter app.

When i use bold, italic and underline then its working fine but after that i tried to edit then its not work proper.

please check this video for more explanation about this bug.

[video link](https://bit.ly/2Xn4Yyc)

I use this **flutter_quill: ^2.0.4**

**Comment by singerdmx** [comment]
Please Submit a PR

**Comment by MagTuxGit** [comment]
@singerdmx This can be closed I guess.
