### ISSUE TITLE
[Mobile] Error - Failed assertion ... 'firstChild != null': is not true when deleting all data in the editor

### ISSUE THREAD

**Issue by joebImagine** [singerdmx/flutter-quill#405]
My issue is about [Mobile]

In `flutter 2.5.1` and using the latest `flutter_quill 2.0.5`, I get an error and the app breaks when I delete all text from the editor using the delete key on a Mac using the emulator: 

`'package:flutter_quill/src/widgets/editor.dart': Failed assertion: line 1133 pos 12: 'firstChild != null': is not true`  

As an example here is a very simple version of the editor that is throwing the error: 

```
class QuillTest extends StatelessWidget {
  const QuillTest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    QuillController? _controller = QuillController(
      document: Document(),
      selection: const TextSelection.collapsed(offset: 0),
    );
    return Column(
      children: [
        QuillToolbar.basic(controller: _controller),
        Expanded(
          child: Container(
            child: QuillEditor.basic(
              controller: _controller,
              readOnly: false, // true for view only mode
            ),
          ),
        )
      ],
    );
  }
}
```
For the test I pass it directly to `main.dart`

**Comment by joebImagine** [comment]
After further testing, the issue only presents itself when using the simulator and typing on a physical keyboard

**Comment by joebImagine** [comment]
Why was this closed though?  Seems like it would still making testing a pain?

**Comment by ajayintelivita** [comment]
Still the same error is shown in the real device
