### ISSUE TITLE
[Mobile] Provide a useRootNavigator parameter when defining the widgets

### ISSUE THREAD

**Issue by prakharb10** [singerdmx/flutter-quill#409]
My issue is about [Mobile]

I'm using Navigator 2.0 in my app. In addition to that, I have nested navigators in my app. The dialog(s) that are shown when choosing a color use the root navigator by default due to which pressing the back button with the dialog open navigates the underlying page but does not close the dialog which should be the intended behavior.

Suggestion: Allow the user to define whether to use the root navigator or not by specifying `useRootNavigator`

**Comment by singerdmx** [comment]
Please Submit a PR
