### ISSUE TITLE
Unable to get dropdown instead of tabs

### ISSUE THREAD

**Issue by hannahlutd** [singerdmx/flutter-quill#411]
The docs have an example picture with the heading style buttons on the Toolbar being inside a dropdown, but they are showing up as separate buttons. I see nothing in the docs about changing the separate buttons to a dropdown, and the default toolbar has them as separate buttons.

This may just be an issue of lack of documentation.

I am running on Flutter 2.5

<img width="503" alt="Screen Shot 2021-09-28 at 9 03 57 AM" src="https://user-images.githubusercontent.com/54041467/135102647-087e3f0e-d3a7-42c4-98b1-2478699d60ac.png">

![Screen Shot 2021-09-28 at 9 07 53 AM](https://user-images.githubusercontent.com/54041467/135103675-1b2cdbab-c9c2-4c9d-8dae-98cd752b967f.png)

**Comment by hbali** [comment]
@hannahlutd was this solved? 
@singerdmx why was this issue closed? I'm also trying to solve the above problem but no solution so far
