### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Nolence** [singerdmx/flutter-quill#42]
Hi ! I'm hoping this issue can be used to follow updates on nullsafety. Currently, there are still several dependencies that are not migrated and might be considered blocking.

```
dart pub outdated --mode=null-safety

Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name                 Current    Upgradable  Resolvable           Latest               

direct dependencies:        
file_picker                  ✗2.1.6     ✗2.1.6      ✓3.0.0-nullsafety.2  ✓3.0.0-nullsafety.2  
flutter_colorpicker          ✗0.3.5     ✗0.3.5      ✓0.4.0-nullsafety.0  ✓0.4.0-nullsafety.0  
flutter_keyboard_visibility  ✗4.0.4     ✗4.0.4      ✓5.0.0-nullsafety.2  ✓5.0.0-nullsafety.2  
image_picker                 ✗0.6.7+22  ✗0.6.7+22   ✓0.7.0               ✓0.7.0               
photo_view                   ✗0.10.3    ✗0.10.3     ✗0.10.3              ✗0.10.3              
quill_delta                  ✗2.0.0     ✗2.0.0      ✗2.0.0               ✗2.0.0               
quiver_hashcode              ✗2.0.0     ✗2.0.0      ✗2.0.0               ✗2.0.0               
string_validator             ✗0.1.4     ✗0.1.4      ✓0.2.0-nullsafety.0  ✓0.2.0-nullsafety.0  
tuple                        ✗1.0.3     ✗1.0.3      ✓2.0.0-nullsafety.0  ✓2.0.0-nullsafety.0  
universal_html               ✗1.2.4     ✗1.2.4      ✗1.2.4               ✗1.2.4               
url_launcher                 ✗5.7.10    ✗5.7.10     ✓6.0.0               ✓6.0.0               

7  dependencies are constrained to versions that are older than a resolvable version.
To update these dependencies, edit pubspec.yaml, or run `dart pub upgrade --null-safety`.
```

`quill_delta` has a active pull request for null safety [here](https://github.com/pulyaevskiy/quill-delta-dart/pull/20). `photo_view` also has an [active pr for null safety](https://github.com/fireslime/photo_view/pull/375). As for quiver_hashcode, here is a [comment](https://github.com/QuiverDart/quiver_hashcode/pull/10#pullrequestreview-586799412) that says people should instead rely on `quiver` instead which is already migrated to null safety. This just leaves `universal_html` without an active PR.

## Edit

With quill_delta removed that leaves just:

- [ ] photo_view
- [ ] quiver_hashcode -> quiver
- [ ] universal_html

**Comment by singerdmx** [comment]
We are on channel stable.
We cannot upgrade package image_picker to 0.7.0  for example

**Comment by Nolence** [comment]
This would be referring to the `master` branch. Also do you think there could be a pre-release version that always follows master as you already have that branch? I remember `zefyr` had this conversation a few times as well and it always caused people headaches. If there's a pre-release version on pub, people can opt into that without having to file weird errors about something not working that was designed to work for stable. `pre-releases`, as far as I understand, don't have to be specifically about null safety

**Comment by singerdmx** [comment]
Default branch master is on channel master. To use channel stable, switch to branch stable. Branch master on channel master supports web.

**Comment by singerdmx** [comment]
Our pub is published based on stable branch, not master branch

**Comment by Nolence** [comment]
Sorry, I just meant to ask why not do this:

```yaml
  flutter_quill: 0.3.3  # This version follows stable branch
```

and then also always have a published [pre-released version](https://dart.dev/tools/pub/publishing#publishing-prereleases) like this:

```yaml
  flutter_quill: 0.3.3.dev-0  # This version follows master branch
```

If someone installs `flutter_quill` even without a version number they'll install the stable version. However, if they specify the `dev` version, they'll get the master branch one. If we also note this in the readme, I think it'll stop people from filing errors in the readme about SDK errors

**Comment by singerdmx** [comment]
@pengw00 could you work on this? And whatever @Nolence needs to update

@Nolence thanks for the suggestion

**Comment by singerdmx** [comment]
@Nolence can you check https://github.com/singerdmx/flutter-quill/commit/2122f9b7cdf75cb64e50c1c65accd1cf1fe209a6

**Comment by singerdmx** [comment]
@Nolence also check out https://github.com/singerdmx/flutter-quill/commit/08734a8ec36309a8e4cfb7f046c5ed3654543dfd

**Comment by singerdmx** [comment]
<img width="593" alt="1" src="https://user-images.githubusercontent.com/122956/109253603-fb562200-77a4-11eb-81c3-aa8a6517f8b4.png">

**Comment by Nolence** [comment]
It looks good to me :)

See comments on 2122f9b though
