### ISSUE TITLE
[Web] flutter beta needs more implementations related to copy/paste

### ISSUE THREAD

**Issue by klapauciusisgreat** [singerdmx/flutter-quill#423]
My issue is about [Web]

This is a heads up that the beta flutter version now requires more methods for EditorState.

When compiling 2.0.7 or 2.0.9 of quill, I get compilation errors like:

```
Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
class RawEditorState extends EditorState
```

```
% flutter --version
Flutter 2.6.0-5.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 400608f101 (5 weeks ago) • 2021-09-15 15:50:26 -0700
Engine • revision 1d521d89d8
Tools • Dart 2.15.0 (build 2.15.0-82.2.beta)```
```

I helped myself by adding this to the RawEditorState, but that's really not a stable solution.

```javascript
@override
  noSuchMethod(Invocation msg) => "got ${msg.memberName} "
      "with arguments ${msg.positionalArguments}";
```

I understand that you are not going to fix this right away, but I thought filing that for later would come handy for you.

**Comment by mcmikecreations** [comment]
Same issue, would be great to get this fixed ASAP

**Comment by singerdmx** [comment]
Please Submit a PR

**Comment by klapauciusisgreat** [comment]
I'm not sure how to interpret that. Implement a PR to override noSuchMethod hack ? That seems ill-advised.

A proper fix ? Unfortunately, I'm not understanding the code base enough (or flutter) to have any confidence, Sorry. I really wanted to give the developers a heads up in the hope that it will be useful to know about this future problem.
