### ISSUE TITLE
type 'double' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by lookdczar** [singerdmx/flutter-quill#43]
```
Operation next([num length = double.infinity]) {
    assert(length != null);

    if (_modificationCount != delta._modificationCount) {
      throw ConcurrentModificationError(delta);
    }

    if (_index < delta.length) {
      final op = delta.elementAt(_index);
      final opKey = op.key;
      final opAttributes = op.attributes;
      final _currentOffset = _offset;
      final actualLength = math.min(op.length - _currentOffset, length);
      if (actualLength == op.length - _currentOffset) {
        _index++;
        _offset = 0;
      } else {
        _offset += actualLength;
      }
      final opData = op.isInsert && op.data is String
          ? (op.data as String)
              .substring(_currentOffset, _currentOffset + actualLength)
          : op.data;
      final opIsNotEmpty =
          opData is String ? opData.isNotEmpty : true; // embeds are never empty
      final opLength = opData is String ? opData.length : 1;
      final int opActualLength = opIsNotEmpty ? opLength : actualLength;
      return Operation._(opKey, opActualLength, opData, opAttributes);
    }
    return Operation.retain(length);
  }
```

`next([num length = double.infinity]) `  length default is a double
but  ` Operation.retain` need a int

And `assert(length != null);` is useless

**Comment by singerdmx** [comment]
Where did you get this code?

**Comment by lookdczar** [comment]
It's in quill_delta-2.0.0/lib/quill_delta.dart, line 642

I'm trying to add text with code
_controller.replaceText(0, 4, 'data', TextSelection.collapsed(offset: 0));

**Comment by lookdczar** [comment]
> Where did you get this code?

It's in quill_delta-2.0.0/lib/quill_delta.dart, line 642

I'm trying to add text with code
_controller.replaceText(0, 4, 'data', TextSelection.collapsed(offset: 0));

**Comment by singerdmx** [comment]
I can copy the file out to our repo. It is just one file

**Comment by singerdmx** [comment]
What fix do you propose to make?

**Comment by lookdczar** [comment]
> What fix do you propose to make?

I'm not sure yet. I just hope I can add text to the editor with code.

**Comment by singerdmx** [comment]
submitted https://github.com/singerdmx/flutter-quill/commit/d603c46c45517ef48b7194fe32907b23b14cfeed

**Comment by singerdmx** [comment]
checkout https://github.com/pulyaevskiy/quill-delta-dart/issues/18

**Comment by singerdmx** [comment]
@lookdczar  please use https://github.com/singerdmx/flutter-quill/commit/e41b2c3b2023f17cc0ffbf1eeb0aff51ef1bc0e1
It is checked in.
Just use latest code.
Let me know if I can resolve this issue

**Comment by singerdmx** [comment]
Reopen it if there is still issue.
