### ISSUE TITLE
[Mobile] FAILURE when building app

### ISSUE THREAD

**Issue by Alcachofraz** [singerdmx/flutter-quill#434]
I'm using Flutter 2.6.0-11.0.pre • channel dev • https://github.com/flutter/flutter.git

Here is the log:

/E:/Users/pedro/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-2.0.13/lib/src/widgets/raw_editor.dart:100:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/E:/Users/pedro/Documents/flutter/packages/flutter/lib/src/services/text_input.dart:956:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
  void copySelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^^
/E:/Users/pedro/Documents/flutter/packages/flutter/lib/src/services/text_input.dart:936:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
  void cutSelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^
/E:/Users/pedro/Documents/flutter/packages/flutter/lib/src/services/text_input.dart:944:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
  Future<void> pasteText(SelectionChangedCause cause);
               ^^^^^^^^^
/E:/Users/pedro/Documents/flutter/packages/flutter/lib/src/services/text_input.dart:950:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
  void selectAll(SelectionChangedCause cause);
       ^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Users\pedro\Documents\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005     

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\Users\pedro\Documents\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

**Comment by singerdmx** [comment]
Please Submit a PR
