### ISSUE TITLE
[Mobile] failure when build or run the app

### ISSUE THREAD

**Issue by wildangery** [singerdmx/flutter-quill#439]
My issue is about [Mobile]

/C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-2.0.14/lib/src/widgets/raw_editor.dart:100:7:
Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/C:/Flutter/flutter/packages/flutter/lib/src/services/text_input.dart:956:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
  void copySelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^^
/C:/Flutter/flutter/packages/flutter/lib/src/services/text_input.dart:936:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
  void cutSelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^
/C:/Flutter/flutter/packages/flutter/lib/src/services/text_input.dart:944:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
  Future<void> pasteText(SelectionChangedCause cause);
               ^^^^^^^^^
/C:/Flutter/flutter/packages/flutter/lib/src/services/text_input.dart:950:8: Context: 'TextSelectionDelegate.selectAll' is defined here.

  void selectAll(SelectionChangedCause cause);
       ^^^^^^^^^
Failed to compile application.

what should I do?

**Comment by ShineYang** [comment]
Same issue. (⊙︿⊙)

**Comment by singerdmx** [comment]
Please Submit a PR
