### ISSUE TITLE
building example claims missing implementations

### ISSUE THREAD

**Issue by bchar19087** [singerdmx/flutter-quill#443]
After cloning the flutter-quill example and trying to build examples/lib/main.dart, I get

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../lib/src/widgets/raw_editor.dart:100:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
 
 
 Where would these supposedly implementations be?

**Comment by singerdmx** [comment]
Please Submit a PR
