### ISSUE TITLE
Choose an attachement

### ISSUE THREAD

**Issue by LearningPlus** [singerdmx/flutter-quill#446]
I've implemented the flutter quill to my note-taking app, and I see that it can't add any files other than an image or a video like a pdf, docs, audio file, and so on. Is there any solution for this?

I've used this package for picking files: https://pub.dev/packages/file_picker

**Comment by singerdmx** [comment]
Please Submit a PR

**Comment by LearningPlus** [comment]
What do you mean by PR?
