### ISSUE TITLE
Links like tel:

### ISSUE THREAD

**Issue by kostasoft** [singerdmx/flutter-quill#46]
Please remove the check for the correctness of the link when you click on it.
This check can and should be done in the onLaunchUrl handler

**Comment by singerdmx** [comment]
Instead of removing check, I think we should add tel to whitelist.
Can u submit a pull request for list of strings you want to handle, please?

**Comment by singerdmx** [comment]
```
  void _launchUrl(String url) async {
    if (!url.startsWith('http')) {
      url = 'https://$url';
    }
    await launch(url);
  }
```

Actually it is more complicated since we append https for any string not starting with http.
We should add logic here to handle `tel:` and other kind of URL like `tel`
Simply removing check is not acceptable.

**Comment by kostasoft** [comment]
If the link starts with tel: - the onLaunchUrl handler doesn't work at all.
At least make the handler triggered, users will remove the extra http themselves

Although it's a crutch. It would be more correct to add validation:
`!url.startsWith('http') && !url.startsWith('tel:') && !url.startsWith('mailto:') && ...`

**Comment by kostasoft** [comment]
Found an article on using scheme on mobile devices. It's a little outdated, but still.
https://beradrian.wordpress.com/2010/01/15/special-links/

**Comment by singerdmx** [comment]
@kostasoft check out https://github.com/singerdmx/flutter-quill/pull/47

**Comment by singerdmx** [comment]
@li3317  can you check https://github.com/singerdmx/flutter-quill/pull/47 and test it? Also expand the prefixes using https://beradrian.wordpress.com/2010/01/15/special-links/ .

**Comment by kostasoft** [comment]
Yes, of course, just tell me how to connect the new branch?
I now connect the plugin like this:
```
  flutter_quill:
    git:
      url: git://github.com/singerdmx/flutter-quill.git
      ref: master
```

**Comment by singerdmx** [comment]
change `ref: master` to `ref: launchUrl` ?

**Comment by singerdmx** [comment]
branch name is launchUrl

**Comment by singerdmx** [comment]
Another way, instead of using white list, we can use regex to check if it is substring after `http://` or `https://`. If true, prepend `https://`. 
But it may have edge cases.

**Comment by singerdmx** [comment]
It is safer to have white list, but we may need to maintain whitelist for new cases.

**Comment by kostasoft** [comment]
When I switch to the launchUrl branch, the project compiles with errors:
```
/C:/Users/kostasoft/AppData/Local/Pub/Cache/git/flutter-quill-a41198c96d6db822406d3ab38192b64cc15e2113/lib/widgets/text_selection.dart:201:43: Error: Too few positional arguments: 8 required, 7 given.
        child: selectionCtrls.buildToolbar(
                                          ^
/C:/Users/kostasoft/AppData/Local/Pub/Cache/git/flutter-quill-a41198c96d6db822406d3ab38192b64cc15e2113/lib/widgets/text_line.dart:63:41: Error: No named parameter with the name 'nullOk'.
        Localizations.localeOf(context, nullOk: true),
                                        ^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^


FAILURE: Build failed with an exception.
```

**Comment by singerdmx** [comment]
My bad, it was based off  master. Please let me redo it

**Comment by singerdmx** [comment]
@kostasoft I merged it to branch stable, just use stable for testing.

**Comment by kostasoft** [comment]
Should I switch back to the master branch?

**Comment by singerdmx** [comment]
`ref: stable`

**Comment by kostasoft** [comment]
Same thing. The project compiles with errors.
The same happens with versions 1.0.0-dev.1 and 0.3.3
Only the master branch directly from git compiles normally.

```
/C:/Users/kostasoft/AppData/Local/Pub/Cache/git/flutter-quill-96ececbebed89f19adcd4fd0e0132c0df0d7cd20/lib/widgets/text_selection.dart:201:43: Error: Too few positional arguments: 8 required, 7 given.
        child: selectionCtrls.buildToolbar(
                                          ^
/C:/Users/kostasoft/AppData/Local/Pub/Cache/git/flutter-quill-96ececbebed89f19adcd4fd0e0132c0df0d7cd20/lib/widgets/text_line.dart:63:41: Error: No named parameter with the name 'nullOk'.
        Localizations.localeOf(context, nullOk: true),
                                        ^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^


FAILURE: Build failed with an exception.
```

**Comment by singerdmx** [comment]
are you on channel stable?

**Comment by kostasoft** [comment]
Yes
```
  flutter_quill:
    git:
      url: git://github.com/singerdmx/flutter-quill.git
      ref: stable
#      ref: master
```

**Comment by singerdmx** [comment]
you may want clean local cache or sth

**Comment by singerdmx** [comment]
Do you know what flutter channel is?

**Comment by singerdmx** [comment]
https://stackoverflow.com/questions/51586259/which-channel-do-i-use-in-flutter-sdk

**Comment by kostasoft** [comment]
beta

**Comment by singerdmx** [comment]
there is no way you can run our code in beta

**Comment by kostasoft** [comment]
Your code on the master branch compiles fine

**Comment by singerdmx** [comment]
That is supposed for channel master

**Comment by singerdmx** [comment]
you can use flutter_quill: ^0.3.4

**Comment by kostasoft** [comment]
0.3.4 does not compile.
The errors are still the same

**Comment by singerdmx** [comment]
because you should use channel stable!

**Comment by kostasoft** [comment]
Using the flutter channel is not possible. The project needs Web support

**Comment by singerdmx** [comment]
Then master

**Comment by kostasoft** [comment]
master - too unstable
