### ISSUE TITLE
[Desktop] triple click on a word to select paragraph

### ISSUE THREAD

**Issue by matthiasn** [singerdmx/flutter-quill#468]
My issue is about selecting text on macOS. The expectation is that triple clicking a word selects the current paragraph, as is the case in most text editing applications I have tried. Is there a way to achieve the same behavior with `flutter_quill`?

I ran the `example` application and it is the same behavior there, which feels unnatural to me. Thanks! Great library overall.

**Comment by singerdmx** [comment]
@li3317  and I will take a look at it

**Comment by simonbengtsson** [comment]
Would also love to see this! This is not currently supported by flutter text fields either, but seems to be active work happening regarding this recently https://github.com/flutter/flutter/issues/63576
