### ISSUE TITLE
[Mobile] Failed assertion: line 30 pos 12: 'value.isInline || value.isIgnored || value.isEmpty'

### ISSUE THREAD

**Issue by xurc** [singerdmx/flutter-quill#473]
My issue is about [Mobile]

When copying and pasting from Wikipedia to Quill, you can get the following op:

```json
    {
      "attributes": {
        "script": "super",
        "color": "#0645ad",
        "background": "initial",
        "link": "https://ru.wikipedia.org/wiki/%D0%A0%D0%BE%D0%B4%D0%B8%D0%BE%D0%BD_%D0%A0%D0%B0%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2#cite_note-_37a3407c9d29c9c4-2"
      },
      "insert": "[2]"
    },
```

And got 
```
 assert(value.isInline || value.isIgnored || value.isEmpty,
        'Unable to apply Style to leaf: $value');
```

The problem is in the ```script``` attribute, it is ignored by flutter_quill, but combined with other attributes.

```dart
  bool get isInline => isNotEmpty && values.every((item) => item.isInline);

  bool get isIgnored =>
      isNotEmpty && values.every((item) => item.scope == AttributeScope.IGNORE);
```

Flags in assertion are formed through ```every```, that is, all attributes should be ignored or not. Not sure, but it might be worth changing this check so that ignored attributes are ignored and only inline affects the styling?

**Comment by singerdmx** [comment]
Could you submit a PR?
