### ISSUE TITLE
[Desktop] and [Mobile] Copy and Paste loses format

### ISSUE THREAD

**Issue by matthiasn** [singerdmx/flutter-quill#479]
When I try to copy and paste formatted text, the formatting is lost, and the text is instead pasted as plain text. This limits the usefulness for any serious usage.

I also tested with the latest version of the example app (both on an iPhone 12 Pro running iOS 15.1.1 and on Macbook Pro running macOS 12.0.1), and it is the same behavior there.

**Comment by singerdmx** [comment]
Could you let us know what format in particular is lost?
block style or inline?

**Comment by nikber84** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/28052262/145783868-b524f601-d3d3-4375-9370-b932c4a1434e.png)
But it insert correctly in bulletjournal.us
![image](https://user-images.githubusercontent.com/28052262/145784077-34477663-9a9b-4971-96fb-5f7465562448.png)

I used this code:
![image](https://user-images.githubusercontent.com/28052262/145784519-24ba061e-d692-4012-83b0-d2c09f378c3a.png)

Did I miss smth?

**Comment by matthiasn** [comment]
@singerdmx thanks for looking into this. For me both inline and block styles are lost, everything gets pasted as plain text.

**Comment by singerdmx** [comment]
Fixed by https://github.com/singerdmx/flutter-quill/commit/3a9630421eafc9deba98f96367d0f8ad49d6d157
