### ISSUE TITLE
Interactive selection work wrong

### ISSUE THREAD

**Issue by li-xiaoyin** [singerdmx/flutter-quill#5]
Both handler at the front of the range. The right way is one at the front and another at the end.

**Comment by singerdmx** [comment]
looking into it

**Comment by li3317** [comment]
Would you mean that the handles should be one at the start of the selected text and one at the end ?

**Comment by li-xiaoyin** [comment]
yes it should be but not now.  and I can not drag handler to adjust the selection

**Comment by li3317** [comment]
Could you provide an example regarding adjusting the handle? I believe the selection can be adjusted and the handles will show up at the front of the last line in text selection. Thank you!

**Comment by li-xiaoyin** [comment]
I try again with official demo just now. The selection can be adjusted but second handler don't move. It
 alway at the start of the selected text. is right ? We can compare with zefyr

![WechatIMG136](https://user-images.githubusercontent.com/6327200/104259849-36ceb280-54bd-11eb-8b40-96164f87051a.jpeg)

see zefyr implements: 

![WechatIMG137](https://user-images.githubusercontent.com/6327200/104260203-f7ed2c80-54bd-11eb-887d-1ea2a63ebdc7.jpeg)

**Comment by singerdmx** [comment]
Found the bug. Fixing

**Comment by singerdmx** [comment]
Fix is https://github.com/singerdmx/flutter-quill/commit/7c2da544c93c8b3e1987c058dbf28d49b9930318
Upgrading pub soon

**Comment by li-xiaoyin** [comment]
Thank you.
