### ISSUE TITLE
Bug: setState() called after dispose()

### ISSUE THREAD

**Issue by florianh01** [singerdmx/flutter-quill#50]
I found a bug when using QuillEditor inside a Stepper-Widget. 

I also have a suggestion for fixing: After adding `if (!mounted) return;` before `setState()` inside `raw_editor.dart` in line 904 & 960 the issue did not come up again.

Here is the error message:
`E/flutter (24393): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: setState() called after dispose(): RawEditorState#669f3(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
E/flutter (24393): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (24393): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (24393): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (24393): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1231:9)
E/flutter (24393): #1      State.setState (package:flutter/src/widgets/framework.dart:1266:6)
E/flutter (24393): #2      RawEditorState._onChangeTextEditingValue (package:flutter_quill/widgets/raw_editor.dart:905:5)
E/flutter (24393): #3      RawEditorState.initState.<anonymous closure> (package:flutter_quill/widgets/raw_editor.dart:704:9)
E/flutter (24393): #4      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (24393): #5      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (24393): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (24393): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (24393): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (24393): #9      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
E/flutter (24393): #10     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
E/flutter (24393): #11     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
E/flutter (24393): #12     _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (24393): #13     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (24393): #14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (24393): #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (24393): #16     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (24393): #17     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (24393): #18     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (24393): #19     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (24393): #20     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (24393): #21     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (24393): #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (24393): #23     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (24393): #24     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (24393): #25     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (24393): #26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (24393): #27     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (24393): #28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`

**Comment by singerdmx** [comment]
Do you have a pull request for the fix?
