### ISSUE TITLE
[Mobile] Not able to insert an image as a inline

### ISSUE THREAD

**Issue by Thuyamani20** [singerdmx/flutter-quill#511]
My issue is about when i insert the image its covering entire width, i like to insert as a inline image so i can write something beside the image instead of new line
![Screenshot_1638941790](https://user-images.githubusercontent.com/95735717/145154207-bfc51fc1-865a-461f-b847-4800e89be57e.png)

**Comment by singerdmx** [comment]
check https://github.com/singerdmx/flutter-quill#custom-size-image-for-mobile

**Comment by Thuyamani20** [comment]
Not able to implement this code, where to insert this code

**Comment by Thuyamani20** [comment]
> check https://github.com/singerdmx/flutter-quill#custom-size-image-for-mobile

how to implement it? no proper code is there like where to insert these code?

**Comment by singerdmx** [comment]
You are welcome to submit a PR
First add a button in toolbar for this

**Comment by suyie001** [comment]
> > check https://github.com/singerdmx/flutter-quill#custom-size-image-for-mobile
> 
> how to implement it? no proper code is there like where to insert these code?

so, how to customize the size of image?
