### ISSUE TITLE
Unable to compile app with flutter 2.8

### ISSUE THREAD

**Issue by subinsv** [singerdmx/flutter-quill#513]
flutter: 2.8 latest
Tested on: Android and iOS

With latest flutter 2.8, we cannot compile the app anymore with flutter_quill.

  ../../../../.pub-cache/hosted/pub.dartlang.org/flutter_quill-2.1.1/lib/src/widgets/raw_editor.dart:100:7: Error: The non-abstract class 'RawEditorState' is
    missing implementations for these members:
     - TextSelectionDelegate.copySelection
     - TextSelectionDelegate.cutSelection
     - TextSelectionDelegate.pasteText
     - TextSelectionDelegate.selectAll
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class RawEditorState extends EditorState
          ^^^^^^^^^^^^^^
    ../../../../fvm/versions/stable/packages/flutter/lib/src/services/text_input.dart:985:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
      void copySelection(SelectionChangedCause cause);
           ^^^^^^^^^^^^^
    ../../../../fvm/versions/stable/packages/flutter/lib/src/services/text_input.dart:965:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
      void cutSelection(SelectionChangedCause cause);
           ^^^^^^^^^^^^
    ../../../../fvm/versions/stable/packages/flutter/lib/src/services/text_input.dart:973:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
      Future<void> pasteText(SelectionChangedCause cause);
                   ^^^^^^^^^
    ../../../../fvm/versions/stable/packages/flutter/lib/src/services/text_input.dart:979:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
      void selectAll(SelectionChangedCause cause);
           ^^^^^^^^^

**Comment by gaganyadav80** [comment]
+1

**Comment by MagTuxGit** [comment]
Does anybody work on this? I can take a look.

**Comment by singerdmx** [comment]
Thanks

**Comment by AndreyKuzmenko** [comment]
+1

**Comment by MagTuxGit** [comment]
While my PR is on review try this
```
  flutter_quill:
    git:
      url: https://github.com/MagTuxGit/flutter-quill.git
      ref: flutter_28
```
