### ISSUE TITLE
 [Mobile]  Checkbox list not working, flutter 2.8.0

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#520]
since flutter update to 2.8.0 checkbox in checkbox list won't toggle

**Comment by singerdmx** [comment]
@MagTuxGit Do you have this issue?

**Comment by maksklimko** [comment]
I have the same issue

**Comment by jonasbernardo** [comment]
Yes, i have this issue too

Em qui., 16 de dez. de 2021 11:22, maksklimko ***@***.***>
escreveu:

**Comment by AZKZero** [comment]
Same here

**Comment by GitGud31** [comment]
Same thing, although I'm running **Flutter: 2.5.3** and **flutter_quill: 2.0.2**

**Comment by singerdmx** [comment]
WIP https://github.com/singerdmx/flutter-quill/pull/541
Please test

**Comment by singerdmx** [comment]
If it works, I will merge it

**Comment by GitGud31** [comment]
It's Fixed (Flutter 2.8.1), thanks!
