### ISSUE TITLE
Please check Release Version 

### ISSUE THREAD

**Issue by krishnaprasadgandrath-nooor** [singerdmx/flutter-quill#527]
I tried running release version but unable to run because "TextLayoutMetrics" is not implemented yet.
facing "TextLayoutMterics Not Found" Error

**Comment by krishnaprasadgandrath-nooor** [comment]
![error](https://user-images.githubusercontent.com/94034275/145978174-aa126d73-5f61-49c9-83b7-14a354c991af.png)

**Comment by Flavio-Vieirastack** [comment]
in my project the same error, this package is wonderful, so I think the problem will be solved soon

**Comment by MagTuxGit** [comment]
My suggestion:
Release version works on Flutter 2.8
If you're using Flutter 2.5.x, stay on flutter-quill 2.1.1

**Comment by Flavio-Vieirastack** [comment]
my flutter version is 2.8 and i have the same issue

**Comment by codesigner-tech** [comment]
the commit "Lower environment flutter version to work with pub.dev" change the flutter  version from 2.8.0 to 2.5.3.

**Comment by MagTuxGit** [comment]
> the commit "Lower environment flutter version to work with pub.dev" change the flutter version from 2.8.0 to 2.5.3.

Flutter version was lowered to work with pub.dev, but anyway release version doesn't work with Flutter 2.5.3.
