### ISSUE TITLE
Issues with the quill editor on Flutter Web 2.0

### ISSUE THREAD

**Issue by stemuk** [singerdmx/flutter-quill#53]
I am currently experiencing issues with the quill editor on Flutter 2.0. If I use the basic QuillEditor example from https://github.com/singerdmx/flutter-quill/blob/master/example/main.dart I can only type a few letters before the editor freezes. Unfortunately there are no console logs out of the ordinary I could post here, the editor just becomes unresponsive.
To reproduce the issues I am experiencing just run the example code (https://github.com/singerdmx/flutter-quill/blob/master/example/main.dart) in Flutter 2.0 on Chrome.

Flutter Doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] Connected device (1 available)
```

**Comment by singerdmx** [comment]
Don't use example 
use app

**Comment by singerdmx** [comment]
Use https://github.com/singerdmx/flutter-quill/blob/master/app/lib/main.dart
Reopen if there is still issue
