### ISSUE TITLE
How to upload to firebase and view them?

### ISSUE THREAD

**Issue by marc-walton** [singerdmx/flutter-quill#54]

**Comment by singerdmx** [comment]
Check out https://github.com/singerdmx/flutter-quill/blob/master/app/lib/pages/home_page.dart#L139

**Comment by singerdmx** [comment]
Check out https://github.com/singerdmx/flutter-quill/blob/master/app/lib/main.dart

**Comment by marc-walton** [comment]
> Check out https://github.com/singerdmx/flutter-quill/blob/master/app/lib/pages/home_page.dart#L139
So if the document looks like this with the text and image url saved together. Should I just load the document  or should something be   done to load the images separately ?

**Comment by singerdmx** [comment]
Use the callback to upload

**Comment by marc-walton** [comment]
> Use the callback to upload

Not upload when the I wanna read the document will the images load automatically?
