### ISSUE TITLE
package update than show issue flutter_quill: ^3.0.0

### ISSUE THREAD

**Issue by arupnaskarbkp** [singerdmx/flutter-quill#548]
Because delta_markdown 0.3.0 depends on flutter_quill ^2.0.0 and no versions of delta_markdown match >0.3.0 <0.4.0, delta_markdown ^0.3.0 requires flutter_quill ^2.0.0.
So, because lms_teacher depends on both delta_markdown ^0.3.0 and flutter_quill ^3.0.0, version solving failed.
pub get failed (1; So, because lms_teacher depends on both delta_markdown ^0.3.0 and flutter_quill ^3.0.0, version solving failed.)
Process finished with exit code 1

**Comment by singerdmx** [comment]
Go to delta_markdown to submit issue. 
NO SPAM!

**Comment by arupnaskarbkp** [comment]
ok sir
