### ISSUE TITLE
[Mobile] Style togglers only work when selection includes the very first word

### ISSUE THREAD

**Issue by mrverdant13** [singerdmx/flutter-quill#561]
## Description

When using the toggler buttons in the toolbar, they apply the proper style to the current selection as expected.
However, it is not possible to remove a style by using the buttons. It only works when the selection includes the very first word of the input field.

### Working properly

1. Select a text range including the first word
    <img width="220" alt="image" src="https://user-images.githubusercontent.com/42245236/147779425-c4edbe38-4fe4-4809-b5d4-a9588e76ac91.png">

2. Apply any style
    The button will now be active to notify that the style has been successfully applied
    <img width="175" alt="image" src="https://user-images.githubusercontent.com/42245236/147779455-b35f9660-b974-4e0b-8273-fc7c2defdabd.png">

3. Remove the applied style
    The button will now be inactive to notify that the style has been successfully removed
    <img width="168" alt="image" src="https://user-images.githubusercontent.com/42245236/147779526-3ef9898f-c9df-42ca-9386-0ba69ddc9a28.png">

### Not working at all

1. Select a text range without including the first word
    <img width="211" alt="image" src="https://user-images.githubusercontent.com/42245236/147779963-64652fc2-d35f-47a1-a8c8-8cc002bc3c34.png">

2. Apply any style
    The style will be applied with no issues, but the button will remain inactive and, thus, unable to remove the style.
	Even selecting a fragment of the styled text does activate the toggler button.
    <img width="179" alt="image" src="https://user-images.githubusercontent.com/42245236/147780001-cc8b8982-661c-451e-9173-5152d2de7c37.png">

### `flutter_quill`

Version: **3.0.4**

### `flutter doctor`

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.63.2)
[√] Connected device (4 available)
```

---

I am forking the repo and I will try to solve the issue.
If I come up with a solution, I will submit a PR.
Thanks for the awesome package, guys!

**Comment by singerdmx** [comment]
Could you submit a PR for the fix, please?
I can provide guidance

**Comment by singerdmx** [comment]
@mrverdant13 Any progress on this?

**Comment by li3317** [comment]
Fixed after fixing queryChild
