### ISSUE TITLE
feat: support insertion of multiple links

### ISSUE THREAD

**Issue by mrverdant13** [singerdmx/flutter-quill#578]
## Description

At the moment (`flutter_quill: 3.1.1`), there are some limitations or bugs when inserting links:

- The link attribute is only applied after a single space char insertion.
- When pasting text that includes links, the proper link attribute is not applied.
- The surrounding text is not always reformatted according to the resulting `Document` i.e. if an existing link gets broken, its link attribute should be removed, but it is not the case.
- Link insertion only uses the `Uri.parse` method and checks the schemas to check if it is valid, which is not that realiable.

I am about to submit a PR on this but would like you to check it and verify the link insertion rule behaviour.

**Comment by singerdmx** [comment]
no change?

**Comment by singerdmx** [comment]
regarding `When pasting text that includes links, the proper link attribute is not applied.` I think it is a general issue, see https://github.com/singerdmx/flutter-quill/issues/479

**Comment by singerdmx** [comment]
I am doing some refactoring. So please sync your code to the latest

**Comment by singerdmx** [comment]
> * Link insertion only uses the `Uri.parse` method and checks the schemas to check if it is valid, which is not that realiable.

This is the best we can come up with right now

**Comment by singerdmx** [comment]
> * The link attribute is only applied after a single space char insertion.

I don't think you can have a link with empty text

**Comment by mrverdant13** [comment]
> > * The link attribute is only applied after a single space char insertion.
> 
> I don't think you can have a link with empty text

Would be great to format/unformat the link as you type.

> > * Link insertion only uses the `Uri.parse` method and checks the schemas to check if it is valid, which is not that realiable.
> 
> This is the best we can come up with right now

Maybe we can rely on regexp as well.

**Comment by singerdmx** [comment]
> * When pasting text that includes links, the proper link attribute is not applied.

Automatically generate link is something interesting. We actually did that at server side https://github.com/singerdmx/BulletJournal/blob/master/backend/src/main/java/com/bulletjournal/util/DeltaContent.java#L21

**Comment by singerdmx** [comment]
> Maybe we can rely on regexp as well.

https://github.com/singerdmx/BulletJournal/blob/master/backend/src/main/java/com/bulletjournal/util/DeltaContent.java#L21 This is the regex

**Comment by singerdmx** [comment]
> This is the regex

But I don't think it works for `www.google.com` which may be common use case

**Comment by singerdmx** [comment]
> Maybe we can rely on regexp as well.

Be careful to not make it too strict. For the least it should work for `www.google.com`

**Comment by singerdmx** [comment]
> * When pasting text that includes links, the proper link attribute is not applied.

@mrverdant13 Is this resolved?

**Comment by mrverdant13** [comment]
> @mrverdant13 Is this resolved?

Solved by #579, mate

**Comment by singerdmx** [comment]
> > @mrverdant13 Is this resolved?
> 
> Solved by #579, mate

Pasting also works?

**Comment by mrverdant13** [comment]
Yes, it does.

From the PR:
> ## Manual testing
> 1. Run the `example` demo app.
> 2. Insert the following text:
>    ```
>    Lorem ipsum dolor sit amet, consectetur www.google.com adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation http://google.com ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse https://www.google.com cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
>    ```

By _insert_ I mean both: pasting and sequential chars insertion 😅

**Comment by singerdmx** [comment]
Sounds good!

**Comment by pramod51** [comment]
I have tried to paste content from this -->https://en.wikipedia.org/wiki/Main_Page
but it's not working.
