### ISSUE TITLE
New gallery_saver causing many errors

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#594]
On iOS it causes an immediate app crash, when I try to load an image picker.  But there are no error messages logged to the terminal

On Android the app fails to launch with the following errors (pages and pages of similar error)

```
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/ch/.gradle/caches/transforms-2/files-2.1/106bc27f1acd230c0f5be4b7b9ef7f9a/jetified-kotlin-stdlib-jdk7-1.5.20.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
```

```
Execution failed for task ':gallery_saver:compileReleaseKotlin'
```

**Comment by MagTuxGit** [comment]
I have the same issue with the latest Kotlin
![Screen Shot 2022-01-21 at 09 49 45](https://user-images.githubusercontent.com/5296407/150487566-896e2dba-46b2-4731-8bd7-005b0df30c5e.png)

**Comment by MagTuxGit** [comment]
To fix the issue change next:
android/build.gradle
`ext.kotlin_version = '1.5.1'`
or any newer version
