### ISSUE TITLE
[Mobile] Link attribute can't open 

### ISSUE THREAD

**Issue by tzthantzin** [singerdmx/flutter-quill#595]
My issue is about [Mobile]

When I use link attribute 

`{
      "insert": "My simple link map",
      "attributes": {
         "link": "https://www.google.com/maps"
      }
   },`

and then I was long press on that link and it is showing bottom navigation drawer menu : open, copy and remove.
When I press open, the link isn't opened.

Could you please kindly check it? 

https://user-images.githubusercontent.com/32185240/150270027-04afa983-1a06-44f9-b23b-45014f96d036.mp4
Thank you very much

**Comment by singerdmx** [comment]
Fixed by https://github.com/singerdmx/flutter-quill/commit/a1be256ff94de5d2ba352a138d01541068edc3e8
