### ISSUE TITLE
cursor position error after dynamic insert

### ISSUE THREAD

**Issue by li-xiaoyin** [singerdmx/flutter-quill#6]
My requirement is when user tap enter then auto insert two space. and my code as follows. 
when I auto insert space, I expect cursor appear after space but now it appear before space
May be my code is wrong. please give me some suggestion Thank you.

I wish you can provide more examples.

@override
  void initState() {
    this._controller.addListener(() {
      this._controller.changes.first.then((value) {
        if (value.item2.length >= 2 &&
            value.item2[1].isInsert &&
            value.item2[1].data == "\n") {
          final index = this._controller.selection.baseOffset;
          this._controller.document.insert(index, "　　");
        }
      });
    });
  }

**Comment by singerdmx** [comment]
I guess you can follow https://github.com/singerdmx/flutter-quill/blob/master/lib/widgets/editor.dart#L376 to do something similar

**Comment by singerdmx** [comment]
Tapping on image or url is what we have.
You can create a pull request so that you can pass in additional behavior if you want.

**Comment by singerdmx** [comment]
check https://github.com/singerdmx/flutter-quill/blob/master/lib/widgets/editor.dart#L340

`getEditor().widget.onLaunchUrl` can be passed from outside
I think you can do sth similar

**Comment by li-xiaoyin** [comment]
Would you mean that I need to change the editor.dart to implements my requirement？ OK  I will try to do this and I think have an extension function to implements custom requirement is a better way.

**Comment by singerdmx** [comment]
Yes you can submit a pull request for external extensibility on tapping.

**Comment by li-xiaoyin** [comment]
@override
  void initState() {
    this._createIndent();

    this._controller.addListener(() {
      this._controller.changes.first.then((value) {
        if (value.item2.length >= 2 &&
            value.item2[1].isInsert &&
            value.item2[1].data == "\n") {
          this._createIndent();
        }
      });
    });
  }

  _createIndent() {
    final indent = "　　"; // em space
    final index = this._controller.selection.baseOffset;

    this._controller.document.insert(index, indent);
    this._controller.updateSelection(
        TextSelection.collapsed(offset: index + 2), ChangeSource.LOCAL);
  }
