### ISSUE TITLE
Emoji feature

### ISSUE THREAD

**Issue by singerdmx** [singerdmx/flutter-quill#604]
Who wants to implement this please contact me

**Comment by singerdmx** [comment]
https://github.com/Fintasys/emoji_picker_flutter

**Comment by MagTuxGit** [comment]
What the purpose of that package? Why do we need an emoji picker when we have default one?

**Comment by singerdmx** [comment]
What default one?

**Comment by singerdmx** [comment]
OK, I guess we don't need that since keyboard has that.
What about custom gifs?

**Comment by singerdmx** [comment]
> What the purpose of that package? Why do we need an emoji picker when we have default one?

Actually web doesn't have default one

**Comment by MagTuxGit** [comment]
> Actually web doesn't have default one

Oh, I see. My project is mobile only, sorry.

**Comment by singerdmx** [comment]
If you look at WhatsApp, it has gif which is similar to custom emoji

**Comment by RamiHI** [comment]
Hello
how can i add custom emoji to my project?

**Comment by jigarfumakiya** [comment]
Hey @singerdmx 

is this feature been implemented or not?

**Comment by HoangHieuHBR** [comment]
Hello sir @singerdmx 
Is this feature been updated or not?

**Comment by singerdmx** [comment]
This feature is basically customized gif and need to have a list of sample gif to be used

**Comment by singerdmx** [comment]
If you want to volunteer to add this feature, we can schedule a time to discuss

**Comment by HoangHieuHBR** [comment]
I have an idea like: If I fork base code of emoji_picker_flutter packges and then change the text controller from TextEditingController to ur QuillController. Is it a good solution ?

**Comment by singerdmx** [comment]
Sounds good
