### ISSUE TITLE
bug: rules are not accessible any more

### ISSUE THREAD

**Issue by mrverdant13** [singerdmx/flutter-quill#617]
## Details

When working with custom controller behaviour, the user would use the `Document.setCustomRules` method, which is still available.

However, this method only receives a collection of instances of type `Rule`, which is not properly exported by the library.

The `lib/flutter_quill.dart` barrel file:
```dart
library flutter_quill;

export 'src/models/documents/attribute.dart';
export 'src/models/documents/document.dart';
export 'src/models/documents/nodes/embeddable.dart';
export 'src/models/documents/nodes/leaf.dart';
export 'src/models/quill_delta.dart';
export 'src/models/themes/quill_dialog_theme.dart';
export 'src/models/themes/quill_icon_theme.dart';
export 'src/widgets/controller.dart';
export 'src/widgets/default_styles.dart';
export 'src/widgets/editor.dart';
export 'src/widgets/link.dart' show LinkActionPickerDelegate, LinkMenuAction;
export 'src/widgets/style_widgets/style_widgets.dart';
export 'src/widgets/toolbar.dart';
```

**Comment by singerdmx** [comment]
`CustomRules` should be removed and not supported anymore

**Comment by singerdmx** [comment]
No more customization. Any rule needed should be in the repo. People should contribute their rules here.
