### ISSUE TITLE
[Mobile] option(s) to skip or customize Save/Zoom image menu 

### ISSUE THREAD

**Issue by xurc** [singerdmx/flutter-quill#629]
My issue is about [Mobile]

Please add an option to skip (always zoom by tap, as it was in quill before as default behavior) or customize the "Save/Zoom" image menu in `defaultEmbedBuilder`. Hardcoded menu design in readOnly mode does not fit into any application where quill can be used.

**Comment by singerdmx** [comment]
Not going to skip
You can submit PR to improve the menu

**Comment by singerdmx** [comment]
Don't fully understand what issue you are saying, but we are not going to skip the menu and you can help improving the menu
