### ISSUE TITLE
How can I apply locale to QuillEditor(contents)?

### ISSUE THREAD

**Issue by Develeste** [singerdmx/flutter-quill#636]
The locale option exists in the QuillToolbar.

But the locale option do not exists in the QuillEditor.

Therefore, i18n doesn't seem to be applied to Save and Zoom that appear when you click on the image.

Is there any way to apply it?

**Comment by singerdmx** [comment]
We need a PR

**Comment by singerdmx** [comment]
Fixed by https://github.com/singerdmx/flutter-quill/commit/2c1856c578bc050150642c433539ba26c8dac4e7
