### ISSUE TITLE
Link Icon Issue with [Web] or [Mobile] or [Desktop]

### ISSUE THREAD

**Issue by ajaykachhawa** [singerdmx/flutter-quill#647]
I have checked this on [Web] but it may be in [Mobile] & [Desktop] also with version flutter_quill: ^3.9.4

I have found two issues with the Link icon.

1. Clicking on the Link icon without any text on a new line will crash.
2. Paste some link & select this link & click on Link icon. It will open the dialog, Edit display text & click Okay. It will not be showing the correct display text instead it will show link URL's last characters for the same length if display text.

**Comment by singerdmx** [comment]
Fixed #1 https://github.com/singerdmx/flutter-quill/commit/a82692fe58a8ecc123070b8b6441c5257a01949a
Cannot repro #2
