### ISSUE TITLE
Underline Icon Issue with [Web] or [Mobile] or [Desktop]

### ISSUE THREAD

**Issue by ajaykachhawa** [singerdmx/flutter-quill#648]
I have checked this on [Web] but it may be in [Mobile] & [Desktop] also with version flutter_quill: ^3.9.4

I have found an issue with the Underline icon.

1. Enter some text & select it & make it underline by clicking on Underline icon.
2. Now click somewhere else & again click on your underline text.
3. Now you will see Underline icon highlighted in toolbar.
4. Deselect Underline icon And it will not allow you remove underline from your text.

It should remove the underline from the text once the underline text is selected & Underline icon is clicked.

**Comment by singerdmx** [comment]
Cannot repro
