### ISSUE TITLE
[WEB] Text is not displayed while typing - only when I change the browser window size (set state)

### ISSUE THREAD

**Issue by crossfire91** [singerdmx/flutter-quill#65]
Hi there,

first of all - a really great plugin!!

Since version 0.3.1 Text is not displayed while typing on web - only when I change the browser window size (which I guess initiates a set state). 

This issue is also in the new 1.0.2 version

**Comment by singerdmx** [comment]
For web related question, @rish07 is the go to guy.
He is also available in slack channel

**Comment by singerdmx** [comment]
Sorry that I and my team do not use this library for web.
@rish07 did quite some work for web

**Comment by singerdmx** [comment]
@crossfire91 are you saying before 0.3.1  it is working?
Maybe we can trace which commit caused it

**Comment by crossfire91** [comment]
yes, 0.3.1 was the last that worked. 0.3.2 - 1.0.2 is not working

**Comment by singerdmx** [comment]
I suspect it is https://github.com/singerdmx/flutter-quill/commit/08ed4c3c85b2bf38cb9631339f81d5ab68edc114

**Comment by singerdmx** [comment]
If you rollback to commit https://github.com/singerdmx/flutter-quill/commit/fd3aac999f4fb34d036d8d7c71b7152170fd21c0 does it work?

**Comment by singerdmx** [comment]
Maybe KeyboardVisibilityController does not work for web?

**Comment by crossfire91** [comment]
> Maybe KeyboardVisibilityController does not work for web?

yes this was the issue.

I changed raw_editor.dart line 888 from:

_didChangeTextEditingValue() {
    if (_keyboardVisible) {
      _onChangeTextEditingValue();
    } else {
      requestKeyboard();
    }
  }
  
  to:
  
 _didChangeTextEditingValue() {
    if (_keyboardVisible || kIsWeb) {
      _onChangeTextEditingValue();
    } else {
      requestKeyboard();
    }
  }

**Comment by singerdmx** [comment]
Cool, you found the fix
Please submit a Pull request

**Comment by singerdmx** [comment]
Done https://github.com/singerdmx/flutter-quill/commit/766058b47332c68423de09b3a69c921351ef8dbb

**Comment by singerdmx** [comment]
Will publish 1.0.3 to pub

**Comment by singerdmx** [comment]
@crossfire91  are you using stable branch? Your pull request looks weird

**Comment by singerdmx** [comment]
Anyway, fix is in now

**Comment by crossfire91** [comment]
yes I am using stable branch... 
oh sorry - I really don't know how to do a pull request here - it was my first pull request.

**Comment by singerdmx** [comment]
No problem.
But I think the fix may not be right.
![image](https://user-images.githubusercontent.com/122956/110235733-81c9dc80-7ee6-11eb-87eb-9288a8873c1e.png)

It looks like you are never going to requestKeyboard?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/110235766-afaf2100-7ee6-11eb-99d6-c6f834552fe8.png)


Can you try this?
```
  _didChangeTextEditingValue() {
    if (kIsWeb) {
      _onChangeTextEditingValue();
      requestKeyboard();
      return;
    }

    if (_keyboardVisible) {
      _onChangeTextEditingValue();
    } else {
      requestKeyboard();
    }
  }
```

Please use master branch

**Comment by singerdmx** [comment]
Because I think you will need to requestKeyboard for web because _keyboardVisible is not useful.

BTW, stable branch is deprecated.

**Comment by singerdmx** [comment]
Pushed https://github.com/singerdmx/flutter-quill/commit/5446a73b86056e925e9c81016a29556e4f03efb0
Try it

**Comment by crossfire91** [comment]
yes your fix works better! (I guess my fix would only have worked on desktop)

**Comment by crossfire91** [comment]
thank you!!

**Comment by singerdmx** [comment]
Your change will never request keyboard for web
I assume you will need to bring up keyboard. Calling requestKeyboard more than once is fine

**Comment by florianh01** [comment]
This is also the case with an IOS simulator if the text is entered via a hardware keyboard. Should work on a real device though But I can't test it because I don't have an iPhone.

**Comment by singerdmx** [comment]
flutter_quill: ^1.0.3 is pushed
