### ISSUE TITLE
[Web] Crash when undoing a change implying indentation

### ISSUE THREAD

**Issue by NicolasDionB** [singerdmx/flutter-quill#655]
My issue is about [Web]. I have tried running `example` directory successfully before creating an issue here. To reproduce, in the example, select the following text, that is the two highlighted lines and the return until the beginning of the following line, like this:

![image](https://user-images.githubusercontent.com/25512495/152854954-8eecf2ba-c07e-46fc-8caf-1115da11912e.png)

Then, delete the text and undo that by pressing Ctrl+Z (on Windows). You'll get the following error:

![image](https://user-images.githubusercontent.com/25512495/152858329-7b005ffd-114f-4558-ad24-245224a8d88d.png)

The `value` is actually an indent attribute object instead of being a numeric value. The undo seems to break the content.

To me it is a major issue because I cannot protect my app from crashing when I get this. Plus there is no way of preventing it so using Flutter Quill in my app may result in it being usable.

I got this running FlutterQuill 3.9.9 with Flutter 2.8.1 on Chrome/Windows 10.

I can start working on it, if anyone can point me where the undo part is handled, maybe that could help!

**Comment by NicolasDionB** [comment]
Update: pressing the undo button does not produce the error. I found the error, pull-request incoming!

**Comment by singerdmx** [comment]
Fixed by https://github.com/singerdmx/flutter-quill/commit/350d7bcfb038c90079a3002e0630a0554e1322f9
