### ISSUE TITLE
[Mobile] Build fails on simple implementation.

### ISSUE THREAD

**Issue by jaded0** [singerdmx/flutter-quill#658]
My issue is about [Mobile]

The example directory fails to run, as well, for the same error.

Error code:
`../lib/src/widgets/editor.dart:51:48: Error: Type 'TextLayoutMetrics' not found.
abstract class RenderAbstractEditor implements TextLayoutMetrics {
                                               ^^^^^^^^^^^^^^^^^
../lib/src/widgets/raw_editor.dart:979:3: Error: Type 'TextLayoutMetrics' not found.
  TextLayoutMetrics get textLayoutMetrics => renderEditor;
  ^^^^^^^^^^^^^^^^^
../lib/src/widgets/raw_editor.dart:231:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextEditingActionTarget.renderEditable
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
`

**Comment by jaded0** [comment]
Oops. this is a duplicate of #644 and using commit #646 worked

**Comment by devtud** [comment]
@jaded0 is your flutter quill editable when using #646 ? On Linux desktop is not editable.
