### ISSUE TITLE
[Mobile] Keep paste formatting

### ISSUE THREAD

**Issue by jaded0** [singerdmx/flutter-quill#659]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here. 

On other editors, lists, bullet points, bolding, and paragraphs (line breaks) are kept when you copy/paste from google docs. This is a useful feature to have in a text editor, and unfortunately is a must-have in my app.

**Comment by singerdmx** [comment]
It is working in flutter 2.8

**Comment by singerdmx** [comment]
copy/paste from google docs

We have no way to get that
Cannot do it

**Comment by jaded0** [comment]
There definitely is. I've tested it on other flutter text box libraries.

**Comment by singerdmx** [comment]
It is not available in Clipboard.
You can submit a PR if you want. No need to debate it.

**Comment by Ibtesam-Mahmood** [comment]
[Web] @singerdmx I’m facing this issue aswell with pasting text that is copied from sources like: notion (markdown), pdfs, and word documents. Furthermore, if i copy text from the editor itself and paste it back in, it removes the format. I think this issue on your board reflects it well #1018. Is there any support within the repository to retain the format of this when pasting text?
