### ISSUE TITLE
[Mobile] Version 4.0.0 cannot focus quill editor

### ISSUE THREAD

**Issue by tzthantzin** [singerdmx/flutter-quill#663]
My issue is about [Mobile]

When I was upgraded version 4.0.0, the quill editor can't focus although readonly false.

I've tested library example, it is also can't focus

https://user-images.githubusercontent.com/32185240/153587461-196c9885-7061-4c21-abc1-8f62b44add40.mp4

Could you please kindly check it? 

Thank you very much 🙏

**Comment by veselv2010** [comment]
having the same issue on web

**Comment by rafildo** [comment]
Same isseu here. I can`t focus on it.

**Comment by LeetaoGoooo** [comment]
Same issue~

**Comment by gcostaapps** [comment]
Same here, but works if autofocus is true

**Comment by tommienu** [comment]
Confirmed issue on [Android] as well.

**Comment by gcostaapps** [comment]
For those who are with problems with cursor disappearing, I created a Stateful Widget and created a FocusNode inside the state (I initialize the controller on initState). Then when I use the focus on the QuillEditor the cursor stop disappearing and it's normal now. Maybe it can help you too.

**Comment by xinyuezhang0402** [comment]
Fixed in flutter_quill 4.0.1

**Comment by tommienu** [comment]
> Fixed in flutter_quill 4.0.1

Confirmed, thanks! 👍

**Comment by rafildo** [comment]
Thank you guys!

**Comment by HSCOGT** [comment]
For anyone experiencing this even with flutter_quill 4.0.1 or higher, do not use `QuillEditor.basic()` instead use the standard constructor `QuillEditor()`, and when assigning the focus node make sure it's a variable inside a StatefulWidget and not an instance declared in the build method.
