### ISSUE TITLE
[Mobile][Android][IOS]Select all, then cut will report error in version 4.0.1

### ISSUE THREAD

**Issue by longch** [singerdmx/flutter-quill#667]
My issue is about [Mobile]

https://user-images.githubusercontent.com/2062905/154087092-77bce72c-0123-4dfd-b1c4-285dbc065750.mp4

### If the content ends with a newline break, then select all, then select cut it will report an error

E/flutter ( 9365): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 0..27: 28

E/flutter ( 9365): #0      RangeError.checkValidRange (dart:core/errors.dart:355:9)
E/flutter ( 9365): #1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
E/flutter ( 9365): #2      Line.getPlainText
E/flutter ( 9365): #3      Document.getPlainText
E/flutter ( 9365): #4      QuillController.getPlainText
E/flutter ( 9365): #5      RawEditorState.cutSelection
E/flutter ( 9365): #6      TextSelectionControls.handleCut
E/flutter ( 9365): #7      MaterialTextSelectionControls.buildToolbar.<anonymous closure>
E/flutter ( 9365): #8      _InkResponseState._handleTap
E/flutter ( 9365): #9      GestureRecognizer.invokeCallback
E/flutter ( 9365): #10     TapGestureRecognizer.handleTapUp
E/flutter ( 9365): #11     BaseTapGestureRecognizer._checkUp
E/flutter ( 9365): #12     BaseTapGestureRecognizer.handlePrimaryPointer
E/flutter ( 9365): #13     PrimaryPointerGestureRecognizer.handleEvent
E/flutter ( 9365): #14     PointerRouter._dispatch
E/flutter ( 9365): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure>
E/flutter ( 9365): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
E/flutter ( 9365): #17     PointerRouter._dispatchEventToRoutes
E/flutter ( 9365): #18     PointerRouter.route
E/flutter ( 9365): #19     GestureBinding.handleEvent
E/flutter ( 9365): #20     GestureBinding.dispatchEvent
E/flutter ( 9365): #21     RendererBinding.dispatchEvent
E/flutter ( 9365): #22     GestureBinding._handlePointerEventImmediately
E/flutter ( 9365): #23     GestureBinding.handlePointerEvent
E/flutter ( 9365): #24     GestureBinding._flushPointerEventQueue
E/flutter ( 9365): #25     GestureBinding._handlePointerDataPacket
E/flutter ( 9365): #26     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter ( 9365): #27     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 9365): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 9365): #29     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter ( 9365): #30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter ( 9365): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)

**Comment by mark8044** [comment]
If you have a VERY long amount of text, and even highlight just a piece of it and delete, you will get a RSOD (red screen of death)

**Comment by jonasbernardo** [comment]
Me too, the same problem

**Comment by jonasbernardo** [comment]
please someone correct this bug

**Comment by jonasbernardo** [comment]
I tried to find the problem, so I checked the method ChildQuery queryChild(int offset) in class Document.dart
is returning wrong values ​​when selecting text with line break \n

I think that's it but I don't know how to fix it

**Comment by mtallenca** [comment]
version 4.0.7 addresses this

**Comment by xinyuezhang0402** [comment]
@mtallenca thanks!
