### ISSUE TITLE
[WEB] Strange behavior when using keyboard left/right arrow to navigate in content

### ISSUE THREAD

**Issue by GreenLim** [singerdmx/flutter-quill#68]
Expect to be:
Press arrow right/left once, move cursor once.

Actually:
Press keyboard right/left arrow once will move cursor twice.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/110249901-6df59900-7f2d-11eb-85d3-ca73a6525c0c.png)

Probably related to this

**Comment by singerdmx** [comment]
Fixed by https://github.com/singerdmx/flutter-quill/commit/54c3eb446e2b90ec0a977d29eb0f21e2752dd07f

Please reopen if it still exists
