### ISSUE TITLE
Flutter Quill does not support "null safety"

### ISSUE THREAD

**Issue by egnimos** [singerdmx/flutter-quill#69]
I have been facing issue, when I run flutter Quill on my flutter web app 

![quill Issue](https://user-images.githubusercontent.com/54541657/110431990-8f44b980-80d4-11eb-8acd-f9094e6e1b6a.PNG)

Please shift your package to null safety so that we can use it 
Thank you For Helping

**Comment by singerdmx** [comment]
We will need help
Pull request is welcome
