### ISSUE TITLE
[Mobile] Enumeration order messes up after indentation

### ISSUE THREAD

**Issue by WesselvanDam** [singerdmx/flutter-quill#696]
First of all, thank you for this great package, it's amazing!

I noticed a small bug when implementing the Quill Editor. It happens when using the enumeration feature. I was pretty amazed when I found out that the indent button changes the enumeration from numbers to letters on indent, but it seems that once you go back to the first indentation level, the enumeration always resumes at '2'. Additionally, the one after that is a 2 as well. After that it will resort to normal.

![image](https://user-images.githubusercontent.com/43265483/156074595-bafce533-5d55-41b9-acb3-21023bc97241.png)

I tried it as well for a list of say 9 items and then creating an indent at 9.a. Pressing Enter and the Decrease Indentation button make the item after 9 resort to 2. Writing some text and pressing Enter again yields a 2 again.

**Comment by singerdmx** [comment]
This is probably a bug. Can you share a video how to repro it?

**Comment by kulture-rob-snider** [comment]
we have noticed this too in our app. i'll try to get a video together.

**Comment by kulture-rob-snider** [comment]
https://user-images.githubusercontent.com/53707285/196763138-452d7ebe-6e8b-4222-8fac-275c1cdedb9d.mp4
