### ISSUE TITLE
 [Mobile]  copy or cut will report error in version 4.0.6

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#699]
I still have the problem of copying, when I select a text and the selection takes the bottom line blank, it gives this error.

**my check in code:
the selection does not take the line break '\n' but it counts as the total size of the text counting the '\n' as a letter
that's why the error says that it tried to get a value with an extra number in the list of letters of the selection**

Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 0..2: 3
E[/flutter]() ( 7206): #0      RangeError.checkValidRange (dart:core[/errors.dart:355:9]())
E[/flutter]() ( 7206): #1      _StringBase.substring (dart:core-patch[/string_patch.dart:400:27]())
E[/flutter]() ( 7206): #2      Line.getPlainText
package:flutter_quill/…/nodes/line.dart:469
E[/flutter]() ( 7206): #3      Document.getPlainText
package:flutter_quill/…/documents/document.dart:175
E[/flutter]() ( 7206): #4      QuillController.getPlainText
package:flutter_quill/…/widgets/controller.dart:101
E[/flutter]() ( 7206): #5      RawEditorState.cutSelection
package:flutter_quill/…/widgets/raw_editor.dart:927
E[/flutter]() ( 7206): #6      TextSelectionControls.handleCut
package:flutter/…/widgets/text_selection.dart:20

**Comment by xinyuezhang0402** [comment]
DUP
