### ISSUE TITLE
[web] Adding image in editor shows blank space

### ISSUE THREAD

**Issue by mordivgor** [singerdmx/flutter-quill#70]
When I am adding image in editor in web, I see only blank space for image.
![image](https://user-images.githubusercontent.com/54472480/110521987-b6b97780-8110-11eb-868b-23ed286f0241.png)

**Comment by singerdmx** [comment]
@rish07  did work for web

**Comment by mordivgor** [comment]
Sure, I will check.
I would like only ask to anyone has it working with Flutter 2.0.0 (stable version). Then I will be able to narrow the problem.

**Comment by rish07** [comment]
@mordivgor is the 'app' inside the flutter-quill's repo working for you?

**Comment by mordivgor** [comment]
@rish07 it works :) I will check what is wrong my the custom code. Thanks for your help! I am closing the issue at this moment.
