### ISSUE TITLE
[Mobile]  Mention feature

### ISSUE THREAD

**Issue by youth-flutter-dev** [singerdmx/flutter-quill#712]
Is there mention feature in this library as like git hub or social media?

if there is no mentions feature, how can i develop same as https://github.com/quill-mention/quill-mention.

Thank you very much

**Comment by ketan10592** [comment]
Hey, Check out my example here : https://github.com/ketan10592/flutter_quill_example
you can find how to add mention in flutter_quill.
<img width="445" alt="Screenshot 2022-05-02 at 6 00 32 PM" src="https://user-images.githubusercontent.com/60574739/166247481-00ce62b5-4177-4d01-b1da-0e80b646f04c.png">

**Comment by Mrgeh** [comment]
When setting the image size, setting the width is invalid, and the height can be set，bug:   Touch pointer move a lot. The moving distance of X is:64.0, limit is:60The moving distance of Y is:11.0, limit is:60。。How to solve this, please help

**Comment by chifandeyu** [comment]
![image](https://user-images.githubusercontent.com/15946864/227870307-508b8032-eaba-4bae-abce-52ef3784d279.png)
Is there a way to pop up at the cursor position while entering the emotion? Notify the position (x, y).

**Comment by GP4cK** [comment]
> ![image](https://user-images.githubusercontent.com/15946864/227870307-508b8032-eaba-4bae-abce-52ef3784d279.png) Is there a way to pop up at the cursor position while entering the emotion? Notify the position (x, y).

You should checkout this issue: https://github.com/singerdmx/flutter-quill/issues/1273

**Comment by NehaKushwah993** [comment]
Try this : https://github.com/NehaKushwah993/flutter_quill_mentions
