### ISSUE TITLE
[web] Does flutter-quill support web application now?

### ISSUE THREAD

**Issue by AscentionOne** [singerdmx/flutter-quill#72]
Hi, @singerdmx I am a user from Zefyr package. I saw you actively answering the question there. Thank you, your answer helps me too. Since the Zefyr is not maintaining now.... ( is at dev 2.0) for a while... Initially, flutter-quill is not supporting the web, only on a mobile. Now it does🎉, I saw the tag under the package name and I am really glad to see that. I am wondering how does the package work on the web currently? Is it still in an early phase or it has all the basic functions working on the web as in mobile? Thanks again for the great package.👍

**Comment by singerdmx** [comment]
I think so
@rish07 knows more since he delivered it
