### ISSUE TITLE
[Mobile]How to customize the style of the HashTag

### ISSUE THREAD

**Issue by sunjianan9900** [singerdmx/flutter-quill#724]
How to customize the style of the HashTag ？
I want the HashTag to automatically display in blue #bule

**Comment by ketan10592** [comment]
You can check my example here : https://github.com/ketan10592/flutter_quill_example
Also you can find how to add AtMention

<img width="445" alt="Screenshot 2022-05-02 at 6 00 32 PM" src="https://user-images.githubusercontent.com/60574739/166246744-3382b64f-d6f5-4201-a19c-bb5a3b39a6cf.png">
