### ISSUE TITLE
[web] Some problems and weird effect on editing text

### ISSUE THREAD

**Issue by AscentionOne** [singerdmx/flutter-quill#73]
Hi, @singerdmx I give it a quick test and found some problems. 

1. The backspace is not working as intended, it is deleting two characters at a time.

![demo1](https://user-images.githubusercontent.com/44708790/110562826-32550c00-8185-11eb-84f7-7c253f707195.gif)

2. When typing and deleting the character several times the "enter" key to the new line will not trigger the first time and will go two lines in the second trigger. The backspace of going back a line will go back two lines at a time.

![demo2](https://user-images.githubusercontent.com/44708790/110563026-95df3980-8185-11eb-9178-b8c9cfd3b4d4.gif)

3. When mixing typing and deleting the character several times, the typing functionality will also not trigger the first time and will output two characters the second time. See the "rrrr" part at the end.

![demo3](https://user-images.githubusercontent.com/44708790/110563394-37668b00-8186-11eb-8716-dd049034322d.gif)

4. Changing text heading is not working as intended.

![demo4](https://user-images.githubusercontent.com/44708790/110563528-6c72dd80-8186-11eb-9186-2733c3076069.gif)

5. Does add a check box to the numbered line replace the number or add the check box after the number? Seems to add after the number works more logically (just my personal thoughts)?

![demo5](https://user-images.githubusercontent.com/44708790/110563968-0f2b5c00-8187-11eb-94fa-0f9205b22964.gif)

6. Maybe adding a check box should disable some of the functionalities. For example, code block ...etc, cause it will cause some weird effect. Below are some demos.

![demo6](https://user-images.githubusercontent.com/44708790/110564208-6af5e500-8187-11eb-8068-02037f7bb493.gif)

![demo7](https://user-images.githubusercontent.com/44708790/110564217-6e896c00-8187-11eb-88a1-150428644803.gif)

7. Selecting of character through the cursor works fine. However, through keyboard "Shift+left arrow" is not working. Shift+right arrow is working.

![demo8](https://user-images.githubusercontent.com/44708790/110564641-261e7e00-8188-11eb-928a-e12e1af8d041.gif)

Above are some problems I encounter after testing on the web application. Thank you for the hard work and make the package better!

Ken

**Comment by singerdmx** [comment]
We could use some help
Pull request is welcome

**Comment by singerdmx** [comment]
Fixed by https://github.com/singerdmx/flutter-quill/commit/54c3eb446e2b90ec0a977d29eb0f21e2752dd07f

Please reopen if it still exists

**Comment by AscentionOne** [comment]
Hi @singerdmx the issue of the keyboard is solved👍😘, which are issues 1,2,3, and 7. 

However, issue 4, changing the text heading is still not working. Should I reopen the issue? Or I create a new one? 

About issues 5 and 6, problems about checkbox and code block. I think it can be a future improvement. Thank you for the work!

**Comment by singerdmx** [comment]
Please do one issue as one item

**Comment by AscentionOne** [comment]
Okay, that was my bad😂. Will do that in the future! Thank you!
