### ISSUE TITLE
Can not insert newline when Bold is toggled ON.

### ISSUE THREAD

**Issue by nnkti18** [singerdmx/flutter-quill#74]
Steps to reproduce:

1. Toggle ON bold
2. Press Enter

Expected result: The editor must insert a new line.

Actual result: nothing happened.

**Comment by singerdmx** [comment]
Mobile or web?

**Comment by nnkti18** [comment]
> Mobile or web?

My app is only available on mobile, I haven't tested on web yet.

**Comment by singerdmx** [comment]
So  you toggle noting and then press enter?

**Comment by nnkti18** [comment]
> So you toggle nothing and then press enter?

Even if the line contains some texts before I switched on bold, this bug still happens

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/110739126-6829dd00-81e5-11eb-9973-449dd5b704f2.png)
Issue is here.
`toggledStyle.isNotEmpty` should be updated with inline style considered.
Also I submitted https://github.com/singerdmx/flutter-quill/commit/17a38965c8753a8ce11656770d7da88161357ca8

**Comment by singerdmx** [comment]
@nnkti18 you can submit a pull request to address this.
Just need to make sure the condition makes sense

**Comment by singerdmx** [comment]
Maybe if it is AttributeScope.INLINE , we should skip `retainDelta`?

**Comment by singerdmx** [comment]
One thing we need to make sure is it does not break other use case

**Comment by singerdmx** [comment]
@nnkti18 check out https://github.com/singerdmx/flutter-quill/pull/75

**Comment by singerdmx** [comment]
Or you can provide a better fix

**Comment by nnkti18** [comment]
> @nnkti18 check out #75
> If it does not break anything else, I can merge it

#75  should not be merged because it breaks the normal bold text behavior. Example: When Bold is toggled on, insert a new text immediately toggle off BOLD.

**Comment by singerdmx** [comment]
@nnkti18 pushed new commit. Try again

**Comment by nnkti18** [comment]
> @nnkti18 pushed new commit. Try again

Looking good, I don't see any unusual behavior

**Comment by singerdmx** [comment]
Merged
