### ISSUE TITLE
Incompatibility flutter_quill with dio,validators - Important

### ISSUE THREAD

**Issue by abresihjj** [singerdmx/flutter-quill#76]
Hello sir
I When
flutter_quill: ^1.0.5

I use with
dio: ^3.0.10
validators: ^2.0.1

It is inconsistent and I have a lot of problems, please solve it

Because flutter_quill >=1.0.1 depends on image_picker ^0.7.2 which depends on image_picker_platform_interface ^2.0.0, flutter_quill >=1.0.1 requires image_picker_platform_interface ^2.0.0.
And because image_picker_platform_interface >=2.0.0 depends on http ^0.13.0 which depends on http_parser ^4.0.0, flutter_quill >=1.0.1 requires http_parser ^4.0.0.
And because dio 3.0.10 depends on http_parser >=0.0.1 <4.0.0 and no versions of dio match >3.0.10 <4.0.0, flutter_quill >=1.0.1 is incompatible with dio ^3.0.10.
So, because myapp depends on both dio ^3.0.10 and flutter_quill ^1.0.5, version solving failed.
pub get failed (1; So, because myapp depends on both dio ^3.0.10 and flutter_quill ^1.0.5, version solving failed.)

This is a big problem for me, please help me as soon as possible
Thanks

**Comment by singerdmx** [comment]
upgrade to flutter 2.0
Otherwise use stable branch

**Comment by abresihjj** [comment]
> upgrade to flutter 2.0
> Otherwise use stable branch

I have upgraded, however I have this problem

**Comment by abresihjj** [comment]
> upgrade to flutter 2.0
> Otherwise use stable branch

Please advise
I found it very difficult

**Comment by singerdmx** [comment]
dependency_overrides:
  url_launcher: ">=6.0.0"
  http_parser: ">=4.0.0"
  plugin_platform_interface: ">=2.0.0"

**Comment by singerdmx** [comment]
You should go to flutter community for this.

**Comment by singerdmx** [comment]
e.g. https://github.com/flutter/flutter/issues/77458
