### ISSUE TITLE
toolbar error ...in flutter quill 0.3.5 

### ISSUE THREAD

**Issue by davidAg9** [singerdmx/flutter-quill#78]
![image](https://user-images.githubusercontent.com/56321266/111012060-7ae21480-8393-11eb-94cc-10843443ccf8.png)

I encountered this error for both iOS and android run ....please help fix this error for the non null safe version of flutter quill....I am using it in a production app

**Comment by singerdmx** [comment]
What is ur flutter version

**Comment by davidAg9** [comment]
flutter 2.0.1
<img width="609" alt="Screenshot 2021-03-13 at 1 20 52 PM" src="https://user-images.githubusercontent.com/56321266/111031334-f1682c00-83fe-11eb-9a68-7ab9f00b0d17.png">

**Comment by davidAg9** [comment]
I see you have closed this issue 
...has the issue been fixed with some kind of hot fix

**Comment by singerdmx** [comment]
Which channel r u using

**Comment by singerdmx** [comment]
This error is something of your own mistake
That is why I closed it

**Comment by singerdmx** [comment]
U probably need to clear pub cache

`flutter pub cache repair`
