### ISSUE TITLE
[web] Web not working after adding desktop support - see https://github.com/flutter/flutter/issues/36126

### ISSUE THREAD

**Issue by mordivgor** [singerdmx/flutter-quill#80]
Hi,

Just FYI - there is a bug in flutter regarding usage of Platform.is, see https://github.com/flutter/flutter/issues/36126.
It means that the last commits with desktop support breaks the web.
As a workaround:
https://github.com/flutter/flutter/issues/36126#issuecomment-596215587

**Comment by jochendev** [comment]
fix in [master](https://github.com/singerdmx/flutter-quill/blob/498dba598d5ab3c9fa9cdf85c3751148a93c1b4c/lib/widgets/raw_editor.dart#L702)
