### ISSUE TITLE
[Mobile] How to define max line in editor

### ISSUE THREAD

**Issue by tzthantzin** [singerdmx/flutter-quill#806]
My issue is about [Mobile]

Dear Developers,

I have one question, I would like to define max line to show , how can I define maxLine: 2 in quill editor.

Thank you very much 🙏

**Comment by singerdmx** [comment]
Not an issue

**Comment by tzthantzin** [comment]
Dear @singerdmx , Yes it is no issue, so how I can solve this max length. Could you please kindly tell me?

**Comment by adrian-moisa** [comment]
As far as I understand you want a line counter. You can count the number of \n from your delta. these indicate new paragraphs. And for maximum restriction you can impose it from outside of Quill by making it readonly conditionally. If you need more advice about Quill, join my unofficial [discord](https://discord.gg/XpGygmXde4) server. Regards.
