### ISSUE TITLE
[Web] , [Mobile]  and [Desktop]

### ISSUE THREAD

**Issue by Quving** [singerdmx/flutter-quill#807]
Hello,
I have installed flutter_quill version 4.1.9. I copied the example in the readme (Usage) in my code. Through the import I got errors. The error message is
```
Error: 'Text' is imported from both 'package:flutter/src/widgets/text.dart' and 'package:flutter_quill/src/models/documents/nodes/leaf.dart'.
```

Obviously there is an overload of the object "Text". How do we work around the problem?  Surely others have the problem too or?

Of course I can put the Quill widget in a separate widget, where there are no text widgets. But that doesn't solve the problem at the root.

Thanks a lot!

**Comment by Quving** [comment]
Hello @singerdmx,

Would you like to at least tell me, why you closed this issue? I mean it's a serious meant issue by me and also probably for others ^^

**Comment by sils** [comment]
just use `import 'package:flutter_quill/flutter_quill.dart' hide Text;` up at the top
