### ISSUE TITLE
Is there a way to upload images to cloud only when the user clicks on a button?

### ISSUE THREAD

**Issue by marc-walton** [singerdmx/flutter-quill#81]
As of now the images get uploaded as soon as the image is picked but  i want to upload them only when the user clicks on a button, If the user doesn't wanna upload and rewrite. The images already stored becomes a waste of storage space.

**Comment by ArjanAswal** [comment]
Don't return anything before the confirmation from the user in _uploadImageCallback function.
After the user confirms the image, upload and return the URL.

**Comment by marc-walton** [comment]
> Don't return anything before the confirmation from the user in _uploadImageCallback function.
> After the user confirms the image, upload and return the URL.

can i do this for multiple images?
Future<String> _onImagePickCallback(File file) async {
    if (file == null) return null;
    // if user clicks button return 
   StorageUploadTask uploadTask =
    storageRef.child("blog_$blogId.jpg").putFile(imageFile);
    StorageTaskSnapshot storageSnap = await uploadTask.onComplete;
    String downloadUrl = await storageSnap.ref.getDownloadURL();
    return downloadUrl;
  } 
will this work? will the images be visible in the editor if i don't return anything until uploaded?

**Comment by ArjanAswal** [comment]
- I don't think this can work for multiple images
- You also need to implement custom logic for the confirmation of user before uploading it.
