### ISSUE TITLE
DarkMode Placeholder

### ISSUE THREAD

**Issue by wesleytoshio** [singerdmx/flutter-quill#82]
Please add support for dark mode in the placeholder? gray color does not match, if possible add a new placeholderStyle property?

**Comment by singerdmx** [comment]
Could you clarify what dark mode is?

**Comment by singerdmx** [comment]
Check sample page in app folder 
U can pass ur own style

**Comment by wesleytoshio** [comment]
I need to define a default color for my text without style for example: defaultTextColor: Colors.white, the screen I use is dark and I can't read the text inside

**Comment by wesleytoshio** [comment]
I need to define a default color for my text without style for example: defaultTextColor: Colors.white, the screen I use is dark and I can't read the text inside

**Comment by wesleytoshio** [comment]
defaultTextColor: Colors.white = DartTheme
defaultTextColor: Colors.black = LightTheme

you understand me?

**Comment by singerdmx** [comment]
You can submit a pull request

**Comment by singerdmx** [comment]
We don't have plan supporting it

**Comment by wesleytoshio** [comment]
what if i pay? I really need... can we chat via email?

**Comment by singerdmx** [comment]
We have a slack group https://join.slack.com/t/bulletjournal1024/shared_invite/zt-fys7t9hi-ITVU5PGDen1rNRyCjdcQ2g

Sure, you can post something like this https://1o24bbs.com/t/200-bounty-for-implementing-web-support-of-flutter-quill/26179

**Comment by wesleytoshio** [comment]
at the moment yes, I do not intend to do web for now

**Comment by singerdmx** [comment]
OK, I think there are a lot of people interested for the bounty. You can make a post under https://1o24bbs.com/c/bulletjournal/108
I will spread the words.

**Comment by jochendev** [comment]
> defaultTextColor: Colors.white = DartTheme
> defaultTextColor: Colors.black = LightTheme
> **`QuillEditor( defaultTextColor: Colors.white, )`**
> you understand me?

You can do it use `customStyles` like this 
```
QuillEditor(
        customStyles: DefaultStyles.getInstance(context).merge(DefaultStyles(
          ...
        )),
        ...
      )
```

**Comment by wesleytoshio** [comment]
Thanks for support, that as useful
