### ISSUE TITLE
[Desktop] Image padding

### ISSUE THREAD

**Issue by jnet06** [singerdmx/flutter-quill#828]
Hi, 
I am using Quill Editor and it works great so far. :)

I have a problem related to the Image upload feature. When I upload an image using the CameraButton I get a lot of padding around the image, that the generated image doesn't have.

Toolbar 
```
QuillToolbar.basic(
  controller: _controller!,
  showDividers: true,
  toolbarIconAlignment: WrapAlignment.start,
  multiRowsDisplay: true,
  showFontSize: false,
  showImageButton: false,
  onImagePickCallback: uploadImage,
  filePickImpl: filePickImplementation,
)
```

Rich Field
```
 Expanded(
  child: Container(
    color: const Color(0xFFFFFFFF),
    child: Padding(
      padding: const EdgeInsets.all(12.0),
      child: Q.QuillEditor.basic(
        controller: _controller!,
        readOnly: false, // true for view only mode
      ),
    ),
  ),
),

```
As you can see in this image the "text" text, is just before the image start, the rest is all padding:

![image](https://user-images.githubusercontent.com/1557193/169683932-5bf02ecf-eacc-4fcd-863f-24ae887fda96.png)

Would appreciate some help.
Let me know if I can do anything else to reproduce the issue.
Thanks!

**Comment by jnet06** [comment]
I have realized that if in embeds/image.dart I change the center alignment for topLeft

![image](https://user-images.githubusercontent.com/1557193/169684715-14c21f99-bd05-44de-a963-c8d1bf63749c.png)

The problem with the padding disappears. How can I that alignment on my own on the QuillEditor level?

Thanks!

**Comment by singerdmx** [comment]
The padding only works for mobile currently

**Comment by szetakyu** [comment]
I can still see the padding problem for pasting and inserting image after nearly one year.

**Comment by freshtechtips** [comment]
> Hi, I am using Quill Editor and it works great so far. :)
> 
> I have a problem related to the Image upload feature. When I upload an image using the CameraButton I get a lot of padding around the image, that the generated image doesn't have.
> 
> Toolbar
> 
> ```
> QuillToolbar.basic(
>   controller: _controller!,
>   showDividers: true,
>   toolbarIconAlignment: WrapAlignment.start,
>   multiRowsDisplay: true,
>   showFontSize: false,
>   showImageButton: false,
>   onImagePickCallback: uploadImage,
>   filePickImpl: filePickImplementation,
> )
> ```
> 
> Rich Field
> 
> ```
>  Expanded(
>   child: Container(
>     color: const Color(0xFFFFFFFF),
>     child: Padding(
>       padding: const EdgeInsets.all(12.0),
>       child: Q.QuillEditor.basic(
>         controller: _controller!,
>         readOnly: false, // true for view only mode
>       ),
>     ),
>   ),
> ),
> ```
> 
> As you can see in this image the "text" text, is just before the image start, the rest is all padding:
> 
> ![image](https://user-images.githubusercontent.com/1557193/169683932-5bf02ecf-eacc-4fcd-863f-24ae887fda96.png)
> 
> Would appreciate some help. Let me know if I can do anything else to reproduce the issue. Thanks!

Recently we have added padding, alignment, and margin for the desktop as well

If you still facing any other issues or have any questions feel free to contact us on GitHub
