### ISSUE TITLE
**Before Closing , Atleast Tell What You guys can do or going to do?**

### ISSUE THREAD

**Issue by KrishnaBros** [singerdmx/flutter-quill#84]
**Before Closing , Atleast Tell What You guys can do or going to do?**

_Originally posted by @KrishnaBros in https://github.com/singerdmx/flutter-quill/issues/83#issuecomment-798928760_

**Comment by KrishnaBros** [comment]
Sorry for just making new issues but i needed some answer

**Comment by KrishnaBros** [comment]
@singerdmx  Please 🙏😞

**Comment by florianh01** [comment]
please refrain from opening new issues. See #15
