### ISSUE TITLE
will flutter_quill support collaborative real-time editing

### ISSUE THREAD

**Issue by dreamer2q** [singerdmx/flutter-quill#85]
I am new to editors, and I like to know some detail about implementing this.

eg its difficulties and so on

If not difficult for me, I want to contrib

**Comment by singerdmx** [comment]
What details do you need?

**Comment by ArjanAswal** [comment]
It is possible.
See [this](https://github.com/memspace/zefyr/issues/409#issuecomment-799207580)

**Comment by ArjanAswal** [comment]
Not a package specific feature.
Closing.

**Comment by singerdmx** [comment]
Closing due to no response from creator
