### ISSUE TITLE
[IOS] [1.0.8] When typing at the end, the window will flash up and down

### ISSUE THREAD

**Issue by youngerstyle** [singerdmx/flutter-quill#86]
Has anyone encountered it? Is there any way to avoid or fix it? 
![Mar-15-2021 14-45-11](https://user-images.githubusercontent.com/7426274/111113765-375af680-859d-11eb-8291-67cea54f0474.gif)

**Comment by singerdmx** [comment]
cannot repro

**Comment by youngerstyle** [comment]
@singerdmx
This is the result of executing flutter doctor:
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by singerdmx** [comment]
R u using master branch? That is supposed to be above 2.0

**Comment by youngerstyle** [comment]
@singerdmx
My project cannot be upgraded to 2.0 yet,
I used the master branch and changed the dependencies to any.
I can use a copy of version 2.0 for testing, wait for a while.

**Comment by singerdmx** [comment]
Use stable branch

**Comment by youngerstyle** [comment]
@singerdmx
I used the stable branch for testing, but the problem still exists.
Forgot to say, my simulator is ios14.4.
![Mar-15-2021 15-38-39](https://user-images.githubusercontent.com/7426274/111119274-e3541000-85a4-11eb-8d51-38b1a7d931dd.gif)

**Comment by ArjanAswal** [comment]
Are you using example app?

**Comment by youngerstyle** [comment]
@ArjanAswal
Yes, I am using the example app.
clone complete and run directly.

**Comment by ArjanAswal** [comment]
I cannot reproduce the issue.
Try using real device instead of an emulator.

**Comment by youngerstyle** [comment]
@ArjanAswal @ArjanAswal 
I may have found the problem. Why is there a static offset in the following code? What animation effect do I think?
The offset of this scroll bar is not effective on Android (it will not trigger listeners), but it is effective on iOS. 

  double getOffsetToRevealCursor(
      double viewportHeight, double scrollOffset, double offsetInViewport) {
    List<TextSelectionPoint> endpoints = getEndpointsForSelection(selection);
    if (endpoints.length != 1) {
      return null;
    }
    RenderEditableBox child = childAtPosition(selection.extent);
    **const kMargin = 8.0;**//<--------Weird value

    double caretTop = endpoints.single.point.dy -
        child.preferredLineHeight(TextPosition(
            offset:
                selection.extentOffset - child.getContainer().getOffset())) -
        kMargin +
        offsetInViewport;
    final caretBottom = endpoints.single.point.dy + kMargin + offsetInViewport;
    double dy;
    if (caretTop < scrollOffset) {
      dy = caretTop;
    } else if (caretBottom > scrollOffset + viewportHeight) {
      dy = caretBottom - viewportHeight;
    }
    if (dy == null) {
      return null;
    }
    return math.max(dy, 0.0);
  }

**Comment by ArjanAswal** [comment]
Have you found the solution?
Can you file the PR for this?
Thanks

**Comment by ArjanAswal** [comment]
Also why is it not showing in Android?
I am using an android device btw.

**Comment by youngerstyle** [comment]
@ArjanAswal
No solution, I just changed the static value to 0,
There should be a deeper problem. My guess is that there is a problem in the calculation of the paragraph height in flutter, which causes the cursor height to be different, and then leads to recalculation.
I did the following test (static value is 0, android), and found that the height of the cursor in the last line will change: 
![Mar-16-2021 09-24-08](https://user-images.githubusercontent.com/7426274/111242201-a38b3800-8639-11eb-94be-269bb9db68af.gif)

**Comment by ArjanAswal** [comment]
Are you sure that the cursor height in last line changes?
I am suspecting that the last line is cut off and not showing fully as the editor doesn't get fully scrolled.
when you start typing the editor gets scrolled and cursor appears to have increased in height.

**Comment by ArjanAswal** [comment]
![ezgif-2-e1ea569a4805.gif](https://user-images.githubusercontent.com/64231789/111259117-5496d000-8644-11eb-89af-ec21261e6157.gif)

Cannot reproduce (Android)

**Comment by youngerstyle** [comment]
@ArjanAswal 
The strange thing is, if the scroll position is wrong at the beginning, then the scroll position should be correct after I add the text and then delete the text, but it is not from the performance point of view, because the cursor repeatedly changes height.
I have no choice but to change the above static value to 0 in my program, but I cannot PR this because I think the problem is not here.
