### ISSUE TITLE
[iOS] - The text style is removed after voice input

### ISSUE THREAD

**Issue by KillianGrd35** [singerdmx/flutter-quill#866]
My issue is about [iOS], I can't reproduce it on Android.
I have noticed that when you select a text style in the toolbar (bold, italic, underline...) and that you do a voice input, the text style is applied but when the voice input is over, this text style disappear. I've also tested it on the flutter_quill example app on the current version (5.0.3) and I found same behavior there too.
Also, on an IPad, the text style is removed as soon as the voice input is over but on an iPhone you have to leave the keyboard.

**Steps to reproduce** : 
- Click anywhere to open the keyboard
- Put some text style in the toolbar (bold, italic, underline...)
- Touch the voice input button to tell your text at loud
- Stop the voice input and the text style is removed (for an iPad, on an iPhone you have to leave the keyboard)

https://user-images.githubusercontent.com/71318025/177570330-cb2a03bb-ac8c-4e0a-ba54-b760dc7363f6.mp4

Would appreciate some help.
Thanks!

**Comment by singerdmx** [comment]
Please submit a PR to fix it.

**Comment by singerdmx** [comment]
Hmm... this is new - voice input

**Comment by singerdmx** [comment]
Actually I am unfamiliar what logic is related when it comes to voice input. If you know which library is being involved, please let me know

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
