### ISSUE TITLE
Deleting added images or videos leads to "storage leaks"

### ISSUE THREAD

**Issue by abcxcba** [singerdmx/flutter-quill#873]
Deleting an image in the editor only removes the URL, there is no way to delete the corresponding file.
Think about adding and deleting a 10M size image 100 times in the editor.
If the image is just left there, it will take up 1G storage space, “storage leak? ”

**Comment by singerdmx** [comment]
Please submit a PR to fix it.

**Comment by abcxcba** [comment]
I think adding a remove callback function should solve the problem, but I don't know where to add it.
There are a lot of flutter-quill files and they often import each other, which seems a bit messy (sorry to say that), and I know very little about flutter-quill at the moment, so I can't submit a PR.

**Comment by singerdmx** [comment]
You are using keyboard to delete the image/video?

**Comment by singerdmx** [comment]
If you are talking about using keyboard, it is more complicated since we need to update keyboard listener

**Comment by singerdmx** [comment]
check out lib/src/widgets/keyboard_listener.dart

**Comment by singerdmx** [comment]
Actually no need for all these.
You can just track the changes and figure out if the user deletes video/image

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/122956/180172481-4e3a7ad3-29a3-42af-97dd-588e81d9f98b.png">

**Comment by abcxcba** [comment]
Yes, I am using the keyboard to delete.
Thank you very much for your reply, your reply was very helpful to me.
I'll look into it.

Also it would be perfect if it provided onImagePickCallback like QuillToolbar.basic provides onImagePickCallback? onImageRemoveCallback would be perfect and the video would be similar.

I'm sure others will encounter this problem as well.
I found a previous discussion:#600

**Comment by DmitrySboychakov** [comment]
I think we need more generalized system here. What about add some callback to the Embeddable itself?

**Comment by abcxcba** [comment]
> I think we need more generalized system here. What about add some callback to the Embeddable itself?

I do agree with you.
I think all embedded content that is not directly included in the document needs a remove callback function, just like the dispos() function to clean up unused resources.
This is a very essential feature.

**Comment by singerdmx** [comment]
Yes, true. But you also want to listen to DELETE key, right?

**Comment by abcxcba** [comment]
> Yes, true. But you also want to listen to DELETE key, right?

Yes, the DELETE key, unlike other character keys, represents the delete function for all objects in a document, whether they are characters or pictures, videos, etc.

**Comment by singerdmx** [comment]
There may be a better way or a central way to deal with this.
Add a new delete rule to subscribe any event you are interested.
![image](https://user-images.githubusercontent.com/122956/180376228-8f77614d-0fa9-4ddc-9de8-738e8dfc4a4d.png)

**Comment by singerdmx** [comment]
This can intercept all delete operation happened

**Comment by abcxcba** [comment]
> This can intercept all delete operation happened

Yes, this is the best way 👍

**Comment by abcxcba** [comment]
Depending on how embed is considered, I think all objects displayed in the editor can be considered embed units, just that their characteristics are different.

Characters, images, videos, and so on, are all embeded units inside the editor, so that all the content inside the editor is conceptually unified.

String is the connection of characters, characters belong to connectable objects, images, and videos can not be connected, perhaps Emoji, like characters, belong to connectable units.

If so it can be named DeletionCallbackRule , in which all deletions are handled.

Of course, if you treat characters as general objects, pictures, videos, files, etc. as embedded objects, EmbedDeletionCallbackRule is more appropriate.

**Comment by singerdmx** [comment]
In order to clarify `Embed`, I recorded a video and please check it out https://youtu.be/pI5p5j7cfHc

This should help you.

**Comment by singerdmx** [comment]
@abcxcba are you working on a change for this or do you need help?

**Comment by abcxcba** [comment]
> @abcxcba are you working on a change for this or do you need help?

I recently needed to stop and work on other issues and wasn't sure how soon I could keep coming back to this.

**Comment by freshtechtips** [comment]
We have added a callback for `onRemove` in flutter_quill_extensions

This issue has been fixed, if you still facing this issue or any others, feel free to contact us on GitHub
