### ISSUE TITLE
[Mobile] Copy/Paste/SelectAll tooltip doesn't work in readOnly mode

### ISSUE THREAD

**Issue by singerdmx** [singerdmx/flutter-quill#878]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/122956/180273719-f6abc46f-936b-4e73-913f-fe896fec15b7.png">

Relevant code here

**Comment by singerdmx** [comment]
Hmm... I seem unable to repro the issue.
I have `Copy` option in readonly mode

**Comment by agjane** [comment]
Our company has the same problem as described above. Can you help with this?

**Comment by freshtechtips** [comment]
> Hmm... I seem unable to repro the issue. I have `Copy` option in readonly mode

We are bit supposed to paste things in readOnly mode.

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
