### ISSUE TITLE
[Web] Playing Videos as Embed Doesn't Work

### ISSUE THREAD

**Issue by garv-shah** [singerdmx/flutter-quill#887]
My issue is about [Web]

I was attempting to get the defaultEmbedBuilderWeb working with my application by looking at the example, and it was throwing an exception of `owner!._debugCurrentBuildTarget == this`.

This also seems to be the case when running the example project without making any changes. Any idea what the issue is?
Thanks!

**Comment by singerdmx** [comment]
See https://github.com/singerdmx/flutter-quill#web

The sample demo fails on the web because the video player embed is missing.

**Comment by singerdmx** [comment]
When we added support for video, we haven't figure out how to do it for web. We would appreciate some help to have that added.

**Comment by garv-shah** [comment]
oh, so the video embeds don't work at all on web right now?

**Comment by singerdmx** [comment]
You should hit here

![image](https://user-images.githubusercontent.com/122956/180633670-adc4ff36-bd7f-49fc-91a1-c50a2f6b2339.png)

**Comment by singerdmx** [comment]
Right now the sample page's defaultEmbedBuilder does not have support for video
![image](https://user-images.githubusercontent.com/122956/180633716-6e211f8a-97c9-4c39-8734-cbfe0cb1f077.png)

**Comment by singerdmx** [comment]
If you can help out finishing that for example, it is really helpful

**Comment by garv-shah** [comment]
hmmm, interesting, alright, i'll try my best to see if there's anything I can do right now!

**Comment by singerdmx** [comment]
Actually it is here

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/122956/180634298-8e3c7f4d-8dd2-4703-8dc8-88cf01470575.png">

**Comment by singerdmx** [comment]
If you just want to work around it, just add a case 'video' and return a container

**Comment by garv-shah** [comment]
I think it might be better to have a similar container in the example saying that it's not supported yet
Also, the real_ui file seems to have errors for me due to https://github.com/flutter/flutter/issues/41563, which it seems like you've already seen, a slightly different configuration seemed to work for me

**Comment by singerdmx** [comment]
https://github.com/singerdmx/flutter-quill/commit/68c814bd5365325fbb2fd35ed8022ee51dcd37b9 here is a workaround

**Comment by singerdmx** [comment]
Oh they still haven't fixed `real_ui ` problem.
In my opinion, flutter support for web is still in early stage and not mature enough.
I use flutter quill mostly for mobile. Supporting web is nice but my knowledge is limited.

**Comment by garv-shah** [comment]
yeahh, things do seem a lot more finicky on web for sure. honestly I would think that embeds on web should be the easiest but it seems that isn't the case

**Comment by singerdmx** [comment]
Maybe there is some public library for handling this for web? 🙏 If so we can import it.

**Comment by singerdmx** [comment]
If you try the code for mobile, what happens?
    ```
case BlockEmbed.videoType:
      final videoUrl = node.value.data;
      if (videoUrl.contains('youtube.com') || videoUrl.contains('youtu.be')) {
        return YoutubeVideoApp(
            videoUrl: videoUrl, context: context, readOnly: readOnly);
      }
      return VideoApp(
        videoUrl: videoUrl,
        context: context,
        readOnly: readOnly,
        onVideoInit: onVideoInit,
      );
```

**Comment by singerdmx** [comment]
I guess the code for mobile might just work. Just need to export VideoApp and YoutubeVideoApp classes.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/122956/180634802-9783670f-d3f9-4c63-891b-52bfce5acb18.png">

**Comment by garv-shah** [comment]
sorry, was just trying to get universal_ui to work for me, I ended up using the "shims" example from the thread above.
Mobile's already been working for me, I'll try [this](https://stackoverflow.com/a/61977369/9937309) out on web really quickly

**Comment by garv-shah** [comment]
Nice! It seems to be somewhat working!

<img width="1440" alt="Screen Shot 2022-07-24 at 4 31 44 pm" src="https://user-images.githubusercontent.com/64292655/180635361-5e5ee095-3d30-4ad4-b883-67f8d9f4ece1.png">

**Comment by garv-shah** [comment]
The problem right now is that https://www.youtube.com/embed/dQw4w9WgXcQ will work since it's an embed, but https://www.youtube.com/watch?v=dQw4w9WgXcQ won't
Seems to be a pretty simple fix though!

**Comment by singerdmx** [comment]
Nice! Please share the code in example with a PR. And thanks!

**Comment by garv-shah** [comment]
My universal_ui file was as follows:

```dart
library universal_ui;

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:universal_html/html.dart' as html;
import 'package:youtube_player_flutter_quill/youtube_player_flutter_quill.dart';

import '../../widgets/responsive_widget.dart';
import 'shims/dart_ui.dart' as ui_instance;

class PlatformViewRegistryFix {
  void registerViewFactory(dynamic x, dynamic y) {
    if (kIsWeb) {
      ui_instance.platformViewRegistry.registerViewFactory(
        x,
        y,
      );
    }
  }
}

class UniversalUI {
  PlatformViewRegistryFix platformViewRegistry = PlatformViewRegistryFix();
}

var ui = UniversalUI();

Widget defaultEmbedBuilderWeb(
    BuildContext context,
    QuillController controller,
    Embed node,
    bool readOnly,
    void Function(GlobalKey videoContainerKey)? onVideoInit,
    ) {
  switch (node.value.type) {
    case BlockEmbed.imageType:
    // TODO: handle imageUrl of base64
      final imageUrl = node.value.data;
      final size = MediaQuery.of(context).size;
      UniversalUI().platformViewRegistry.registerViewFactory(
          imageUrl, (viewId) => html.ImageElement()..src = imageUrl);
      return Padding(
        padding: EdgeInsets.only(
          right: ResponsiveWidget.isMediumScreen(context)
              ? size.width * 0.5
              : (ResponsiveWidget.isLargeScreen(context))
              ? size.width * 0.75
              : size.width * 0.2,
        ),
        child: SizedBox(
          height: MediaQuery.of(context).size.height * 0.45,
          child: HtmlElementView(
            viewType: imageUrl,
          ),
        ),
      );
    case BlockEmbed.videoType:
    // TODO: implement 'video' builder
      String embedUrl = "https://www.youtube.com/embed/${YoutubePlayer.convertUrlToId(node.value.data) ?? 'dQw4w9WgXcQ'}";

      UniversalUI().platformViewRegistry.registerViewFactory(
          embedUrl,
              (int id) => html.IFrameElement()
            ..width = MediaQuery.of(context).size.width.toString()
            ..height = MediaQuery.of(context).size.height.toString()
            ..src = embedUrl
            ..style.border = 'none');

      return SizedBox(
        height: 500,
        child: HtmlElementView(
          viewType: embedUrl,
        ),
      );
    default:
      throw UnimplementedError(
        'Embeddable type "${node.value.type}" is not supported by default '
            'embed builder of QuillEditor. You must pass your own builder function '
            'to embedBuilder property of QuillEditor or QuillField widgets.',
      );
  }
}
```

I think it would probably be preferable to have the defaultEmbedBuilderWeb be a built in value rather than in the example, so is it possible for you to add it to the example and as a default variable in the package? I'll do it afterwards if it's too much work, I'll just be gone for a bit :)

**Comment by singerdmx** [comment]
I think I got what you mean to some extent. I guess it would be easier just for you to go ahead with a PR as `a default variable in the package`.

**Comment by singerdmx** [comment]
I don't understand this code
```
String embedUrl = "https://www.youtube.com/embed/${YoutubePlayer.convertUrlToId(node.value.data) ?? 'dQw4w9WgXcQ'}";
```
What is dQw4w9WgXcQ ?

**Comment by singerdmx** [comment]
Oh I guess you still need work for parse url

**Comment by garv-shah** [comment]
> I don't understand this code
> 
> ```
> String embedUrl = "https://www.youtube.com/embed/${YoutubePlayer.convertUrlToId(node.value.data) ?? 'dQw4w9WgXcQ'}";
> ```
> 
> What is dQw4w9WgXcQ ?

For now it's a backup youtube video to take you to if the URL is invalid.
You're right, it needs just a bit more work, I'll send the finish version in a bit

**Comment by garv-shah** [comment]
This lets you put in any video, not just a youtube video, but it is still a bit not ideal. For example, there are a few issues with focusing (clicking on overlays on top still has the focus on the video) and scrolling when hovering over the youtube videos doesn't scroll the actual page. Right now it works, but is not ideal for a good experience

```dart
library universal_ui;

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:universal_html/html.dart' as html;
import 'package:youtube_player_flutter_quill/youtube_player_flutter_quill.dart';

import '../../widgets/responsive_widget.dart';
import 'shims/dart_ui.dart' as ui_instance;

class PlatformViewRegistryFix {
  void registerViewFactory(dynamic x, dynamic y) {
    if (kIsWeb) {
      ui_instance.platformViewRegistry.registerViewFactory(
        x,
        y,
      );
    }
  }
}

class UniversalUI {
  PlatformViewRegistryFix platformViewRegistry = PlatformViewRegistryFix();
}

var ui = UniversalUI();

Widget defaultEmbedBuilderWeb(
    BuildContext context,
    QuillController controller,
    Embed node,
    bool readOnly,
    void Function(GlobalKey videoContainerKey)? onVideoInit,
    ) {
  switch (node.value.type) {
    case BlockEmbed.imageType:
    // TODO: handle imageUrl of base64
      final imageUrl = node.value.data;
      final size = MediaQuery.of(context).size;
      UniversalUI().platformViewRegistry.registerViewFactory(
          imageUrl, (viewId) => html.ImageElement()..src = imageUrl);
      return Padding(
        padding: EdgeInsets.only(
          right: ResponsiveWidget.isMediumScreen(context)
              ? size.width * 0.5
              : (ResponsiveWidget.isLargeScreen(context))
              ? size.width * 0.75
              : size.width * 0.2,
        ),
        child: SizedBox(
          height: MediaQuery.of(context).size.height * 0.45,
          child: HtmlElementView(
            viewType: imageUrl,
          ),
        ),
      );
    case BlockEmbed.videoType:
    // TODO: implement 'video' builder
      String? youtubeID = YoutubePlayer.convertUrlToId(node.value.data);
      String embedUrl;

      if (youtubeID != null) {
        embedUrl = "https://www.youtube.com/embed/${YoutubePlayer.convertUrlToId(node.value.data)}";
      } else {
        embedUrl = node.value.data;
      }

      UniversalUI().platformViewRegistry.registerViewFactory(
          embedUrl,
              (int id) => html.IFrameElement()
            ..width = MediaQuery.of(context).size.width.toString()
            ..height = MediaQuery.of(context).size.height.toString()
            ..src = embedUrl
            ..style.border = 'none');

      return SizedBox(
        height: 500,
        child: HtmlElementView(
          viewType: embedUrl,
        ),
      );
    default:
      throw UnimplementedError(
        'Embeddable type "${node.value.type}" is not supported by default '
            'embed builder of QuillEditor. You must pass your own builder function '
            'to embedBuilder property of QuillEditor or QuillField widgets.',
      );
  }
}
```

**Comment by singerdmx** [comment]
What did you add in pubspec.yaml ?

**Comment by garv-shah** [comment]
nothing, what makes you say that?

**Comment by singerdmx** [comment]
`import 'shims/dart_ui.dart'` seems to give me error.

Also I need to add dependency `youtube_player_flutter_quill: ^8.2.2`

**Comment by singerdmx** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/122956/180637129-cd217edc-e77e-4641-b32c-168d9dfb57e3.png">

**Comment by garv-shah** [comment]
youtube_player_flutter_quill should already be in the pubspec, shims was a folder I added since the universal_ui already in there wasn't working for me. It's the same as putting `import 'fake_ui.dart' if (dart.library.html) 'real_ui.dart' as ui_instance;`, just that that doesn't work for my computer

**Comment by garv-shah** [comment]
https://github.com/flutter/flutter/issues/41563 this is where I got shims from

**Comment by singerdmx** [comment]
Submit https://github.com/singerdmx/flutter-quill/commit/ce0b551d345501b9d3b4414ba9ae51e7af5daeae

Yeah, clicking on it seems not playing the video.
Still need some work but it is big progress already.

**Comment by garv-shah** [comment]
Clicking on it doesn't play the video if you are already focused on the QuillEditor. If you click off the QuillEditor and then click on the video, it plays and pauses. Might need some logic with a focus node

**Comment by singerdmx** [comment]
I see.
BTW are you able to debug it when running in web.
I can do it in command line `flutter run -d chrome`.
But it will be better if I can debug this with break point in android studio.

**Comment by garv-shah** [comment]
yup, I'm using IntelliJ and can debug it and all the normal stuff I do with web. Are you getting a specific error?

**Comment by singerdmx** [comment]
Oh I got it. Didn't notice I can select chrome here. My bad

<img width="528" alt="image" src="https://user-images.githubusercontent.com/122956/180637542-0b0cff06-c164-42a0-b4e3-f610a870bcb0.png">

**Comment by garv-shah** [comment]
nice nice

**Comment by garv-shah** [comment]
I tried a couple webview plugins, and they all seem to have the same quirks as the normal implementation, with the scrolling and focusing. [This](https://pub.dev/packages/webviewx) plugin does seem to be nice, with a couple more options, and allowing youtube to be fullscreen even as an embed, as it modifies some headers

I have no clue how to work with focus nodes so if you can get that working that would be wonderful!

Here's what I used when messing around with the webviewx plugin:

```dart
library universal_ui;

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:universal_html/html.dart' as html;
import 'package:youtube_player_flutter_quill/youtube_player_flutter_quill.dart';
import 'package:webviewx/webviewx.dart';

import '../../widgets/responsive_widget.dart';
import 'shims/dart_ui.dart' as ui_instance;

class PlatformViewRegistryFix {
  void registerViewFactory(dynamic x, dynamic y) {
    if (kIsWeb) {
      ui_instance.platformViewRegistry.registerViewFactory(
        x,
        y,
      );
    }
  }
}

class UniversalUI {
  PlatformViewRegistryFix platformViewRegistry = PlatformViewRegistryFix();
}

var ui = UniversalUI();

Widget defaultEmbedBuilderWeb(
    BuildContext context,
    QuillController controller,
    Embed node,
    bool readOnly,
    void Function(GlobalKey videoContainerKey)? onVideoInit,
    ) {
  switch (node.value.type) {
    case BlockEmbed.imageType:
    // TODO: handle imageUrl of base64
      final imageUrl = node.value.data;
      final size = MediaQuery.of(context).size;
      UniversalUI().platformViewRegistry.registerViewFactory(
          imageUrl, (viewId) => html.ImageElement()..src = imageUrl);
      return Padding(
        padding: EdgeInsets.only(
          right: ResponsiveWidget.isMediumScreen(context)
              ? size.width * 0.5
              : (ResponsiveWidget.isLargeScreen(context))
              ? size.width * 0.75
              : size.width * 0.2,
        ),
        child: SizedBox(
          height: MediaQuery.of(context).size.height * 0.45,
          child: HtmlElementView(
            viewType: imageUrl,
          ),
        ),
      );
    case BlockEmbed.videoType:
    // TODO: implement 'video' builder

      String? youtubeID = YoutubePlayer.convertUrlToId(node.value.data);
      String embedUrl;

      if (youtubeID != null) {
        embedUrl = "https://www.youtube.com/embed/${YoutubePlayer.convertUrlToId(node.value.data)}";
      } else {
        embedUrl = node.value.data;
      }

      // UniversalUI().platformViewRegistry.registerViewFactory(
      //     embedUrl,
      //         (int id) => html.IFrameElement()
      //       ..width = MediaQuery.of(context).size.width.toString()
      //       ..height = MediaQuery.of(context).size.height.toString()
      //       ..src = embedUrl
      //       ..style.border = 'none');

      return WebViewX(
          initialContent: '',
          initialSourceType: SourceType.html,
          onWebViewCreated: (controller) => controller.loadContent(
            embedUrl,
            SourceType.url,
          ), height: 500, width: MediaQuery.of(context).size.width,
      );
    default:
      throw UnimplementedError(
        'Embeddable type "${node.value.type}" is not supported by default '
            'embed builder of QuillEditor. You must pass your own builder function '
            'to embedBuilder property of QuillEditor or QuillField widgets.',
      );
  }
}
```

**Comment by singerdmx** [comment]
> I have no clue how to work with focus nodes so if you can get that working that would be wonderful!

Yeah I suspect focus node too but hard to say. Need to debug it.

**Comment by singerdmx** [comment]
Hmm, it just makes the page all blank for me. 
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/122956/180638175-4e446deb-bfda-4a67-856d-0afd893d8a37.png">

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/122956/180638160-efe2fb2c-8847-4fda-b121-4ae660d35701.png">

**Comment by garv-shah** [comment]
huh, that's odd :/
not sure why that's happening at all

**Comment by tiger5226** [comment]
Ok, I am a bit interested here. Maybe this is a dumb question, but why is there so much focus on using `universal_ui` ? I don't understand why that is even required to achieve the result desired which is to show a video. 

[package:video_player](https://pub.dev/packages/video_player) already supports iOS, Android **& Web**

For youtube specific embed functionality there is also:

[package:youtube_player_iframe](https://pub.dev/packages/youtube_player_iframe) already supports iOS, Android **& Web**

How come we are not just using these defaults instead of trying to do platform specific handling? Just curious, I assume I am missing something and I was curious.

**Comment by freshtechtips** [comment]
> You should hit here
> 
> ![image](https://user-images.githubusercontent.com/122956/180633670-adc4ff36-bd7f-49fc-91a1-c50a2f6b2339.png)

Is the issue fixed yet??

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
