### ISSUE TITLE
[web] All inserted widgets in editor (e.g. image) has been rebuilding constantly

### ISSUE THREAD

**Issue by mordivgor** [singerdmx/flutter-quill#89]
Hello,

I would like to ask about whether it is a editor nature (and its internal limitation) or could be improved.
When I am entering new line by clicking enter (or pasting new image or other action) the inserted image (and every custom widget which I have inserted) is being rebuilt every time when such action appears.
It looks like every action which I mentioned (new line etc.) causes that the whole editor executes embedBuilder and create new instances of inserted widgets (i.e. image).
Do you see any chance which could improve this situation?

**Comment by singerdmx** [comment]
@rish07 do you know anything about it?

**Comment by singerdmx** [comment]
Fixed by https://github.com/singerdmx/flutter-quill/commit/54c3eb446e2b90ec0a977d29eb0f21e2752dd07f

Please reopen if it still exists

**Comment by mordivgor** [comment]
@singerdmx  I would like to reopen this issue, because it is still visible in 1.0.9 version. The video shows the blinking image when I am adding new line..

https://user-images.githubusercontent.com/54472480/111499225-0288a400-8743-11eb-8c75-961e5ddab50f.mp4

**Comment by rish07** [comment]
Hey @singerdmx, i am busy with my exams rn, will take a look after them.

**Comment by mordivgor** [comment]
hello @rish07 
I know exams are more important than this plugin, but I am wondering if you had time to take a look at that :)
Or at least maybe you have some tip how "rendering" of inserted objects are done by this plugin - maybe it would help me to find the problematic part of the code.

PS. I think it might be not only relevant to Web, but this is only my suspicious.

**Comment by rish07** [comment]
@mordivgor I am not really sure why it's rebuilding it.
