### ISSUE TITLE
[Mobile] Single embed in a text line always takes the full width

### ISSUE THREAD

**Issue by shorben07** [singerdmx/flutter-quill#896]
Because of the following code in `TextLine` class
```
    if (widget.line.hasEmbed && widget.line.childCount == 1) {
      // For video, it is always single child
      final embed = widget.line.children.single as Embed;
      return EmbedProxy(
        widget.embedBuilder(
          context,
          widget.controller,
          embed,
          widget.readOnly,
          null,
        ),
      );
    }
```
Single embed in a text line always takes the full width. This makes sense for image and video. But my use case is mentions that are implemented as custom embed type
<img width="377" alt="Screenshot 2022-07-30 at 14 34 16" src="https://user-images.githubusercontent.com/36268266/181909050-a47969f5-1847-401e-bb6c-0386c2d2a94d.png">
On the screenshot above cursor is on the right edge because embed took the whole width.

If you type at least one more character then everything looks good again
<img width="375" alt="Screenshot 2022-07-30 at 14 36 33" src="https://user-images.githubusercontent.com/36268266/181909127-93aada78-bd15-4488-884b-4f52f673dd3a.png">

Any ideas on how to workaround the issue? Or what's the best way to make this behaviour configurable? I am willing to contribute

**Comment by singerdmx** [comment]
Actually for image we allow it to not take the whole line.
I think the code you pasted is the right place. And you can see it is meant for video.
Well, in the past embed is either image or video.
I guess you want the new embed behavior to be more like image.
Just check how image works in the code following the section.

**Comment by singerdmx** [comment]
If you change the if condition to be video only, your embed will probably fall through to the rest of the code

**Comment by shorben07** [comment]
@singerdmx In the code that I posted in the initial message I don't actually see a type check related to video although comment says so.
Plus in the debugger image flow falls into same if condition as video https://github.com/singerdmx/flutter-quill/blob/master/lib/src/widgets/text_line.dart#L135

> If you change the if condition to be video only, your embed will probably fall through to the rest of the code
To avoid breaking changes I would keep logic for images and videos as it is now

**Comment by singerdmx** [comment]
What I am trying to say is:
For the if condition here (code you pasted), you can restrict it to only types of video and image. And you can follow how image works when it comes to the scenario which allows embed not to take up the whole line

**Comment by singerdmx** [comment]
Also in document load method we automatically add line break for video type. Just fyi

**Comment by shorben07** [comment]
Thanks, @singerdmx! I'll try to come up with the solution. Closing this issue for now

**Comment by huangsir0** [comment]
I have the same problem,more info about this?

**Comment by JunCaiLi** [comment]
hi @huangsir0  i try to solve this problem by some trick, add a space before adding customEnbed, but when user delete the space the customEnbed will take whole line. so may be have better method to solve this issue and i browsed all the issues and didn't see a good solution
```dart
    _controller.document.changes.listen((event) {
      // due to customEmbedWidget takes 100% width of view, so add space in editor start
      String text = _controller.document
          .toDelta()
          .first
          .data
          .toString()
          .replaceAll('\n', '');
      if (!text.startsWith(' ') && text.length < 2) {
        _controller.document.insert(0, ' ');
        _controller.updateSelection(
          TextSelection.collapsed(offset: _controller.document.length),
          quill.ChangeSource.LOCAL,
        );
      }
    });
```
<img width="293" alt="image" src="https://user-images.githubusercontent.com/42626941/212017973-682f44f8-5ec6-4335-990d-8970104f8409.png">

**Comment by JunCaiLi** [comment]
> > hi @huangsir0 i try to solve this problem by some trick, add a space before adding customEnbed, but when user delete the space the customEnbed will take whole line. so may be have better method to solve this issue and i browsed all the issues in repo and didn't see a good solution
> > ```dart
> >     _controller.document.changes.listen((event) {
> >       // due to customEmbedWidget takes 100% width of view, so add space in editor start
> >       String text = _controller.document
> >           .toDelta()
> >           .first
> >           .data
> >           .toString()
> >           .replaceAll('\n', '');
> >       if (!text.startsWith(' ') && text.length < 2) {
> >         _controller.document.insert(0, ' ');
> >         _controller.updateSelection(
> >           TextSelection.collapsed(offset: _controller.document.length),
> >           quill.ChangeSource.LOCAL,
> >         );
> >       }
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="293" src="https://user-images.githubusercontent.com/42626941/212017973-682f44f8-5ec6-4335-990d-8970104f8409.png">
> 
> you can use expanded of EmbedBuilder to resoule this issue, like this:
> 
> ![image](https://user-images.githubusercontent.com/10161096/234219979-834889b5-852a-48fb-ac7f-c6ef3478e18a.png)

Thanks, https://github.com/singerdmx/flutter-quill/pull/1141#issue-1640497433 this PR solved this issue recently
