### ISSUE TITLE
Is there a way to get or load html content

### ISSUE THREAD

**Issue by tevfik1** [singerdmx/flutter-quill#9]
Hello,

I really like this package, it looks promising. I only have one question:
is there an Html converter? what if we want to get or load html content in editor?

Thanks.

**Comment by singerdmx** [comment]
Thanks for asking.
Check out https://github.com/singerdmx/flutter-quill/issues/1

**Comment by singerdmx** [comment]
Closing

**Comment by singerdmx** [comment]
@tevfik1 check out https://github.com/ArjanAswal/quill_markdown

**Comment by dsyrstad** [comment]
@tevfik1 https://pub.dev/packages/vsc_quill_delta_to_html provides a robust delta to HTML conversion.
