### ISSUE TITLE
[Mobile] Missing concrete implementation of 'TextInputClient.performSelector'. Try implementing the missing method, or make the class abstract.

### ISSUE THREAD

**Issue by louislamme** [singerdmx/flutter-quill#905]
This error happens when I use flutter master channel **Flutter:3.1.0-0.0.pre.2122** with **flutter_quill: 5.4.1**.

The reason I needa use the latest master version is here:
https://github.com/flutter/flutter/issues/104049

May I ask if it's possible to fix it? Thanks!

**Comment by FelixMittermeier** [comment]
Add
```
@override
  void performSelector(String selectorName) {}
```
inside the raw_editor.dart file in line 248

**Comment by louislamme** [comment]
@FelixMittermeier 
Sorry for late reply, Thank you!
