### ISSUE TITLE
[Mobile] Node class is not exported

### ISSUE THREAD

**Issue by bytes7bytes7** [singerdmx/flutter-quill#907]
I try to implement my own QuillEditor.linkActionPickerDelegate and signature of this method is
```
typedef LinkActionPickerDelegate = Future<LinkMenuAction> Function(
    BuildContext context, String link, Node node);
```

And I noticed that I am not able to import Node class

**Comment by singerdmx** [comment]
https://github.com/singerdmx/flutter-quill/commit/b8ebcbdbda2191a059b42ce6f6e438b5ab347b47
