### ISSUE TITLE
toPlainText have a \n at the end

### ISSUE THREAD

**Issue by mohamedamr987** [singerdmx/flutter-quill#909]
https://github.com/singerdmx/flutter-quill/blob/b8ebcbdbda2191a059b42ce6f6e438b5ab347b47/lib/src/models/documents/document.dart#L349

I don't know why toPlainText() have a line break at the, if modified it would it affect any thing ?

**Comment by singerdmx** [comment]
I think it will break a lot of things

**Comment by mohamedamr987** [comment]
alright, thanks for replying.
