### ISSUE TITLE
[Mobile] "\n" creates extra space under text lines

### ISSUE THREAD

**Issue by bytes7bytes7** [singerdmx/flutter-quill#914]
I try to parse this doc:
```
[{"insert":"Flutter Quill\n\n\n\n\n\n\n\n\n\n\n\n"},{"insert":"Flutter Quill\n"},{"insert":"Flutter Quill"},{"insert": "\n"}]
```
And I noticed, that "\n" creates some extra space after lines (you can notice that on the screenshot... guidelines end after 3rd "Flutter Quill", so there is nothing underneath, but why there is an extra space?)

![fq](https://user-images.githubusercontent.com/74134786/184954316-4e9b5dab-9cd9-4ed6-9076-d9e3f9d4bc68.png)

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
