### ISSUE TITLE
[Mobile] Is there any way to make a parameter like onChanged in textfield for use?

### ISSUE THREAD

**Issue by qwer122120043** [singerdmx/flutter-quill#915]
My issue is about [Mobile]

Is there any way to make a parameter like onChanged in textfield for use? thank you very much

**Comment by TrAndRS** [comment]
QuillController's onReplaceText and onSelectionChanged can help

**Comment by MagTuxGit** [comment]
QuillController's onReplaceText and onSelectionChanged can help

**Comment by qwer122120043** [comment]
@MagTuxGit 

In my project, I treat a quillEditor as a paragraph. At the beginning, there is only one paragraph. As long as there is an input word, a new paragraph will be added. If one of the paragraphs is emptied, the paragraph will be deleted.

The method I thought of is to add a new paragraph after checking the last paragraph in the paragraph list in onChanged, so I need to use the onChanged parameter. I don't know how to use onReplaceText and onSelectionChanged correctly in this project?

I translated it with google, please forgive me if it is impolite or the sentence is not smooth, thank you for your reply!

**Comment by MagTuxGit** [comment]
``` dart
    final quillController = QuillController(
      ...
      onReplaceText: (int index, int length, Object? data) {
          // something changed at position index with length. data should be String.
      },
      onSelectionChanged: (TextSelection selection) {
          // new selection set
      },
    );

    final quillEditor = QuillEditor(
      controller: quillController,
      ...
     );
```

**Comment by lordofkawaiii** [comment]
I used onReplaceText to discard some characters by returning 'false' as mentioned in the doc
but the index still grow, making an error (not in range) when I type valid character after typing a not valid one. I must change the selection to avoid it.

```
onReplaceText: (index, len, data) {
          if (data == '\n') {
            return false;
          } else {
            return true;
          }
        },
```
