### ISSUE TITLE
[Mobile] Can Quill open up UI customization? For example, toolbar, use widget instead of IconData, IconData is not very flexible.

### ISSUE THREAD

**Issue by SimbAforGit** [singerdmx/flutter-quill#922]
My issue is about [Mobile]

Can Quill open up UI customization? For example, toolbar, use widget instead of IconData, IconData is not very flexible.

**Comment by singerdmx** [comment]
I don't encourage using or will support any custom feature or functionality. I encourage you to submit PR to merge any so-called custom feature or functionality to this repo here so everyone can benefit from it.

**Comment by freshtechtips** [comment]
> I don't encourage using or will support any custom feature or functionality. I encourage you to submit PR to merge any so-called custom feature or functionality to this repo here so everyone can benefit from it.

Actually it's a good idea, only if I see this before refactoring the code

but we did add childBuilder anyway to show custom widget

This issue has been fixed, if you still facing this issue or any others, feel free to contact us on GitHub
