### ISSUE TITLE
Gboard autocomplete causes double cursor

### ISSUE THREAD

**Issue by LogicNg** [singerdmx/flutter-quill#928]
For Android devices that use Gboard (by far the most popular keyboard on Android), if you autocomplete the last word of the line and hit enter, the cursor on the last line won't hide correctly, and it causes double cursor. For other keyboard such as Microsoft SwiftKey, this problem does not exist.

This is likely due to the fact that Gboard insert white space after every word it autocompletes. If the last word of the line is auto-completed, when user press the enter button, it replace spalce to line feed. For Microsoft SwiftKey, it just inserts line feed after the space.

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
