### ISSUE TITLE
dependencies path_provider error in release

### ISSUE THREAD

**Issue by wesleytoshio** [singerdmx/flutter-quill#93]
hello, my project is using **path_provider: ^2.0.1** and I noticed that **flutter_quill: ^1.0.9** also uses this version, so I removed path_**provider: ^2.0.1** and I'm using path_provider through the dependencies of flutter_quill , right?
When I try to use the following code
**final appDocumentDir = await getApplicationDocumentsDirectory ();**
 print (appDocumentDir.path);
when I run the command **flutter run --release** I get this error:

E / flutter (32146): [ERROR: flutter / lib / ui / ui_dart_state.cc (186)] Unhandled Exception: MissingPluginException (No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E / flutter (32146): # 0 MethodChannel._invokeMethod (package: flutter / src / services / platform_channel.dart: 156)
E / flutter (32146): <asynchronous suspension>
E / flutter (32146): # 1 getApplicationDocumentsDirectory (package: path_provider / path_provider.dart: 139)
E / flutter (32146): <asynchronous suspension>
E / flutter (32146): # 2 main (package: my_notes / main.dart: 10)

this error happens when I try to use the path_provider dependency of the flutter_quill itself ... when I remove the flutter_quill from the project and install path_provider: ^ 2.0.1 everything works fine.

PS W: \ flutter \ my_notes> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [version 10.0.18363.1440], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.54.3)
[√] Connected device (3 available)

sorry for the bad english.

**Comment by singerdmx** [comment]
check out https://github.com/singerdmx/flutter-quill/issues/76

You should go to flutter community for this. e.g. flutter/flutter#77458

**Comment by wesleytoshio** [comment]
even adding in **dependency_overrides** the error continues when using flutter_quill, if I remove it, everything works fine

dependency_overrides:
path_provider: ^2.0.1
