### ISSUE TITLE
High dependency count

### ISSUE THREAD

**Issue by Jon-Salmon** [singerdmx/flutter-quill#930]
Firstly thank you very much for this plugin, it is awesome!

The embedded blocks are great features, but supporting them does add a significant overhead to the app (>2mb in android apk size and ~20 dependencies). It would be nice to have a way to reduce this overhead for apps that don't need these advanced features, but I'm aware this is easier said than done (and would be a major breaking change).

My proposal for this would be:
- Split the plugin into two plugins, a 'core' package and a 'embeds' package
- To use the full-featured option, a user would have to either add an extra parameter to their use of quill to load the extra widgets, or maybe there could be a static global method of loading the extra widgets on app startup.

I am very happy to perform such a refactor and submit a pull request, but wanted to check if this was something you were interested in supporting @singerdmx before I committed too much time to this as it would be a breaking change.

**Comment by singerdmx** [comment]
Does it mean we need to publish two packages in https://pub.dev/ ?

**Comment by Jon-Salmon** [comment]
Yes, that would unfortunately be required.

**Comment by singerdmx** [comment]
This kind of things have been discussed.
But it seems not an ideal solution

**Comment by singerdmx** [comment]
That being said, moving embed stuff to example and just asking users to copy/paste code may be a better solution than maintaining two packages.

**Comment by singerdmx** [comment]
Let's start with something small.
First separate the code of `embed` into a standalone folder.
Then we decide if this folder should go to the example or a different package.

**Comment by Jon-Salmon** [comment]
Ok, I'll have a crack at that and open a PR shortly

**Comment by singerdmx** [comment]
![image (3)](https://user-images.githubusercontent.com/122956/187790641-37642a4a-22b4-4bb7-b890-9036f995927c.png)
Here is the old thought. The right side box is the `core`

**Comment by singerdmx** [comment]
So instead of one example folder, we are going to have 3.
I prefer to keep current example folder for mobile.

**Comment by singerdmx** [comment]
Main idea is still keeping one package. 
Users can refer to the folder to do whatever.

**Comment by Jon-Salmon** [comment]
The only issue with that is that either the user would then have to add all the dependencies for images, videos etc themselves, or otherwise we would be back where we started with the bloat.

My original proposal would end up with a repo structure similar to this, with only the one example folder:

repo/
├─ flutter_quill/
│  ├─ lib/
│  ├─ example/
├─ flutter_quill_extensions/
│  ├─ lib/

**Comment by singerdmx** [comment]
repo/
├─ lib/
├─ example/
├─ flutter_quill_extensions/
│ ├─ lib/

For now, do not have flutter_quill as extra layer

**Comment by Jon-Salmon** [comment]
I've created a proposal in PR #933, let me know what you think. I haven't fully tested or updated the readme yet.

**Comment by singerdmx** [comment]
Generally looks good.
Need to update the main README for this big change

**Comment by singerdmx** [comment]
Also I wonder if you will do the honor to maintain the second package.

**Comment by Jon-Salmon** [comment]
I'm happy to act as maintainer of the second package. I probably won't be spending much time on adding functionality to the embed objects (my app explicitly doesn't support them), but very happy to do general maintenance as required. How would you envision this working, will it stay in this repository or would you rather it be moved out? Are you happy with it published to pub.dev via your org or mine?

**Comment by singerdmx** [comment]
So the code should stay here in one github repo.
As for the package, it goes to pub.dev via your org. But you will have a duty that whenever there is a change in extension you need to bump the version.

**Comment by Jon-Salmon** [comment]
I've submitted PR #934, let me know once you are happy and I'll publish the second package to pub.dev

**Comment by singerdmx** [comment]
Looks good

**Comment by Jon-Salmon** [comment]
Package is live here: https://pub.dev/packages/flutter_quill_extensions

Let me know if you want me to add a link to the readme or if you are happy doing so.

**Comment by singerdmx** [comment]
Please go ahead

**Comment by Jon-Salmon** [comment]
Many thanks!

**Comment by singerdmx** [comment]
So just FYI: the original intention is to split fluter_quill_extensions into three as web, desktop and mobile. We will see.
