### ISSUE TITLE
[Mobile] CJK style problem

### ISSUE THREAD

**Issue by yeonsang-An** [singerdmx/flutter-quill#937]
My issue is about [Mobile]
Hi.

If you try to start writing after applying a style in CJK, the applied style will be released. It is thought to occur only in CJK characters. There is no problem with applying styles after specifying selection.

![Sep-06-2022 12-52-47](https://user-images.githubusercontent.com/75961262/188543516-de726edf-159b-4333-a9a6-a7bdab53b962.gif)

I using `QuillController.formatSelection`. Is any other way to solve this problem? Thank you.

flutter_quill: ^6.0.0
flutter: ^3.0.5

**Comment by bugrevealingbme** [comment]
It's irrelevant. I need page with such functionality. Can you share? @yeonsang-An

**Comment by suntianjun** [comment]
when the cursor is in somewhere, toolbar should show the next text's style, but not the current style. 
I think this reason cause the CJK problem.

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
