### ISSUE TITLE
[Web] [Mobile]  [Desktop] Add Quote Direction & Add layout

### ISSUE THREAD

**Issue by mstfkhazaal** [singerdmx/flutter-quill#947]
Please Add Quote Direction (RTL/LTR) & Layouts like Columns, Grids...

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
