### ISSUE TITLE
How to create a rich text editor that returns html results in Flutter?

### ISSUE THREAD

**Issue by mycar98765** [singerdmx/flutter-quill#949]
My goal is to create a rich text editor that returns html results. I am using the package [`flutter_quill`][1]. It can only [return plain text using `_controller.document.toPlainText()` and json using `_controller.document.toDelta().toJson()`][2]. Are there any other rich text editors that can return html results or any way to return html results in [`flutter_quill`][1]? Appreciate if someone can advise. Thank you in advance!

  [1]: https://pub.dev/packages/flutter_quill
  [2]: https://pub.dev/packages/flutter_quill#input--output
  [3]: https://pub.dev/packages/html_editor_enhanced

**Comment by mycar98765** [comment]
I finally found a solution!

I am using the following code to return html results:

    final convertedValue = jsonEncode(delta.toJson());
    final markdown = deltaToMarkdown(convertedValue);
    final html = markdownToHtml(markdown);

**Comment by dragongesa** [comment]
what library to use deltaToMarkdown and so?

**Comment by dsyrstad** [comment]
@mycar98765 @dragongesa https://pub.dev/packages/vsc_quill_delta_to_html provides a robust delta to HTML conversion.
