### ISSUE TITLE
Is there any image button in flutter_quill toolbar in web?

### ISSUE THREAD

**Issue by mycar98765** [singerdmx/flutter-quill#952]
Is there any image button in [`flutter_quill`][1] toolbar in web?

When I read the [`flutter_quill`][1] package readme, I see that there is an image button in the [`flutter_quill`][1] toolbar in Android, as shown in the image below:

[![image][2]][2]

However, in the app I run via `web (Chrome)`, there is no image button in the [`flutter_quill`][1] toolbar, as shown in the image below:

[![image][3]][3]

Where is the image button? Is it because of the different versions, or do I need to add the image button myself, or something else.

Appreciate if someone can advise. Thank you in advance!

  [1]: https://pub.dev/packages/flutter_quill
  [2]: https://i.stack.imgur.com/C29LL.png
  [3]: https://i.stack.imgur.com/9Cb7d.png

**Comment by singerdmx** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/122956/190551750-2a302791-4820-4fce-a1ad-f949432a9bfe.png">

**Comment by mycar98765** [comment]
@singerdmx, I tried it before. When I select the image it doesn't change anything.

**Comment by freshtechtips** [comment]
This issue has been fixed, if you still facing this issue or any others, feel free to contact us on GitHub
