### ISSUE TITLE
[Desktop] Editor loses focus when toolbar buttons are pressed.

### ISSUE THREAD

**Issue by Blquinn** [singerdmx/flutter-quill#955]
I experienced this on desktop, it may be the same for web. Current master a855f59922a8efef1d654a23ea1d325e8f587eda

Title pretty much says it. Whenever a toolbar button is pressed, the editor loses focus. This makes to so that if you click bold, for example, the cursor is lost and you need to click back into the editor to recover it. When you do click the editor, the active text is no longer bolded. (This is when there is no selection.)

> Flutter 3.3.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision ffccd96b62 (3 weeks ago) • 2022-08-29 17:28:57 -0700
> Engine • revision 5e9e0e0aa8
> Tools • Dart 2.18.0 • DevTools 2.15.0

**Comment by Blquinn** [comment]
Closing this since, this can now be sovled by requesting focus in the afterButtonPressed callback of the editor.

**Comment by hcanyz** [comment]
Possibly a better solution: set ```onTapOutside``` to ```QuillEditorConfigurations``` to manually control focus.

The focus thief is ```QuillRawEditorState``` ```_defaultOnTapOutside```

**Comment by maelchiotti** [comment]
> Possibly a better solution: set `onTapOutside` to `QuillEditorConfigurations` to manually control focus.
> 
> The focus thief is `QuillRawEditorState` `_defaultOnTapOutside`

Hi, I have this issue, can you show how you would do that? I don't understand what you exactly mean by "manually control focus". Thanks

**Comment by hcanyz** [comment]
@maelchiotti, this can be done

```
    QuillEditor.basic(
      focusNode: _focusNode,
      configurations: QuillEditorConfigurations(
        controller: _quillController,
        onTapOutside: (_, __) {
          // _focusNode.unfocus(); or doNothing
        },
      ),
    )
```
If ```onTapOutside``` is set then ```QuillEditor``` will not control focus. We can control it ourselves through ```_focusNode```.

**Comment by md-rifatkhan** [comment]
@hcanyz this doesn't work when toolbar button is pressed
