### ISSUE TITLE
There will be problems when adding Chinese

### ISSUE THREAD

**Issue by dyshero** [singerdmx/flutter-quill#957]
When I add Chinese, the style is invalid, but when I add English, there is no problem.
[http://rh23rtn62.hn-bkt.clouddn.com/screen.mov](url)

**Comment by yeonsang-An** [comment]
same here https://github.com/singerdmx/flutter-quill/issues/937

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
