### ISSUE TITLE
[Mobile] TextInputClient.showAutocorrectionPromptRect: UnimplementedError

### ISSUE THREAD

**Issue by bugrevealingbme** [singerdmx/flutter-quill#958]
My issue is about [Mobile]

════════ Exception caught by services library ══════════════════════════════════
The following UnimplementedError was thrown during method call TextInputClient.showAutocorrectionPromptRect:
UnimplementedError

When the exception was thrown, this was the stack
#0      RawEditorStateTextInputClientMixin.showAutocorrectionPromptRect
#1      TextInput._handleTextInputInvocation
#2      TextInput._loudlyHandleTextInputInvocation
#3      MethodChannel._handleAsMethodCall
#4      MethodChannel.setMethodCallHandler.<anonymous closure>
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#6      _invoke2 (dart:ui/hooks.dart:186:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
call: MethodCall(TextInputClient.showAutocorrectionPromptRect, [16, 17, 23])
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
UnimplementedError
════════════════════════════════════════════════════════════════════════════════

I don't know where the problem is coming from, I just put Quill normally. Older versions did not have this error.

**Comment by sigpoggy** [comment]
I am also getting this using the example app (in the current version) without modification. It occurs when entering text in edit mode.

**Comment by lh9403** [comment]
The same problem, the latest version

**Comment by tanzilzubair** [comment]
Same problem, using the latest version of Flutter Quill

**Comment by Allenxuxu** [comment]
Same problem, using 5.0.1

**Comment by SApolinario** [comment]
Any updates on this?  Is this expected and do we simply ignore it?  Thanks.

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
