### ISSUE TITLE
A problem with Japanese

### ISSUE THREAD

**Issue by hoanganhsong1** [singerdmx/flutter-quill#965]
Hi, Thank you so much for the plugin. It is really helpful for me.
I have a problem. I am using this plugin for Japanese. The problem is when I entered Japanese. After that, I want to edit the text at some positions. I touched at that position, but the cursor could not move to that position. The error only happens with Japanese. Other languages such as English are Ok. 
Please help me.

**Comment by singerdmx** [comment]
You are welcome to submit a PR to fix it

**Comment by hoanganhsong1** [comment]
> 

I am sorry. I don't understand PR. Could you explain in detail?

**Comment by hoanganhsong1** [comment]
> You are welcome to submit a PR to fix it

Could you give me a short guide about this problem?

**Comment by yeonsang-An** [comment]
I think same issue here https://github.com/singerdmx/flutter-quill/issues/937

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
