### ISSUE TITLE
Longpress-link-popup in edit mode is not following dark mode

### ISSUE THREAD

**Issue by tschiekdev** [singerdmx/flutter-quill#968]
Please see screenshot.

When long press on the link it shows a popup, which is white instead dark under dark mode.

![193395516-899860f9-fe08-4c33-adbe-c78b290fe88e](https://user-images.githubusercontent.com/11464255/193399974-136f9d12-fe1f-409d-9586-ea9a9e386506.jpg)

**Comment by freshtechtips** [comment]
This issue has been fixed

Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
