### ISSUE TITLE
[Mobile] Add a CustomBlockEmbed,but cursor auto move to end of row

### ISSUE THREAD

**Issue by newstrong** [singerdmx/flutter-quill#969]
flutter_quill: 6.0.6+1 
Flutter SDK version: 3.3.1

My issue is:when i add a customblock embed in a empty row ,then the cursor auto move to end of row.if i input some word,the cursor move back the end of the customblock embed.

https://user-images.githubusercontent.com/6466414/193455225-395d9f0d-4d92-459a-8482-d7cbb430cd3c.mp4

Please tell me how can i resolve this.

**Comment by LWFLBB** [comment]
The problem is here
<img width="1083" alt="截屏2022-10-04 15 07 31" src="https://user-images.githubusercontent.com/16347796/193756736-deafc15c-4c22-4913-889a-536105f87114.png">

**Comment by newstrong** [comment]
> The problem is here <img alt="截屏2022-10-04 15 07 31" width="1083" src="https://user-images.githubusercontent.com/16347796/193756736-deafc15c-4c22-4913-889a-536105f87114.png">

tks your answer
