### ISSUE TITLE
Insert link via controller

### ISSUE THREAD

**Issue by pramod51** [singerdmx/flutter-quill#970]
How can i insert through quillController....
I want to insert link manually.

**Comment by MohammedSalehelShazly** [comment]
any questions...

**Comment by pramod51** [comment]
No

**Comment by pramod51** [comment]
`
// insert hyper link to textEditor
  void _linkSubmitted(Tuple2 value) {
    // text.isNotEmpty && link.isNotEmpty
    final String text = value.item1;
    final String link = value.item2.trim();
    var index = quillController.selection.start;
    var length = quillController.selection.end - index;
    if (_getLinkAttributeValue() != null) {
      // text should be the link's corresponding text, not selection
      final leaf = quillController.document.querySegmentLeafNode(index).item2;
      if (leaf != null) {
        final range = getLinkRange(leaf);
        index = range.start;
        length = range.end - range.start;
      }
    }
    quillController.replaceText(index, length, text, null);
    quillController.formatText(index, text.length, LinkAttribute(link));
    quillController.moveCursorToPosition(index + text.length);
  }

  String? _getLinkAttributeValue() {
    return quillController
        .getSelectionStyle()
        .attributes[Attribute.link.key]
        ?.value;
  }

  TextRange getLinkRange(Leaf node) {
    var start = node.documentOffset;
    var length = node.length;
    var prev = node.previous;
    final linkAttr = node.style.attributes[Attribute.link.key]!;
    while (prev != null) {
      if (prev.style.attributes[Attribute.link.key] == linkAttr) {
        start = prev.documentOffset;
        length += prev.length;
        prev = prev.previous;
      } else {
        break;
      }
    }
    var next = node.next;
    while (next != null) {
      if (next.style.attributes[Attribute.link.key] == linkAttr) {
        length += next.length;
        next = next.next;
      } else {
        break;
      }
    }
    return TextRange(start: start, end: start + length);
  }`
