### ISSUE TITLE
[Mobile] The editor with placeholder throws an exception when onTapUp  was called 

### ISSUE THREAD

**Issue by guoz2013** [singerdmx/flutter-quill#975]
Source code here:
```
 ChildQuery queryChild(int offset) {
    // TODO: prevent user from moving caret after last line-break.
    final res = _root.queryChild(offset, true);
    if (res.node is Line) {
      return res;
    }
    final block = res.node as Block;
    return block.queryChild(res.offset, true);
  }
```

If I input nothing ,the res.node will be null, so it throws an exception when cast to Block,
```
the following _CastError was thrown while handling a gesture:
type 'Null' is not a subtype of type 'Block' in type cast
```

**Comment by freshtechtips** [comment]
Thank you for the report, if you still facing the issue can you tell us more details about how to encounter the issue?

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
