### ISSUE TITLE
ToggleStyleButtonBuilder incorrect parameter

### ISSUE THREAD

**Issue by diegogarciar** [singerdmx/flutter-quill#98]
Hello, it seems that ToggleStyleButtonBuilder has parameter `bool? isToggled` as nullable

then at the `defaultToggleStyleButtonBuilder` you choose colors as so
```
 final iconColor = isEnabled
      ? isToggled != null  ? theme.primaryIconTheme.color
          : theme.iconTheme.color
      : theme.disabledColor;
```

What I found is that isToggle is never null and the first color is always chosen.

My suggestion is to make isToggled as bool (not bool?) and change the color choosing to a simple bool check, In case there's a scenario where isToggle can be null, just default it to false or true

**Comment by singerdmx** [comment]
Check out https://github.com/singerdmx/flutter-quill/commit/4ac00bd912b982dec50e58df5abc95503fce9225

Contact @theacheng if it has issue

**Comment by singerdmx** [comment]
check https://github.com/singerdmx/flutter-quill/pull/97

you can also contact @friebetill

**Comment by diegogarciar** [comment]
Thanks it seems it will be fixed soon!
