### ISSUE TITLE
TextSelectionTheme issue

### ISSUE THREAD

**Issue by sunnykinger** [singerdmx/flutter-quill#987]
I was facing the issue when I used to select the text and text was highlighted with defined color in TextSelectionTheme. The problem was that I was not able to see the text, just the highlight was visible. 

I have applied textSelectionTheme to example application of flutter-quill and even there this issue appeared. 
In the main.dart, under MaterialApp-> ThemeData, added this code
 ```
textSelectionTheme: TextSelectionThemeData(
          cursorColor: Colors.blue,
          selectionHandleColor: Colors.orange,
          selectionColor: Colors.indigo.shade600,
        )
```

Result is here
![2022-10-27 15 30 30](https://user-images.githubusercontent.com/6624048/198255183-5ed430a4-9a03-4b0f-9d72-ee8e43212ae8.jpg)

**Comment by freshtechtips** [comment]
This issue has been fixed, if you still facing this issue or any others, feel free to contact us on GitHub

**Comment by fdemiguel** [comment]
@EchoEllet It happens again in version 11.5.0. It also happened in 11.4.2. In my case, I am working in Flutter Web.

<img width="920" height="125" alt="Image" src="https://github.com/user-attachments/assets/3e857016-0567-41dc-99af-da555bef8f3f" />
