### ISSUE TITLE
[Mobile] Thrown error in inappwebview when install the flutter_quill_extension

### ISSUE THREAD

**Issue by SuryaChinnadurai1997** [singerdmx/flutter-quill#989]
I tried to add flutter quill extension. But i'm facing the below issue:

**Exception**

C:\Users\Surya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_inappwebview_quill-5.4.6\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:280: error: cannot find symbol
      settings.setAppCachePath(options.appCachePath);
              ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
C:\Users\Surya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_inappwebview_quill-5.4.6\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:494: error: cannot find symbol
      settings.setAppCacheEnabled(false);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
C:\Users\Surya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_inappwebview_quill-5.4.6\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:504: error: cannot find symbol
      settings.setAppCacheEnabled(true);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
C:\Users\Surya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_inappwebview_quill-5.4.6\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:515: error: cannot find symbol
        settings.setAppCachePath(ctx.getCacheDir().getAbsolutePath());
                ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
C:\Users\Surya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_inappwebview_quill-5.4.6\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:517: error: cannot find symbol
        settings.setAppCacheEnabled(true);
                ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
C:\Users\Surya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_inappwebview_quill-5.4.6\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:521: error: cannot find symbol
      settings.setAppCacheEnabled(false);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
C:\Users\Surya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_inappwebview_quill-5.4.6\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:767: error: cannot find symbol
      settings.setAppCachePath(newOptions.appCachePath);
              ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_inappwebview_quill:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 28s
Exception: Gradle task assembleDebug failed with exit code 1

**Code snippet**

```
QuillEditor(
            controller: _controller,
            scrollController: ScrollController(),
            scrollable: true,
            autoFocus: false,
            showCursor: false,
            expands: false,
            floatingCursorDisabled: true,
            focusNode: _focusNode,
            padding: EdgeInsets.zero,
            readOnly: true,
            embedBuilders: FlutterQuillEmbeds.builders(),
          ),
        )
```

**Flutter version:**
Flutter 3.3.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6928314d50 (4 days ago) • 2022-10-25 16:34:41 -0400
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0

**dependencies:**
  dio: ^4.0.4
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  image_picker: ^0.8.4+11
  webview_flutter: ^3.0.2
  flutter_quill: ^6.1.1
  flutter_quill_extensions: ^0.1.0

Please let me know how to fix that issue

**Comment by PascalGehring** [comment]
Experiencing the same issue...

**Comment by GP-Y** [comment]
我也遇到了这个问题，我把flutter_inappwebview_quill换成flutter_inappwebview解决了这个问题

**Comment by singerdmx** [comment]
```
dependency_overrides:
  url_launcher: ^6.1.2
  http_parser: ">=4.0.0"
  plugin_platform_interface: ">=2.0.0"
  xml: ^5.0.0
  analyzer: ^3.0.0
  math_keyboard: ^0.1.6
  flutter_math_fork: ^0.6.3+1
  flutter_svg: ^1.1.6
  flutter_quill_extensions:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      path: flutter_quill_extensions
```
