### ISSUE TITLE
[Mobile] No cursor is showing after typing

### ISSUE THREAD

**Issue by mikron123** [singerdmx/flutter-quill#990]
Issue using Android (both physical and emulator)

The cursor is simply disappearing after I start typing as shown in the attached video clip.  
It happens since I'm calling setState when that text is changing, since I need to manipulate the layout when a specific text change happened.

```
_quillController.addListener(() {
 setState(() {});
}
```

The users can't know where they are, which is of course annoying.
How do I work around it?

https://user-images.githubusercontent.com/16115860/198979384-7333162d-c35b-4db8-9059-f7febe08f1f3.mp4

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
