### ISSUE TITLE
 [Mobile]  problem copying and pasting text with formatting

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#991]
i am using flutter 3.3.6
when copying text with formatting but in the middle of it there is a blank line, it confuses the styles, (from what I have verified it cannot count the blank spaces in a new line that has nothing written when it is in the middle of the text)

https://user-images.githubusercontent.com/22117346/199243890-081ccea3-bcf1-4a00-a2d2-40e5592322c7.mp4

**Comment by Taherpats** [comment]
Any updates on this??

**Comment by ellet0** [comment]
> Any updates on this??

You can try it now

**Comment by ellet0** [comment]
> i am using flutter 3.3.6 when copying text with formatting but in the middle of it there is a blank line, it confuses the styles, (from what I have verified it cannot count the blank spaces in a new line that has nothing written when it is in the middle of the text)
> 
>  tentando-copiar_uQGnVfHY.mp4

Hi, can you confirm if the issue still the exist?

**Comment by AtlasAutocode** [comment]
This has been fixed in a recent update.
If this is still an issue, please reopen and give us details on what is still not fixed.
