### ISSUE TITLE
[Mobile]  it is impossible to place the cursor inside the written text that has  colored background

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#992]
flutter 3.3.6

When writing text on a colored background, it is impossible to place the cursor inside the written text, I can write but the cursor does not appear

https://user-images.githubusercontent.com/22117346/199244689-758780da-5e69-48a9-87a4-c61437ca2a7c.mp4

**Comment by raulmabe** [comment]
In my case it happens to every word, not only background colored

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
